### ISSUE TITLE
Generování RSA klíčů offline

### ISSUE THREAD

**Issue by petrkutalek** [csob/paymentgateway#1]
Je možné dvojici asymetrických klíčů vygenerovat offline a do systému pak jen veřejný klíč zaregistrovat? 

Vzhledem k tomu, že https://iplatebnibrana.csob.cz/keygen generuje RSA klíče, působilo by na mne mnohem důvěryhodněji, bylo-li by možné klíče vygenerovat klasickou cestou přes 

```
openssl genrsa -out private.pem 2048
openssl rsa -in private.pem -outform pem -pubout -out public.pem
```

(podle libosti) a následně jen veřejný klíč obchodníka zaregistrovat. Přeci jen, kdykoli mi někdo nabízí, že mi vygeneruje privátní klíč za mne, mám pochybnosti.

**Comment by dmarek** [comment]
Dobrý den,

Aktuálně to možné není.

Stávající řešení je založeno na generování klíčů v prostředí prohlížeče pomocí javascriptové knihovny *jsencrypt*, z tohoto pohledu se jedná o proces spuštěný na lokálním počítači uživatele. 
Privátní klíč ukládá uživatel aplikace na disk lokálního počítače, aplikace neprovádí žádné další operace s privátním klíčem (odesílání přes síť apod).

Tím, že se jedná o webovou aplikaci, jsou samozřejmě zdrojové kódy generátoru klíčů dostupné na https://platebnibrana.csob.cz/keygen/, (obdobně pro generátor klíčů pro integrační prostředí běžící na adrese https://iplatebnibrana.csob.cz/keygen/). 

Hlavní logika je soustředěna v následujících souborech:
https://platebnibrana.csob.cz/keygen/js/javascript.js
https://platebnibrana.csob.cz/keygen/js/libs/jsencrypt/jsencrypt.js

Cílem bylo nabídnout uživatelům bezpečný a snadno dostupný způsob jak generování klíčů, tak distribuce veřejného klíče na server platební brány ČSOB bez nutnosti instalovat na počítači uživatele potřebný SW. 

Chápu, že z Vašeho pohledu to není totéž jako „offline“ vygenerování přes *openssl*, které z pohledu instalované verze, zdrojových kódů apod. máte pod větší kontrolou. 
Váš požadavek nicméně neskončí v koši, zařadili jsme jej do plánovaných vylepšení platební brány ČSOB. V budoucnu bude tedy možné použít jak stávající generátor klíčů, tak možnost generování klíčů offline a odeslání public klíče na server.

S pozdravem

Daniel Marek

**Comment by ratajskym** [comment]
Dobrý den, platební brána již umožňuje upload vašeho vlastního veřejného klíče.

**Comment by petrkutalek** [comment]
Dobrá práce, Martine! 👍 @ratajskym

**Comment by ratajskym** [comment]
Děkuji @petrkutalek,

nicméně pochvala jde spíše za vývojovým týmem než za mnou
