### ISSUE TITLE
Certifikáty

### ISSUE THREAD

**Issue by Mickejus** [csob/paymentgateway#10]
Majitel e-shopu se na mě obrátil s žádostí o integraci platební brány na e-shop na http://www.atomer.com/.

Tam v dokumentaci k napojení GP webpay vyžadují (kromě jiného): 
- Certifikát produkčního systému
- Certifikát testovacího systému
- Privátní certifikát
- Klíč

K certifikátům na helpu tvrdí, že je dodá banka v implementačním balíčku buď jako soubory s příponou pem, nebo jako generátor, který soubory vygeneruje.

Ke klíči tam tvrdí, že jde o klíč nebo heslo, které obchodník obdržel od banky.

Bohužel majitel mi tvrdí, že žádné certifikáty ani implementační balíček ani klíč nebodržel. Pouze odkaz na generátor privátního a veřejného klíče, které mi atomer nebere s hláškou, že nemají správný formát.

Prosím tedy o informaci, zda majitel e-shopu měl skutečně něco od banky obdržet (certifikáty/implementační balíček), nebo jestli je nějaká nová verze platební brány, na kterou atomer nereflektoval a případně neaktualizoval integrační rozhraní, případně zda mi něco uniká.

Děkuji

**Comment by dmarek** [comment]
V tomto případě se prosím obraťte na provozovatele platformy atomer s žádostí o integraci na novou platební bránu ČSOB (https://platebnibrana.csob.cz). 

Stavající modul na atomer.com aktuálně umožňuje kromě jiných platebních metod integraci na platební bránu GP Webpay, přičemž např. není možné změnit URL, provádí se validace na použitý certifikát apod. Není tedy možné stávající modul použít pro napojení na novou platební bránu ČSOB.

**Comment by ratajskym** [comment]
@Mickejus 
Dobrý den, posunuli jste se v implementaci dál ?
