### ISSUE TITLE
Ukončení práce v integračním prostředí

### ISSUE THREAD

**Issue by fiorita** [csob/paymentgateway#100]
Dobrý den,

V prvním e-mailu ohledně implementace platební brány je odkaz na stránku

https://iposman.iplatebnibrana.csob.cz/posmerchant

... kam mám jít po zkoušení brány. Ta stránka však žádá po mně uživatelské jméno a heslo. Jaké jménotam mám uvést? Jinak testování proběhlo ok

Díky a s pozdravem,
Kirill Gorbunov

**Comment by ratajskym** [comment]
Dobrý den, 

přihlašovací údaje jste obdržel od banky při podepsání smlouvy. Pokud používáte pouze anonymní účet, pak není přihlášení do aplikace Posmerchant možné.

**Comment by fiorita** [comment]
Díky moc za odpověď, to tedy najdeme
