### ISSUE TITLE
Částečné vracení prostředků před zaúčtováním

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#101]
Pokud je platba ve stavu 4, je možné provést částečné storno voláním close s parametrem totalAmount
Pokud je platba ve stavu 8, je možné použít refund

Dá se provést částečné vrácení prostředků pokud je platba ve stavu 7?

**Comment by dmarek** [comment]
Pokud je platba ve stavu 7 (zařazena do zúčtování), nelze provést vrácení prostředků. Je potřeba počkat až se zúčtuje a bude ve stavu 8. Platbu ve stavu 7 lze celou pouze reverzovat.
