### ISSUE TITLE
WooCommerce různé měny a jazyky

### ISSUE THREAD

**Issue by Musilda** [csob/paymentgateway#102]
Mám dotaz, ohledně změny měny, při provádění platby. 
Pokud má jazyk EN a Měnu USD, vše proběhne korektně. 
V případě, že cokoliv změním, nedojde k přesměrování na platební bránu. 

Je to nějakým způsobem kontrolováno, jaká měna se odesílá? Protože, pokud je lang CZ a currency CZK, tak se to jen přesměruje zpět na pokladnu.

**Comment by Musilda** [comment]
Tak jsem nakonec přišel, že je problém, zřejmě v url. Mám na eshopu 5 jazyků, CZ, EN, DE, SK a PL. 
Pokud mám vybraný jazyk EN, v url je http://obchod.cz/?lang=en a vše proběhne v pořádku, i měna se mění, tak jak vyberu. 

Problém je, při výběru jiného jazyka, například http://obchod.cz/?lang=de, tak nedojde k přesměrování na bránu.

Díky za pomoc.

**Comment by ratajskym** [comment]
Dobrý den, přesměrování přece provádí Váš eshop. Proč tedy nedojde k přesměrování netuším.

**Comment by Musilda** [comment]
Přesměrování provádí eshop, to ano, ale pomocí vámi vytvořeného pluginu pro WooCommerce. A proto se ptám, zda je možné, že nějakým způsobem ten plugin není schopen přesměrovat na platební bránu, pokud plugin WPML mění url v závislosti na zvoleném jazyce, kdy pro každý jazyk přidává do url ?lang=kod_jazyka. 

Děkuji za odpověď.

**Comment by Musilda** [comment]
Vyřešeno, problémem byl plugin WPML, který nesprávně zaregistroval string endpointu order-pay.
Stačilo v Theme and plugins localization, znovu proskenovat WooCommerce, přeložit string a vymazat ten prázdný.
