### ISSUE TITLE
Požadovaná platba bohužel neexistuje, nebo vypršela platnost požadavku

### ISSUE THREAD

**Issue by michalsanger** [csob/paymentgateway#104]
Ačkoliv mi `payment/status` vrátí:
```
{
	"dttm": "20151216150918",
	"signature": "...",
	"payId": "24e366782412fAL",
	"resultCode": 0,
	"resultMessage": "OK",
	"paymentStatus": 1
}
```

a následný `payment/process` (`https://iapi.iplatebnibrana.csob.cz/api/v1.5/payment/process/A14717Jgqg/24e366782412fAL/20151216150729/...`) přesměruje na `https://iplatebnibrana.csob.cz/pay/shop.example.com/....` tak se dozvím že:
> **Platba nenalezena**
> Požadovaná platba bohužel neexistuje, nebo vypršela platnost požadavku. Pokoušíte-li se zaplatit objednávku, vraťte se prosím na stránky obchodníka a zaplaťte prosím znovu.

Nevíte kde může být problém?
```
Merchant Id: A14717Jgqg
Pay Id: 24e366782412fAL
```

**Comment by rudolfdobias** [comment]
+1

**Comment by HonzaMac** [comment]
:+1:

**Comment by jiripsota** [comment]
+1

**Comment by ratajskym** [comment]
Dobrý den, 

dokážete tohle kdykoliv nasimulovat? Z logu se zdá všechno v pořádku. Děkuji za informaci.

**Comment by dmarek** [comment]
Dobrý den, platební brána kontroluje, z jaké klientské ip se přistupuje na stránky brány.

V 15:07:03.751 jste provedl první payment/process, ip 52.28.71.142, user agent: guzzle/3.9.3 curl/7.35.0 php/5.6.16-1~dotdeb+7.1

V  15:07:23.900 to byl druhý požadavek, tady už přes prohlížeč, user agent: mozilla/5.0 (macintosh; intel mac os x 10_10_5) applewebkit/537.36 (khtml, like gecko) chrome/47.0.2526.80 safari/537.36, klientská ip byla jiná

payment/process je operace pro redirect z eshopu na platební bránu, kterou je potřeba provádět přes prohlížeč, řešením je tedy vynechat ten první request přes curl ...

**Comment by michalsanger** [comment]
Díky za info, to bude ono. Neznemožňuje ale taková kontrola IP adresy implementaci na tenkých klientech (v našem případě JS app a restového API serveru)? 

Flow máme totiž takovou, že init a process požadavky udělá server a klientovi pošle výslednou redirect URL, na kterou se klient přesměruje, zaplatí a po přesměrování zpět pošle "finish" request na API server.

**Comment by dmarek** [comment]
To by melo byt ok. IP adresa se uklada az pri prvnim pristupu na vyslednou redirect stranku (/pay/vasobchod.cz/1234-abcd-7890), payment/process je tedy mozne volat na serveru (seskladat parametry, podepsat) a vyslednou 302 redirect url uz predat js app klientovi, ktery ji v browseru zakaznika pouzije.

**Comment by michalsanger** [comment]
Přesně tak to ale děláme. Výslednou `https://iplatebnibrana.csob.cz/pay/shop.example.com/....` v JSON response dostane JS app, přesměruje se na ni a dozví se že "Platba nenalezena"

**Comment by dmarek** [comment]
v tom pripade pro volani `payment/process` je potreba vypnout `CURLOPT_FOLLOWLOCATION`, a vycist `Location` header z response ...

podle toho vyse uvedeneho logu se redirect pres curl nyni provede, cimz se na platebni brane ulozi ip adresa serveru, coz nechceme ...

**Comment by michalsanger** [comment]
Díky moc za rady, problém byl skutečně v tom že Guzzle následoval redirect
```php
$httpRequest = $this->httpClient->get(
    $url,
    null,
    [RequestOptions::ALLOW_REDIRECTS => false]
);
```
