### ISSUE TITLE
Zapamatování karty nefunguje na testovací bráně?

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#105]
Na testovací bráně se mi nedaří docílit zobrazení inputu pro zapamatování karty. Je tato funkce podporovaná?

Posílám customerId, ale v rozhraní brány se checkbox nezobrazí...

Request na `payment/init`
```json
{
    "merchantId": "M1E3CB0860",
    "orderNo": "7049908974",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 39000,
    "currency": "CZK",
    "closePayment": true,
    "returnUrl": "...",
    "returnMethod": "POST",
    "cart": [{
        "name": "N\u00e1kup",
        "quantity": 1,
        "amount": 39000
    }],
    "description": "Platba",
    "customerId": "728207789",
    "language": "CZ",
    "dttm": "20151221160609",
    "signature": "..."
}
```

**Comment by dmarek** [comment]
Nemáte povolené ukládaní karet "pro platby dříve uloženou kartou" (toto je jedno z nastavení obchodníka na platební bráně, které povoluje banka). Můžeme změnit, dám vědět, až to bude.

**Comment by janlanger** [comment]
Nakonec to nebudeme využívat, takže uzavírám
