### ISSUE TITLE
Brána odmítá Visa karty z důvodu, že nepodporují 3DSecure, ale tyto karty podporu pro 3DSecure mají

### ISSUE THREAD

**Issue by MichalMoravcik** [csob/paymentgateway#106]
Dobrý den,

Po nasazení brány se některým klientům s visa kartami stává, že je brána odmítne z důvodu, že nemají podporu 3DSecure. Jenže tito klienti podporu 3DSecure mají.

Přicházíme o klienty a velké sumy peněz. Co stím?

**Comment by ratajskym** [comment]
Dobrý den, 

pošlete prosím na supportní adresu platebnibrana@csob.cz Vaše merchant id a pokud to bude možné tak i číslo objednávek. Popisovaný stav prověříme.

**Comment by MichalMoravcik** [comment]
Děkuji, zkusíme.

**Comment by Miculka** [comment]
@Danny177 již jsem vám odpovídal na email. Vaše konkrétní objednávky se týkaly zamítaní z GPE, tedy nikoliv BIN, nebo brána. To prověří banka.
