### ISSUE TITLE
Omezení platby dle země vydání karty

### ISSUE THREAD

**Issue by smpoky** [csob/paymentgateway#107]
Dobrý den,
potřebovali bychom omezit, aby v CZK mohli platit jen zákazníci s kartou vydanou v ČR. Jedná se nám o to, aby zahraniční klient nemohl oklikou skrze českou verzi webu zakoupit produkt, který v CZK bude mít o něco nižší hodnotu než v EUR, což by bylo dostupné pro ostatní státy. Je toto možné s vaší platební bránou omezit?
Děkuji,
Jiří Pokorný

**Comment by smpoky** [comment]
Ještě dodatek. Alternativou by bylo alespoň možnost na naší straně zjištění země vydání zákazníkovi karty.
Děkuji,
Jiří Pokorný

**Comment by maximapojistovna** [comment]
Dobry den,

obavam se ze omezeni plateb na karty vydane v CR není mozne.

 

Nas nosny produkt je zdravotni pojisteni cizincu při pobytu v CR a tyto klienti nevlastni platebni kartu vydanou v CR.

 

 

 

S pozdravem Kotrba

Manager IT
