### ISSUE TITLE
Chyba přesměrování po úspěšné platbě (Android)

### ISSUE THREAD

**Issue by kjanek73** [csob/paymentgateway#109]
Dobrý den, 

Na mobilním zařízení s Android 4.1.2 (vyzkoušeno na CAT B15, Samsung Galaxy S2) v standardním Android Browseru (cme01.1367398115) se nám stává, že po úspěšné platbě nedojde k přesměrování na naši stránku, která přepne na naši aplikaci, z které byla platba volána. Při nepřesměrování se zobrazí potvrzující stránka bez textu o přesměrování viz snímek obrazovky Potvrzení bez přesměrování (v příloze). Url stránky je https://iplatebnibrana.csob.cz/pay/IDOS.CZ/70adae5f-32fd-4474-992f-76edd014c632/ . Navíc je zde problém, že se to nechová pořád stejně a někdy platba proběhne i když nastavení/postup je stejný .
Někdy pomůže odinstalace a instalace naší aplikace nebo vymazání nastavení Browseru „Spouštět jako výchozí“.

Úspěšně provedená transakce s přesměrováním (viz snímek Potvrzení s přesměrováním, Url https://iplatebnibrana.csob.cz/pay/IDOS.CZ/6752dfdc-0a6b-4cc4-8989-35e81277a21a/ )

Nevíte, proč se zobrazuje potvrzení platby bez informace o přesměrování? Myslíme, že to s tím má nějakou spojitost.

Používám platební údaje:
karta 4215010001000208
platnost 12/16
kód 301

Děkuji za reakci

Karel Janěk

1. Potvrzení bez přesměrování
![potvrzeni bez presmerovani](https://cloud.githubusercontent.com/assets/13237291/12232302/0bd35640-b85e-11e5-8132-4b0a301b5492.png)

2. Potvrzení s přesměrováním
![potvrzeni s presmerovanim](https://cloud.githubusercontent.com/assets/13237291/12232303/0bd46314-b85e-11e5-8f4c-d695797f3dc3.png)

**Comment by dmarek** [comment]
Dobrý den, úprava je připravena / nyní prochází interními testy. Dáme vědět, až bude nasazeno na integračním prostředí.

Původně se redirect zpět obchodníkovi posílal vždy jen jednou, nyní (pokud je např. platba zobrazena ve více tabech/oknech a procesuje se) může být redirect poslán zpět obchodníkovi vícekrát. 

Ve Vašem případě došlo k duplikování požadavku na zobrazení platby od prohlížeče (poté, co se vrátí řízení z 3DS ověření zpět na platební bránu, provedou se validace a nastartuje autorizace platby, následně se pošle prohlížeči 302 redirect na zobrazení aktuálního stavu platby, od prohlížeče přišly na server v rozmezí několika ms dva identické požadavky, odpověď ye serveru na první požadavek obsahoval redirect, nicméně prohlížeč zobrazil až druhý response bez redirectu.

**Comment by dmarek** [comment]
Uprava je nasazena na integracnim prostredi.

**Comment by ratajskym** [comment]
Aplikace byla nasazena na produkční prostředí. Pro tuto chvíli issue zavírám
