### ISSUE TITLE
Legacy API (migrace z GP Webpay) a ověření stavu platby

### ISSUE THREAD

**Issue by webczech** [csob/paymentgateway#11]
Po obšírné komunikaci jsem se dozvěděl, že legacy API neumožňuje ověření stavu platby. Vzhledem k tomu, že předchozí integrace toto umožňovala prostř. SOAP protokolu a odhaduji že 99% integrací tuto možnost využívá, domnívám se, že bylo by vhodné uvést informaci, že je ve skriptech potřeba toto ověřování zrušit (jinak se samozřejmě bude dále ověřovat prostř. WSDL GP Webpay) a také zákazníkovi zobrazit nějakou výchozí informaci "platební brána neumožnuje ověření stavu transakce".

**Comment by tomastak** [comment]
Mohol by sa prosím niekto z kompetentých vyjadriť k tomuto dotazu? Máme to skutočne chápať tak, že legacy API neposkytuje žiadnu možnosť, ako overiť stav platby?

**Comment by ratajskym** [comment]
Dobrý den, Legacy API skutečně nepodporuje možnost ověření stavu platby. Tato funkcionalita je ovšem implementovaná v eAPI viz dokumentace https://github.com/csob/paymentgateway/wiki/eAPI-v1-CZ
