### ISSUE TITLE
Klientská knihovna pro PHP

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#110]
Při přípravě platební brány jsme Slevomatu vytvořili klientskou knihovnu pro komunikaci s eAPI.
Rádi jí dáme k dispozici a využití i dalším vývojářům, proto ji dnes zveřejňujeme jako open-source.

https://github.com/slevomat/csob-gateway

Bylo by skvělé kdyby tady v repozitáři nebo na wiki vznikl seznam knihoven třetích stran, které vývojářům usnadňují implementaci brány do systému...

**Comment by ratajskym** [comment]
Dobrý den,

doplněno [zde](https://github.com/csob/paymentgateway/blob/master/README.md#3-repozitář)
