### ISSUE TITLE
Platba kartou pro testování opakované platby je vždy autorizována

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#111]
Dobrý den,

platba kartou 5332290001000202 se nechová podle dokumentace - projde nám jak první platba s vyplněním údajů tak i recurring která by projít neměla.

Chování je stejné pro merchant id M1E3CB0860 i M1E3CB0959

**Comment by dmarek** [comment]
diky za info, mame nachystanou opravu pro integracni prostredi (oprava simulatoru autorizace), dame vedet, az bude nasazeno.

**Comment by dmarek** [comment]
oprava simulatoru nasazena na integracnim prostredi (nyni tedy prvotni platba s kartou 5332290001000202 projde, nasledna opakovana platba pomoci `payment/recurrent` s `origPayId` nastavenym na prvotni platbu vrati `paymentStatus: 6`, zamitnuto)

vyzkousejte a pripadne zavrete. diky

**Comment by janlanger** [comment]
funguje, diky
