### ISSUE TITLE
Chyba 900 bez bližších informací (v1.5)

### ISSUE THREAD

**Issue by kytart** [csob/paymentgateway#112]
Nějakou dobu jsem nemohl přijít na to, proč mi při vytváření nové platby API vrací kód 900. Nakonec jsem přišel na to, že je to tím, že jsem zapoměl celkovou cenu vynásobit 100, aby to bylo v haléřích. Je to sice chyba na mé straně, ale bylo by fajn, kdyby chybové hlášky více napovídaly, co je zdrojem chyby. V tomhle případě bych si to představoval tak, že API vrátí nějakou variaci chybového kódu 110.

**Comment by ratajskym** [comment]
Dobrý den, 

děkujeme za Váš podnět, ale specifikace API je dosti přesná.
