### ISSUE TITLE
Chyba 400 bez bližších informací (v1.5)

### ISSUE THREAD

**Issue by kytart** [csob/paymentgateway#113]
Dlouho jsem se snažil přijít na to, proč mi API vrací při vytváření nové platby chybu 400. Odpověď neobsahovala žádné další informace. Nakonec jsem přišel na to, že jedna z položek košíku měla kvantitu jako desetinné číslo. Je otázka, jestli by kvantita měla být možná jako desetinné číslo, každopádně hlavní problém tady je to, že v odpovědi chybí informace o zdroji chyby. Představoval bych si nějakou variaci na kód 110 nebo tak něco.

**Comment by ratajskym** [comment]
Dobrý den,

děkujeme za upozornění. Informaci doplníme do dokumentace, nicméně návratový kód se měnit nebude
