### ISSUE TITLE
Kreditovani plateb pres API

### ISSUE THREAD

**Issue by Danny177** [csob/paymentgateway#117]
Prosim o umozneni kreditovani plateb pres API:
Castecne kreditovani probiha asynchronne + nejsme schopni se dotazat
na castku jaka byla vracena, tudiz v pripade opakovaneho kreditovani
nejsme schopni zjistit kolik bylo vraceno penez celkem.

Prosim o napraveni,
Daniel Novak

**Comment by ratajskym** [comment]
Dobrý den, 

uvedenou funkcionalitu připravujeme. O nasazení do produkčního prostředí Vás budeme informovat

**Comment by ratajskym** [comment]
Dobrý den, uvedenou funkcionalitu jsme nakonec vyřadili z feature listu. Chování zůstane stávající

**Comment by Danny177** [comment]
Dobry den,
je to problem, system tak nefunguje korektne, budeme kontaktovat manazera CSOB,
