### ISSUE TITLE
Neakceptace nekterych karet - DE a AT

### ISSUE THREAD

**Issue by Danny177** [csob/paymentgateway#118]
Dochazi k neakceptaci karet zejmena z DE a AT, kvuli tomu, ze nemate BINy karet v tabulce,
prosim o napreveni situace ASAP.

**Comment by ratajskym** [comment]
Dobrý den, máte nějaký konkrétní BIN, který bychom mohli prověřit?

**Comment by Danny177** [comment]
posilam screenshot, u GP Webpay vse vali

Daniel Novák

**Comment by ratajskym** [comment]
Dobrý den, kam jste ten screenshot poslal?

**Comment by Danny177** [comment]
Dobry den,
sem:
to: csob/paymentgateway <
reply@reply.github.com
>
cc: csob/paymentgateway <paymentgateway@noreply.github.com>

Daniel Novák

**Comment by Danny177** [comment]
Prosim o reseni BINu, ztracime kvuli tomu zakazniky

**Comment by JaroMach** [comment]
Dobrý den, byl tento problem již vyřešen? máme velké množství stížností na nemožnost platby VISA kartami. S GPwebpay s timto nebyl problem. Jedná se rovněž o DE a AT klienty proto se domnívám, že je to stejný důvod. Diky za odpověd J.Mach

**Comment by Danny177** [comment]
Dobry den,
vypada to nyni lepe - za brezen se situace zlepsila,
DN

**Comment by Miculka** [comment]
@Danny177  již jsem vám odpovídal na email. Vaše konkrétní objednávky se týkaly zamítaní z GPE, tedy nikoliv BIN, nebo brána. To prověří banka.
