### ISSUE TITLE
Zlepšení bezpežnostně-uživatelského GUI pro zahraniční zákazníky

### ISSUE THREAD

**Issue by Danny177** [csob/paymentgateway#119]
Dobrý den,
bohužel dochází k tomu, že zahraniční zákazníci nevěří tolik platební bráně která běží na domene .cz - lepší je .eu domena nebo .com

Dále:
- je vhodne pouzit - Extended validation certificate
https://www.startssl.com/Support?v=30
- logo KBC (aspon "CSOB is a member of KBC group")

DN

**Comment by ratajskym** [comment]
Děkujeme za podněty, nicméně podobné úpravy v nejbližší době neplánujeme.
