### ISSUE TITLE
Koncový stav transakce

### ISSUE THREAD

**Issue by petr-goca** [csob/paymentgateway#12]
Navazuji na https://raw.githubusercontent.com/wiki/csob/paymentgateway/img/cz/state-transitions.png

Můžeme stav 7 chápat jako finální? Tedy, pokud je transakce ve stavu 7, můžeme u nás na webu provést efekt platby (jako je např. připsání kreditu na webu, změna stavu objednávky na zaplacenou apod.)? Nebo je finálním stavem až stav 8?

Nyní to chápeme tak, že finálním je asi už stav 7 a 8 je stav, který nastane až po převodu peněz (což může nastat až např. druhý pracovní den). Chápeme to správně?

**Comment by dmarek** [comment]
Přesně tak, stav 7 odpovídá úspěšné autorizaci, můžete na straně eshopu provést požadované akce související se zaplacením objednávky. Přechod ze stavu 7 do 8 je víceméně technická záležitost na straně banky, kdy 1x denně probíhá zaúčtování autorizovaných transakcí (= výměna dat / převod peněz mezi ČSOB a cílovou bankou, která vydala danou platební kartu).
