### ISSUE TITLE
ResultCode 900 na produkční bráně

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#120]
Dobrý den,

na produkční bráně se nám občas vrací odpověď s resultCode 900 - Internal error a nedaří se nám odhalit žádnou chybu na naší straně.
Můžete prosím prověřit následující platby jestli je chyba u nás nebo u vás?

Merchant ID - M1E3CB0860
- a6669c30e3efbBA
- e1cff62bf44bbBA

Merchant ID - M1E3CB0959
- 994a2365269cdBA
- 9d24bb3146e69BA
- 4feaedabdd013BA

**Comment by Miculka** [comment]
Dobrý den. 
 
Všechny transakce mají jednoho společného jmenovatele a tím je nepodporovaný prohlížeč. Z toho důvodu je uživatel zpět přesměrován a transakce expiruje. Je to z důvodu správné fce platební brány. Jsou nastaveny určité nejnižší verze jednotlivých browserů, které uživatele pustí dále.

**Comment by Miculka** [comment]
uživatel je o této věci informován následovně

![11](https://cloud.githubusercontent.com/assets/14308839/12358137/1ca3eda8-bbac-11e5-9953-2fac4108d594.png)

**Comment by janlanger** [comment]
Děkuji. Můžete ještě napsat která verze prohlížečů jsou podporované?

**Comment by Miculka** [comment]
Ano prosím. Zde. 

![image](https://cloud.githubusercontent.com/assets/14308839/12358811/5b4807bc-bbaf-11e5-91be-fee174cd125a.png)

**Comment by janlanger** [comment]
Díky za info. Jako námět do dalšího vývoje - bylo by skvělé kdyby se tato situace dala detekovat z odpovědi (ať už v resultCode nebo třeba jen jiným textem místo "Internal Error")

**Comment by dmarek** [comment]
Ja jen doplnim, ze u mobilnich prohlizecu detekujeme krome android browseru a mobilni opery take mobilni firefox (30), mobilni safari (4), mobilni chrome (30) a mobilni iexplorer (6) / ve vyse uvedene tabulce to neni uvedene - detailni chovani a specifikaci jeste doplnime do wiki.

Plati, ze kdyz detekujeme browser, tak kontrolujeme major verzi oproti vyse uvedenemu limitu. 

Detailni stav odmitnuti transakce planujeme, diky za feedback.

**Comment by janlanger** [comment]
Dobrý den,

máme další stav 900, tentokrát s user agentem Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E) což je IE 8, čili podporovaný prohlížeč.

PayId 03b888c8219d7BA

Jaký je problém s touto platbou?

**Comment by dmarek** [comment]
pro payId 03b888c8219d7BA mame zalogovany User-Agent 

```
mozilla/5.0 (windows nt 6.1) applewebkit/537.36 (khtml, like gecko) chrome/28.0.1500.72 safari/537.36
```

**Comment by janlanger** [comment]
Aha, pravda, evidentně zkoušel jiné prohlížeče na naší koncové stránce...

Díky
