### ISSUE TITLE
Podpora a detekce starších prohlížečů

### ISSUE THREAD

**Issue by ondrejmirtes** [csob/paymentgateway#121]
Dobrý den,
aktuálně vaše brána znemožňuje zaplatit transakci zákazníkům, které nesplňují požadavek na verzi prohlížeče podle následující tabulky:

![Tabulka podpory](https://cloud.githubusercontent.com/assets/14308839/12358811/5b4807bc-bbaf-11e5-91be-fee174cd125a.png)

Takoví zákazníci se setkají s následující hláškou:

![Aktualizujte si prohlížeč](https://cloud.githubusercontent.com/assets/14308839/12358137/1ca3eda8-bbac-11e5-9953-2fac4108d594.png)

Chápu důvody, které vás vedou k odmítání uživatelů se staršími prohlížeči - více podporovaných verzí pro vás znamená více testování a tedy větší náklady a v případě, že starší prohlížeč nepodporuje nějakou vámi vyžadovanou funkcionalitu, tak i náročnější vývoj.

Nechci tedy po vás, aby v tabulce výše byla uvedena nižší čísla verzí a díky tomu přes vaši bránu prošlo větší % uživatelů. Místo toho vám chci navrhnout jiný přístup k podpoře a detekci starších prohlížečů, u kterého věřím, že povede k nižším nákladům z vaší strany a větší spokojenosti uživatelů zároveň.

Mám za to, že za výše uvedenou tabulkou podpory se skrývá jistá skrytá logika, tedy postup, jak jste ke konkrétním číslům došli. Vzali jste všechny pokročilé funkce z JavaScriptu a CSS, které na platební bráně chcete při vývoji používat, podívali jste se na jednotlivé prohlížeče a od jaké minimální verze vaše požadované vlastnosti podporují, a zanesli tyto informace do tabulky a detekce prohlížečů.

Tento přístup má následující problémy:

* Tu tabulku musíte udržovat a neustále aktualizovat, podle toho, jaké vlastnosti prohlížečů vývojáři používají.
* Na trhu se pravidelně objevují nové prohlížeče s novými verzemi, i z toho důvodu je potřeba tabulku aktualizovat.
* Verze prohlížečů musíte na straně serveru nebo klienta detekovat. Vzhledem k různému formátu user agent stringů tato detekce nemusí být zrovna spolehlivá a její údržba je také náročná.
* User-agent string lze podvrhovat, tedy vámi nepodporovanému prohlížeči stejně umožníte zaplatit, pokud se díky User-agent stringu začne tvářit jako nejnovější verze.

Namísto odmítání uživatelů s konkrétními verzemi prohlížečů navrhuji přistupovat k problému jinak: Detekovat na straně klienta konkrétní vyžadované funkce, nikoli verze prohlížečů.

Např. v případě, že potřebujete detekovat podporu geolokace, tak namísto:

```
if (ie.version > 8)
```

tedy použijete:

```
if ('geolocation' in navigator)
```

Čímž dosáhnete toho samého a funkcionalita bude dostupná automaticky ve všech prohlížečích, které ji podporují.

Tolik k JavaScriptu. Pokud omezujete podporu prohlížečů i kvůli CSS vlastnostem, opět existuje lepší přístup. Použijte např. nástroj [autoprefixer](https://github.com/postcss/autoprefixer), který umožňuje zapisovat CSS vlastnosti bez vendor prefixů a automaticky je doplňuje podle zvolených nastavení, břemeno podpory starších prohlížečů tedy vývojový tým nezatěžuje tolik. Co se týče starších prohlížečů, věřím, že uživatelé raději projdou nákupním procesem v mírně rozpadlém designu, než vůbec. Nezapomeňte, že žádost "aktualizujte si prohlížeč" pro některé uživatele Androidu znamená "kupte si nový telefon", protože mohou mít takového výrobce, který jim aktualizace vůbec neposkytuje!

Další zdroje k tématu:

* [How to Detect Features Instead of Browsers](https://msdn.microsoft.com/en-us/library/hh273397%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) - Microsoft.com
* [Future-Proofing JavaScript Libraries](http://ejohn.org/blog/future-proofing-javascript-libraries/) - John Resig, autor jQuery
* [Browser Detection (and what to do Instead)](http://www.jibbering.com/faq/notes/detect-browser/)

Děkuji předem za zvážení mého návrhu,
Ondřej Mirtes,
vývojář Slevomat.cz

**Comment by jirihelmich** [comment]
:+1:

**Comment by pepakriz** [comment]
:+1:

**Comment by Dundee** [comment]
:+1:

**Comment by petrjirasek** [comment]
:+1:

**Comment by zakjan** [comment]
:+1:

**Comment by janlanger** [comment]
:+1:

**Comment by pesovo** [comment]
:+1:

**Comment by lsuchanek** [comment]
:+1:

**Comment by integer** [comment]
:+1:

**Comment by snake-aas** [comment]
:+1:

**Comment by Twista** [comment]
+1

**Comment by defragment** [comment]
:+1:

**Comment by jakubkulhan** [comment]
:+1:

**Comment by kukulich** [comment]
:+1:

**Comment by fprochazka** [comment]
:+1:

**Comment by rydercz** [comment]
:+1:

**Comment by ratajskym** [comment]
Dobrý den, 

jen pro pořádek a vaši informaci. Detekce zastaralých prohlížečů byla až do vyřešení vypnuta.
