### ISSUE TITLE
Chyba 900

### ISSUE THREAD

**Issue by samyce** [csob/paymentgateway#122]
Zdravim a prosim o pomoc,

pouzivam plugin pro branu v prestashopu, ktery mel udajne pro testovaci klice a url API fungovat. Nicmene pri prechodu na ostre klice se mi nedari na branu prejit.

S chybou 400 jsem se vyporadal, podle rad v dokumentaci - closePayment  false/true => 0/1

Nicmene dostavam novou chybu a to prave chybu s kodem 900. Cena je 100 nasobena, format dat pro kosik vypada take spravne. Prikladam format dat ktery ce se postuje, nemam tuseni, kde by mohla byt chyba. 

(Uvedena data jsou pouze testovaci, abych porad nevytvarel objednavky, tzn. ze id objednavky i cena jsou vymyslene - predpokladam ze to nevadi, protoze tuto chybu dostavam i pro skutecnou objednavku)

{
   "merchantId":"M1MIPS0240",
   "orderNo":777,
   "dttm":"20160118161029",
   "payOperation":"payment",
   "payMethod":"card",
   "totalAmount":20100,
   "currency":"CZK",
   "closePayment":"1",
   "returnUrl":"",
   "returnMethod":"POST",
   "cart":[
      {
         "name":"Shopping at ...",
         "quantity":1,
         "amount":20100,
         "description":"..."
      },
      {
         "name":"Shipping",
         "quantity":1,
         "amount":0,
         "description":"PPL"
      }
   ],
   "description":"Platba objedn\u00e1vky 777",
   "merchantData":null,
   "customerId":"",
   "language":"CZ",
   "signature":"---"
}

Dekuj za kazdou radu. 

Samuel

**Comment by Miculka** [comment]
Dobrý den. 

V logu vidím následující : message	 	Invalid paymentInit signature for M1MIPS0240

Takže bych šel po klíčích. Někde v tom bude chyba. Pokud mi pošlete jak máte poskládaný podpis, tak Vám můžu říci více.

**Comment by samyce** [comment]
Pokud bychom se mohli spoji napriklad emailem mohu poslat, kompletni zdrojak, kde probiha init a priprava dat pro post pozadavek.

Nicmene, jak jsem uvedl vyse, tak v testovacim modu mela brana fungovat - je mozne, ze je napriklad problem s klici, ve smyslu zameny tesovaci/ostre? Klice jsem pouze dostal pro nasazeni na web s tim, ze jsou aktivni.

Diky. S.

**Comment by Miculka** [comment]
Pokud metoda paymentinit v testu prochazela, pak podpis máte nastaven dobře. 

Jedná se tedy dle všeho o záměnu klíčů jak píšete výše. Plus je třeba nahradit i veř. klíč brány na ostrý . 
viz. https://github.com/csob/paymentgateway/tree/master/keys

**Comment by samyce** [comment]
No jak jsem se dozvedel, tak je i nutne, nejprve platebni branu zprovoznit
v testovacim modu a az po te je mozne vygenrovat klice pro produkcni
pouziti, takze signatura by mela byt v poradku.

Pro jeji generovani se mimo jine pouziva parametr 'privateKeyPassword',
ktery byl pro testovaci rezim pradny - je mozne ze je nyni potreba?
Pripadne, myslite, ze by pomohlo vygenerovani novych klicu? Po nahledu do
soubrou s privatnim klicem a verejnym, by si mely soubory odpovidat, tj. k
zamena by pricinou byt nemela. Prikaldam config, ktery predava nastaveni
pro branu.

$url = "https://api.platebnibrana.csob.cz/api/v1.5";
$publicKey = "rsa_M1MIPS0240.pub";
$merchantId="M1MIPS0240";
$privateKey = "rsa_M1MIPS0240.key";
$privateKeyPassword = null;


Diky M. K.

Michael Kurdík

+420 724 124 224
michael.kurdik@gmail.com

Dne 19. ledna 2016 19:19 Michal Mičulka <notifications@github.com>
napsal(a):

**Comment by Miculka** [comment]
Dobrý den. 
Ano platební bránu, pokud nepřecházíte GP Webpay, je nutné zprovoznit nejprve v testovacím (integračním) prostředí. Je nutné projít validací a poté je možný přístup do produkce. 

V POSm však vidím, že jste úspěšně provedl 3 požadované transakce a chybí jen jedna se statusem Autorizovano/Poslano k zauctovani. V produkci vidím, že jste již aktivní.

V případě vašeho podpisu vidím problém v URL : pro testovací prostředí je adresa : https://iapi.iplatebnibrana.csob.cz/api/v1.5

A nikde nevidím veř. klíč brány jak jsem odkazoval výše.

**Comment by samyce** [comment]
Ano, prave ze testem jiz probehlo, kde vse bylo funkcni. Proto jsme
prechazeli na produkcni rezim. Byly vygenerovany nove klice pro produkcni
pouziti, kterymi jsem nahradil ty testovaci klice.

Co se url tyce, tak vychazim z dokumentace

"*Pro vývoj a integraci řešení je testovací platební brána pro obchodníky
dostupná na adrese https://iapi.iplatebnibrana.csob.cz/
<https://iapi.iplatebnibrana.csob.cz/>. Migraci na produkční prostředí pak,
po odsouhlasení řešení ze strany banky, lze provést výměnou testovacích
klíčů za produkční a přesměrováním api na
https://api.platebnibrana.csob.cz/ <https://api.platebnibrana.csob.cz/>.*"

Privatni klic brany by mel odpovidat souboru s nazvem "rsa_M1MIPS0240.key"
a verejny souboru "rsa_M1MIPS0240.pub"



Michael Kurdík

+420 724 124 224
michael.kurdik@gmail.com

Dne 20. ledna 2016 15:19 Michal Mičulka <notifications@github.com>
napsal(a):

**Comment by Miculka** [comment]
To určitě ne. Veř. Klíč platební brány má podobu –
mips_platebnibrana.csob.cz



PRODUCTION ENVIRONMENT

----------------------



mips_platebnibrana.csob.cz.pub - this file contains public key of CSOB
payment gateway

  for production environment (https://platebnibrana.csob.cz),

  required for response signature verification



mips_platebnibrana.csob.cz.cer - this file contains certificate of CSOB
payment gateway

  for production environment (https://platebnibrana.csob.cz),

  required for response signature verification





S pozdravem


*Ing. Michal Mičulka*IT support specialist

[image: http://www.monetplus.cz/data/images/Monet_tagline_CMYK.png]
*E:* mmiculka@monetplus.cz



*From:* samyce [mailto:notifications@github.com]
*Sent:* Wednesday, January 20, 2016 8:47 PM
*To:* csob/paymentgateway <paymentgateway@noreply.github.com>
*Cc:* Michal Mičulka <mmiculka@monetplus.cz>
*Subject:* Re: [paymentgateway] Chyba 900 (#122)



Ano, prave ze testem jiz probehlo, kde vse bylo funkcni. Proto jsme
prechazeli na produkcni rezim. Byly vygenerovany nove klice pro produkcni
pouziti, kterymi jsem nahradil ty testovaci klice.

Co se url tyce, tak vychazim z dokumentace

"*Pro vývoj a integraci řešení je testovací platební brána pro obchodníky
dostupná na adrese https://iapi.iplatebnibrana.csob.cz/
<https://iapi.iplatebnibrana.csob.cz/>. Migraci na produkční prostředí pak,
po odsouhlasení řešení ze strany banky, lze provést výměnou testovacích
klíčů za produkční a přesměrováním api na
https://api.platebnibrana.csob.cz/ <https://api.platebnibrana.csob.cz/>.*"

Privatni klic brany by mel odpovidat souboru s nazvem "rsa_M1MIPS0240.key"
a verejny souboru "rsa_M1MIPS0240.pub"



Michael Kurdík

+420 724 124 224
michael.kurdik@gmail.com

Dne 20. ledna 2016 15:19 Michal Mičulka <notifications@github.com>
napsal(a):

> Dobrý den.
> Ano platební bránu, pokud nepřecházíte GP Webpay, je nutné zprovoznit
> nejprve v testovacím (integračním) prostředí. Je nutné projít validací a
> poté je možný přístup do produkce.
>
> V POSm však vidím, že jste úspěšně provedl 3 požadované transakce a chybí
> jen jedna se statusem Autorizovano/Poslano k zauctovani. V produkci vidím,
> že jste již aktivní.
>
> V případě vašeho podpisu vidím problém v URL : pro testovací prostředí je
> adresa : https://iapi.iplatebnibrana.csob.cz/api/v1.5
>
> A nikde nevidím veř. klíč brány jak jsem odkazoval výše.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csob/paymentgateway/issues/122#issuecomment-173216733>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/csob/paymentgateway/issues/122#issuecomment-173338051>.

**Comment by samyce** [comment]
Dobre odpoledne,

stale se mi nedari rozhodit platebni branu. Pokud se odkazu na vasi
posledni zpravu, tak mi neni jasne, co tedy presne myslite verejnym klicem
brany. Pro jistotu jsme vygenrovali klice nove (na url
https://platebnibrana.csob.cz/keygen/), ale stale plati, ze jeden klic,
ktery generator nabidne ke stazeni je rsa_M1MIPS0240.key a
rsa_M1MIPS0240.pub. Tyto klice dale predavam do pluginu, ktery obstarava
komunikaci s branou. Po prozkoumani zdrojoveho kodu, mi nejprijde nutne,
aby se soubor s verenjnym klicem jmenoval 'mips_platebnibrana.csob.cz.pub',
jak uvadite vyse -  k vypoctu signatury se pouziva obsah klice (privatniho).

Kod 900 dostavam v momente vykonani POST
https://api.platebnibrana.csob.cz/api/v1.5/payment/init, kde se podle
zdrojoveho kodu, signatura nezpracovava s verejnym klicem, ale prave
zminenym privatnim. Az po te, kdy by mela prijit odpoved z brany, kde se
prijata signatura porovnava se signaturou genrovanou s verejnym klicem (ale
do tohoto kroku se diky 900 nedostanu).

Rekl bych ze popsany proces sedi, proto me mate, ze se odkazujete na
verejny klic brany. Mozna ze je zmatek jen v nazvoslovi, ale jak jsem psal,
mam pouze tyto dva vygenerovane klice.

Diky za odpoved.


Michael Kurdík

+420 724 124 224
michael.kurdik@gmail.com

Dne 20. ledna 2016 21:55 Michal Mičulka <notifications@github.com>
napsal(a):

**Comment by Miculka** [comment]
Dobrý den,

Nastíním zde využití jednotlivých klíčů.

Existuji dva páry klíčů.

Klíče obchodníka:
	soukromým klíčem obchodník podepisuje požadavek, který posílá na server (např. payment/init)
	veřejným klíčem obchodníka se na straně platební brány ověřuje podpis obchodníka

Klíče brány (veřejný klíč je dostupný na https://github.com/csob/paymentgateway/tree/master/keys)
	soukromým klíčem brány podepíše brána odpověď (např. odpověď na payment/init)
	veřejným klíčem brány obchodník ověřuje podpis odpovědi brány (např. odpověď na payment/init)

Veřejné klíče brány jsou dostupné ve dvou formátech - pub a cer (muže se použít jeden nebo druhy formát, důležité je, že je možné jej použít jen na ověření podpisu odpovědi od brány, ničeho jiného).
Stejně tak nelze použít veřejný klíč obchodníka na ověření podpisu odpovědi od brány (protože je podepsáno soukromým klíčem brány a ne soukromým klíčem obchodníka).

S pozdravem
