### ISSUE TITLE
Odvolaní probíhající platby

### ISSUE THREAD

**Issue by SrubarChaps** [csob/paymentgateway#124]
Dobrý den,
máme eShop jako nativní Android aplikaci a  řešíme situaci, kdy zákazníkovi zavře nebo mu zatuhne okno prohlížeče s platbou. 
Vymysleli jsme tedy, že v to případě si zákazník bude moci platbu ověřit přes funkci payment/status. V případě, že je platba zamítnuta nebo zaplacena, nemáme problém. 
Ale v případě, že platba probíhá, bychom potřebovali možnost tuto probíhající platbu aktivně ukončit, ideálně přes odvolaní platby (payment/revrerze), případně nějak jinak. Je to možné? V dokumentaci taková možnost zmíněna není.
Na timeout spoléhat nechceme, co kdyby zákazník přece jen okno nějak otevřel a platbu dokončil.

Zdraví
Ondřej Šrubař

**Comment by Miculka** [comment]
Dobrý den. 
Aktivni zruseni/ukonceni probihajici transakce (stav 2=pending) od obchodnika neni mozne. Autorizace dane platby muze jiz probihat (platebni brana ceka na dokonceni autorizace pozadavku u issuera karty). Je nutne vyckat na vysledek autorizace a zjistovat stav pomoci payment/status.
