### ISSUE TITLE
Přechod do ostrého prostředí

### ISSUE THREAD

**Issue by Madla** [csob/paymentgateway#126]
Dobrý den,

přešli jsme do ostrého prostředí, ale bohužel platba (počáteční krok - výměna klíčů) se neautorizovala. Je možné získat aktuální klíče nebo je nutné je znovu vygenerovat?

Děkuji

**Comment by Miculka** [comment]
Dobrý den.



Je skvělé, že jste úspěšně absolvovali integrační prostředí a nyní jste
v produkci. Bohužel Vám moc nepomůžu pokud nebudu znáti alespoň ID Merchant
tj. číslo obchodníka, nebo alespoň název firmy, či její IČO – cokoliv co by
mi umožnilo bránu identifikovat.



K vašemu dotazu – počátečním krokem do produkce je výměna integračních
klíčů za produkční – tyto jsou k mání zde
https://platebnibrana.csob.cz/keygen/



Po té klíče aktivujete na POSm viz. Odkaz z emailu od platebnibrana, který
Vám přišel. Přihlašovací údaje jsou ve smlouvě.



Dále je nutné vyměnit veřejný klíč brány z integračního na produkční
k nalezení zde : https://github.com/csob/paymentgateway/tree/master/keys



Nutné je i změnit URL brány – na https://api.platebnibrana.csob.cz/   (v
pripade, ze vyuzivate metodu Legacy API) nebo
https://api.platebnibrana.csob.cz/api/v1.5/   (v případě využití modernější
a dokonalejší brány eAPI1.5 )



Pokud jste úspěšně prošli prostředím integračním, pak by Vám výše zmíněné
mělo pomoci. V případě jakýkoliv problémů nás neváhejte kontaktovat,
poprosím jen o nějakou indicii, které bych se mohl chytnout a bránu na tom
základě identifikovat.



Děkuji.



S pozdravem


*Ing. Michal Mičulka*IT support specialist

[image: http://www.monetplus.cz/data/images/Monet_tagline_CMYK.png]
*E:* mmiculka@monetplus.cz



*From:* Madla [mailto:notifications@github.com]
*Sent:* Thursday, January 21, 2016 10:36 PM
*To:* csob/paymentgateway <paymentgateway@noreply.github.com>
*Subject:* [paymentgateway] Přechod do ostrého prostředí (#126)



Dobrý den,

přešli jsme do ostrého prostředí, ale bohužel platba (počáteční krok -
výměna klíčů) se neautorizovala Je možné získat aktuální klíče nebo je
nutné je znovu vygenerovat?

Děkuji

—
Reply to this email directly or view it on GitHub
<https://github.com/csob/paymentgateway/issues/126>.[image: Obrázek byl
odebrán odesílatelem.]

**Comment by ratajskym** [comment]
@Madla Dobrý den, došlo k vyřešení Vašeho dotazu? Můžeme toto issue uzavřít?

**Comment by Madla** [comment]
Dobrý den,

bohužel jsem odjel na 3týdenní služební cestu mimo Evropu a neměl jsem čas to řešit ... budu řešit až příští týden.

**Comment by rjansky** [comment]
Dobry den,
pro platebni branu M1MIPS0488 jsme provedli vsechna testovani z navodu v e-mailu. Prechod na produkcni prostredi muzeme inociovat sami, nebo musime cekat az se nam po testech ozvete?

Dekuji
Jansky

**Comment by aKocian** [comment]
Dobrý den,

po úspěšné validaci brány odejde do banky mail a na základě toho jí pošlou do produkčního prostředí.

**Comment by Miculka** [comment]
pro jistotu bych poslal email na akceptacekaret(zavinac)csob.cz , zadal sve ID Merchant a poprosil o aktivaci produkcniho prostredi.
