### ISSUE TITLE
Stav po částečném vrácení

### ISSUE THREAD

**Issue by SrubarChaps** [csob/paymentgateway#127]
Dobrý den,
jaký je správný stav po částečném vrácení, kdy nejsou ještě vráceny všechny peníze? Není to zdokumentované, ale pokusem jsem zjistil, že 10 (platba vrácena). Nemělo by to být spíš 8? 
Případně 10, ale pak by se při zjišťování stavu hodila informace o tom, zda a případně kolik je možné ještě vrátit.

Zdraví 
Ondřej Šrubař

**Comment by janlanger** [comment]
:+1:

**Comment by ratajskym** [comment]
Dobrý den, 

děkujeme za Váš podnět, přesto do stávající logiky refund transakcí nebudeme zasahovat.
