### ISSUE TITLE
unable to verify signature

### ISSUE THREAD

**Issue by mobilttl** [csob/paymentgateway#128]
zdravím,
v testovacím provozu mi nějak zlobí veřejný klíč. Požadavek na platbu se odešle, ale odpověď už nejde ověřit podpisem:

preparing payment init data ...

preparing cart data:
[
    {
        "name": "Shopping at ...",
        "quantity": 1,
        "amount": 120000,
        "description": "Lenovo ThinkPad Edge E540..."
    },
    {
        "name": "Shipping",
        "quantity": 1,
        "amount": 0,
        "description": "PPL"
    }
]

data to sign:
"M1MIPS0297|123456|20160126112927|payment|card|120000|CZK|false|https://vasobchod.cz/gateway-return|POST|Shopping at ...|1|120000|Lenovo ThinkPad Edge E540...|Shipping|1|0|PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|1234|CZ"

prepared payment/init request:
{
    "merchantId": "M1MIPS0297",
    "orderNo": "123456",
    "dttm": "20160126112927",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 120000,
    "currency": "CZK",
    "closePayment": "false",
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 120000,
            "description": "Lenovo ThinkPad Edge E540..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 0,
            "description": "PPL"
        }
    ],
    "description": "Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
    "merchantData": null,
    "customerId": "1234",
    "language": "CZ",
    "signature": "NxqZqs4XR5CdC9GplEI/f47LpFMNXWasC4E34fRfFz+PQMjFN+KuivYWC8U0Zta1a5BDSUO3jJpYuJsjWmoDlUzKVjxTDhNoW26TtEOdQDKZjUOA5cvOynrFPMJPLoj6En1zF7CRSp5d5FCps89ahBJCbnNq7G5ve6wfVEBGJj2j6Aom+MDGJQ6Lm+tbb/YoFu3mX++I7vd9XRbE4vFC1jeSu1VBGdZNIcPm2G7+okptxGwZle2BTWEkF95X0Sk91d4I9UfRjExp5sFJNTCUI3mpqGaUs5JKVHKzdCrkQx0qD9sd8OXVDSoahHbZhnwTUM7feQ/mwvuI7dC+6KlG/Q=="
}

processing payment/init request ...

payment/init result:
{"dttm":"20160126112927","signature":"La2FXP12DkFHpE/MHBMwtYg4N4i+wzweuchxyBF7ll4Dokxhg16nQuOeFcpEF0xK2ABwOb1yxiLxb+JsU6iO/lLGOblq2zBjQC7W1wrtnlv9EZU5Twj4e76V9/wl+zzyNFLQ/1HgGxFht0zdSeWjzakDhIbn+zyYani1PLIOhItzysanf3rp0OIshr/781l+GC8SMmUIWN7Fr8TiyhGJywhp/VvHekvt0NxKiAIw/PeGTnBIQhOCuHwotbtkcpq109qdk8k0tJNh0n87ppLh7AxE+Q9C9S5kiWfX/QDkuM9zkQ9JIlKBht42zLQuZghTlfxAcVqH36I4u+GBedBEqA==","payId":"a587fea8ef612BA","resultCode":0,"resultMessage":"OK","paymentStatus":1}

payment/init failed, unable to verify signature

díky za radu.

Tomáš

**Comment by Miculka** [comment]
Dobrý den. 
Spíše by mi pomohlo kdyby jste poslal jak máte seskládaný podpis. 
Nicméně, tady vidím, že bude pravděpodobně problém s veřejným klíčem banky - tj. ten který slouží k ověření obchodníka na bráně. 

Tyto klíče stáhnete zde : https://github.com/csob/paymentgateway/tree/master/keys

budete potrebovat klíč mips_iplatebnibrana...

**Comment by mobilttl** [comment]
Dobrý den,

děkuji..funguje. Ale proč mi nešli klíče, které jsem si generoval na https://iplatebnibrana.csob.cz/keygen/ ?

každopádně děkuji za pomoc

**Comment by ratajskym** [comment]
Dobrý den, 
privátní klíč vygenerovaný [aplikací ](https://iplatebnibrana.csob.cz/keygen/) slouží k podepisání Vašich zpráv. Veřejný klíč stažený z repozitáře platební brány slouží k ověření zpráv, které posílá právě platební brána
