### ISSUE TITLE
Implementace

### ISSUE THREAD

**Issue by krouza** [csob/paymentgateway#129]
Dobrý den.

Potřeboval bych poradit ohledně nové platební brány:
Používáme  pro e-shop systém od společnosti Zoner. Poslal jsem jim klíče, v systému nastavil ID merchant, ale když se má zaplatit kartou, stále to hlásí

Platba nemůže být provedena
Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba.Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.

Podle Zoneru mají vše nastavené správně a mám Vás kontaktovat, "co Vám posílají špatně".

Můžete mi prosím poradit?

Předem děkuji,

Miloslav Kroužek

Merchant ID: M1E3CB1217

Název obchodního místa: diag4bike.inshop.cz

**Comment by Miculka** [comment]
Dobrý den. 

Jste aktivní v testovacím i produkčním prostředí. 

Chápu dobře, že testovací (integrační) prostředí jste přeskočili z důvodu přechodu z GP Webpay?

V produkci vidím, že klíče pro produkci byly vygenerovány a odeslán potvrzovací kod na váš email.

V testovacím prostředí vidím dnešní snahu 27.1.2016, ale systém říká, že nemá klíče. 

Takže problém bude s největší pravděpodobností na straně URL zde správná  : https://api.platebnibrana.csob.cz/
