### ISSUE TITLE
Předávání obsahu košíku na platební bránu

### ISSUE THREAD

**Issue by petr-goca** [csob/paymentgateway#13]
Ve specifikaci jsme se dočetli o povinnosti předat na bránu "obsah košíku", ale je zde aktuálně omezení na max. 2 položky. Pro nás to tedy znamená, že bráně nemůžeme předat výčet produktů, dopravného apod. odděleně v jednotlivých položkách (protože tohoto je prakticky vždycky více než 2 položky), ale předáme sem jen jednu položku souhrnně pojmenovanou např. „celková cena“ s celkovou cenou transakce.

Pokud do budoucna omezení na 2 položky zmizí, mohli bychom sem předávat jednotlivé řádky z košíku eShopu.

Chápeme toto správně?

**Comment by dmarek** [comment]
Ano, omezení na max. 2 položky jsou z důvodu grafické úpravy platební brány, v další verzi bude tento limit zrušen. Nyní tedy můžete plnit košík dvěma položkami, např. "nákup ..." a "dopravné".
