### ISSUE TITLE
Automatické zaúčtování po 4 dnech

### ISSUE THREAD

**Issue by KuchynskePotrebyCZ** [csob/paymentgateway#130]
Dobrý den,
prosím o informaci, které proměnné mají na starosti automatické zaúčtování transakce (eAPI v1)?

Resp. které proměnné upravit, aby byla platba automaticky zaúčtována po 4 dnech?

Děkuji.

**Comment by dmarek** [comment]
Dobry den,

v ramci `payment/init` muzete pomoci `closePayment` zvolit, zda bude transakce automaticky zarazena do zuctovani anebo bude pouze ve stavu autorizovana a do zuctovani ji zaradite explicitne volanim payment/close (napr. po uplynuti 4 dnu anebo po kontrole, ze zbozi je na skladu a zakazka byla expedovana apod)

Staci takto?

**Comment by KuchynskePotrebyCZ** [comment]
Dobrý den,
moc děkuji za zprávu, předávám programátorovi.

S pozdravem,

*Ing. Lukáš Blažek*

E-Commerce Manager
Nám. 17. listopadu 298
261 01, Příbram VII
tel.: 602 754 471
www.KuchynskePotreby.cz <http://www.kuchynskepotreby.cz/>

<http://www.kuchynskepotreby.cz/>

Dne 29.1.2016 v 10:57 Daniel Marek napsal(a):
>
> Dobry den,
>
> v ramci |payment/init| muzete pomoci |closePayment| zvolit, zda bude 
> transakce automaticky zarazena do zuctovani anebo bude pouze ve stavu 
> autorizovana a do zuctovani ji zaradite explicitne volanim 
> payment/close (napr. po uplynuti 4 dnu anebo po kontrole, ze zbozi je 
> na skladu a zakazka byla expedovana apod)
>
> Staci takto?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/csob/paymentgateway/issues/130#issuecomment-176673122>.
>

--
