### ISSUE TITLE
Produkční prostředí - woo commerce

### ISSUE THREAD

**Issue by hrncir39** [csob/paymentgateway#131]
Dobrý den, nedaří se mi přejít do produkčního prostředí, i když jsem provedl testovací platby přes bránu a nastaveni:

Brána: https://iapi.iplatebnibrana.csob.cz/api/v1
veřejný klíč: mips_iplatebnibrana.csob.cz.pub
priv. klíč: rsa_M1MIPS0333.key
heslo: ********

Jedna se o Woo commerce. 

Na adrese  https://platebnibrana.csob.cz/keygen/ nelze vygenerovat key pro produkci.(Zadali jste nesprávný merchant ID nebo e-mail.)

obchodník: M1MIPS0333

**Comment by ratajskym** [comment]
Dobrý den, 

je to způsobeno tím, že je Váš merchant blokovaný. Poslal jsem dotaz na zodpovědné lidi

**Comment by ratajskym** [comment]
Dobrý den, 

testovacím prostředím jste neprošel. Vraťte se do aplikace posmerchant, stiskněte tlačítko provést validaci a uvidíte, co Vám chybí.
