### ISSUE TITLE
ResultCode 999

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#132]
Už několikrát nám brána vrátila při opakované platbě resultCode 999. V dokumentaci ho nevidím, co znamená?

**Comment by Miculka** [comment]
Dobrý den. 

Z kraje bych Vás chtěl poprosit o identifikační údaje - tj. ID Merchant by mi pomohlo. 

Opakovanou platbu - využíváte eAPI 1.5 a máte uloženou kartu s kterou provádíte opakovanou platbu?

Děkuji.

**Comment by janlanger** [comment]
Merchat ID M1E3CB0860

PayId prvotní platby fe93732cec3c9BA, identifikaci transakce která skončila stavem 999 bohužel nemám, pouze variabilní symbol - 7050266909.
Zákazníkovi se dalším pokusem podařilo transakci dokončit.

**Comment by janlanger** [comment]
@Miculka můžu požádat o nějaké vyjádření? Co znamená resultCode 999?

**Comment by dmarek** [comment]
ve vasem pripade se jednalo o opakovane platby (pro prvotni platbu fe93732cec3c9BA)

2fb0f99f46203BB
16e31915f5d0eBB
c722a693705b0BB
ea1591a2425adBB
76002505b4827BB

ktere byly korektne zamitnuty na expirovanou platebni kartu (platnost do 1601, posledni autorizovana opakovana platba probehla 31.1.2016)

result code 999 je obecna chyba, doplnime do dokumentace
u specifickych pripadu zamitnuti u opakovanych plateb rozsirime navratove kody v nove verzi eAPI o nove hodnoty

**Comment by janlanger** [comment]
Ok, očekával bych tedy spíše klasickou response se zamítnutím, tzn. result code 0, payment status 6. Reagovat na expiraci stavem obecná chyba je takové zvláštní...

**Comment by janlanger** [comment]
@dmarek @Miculka máte v planu toto chování změnit, tedy aby odpovědí bylo normální zamítnutí a ne stav obecná chyba který může znamenat cokoliv?

**Comment by dmarek** [comment]
@janlanger ano, opraveno, predano do testovani. V pripade expirovane karty bude result code bude 0, payment status 6

**Comment by kukulich** [comment]
@dmarek Kdy přibližně bychom mohli očekávat nasazení na produkci? Děkuji.

**Comment by janlanger** [comment]
ping @dmarek @Miculka

**Comment by dmarek** [comment]
uvedeny fix je soucasti vetsiho baliku zmen, predpokladam, ze v ramci pristiho tydne by mohl byt na produkci.

**Comment by kukulich** [comment]
@dmarek Je možné se nějak dostat k seznamu těch změn, abychom byli schopni otestovat, zda nám vše funguje?

**Comment by dmarek** [comment]
nasazeno na produkci, pripravujeme changelog
