### ISSUE TITLE
Returning money to customer ( refund)

### ISSUE THREAD

**Issue by gnakry** [csob/paymentgateway#136]
Hi,

when a customer purchase a good from our eshop, and he realizes that he doesn't like the product and we have to refund him? how does it work? since I don't have his account number. I just see the card that is linked to it? Also how long does it take for the money to get to the customer's account?
Thanks

**Comment by vzich** [comment]
Hi,
if you have an account on POSmerchant you can easily reverse payments through its web interface.  We proceed these requests immediately to bank where it can take a few days to complete reverse transaction. Or as another possibility you can use reverse and refund method right from your eshop https://github.com/csob/paymentgateway/wiki/eAPI-1.5#puthttpsapiplatebnibranacsobczapiv15paymentrefund-https://github.com/csob/paymentgateway/wiki/eApi-1.5#put-httpsapiplatebnibranacsobczapiv15paymentreverse- 

Regards,
VZ

**Comment by gnakry** [comment]
Thanks for the  answer, makes sense, now how long does it for the refund most of the time, roughly?
because we need to mention this in our return and refund policy.
Thanks

**Comment by radehorak** [comment]
Hello,

In general, once an amount is refunded, on the next day the amount is transmitted to issuer (cardholder´s bank). Then it depends when the issuer credits cardholder´s account with the refund. It takes about 3 days.

Regards,

Radek
