### ISSUE TITLE
Přesměrování z platební brány na mobilu nefunguje

### ISSUE THREAD

**Issue by SrubarChaps** [csob/paymentgateway#138]
Dobrý den,
při testování nativní aplikace eShop na mobilu máme následující problémy:

1.
Telefon CAT B15, Android 4.1.2. výchozí webový Prohlížeč (Browser 4.1.2.-eng, cme01.1367398115)
Testujeme nákupy našem eShopu 
V testovací platební bráně ČSOB máme možnost zaplatit MasterCard Mobile. Po této volbě spadne prohlížeč v různých okamžicích (někdy hned po zvolení platby nebo při volání InCard aplikace). Naposledy se to stalo 8.2.2016 v 9:14
Navíc to má dva výsledky: 
  a.	Browser je defaultní – tak po opětovném spuštění Browseru se platba dokončí
  b.	Browser není defaultní – tak po opětovném spuštění Browseru se již neotevře a z pohledu uživatele je ztracena (nastalo 8.2. v cca 8:40)
Platby pomocí platebních karet probíhají bez problémů v obou prohlížečích.

2.
Na stejném mobilu na prohlížeči Chrome (verze 47.0.2526.83) máme jiný problém. 
Pro přesměrovaní dokončené platby do aplikace používáme mezistránku, na kterou přijde odpověď od CSOB platební brány a která po zaúčtování provede přesměrování do nativní aplikace (přes `<script>window.location.replace("neco://...."); </script>` vložené na začátek stránky).
Tato konstrukce většinou funguje, pouze v případě, kdy se na výše popsaném mobilu použije platební metoda MasterCard Mobile, tak přesměrování z mezistránky do aplikace nedojde a ani se mezistránka nezobrazí, přitom zaúčtování se provede, tedy k přesměrování z platební brány do mezistránky dojde. Jelikož při normální platbě k takovému chování nedochází, přestože url pro přesměrování je stejné, podezříváme platební bránu, že při použití platební metody MasterCard Mobile nějak naruší chování prohlížeče.

Oba popsané problémy nastávají pouze na výše uvedeném mobilu, ostatní mobily a ani browser na desktopu problémy nemá.

Zdraví
Ondřej Šrubař

**Comment by ratajskym** [comment]
wont fix
