### ISSUE TITLE
POS merchnat  - chyby v PDF účtence

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#139]
PDF účtenka kterou lze generovat z rozhraní POSmerchant obsahuje nesprávné a neúplné údaje

- částka je zaokrouhlena na celé číslo (př. M1E3CB0959 - payId 71f7a60334274BB - zaplaceno 4,99 EUR, na účtence je 4,00)
- vůbec nezohleňuje vratky, ani částečné ani kompletní

Prosím o opravu chybných částek a případně vylepšení o vratky.

**Comment by vzich** [comment]
Dobrý den,
částky jsou opravené a budou nasazeny v nové verzi.
Co se týče účtenek, tak ty jsou tisknuty pouze k původní transakci. 

S pozdravem 
VZ

**Comment by janlanger** [comment]
Díky
