### ISSUE TITLE
Use Casy pro vrácení z platební brány na web

### ISSUE THREAD

**Issue by petr-goca** [csob/paymentgateway#14]
Ve specifikaci jsme nenašli Use Casy situace, kdy je člověk vrácen z platební brány na eShop. Tedy něco ve smyslu, že je uživatel přesměrován z platební brány na OK nebo NOK stránku eShopu, že v případě OK se má eShop ještě jednou zeptat platební brány na status transakce atd.

Z pohledu bezpečnosti aplikace je tento krok důležitý a Use Case by zde myslíme byl žádoucí. Podobné Use Casy specifikace GP WebPay má a podle nás je vhodné toto podchytit i ve Vaší specifikaci, aby dokončení transakce a její ověření doběhlo ze strany eShopu korektně.

**Comment by dmarek** [comment]
Díky za Váš podnět, zapracujeme jej do dokumentace k eAPI. Nyní je tam pouze zmínka o možnosti volat kdykoliv `payment/status` pro zjištění aktuálního stavu. Jsou nicméně situace, které z podstaty rozumně ošetřit nelze (např. zavření prohlížeče zákazníkem předtím, než se provede závěrečné přesměrování z platební brány do eshopu anebo výpadek spojení při tomto přesměrování) a tam je právě volání `payment/status` jedinou možností, jak tyto věci napravit.

**Comment by petr-goca** [comment]
Děkuji za odpovědi ke všem mým Issues.

K tomuto Issue: Dokud nejsou zmíněné Use Casy hotové, rád bych se zeptal konkrétněji na:

1) ve chvíli, kdy platební brána přesměruje uživatele zpět na returnUrl, je možné se spolehnout na to, že už transakce není ve stavu 1 (Platba založena) ani 2 (Platba probíhá)?

2) je potřeba při návratu uživatele z platební brány volat payment/status nebo je možné se spolehnout na resultCode = 0 (a ověření signature) a takovou transakci považovat za úspěšnou?

Děkuji.

**Comment by petr-goca** [comment]
Dobrý den, rád bych se připomenul s mými 1 měsíc starými dotazy. Děkuji.

**Comment by ratajskym** [comment]
Dobrý den

add 1 - ano, pokud proběhne přesměrování zpět na eshop není transakce ve stavu 1 ani 2
add 2 - ano, pokud se povede ověření podpisu nemusíte volat metodu payment/status. Nicméně je potřeba rozlišovat resultCode a payState
