### ISSUE TITLE
Po obnovení konektivity na mobilním zařízení nahlásí brána Platba nenalezena.

### ISSUE THREAD

**Issue by SrubarChaps** [csob/paymentgateway#141]
Dobrý den,
platební brána hlásí platba nenalezena i když platba proběhla úspěšně.
Chyba nastává v okamžiku, kdy došlo k přerušení spojení a opětovnému načtení platební brány v prohlížeči. Poté však pomocí funkce Ověření stavu platby zjistíme, že platba byla uhrazena.
Id platby - 7ff5ad2673e8cBB

Zařízení - CAT B15, Android 4.1.2, defaultní prohlížeč 4.1.2 

![screenshot_2016-02-16-14-01-39](https://cloud.githubusercontent.com/assets/16815084/13077303/361da3c6-d4b8-11e5-93d9-728316221ca4.png)

**Comment by dmarek** [comment]
Bylo obnovene spojeni pres jineho providera? (z wifi na mobilni data apod?) V logu vidime, ze se zmenila klientska ip adresa, brana tyto zmeny monitoruje a nedovoli pro danou platbu pristoupit z jine klientske ip adresy.

**Comment by SrubarChaps** [comment]
Děkuji za odpověď, ano je to celkem možné. Ještě ověřím u testerů.

**Comment by SrubarChaps** [comment]
Takže, ip se mění (už jen tím, že se přeruší datový přenos), ale chování platební brány je dle nás nesprávné, protože takový stav může v provozu normálně nastávat. 
Minimálně by se měla platební brána zachovat konzistentně - buď platbu zrušit a i  následné ověření stavu platby by pak mělo vracet, že byla platba zrušena, nebo naopak platbu umožnit.

**Comment by ratajskym** [comment]
Dobrý den, 
chování je konzistentní

- pokud přistoupíte z jiné ip adresy, než byl původní požadavek, platba nebude existovat
- pokud znovu přistoupíte z původní ip adresy, můžete platbu dokončit

Pokud platbu během 30min životního cyklu nedokončíte, skončí jako expirovaná

**Comment by SrubarChaps** [comment]
Dobrý den, 
tak jsme se k tomu zase dostali, a podle nás to konzistení není.
Scénář - zahájíme platbu (init), přesměrujeme se na platební bránu, změníme ip a dáme dokončit. Stránka vypíše výše uvedenou chybu. Pak dáme ověřit platbu (funkce status pod novou ip) a platební brána vrátí stav 7 (čeká na zůčtování) - tj. že platba proběhla.

Zkoušel jsem to dneska (18.3.2016), id platby je 5bfd12d74abbaBC.
Pokdu budet chtít, mohu vám poslat celý komunikační log.

**Comment by MilanVilim** [comment]
Dobrý den,
chtěl jsem se zeptat, zda je tento problém nějak řešen? Prosím o informaci. Děkuji.

**Comment by dmarek** [comment]
omlouvam se za pozdni rekaci, kontrola ip adres byla pred casem upravena, zminovane chovani by se uz dit nemelo
