### ISSUE TITLE
Ověření odpovědi z platební brány

### ISSUE THREAD

**Issue by PeterekM** [csob/paymentgateway#142]
Dobrý den,
v této chvíli programujeme „Přechod z již používané platební brány GP Webpay“. Nedaří se nám ověřit odpověď, kterou dostaneme od platební brány. Můžete nám prosím poradit? Jako odpověď dostaneme:

OPERATION=CREATE_ORDER
ORDERNUMBER=201674193
MERORDERNUM=201674193
PRCODE=0
SRCODE=0
RESULTTEXT=OK
DIGEST= nejaky_string_0
DIGEST1= nejaky_string_1

Do funkce openssl_verify, která má na starost ověření dáváme toto: (‘CREATE_ORDER|201674193|201674193|0|0|OK‘,‘base64_decode(nejaky_string_0)‘, ...)
Zajímalo by mě, které parametry z odpovědi by měly přijít do funkce openssl_verify, nedáváme tam DIGEST, DIGEST1.

**Comment by Miculka** [comment]
Dobrý den. Odpoveď na email jsem posílal do banky, zde je co jsem psal. 

S největší pravděpodobností Vám chybí ještě veř. Klíč brány, který v tomto případě ověřuje odpověď, kterou postrádáte. 

Ke stažení zde - https://github.com/csob/paymentgateway/tree/master/keys

Transakce ze dne 16.02.201616:12:48 na částku 69 CZK byla autorizována a odeslána do PTFL – takže tady problém nevidím. 

Neúspěšná autorizace toho dne dřívějšího času byla způsobena neznámím BIN Card. 

S pozdravem
