### ISSUE TITLE
Prestashop

### ISSUE THREAD

**Issue by VladimriBozik** [csob/paymentgateway#143]
Dobrý den,
rád bych zprovoznil platební bránu na systému prestashop na firemním eshopu. Pro starší systém GP WebPay existují různé moduly, pro tento nový se mi nepovedlo najít žádný, ale placený ani free. Vzhledem na charakter modulu, nerad bych jeho tvorbu zadal leckomu. Můžete prosím poradit, případně nasměrovat na koho se obrátit?

Děkuji za odpověď.

**Comment by ratajskym** [comment]
Dobrý den, 
původní modul s novou bránou nefunguje? Zkoušel jste to?

**Comment by VladimriBozik** [comment]
Zatím jsem nezkoušel. Oslovil jsem prodejce modulu a čekám na vyjádření. Zatím jsem dostal pouze takové, že by to mělo fungovat. Asi to však budu muset ověřit přímo na webu.

**Comment by ratajskym** [comment]
Jestli máte testovací instanci webu, nic Vám nebrání otestovat to proti našemu testovacímu prostředí.

**Comment by VladimriBozik** [comment]
Eshop je v ostrém provozu, ale možnost testování nějak vymyslím.

**Comment by digiage** [comment]
dobrý den, nějak se tato otázka vyřešila? také řeším napojení Prestashopu 1.7 na ČSOB payment gateway

**Comment by Mspisar** [comment]
Dobrý den,

veškeré pluginy jsme oficiálně přestali podporovat. Vzneste prosím dotaz přímo na Prestashop.

s pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by digiage** [comment]
Dobrý den, Milane, 

Díky za rychlou odpověď. Byl to spíše dotaz na pana Božika.

Nicméně i přesto, že nepodporujete pluginy, je úprava stávajícího kódu komplikovaná/nemožná, nebo lze podle tohoto postupu bránu jednoduše upravit z GP webpay na ČSOB payment gateway? https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

Případně nějaká neoficiální (vámi nepodporovaná cesta) například v podobě neoficiálního modulu.

Díky

**Comment by VladimriBozik** [comment]
Dobrý den.
Je to již pár let, tak bohužel nevím zda se to povedlo vyřešit. Ale bránu
pro ČSOB nevyužívám.

S pozdravem

Vladimír Božik
Dopler Studio s.r.o.
Rybářská 2112/15
709 00 Ostrava
GSM: +420 603 352 434
email: ***@***.***
www.dopler.eu

**Comment by Mspisar** [comment]
Dobrý den,

úprava modulu je spíše dotaz na vývojáře. Co se týká funkčních a již nepodporovaných modulů fungoval woocommerce.

s pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by digiage** [comment]
Tak ještě jinak. Modul bych si upravil sám. Šlo mi o to, jestli jste použili implementaci z GP webpay a změněná by byla například jen URL endpointu. Podle tohoto článku to tak vypadá: https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

**Comment by janbrasna** [comment]
@digiage To byla cesta pro obchodniky, kteri prechazeli z puvodni CSOB GPWP brany, tzn. novych obchodniku dnes uz se to asi ani nema jak tykat.  Co se pluginu a API tyce, tak pokud spolehaji napr. na SOAP komunikaci, tak to v migraci nefungovalo nikdy, ani v tom legacy modu. Ale to prave musi vedet ci vyzkouset prave autor pluginu atp., zhruba pred 10 lety byla nejaka API kompatibilita na zakladni funkce (zalozeni trx a navrat zpet), ale to se za tu dekadu mohlo zmenit, tj. ani pro obchodniky z te doby nedokazu odhadnout, zda by plugin z dnesni verze GPWP pro jine banky mohl "nejakym hackem" fungovat zde.
