### ISSUE TITLE
Reverse/refund šablony pro recurring platbu

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#144]
Dobrý den, prosím o informaci, jak správně pracovat s objednávkou která je šablonou pro recurring platbu v případě že dochází k jejímu stornu.

Během implementace jsme od ČSOB dostali informaci, že v případě že dojde k zaúčtování prvotní platby, tak zůstává platná pro recurring platby i když je později celá stornovaná.
Zdá se mi ale že to tak úplně nefunguje. U následujících prvotních objednávek došlo po několika dnech (takže už měli být zaúčtované) ke stornu ale následně už se zákazníkům pomocí nich nepodařilo zaplatit.

M1E3CB0959 - f506a871a8056BA
M1E3CB0860 - 5b14c04422e71BA

V obou případech se nám vrátil response code 150 s textem "orig payment not authorized"

**Comment by Miculka** [comment]
Dobrý den. Rád bych Vás poprosil o trochu bližší specifikaci toho co očekáváte. 

U obou objednávek proběhla v pořádku autorizace - poté proběhl o několik dní dále reverzal plateb. 

Co dále by jste s těmi objednávkami chtěl dělat? Děkuji

**Comment by janlanger** [comment]
obě payId byly označené jako recurrentPayment v payment/init

Má otázka je jestli platby zústávají platné jako prvotní objednávka pro payment/recurrent i pokud byly celé stornované. Během implementace brány jsme dostali informaci že ano pokud byly před stornem zaúčtované, ale z odpovědí brány se zdá že tomu tak minimálně někdy není.

**Comment by janlanger** [comment]
@Miculka můžu poprosit o nějakou reakci?

**Comment by dmarek** [comment]
Diky za pripominku, stavajici chovani platebni brany upravime, pokud prvotni opakovana platba projde zauctovanim, bude mozne provadet nasledne opakovane platby bez ohledu na to, zda se prvotni platba (castecne nebo uplne) refunduje.

**Comment by dmarek** [comment]
budu informovat o nasazeni na integracni a produkcni prostredi

**Comment by dmarek** [comment]
bugfix nasazen na integracnim prostredi

**Comment by dmarek** [comment]
bugfix nasazen i na producknim prostredi
