### ISSUE TITLE
Opět ResultCode 900 na produkční bráně

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#145]
Opět se nám objevilo několik případů kdy brána vrací internal error 900. Tentokrát jde o prohlížeč s UA
`Mozilla/5.0 (Linux; Android 4.4.2; SM-N7505 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 SlevomatAndroid`
čili mobilní Chrome 30. Měl by být tedy podporovaný.

PayId 6c30119f1956aBB, merchant M1E3CB0860

Co je důvodem 900 tentokrát?

**Comment by Miculka** [comment]
Dobrý den. 

Tak ačkoliv to vypadá, že by to mělo být podporované, tak není. 

Viz. log - message": "Unsupported browser, header: mozilla/5.0 (linux; android 4.4.2; sk-sk; samsung sm-n7505 build/kot49h) applewebkit/537.36 (khtml, like gecko) version/1.5 chrome/28.0.1500.94 mobile safari/537.36, parsed: UserAgent [deviceCategory=DeviceCategory [category=SMARTPHONE, icon=phone.png, infoUrl=/list-of-ua/device-detail?device=Smartphone, name=Smartphone], family=CHROME_MOBILE, icon=chrome.png, name=Chrome Mobile, operatingSystem=OperatingSystem [family=ANDROID, familyName=Android, icon=android.png, name=Android 4.4 KitKat, producer=Google, Inc., producerUrl=http://www.google.com/, url=http://en.wikipedia.org/wiki/Android_%28operating_system%29, versionNumber=VersionNumber [groups=[, , ], extension=]], producer=Google Inc., producerUrl=http://www.google.com/, type=MOBILE_BROWSER, typeName=Mobile Browser, url=http://www.google.com/intl/en/chrome/browser/mobile/, versionNumber=VersionNumber [groups=[28, 0, 1500, 94], extension=]]",

**Comment by Miculka** [comment]
předávám ještě na vývoj, pro odbornější vyjádření.

**Comment by dmarek** [comment]
@janlanger jeste dotaz - byl pouzit jeden a ten samy telefon/browser?

v case 26.02.2016 16:06:16 je pristup s podporovaneho

Compatible user agent: mozilla/5.0 (linux; android 4.4.2; sm-n7505 build/kot49h) applewebkit/537.36 (khtml, like gecko) version/4.0 chrome/30.0.0.0 mobile safari/537.36 slevomatandroid

o par sekund pozdeji 26.02.2016 16:06:25 (ta sama transakce) je to uz nepodporovany prohlizec ...

 User agent not supported: mozilla/5.0 (linux; android 4.4.2; sk-sk; samsung sm-n7505 build/kot49h) applewebkit/537.36 (khtml, like gecko) version/1.5 chrome/28.0.1500.94 mobile safari/537.36

**Comment by janlanger** [comment]
Je to prý strašně nepravděpodobné, ale možné ze má uživatel nižší verzi prohlížeče než webview komponenty v aplikací. Uzaviram.
