### ISSUE TITLE
Akceptace karet v testovacim rezimu

### ISSUE THREAD

**Issue by rjansky** [csob/paymentgateway#146]
Dobry den,

testovaci platebni branu mame implementovanou do eshopu a po kliknuti na Zaplatit se dostanu na vasi platebni branu, ale nedari se mi zaplatit ani jednou z mych platebnich karet (2x KB, 1x CSOB). Jakym zpusobem to ma fungovat?

Pise mi to: 
"Vase platba byla zamitnuta z duvodu blokace karty. Pouzijte prosim jinou kartu nebo se vratte na delikatesy.online a vyberte jinou platebni metodu.”

Dekuji
R. Jansky

**Comment by ratajskym** [comment]
Dobrý den, funguje to přesně podle [dokumentace](https://github.com/csob/paymentgateway/wiki/Testovac%C3%AD-karty)
