### ISSUE TITLE
Editace detailu platebni brany

### ISSUE THREAD

**Issue by rjansky** [csob/paymentgateway#147]
Dobry den,
v POS Merchant bychom potrebovali v detailu platebni brany zmenit kontaktni udaje, ktere se pak zobrazuji zakaznikovi. Jakym zpusobem to udelat?

R. Jansky

**Comment by aKocian** [comment]
Dobrý den,

pro editaci údaju je zapotřebí obrátit se na banku.  (akceptacekaret@csob.cz)
