### ISSUE TITLE
Nejasné využití návratové hodnoty "authCode"

### ISSUE THREAD

**Issue by petr-goca** [csob/paymentgateway#15]
Ve specifikaci máte zmíněnou návratovou hodnotu „authCode“, ale nevíme, k čemu nám je dobrá. Má pro eShop smysl tuto hodnotu nějak zpracovávat?

Bylo by fajn toto mít podchycené v Use Casu, který zmiňuji v https://github.com/csob/paymentgateway/issues/14

**Comment by dmarek** [comment]
Autorizační kód (vrací se v případě úspěšně autorizované transakce) je pro obchodníka důležitý v případě, kdy zboží odešlo zákazníkovi ale na účet nepřišla platba. Pomocí něj (a dalších doplňujících údajů jako je datum a čas platby, číslo objednávky) lze "vypátrat" danou platbu.
