### ISSUE TITLE
Termin prevodu financnich prostredku

### ISSUE THREAD

**Issue by rjansky** [csob/paymentgateway#150]
Dobry den,
minuly tyden jsem spustili platebni branu do produkcniho prostredi. Stahnul jsem si ted vypis transakci v POS Merchantu, ale na bankovnim uctu nevidim nikde pripsane financni prostredky a to ty platby probehly a vyly zauctovany 4.3.2016. Kdy budou penize na ucet pripsany?

Dekuji
R. Jansky

**Comment by hanuss** [comment]
Muzete nam prosim zaslat identifikaci platební brany (MIPSxxxx / E3CBxxxx) nebo alespon Vase IC ? 
Dekuji
Hanus

**Comment by rjansky** [comment]
02110709

Roman Jansky
Gruber Feinkost s.r.o.
delikatesy.online




On Fri, Mar 11, 2016 at 5:02 AM -0800, "Štěpán Hanuš" <notifications@github.com> wrote:












Muzete nam prosim zaslat identifikaci platební brany (MIPSxxxx / E3CBxxxx) nebo alespon Vase IC ? 

Dekuji

Hanus

**Comment by hanuss** [comment]
Dobry den, 
obe castky z vypisu (MCI, VIS) Vam byly pripsany na Vas ucet dne 7.3.2016.
Hanus
