### ISSUE TITLE
Přechod do produkčního prostředí

### ISSUE THREAD

**Issue by SumLord** [csob/paymentgateway#151]
Dobrý den,
na testovacím prostředí jsem si vygeneroval klíče bez problému, když se ale snažím o to samé i na produkční adrese https://platebnibrana.csob.cz/keygen/ se stejnými údaji (tedy ses stejným Merchant ID i emailem jako na testu), aplikace vypíše hlášku "Zadali jste nesprávný merchant ID nebo e-mail."
Je u generování produkčních klíčů nutný nějaký speciální postup?
Předem děkuji za odpověď

**Comment by ratajskym** [comment]
Dobrý den, 
produkční klíče můžete vygenerovat v případě, že Váš merchant není blokovaný. Zároveň musí souhlasit merchant id a technický email, který jste zadali do smlouvy s ČSOB.

**Comment by SumLord** [comment]
U otázky 131 https://github.com/csob/paymentgateway/issues/131 jsem se dozvěděl, že se v POSMerchant dá tlačítkem "Provést validaci" zobrazit, z jakého důvodu je Merchant blokovaný. Takové tlačítko jsem ale nikde nenašel, můžu poprosit o bližší popis?
Také bych se rád zeptal, jakým způsobem se u pluginu pro Woocommerce testuje reverzovaná platba.
Předem děkuji za odpověď

**Comment by Miculka** [comment]
Dobrý den. V POSMerchant máte ikonku klíčů - viz. screen a po kliknutí je tam možnost provést validaci. 
![image](https://cloud.githubusercontent.com/assets/14308839/13792273/5cf85fb4-eaf1-11e5-8b7d-2b2f01436665.png)

**Comment by SumLord** [comment]
Pod tlačítkem klíče se mi bohužel zobrazí jen text: "Nemáte žádný nový požadavek na zavedení klíče" a tlačítko Zrušit. Možnost Provést validaci bohužel nevidím.

**Comment by Miculka** [comment]
Zkuste to prosím v integračním prostředí. Nyní to zkoušíte v produkci.

**Comment by SumLord** [comment]
Do integračního prostředí jsou jiné přihlašovací údaje než do produkce? Od zákazníka jsem dostal jen jedny a na ty se nedaří na test přihlásit.
A ještě bych vás rád poprosil o popis testu rezervované platby v pluginu pro Woocommerce.
Předem děkuji

**Comment by ratajskym** [comment]
Dobrý den, 

přihlašovací údaje jsou stejné pro testovací i produkční prostředí. 
Woocommerce reversal pokud vím nepodporuje. Pokud jej tedy nebudete využívat, stačí tuto informaci poslat na akceptacekaret@csob.cz a oni Vás aktivují v produkci i bez splnění tohoto kroku.

**Comment by SumLord** [comment]
Bohužel mi testovací prostředí (https://iposman.iplatebnibrana.csob.cz/posmerchant) při přihlašování vypíše "Nepodařilo se přihlásit do systému", přestože se přihlašuji stejnými údaji jako do produkčního POSMerchant.

**Comment by ratajskym** [comment]
Vzhledem k tomu, že od Vás nemám žádnou konkrétní informaci, těžko můžu něco dohledat a zanalyzovat. Pošlete prosím Vaše údaje (merchant id, ico, mail, odkaz na tohle issue) na adresu  akceptacekaret@csob.cz

**Comment by SumLord** [comment]
Pokud to někomu pomůže, ČSOB zaslala zákazníkovi údaje speciálně pro testovací verzi POSMerchant a platební brána byla aktivována i bez testu reverzované platby (plugin pro Woocommerce).
