### ISSUE TITLE
Dlouhotrvající zaúčtování vratky

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#152]
Dobrý den,

v některých případech se nám stává, že zaúčtování (částečné) vratky trvá i týden. Jindy je to zaúčtované druhý den. Co to ovlivňuje?

Je to docela problém, protože pak zákazník dlouho čeká na peníze, a pokud dojde k dalšímu částečnému stornu, tak jej nelze poslat do API dokud se to první nezaúčtuje.

Šlo by to nějak vylepšit?

Konkrétně teď jde např. o transakci 22c5dfe660b88BC, merchant M1E3CB0860. Ve stavu "Požadavek na reverzování transakce" visí už od 10.3.

**Comment by radehorak** [comment]
Dobrý den,
aspektů může být více, ale většinou je to problém vydavatelské banky. Každopádně Váš případ prověříme u karetní asociace, abych vědět o daná transakci více informací.
S pozdravem
Radek Horák

**Comment by janlanger** [comment]
@radehorak Máte k tomu nějaké podrobnější informace? Zaúčtování vratky trvalo 11 dní.

**Comment by ratajskym** [comment]
Věřím, že se jednalo o jednorázovou záležitost. Issue uzavírám
