### ISSUE TITLE
kontrola "autorizované nezaúčtované" transakce

### ISSUE THREAD

**Issue by zdenekgebauer** [csob/paymentgateway#153]
Kontrola implementace brány po přechodu z gpwebpay vypisuje požadavek "Nenalezena transakce se stavem: Autorizace potvrzena/Posláno k zaúčtování Musíte udělat alespoň jednu autorizovanou nezaúčtovanou transakci"

Samotná platba prochází, ověření podpisu také. Vyzkoušel jsem všechny CVV kódy uvedené na https://github.com/csob/paymentgateway/wiki/Testovac%C3%AD-karty . Co přesně je třeba provést pro vytvoření takovéto transakce?

**Comment by ratajskym** [comment]
Dobrý den, 

popis požadovaných stavů transakcí naleznete na [wiki](https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD#%C3%9Asp%C4%9B%C5%A1n%C4%9B-autorizovan%C3%A1-platba)
