### ISSUE TITLE
Hodnota CVC/CVV 200 Obecné zamítnutí

### ISSUE THREAD

**Issue by simPod** [csob/paymentgateway#154]
Dobrý den, chci se zeptat co znamená Obecné zamítnutí při pokusu o platbu kartou? V jakých případech se tato response vrací? Děkuji

**Comment by ratajskym** [comment]
Dobrý den, 

jedná se o hlášku, kdy není přesně definovaný důvod resp. může se jednat o zamítnutí na straně karetní asociace bez udání důvodu. Pokud máte konkrétní transakci, kdy Vás přesný důvod zajímá, můžeme se pokusit ji zanalyzovat.
