### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by nedoff** [csob/paymentgateway#155]
Hello. I try to integrate the payment gateway script https://github.com/csob/paymentgateway/tree/master/Integration%20Examples/eAPI%20v1.5/php from your bank in my site http://elegancewear.eu

I generated keys for instructions Merchant ID: M1MIPS0530 But the script does not pass the test. Work stopped in the code

if (verifyResponse ($ result_array, $ publicKey, "payment / init verify") == false) {
echo 'payment / init failed, unable to verify signature';
return;
}

**Comment by Miculka** [comment]
Hi. 

Your problem is Invalid paymentInit signature for M1MIPS0530.

Do you have right keys?
Generate on https://iplatebnibrana.csob.cz/keygen/
And still need public certificate from https://github.com/csob/paymentgateway/tree/master/keys

Please repair it and try again. 

Regards.

**Comment by ratajskym** [comment]
@nedoff Hello, can you confirm that everything is working on your side?
