### ISSUE TITLE
Podpis požadavku .net

### ISSUE THREAD

**Issue by jan1971** [csob/paymentgateway#156]
Dobrý den.
Implementuji platební bránu do .net aplikace.
Otázka 1. není k dispozici nějaký kód, z kterého by se dalo vyjít?
Otázka 2. Procházel jsem vzorovou aplikaci v PHP a při generování podpisu se krom klíče operuje ještě s heslem. Předpokládám, že jde o heslo, které se vkládá při generování klíče pomocí JAVA aplikace. Mě se však na https://iplatebnibrana.csob.cz/keygen/ vygenerovali rovnou klíče. Heslo tedy nemám...
Děkuji.

**Comment by ratajskym** [comment]
Dobrý den, 

add 1.) je mi líto, .net example není k dispozici
add 2.) klíče jsou bez hesla

**Comment by jan1971** [comment]
Dobrý den.
Takže při vytváření podpisu heslo vynechám, nebo použiji prázdný řetězec? 
(Jde o funkci sign v php examplu)
Děkuji.

**Comment by ratajskym** [comment]
Podívejte se třeba [sem](https://github.com/csob/paymentgateway/blob/master/Integration%20Examples/eAPI%20v1.5/php/sign-verify-test.php)

**Comment by jan1971** [comment]
Díky. Ještě jeden dotaz. Zkoušel jsem volat bránu bez odeslání parametrů (nebo s parametry bez zakódovaného podpisu)... Je ok, že se mi vrací hlavička 400? Cokoli jiného se mi vrátí až po té, kdy budou parametry správné?

**Comment by ratajskym** [comment]
Musíte mít správně parametry a podpis

**Comment by jan1971** [comment]
Děkuji. 
Je možné nějak ověřit správnost posílaného stringu? Nyní mi brána vrací response 500 - Internal Server Error...

**Comment by Miculka** [comment]
Dobrý den. Správnost posílaného stringu ověřit nelze. Můžeme Vám však pomoci, pokud nám prozradíte ID Merchant. Z logu pak dokážu vyčíst v čem je problém.

**Comment by jan1971** [comment]
Dobrý den.
M1MIPS0532
Děkuji!

**Comment by Miculka** [comment]
Tak momentálně vidím v logu pouze načtení obchodníka. Nemáte tedy správně seskládaný resp. chybí  paymentinit. 

April 6th 2016, 10:17:37.088	imips	INFO	fetch merchant Merchant[id=M1MIPS0532

**Comment by jan1971** [comment]
Ten čas je náš, český?

**Comment by Miculka** [comment]
Ano vidím v logu pod tímto ID, že jste se pokoušeli dnes 6.4 v 10:17

**Comment by jan1971** [comment]
To je divné, zkoušíme celý den...
Aktuálně touto metodou:
HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create("https://api.platebnibrana.csob.cz/api/v1.5/payment/init");
                    request.Method = "POST";
                    request.ContentType = "application/json";

**Comment by jan1971** [comment]
Zatím stále vrací HTTP stav 500. Děkuji za pomoc.

**Comment by Miculka** [comment]
máte špatně URL - míříte na produkci, kde jste v této chvíli ještě blokování. Změňte prosím na testovací URL.

**Comment by jan1971** [comment]
Dobrý den.
Tak jsem použil: 
HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create("https://iapi.platebnibrana.csob.cz/api/v1.5/payment/init");
ovšem odpověď: The remote name could not be resolved: 'iapi.platebnibrana.csob.cz'

**Comment by ratajskym** [comment]
Máte špatně url

**Comment by jan1971** [comment]
A správné je? Omlouvám se, vycházím z https://github.com/csob/paymentgateway/wiki/eAPI-1.5
Asi se dívám špatně.

**Comment by ratajskym** [comment]
https://iapi.iplatebnibrana.csob.cz/api/v1.5/payment/init

**Comment by jan1971** [comment]
Tak z touto: https://github.com/csob/paymentgateway/wiki/eAPI-1.5
The remote server returned an error: (500) Internal Server Error
Můžete zkusit log, jestli neřekne více?

**Comment by jan1971** [comment]
Omlouvám se... Z tou správnou adresou...

**Comment by jan1971** [comment]
Zkusil jsem z PHP a tam to prošlo bez problému... :(

**Comment by jan1971** [comment]
Dobrý den. Z .net stále error 500...

**Comment by jan1971** [comment]
Dobrý den znova:
Pokud posílám tato pokusná data:
{"merchantId":"M1MIPS0532","orderNo":"123456","dttm":"20160704102653","payOperation":"payment","payMethod":"card","totalAmount":100,"currency":"CZK","closePayment":"false","returnUrl":"https:\/\/vasobchod.cz\/gateway-return","returnMethod":"POST","cart":[{"name":"Shopping at ...","quantity":1,"amount":100,"description":"Lenovo ThinkPad Edge E540..."},{"name":"Shipping","quantity":1,"amount":0,"description":"PPL"}],"description":"Nakup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)","merchantData":null,"customerId":"1234","language":"CZ","signature":"LI39uyIx+mAkSU6W2qE7cLWFmPG2Y76ZA\/BGJnGRy1i9AfYYa2DSYrxm67LREiRgNjqv12w1WwSfFetXZqFXrt0WrAoDJf\/+7bgZ2fO60O5mAtrxiDwW\/0enNqd92dpwJK63s4uokSu4+zmY1yWqD98hy1JJxC4SAh5eBv9TZgHpF93Z05jIObXvbnSzyeO2PVKt8BpESBBD1XGnCHoraSy9K8Kyl40baXf2WjFaL1B8MVfnxIvGvShsZsIBU4dfpSh33\/yuU3cziGpPpjriCSYgUpC75RcjOmXUtNj\/LCm7oya6jBA852ILWFdrbDscN9fnfGhP4y9aGkhJ4iDszw=="}
Vrátí brána error 400

Pokud pošlu tato data:
{"merchantId":"M1MIPS0532","orderNo":"123456","dttm":"20160407135240","payOperation":"payment","payMethod":"card","totalAmount":1189900,"currency":"CZK","closePayment":"false","returnUrl":"https:\/\/eshop.mso.meopta.cz\/onlinepayment","returnMethod":"POST","cart":[{"name":"Shopping at ...","quantity":1,"amount":1189900,"description":"Meopta"},{"name":"Shipping","quantity":1,"amount":0,"description":"PPL"}],"description":"Nakup na Meopta","merchantData":null,"customerId"::null,"language":"CZ","signature":"SzNliOAQcnwlVryJeDNvEuswu8rYQwS9lk3V7GfldbdFAPOsq9LDWAlW6IAfJk9Ea63cUtGFVYnFkZumsFEDgBTq8UWFBitUsryJRUKuB8Iky0d7FdqDHQfim4PedDoCKdRMBMPU44oT1PyDEpjKwwZ+ONZk88PpP1MRw+cMrDexC8iYNdxU/wPf3CeC5SNZAxxODaClmpofUfLqmSTLaa2DIE9Ge8n4g3sj3EMEJDHp+R1UUdRuTEbwKBby4NMMa7N4JWC0eByaXogHo0cW6PCKP1NymrFuJ1Kq+q6GtMBMbb+6UdEriccvuZZVxlzbP+oHwnMEobHV3cqxi1Ijig=="}
Vrátí error 500

Nemohu najít syntaktický rozdíl, který by mohl zavinit ten rozdíl.
Děkuji za pomoc.

**Comment by ratajskym** [comment]
na první pohled, bez analýzy .. není problém tady?

,"customerId"::null,"

**Comment by jan1971** [comment]
Není to povinný údaj. Stejně jako merchantData... Vyplnil jsem dle toho.

**Comment by jan1971** [comment]
Aha. Už vidím ty dvě dvojtečky!

**Comment by jan1971** [comment]
Moc díky. Již se mi vrací jen :) 400. je možné z vašeho logu zjistit, ve které části dat je chyba?
Děkuji.

**Comment by ratajskym** [comment]
To bohužel možné není. Jedinou informaci, kterou Vám poskytnu je, že máte špatný podpis

**Comment by jan1971** [comment]
ok. díky. laboruji se sing funkcí.

**Comment by jan1971** [comment]
Ještě prosím, pokud je to možné, o kontrolu řetězce zprávy určené k zakódování:
M1MIPS0532|1254549|20160407160507|payment|card|1189900|CZK|true|https://eshop.mso.meopta.cz/onlinepayment|POST|Nakup: Meopta|1|1189900|Meopta|Postovne|1|0|Osobni odber|Vase objednavka 1254549|CZ

Ke kódování při volání brány používám klíč rsa_M1MIPS0532.key
Děkuji.

**Comment by jan1971** [comment]
Dobrý den.
Prosím o kontrolu nově zaslaného požadavku. Posílám z PHP naprosto totožný string (kromě časového údaje a samozřejmě podpisu). Z PHP se mi vrátí vaše odezva. Z .net aplikace stále error 400.
Děkuji.

**Comment by ratajskym** [comment]
April 8th 2016, 09:40:22.495 - špatný podpis

**Comment by jan1971** [comment]
Pokud by tu byl někdo se zkušenostmi z .netu
Toto je funkce, kterou používáme k vytvoření podpisu (který zatím není správný). Pokud byste viděli nějakou chybu, děkuji za informaci.

string merchantPrivateKey = File.ReadAllText(this.Application.Session.Config.FileRootPath+"\\keys\\rsa_XXXXXXXXXX.key");            
            OpenSSL.Crypto.RSA rsa = OpenSSL.Crypto.RSA.FromPrivateKey(new BIO(merchantPrivateKey));
            MessageDigest md = MessageDigest.SHA1;
            BIO b = new BIO(data);
            CryptoKey ck = new CryptoKey(rsa);
            byte[] res1 = MessageDigestContext.Sign(md, b, ck);
            return Convert.ToBase64String(res1);

**Comment by ratajskym** [comment]
Dobrý den, vzhledem k tomu, že Vám s .net neporadíme, issue uzavírám.
