### ISSUE TITLE
ClosePayment u recurrent platby [DOTAZ]

### ISSUE THREAD

**Issue by KEYELEMENTS** [csob/paymentgateway#157]
Dobrý den,
V dokumentaci se píše: z šablony pro opakovanou platbu se přebírá nastavení closePayment (příznak, zda se opakovaná platba zařadí do zúčtování). Je možné tento příznak přepsat při recurrent platbě? V API tento parametr nevidím, ale třeba to jde. A pokud to nejde, tak je důvod to nedat do příští verze :) ?

Děkuji

**Comment by dmarek** [comment]
diky za podnet, zvazime a pokud to bude vhodne, tak doplnime do pristi verze api

**Comment by ratajskym** [comment]
Dobrý den, uvedená funkcionalita byla z feature listu vyřazena.
