### ISSUE TITLE
Číslo karty a reporting [DOTAZ]

### ISSUE THREAD

**Issue by KEYELEMENTS** [csob/paymentgateway#158]
Dobrý den,
  lze získat programově nějaké informace o kartě, kterou byla platba realizována  např. částečně obfluskovaný PAN např. "4100 **** **** 5832" či expiraci?
Mám zatím anonymní přístup, ale možná po uzavření smlouvy je k dispozici nějaké extra API?
S tím nepřímo souvisí i otázka reportů - přehled transakcí zaúčtovaných na náš bankovní účet, které byly realizovány přes Vaši bránu. Existuje někde veřejně přístupná dokumentace, API? Např. potřebuju provést rekonciliaci plateb přes platební bránu s transakcemi na účtu. Musím je umět nějak spárovat (podle čeho?) atp. GP posílá nějaké aviza, ČS také v definovaném formátu, ale API by bylo lepší... 

Děkuji

**Comment by radehorak** [comment]
Dobrý den,
v ostré verzi Vám dokážeme posílat maskované číslo karty 5/4, tak aby to splňovalo PCI DSS. Jinak banka pro obchodníky poskytuje speciální report transakcí, který má definovanou strukturu a slouží k párování plateb. V případě potřeby můžete napsat na akceptacekaret@csob.cz a vzor daného reportu Vám pošlou.
Radek Horák
