### ISSUE TITLE
Platba nebyla uhrazena

### ISSUE THREAD

**Issue by pytel87** [csob/paymentgateway#159]
Pri prvnim volani payment/process po payment/init (volano z Android aplikace) jsem ve WebView presmerovan na https://iplatebnibrana.csob.cz/pay/shop.example.com/ee246bd4-d4e6-4f8c-9a2c-88b680617b4a/
s tim, ze Platba nebyla uhrazena.

**Comment by dmarek** [comment]
volani payment/init skoncilo s chybou, Invalid length of orderNo parameter, proto payment/proces hlasi uz jen chybu ze platba byla zamitnuta.

orderNo ma povolenou max. delku 10 cislic (= variabilni symbol ve vypisu bank. uctu klienta), v payment/init jste poslali 13 cislic
