### ISSUE TITLE
"Přechod z platební brány GP Webpay" vs. "Přechod do produkčního prostředí"

### ISSUE THREAD

**Issue by zamazaljiri** [csob/paymentgateway#16]
Dobrý den,

přecházíme z platební brány GP webpay a můj dotaz zní, jestli pro nás platí stránka https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD

Například reverzování platby jsme neměli ani dříve implementované a ani to teď nemáme v plánu implementovat (máme malý objem transakcí a tohle dělají správci ručně). Samozřejmě až v budoucnu přejdeme na nové eAPI, tak vše implementuje.

Dotaz tedy zní, jestli musíme splnit všechny body ze stránky "Přechod do produkčního prostředí".

Ještě doplním druhý dotaz: Dostali jsme nové Merchant ID. Dotaz zní, jestli ORDERNUMBER má pokračovat ve staré řadě (příklad: pod starým Merchant ID měla poslední platba ORDERNUMBER nastaveno 999 a pod novým Merchant ID bych ORDERNUMBER poslal s hodnotou 1000) nebo jestli můžeme začít od jedničky.

Děkuji

**Comment by ratajskym** [comment]
Dobrý den, Vámi odkazovaná stránka se týká eApi. 

Vy byste měli projít postupem uvedeným zde https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

Co se týká ORDERNUMBER, můžete pokračovat v číselné řadě nebo můžete začít od jedničky. Je to čistě na Vás.

**Comment by zamazaljiri** [comment]
Děkuji za rychlou odpověď! :-)
