### ISSUE TITLE
Platební brána nebere MC kartu

### ISSUE THREAD

**Issue by simPod** [csob/paymentgateway#160]
zákazníkovi se zobrazuje tento screen:

![image](https://cloud.githubusercontent.com/assets/327717/14555027/890b7f0c-02f0-11e6-9f22-3f11c2768719.png)

Věděli byste, co je za problém? Koukal jsem, že karta je typu MasterCard, měla by tedy projít.

Děkuji.

**Comment by pepakriz** [comment]
@simPod Že zákazníkovi nejde zaplatit je imho daleko menší problém, než že je tady vystaveno jeho číslo karty :(

**Comment by simPod** [comment]
to me nenapadlo, diky :( orpaveno

**Comment by ratajskym** [comment]
Z výše uvedené hlášky je zřejmé pouze to, že obchodník danou kartu nepřijímá. Je tedy potřeba poslat na adresu akceptacekaret@csob.cz id obchodníka (merchant id) a číslo karty (prefix, prvních 6 čísel karty) nebo aspoň čas transakce, abychom to dohledali v logu. Následně by došlo k prověření nastavení obchodníka a vyhodnocení, jestli byla karta sprváně povolena resp. zamítnuta
