### ISSUE TITLE
Platební brana ukazuje jinou měnu než je na mém webu

### ISSUE THREAD

**Issue by czseo** [csob/paymentgateway#161]
Dobrý den,

Mám problem spojeny s měnou platby.
Můj web kde je nastavená platební brana akceptuje měny v EUR. Po přechodu z nakupního košiku na platební bránu častka se přepočitavá z EUR do českých korun a to ani bez přepočtu kurzu. Tedy když kupujicí zvolil zboží na 1500 EUR na platební braně dostane častku 1500 CZK.
Původně v bance jsem žádal o pripojení platební branu pro platby v EUR.
Taky vidím v aplikace POSMerchant, že v nastavení platební brány mám nastavemou měnu CZK. Předpokladam, že tato chyba nastava pravě kvůli tomu nastavení platební brány v CZK.

Chtěl bych Vás poprosit o řadu jak tento problěm vyřešit, připadně jak nastavit akceptace plateb v EUR přimo v EUR, jak je tomu na webu.

**Comment by ratajskym** [comment]
Dobrý den, 

měnu transakce určujete Vy sám v platebním požadavku. Podívejte se do [dokumentace](https://github.com/csob/paymentgateway/wiki/eApi-1.5#payment-init-operation)

**Comment by czseo** [comment]
Dobrý den,

Děkují Vám za pomoc. Problem je vyřešen.
