### ISSUE TITLE
Podpora

### ISSUE THREAD

**Issue by simPod** [csob/paymentgateway#162]
Dobrý den, potřebujeme nějakou podporu, kam se dá napsat a do 24h nám odpoví. Máte něco takového? Tady je to mrtvé.

**Comment by ratajskym** [comment]
A co přesně Vás zajímá?

**Comment by simPod** [comment]
aktualne treba jak vznikne #160 
cas od casu mame nejaky dotaz co se primarne tyce problemu zakazniku s platebni branou a my jim nejsme schopni poradit protoze nemame dostatek dat, ze kterych to vycist, ani nemame nad branou nejakou vetsi kontrolu

a viz #160 predpokladam, ze zde podpora nutne neni (?)

**Comment by ratajskym** [comment]
K uvedenému issue jsem doplnil co je potřeba v takovém případě udělat. Podobné dotazy můžete řešit zde přes Github, ale pokud z pochopitelných důvodů nechcete psát citlivé údaje, které jsou pro podrobnější analýzu nezbytné, je možné použít kontaktní email akceptacekaret@csob.cz

**Comment by simPod** [comment]
Supr, děkuji
