### ISSUE TITLE
notifikace o uskutecnene platbe klientem

### ISSUE THREAD

**Issue by SvecMichal** [csob/paymentgateway#163]
Prosím, jake jsou moznosti notifikace o uskutecnene platbe klientem? Existuje moznost emailovych notifikaci o uskutecnene platbe?

O zrealizovane platbe se dovíme z odkazu, který obdržíme po úhrade klienta a návratu z platebni brany na náš web (s daným odkazem o platbe). Ale stávaji se občas pripady, že klient uhradí a již se nevráti na náš web (zavre okno).

**Comment by ratajskym** [comment]
Dobrý den, 

přesně pro takové případy je určena metoda [paymentStatus](https://github.com/csob/paymentgateway/wiki/eAPI-1.6#payment-status-operation)

**Comment by SvecMichal** [comment]
Ano, ale v případě, že klient zavře okno ihned po uskutečnění platby, tedy se nevráti na náš web a my návratovou url neobržíme. Jiné banky/ platební brány to mají řešeno, že zasílají i notifikační emaily právě pro tyto případy

**Comment by ratajskym** [comment]
V metodě paymentStatus návratovou url nepotřebujete. Expirace transakce je nastavena na 30minut tzn. pokud do 30 minut od přesměrování klienta z eshopu na platební bránu neznáte výsledek, zavoláte si uvedenou metodu.

**Comment by SvecMichal** [comment]
ok diky
