### ISSUE TITLE
Při zamítnutí platby nepředává kódy zpět obchodníkovi

### ISSUE THREAD

**Issue by JosefJu** [csob/paymentgateway#164]
Dobrý den.
Po několika měsících provozu nové platební brány jsme si všimli, že na rozdíl od předchozí brány GPWebPay máme velký podíl nedokončených plateb, tedy takových, kdy se uživatel z brány nevrátil zpět na náš server, a ani jednou není předán kód zamítnutí platby (pouze dvakrát kód 50 Zrušeno uživatelem a jednou kód 35 Expired session.
Pokus s vlastní kartou ukázal, že při zamítnutí zůstává platící stále na platební bráně, odkud se může vrátit volbou Zrušit platbu a vrátit se do e-shopu. 

Problém je i s naším přístupem přes posman,csob.cz. Pro zobrazení přehledu plateb se většinou točí ozubené kolečko a nakonec se nic nezobrazí, nebo se objeví text jako:
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /posmerchant/fyBfZ9p6trMddx1hfPFUNdo6nsCdYL1TziJv8WXQMRWXBcQ1mnf3iKRLjw5cKtIn49emqVuX6HH2PFdAvGpa3NXzS93qHXEkrJrTR37AeEs/fyBce/6HHa5.
Reason: Error reading from remote server.

 Když už se při několikátem pokusu seznam zobrazí, neobsahuje důvod odmítnutí platby (PRCODE/SRCODE), tlačítko "detaily" vpravo opět vyvolá otáčející se ozubené kolečko, ale nic se až na výjimky nestane.
Export do csv funguje, ale opět neobsahuje návratové kódy.

Mám obavy, že velký podíl nedokončených plateb může plynout i z případného podobného chování platební brány vůči platícím, tedy pomalou odezvou, timeoutováním, chybami proxy error.

Lze něco z toho řešit na naší straně?

S pozdravem
Josef Jůza

**Comment by ratajskym** [comment]
Dobrý den, 

pošlete mi id konkrétní transakce a podíváme se na to. To že se uživatel nevrátí z platební brány zpět na eshop může být způsobeno tím, že zavře prohlížeč (tab), dříve než dojde k přesměrování. V takovém případě byste měli využívat metodu paymentStatus a doptat se na stav transakce.

**Comment by JosefJu** [comment]
Dobrý den.
Posílám na Vaši předpokládanou e-mailovou adresu.

**Comment by ratajskym** [comment]
Emailová adresa je akceptacekaret@csob.cz a odkažte se prosím na tohle issue
