### ISSUE TITLE
Podpora před-autorizace pro oneclick platby

### ISSUE THREAD

**Issue by vladaman** [csob/paymentgateway#165]
Rádi bychom využili možnost před-autorizace prostředků na kartě při oneclick platbě. Je toto možné s použitím současného API?

Flow:
1. payment/init - uloží kartu
2. oneclick/pre-authorize
3. oneclick/close

Related: #157

**Comment by ratajskym** [comment]
Dobrý den, uvedené flow není ve stávající aplikaci možné a v nejbližší době nebude.
