### ISSUE TITLE
wocommerce plugin, chyba aktivace

### ISSUE THREAD

**Issue by vict0ry** [csob/paymentgateway#166]
při aktivace pluginu vyskakuje chyba : 
Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /mnt/data/accounts/a/agenturag/data/www/DOMAIN_NAME/htdocs/wp-content/plugins/WooCommerceMonetGateWay/start.php on line 134

**Comment by dmarek** [comment]
jakou verzi php pouzivate? Nejspis to bude souviset ... viz
http://stackoverflow.com/questions/13388541/php-parse-error-syntax-error-unexpected-t-object-operator

**Comment by vict0ry** [comment]
Děkuji, měl jste pravdu, problém vyřešen.

**Comment by webillusioncz** [comment]
mam ten samy problem, je se zmenou oznaceny radek je 137, trochu tapu, kde mam ten opravny kod umistit. V start start.php  zady kod, ktery tady pisete ze se ma opravit neni. Muzete me prosim trchu postrcit ? Dekuji predem

**Comment by ratajskym** [comment]
Dobrý den, 

pravděpodobně používáte verzi php < 5,4. Proto nemůžete volat metodu při vytváření objektu viz link na stackoverflow. Musíte upravit vytváření datumu

**Comment by webillusioncz** [comment]
bezi to na verzi php 5.6,
hazi to  syntax error, unexpected T_OBJECT_OPERATOR in 
/mnt/data/accounts/o/oliver2/data/www/cool-webdesign.cz/dev/projects/salatek/wp-content/plugins/WooCommerceMonetGateWay/start.php 
on line 137

na prislusnem radku  je kod $dttm = (new DateTime ())->format('YmdHis');

mohl by jste me posunou co tam vlastne mam dat, nejsem programator php

dekuji predem



s přáním hezkého dne
Pavel Bumba
Kreativní webdesigner,
UI, front-end developer
Grafické návrhy web stránek a e-shopů,
XHTMl/CSS koding šablon
Tel.: 775 599 195
Tel.: 607 074 312
Skype: webillusion
http://webdesign-restaurants.cz



------ Původní zpráva ------
Od: "Martin Ratajský" <notifications@github.com>
Komu: "csob/paymentgateway" <paymentgateway@noreply.github.com>
Kopie: "webillusioncz" <webillusioncz@gmail.com>; "Comment" 
<comment@noreply.github.com>
Odesláno: 08.06.2016 10:23:16
Předmět: Re: [csob/paymentgateway] wocommerce plugin, chyba aktivace 
(#166)

**Comment by webillusioncz** [comment]
dekuji za odpoved, ale nemohu najit kde to upravit, nemuzu totiz 
dohledat
s přáním hezkého dne
Pavel Bumba
Kreativní webdesigner,
UI, front-end developer
Grafické návrhy web stránek a e-shopů,
XHTMl/CSS koding šablon
Tel.: 775 599 195
Tel.: 607 074 312
Skype: webillusion
http://webdesign-restaurants.cz



------ Původní zpráva ------
Od: "Martin Ratajský" <notifications@github.com>
Komu: "csob/paymentgateway" <paymentgateway@noreply.github.com>
Kopie: "webillusioncz" <webillusioncz@gmail.com>; "Comment" 
<comment@noreply.github.com>
Odesláno: 08.06.2016 10:23:16
Předmět: Re: [csob/paymentgateway] wocommerce plugin, chyba aktivace 
(#166)
