### ISSUE TITLE
Potvrzení komunikace při zavádění platební brány.

### ISSUE THREAD

**Issue by FUTURAJ** [csob/paymentgateway#167]
Dobrý den,

můžete mi někdo potvrdit, jestli proběhla komunikace s bankou v testovacím módu ČSOB platební brána, abychom mohli přejít do produkčního provozu? Máme Merchant ID: M1MIPS0602.

Brána se nám zobrazuje, zkoušeli jsme provést platbu kartou, což se nezdařilo. Je to v pořádku?

S pozdravem
Jiří Procházka

**Comment by vzich** [comment]
Dobrý den, 

28.4 proběhla komunikace v testovacím prostředí (poslední platba byla zrušena zákazníkem). Dnes jste se pokoušel o komunikaci v produkčním prostředí, ale pro přechod na produkci si potřebujete vygenerovat produkční klíče na webu https://platebnibrana.csob.cz/keygen/ 

S pozdravem
Vítězslav Zich
