### ISSUE TITLE
Přechod na produkční prostředí

### ISSUE THREAD

**Issue by expe-git** [csob/paymentgateway#168]
Zdravím
Nejde se mi přihlásit do produkčního prostředí a netuším proč.
Testovacím prostředí jsem prošel v pořádku, provedl úspěšnou validaci, vygeneroval jsem klíče pro ostré prostředí a následně mi dorazil nějaký jednorázový kód pro produkční prostředí (nevím jestli tímto kódem se mám přihlásit nebo jej někde zadat po přihlášení v produkčním prostředí). Nicméně přihlásit se jím nelze a nelze to ani původním uživ.jm. + kódem který jsem používal pro testovací prostředí (uživ.jm. + kód pro testovací prostředí funguje stále ale pouze na testovací prostředí)

merchant ID: M1MIPS0628

Děkuji za odpověd.

**Comment by vzich** [comment]
Dobrý den,

kódem, který uvádíte, že jste vygeneroval, potvrdíte v POSmerchantu, záložka klíče,odeslání Vašeho veřejného klíče brány do banky. 
Pro přihlášení do POSmerchantu Vám přišlo heslo smskou po podpisu smlouvy, pokud si jej ale nepamatujete (nemůžete dohledat), tak si jej můžete zresetovat pomocí Vašeho kontaktního mailu a IČ.

S pozdravem

Vítězslav Zich

**Comment by expe-git** [comment]
Tak nějak to nejde jak má, testovací prostředí (uživ. jm. + heslo = přihlásím se), produkční prostředí (stejný uživ. + stejné heslo jako testovací = nepřihlásím se). Reset hesla na produkčním prostředí rovněž bez úspěchu.
viz. screenshoty.

![screenshot1](https://cloud.githubusercontent.com/assets/19165769/14983550/69dba010-113e-11e6-8c6e-9489c04cef26.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/19165769/14983553/6d6c7ff6-113e-11e6-8ed0-02b90ffcffba.jpg)
![screenshot3](https://cloud.githubusercontent.com/assets/19165769/14983557/708e8e18-113e-11e6-89b3-9b7b291915da.jpg)

**Comment by Mspisar** [comment]
Dobrý den

Uživatel má vedený aktivní účet obchodníka na rozhraní webové aplikace POSmerchant, ale uživatelský účet neobsahuje kontaktní e-mail. Z tohoto důvodu není uživatel schopný svépomoci resetovat heslo. Prosím tedy o přidělení nového hesla pro produkční prostředí.

S pozdravem

Milan Spisar

**Comment by expe-git** [comment]
Po vygenerování hesla vše funguje.
Děkuji za pomoc
