### ISSUE TITLE
Přechod na produkční prostředí

### ISSUE THREAD

**Issue by ferdinand64** [csob/paymentgateway#169]
Dobrý den,
pokouším se zprovoznit produkční bránu pro www.promoce.cz , ale při inicializaci dochází stále k chybě. Rád bych se zeptal, co by mohlo být špatně, když ta testovací funguje v pořádku. Postupoval jsem podle návodu pro přechod. Již v únoru jsem provedl testy na zkušební bráně, kterými jsem prošel. Následně jsem vygeneroval klíče, veřejný odeslal do posmerchantu a vložil zde autorizační kód. Klíče jsem vložil do obchodu a nastavil k nim cestu. Změnil jsem jsem url na produkční bránu. Podle návodu by to mělo fungovat. Po zadání nových hodnot nejde ani aplikace stažená z Githubu, která v testovacím prostředí funguje. Níže je json výpis, zde jsou naše údaje:

brána: M1MIPS0270
 
setup aplikace:
$url = "https://api.platebnibrana.csob.cz/api/v1";
$publicKey = "rsa_M1MIPS0270.pub";
$merchantId="M1MIPS0270";
$privateKey = "rsa_M1MIPS0270.key";
$privateKeyPassword = null;
 
preparing cart data: [{"name":"Promoce.cz","quantity":1,"amount":3100,"description":"- Obj. \u010d.: 20160999150..."},{"name":"Dod\u00e1n\u00ed","quantity":1,"amount":0,"description":"\u010cesk\u00e1 po\u0161ta"}] data to sign: "M1MIPS0270|90036|20160504115652|payment|card|3100|CZK|false|https://www.promoce.cz/test/new/index.php?sec=after_order&school=50&lang=cz&action_id=13874&pre_sec=cart&from=quick_gallery&foto=0001.jpg&order_id=90036&days_to_delivery=9|POST|Promoce.cz|1|3100|- Obj. č.: 20160999150...|Dodání|1|0|Česká pošta|Nákup na promoce.cz|79489|CZ" prepared payment/init request: {"merchantId":"M1MIPS0270","orderNo":90036,"dttm":"20160504115652","payOperation":"payment","payMethod":"card","totalAmount":3100,"currency":"CZK","closePayment":"false","returnUrl":"https:\/\/www.promoce.cz\/test\/new\/index.php?sec=after_order&school=50&lang=cz&action_id=13874&pre_sec=cart&from=quick_gallery&foto=0001.jpg&order_id=90036&days_to_delivery=9","returnMethod":"POST","cart":[{"name":"Promoce.cz","quantity":1,"amount":3100,"description":"- Obj. \u010d.: 20160999150..."},{"name":"Dod\u00e1n\u00ed","quantity":1,"amount":0,"description":"\u010cesk\u00e1 po\u0161ta"}],"description":"N\u00e1kup na promoce.cz","merchantData":null,"customerId":"79489","language":"CZ","signature":"BbM67coPcsNBch8Vdd\/AgYgZmu+Di1hh\/xbZZlxl5U9CeI0eV7hwTiwcZe1VXXuVAd7RH2cg0cNC5ZhDMsoWl5B0+uLNHf1IOXY1F11Mpn7n7C0dbOo0aITXYtIKWShwmfGfb6YT7+tlzfalcgUTkIBNh2BP3+B9QpelfzP5LpyEyLwUfOfR\/tdBcyFH0rWBMrMJ+4bjObXbgtwFJ7+SmwspySdv+7g3AdRt8EGMa61bEDncNN9C1FbmDoFdJN2ZbPGwgMNj70bQkuxW\/dbMyiUK+kjts9ngVO1w78344VT0xQOaL5+nY+yYJ5\/+mNfpXhxIfvQqbgaIR1Zjx0dZkQ=="} processing payment/init request ... payment/init result: {"dttm":"20160504115653","signature":"VIQZlQWN4s1MxmbKvNn6k5cTpUah5jOhxbIQ/QoTALnsA1tGaVOE1XxKWj6dHLVejkqxjcmyzUKn74+JAos/lbq3clDntSchcY90JNidwsk1UgPKaJ8oT/+pddmodpGaOMUC+63c/b9Q2R7aUoCIllqKFrDbGJq3CwrhmGFYWlqbW4S6UtIQ0E/AbvT/1veGt2CjXBFuPNWubwt+FI5wg32GS6gjGiGO8FAF8j6AP0KW3Mrn4OoLfHno2gi/EbiNJGOMutZivrlkniKzrjxWieANfcYEtJpO/Ozxv+xJ+bcnOhHV1MpmPx7zsDzy9o/pO0Dwd2PE8mPfT607jrpyUA==","payId":"ef31c276206c1BE","resultCode":0,"resultMessage":"OK","paymentStatus":1}

**Comment by ratajskym** [comment]
Dobrý den,

v logu vidím jen paymentInit, ale nevidím paymentProcess. Když se dívám co jste nasdílel, musíme se zeptat: Proměnnou $publicKey používáte pro ověření podpisu z platební brány? Protože pokud ano, je to špatně a musíte použít veřejný klíč platební brány.

**Comment by ferdinand64** [comment]
Dobrý den,
děkuji za odpověď. To bude asi ono. V testovacím prostředí byl veřejný klíč mips_iplatebnibrana.csob.cz.pub, to je pravda . Kde prosím získám veřejný klíč brány?

Děkuji

**Comment by ratajskym** [comment]
Produkční klíč naleznete na stejném místě [zde](https://github.com/csob/paymentgateway/tree/master/keys)

**Comment by ferdinand64** [comment]
Vložil jsem nový veřejný klíč, bohužel to nejde a končí to stejně. 

$url = "https://api.platebnibrana.csob.cz/api/v1";
$publicKey = "mips_platebnibrana.csob.cz.pub";
$merchantId="M1MIPS0270";
$privateKey = "rsa_M1MIPS0270.key";
$privateKeyPassword = null;

**Comment by ferdinand64** [comment]
Dobrý den,
zjistil jsem, že problém nastane v následující php funkci, jejíž návratovou hodnotou je false, ale to jen ukazuje na to, že verifikace neproběhla v pořádku:

function verify($text, $signatureBase64, $key, $logMsg = null) {
	$path = dirname(__FILE__)."/keys/";
	$key = $path . $key;
	$fp = fopen ( $key, "r" );
	if (! $fp) {
		throw new Exception ( "Key not found" );
	}
	$public = fread ( $fp, filesize ( $key ) );
	fclose ( $fp );
	$publicKeyId = openssl_get_publickey ( $public );
	$signature = base64_decode ( $signatureBase64 );
	$res = openssl_verify ( $text, $signature, $publicKeyId );
	openssl_free_key ( $publicKeyId );
	return (($res != '1') ? false : true);
}

**Comment by ratajskym** [comment]
Ano, pokud z nějakého důvodu selže ověření podpisu, vrátí se false.

**Comment by ferdinand64** [comment]
Dobrý den,
tak jen pro informaci, čím to bylo. Napadlo mě podívat se co v tom souboru veřejného klíče brány, staženém na uvedené adrese, doopravdy je a k mému překvapení tam byla místo klíče uložená celá ta stránka v html. Zobrazil jsem si klíč jako raw, vkopíroval do souboru a již to jde. Děkuji.
