### ISSUE TITLE
Merchant unsupported region

### ISSUE THREAD

**Issue by Tomas-M** [csob/paymentgateway#170]
Při pokusu o opakování platby API vrací
[resultCode] => 0
[resultMessage] => Merchant unsupported region for bin 546234
[paymentStatus] => 6

A opakovaná platba se neprovede.
Jak si to mám vysvětlit?
Pokud jde o chybu, proč je resultCode = 0? pokud nejde o chybu, proč se neprovede platba?
Děkuji.

**Comment by Tomas-M** [comment]
BTW je používána verze API 1.5 a volání payment/recurrent, signature je v požadavku i v odpovědi ověřeno v pořádku.

**Comment by Mspisar** [comment]
Dobrý den

   BIN odpovídá kartě mastercard vydané v Severní Americe. Umožňuje Vaše brána tento region?

S pozdravem

Milan Spisar 

Monet+, a.s.

**Comment by Tomas-M** [comment]
To já netuším :) Tak ale jednou už uživatel zjevně zaplatil, když je v seznamu pro opakování plateb. To se musí pro jednotlivé země nějak "povolit" zvlášť?

**Comment by dmarek** [comment]
Muzete poslat payId pro danou zamitnutou platbu? Proverime. Diky.

**Comment by Tomas-M** [comment]
Celé je to nějaké divné.
Tyto payID se měly dneska zopakovat:
09925cf39ecc5BD
83d7266a414a9BD
95d286a7cee42BD

Při zopakování ale byly obdrženy tyto odpovědi:

pro 09925cf39ecc5BD:
[payId] => 3c18849f34010BE [resultCode] => 0 [resultMessage] => Merchant unsupported region for bin 546234 [paymentStatus] => 6

pro 83d7266a414a9BD:
[payId] => e3cadc341d18cBE [resultCode] => 0 [resultMessage] => Merchant unsupported region for bin 418550 [paymentStatus] => 6

pro 95d286a7cee42BD:
[payId] => a59010ca87b92BE [resultCode] => 0 [resultMessage] => OK [paymentStatus] => 6

Ta poslední je taky divná, tváří se jako OK ale paymentStatus je 6.

Děkuji za prověření všech.

**Comment by dmarek** [comment]
Parametr `resultCode` urcuje vysledek zpracovani operace (0 znaci, ze operace probehla, tzn. transakce byla nalezena, podpis pozadavku overen atd.), samotny stav transakce (a tedy i vysledek autorizace) je v parametru `paymentStatus`. Popiseme podrobneji do dokumentace.

Co se tyce transakci, tak prvni dve se neautorizovaly z duvodu toho, ze aktualne nemate povolene v nastaveni obchodnika ackeptaci US karet (v dobe autorizace prvotni transakce nicmene povolene byly). Treti transakce a59010ca87b92BE byla zamitnuta issuerskou bankou na obecne zamitnuti (duvod nebyl upresnen).

**Comment by Tomas-M** [comment]
Děkuji za objasnění.

Banka se může sama od sebe jednostranně rozhodnout, že přestane US karty akceptovat? Koho kontaktovat pro zajištění, že bude banka akceptovat všechny země bez rozdílu?

**Comment by ratajskym** [comment]
Dobrý den, 

vidím, že jste zůstal bez odpovědi, tak jen doplním. Požadavky ohledně Vašeho nastavení platební brány zasílejte na adresu akceptacekaret<at>csob.cz
