### ISSUE TITLE
Nastavení data zúčtování

### ISSUE THREAD

**Issue by ferdinand64** [csob/paymentgateway#171]
Dobrý den,
rád bych Vás požádal o radu.  Zákazník si přeje, aby k zúčtování docházelo automaticky na konci dne a nikoli manuálně. Čas zúčtování lze možná nastavit v proměnné settlementDate, ale nikde jsem nenašel příklad, jak jí implementovat. Ani v příkladech na Githubu k verzi 1.6 není. V tamní funkci createPaymentInitData možnost přidat takovou proměnnou není. V Posmerchantu jsem žádné podobné nastavení pro celou bránu také nenašel. Mohl byste mě prosím nějak nasměrovat?

Děkuji 
S pozdravem
Tomáš Bartoň

**Comment by ratajskym** [comment]
Dobrý den, tohle se řídí již v metodě payment Init viz [dokumentace](https://github.com/csob/paymentgateway/wiki/eAPI-1.6#-post-httpsapiplatebnibranacsobczapiv16paymentinit-)

Parametr closePayment
