### ISSUE TITLE
Přechod do produkčního prostředí

### ISSUE THREAD

**Issue by mobilttl** [csob/paymentgateway#173]
Dobrý den,

v testovacím prostředí vše funguje OK.

Po změně na produkční verzi se mi nedaří ověřit odpověď veřejným klíčem, který jsem v aplikaci POSMerchant potvrdil heslem a klíče zavedl, vše OK. (vše 2 x vyzkoušeno)

nastavení:
$url = "https://api.platebnibrana.csob.cz/api/v1.5";
$publicKey = "rsa_M1MIPS0297.pub";

$merchantId="M1MIPS0297"; 

$privateKey = "rsa_M1MIPS0297.key";
$privateKeyPassword = null;

log:
preparing cart data: [ { "name": "Nákup na koloshop.cz", "quantity": 1, "amount": 56300, "description": "Shimano BR-M396L zadní kotoučová..." }, { "name": "Poštovné a balné", "quantity": 1, "amount": 9900, "description": "Platba za dopravu a platbu" } ] prepared payment/init request: { "merchantId": "M1MIPS0297", "orderNo": "375", "dttm": "20160517092717", "payOperation": "payment", "payMethod": "card", "totalAmount": 66200, "currency": "CZK", "closePayment": "false", "returnUrl": "http://beta.koloshop.cz/index.php?volba=objednavka&payment_back=1", "returnMethod": "GET", "cart": [ { "name": "Nákup na koloshop.cz", "quantity": 1, "amount": 56300, "description": "Shimano BR-M396L zadní kotoučová..." }, { "name": "Poštovné a balné", "quantity": 1, "amount": 9900, "description": "Platba za dopravu a platbu" } ], "description": "Shimano BR-M396L zadní kotoučová", "merchantData": null, "customerId": "1455", "language": "CZ", "signature": "cSFbs1/TMJdLMr+D6orq4OVtYCIweX8/HSuiJ6qqQmGmXHlK/GEUpyk9xwGzZuH4goKs+vkKoEONg005PcPd+reDC1QIhTS2aM8eqndjryOKSvf6OCJs0NjhJAKARmgshjMWx/A1kw0042ZPQjlPaCzKMpZeWR7I/GMea2mLoOSRanLNO8i3KSDcq4Cik6uujturaNtFYmU9BENI4HR6tSJRC4hx2N/zw71aoaE4GjU/g9JjHeVhJ6Kry7J+yJm1AOG7KgG0NScYtpjPlXlqQJLBBXVLDgti8hImYKDcnXjqP349rHe1B/jEEyPIEuGawIWyDZ+eo08DiICqz9uGxg==" } processing payment/init request ... payment/init result: {"dttm":"20160517092717","signature":"SiyH8Jo0yZ+0KwvoOKMARMInZ8BEOmWb3/t+h18xvUNUg+5OQ4CQvJlCQyubGUuIx88b4pm8y9elgdXxLZ374vJRuRygjX0eEzkZmiJ7HfXwwqNECef5CjJmAkzgHvWqMmiLMfRxA8iv0qVCcMhj626T81nAelemRJkORJ6J0Usqh/GzV+HtBbYx1+TTGS6YeUNbd1DQd5HpiFPJglInT5cHmDXiuXJlWV7PjNF//eD6jzu1yQZ9c4kMTerFhS7Kdix7NdUkkQJL78h5xAKCEeoLgHqps1Tvn3MFo/488uLwxIDuYDXKqhHqkTnQslObl7+oAhqYE1VTpxiy1Ed/dQ==","payId":"8ae4a94bcc474BE","resultCode":0,"resultMessage":"OK","paymentStatus":1} payment/init failed, unable to verify signature

prosím o pomoc.

díky

**Comment by ratajskym** [comment]
Dobrý den, 

není náhodou problém ve veřejném klíči platební brány, kterým ověřujete odpověď?

**Comment by mobilttl** [comment]
Dobrý den,


pravděpodobně ano, ale nevím jaký..klíč jsem stáhl, uložil, cesta je správná. Jaký může být jiný problém?

**Comment by ratajskym** [comment]
Tohle by vám mělo pomoci 

https://github.com/csob/paymentgateway/wiki/Splnil-jsem-testy.-Co-d%C3%A1l%3F

**Comment by mobilttl** [comment]
díky....stydím se!

přehlédl jsem "i" v názvu souboru
