### ISSUE TITLE
Legacy brána, stav zamítnutí?

### ISSUE THREAD

**Issue by itstudiocz** [csob/paymentgateway#174]
Nedaří se mi při testování provést stav zamítnutí. Zkouším všechny možné kombinace karet a CVC kódů (funkční karta/kód 200, karta pro zamítnutí/kód XXX, nic nefunguje a platba se nezvaliduje).

Merchant number M1MIPS0619 - co dělám špatně?

**Comment by ratajskym** [comment]
Dobrý den, 

zamítnutá transakce vznikne její expirací. Díval jsem se na Vaše transakce a chybí Vám jen reversal a transakce odeslaná do zaúčtování.
