### ISSUE TITLE
variabilní symbol platby

### ISSUE THREAD

**Issue by dferbas** [csob/paymentgateway#175]
Odkud se bere VS, s kterým od ČSOB přijde platba, která hradí transakci?
Není to ani číslo objednávky, ani VS transakce.
Poprvé se to podle mě objevuje v XML souboru statement jako invoice_number.
Je možné, aby se platby prováděly s VS, který je ve statement souboru uveden jako variable_symbol? (ten totiž i odpovídá VS, který je uveden v aplikaci POS Merchant)

**Comment by radehorak** [comment]
Dobrý den,
můžete prosím poslat daný požadavek na mail platebnibrana@csob.cz a uvést i ID platební brány? 
Děkuji moc.
S pozdravem
Radek Horák

**Comment by dferbas** [comment]
Dobrý den,

na tento požadavek jsem poslal požadované údaje, ale dosud jsem 
neobdržel žádnou odpověď.

Prosím nezavírejte nám tento požadavek, nebyl zodpovězen.

On 20.5.2016 23:18, Dusan Ferbas wrote:

> Dobrý den,
>
> přeposílám dotaz na variabilní symbol, který jsem dle instrukcí poptal 
> na githubu, ale odtamtud mě poslali na vás.
>
> ID platební brány je M1MIPS/nnnn/, soubor statementu je v příloze, VS 
> v POS Merchant je /xxxx/, taktéž i v přiloženém XML.
>
> Zdraví
>
> *Ing. Dušan Ferbas*, jednatel
> Solar Monitor s.r.o. | 28. října 17 | 511 01 Turnov | Czech Republic
> Tel.: +420 481 313 661 | Mobil: +420 603 147 723
>
> [ www.solarmonitor.cz] | [ e-shop <http://shop.solarmonitor.cz>] | [ 
> Solar Portal <http://portal.solarmonitor.cz>]
>

*Dušan*

**Comment by ratajskym** [comment]
Zaurgoval jsem Váš požadavek v bance.

**Comment by marekdub** [comment]
Dobrý den,
VS se na bankovní výpis propisuje z parametru orderNo.
Marek Dub

**Comment by vachotka** [comment]
Dobrý den, doba odezvy z mailu platebnibrana(at)csob.cz je bohužel dost nepružná a já bych potřeboval zjistit v čem je problém adhoc. Podle všeho správně vyplňuji orderNo, jak je uvedeno v postu výše, protože v POS MERCHANT aplikaci se ve sloupci VS skutečně zobrazuje správné VS. Na bankovním výpise je ale jiný, úplně nesmyslný VS. Náš VS má 8 znaků. V čem může být prosím problém? Párování plateb v účetnictví je momentálně peklo. Děkuji.

**Comment by hanuss** [comment]
Dobrý den, 
Vámi uvedený VS k jednotlivé transakci se (kromě POSmerchant) propisuje pouze do výpisu o transakcích provedených platebními kartami. Na účet se transakce připisují v součtu za den a karetní asociaci. Tento součet i příslušný VS, pod kterým se transakce na účet připíší, je rovněž uveden na výpisu o transakcích. Připisování na účet po jednotlivých transakcích není bohužel možné.
Štěpán Hanuš
