### ISSUE TITLE
formát statement souboru

### ISSUE THREAD

**Issue by dferbas** [csob/paymentgateway#176]
Statement soubor, který přijde emailem, je ve formátu XML.
Je možné tento soubor získat i ve formátu txt? (ten totiž můžeme importovat do účetnictví Stormware Pohoda)

**Comment by radehorak** [comment]
Dobrý den,
ano je možné daný soubor posílat i ve formátu TXT. Můžete prosím poslat požadavek na mail akceptacekaret@csob.cz.
Radek Horák

**Comment by radehorak** [comment]
Dobrý den,
ano je možné to posílat i ve formátu TXT. Můžete prosím poslat požadavek na mail akceptacekaret@csob.cz nebo dát požadavek prostřednictvím HelpDesku ČSOB 495 800 116.
S pozdravem
Radek Horák
