### ISSUE TITLE
eAPI - vrací 400 (.NET implementace)

### ISSUE THREAD

**Issue by MaraS82** [csob/paymentgateway#177]
Dobrý den, 
snažím se implementovat eAPI pro platební bránu a zasekl jsem se hned na prvním kroku - echo.

Vrací mi to 400 bez dalších informací. Můžete mi prosím říct, kde je problém a kde se dostanu k podrobnějším informacím.

MerchantId : M1MIPS0689.

Děkuji

**Comment by ratajskym** [comment]
Dobrý den, 

podle aplikačního logu jste neodeslal vygenerovaný veřejný klíč do banky - na platební bránu

**Comment by MaraS82** [comment]
Děkuji moc, zabralo to:)

**Comment by MaraS82** [comment]
Děkuji moc, zabralo to:)
