### ISSUE TITLE
Kontrola parametru digest ze serveru

### ISSUE THREAD

**Issue by K0nias** [csob/paymentgateway#178]
Dobry den,

Merchant ID: M1MIPS0640

zkousim testovat vytvoreni platby dle navodu z https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

certifikaty jsem vygeneroval na https://iplatebnibrana.csob.cz/keygen/ a odeslal do banky. Transakce se podle vseho vytvori spravne (url pro init transakce https://iplatebnibrana.csob.cz/pay/entry/merchant), ale pri navratu do aplikace se mi nedari overit parameter DIGEST ze serveru. Netusite prosim, jestli mi neco neuniklo? Napriklad, jestli se ma pouzivat pro overeni DIGEST ze serveru verejny certifikat banky, ktery se pouziva u reseni eAPI? Protoze nic takoveho v navodu neni napsane.

posledni platby jsem zkousel primo z Vaseho ukazkoveho kodu:
https://github.com/csob/paymentgateway/tree/master/Integration%20Examples/eAPI%20v1
u tech se vse tvarilo, ze funguje spravne.

Predem dekuji za odpoved

S pozdravem

Vladimir Zapletal

**Comment by ratajskym** [comment]
Dobrý den, 

pro ověření odpovědi ze serveru opravdu potřebujete veřejný klíč platební brány.

Dokumentaci upravíme
