### ISSUE TITLE
Chyba pri vytvoreni transakce - PrCode:14

### ISSUE THREAD

**Issue by K0nias** [csob/paymentgateway#179]
Dobry den,

zkusil jsem dnes otestovat zaplaceni transakce na DEV serveru a bohuzel se mi nepodarilo vytvorit ani transakci. 

Navratove kody:
PrCode: '14'', SrCode: '0'

bohuzel jsem nikde nedohledal, co PrCode = 14 znamena. 

Jednalo se o transakce 2016000047,216000048 a 216000049.

Merchant ID: M1MIPS0640

Predem dekuji 

Zapletal

**Comment by vzich** [comment]
Dobrý den,

transakce které jste uvedl byly nejprve zrušeny zákazníkem 24.5 mezi 15:50 - 16:00. A poté jste se stejnými pay ID snažil provést platbu znova v 16:30, proto byly tyto pokusy zamítnuty na duplicitu. PayID transakce je totiž unikátní. Viz. - [Návratové hodnoty](https://github.com/csob/paymentgateway/wiki/eAPI-1.6#n%C3%A1vratov%C3%A9-hodnoty-)

S pozdravem

VZ

**Comment by K0nias** [comment]
Dobry den,

tomuhle uplne nerozumim. Jestli se nepletu, tak "payId" by mela generovat brana a neni mozne vytvaret znovu transakci znovu, protoze "payId" se neda ovlivnit pri vytvareni transakce. Pokud teda nemyslite, ze cislo objednavky by melo byt unikatni u jednoho obchodnika. To by mohl byt problem, protoze jsem vyvoj zkousel u sebe a pak i na DEV serveru. A cislo objednavky je jen inkrementacni cislo, ktere neni unikatni v ramci instanci aplikace. Muze to byt tim? Pak bych se zeptal, zdali se nesdili cisla objednavek i mezi vyvojovym a produkcnim prostredim. Protoze by bylo nutne transakce smazat.

S pozdravem

Vladimir Zapletal

**Comment by K0nias** [comment]
jen jeste pro info, nepouzivam eAPi, ale postupoval jsem podle tohoto navodu: https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

**Comment by vzich** [comment]
Dobrý den, pane Zapletal,

 jelikož používáte legacy API a ne eAPI, tak si své payID vytváříte sám parametrem ORDERNUMBER, který musí být unikatní. V eAPI si jej brána generuje sama. Konkrétně ve Vašem případě jste použil stejné ORDERNUMBER pro více transakcí, proto byly zamítnuty na duplicitu, jak jsem již zmiňoval. Jen pro info pro variabilní symbol platby je určen parametr MERORDERNUM.
Čísla objednávek a jiné informace o transakci nejsou sdíleny mezi integračním a produkčním prostředí. 

S pozdravem

Zich
