### ISSUE TITLE
Problém s vygenerováním klíče

### ISSUE THREAD

**Issue by brembou** [csob/paymentgateway#18]
Po zadání platných údajů do formuláře pro vygenerování klíčů (testovací i produkční) my formulář pořád hlásí chybu "Zadali jste nesprávný merchant ID nebo e-mail." Ale podle dodatku smlouvy je e-mail správně a z Posmerchant ID brány taktéž. Potřeboval bych zjistit, kde je problém. Mohl by mě někdo zavolat, abychom tyto údaje mohly ověřit? 728 315 819

**Comment by brembou** [comment]
Poslal jsem na podporu kombinaci ID a e-mail. Napsali, ať to zkusím teď a najednou to se stejnými údaji fungovalo. Příčinu problému jsem se nedozvěděl.

**Comment by radehorak** [comment]
Dobrý den,
problém byl v založení mailu v systémech ČSOB.
Radek Horák
