### ISSUE TITLE
Vývoj vs testovací prostředí payment/process

### ISSUE THREAD

**Issue by MaraS82** [csob/paymentgateway#180]
Dobrý den,

setkal jsem se zvláštním chování - pokud volám Vaši testovací bránu z prostředí vývoje(localhost) tak vše funguje jak má.

Pokud ale aplikaci nasadím na testovací prostředí, tak url, na které směruje brána po úspěšném provedení platby neobsahuje **žádné url parametry**(query string). A vypadá to, že žádné data nejsou ani v postu.

Jedná se o nějakou politiku testovací brány? Požadavky se opravdu liší jen v tom, jaké mají returnUrl. A obě url jsou https.

Moje MerchantID: M1MIPS0689

Děkuji

**Comment by ratajskym** [comment]
Dobrý den, 

žádná podobná politika nastavená není. Navíc testovací a produkční prostředí je téměř identické. Vaše transakce prověřím a ozvu se.

**Comment by MaraS82** [comment]
Omlouvám se, chyba byla na mojí straně. Špatný routing, který request přesměrovával na kanonickou doménu bez query stringu.

**Comment by ratajskym** [comment]
Ok, děkuji za info
