### ISSUE TITLE
Stav 2 "platba probíhá"

### ISSUE THREAD

**Issue by mobilttl** [csob/paymentgateway#181]
Dobrý den, 
jak dlouho může být platba ve stavu "2" (platba probíhá) ? Mám platbu, která je cca 14 hodin v tomto stavu. V produkčním prostředi

díky

**Comment by ratajskym** [comment]
Dobrý den, 

tento stav může trvat maximálně 30minut než transakce expiruje a překlopí se do stavu zamítnuto. V databázi není ani jedna transakce ve stavu 2. Jaké je payId transakce u které se Vám toto děje.

**Comment by mobilttl** [comment]
Dobrý den,

plaším..akorát jsem neaktualizoval objednávky s tímto stavem. Platba je nyní zamítnutá.

omlouvám se a děkuji za reakci.
