### ISSUE TITLE
WS podporované Legacy API (one click platby přes Legacy API)?

### ISSUE THREAD

**Issue by tomaprot** [csob/paymentgateway#182]
Dobrý den,

Legacy API nepodporuje standardní GP Webpay webovou službu getOrderState. Tzn. ono to podporuje jen REST api část GP Webpay? Jen počáteční CREATE_ORDER a asynchronní REST odpověď? Nebo to podporuje alespoň některé synchronní GP Webpay WS, zejm. processRecurringPayment, processDepositReverse? Businessově mi jde zejména o to, zda přes Legacy API lze provozovat "one click platby".

Díky,

T. Protiva

**Comment by dmarek** [comment]
Platbu na klik a dotazovani na status lze provadet jen pres eAPI, legacy api podporuje jen pocatecni "create order".
