### ISSUE TITLE
Payment not found při zadání vratky

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#183]
Dobrý den,
narazil jsem na problém při zadání vratky několik měsíců starých plateb. Před zadáním vratky ověřujeme stav platby na bráně a v obou případech payment/status vracelo result 140 - payment not found. Přes POSmerchant platby refundovat šlo bez problémů.

Merchant M1E3CB0860

878c05722950aBB
d35a57c7f8403BD

prosím o prověření

**Comment by ratajskym** [comment]
Dobrý den, 

pokud je Váš požadavek ještě aktivní, pošlete mi prosím na servis @ monetplus.cz url, kterou posíláte. Mě se obě transakce podařilo bez problému dohledat

**Comment by janlanger** [comment]
Od té doby se to neobjevilo, takže asi ok.
