### ISSUE TITLE
Chybne presmerovani pri chybe 900 a Internal Error

### ISSUE THREAD

**Issue by HonzaMac** [csob/paymentgateway#184]
Zdravím!
Při chybě https://github.com/csob/paymentgateway/issues/120 s nepodporovaným browserem brána přesměruje zpátky na eshop metoudou GET na místo očekávané POST. 
Je k tomu nějaký důvod, nebo se jedná o chybu?

**Comment by HonzaMac** [comment]
Je tam opravdu tato chyba? cc @vzich

**Comment by dmarek** [comment]
Chyba to neni, i kdyz priznavam ze idealni chovani to neni. Platebni brana u nekterych akci provadi GET, je to takto uvedeno i v dokumentaci.

_Poznámka: eShop musí od v1.5 podporovat zpracování návratovych hodnot pomocí metody GET i POST (platební brána provadí redirect podle parametru returnMethod, u některých akcí -- např. zrušení platby uživatelem -- nicméně provede vždy redirect pomocí GET metody)._
