### ISSUE TITLE
Generátor klíče

### ISSUE THREAD

**Issue by jan1971** [csob/paymentgateway#185]
Dobrý den.
Připravujeme pro klienta platební bránu.
Mám k dispozici Merchant ID i smlouvu s technickým kontaktem, nicméně při pokusu o generování klíče dostávám hlášku: Špatné Merchant ID nebo email.
S Kým mohu tento problém konzultovat?
Děkuji za odpověď.
Pěkný den.

**Comment by ratajskym** [comment]
Dobrý den, 

dokážu si představit, že pokud to zkoušíte na produkčním prostředí a váš merchant není aktivován, můžete dostat právě takovou odpověď. Bez detailů se v tomto případě neobejdeme. Pošlete email na akceptacekaret <at> csob.cz
