### ISSUE TITLE
Přesnější návratové kódy zamítnutých transakcí

### ISSUE THREAD

**Issue by lojza3d** [csob/paymentgateway#186]
Dobrý den,
prosím, bylo by možné rozšířit seznam návratových kódů u payment/status (resultCode) o následující položky v případě zamítnuté transakce?

- Plátce neprovedl správně 3D ověření
- Banka plátce (vydavatel karty) nepovolila platbu kartou

V tuto chvíli umíme rozlišit jen chybu na straně naší brány, resp. expiraci požadavku (uživatel zavřel okno). Pro lepší komunikaci na zákazníky a lepší UX by nám velmi pomohlo i detailní rozlišení výše.

**Comment by ratajskym** [comment]
Dobrý den, 

v tuto chvíli není jisté, kdy bude rozšíření návratových kódů zařazeno do pipeline.
