### ISSUE TITLE
MCM – MasterCard Mobile

### ISSUE THREAD

**Issue by jenysdavid** [csob/paymentgateway#187]
Dobrý den,
chtěl bych se zeptat na aktuální stav paymethod, zda byla rozšířena o metodu MC mobile? Kolega se Vás dotazoval v záznamu zde https://github.com/csob/paymentgateway/issues/63 a bylo mu odpovězeno, že rozšíření zvážíte. Můžu se zeptat na aktuální stav?

Předem děkuji za odpověď.

S pozdravem
David jenyš

**Comment by dmarek** [comment]
Požadavek je stále v pipeline, prozatím nebylo rozhodnuto.

**Comment by jenysdavid** [comment]
Děkuji za odpověď. Budeme tedy muset tuto platební metodu potlačit na naší straně.
