### ISSUE TITLE
Přesměrování na platební bránu se nezdařilo

### ISSUE THREAD

**Issue by webillusioncz** [csob/paymentgateway#188]
pri testovani po odeslani na platebni branu https://iapi.iplatebnibrana.csob.cz/api/v1
 se objevi tyto chyby 
Warning: openssl_sign(): supplied key param cannot be coerced into a private key in /mnt/data/accounts/o/oliver2/data/www/cool-webdesign.cz/dev/projects/salatek/monetWebPay/crypto.php on line 169

Warning: openssl_free_key() expects parameter 1 to be resource, boolean given in /mnt/data/accounts/o/oliver2/data/www/cool-webdesign.cz/dev/projects/salatek/monetWebPay/crypto.php on line 171

Není problémem to, ze není pouzito ssl na domene ?
nebo v cem je problém ?

**Comment by ratajskym** [comment]
Dobrý den, 

z výše uvedené hlášky usuzuji, že máte problém s privátním klíčem. Špatná konfigurace ?

**Comment by webillusioncz** [comment]
Dobrý den,
konfigurace
ID obchodníka: A1836EwI7i
Adresa brány: https://iapi.iplatebnibrana.csob.cz/api/v1
Veřejný klíč:rsa_A1836EwI7i.pub
Soubor privátního klíče:rsa_A1836EwI7i.key

po odeslanise objevi:

Přesměrování na platební bránu se nezdařilo

dekuji predem za radu

**Comment by ratajskym** [comment]
Špatný veřejný klíč. A ještě bych vám doporučil použít novější verzi api v1.6

**Comment by webillusioncz** [comment]
Takze znova vygenerovat ? Co se tyka API, pouzivam reseni formou pluginu pro wordpress, ktery jsem si stahl u Vas a predpokladam, ze je verejna

**Comment by vzich** [comment]
Dobrý den,
pokud používáte

**Comment by vzich** [comment]
Dobrý den,
není třeba si generovat znovu klíče. Pokud používáte plugin pro WooCommerce, tak si stáhněte veřejný klíč platební brány uvedený zde na githubu v záložce Code. Pro testovací prostředí použijte tedy **mips_iplatebnibrana.csob.cz.**

**Comment by webillusioncz** [comment]
po pouziti
Inicilizace platby na platební bráně se nezdařila, důvod: Couldn't resolve host 'mips_iplatebnibrana.csob.cz' .
Pouzil jsem mips_platebnibrana.csob.cz.pub.
mips_iplatebnibrana.csob.cz je to spravna domena ? Pokud to zadam ciste do prohlizece vyhodi to ze 
Server nenalezen

**Comment by vzich** [comment]
Dobrý den,
mips_iplatebnibrana.csob.cz. je název veřejného klíče platební brány ne doména. Stáhnete jej zde - https://github.com/csob/paymentgateway/tree/master/keys, pro WooCommerce s koncovkou PUB. Jako URL použijte stejnou jakou jste zaslal v předchozí komunikaci.

**Comment by webillusioncz** [comment]
Omlouvam se za neustale problemy, uz sem z toho zoufalej.
Shrnu stavajici nastaveni
Adreasa brány:https://iapi.iplatebnibrana.csob.cz/api/v1
Verrejny klic mips_iplatebnibrana.csob.cz.pub
a pridavam scree nastaveni
![2016-06-16_13-35-28](https://cloud.githubusercontent.com/assets/1929525/16115543/f8a6a23a-33c7-11e6-8a63-cd32814ebde5.png)

co tam mam spatne ?

**Comment by ratajskym** [comment]
1. Přečtěte si pro dokumentaci [zde](https://github.com/csob/paymentgateway/wiki/eAPI-1.6#postup-integrace-kl%C3%AD%C4%8De-a-kde-je-vz%C3%ADt). Vypadá, to, že jste po vygenerování klíčů neodeslal veřejnou část do banky

2. Veřejný klíč brány jste si přejmenoval ? Ve vaší konfiguraci se jmenuje jinak, než jak se jmenuje originální soubor

**Comment by ratajskym** [comment]
Dobrý den, pokročil jste? Potřebujete ještě nějak pomoci?

**Comment by webillusioncz** [comment]
Dobry den,
děkuji vse je jiz implementovano a funkční.


s přáním hezkého dne
Pavel Bumba
Kreativní webdesigner,
UI, front-end developer
Grafické návrhy web stránek a e-shopů,
XHTMl/CSS koding šablon
Tel.: 775 599 195
Tel.: 607 074 312
Skype: webillusion
http://webdesign-restaurants.cz



------ Původní zpráva ------
Od: "Martin Ratajský" <notifications@github.com>
Komu: "csob/paymentgateway" <paymentgateway@noreply.github.com>
Kopie: "webillusioncz" <pavel@webdesign-restaurants.cz>; "State change" 
<state_change@noreply.github.com>
Odesláno: 23.08.2016 7:52:29
Předmět: Re: [csob/paymentgateway] Přesměrování na platební bránu se 
nezdařilo (#188)
