### ISSUE TITLE
Iniclizace platby na platební bráně se nezdařila, důvod: Missing parameter cart/name

### ISSUE THREAD

**Issue by webillusioncz** [csob/paymentgateway#189]
Dobry den,
pro provedeni platby se objevi tato hlaska. Jedna se o plugin pro woocommerce.
V cem je problem ?

**Comment by ratajskym** [comment]
Dobrý den, 

máte popsány položky, jak se zmiňuje dokumentace?

**Comment by ratajskym** [comment]
@webillusioncz Dobrý den, předpokládám, že tohle je už dávno z Vaší strany vyřešeno .. ?

**Comment by dohnalf** [comment]
Dobrý den, mám stejný problém.
Nedaří se nám najít, který parametr chybí.
Prosím o radu
error log:
orderNumber 17941
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- parts of orderNumber 17941, 
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- Checking order 17941, orderId 17941
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- SELECT * FROM monetTransaction WHERE orderNumber=17941
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- after select
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- cart created
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- loaded paymentStatus:  PayId: 
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- payment not inicialized OR payment cancelled or declined OR detected cart changes
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- payment/init, url: https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/init/
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- payment/init sign: M1MIPS0434|17941|20170206185355|payment|card|17600|CZK|false|http://www.crystallo.co.uk/wp-content/plugins/WooCommerceMonetGateWay/returnUrl.php?orderNumber=17941|GET||1|17600|Black Leather Suit...||1|0|Objednavka 17941|2|CZ
----- Mon, 06 Feb 2017 18:53:55 +0000 ----- payment/init data: {"merchantId":"M1MIPS0434","orderNo":"17941","dttm":"20170206185355","payOperation":"payment","payMethod":"card","totalAmount":17600,"currency":"CZK","closePayment":"false","returnUrl":"http:\/\/www.crystallo.co.uk\/wp-content\/plugins\/WooCommerceMonetGateWay\/returnUrl.php?orderNumber=17941","returnMethod":"GET","cart":[{"name":"","quantity":1,"amount":17600,"description":"Black Leather Suit..."},{"name":"","quantity":1,"amount":0}],"description":"Objednavka 17941","merchantData":null,"customerId":2,"language":"CZ","signature":"ZffPdRPc3HBHiW3LD+vN8GM36Svn\/HGhKlg3WQSeggisbCIm154Ayv+4lE5IyaclF8DjsQlinay+XzNOTmoTab2mcZ30C4DgGTBqv5Z0f4hgA2npH79gByQnNu1Tqm1vWAx+BHgKSGulvs2Mjib+7ZMa9dXORXwMvDX7qBSvBetgQ2mwYAlFrtaw\/RMkMCyDbVZYjZ\/c7LJJq2Y8UdGIKnGzYO1VO1jfTkv6ppRG3GvwEgLh9XNxbgabmkgNgdEFV8\/jLn07+V4851jmoABvZZlU4tt88ELJLGKXr1H2FnDaE3gObVQNBLCKl8xVVAft\/HCKsVCgqjQ06+MGnoc\/kw=="}
----- Mon, 06 Feb 2017 18:53:56 +0000 ----- payment/init result: {"dttm":"20170206195355","signature":"LW6vT9PlySw6lB3+s2GbN1/1f39dturFbuGD4N3QKC16436VC4xy1IqkIrQQYGD1WYo2BgKYvSbfMyKoJ+lW6ZMiQlvRgL41k8Gv5RnwajIfSNzC3GeFeuvTBCt+SMXcil+dkDJvPa5dtKD0wgHuS7cR1cf+Z/qVtP8nIaGu/zmPovGczZyP/YC3hy99pcXVxDRbMiTtbeKDqNEt1IoCrW5zDt6N1PLuRSc115BY8vsO7f3T51bU0SajSJ8MfjL5lLI6PpEstK3/SmOwAwN2CsO3AznR9PHo9hzf6uZzANxyPj+hj3rNNoFvEgd1C3q3UtnXUNdk6c0nRkUKfucFtA==","payId":"8ac47f3424198CB","resultCode":100,"resultMessage":"Missing parameter cart/name","paymentStatus":6}
----- Mon, 06 Feb 2017 18:53:56 +0000 ----- payment/init verify: 8ac47f3424198CB|20170206195355|100|Missing parameter cart/name|6

**Comment by joskera** [comment]
Dobrý den,
chybí Vám vyplnit názvy položek v košíku, viz dokumentace: https://github.com/csob/paymentgateway/wiki/eAPI-1.6#item---polo%C5%BEka-ko%C5%A1%C3%ADku-objekt-cart-

**Comment by dohnalf** [comment]
Dobrý den,

děkuji - tím, že je v těchto položkách nabídkový text, tak to vypadá, že se nemusí vyplňovat. Již to funguje. FD
