### ISSUE TITLE
Chybová stránka po přechodu na produkční prostředí

### ISSUE THREAD

**Issue by jan1971** [csob/paymentgateway#191]
Dobrý den.
Po úspěšném schválení testovacích plateb jsme vyměnili klíče, heslo a upravili adresu na https://platebnibrana.csob.cz/pay/entry/merchant
Bohužel, přestože testovací platby prošli bez potíží, nyní se jen objeví chybová hláška.
Merchant ID:M1MIPS0669
Platba dnes 10:23... Můžete se prosím podívat do vašeho logu a případně nasměrovat k řešení?
Děkuji.

**Comment by Mspisar** [comment]
Dobrý den,

  Brána neměla podepsány klíče jednorázovým heslem. Zkuste prosím platbu znovu.

s pozdravem

Milan Spisar

**Comment by jan1971** [comment]
Dobrý den.
Moc děkuji. Platba prošla. Nicméně bych tedy prosím o info, kde byla chyba. Eventálně, jak jí příště předejít.

**Comment by Mspisar** [comment]
Zde byla skutečně chyba jen v klíčích. Stačilo v aplikaci posmerchant u brány v sekci klíče zadat Vaše jednorázové heslo - udělal jsem za Vás ať ověříme funkčnost.

**Comment by jan1971** [comment]
Děkuji!
