### ISSUE TITLE
Nekonzistence dokumentace s ukázkou

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#192]
Dobrý den,

narazil jsem na tuto nekonzistenci na stránce https://github.com/csob/paymentgateway/wiki/eAPI-v1.6-datum-transakce
`authDate` má být ve formátu `YYYYMMDDHHMMSS`, ale v ukázce je `160412100635`, tedy `YYMMDDHHMMSS`.

**Comment by dmarek** [comment]
Diky, opraveno, spravne ma byt format `YYMMDDHHMMSS`
