### ISSUE TITLE
Drobný překlep v dokumentaci

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#193]
Dobrý den,

na https://github.com/csob/paymentgateway/wiki/eAPI-1.6#-post-httpsapiplatebnibranacsobczapiv16paymentinit-  parametr `language` obsahuje v povolených hodnotách dvakrát `SK`. Nevím, jestli je ta hodnota uvedena chybně dvakrát, nebo se jedná o překlep jiného jazyka, proto na to upozorňuji.

**Comment by dmarek** [comment]
Diky, preklep opraven, chybela `FR`
