### ISSUE TITLE
testovaci brana nevraci chybu ani data

### ISSUE THREAD

**Issue by kkristal** [csob/paymentgateway#194]
Dobry den, prosim o pomoc s testovanim vasi platebni brany , posilam tato data: 

`
{
    "merchantId": "A1864Hu8kS",
    "orderNo": "123456",
    "dttm": "20160628001344",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 2000,
    "currency": "CZK",
    "closePayment": false,
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 1000,
            "description": "Lenovo ThinkPad Edge E540"
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 1000,
            "description": "PPL"
        }
    ],
    "description": "Nákup na vasobchod.cz",
    "merchantData": null,
    "customerId": "1234",
    "language": "CZ",
    "signature": "NB1utk22Qiwa5G0gSybwsTES08QHEwu27o+Q3izD+2EZr4F40FDCMBNOJ0c018XMrb056kMVtGd54O+tiwIn4CEIcsnIVfps1LSDC7BdxxaBUfEDJLJxQur5zKXqa3FJp+ZE5R1sJn26/eu8l3HN1WvY/feKr4p43xelLgX+3uILFrxk2n8Ov/GvMnrjD+hdKN3OTwGOGCkq6Kv4i5BqWjFqfrc4Jgq/TmUFDWNGWAunI1T53+Cvqxy89sFXv39QxowOyEItwHFdjv/JWFRcf9Q+f0zu39CfATECdGGEU9mhQQm2Vii912FRyyXCKTbTnozb/h9fjlk7afzshcfwrw=="
}

`

brana mi ale nevraci zadnou chybovou hlasku ani vysledek ... je problem ve formatu dat, v signature (encoduji base64) nebo ve zpusobu odeslani (v node):

`

request.post
	url: "https://iapi.iplatebnibrana.csob.cz/api/v1.5/payment/init/"
	json: data
	headers:
		'Content-Type': 'application/json'
		Accept: 'application/json;charset=UTF-8'
, (err, res, body) ->
	console.log err, body

`

**Comment by vzich** [comment]
Dobrý den,
Váš problém je v podpisu. Používáte privátní klíč brány, který jste si vygeneroval a odeslal jste veřejný klíč platební brány do banky při generování?

S pozdravem 

VZ

**Comment by kkristal** [comment]
Dobry den, 

dekuji za odpoved. Vygeneroval jsem nove klice a uploadoval do banky: http://prntscr.com/bnm16f  

signature jsem vygeneroval pomoci php kodu z vaseho example: http://phpfiddle.org/main/code/giyy-0754

ale vysledek stale stejny.

S pozdravem,
KK

**Comment by ratajskym** [comment]
Dobrý den, v jakém stavu je Váš požadavek? Můžeme toto issue uzavřít?

**Comment by kkristal** [comment]
Dobry den, k funkcnimu reseni jsem se bohuzel jeste nedopracoval, vas kolega mi napsal, ze problem je v signature, tak jsem vyzkousel generovat a uploadovat nove klice, vytvoril jsem znovu signature ... ale stale jsem byl ve stejnem stavu...
Tak jsem vam napsal postup, jak jsem ho generoval http://phpfiddle.org/main/code/giyy-0754 a doufal jsem, ze mi nejak pomuzete najit problem

**Comment by ratajskym** [comment]
Doporučuji napřed implementovat velmi jednoduchou metodu [echo](https://github.com/csob/paymentgateway/wiki/eAPI-1.6#echo-operation). Pokud Vám bude procházet echo, máte jistotu, že jsou klíče a práce s nimi v pořádku. V následujícím kroku se můžeme zaměřit na chybu v parametrech init požadavku

**Comment by ratajskym** [comment]
Dobrý den, pokročil jste? Potřebujete od nás nějak pomoci ?
