### ISSUE TITLE
Nepřesnosti v dokumentaci týkající se `paymentStatus`

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#196]
Dobrý den,

V této sekci https://github.com/csob/paymentgateway/wiki/eAPI-1.6#n%C3%A1vratov%C3%A9-hodnoty- chybí zmíňka, že se stejné návratové hodnoty používají i pro `payment/oneclick/start` a `payment/oneclick/init`.
Zároveň je v dokumentaci uvedeno, že `paymentStatus` je nepovinný. Je to tak správně? Kdy nastane situace, že `paymentStatus` v responsu chybí?

**Comment by pepakriz** [comment]
Přítomnost `paymentStatus` pravděpodobně závisí na `resultCode`, kdy `resultCode` musí být 0

**Comment by vzich** [comment]
Dobrý den,
přesně jak uvádíte pokud je resultCode různý od nuly, tak vracíme chybový kód, ale už nevracíme paymentStatus. Chybějící info doplníme do dokumentace.

**Comment by dmarek** [comment]
doplněno
