### ISSUE TITLE
Extensions pod anonymnim uctem

### ISSUE THREAD

**Issue by KEYELEMENTS** [csob/paymentgateway#197]
https://github.com/csob/paymentgateway/wiki/eAPI-1.6-maskovane-cislo-karty

Zde se pise, ze extensions musi mit obchodnik povolene. 
Jak se to ma chovat pod anonymnim test. pristupem?  Zkousim to a extensions (pro oneclick init platbu) se mi nevraci. Nevim jestli nedelam neco spatne, proto se ptam.
Pokud se opravdu nevraci, tak by bylo vhodne kdyby ano.

Dekuji

**Comment by vzich** [comment]
Dobrý den,
anonymní účet slouží pro základní testy api. Pro testování extensions je třeba mít již přidělené merchantID a povoleny extensions od banky.
