### ISSUE TITLE
Duvody odmitnuti plateb

### ISSUE THREAD

**Issue by Danny177** [csob/paymentgateway#198]
Dobry den,
velmi bychom ocenili kdyby v POSMERCHANTu, nebo lepe v API bylo mozne zjistit presny dovody odminuti platby - lepe bychom tak mohli komunikovat s zakazniky o problemu - predat jim presne informace, aby si mohli problem opravit (napr. zvysit limit)

Dekuji,
DN

**Comment by vzich** [comment]
Dobrý den, 
prostřednictvím api není možné zjistit přesný důvod zamítnutí plateb, tuto možnost zařadíme do budoucích vylepšení. Nicméně v prostředí Posmerchant můžete u plateb zjistit podrobnější důvody zamítnutí objednávek.

**Comment by pepakriz** [comment]
Dobrý den, je v této funkcionalitě nějaký progress? Plánuje se něco?

**Comment by Danny177** [comment]
Uz byste s tim neco mohli udelat
