### ISSUE TITLE
Veřejný klíč platební brány ve formátu *.PEM

### ISSUE THREAD

**Issue by brembou** [csob/paymentgateway#20]
Pro naši implementaci bych potřeboval dodat veřejné klíče k platební bráně (produkční i testovací) ve formátu PEM.

**Comment by kubisjan** [comment]
Připojuji se k žádosti o veřejné klíče ve formátu PEM, nebo CER.

**Comment by ondrakoupil** [comment]
Dobrý den,

do 12. července jsem na dovolené. 

Po tuto dobu se prosím obracejte na kolegu Štěpána Rambouska, e-mailem na rambousek@optimato.cz, telefonicky na číslo 603 579 377. Váš e-mail nebyl přeposlán.

Své e-maily v této době budu průběžně kontrolovat, v urgentních záležitostech se na mě můžete obrátit telefonicky.

Ondřej Koupil
Optimato s. r. o.

------------------

I am out of office until 12. 7. 2015. During this time please contact my colleague Štěpán Rambousek by e-mail rambousek@optimato.cz or by phone +420 603 579 377. Your message was not forwarded.
I will try to check my inbox now and then, in urgent cases you can try to contact me telephonically.

**Comment by ondrakoupil** [comment]
Jsou na https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys

**Comment by kubisjan** [comment]
domnívám se, že veřejné klíče umístěné na uvedené adrese nejsou ani v PEM ani v CER formátu, případně mohu poprosit o postup jak tyto klíče převést do formátu PEM/CER?

oba veřejné klíče jsem zkoušel aplikací použít stejně jako PEM i CER, ale validace pokaždé nedopadla v pořádku, pro validaci používáme tento kód (v .NETu - na původní bráně fungoval bez problémů) : 
SHA1CryptoServiceProvider sha1 = new SHA1CryptoServiceProvider();
RSACryptoServiceProvider rsaCryptoIPT = //ziskani provideru (zalezi na typu klice ...)
ASCIIEncoding encoder = new ASCIIEncoding();
return rsaCryptoIPT.VerifyData(encoder.GetBytes({složený řetězec}),CryptoConfig.MapNameToOID("SHA1"), Convert.FromBase64String({hodnota z parametru DIGEST}));

Příklad odpovědi, kterou se snažím validovat : 
složený řetězec : "CREATE_ORDER|565901077253801|||50|0|"
digest : "bOix5fw5gqa16sWtsvwNpHw/4EnsE40m7Os2s2nqZckQ4t5Syuoe9/oAdTSBJUkuvp3qQ+kdnggochTUow+iZqRTbsu8jRXBA1zjemsQXS9jkyAMZoZhNvWKTkteUqtkYyu0Q16z1FzLTEl0HOs6bvSTkhmK2Yxh0p2IlbS7zLoxHJY72EJfHynrqAMfq8Xfd1IYkFZGVGiSB2Qft41uNq5holRbzOGJ0eqlY+9Lzff2teiux6W4Vu+Z4M26eIPro10xa+lRYsISK3u9Sg9rbAVTKr21H64Ragn8I0EKqOu2FkfV8RsmquTjbijSJ7EBDQNfMagQcLobijK/zqzbAA=="
veřejný klíč : "mips_iplatebnibrana.csob.cz.pub"

**Comment by kubisjan** [comment]
tak u nás nakonec pomohla až implementace nového eAPI, tam nám funguje validování podpisu správně, z nějakého důvodu na původním legacy rozhraní není možné podpis validovat proti zde nahraným veřejným klíčům

**Comment by martenbrett** [comment]
Dobrý den,

máme úplně stejný problém při migraci. Aplikace je napsaná v PHP. Platba proběhla úspěšně, nicméně se nedaří provedenou transakci ověřit.

Je vystavený veřejný klíč opravdu v pořádku? Test proběhl na produkční bráně s certifikátem mips_platebnibrana.csob.cz.pub

Předem díky za odpověď.

**Comment by dmarek** [comment]
Dobrý den,

k tomu ověření podpisu - řetězec který vstupuje do verifikace podpisu "CREATE_ORDER|565901077253801|||50|0|" by měl obsahovat jen vyplněné parametry, tzn. "CREATE_ORDER|565901077253801|50|0|", bez MERORDERNUM a MD.

Jinak jsme doplnili kromě veřejných klíčů brány i certifikáty (binární formát DER, přípona .cer). 
https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys
