### ISSUE TITLE
Časové pásmo pole dttm

### ISSUE THREAD

**Issue by tomas789** [csob/paymentgateway#201]
Dobrý den,

v dokumentaci chybí zmínka o tom, že časové pásmo údajů zakódovaných v DTTM má být Europe/Prague. I když tato možnost byla první, kterou jsem zkusil a jde to snadno ověřit podle času odeslaného v odpovědi serveru, tak pro úplnost by to tam jistě mohlo být.

**Comment by vzich** [comment]
Dobrý den,
děkujeme za poznámku, upravíme v dokumentaci.

**Comment by dmarek** [comment]
pridano do technical faq
