### ISSUE TITLE
Nefunguje v WP 4.5.3  a Woocommerce 2.6.2

### ISSUE THREAD

**Issue by ondrejvymetalik** [csob/paymentgateway#203]
Dobrý den,

snažím se nainstalovat plugin do Wordpressu verze 4.5.3 a Woocommerce ve verzi 2.6.2 a bohužel při načtení nastavení ve Woocommerce je platební brána brázdná a nejde tam vepsat žádný informace.

<img width="1228" alt="screen shot 2016-07-19 at 17 27 15" src="https://cloud.githubusercontent.com/assets/20541229/16955732/1372a546-4dd6-11e6-844e-591e6105e76a.png">

Ve starší verzi WP a Woocommerce se to načte.

Děkuji za info

**Comment by ratajskym** [comment]
Dobrý den, prosím o spolupráci při řešení tohoto problému (mám verzi WP 4.5.3 a WC 2.6.4)

Editujte tento soubor
wp-content/plugins/WooCommerceMonetGateWay/start.php

A na řádku 55 proveďte následující úpravu
//$this->id = 'MonetWebPay';
$this->id = 'WC_Monet_Payment_Gateway';

Následně zkuste znovu zobrazit stránku pluginu a dejte mi vědět

Děkuji

**Comment by ozaoral** [comment]
Dobré odpoledne, plugin jsme aktualizovali. Můžete si stáhnout celý plugin, nebo jen provést výše popsanou úpravu.
