### ISSUE TITLE
echo - resultCode : 900

### ISSUE THREAD

**Issue by martinkaplan** [csob/paymentgateway#204]
Zdravím 

chci implementovat platební branu v iOS aplikaci

používám Alamofire pro vytvaření req a SwiftyRSA pro vytvoření signature 

odpověd:
{
  "resultCode" : 900,
  "resultMessage" : "Internal error"
}
 
zkusil jsem obě url
https://iapi.iplatebnibrana.csob.cz/api/v1/echo
https://api.platebnibrana.csob.cz/api/v1/echo

klíč používám stejný jako android aplikace

Předem děkuji za odpověd

**Comment by vzich** [comment]
Dobrý den,
ve vaší android aplikaci Vám platby prochází? Jaké máte případně ID platební brány abychom mohli pokusy prověřit? Pokud nemáte anonymní účet, vygeneroval jste si, případně uploadoval, klíče na [](https://iplatebnibrana.csob.cz/keygen/)  

S pozdravem

VZ

**Comment by martinkaplan** [comment]
merchant id? M1MIPS0035

**Comment by ratajskym** [comment]
Dobrý den, v jakém stavu je Váš požadavek? Můžeme toto issue uzavřít?

**Comment by martinkaplan** [comment]
ano problem byl v chybějící hlavičce 

Content-Type: application/json

**Comment by ratajskym** [comment]
Ještě bych Vám doporučil, abyste používal nejnovější verzi eAPI, tedy 1.6
