### ISSUE TITLE
WC plugin produkční prostředí  Přesměrování na platební bránu se nezdařilo /Platba nemůže být provedena

### ISSUE THREAD

**Issue by webillusioncz** [csob/paymentgateway#205]
Zdravim,
mam problem u pluginu pro Woocommerce . Pokud testuju v testovacim modu tj. https://iapi.iplatebnibrana.csob.cz/api/v1 a mips_iplatebnibrana.csob.cz.pub merchmant ID zadavam pridelene z csob a na zaklade jeho i vygenerovany private key, ktery je i odeslany do banky a public key mips_iplatebnibrana.csob.cz.pub , tak vse funguje jak ma. Pokud zadam uz produkcni adresu https://api.platebnibrana.csob.cz/api/v1 a mips_platebnibrana.csob.cz.pub, mercmant ID a private key stejny. Tak se objevi bud  po presmerovani na banku Platba nemůže být provedena Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem. A po dalsim novem pokusu o zaplaceni Přesměrování na platební bránu se nezdařilo. V čem je problem ?

**Comment by dmarek** [comment]
pro produkcni prostredi musite mit jiny private key obchodnika, z vyse uvedeneho jsem vyrozumnel, ze pouzivate stejny private key pro obe prostredi. Rozdilny je i generator https://iplatebnibrana.csob.cz/keygen/ vs https://platebnibrana.csob.cz/keygen/

**Comment by ratajskym** [comment]
@webillusioncz - Dobrý den, pomohlo Vám to ? Můžeme task uzavřít ?

**Comment by webillusioncz** [comment]
dobry den,
ano pomohlo

s přáním hezkého dne
Pavel Bumba
Kreativní webdesigner,
UI, front-end developer
Grafické návrhy web stránek a e-shopů,
XHTMl/CSS koding šablon
Tel.: 775 599 195
Tel.: 607 074 312
Skype: webillusion
http://webdesign-restaurants.cz



------ Původní zpráva ------
Od: "Martin Ratajský" <notifications@github.com>
Komu: "csob/paymentgateway" <paymentgateway@noreply.github.com>
Kopie: "webillusioncz" <pavel@webdesign-restaurants.cz>; "Mention" 
<mention@noreply.github.com>
Odesláno: 01.08.2016 10:22:13
Předmět: Re: [csob/paymentgateway] WC plugin produkční prostředí 
Přesměrování na platební bránu se nezdařilo /Platba nemůže být provedena 
(#205)
