### ISSUE TITLE
problémy s implementačním prostředím - woocommerce

### ISSUE THREAD

**Issue by TomLindemann** [csob/paymentgateway#206]
Dobrý den,

již delší dobu se snažím o implementaci platebního brány do woocommerce a stále se potýkám s problémy. Při platbě se mi zobrazuje hlášení:

Warning: openssl_verify(): supplied key param cannot be coerced into a public key in /web/htdocs3/refereezoneeu/home/www/wordpress/monetWebPay/crypto.php on line 188

Warning: openssl_free_key() expects parameter 1 to be resource, boolean given in /web/htdocs3/refereezoneeu/home/www/wordpress/monetWebPay/crypto.php on line 189

Inicilizace platby na platební bráně se nezdařila, nepodařilo se ověřit podpis odpovědi

Vše jsem dělal dle návodu v readme souboru a nevím tudíž kde je chyba. Vygeneroval jsem klíče dle  návodu a nastavil plugin také dle návodu a to takto:

ID: M1MIPS0765
Brána: https://iapi.iplatebnibrana.csob.cz/api/v1.6
Veřejný: mips_iplatebnibrana.csob.cz.pub
Privátní: rsa_M1MIPS0765.key

Soubory jsou na svém místě také dle návodu. Do banky také uploadováno.

EDIT: pokud zadám veřejný klíč vygenerovaný tak jako privátní, chybové hlášení odpadne a zůstane pouze: Inicilizace platby na platební bráně se nezdařila, nepodařilo se ověřit podpis odpovědi

Můžete mi poradit kde dělám chybu? Děkuji Vám mnohokrát.

S pozdravem

Tomáš

**Comment by ratajskym** [comment]
Dobrý den, 

podle uvedené hlášky to vypadá, že se skriptu nepodaří pracovat s veřejným klíčem. Více mě z uvedeného popisu nenapadá.

**Comment by TomLindemann** [comment]
Jak bych to mohl odstranit ? vygenerovat nový klíč ?

**Comment by ratajskym** [comment]
Veřejný klíč negenerujete resp ano, ale ten slouží pro něco jiného. Vy musíte podle potřeby stáhnout a použít jeden z těchto https://github.com/csob/paymentgateway/tree/master/keys

**Comment by TomLindemann** [comment]
vyzkoušel jsem již všechny, respektive tento: mips_iplatebnibrana.csob.cz.pub, který by měl být správný pro implementační prostředí a chybu hlásí stejnou.

**Comment by ratajskym** [comment]
Pošlete mi tento klíč na email servis @ monetplus.cz spolu s printscreenem Vašeho nastavení v eshopu

**Comment by ratajskym** [comment]
Děkuji za zaslání, popravdě jsem si to trochu myslel, už jsme na to v minulosti narazili. Podívejte se na zdrojový kód zmiňovaného klíče. Poznáte, že jste jej špatně stáhl a jeho formát je tak nepoužitelný. Klíč musí obsahovát pouze [toto](https://raw.githubusercontent.com/csob/paymentgateway/master/keys/mips_iplatebnibrana.csob.cz.pub)

**Comment by TomLindemann** [comment]
Děkuji, nenapadlo mě při stáhnutí obsahu, že by se mohlo stát abych stáhl něco jiného, ale přesto se to jmenovalo jako daný soubor. Opravdu jsem přepsal celý obsah souboru tím, co je v odkaze a funguje to. Tudíž vše bylo správně nastaveno pouze veřejný klíč měl jiný obsah. Děkuji Vám za pomoc.

**Comment by ratajskym** [comment]
Dobrá zpráva, dejte si na to pozor až budete stahovat produkční klíč
