### ISSUE TITLE
Inline payment form

### ISSUE THREAD

**Issue by simPod** [csob/paymentgateway#207]
Dobrý den, někdy v prosinci / lednu 2016 jsem od vás dostal informaci, že k 2Q 2016 byste měli mít hotový inline payment form, něco na způsob https://www.braintreepayments.com/products-and-features/drop-in-ui 

Chci se zeptat, v jakém je to stavu. Díky moc

**Comment by ratajskym** [comment]
Dobrý den, 

tušíte kdo Vám tuto informaci poskytl? Osobně si to nevybavuji.

**Comment by ratajskym** [comment]
Dobrý den, 

jen doplním informaci, že v tuto chvíli není inline payment form v pipeline.

**Comment by simPod** [comment]
Kdo to byl netuším. Řešil jsem to přes email, když jsem zkoumal funkčnost jednotlivých bran...
