### ISSUE TITLE
Špatná cena při platbě

### ISSUE THREAD

**Issue by Chvojan** [csob/paymentgateway#209]
Dobrý den,
u platby se nám stalo že se data špatně přenesla na platebí bránu. Jedná se o to že na bránu zasílám cenu 22 874,- za produkt a 240,- za dopravu. Celková cena potom na bráně měla být 23 114,- ,avšak brána ukazuje pouze cenu 22 874,- a ponížila cenu u produktu na cenu 22 634,-. Vypadá to jakoby po cestě od shopu do brány někde z ceny pro duktu odečetla cenu dopravy. V init-result.php je nastavno takto:
$merchantId = "M1MIPS0342";
$orderNo = $idObjednavky;
$totalAmount = $_POST['cena_kusu_s_DPH'] * $_POST['pocet_kusu'];          //22 874,- * 1
$shippingAmount = $celkemPostovne;   //240,-
$returnUrl = "http://cistyvzduch.com/platba_hotova.php?id=".$idObjednavky."";
$goods_desc = $_POST ['nazev_produktu'];
$description = $_POST ['text'];
$customerId = 1;
$returnMethodPOST = "yes";
$closePayment = false;
$merchantData = null;
Děkuji za pomoc

**Comment by ratajskym** [comment]
Dobrý den, 

v parametru totalAmount musíte poslat celou částku tedy včetne dopravy.

totalAmount - Celková cena v setinách základní měny. Tato hodnota bude zobrazena na platební bráně jako celková částka k zaplacení

**Comment by Chvojan** [comment]
Děkuji nějak jsem to přehlédl moje chyba.
