### ISSUE TITLE
Migrace: Nelze ověřit odpověď po zaplacení objednávky

### ISSUE THREAD

**Issue by martenbrett** [csob/paymentgateway#21]
Dobrý den,

mám problém s ověřením odpovědi která přijde po zaplacení/zrušení platby na bráně. Digest neodpovídá kontrolnímu součtu. Pro ověření používám veřejný klíč, který je k nalezení zde na githubu (mips_platebnibrana.csob.cz.pub).

Kde by mohl být problém? Na gpwebpay funguje ověření bez problémů...

**Comment by ratajskym** [comment]
Dobrý den, bohužel bez více informací nejsem schopen Vám poradit. Budu potřebovat minimálně Vaše merchant id.

**Comment by martenbrett** [comment]
Mechant ID: M1E3CB2220

**Comment by ratajskym** [comment]
Na naší straně jsem s Vaším id nedohledal problém. Nepomůže Vám example zde https://github.com/csob/paymentgateway/blob/master/eshop-integration/eAPI/v1/php/example/crypto.php ?

**Comment by martenbrett** [comment]
Nemyslím si. Nepoužívám eApi, ale postupoval jsem dle https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay (myslel jsem, že z titulku je to jasné)..

Nicméně metodu verifyResponse mám obdobnou, jen používá jiné parametry a jak jsem psal na bráně gpwebpay fungovala bez problémů.

Zde je celá odpověď od serveru:
```
?MERCHANTNUMBER=M1E3CB2220&OPERATION=CREATE_ORDER&ORDERNUMBER=1225&PRCODE=0&SRCODE=0&MERORDERNUM=1&DIGEST=RjT2anIDynTS%2BSbP8%2BISCwtsdQX9WDSBfd09Yb%2BCqT8uDeQvpAWm1vzmvNqoM7TJZBFP7ZE4Jc5E%2F740ggF0SSj%2BGT17iZfIgkNKiiLzOTxeEugMnDmR2nS2%2F8JP8%2FH7LzOGlATSotjtaoa6jNbQAHFFXqRjTq5Dv6Q0AddtFWJsErkYop6CKimGX668I3gVgXKEIe398UcIx10DlMmoLQiJL4GKGZ%2BwZZyACswu5SXoqMrqJhsssRWmnAz8mmBKpdHLnAgwtGxqY7WZ0D1%2FLu9a4bmOHdvOqP9GKnHrle%2FXERGLvHSqQidLW65DwRypK3WiBwjUUMTqgWmWOgv8kw%3D%3D&DIGEST1=IkOMWhInVgEW0s%2B3XJiGXJERwG6uf9IZYxTBCGReyV%2BH6ZTyK4LV7xjciYaSZr8%2FbT31DB91JIj0fa0HdmCt3H5xxFJcoTRAT%2BcSeYd4SgedIHfCp6mGHn%2FmAb3sgR7dyk1eZwUw81tuvE9apJmUKOr2xLxZEVD%2F0B5GlDEMusDO9cLxHW9FpRcEV1vJB6DoYQQJeR1lG3U3V5QhYfFVGnD%2FFj1GTdVDRggL4SKAekv4hcpTiyqWP2nHUBsGzgl%2Fo2wtPvc0ZVH2E0zXYmfxOdogEUMh5%2BmknZB1RfzCBS3Irhx3GBnkDfhUNVbbzmXiP6vGF5tlzqdylnzDYuzY3g%3D%3D
```
Text k verifikaci je tedy:
```
CREATE_ORDER|1225|1||0|0|
```
resp. jsem zkoušel i 
```
CREATE_ORDER|1225|1|0|0
```

**Comment by dmarek** [comment]
Dobrý den,

pokud zkusím ověřit podpis řetězce "CREATE_ORDER|1225|1|0|0" (poskládáné parametry jsou v pořadí CREATE_ORDER|ORDERNUMBER|MERORDERNUM|PRCODE|SRCODE, vkládají se jen ty, které jsou vyplněny, tzn. MD a RESULTTEXT tam nejsou a to včetně oddělovačů), tak podpis oproti veřejnému klíči https://github.com/csob/paymentgateway/blob/master/eshop-integration/keys/mips_platebnibrana.csob.cz.pub je v pořádku.

verifikace prováděna oproti DIGEST z parametrů, po url dekodovani je to hodnota

```
RjT2anIDynTS+SbP8+ISCwtsdQX9WDSBfd09Yb+CqT8uDeQvpAWm1vzmvNqoM7TJZBFP7ZE4Jc5E/740ggF0SSj+GT17iZfIgkNKiiLzOTxeEugMnDmR2nS2/8JP8/H7LzOGlATSotjtaoa6jNbQAHFFXqRjTq5Dv6Q0AddtFWJsErkYop6CKimGX668I3gVgXKEIe398UcIx10DlMmoLQiJL4GKGZ+wZZyACswu5SXoqMrqJhsssRWmnAz8mmBKpdHLnAgwtGxqY7WZ0D1/Lu9a4bmOHdvOqP9GKnHrle/XERGLvHSqQidLW65DwRypK3WiBwjUUMTqgWmWOgv8kw==
```

Použitý algoritmus pro výpočet hashe je (stejně jako u GPE) SHA1

Pokud ověřím DIGEST1 (doplněný o MERCHANTNUMBER, řetězec pro ověření podpisu je tedy "CREATE_ORDER|1225|1|0|0|M1E3CB2220"), tak podpis také sedí.

verifikace prováděna oproti DIGEST1 z parametrů, po url dekodovani je to hodnota

```
IkOMWhInVgEW0s+3XJiGXJERwG6uf9IZYxTBCGReyV+H6ZTyK4LV7xjciYaSZr8/bT31DB91JIj0fa0HdmCt3H5xxFJcoTRAT+cSeYd4SgedIHfCp6mGHn/mAb3sgR7dyk1eZwUw81tuvE9apJmUKOr2xLxZEVD/0B5GlDEMusDO9cLxHW9FpRcEV1vJB6DoYQQJeR1lG3U3V5QhYfFVGnD/Fj1GTdVDRggL4SKAekv4hcpTiyqWP2nHUBsGzgl/o2wtPvc0ZVH2E0zXYmfxOdogEUMh5+mknZB1RfzCBS3Irhx3GBnkDfhUNVbbzmXiP6vGF5tlzqdylnzDYuzY3g==
```

Zkuste prosím ještě jednou ověřit, zda do verifikační funkce vstupuje s výše uvedenou hodnotou parametru DIGEST řetězec "CREATE_ORDER|1225|1|0|0", IMHO náš test vylučuje, že bychom používali jiný klíč.

**Comment by martenbrett** [comment]
Máte pravdu, ověření
```
CREATE_ORDER|1225|1|0|0
```
funguje. Myslel jsem, že jsem testoval i tuto větu a očividně ne. 

Přišel jsem na to, v čem byl zakopán pes. Na gpwebpay chodily i nevyplněné parametry jako prázdný řetězec (MD,RESULTTEXT), ale na nové bráně v odpovědi nejsou (změna podmínky z === '' na === null).
Díky
