### ISSUE TITLE
Na testovací bráně prochází platby reálnými kartami

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#211]
Jsem si poměrně jistý že to dříve nešlo a v dokumentaci je to taky tak.

**Comment by ratajskym** [comment]
Dobrý den, 

pro potřeby testování byla dočasně upravena konfigurace, aby bylo možné autorizovat všemi kartami. Toto nastavení jsem již přenastavil a chování brány je tedy dle dokumentace.

Chci Vás ujistit, že žádná transakce reálnou kartou neopustila testovací prostředí a všechny byly autorizovány proti simulátorům.
