### ISSUE TITLE
navratove data $_POST

### ISSUE THREAD

**Issue by robertgajdos** [csob/paymentgateway#212]
Prestali nam chodit navratove informacie pri platbach cez vasu branu. Platba sice prebehne, teda aspon ju vidim cez portal, ale kedze nam nevratite informacie o vykonanej platbe, tak zakaznikovi sa zobrazi hlaska, ktora je velmi zmetocna. Hlasku zobrazime, pretoze nedostaneme spat o uspesnej platbe s cislom objednavky, kotre vam posielame. To sa aj spravne zobrazuje v portali. Prosim o preverenie a odstranenie poruchy. Pre lahsiu kontrolu posielam jedno cislo objednavky  - 234466 .

![eshop](https://cloud.githubusercontent.com/assets/20966646/17583421/3e5f783c-5fb1-11e6-8a42-dfce9ad5eeff.jpg)

**Comment by ratajskym** [comment]
Dobrý den, 

na straně platební brány není co odstraňovat, určitě nejde o poruchu. Tohle se Vám děje u všech transakcí nebo jen u některých. Po úspěšné autorizaci dochází k redirectu zpět na eshop. Pokud ale uživatel zavře tab ještě před samotným redirectem, tak k vám informace o transakci nepropadne.

**Comment by robertgajdos** [comment]
Dobry den, robi nam to u vsetkych platieb, aspon to tvrdia zakaznici, ako to vieme osetrit?

--
Róbert Gajdoš

**Comment by ratajskym** [comment]
Na straně aplikace platební brány nedošlo k žádné změně a Vámi popisovaný problém neevidujeme ani u jiných zákazníků. Děje se Vám to i na integračním prostředí? Věřím, že dokážete nasimulovat transakci a podívat se na (odchytit si) odpověd z brány.

**Comment by ratajskym** [comment]
Dobrý den,

nemám od Vás zpětnou vazbu. Jak to vypadá s Vaším požadavkem?

**Comment by robertgajdos** [comment]
Dobry den, preveroval som to u nasho dodavatela web aplikacii, tiez som nedostal spatnu info, a vraj je to uz v poriadku. Mozte tento ticket uzavriet.

Dakujem.

--
Róbert Gajdoš

**Comment by ratajskym** [comment]
Jen doplním, že na straně platební brány k žádné změně nedošlo před ani po vzniku tohoto issue.
