### ISSUE TITLE
GET 404

### ISSUE THREAD

**Issue by ludekbenedik** [csob/paymentgateway#213]
Dobrý den,
implementuji platební bránu CSOB. Narazil jsem na problém s GET požadavky (ať už přes prohlížeč nebo klienta v aplikaci). Požadavky POST mi fungují.
Stejný problém mám jak pro verzi 1.5 tak pro verzi 1.6. Níže posílám ukázky. Můžete mi prosím poradit? Děkuji

**echo**

Request:
POST https://iapi.iplatebnibrana.csob.cz/api/v1.6/echo
{"merchantId":"M1MIPSxxxx","dttm":"20160811091542","signature":"IonNRLHWBdyMKQYjeqzKIwtaW9jk1UT3uplEN33IAGOzTfZJTkoh62tLqKo80t\/hWMHcUnfBo+VzBFXKP4m1hhd2KzawJq3n6P1PnyuVdQXp8cioUSj64sjqYvlCxqagtQAhpeoCeE82CEsmnzBETXiPpkBk6zuzd7K52A+tbtpze4aZ8bzGbRuD+Cu6P2aLRive0jh8yvI50b0rJuYmOxIMsHxpO8ay+gNFlfwynCSNIf1HW+84DmV50Mj89f7XQwzUp7BwsMSsOmLETXBr7pLryHfI40ML\/j8hkav\/3OYWGuWnsSk0rak8cSqWt68pfQ22E9rLaWN1MgcSxfAShA=="}

Response: {"dttm":"20160811091543","signature":"Q8HhY5TIIINhuIQWqQ0HF2Rqf+xy76X+v8GIWMKrVvw80FxgBf3CHadFkteioj03OCvHGw9NMW0y8SK+yZ9bGher94vrbkW7r+DfgqHSB3NjAnkUValzRVHyglfyBtReTHio8V3K1vScBZ49P8Z07pxUSNKSwFKyI6caKHg3JiqfdPrkssLBUu5k8qjJf5RmYZVeVYBnV1n5r584kwwtyZSFEiIsu4UcyA6GVJ+GX23TtvxUvQBsgkIh5ZWOllgbwyFTWKMYeomULCdeO6r1EhfA5sayk/PgaCVroAKT1F8R4gJVexqqqenWBOd1ZNeHNUKCc2hoQ4cXaokIQ7BN2Q==","resultCode":0,"resultMessage":"OK"}

Request:
GET https://iapi.iplatebnibrana.csob.cz/api/v1.6/echo/M1MIPSxxxx/20160811091825/HCnr58LW8IN6dtQoEihX1MtdVZ2QpdbSeWVtEfdikPZ83F6dxDpYjYo4u8rVwJwDEe3D3todijjsw7uLdzb2XbqeDIBLtEKAAGDy3d+w1v8TIATTScfSpI7FZ165NoxQQknZJcUAeT65zyh/sQlvgJpOdppRKfiNMvmh4UTDcSNFLSUZFwAZOALvcfI2EOTi8RLXHra+IlBR1UtAhXMqsoLf1zmgK+0f9yI6LIJUam6RJY0p2ZB47J26aRS+LatvJb6cjqfiXtoCeN7q9A1YkeI2IL0VZ7M/3bJogPhi2tsIrCeVw36vkwdXH7eHsCc6neTXGDpFKrXwC/V/PTYEkg==

Response:
HTTP status 404

**payment/init**

Request:
POST https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/init
{.......}

Response:
{.......}
OK

**payment/process**

Request:
GET https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/process/M1MIPSxxxx/6ce3374447379BH/20160811092104/pUa0eM5bE3oQwWDyqQIVebF/6XQyRw7fmNoUiqieflkuw9esRqDxD4jcZmCxnmbOzd1Pu6UO72ulxhyRsqIXYAQPBJawpN6JHEluFyGIydsHexxbFmBGPyW/H+GnZvPn4JycET56OmWeMxI0TcG/fh0xu87f/1ye7dbSsWhmTbgzqibTz4vhxcDpNvQ2/EGx9dtEKDo7HauoRSd4l3sQwDe7QwrAB+A+WlCyP/3TIqQF8Hkv7b+/+r411D4ibV78uU5Sx1twP6NV0XheWyFxv1mQrU01KGc7MhBhIAe80RybBVb4MeiRXOT4owjKZ6ZJ+VgQfoc8/E0Tm4nn+NEhYQ==

Response:
HTTP status 404

**Comment by ratajskym** [comment]
Dobrý den, mám takový pocit, že nesplňujete následující požadavek 

Dokumentace
Poznámka: hodnoty parametrů jsou „URL enkódovány“.

**Comment by ludekbenedik** [comment]
Máte pravdu, to jsem přehlédl.
Děkuji za rychlou odpověď
