### ISSUE TITLE
Error 400 s produkčním klíčem

### ISSUE THREAD

**Issue by greeny** [csob/paymentgateway#214]
Dobrý den,

máme problém s aktivací ostrých klíčů platební brány ČSOB na projektu zadejtisk.cz

Po úspěšné integraci platební brány do naší aplikace skrz integrační klíče jsme si nechali vygenerovat produkční klíče přes produčkní keygen. Na mail nám došel kód na aktivaci klíče, který jsme zadali do aplikace POSMerchant, čímž se aktivoval produkční klíč. V naší aplikaci jsme prohodili integrační klíč za produkční a začali používat, ovšem z platební brány dostáváme HTTP odpověď 400, neboli nevalidní klíče.

Na radu kolegy jsem i změnil veřejný klíč ČSOB banky za ten, který je v repozitáři na GitHubu, ovšem ten také nefungoval.

**Comment by ratajskym** [comment]
Dobrý den, 

jak to vypadá s Vaším požadavkem. Povedlo se Vám to vyřešit?

**Comment by revoke** [comment]
Chyba mohla být způsobena voláním URL testovací brány, která s produkčními klíči správně vracela 400.
