### ISSUE TITLE
Integrace brány do RS Joomla/Virtuemart

### ISSUE THREAD

**Issue by benyrfg** [csob/paymentgateway#215]
Dobrý den, existuje nějaký plugin (i třetích stran) pro snadnou integraci platební brány do Virtuemartu? Nebo nějaký návod pro ne-programátora, jak integraci vyřešit?

Děkuji

**Comment by ratajskym** [comment]
Dobrý den, máme k dispozici plugin pouze pro Wordpress (Woocommerce)

**Comment by benyrfg** [comment]
Dobrý den, našel jsem plugin pro integraci brány do Virtuemartu zde: http://www.platiti.cz/Virtuemart-GPWebPay.php

Máte s tímto pluginem nějaké zkušenosti a můžete ho doporučit?

**Comment by vzich** [comment]
Dobrý den,
máme zkušenosti s pluginem pro Woocommerce, který je k dispozici zde na githubu. Ohledně zkušeností s daným pluginem doporučuji se porozhlédnout po recenzích na internetu.
