### ISSUE TITLE
Integrační brána vrací 400

### ISSUE THREAD

**Issue by jiripudil** [csob/paymentgateway#216]
Dobrý den, v Kdyby/CsobPaymentGateway jsme narazili na to, že integrační brána vrací na jakýkoliv požadavek HTTP kód 400; merchant vč. klíčů je použitý z `Integration Examples`. Vyzkoušel jsem pro jistotu i přímo vaše `Integration Examples/eAPI v1.5/php` a problém je i tam :(

**Comment by Mspisar** [comment]
Dobrý den,

Ověřte si že máte bránu správně naklíčovanou ( dle popisu zde v githubu v technické sekci ):

Při odeslání požadavku na native API se vrací http status 400, bad request

Pravděpodobně se jedná o špatný podpis požadavku. Nejčastější chyby a opomenutí jsou následující:

řetězec pro výpočet podpisu je chybný nebo je použit špatný algoritmus pro podpis požadavku, více viz specifikace v rámci native API
používá se špatný privátní klíč obchodníka pro podpis požadavku (jedná se např. o záměnu privátního klíče pro integrační a produkční prostředí) **- nejčastější příčina** 
v případě parametru closePayment u operace payment/init se do řetězce pro podpis nevkládá povolená hodnota true nebo false ale (v případě použití php) hodnota 1 nebo 0

Více nám napoví číslo Vaší platební brány.

S pozdravem

Spisar

**Comment by ratajskym** [comment]
@jiripudil Doporučuji, abyste i na integračním prostředí pracovali pod svým vlastním merchant id. Id, které je v examplech je testovací a může u něj dojít ke změně klíčů, k zablokování, k přenastavení limitu ... 

Pokud budete chtít poradit, jak nastavi merchant id na itengrační bráně, kontaktujte nás. Jedná se o tři jednoduché kroky
- použití privátního klíče vygenerovaného na integračním generátoru + odeslání veřejné části do databáze brány
- použití veřejného klíče integrační brány
- url musí být nastavena na integrační bránu

**Comment by brychtaj** [comment]
Dobrý den, mám stejný problém jako jiripudil - http response: 400. Mám prostřednictvím keygenu vytvořeno vlastní Merchant ID, klíče jsem uložil do složky a změnil nastavení v setupu. Hodnota closePayment přenastavena na 0 (jedná se o PHP). Bohužel stále bez úspěchu. Vytvořil jsem vlastní repozitář, kde je testovací brána uložena, viz: https://github.com/brychtaj/paymentCSOB

Díky za případnou pomoc!

**Comment by ratajskym** [comment]
@jiripudil Dobrý den, posunul jste se ? Můžu toto issue uzavřít ?

**Comment by Koricz** [comment]
Zdravim, mam naprosto stejny problem. Uz jsem tim stravil 5 hodin a nevim, co dal :-(

Postup:
Na https://iplatebnibrana.csob.cz/keygen/  byly vygenerovany klice pro testovaci prostredi.
Vygenerovany verejny klic byl uploadovan.
URL pro API pouzivane v aplikaci: https://iapi.iplatebnibrana.csob.cz/api/v1.6/
Verejny klic banky:  mips_iplatebnibrana.csob.cz.pub

Jakykoliv pozadavek na vytvoreni platby (POST, payment/init) vraci 404. 

Zkousel jsem si vytvorit i noveho testovaciho merchanta s klici a to same. V tomto pripade jsem akorat neuploadoval vygenerovany verejny klic, neb jsem nevedel, jaky e-mail tam zadat.

**Comment by mrazekl** [comment]
Dobrý večer,

potřeboval bych znát minimálně Vaše merchant ID? Abych mohl prověřit Váš problém.

**Comment by Koricz** [comment]
Zdravim, je to M1MIPS0852

**Comment by mrazekl** [comment]
Děkuji, vidím, že jste měl problém s klíči(naposled 21:14), ten jste ale odstranil. Nyní vidím na bráně 9 úspěšně založených objednávek, které čekají na potvrzení. Pokud je do 30-ti minut nepotvrdíte, expirují, a přejdou do stavu zrušená platba.

**Comment by Koricz** [comment]
Zdravim, ano, uz to funguje. Chybejicim krokem bylo potverzeni verejneho klice. Toto je, rekl bych, dost nejasne v dokumentaci napsano. Mel jsem celou dobu za to, ze vygenerovanim klicu se verejny klic automaticky na brane zaregistruje a vice neni potreba delat...

**Comment by mrazekl** [comment]
Ano, vygenerováním a následným odesláním do banky se Váš veřejný klíč uloží na bráně. To máte pravdu. Jedná se ale o "VÁŠ" veřejný klíč.  Ve druhém kroku stahujete a potvrzujete veřený klíč "BANKY".

**Comment by Koricz** [comment]
Ano, ja tomu rozumim.  Kdyby to bylo lepe napsano, tak jsem to udelal hned :-) Z tohotho textu jsem pochopil, ze je to provedeno automaticky:

Generátor pracuje tak, že přímo na stránce se do počítače obchodníka stáhne JavaScriptová aplikace obsahující generátor klíčů. Průvodce tohoto generátoru pak provede následující kroky:

Vyžádá od plátce jeho MerchantID a registrovanou eMailovou adresu
Zkontroluje na platební bráně, zda je obchodník registrován a v jaké fázi se nachází
Nabídne pouze možnost generování testovacích klíčů
Lokálně vygeneruje testovací pár klíčů private key/public key
Privátní část private key uloží do souboru v počítači obchodníka
**Veřejnou část odešle zabezpečeným kanálem na platební bránu**

Integrace V tomto okamžiku může obchodník spustit integraci svého řešení (e-shopu) s platební bránou. Privátní klíč předá vývoji, který může vyvíjet a testovat proti veřejné iBráně. **Jeho klíč je tam automaticky zaveden ihned po vygenerování.**
