### ISSUE TITLE
Nastavení měny a jazyku Woocommerce plugin

### ISSUE THREAD

**Issue by ondrejvymetalik** [csob/paymentgateway#217]
Dobrý den,

nasadili jsme již produkční verzi brány, ale nevím kde nastavíme měnu na Euro (eshop je v eurech) a také to aby jazyk defaultně byl angličtina (prodáváme do celého světa).

Jedná se o plugin Woocommerce.

Díky

**Comment by vzich** [comment]
Dobrý den,
pro nastavení měny a jazyka v pluginu Woocommerce, je třeba změnit v souboru crypto.php -
```
static $LANGUAGE = 'CZ'; 
static $CURRENCY = 'CZK';
```
na
```
static $LANGUAGE = 'EN'; 
static $CURRENCY = 'EUR';
```
