### ISSUE TITLE
Platební brána - Woocommerce

### ISSUE THREAD

**Issue by represent-cz** [csob/paymentgateway#218]
Dobrý den,
testuji platební bránu na WooCommerce, postupoval jsem dle návodu a nastavil vše.
Brána vrátí odpověď normální s kódem 0 a stavem platby 1, resultMessage OK ale vyskočí na mě potom tato hláška "Inicilizace platby na platební bráně se nezdařila, nepodařilo se ověřit podpis odpovědi"

Nevíte kde může být problém?
`----- Tue, 30 Aug 2016 17:47:28 +0000 ----- orderNumber 21
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- parts of orderNumber 21, 
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- Checking order 21, orderId 21
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- SELECT * FROM monetTransaction WHERE orderNumber=21
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- after select
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- cart created
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- loaded paymentStatus:  PayId: 
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- payment not inicialized OR payment cancelled or declined OR detected cart changes
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- payment/init, url: https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/init/
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- payment/init sign: M1MIPS0863|21|20160830174728|payment|card|60000|CZK|false|http://www.silvergate.cz/shop/wp-content/plugins/WooCommerceMonetGateWay/returnUrl.php?orderNumber=21|POST|Testovací produkt|1|60000|Testovací produkt...|Testovací produkt|1|0|Objednavka 21|1|CZ
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- payment/init data: {"merchantId":"M1MIPS0863","orderNo":"21","dttm":"20160830174728","payOperation":"payment","payMethod":"card","totalAmount":60000,"currency":"CZK","closePayment":"false","returnUrl":"http:\/\/www.silvergate.cz\/shop\/wp-content\/plugins\/WooCommerceMonetGateWay\/returnUrl.php?orderNumber=21","returnMethod":"POST","cart":[{"name":"Testovac\u00ed produkt","quantity":1,"amount":60000,"description":"Testovac\u00ed produkt..."},{"name":"Testovac\u00ed produkt","quantity":1,"amount":0}],"description":"Objednavka 21","merchantData":null,"customerId":1,"language":"CZ","signature":"cy6CFKI7f+x3iB8I87bNutxHSTGNmo7dRfFvTdilHZm0WColJa0aRRRiAGEeCz2Yhlowcb2D1dKljh7jNjox07G7ffUl7RaHIsKYdn06ySt8ZTyySLOyJt9D+R2dojd5jy2bcFVu2bXlR1UeE9sRaZ8oxcfL2ftRdgHBaQVSEU8pfMLruaKHJ4x1\/ftn4Q38Mh1ByeI5j6fdumP+tPDu2hBgGpn6sZyZPQxruvZbV15Avpky8UZc43Juamdsfh2S6AszYgRv\/G7NTDDriAdVKMZcQq6jBiHvTUUDzhWmHJRo0kuxHt2gvA+BA48uqE+KTG7+TWn9IkYsVcv2ODVdqw=="}
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- payment/init result: {"dttm":"20160830194729","signature":"c+7j8kbp3DrHmPjWJUma5UaiKBFNp5d9uth4L3famKVcywlR5Evy46vzDKNq5bA0EXpa9zRE9XElvAAIRjsHVMDWJ4uJ6xCH1Q8bRd4oMoappm4djWq7iuj5T+NsT5PkerMSt9MF7ZPNhpeIqab2mN7fFzAC8Ne+nMDqw4bRHUjkgtqwFyEdII263bcI+ck5HLnr9KMo30sNc+GIoRNm9Pf+4+V/qYAt5g8LOgqmGIKe5ExashfP2nyL8ShQ+XGDSm22zWWqgLOaKyFkkZh0zufHaCEH87n0zF/WXcC13WvFipzJEPvcHOrLEYUUSarb2KPdYuIeOM1Uo5bi+7d9JA==","payId":"15457ee0c9249BH","resultCode":0,"resultMessage":"OK","paymentStatus":1}
----- Tue, 30 Aug 2016 17:47:28 +0000 ----- payment/init verify: 15457ee0c9249BH|20160830194729|0|OK|1`

**Comment by vzich** [comment]
Dobrý den,
pokud se vám nepodařil ověřit podpis odpovědi, zkontrolujte, zda používáte klíče, které jste si naposled generoval. Dnes jste si je totiž generoval již dvakrát. V nastavení Woocommerce tedy jako soubor privátního klíče nastavte privátní klíč, který jste si naposled vygeneroval a jako veřejný - klíč brány pro testovací prostředí (ke stažení [zde](https://github.com/csob/paymentgateway/tree/master/keys)). V případě, že Vám nastavení klíčů nepomohlo, vyzkoušejte znovu vytvořit transakci a prověříme ji.
S pozdravem
V. Zich

**Comment by represent-cz** [comment]
Dobrý den,
můžete to vyzkoušet projít?

Na shop.silvergate.cz si dejte do košíku jediný produkt a zkuste zaplatit.
Byl jsem správně přesměrován na platební bránu ale nejsem si jistý, jestli to je testovací rozhraní a nebo produkční, v nastavení brány máme toto https://iapi.iplatebnibrana.csob.cz/api/v1.6

Jinak klíče a podpisy vypadají, že fungují.
Marek

**Comment by vzich** [comment]
Dobrý den,
Ano, směřujete se na testovací(integrační) platební bránu. Vyzkoušel jsem tedy testovací platbu a objednávka se v pořádku autorizovala. Byla i následně korektně přesměrována zpět na eshop.

**Comment by represent-cz** [comment]
Ano, již to funguje.

Děkuji.
Marek
