### ISSUE TITLE
Přihlášení do iposman.iplatebnibrana.csob.cz

### ISSUE THREAD

**Issue by jbrhel** [csob/paymentgateway#219]
Dobrý den,

nedaří se mi přihlášení ani změna hesla do integračního iposman.iplatebnibrana.csob.cz. Můžete prosím ověřit, že je v systému zaveden uživatel "25911741"? 

Do produkčního posman, se pod tímto uživatelem přihlásit mohu. 

Děkuji

**Comment by Mspisar** [comment]
Dobrý den, 

S pomocí o přihlášení se prosím obraťte na akceptacekaret@csob.cz

S pozdravem

Spisar
