### ISSUE TITLE
http response: 500

### ISSUE THREAD

**Issue by mlc73** [csob/paymentgateway#22]
Dobrý den,

zkouším Váš testovací skript (nechal jsem si přidělit anonymní merchant ID). Nastavil jsem jej do setup.php včetně kličů. Přivolání testovacího formuláře se mi vrátí "http response: 500". V čem je chyba?

preparing payment init data ...

preparing cart data:
[
    {
        "name": "Shopping at ...",
        "quantity": 1,
        "amount": 10000,
        "description": "Lenovo ThinkPad Edge E540..."
    },
    {
        "name": "Shipping",
        "quantity": 1,
        "amount": 0,
        "description": "PPL"
    }
]

data to sign:
"A1104OVLv7|1|20150720132200|payment|card|10000|CZK|false|http://nbna208b.vsb.cz/eps2/example/gateway-return.php|POST|Shopping at ...|1|10000|Lenovo ThinkPad Edge E540...|Shipping|1|0|PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|1234|CZ"

prepared payment/init request:

processing payment/init request ...

payment/init failed, http response: 500

**Comment by mlc73** [comment]
ještě jsem zjistil, že po volání: $result = curl_exec ( $ch ); je v $result:
$result = {"resultCode":900,"resultMessage":"Internal error"}

**Comment by dmarek** [comment]
na strane platebni brany v integracnim prostredi mame zalogovano, ze payment/init request (POST) nebosahoval zadny JSON v tele pozadavku.

**Comment by dmarek** [comment]
+ melo by se zalogovat (vypsat na stranku), jaka data se v ramci payment/init posilaji...

```
echo "prepared payment/init request:\n";
echo json_encode($data, JSON_PRETTY_PRINT + JSON_UNESCAPED_SLASHES + JSON_UNESCAPED_UNICODE) . "\n\n";
```

**Comment by mlc73** [comment]
Tak vyřešeno: "description": "Nakup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)", obsahoval ne UTF znak, opravil jsem dlouhé a a už to jede.
