### ISSUE TITLE
Generovani klicu a ulozeni na Mac

### ISSUE THREAD

**Issue by evapavlik** [csob/paymentgateway#220]
Dobry den, omlouvam se za tento dotaz, ale...vygenerovala jsem si kody pres odkaz: https://iplatebnibrana.csob.cz/keygen/, kde je button ulozit klic. V obou pripadech pri pokusu o ulozeni se v prohlizeci zobrazi nove okno s odkazem blob.... Neni jasne, v jakem formatu a jak ukladat. Jde o stazeni v safari.

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod: TSGSMIPS-2039 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem

**Comment by ratajskym** [comment]
@evapavlik 

Dobrý den, 

bohužel pro Safari se generátor klíčů chová trošku jinak než pro ostatní prohlížeče. Vy v podstatě musíte udělat pouze to, že si privátní klíč zkopírujete a uložíte do souboru. Název souboru může být libovolný, jen ho pak musíte uvést i ve Vaší konfiguraci. Dále pak stiknete tlačítko Odeslat veřejný klíč do banky.

**Comment by evapavlik** [comment]
Dobry den,
a privatni klic se ma jmenovat .key, ze?

Verejny klic muzu pouzit tento, co je zde ve slozce nebo take musim generovat? https://github.com/csob/paymentgateway/tree/master/keys

**Comment by ratajskym** [comment]
Na názvu opravdu nezáleží, ale ano, pojmenujte jej podle vašeho přiděleného id tedy něco jako M1MIPSxxxx.key. Vygenerovaný veřejný klíč odešlete tlačítkem do databáze platební brány.

Veřejný klíč brány si musíte stáhnout z githubu. Vyberte si, jestli potřebujete testovací nebo produkční.

**Comment by evapavlik** [comment]
A nezalezi ani na pripone souboru, tzn je to musi byt pripona .key? Muzu ulozit klic do souboru klic.txt?

Sent from iPhone

7. 9. 2016 v 13:47, Martin Ratajský <notifications@github.com>:

**Comment by ratajskym** [comment]
Záleží na Vašem eshopu. Dokáže s takovým souborem správně pracovat? Pokud ano, pojmenujte jej podle libosti.

**Comment by evapavlik** [comment]
Pouzivame prave plugin od Vas - woocommerce, takze nevim, jake nastaveni nadstavba podporuje.

**Comment by ratajskym** [comment]
Pojmenujte jej jak chcete, jen to musíte uvést správně i v konfiguraci

**Comment by evapavlik** [comment]
chapu, diky.
