### ISSUE TITLE
Pouziti Název druhé položky košíku

### ISSUE THREAD

**Issue by evapavlik** [csob/paymentgateway#221]
Dobry den, pri testovani platebni brany mi neni jasne pouziti polozky Název druhé položky košíku. V testovacim prostredi, resp. v manualu doporucujete tuto polozku nastavit jako Postovne. Pri mem test, presto, ze mam postovne nastavene na 49, tak se mi zobrazuje jako ZDARMA. Prosim o vysvetleni, jaka polozka se presne tam zobrazuje. 
<img width="1280" alt="snimek obrazovky 2016-09-06 v 22 13 47" src="https://cloud.githubusercontent.com/assets/19546548/18289551/2145cf06-7480-11e6-8713-a51713fe0e7c.png">
<img width="1280" alt="snimek obrazovky 2016-09-06 v 22 20 19" src="https://cloud.githubusercontent.com/assets/19546548/18289556/26d731f8-7480-11e6-839a-eb414a5822bf.png">

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek jsme zaregistrovali. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

Spisar

**Comment by ratajskym** [comment]
@evapavlik 

Dobrý den, 

plugin se v tomto případě chová tak, že Vám sečetl cenu zboží + cenu dopravy (tedy 55 + 49 = 104). To se objevilo na platební bráně jako cena položky a doprava jako zdarma. Toto je způsobeno změnou na straně woocommerce.

Než vydáme opravu, vyzkoušejte prosím následující postup a dejte mi vědět
V adresáři pluginu monetWebPay editujte soubor crypto.php

Nejděte a zakomentujte následující řádky
//    $shippingTotal = substr($cart->get_cart_shipping_total(), 21, 2);
//    $shippingTotal = $shippingTotal * 100;

A pod ně přidejte následující řádek
    $shippingTotal = $cart->shipping_total * 100;

Budu rád za zpětnou vazbu

**Comment by evapavlik** [comment]
Dobry den,
diky, vecer to vyzkousim, dam veder. Nemuzu ted sahat do produkce.

**Comment by evapavlik** [comment]
Dobry den, oprava funguje, diky. Aktualizace pluginu probihaji automaticky pres woocommerce nebo je musim nekde aktivne stahovat?

**Comment by ratajskym** [comment]
Dobrý den, prozatím se musí plugin stahovat manuálně z githubu platební brány.

**Comment by evapavlik** [comment]
Diky.

dostanu nejakou notifikaci o updatu. Jak se o updatu dozvim?

**Comment by JakubSchejbal** [comment]
Dobrý den, mám obdobný problém. Založím objeddnávku

![image](https://cloud.githubusercontent.com/assets/22091966/18376490/f8a4af54-765f-11e6-8c77-0e5d1d9b6670.png)

Kde je poštovné (doručení) 117 Kč, ale když přejdu na platební bránu, tak tam je jako druhá položka pouze 11 Kč, v minulých případech tam bylo například jen 10 Kč.

![image](https://cloud.githubusercontent.com/assets/22091966/18376517/2eb1490e-7660-11e6-9b26-c163401be193.png)

Chtěl bych se zeptat na příčinu a co upravit tak, aby se tam dotahovalo korektní poštovné. Plugin jsem pro Woocommerce stahoval včera.

Díky moc,

Jakub Schejbal
jakub.schejbal@laserx.cz

**Comment by evapavlik** [comment]
Me pomohla uprava v kodu zminena v tomto vlakne. Pricina by mohla byt nove zony v woocommerce? Ale to jen tipuju.

Sent from iPhone

9. 9. 2016 v 7:39, JakubSchejbal <notifications@github.com>:

**Comment by JakubSchejbal** [comment]
@evapavlik máte pravdu, zkusil jsem a pomohlo mi to také. :) :+1:  Díky moc

J.S.

**Comment by ratajskym** [comment]
@evapavlik a @JakubSchejbal Děkuji Vám oběma za úspěšné otestování. Tuto úpravu commitneme. Co se týká automatické aktualizace pluginu, tak na tom v současné době pracujeme.
