### ISSUE TITLE
slozitost implementace ze strany zakaznika

### ISSUE THREAD

**Issue by marekpw** [csob/paymentgateway#222]
Dobry den,

bylo by mozne cely proces testovani a prechodu do produkce trochu zjednodusit? Delame to uz asi pro pateho klienta, a vzdycky se v tom ztracime jak my, tak oni. V podstate je nutne:

1) pozadat zakaznika o nastaveni technickeho kontaktu nekoho z nas, na tento e-mail nam pote prijde informacni mail o integraci,

2) vygenerovat v keygenu integracni klice

3) (nejvetsi hloupost) napsat zakaznikovi, aby nam zaslal **svoje** pristupove udaje do POS Merchanta, protoze pro testovaci verzi i produkcni se pouzivaji stejne udaje. Pokud je zakaznik trochu paranoidni a heslo ve svem POS Merchantu zmeni a zasle nam jej, stejne nefunguje, protoze v integracni verzi zustavaji stare udaje.

4) provedeni testovaci sady

5) zvalidovat testovani - vaze se na krok 3, pokud nam zakaznik udaje neposle, jsme v pasti

6) vygenerovat produkcni klice

7) tento klic poslat do produkcniho POSMana, kam se musime opet my nebo zakaznik prihlasit a **do 6 hodin** klic potvrdit kodem, ktery prijde na e-mail osoby na kterou je vazana smlouva. Toto byva dost casto problem, protoze ne kazdy sedi u PC 24 hodin denne, aby mel cas ihned zareagovat na nas pozadavek. Mnoho lidi navic resi spravu e-shopu za majitele, ktery byva vetsinou nedostupny, takze se do jeho e-mailove schranky v ramci 6 hodin nema sanci dostat. Zde je opet lepsi, kdyz nam zakaznik zasle svoje udaje, abychom to mohli udelat za nej (protoze to sami nedokazou - zakaznici jsou spravci e-shopu, ne technicti guru a POS Merchant je bohuzel strasne neintuitivni aplikace; obzvlast pro lidi, kteri berou nahrani obrazku k polozce za uspech), i presto ale potrebujeme kod, ktery je zaslan na jeho e-mail.

Hodne by pomohlo, kdybychom krok 3 mohli uplne odfiltrovat a minimalne prodlouzit trvanlivost. Potvrzovaci kod pro zavedeni produkcniho klice prece muze take rovnou dojit implementatorovi. Nemuzete vygenerovat jine udaje pro integracni prostredi, nez do produkce, a ty zakaznikovi poslat s tim, ze je ma poslat implementatorovi?

Cilem implementatora by melo byt branu rozchodit, ne udelat 50% prace a zbytek chtit po klientovi. Bohuzel jsme implementovali nekolik bran, at uz stare GP Webpay, nove GoPay, TatraPay, AGMO apod. a vse bylo znacne jednodussi, nez implementace Vasi brany.

Dekuji za zvazeni,

Michal Marek (IT STUDIO s.r.o.)

**Comment by ratajskym** [comment]
Dobrý den, 

děkuji za Vaše podněty. Shrnu to bod po bodu:

1. Nastavení technického kontaktu - tohle je potřeba vyplnit vždy, ať už je tam kontakt na obchodníka nebo externího implementátora brány.

2. Vygenerování klíče pro integrační prostředí - ano, cílem je oddělit integrační prostředí nejen pomocí url, ale i pomocí klíčů

3. Zajímavá myšlenka, mít pro obě prostředí různá hlesla. Jen se bojím, aby v tom následně nebyl zmatek. Každopádně na produkčním prostředí je obchodník při prvním přihlášení vyzván ke změně hesla. Je správně, pokud to udělá. Na integračním prostředí zůstane staré / původní heslo. Nebo jiný scénář může být, že Vám sdělí heslo ihned, Vy zařídíte vše nezbytné a heslo si změní až po úspěšném přepnutí brány do produkce. 

4. Pokud máte jedno řešení, které prodáváte více zákazníkům, tak samozřejmě nemusíte pokaždé absolvovat testy. Stačí se domluvit s bankou resp. s podporou platebních bran. 

5. Pokud Vám obchodník nepošle přihlašovací údaje, vždy se můžete obrátit na podporu platebních bran a tam Vám stav testů řeknou.

6. Vygenerování klíče pro produkční prostředí - ano, cílem je oddělit integrační prostředí nejen pomocí url, ale i pomocí klíčů (viz bod 2)

7. Časový limit prověříme a případně prodloužíme na 48hod.

Obecně si nemyslím, že práce implementátora a obchodníka není poměru 50:50 jak zmiňujete. Každopádně, pokud chce obchodník rozchodit platební bránu, ze zkušenosti vím, že bude muset spolupracovat. 

Martin Ratajský

**Comment by ozaoral** [comment]
dobry vecer @marekpw, diky za zpetnou vazbu, o nekterych tech vecech vime (a diky za utvrzeni v nich), nektere jsou nove ... takze v kazdem pripade tohle zustane otevrene :)

**Comment by dominikfiala** [comment]
Dobrý den,

nějaký vývoj ohledně této věci?

Po téměř roce stále aktuální otázka. Přijdou instrukce k implementaci, třetí bod je potvrzení v POS Merchant, do kterého ale nemám přístup.

Dominik Fiala, Pilot vos

**Comment by Mspisar** [comment]
Dobrý den,

co se týká přístupu do Posmerchantu. Obraťe se prosím na: akceptacekaret@csob.cz.
V připadě dotazů na konkrétní bránu uvádějte IČO, nebo merchant ID.

děkuji

s pozdravem

Spisar

**Comment by viktorzavadil** [comment]
Dobrý den,

řeším situaci, která s tímto issue úzce souvisí. Před přechodem do produkčního prostředí je zapotřebí provolat nějaké endpointy, ale nikde není řečeno, jestli by volání měl iniciovat samotný kód implementace nebo jde o to provolat služby jakýmkoliv způsobem. Jde mi o to, že ne každé volání je pro naší implementaci nutné (například nepotřebuji implementovat `GET echo` i `POST echo`, stačí mi jedno z toho, nebo *reverzovaná platba* - nyní tuto funkcionalitu nepotřebujeme). Chápu, že by bylo pěkné, aby byly služby volány přímo implementací a ověřila se tak funkčnost, ale některé volání jsou zkrátka samoúčelné.

Díky za reakci.

S pozdravem
Viktor Zavadil

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem

**Comment by ratajskym** [comment]
Dobrý den, tohle je přece na Vás. Někomu může vyhovovat POST, někomu GET. Ani Vás nenutíme metodu echo používat. Podle dokumentace API si implementujte co budete používat. Někteří obchodníci například nepoužívají opakované platby nebo návratové transakce.

Stačí takhle ?

**Comment by viktorzavadil** [comment]
Neodpovídá to úplně na mojí otázku. Jde mi o to testovací kolečko před nasazením do produkce (viz https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD). Pochopil jsem to tak, že před nasazením musíme zavolat všechny tyto operace, aby nám banka schválila implementaci. Tak to není? Můžete mi, prosím, objasnit, jak to je? Jak se tedy test implementace provádí? Díky.

**Comment by ratajskym** [comment]
Proveďte testy, které jsou předepsány. U metody echo si vygerte POST nebo GET. Pokud nebudete využívat reversal, tak to budete muset napsat na akceptacekaret@csob.cz. 

Úspěšnost testů si můžete ověřit v aplikaci Posmerchant.

**Comment by viktorzavadil** [comment]
Díky.
