### ISSUE TITLE
rekurzivní platba

### ISSUE THREAD

**Issue by represent-cz** [csob/paymentgateway#223]
Dobrý den,
chtěl bych se zeptat jak je možné udělat rekurzivní platbu v případě modulu woocommerce ?

Děkuji

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod: TSGSMIPS-2083 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem

**Comment by aKocian** [comment]
Dobrý den,

Doporučuji vám přečíst si tenhle [odkaz](https://github.com/csob/paymentgateway/wiki/eAPI-1.6#platba-na-klik-) 
Pokud byste po přečtení měl nějaké nejasnosti, neváhejte se na nás obrátit.

**Comment by represent-cz** [comment]
Dobrý den,
co přesně si tam mám přečíst ? Úplně si nejsem jistý, jestli to totiž nějak odpovídá na můj dotaz.
Počítám, že rekurzivní platba je platba, kterou vrátím zákazníkovi

**Comment by ratajskym** [comment]
@represent-cz 

Dobrý den, možná jsme se ztratili v názvosloví. Rekurzivní platba v názvosloví platební brány nic neznamená. Možná myslíte 
OneClickPayment - (reccurent transakce) -  jedná se o platbu na klik dříve uloženou kartou - plugin toto neumožňuje
Zmiňujete vrácení peněz zákazníkovi v názvosloví se jedná o reversal případně refund (návrat transakce) - plugin toto neumožňuje, návraty transakcí se provádí z aplikace PosMerchant

**Comment by ratajskym** [comment]
Myslíte testy, které vyžadujeme pro přechod do produkčního prostředí nebo nějaké Vaše vlastní testy ?

Naše testy opakovanou platbu nevyžadují a návrat transakce dělát z aplikace PosMerchant. Nic tedy programovat nemusíte.

**Comment by represent-cz** [comment]
no, snažím se přejít do produkce a mám toto vyjádření

Výsledek validace
Nalezena transakce se stavem: Zamítnuta
Nalezena transakce se stavem: Zrušena
Nalezena transakce se stavem: Autorizace potvrzena/Posláno k zaúčtování
Nenalezena transakce se stavem: Reverzováno Musíte udělat alespoň jeden reverzal

**Comment by represent-cz** [comment]
že chybí Reverzováno

**Comment by ratajskym** [comment]
Ano, reverzal - návrat transakce. Provádí se z aplikace Posmerchant. Tzn přejděte do výpisu transakcí a některou z potvrzených transakcí zrušte.

**Comment by represent-cz** [comment]
Funguje.
Děkuji
