### ISSUE TITLE
Přechod do produkčního provozu

### ISSUE THREAD

**Issue by represent-cz** [csob/paymentgateway#224]
Dobrý den,
na webu shop.silvergate.cz se snažím přejít do produkčního prostředí.
Je tam ale problém, který úplně nechápu. Odchytával jsem si statusy tedy a snažil se to nějak dořešit ale bohužel se mi to úplně nepovedlo.

Při přechodu do ostrého provozu jsem znovu vygeneroval klíče a odeslal je, změnil URL pro API ale nyní jsem ve stavu, kdy se buď nedokáže ověřit podpis nebo to hodíš chybu s tím, že se nezdařilo inicializovat platební bránu ( její přesměrování ).

Může to být i SSL certifikátem,který je použitý ? Nebo kde může být chyba?

**Comment by joskera** [comment]
Dobrý den,
prověřil jsem Vaši plat. bránu v produkčním prostředí a zjistil jsem, že se Vám již povedlo založit několik plateb, které skončily zamítnuty z důvodu jejich expirace. To znamená, že žádná z nich nebyla dokončena, v logu vidím, že chybí paymentProcess.
Zkontrolujte zda jste si změnil veřejný klíč banky na produkční (mips_platebnibrana.csob.cz), který naleznete zde https://github.com/csob/paymentgateway ve složce keys.

S pozdravem Jiří Oškera.

**Comment by represent-cz** [comment]
Dobrý den,
jedná se o integraci WooCommerce, což jste ale asi poznal z webových stránek.
Keys mám tedy vložit do stejné složky jako mám teď vygenerované klíče ??

**Comment by ratajskym** [comment]
@represent-cz 
Dobrý den, 

v testovacím prostředí Vám to předpokládám fungovalo. Do stejné složky jako máte testovací klíč, vložte klíč produkční a název klíče změníte i v administračním rozhraní.

**Comment by represent-cz** [comment]
já jsem právě vygeneroval nový klíč, zaslal jsem vám jej ale název souborů s klíčem jsem nechal stejný..
Upřímně nechápu, kde je problém protože reálně to vidím na 3 jednoduché kroky
1. vygenerovat nové produkční klíče
2. nahrát na FTP
3. změnit Endpoint URL pro PLatební bránu

**Comment by ratajskym** [comment]
4. potvrdit nově vygenerovaný klíč v prostředí posmerchant
5. stáhnout produkční veřejný klíč platební brány, jak Vám radil kolega @joskera

**Comment by represent-cz** [comment]
klíče jsem potvrdil

**Comment by ratajskym** [comment]
Ještě jednou ... s nejvetší pravděpodobností máte problém s veřejným klíčem platební brány. Stáhl jste si jej z githubu ?

**Comment by represent-cz** [comment]
Ano, stáhnul. Nasadil jsem jej do složky monetWebPay/keys
teď k němu mám v pluginu nastavit cestu nebo smazat název klíče, který tam mám napsaný?

**Comment by ratajskym** [comment]
Produkční klíč je pojmenovaný jinak než testovací. Takže musíte změnit jeho název v administraci.

**Comment by represent-cz** [comment]
Nejspíš se někde nepotkáváme myšlenkově.. 
Vysvětlím..

Vygeneroval jsem si nové klíče a ty jsem si stáhl a nahrál na FTP do složky monetWebPay/keys
Potom jsem klíče potvrdil v rozhraní posmerchant
Změnil jsem Endpoint URL na https://api.platebnibrana.csob.cz/api/v1.6

![image](https://cloud.githubusercontent.com/assets/4127617/18465146/7793fa30-7995-11e6-9029-c12179c4f248.png)

Momentálně nastavení vypadá tedy takto.

**Comment by ratajskym** [comment]
Nejspíš se někde nepotkáváme myšlenkově.. 
Vysvětlím..

Vygenerujete si privátní a veřejný klíč
- privátní slouží pro zašifrování Vaší odpovědi
- veřejný slouží pro PLATEBNÍ BRÁNU, aby pomocí něj dokázala ověřit podpis

Stáhněte si veřejný klíč platební brány z Githubu [zde](https://github.com/csob/paymentgateway/tree/master/keys)
- platbení brána vlastním veřejným klíčem zašifruje odpověď pro Váš eshop
- stažený veřejný klíč slouží pro ESHOP, aby pomocí něj dokázala ověřit podpis 

Takže ... v adresáři keys budete mít klíč pojmenovaný mips_platebnibrana.csob.cz.pub a v administraci u veřejného klíče napíšete mips_platebnibrana.csob.cz.pub

Je to stejný postup jako na testovacím prostředí. Případně se poraďte s někým, kdo Vám to nastavoval

**Comment by represent-cz** [comment]
To je právě největší paradox. Já jsem nastavoval testovací prostředí a problém vesměs nebyl.
Klíče jsem od Vás nestahoval a rovnou jsem je vygeneroval a nasadil.

Teď jsem si znovu vygeneroval veřejný a soukromý klíč. 
Nasadil jsem to do prostředí. A stejně to nefunguje.

Teď pro změnu to hlásí přímo error.
Můžete to vyzkoušet na eshopu
![image](https://cloud.githubusercontent.com/assets/4127617/18466090/7121cdbc-799a-11e6-9722-eb73c63006fd.png)

**Comment by represent-cz** [comment]
vyřešeno :) xdebug pomohl i tak děkuji
