### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by westkir** [csob/paymentgateway#225]
Dobry den,

Nejak mi nefunhuje castecny refund

http method: PUT
gateway url: https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/refund/
req: {"merchantId":"M1MIPS0626","payId":"0369832c5cb2dBI","dttm":"20160919110011","amount":100,"signature":"f3PRsS3YqkYRvqQYCUOud/yOH4NOEci3F/rR45zwwyZxB5NOz0X3BMC4m2dCl4Ot2us5iL8An3C4s20UfSGGgTpGJGmxXrYSmiGA2q2HtTdpaW1auLGAbY5V0eIjwVjBFJ3jYuYIcqmLxbCbP/hkrNgtDYSN8I+SgB6G9m+ueXPg8XfHCN6eITgkl5K8LVlPkU8zRwkPE8c204pjwMUFBN7rIZWI/FruBvY4P86wpGzSfd3X/8zP5+aySaMRlcXtEQWD04nKV/CwYn6Ts4ql6pEU2Q19suDT9MxMBZ0OPzDf8x+HpfR4I2Yv4lk/nctxxYWbxLId+2Ps/xLxFWVZUQ=="}

Stav  (8)

http status: 400

payment/refund failed, http response: 400

**Comment by ratajskym** [comment]
Dobrý den, v našem aplikačním logu vidím chybu v podpise. Zaměřte se právě na toto.

September 19th 2016, 17:00:15.501
Invalid paymentRefund signature for merchant M1MIPS0620

**Comment by westkir** [comment]
Jinak ostatni pozadavky funhuji (refund uplnej, platba)

**Comment by ratajskym** [comment]
Zahrnujete do podpisu i částku?

**Comment by westkir** [comment]
ne jak to mam udelat ???

**Comment by ratajskym** [comment]
Úplně stejně jako když tam zahrnujete merchantId, payId, dttm ..

**Comment by westkir** [comment]
Jj uz to jde, jenom jeste dotaz mam posilat castku kterou chci vratit nebo kolik ma zustat ( platba 200 KC mam vratit 50 Kc , mam posilat 50 nebo 150 ?

**Comment by ratajskym** [comment]
Viz dokumentace - amount - Požadovaná částka pro částečný refund v setinách základní měny

**Comment by westkir** [comment]
Dekuji moc krat

**Comment by ratajskym** [comment]
Rád jsem vám pomohl. Task zavírám.

**Comment by ratajskym** [comment]
Interní issue TSGSMIPS-2124
