### ISSUE TITLE
Přechod do produkčního prostředí

### ISSUE THREAD

**Issue by marekkrivan** [csob/paymentgateway#226]
Dobrý den,
 měl bych dotaz provádím validaci vaší platební brány ovšem nedaří se mi nasimulovat transakci se stavem zamítnuto. Vaše brána vždy napíše zamítnuto a že mám možnost zadat jinou platební kartu nebo se vrátit k obchodníkovi a zvolit jinou platební metodu. Ovšem jediný odkaz/tlačítko je Zrušit návrat do obchodu a když na to kliknu tak mě to pokaždé přesměruje se stavem "zrušeno" ano logické.

Můžete mi tedy prosím povědět co mám přesně udělat, abych nasimuloval tuto chybu a vše prošlo jak má.

Děkuji za odpověď

**Comment by vzich** [comment]
Dobrý den,
transakci se stavem zamítnuto - stav 6, nasimulujete například tím, že inicializujete platbu a následně po přesměrování na bránu neprovedete žádnou akci, případně zavřete okno prohlížeče. Transakce poté po 30ti minutách expiruje a dostane se do stavu 6 - zamítnuto. Jednotlivé simulace stavů jsou popsány v dokumentaci, konkrétně tento příklad [zde](https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD#expirovan%C3%A1-zru%C5%A1en%C3%A1-platba)
S pozdravem 
VZ

**Comment by marekkrivan** [comment]
Děkuji. Již zvalidováno
