### ISSUE TITLE
chybny podpis odpovedi z "Legacy" rozhrani  (prechod z GP WebPay)

### ISSUE THREAD

**Issue by slim63** [csob/paymentgateway#227]
- chyba nastava v pripade ze request nema vyplnenu hodnotu v atribut MD
- response z brany pak tento atribut neobsahuje vubec a ani v podpisu evidentne neni zahrnut, pricemz by v tomto pripade tam mel byt oddelovac (pipe - 0x7c)

tzn. napr. misto stringu
"CREATE_ORDER|000002016000009|2016000009||0|0|OK"
podepisujete evidentne
"CREATE_ORDER|000002016000009|2016000009|0|0|OK"

Otazka: budete s tim neco delat ?

P.S. zkousel jsem jen na testovacim prostredi

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaznamenán o dalším průběhu Vás bude informovat odpovědný kolega.

S pozdravem

Spisar

**Comment by slim63** [comment]
pro uplnost prikladam request:
`MERCHANTNUMBER=A2001kpZG4&OPERATION=CREATE_ORDER&ORDERNUMBER=000002016000009&AMOUNT=300&CURRENCY=203&DEPOSITFLAG=1&MERORDERNUM=2016000009&URL=http%3A%2F%2Flocalhost%3A8080%2FKoplaGW%2FGPWebpayReceiver&DESCRIPTION=description+ev.+v+base64&MD=&DIGEST=RHumlBFxLkqKpjHHF9hpeojHAXIFUx%2Bmhw%2FixCDX7QbMmeha0iKNXio99zByVe%2BiA%2BFIB3Q7FFiF5xa65CeOy%2FZEXcl8pfxNbUfXg0ePSN%2FjL7HsEd9EF82nNDgrEN%2BT7oL9Rp9hM8Si2VZctID3TN3rGlTfoxDiydXV9x8%2FHgsYXVY6yBgKGAosZksWC510Clxpb9mHTAbQhiTY8Fkx7fYY77joC0yA%2BHxUx8xeV6mRq4pSHTyYfDI%2B64e6JsgoKW7iMBhz1VbUabNm1xz3WkDJJG3Jxf2%2B7j6bUJF0ywx3IH3luq7%2FV1KTPXZJvKEZkwrGhDBPQ2lsQonZBD7o7w%3D%3D&`

**Comment by dmarek** [comment]
dobrý den, jedná se o chybu (prázdný parametr MD - empty string - poslaný při přesměrování z eshopu na bránu se nepředává do odpovědi při zpětném redirectu na eshop), opravíme. Pozn: pokud je MD nastavený, tak nastavení do odpovědi funguje OK.

**Comment by ratajskym** [comment]
@slim63 Dobrý den,
na testovací prostředí jsme nasadili novou verzi aplikace, která opravuje Vámi popisované chování.  Vyzkoušejte prosím a dejte vědět. Následně bychom ji nasadili do produkčního prostředí.

Děkuji

**Comment by slim63** [comment]
bezva, zkusil jsem a vypada to dobre
diky
mejte se
HP
