### ISSUE TITLE
Nefunhuje platba 

### ISSUE THREAD

**Issue by westkir** [csob/paymentgateway#229]
Dobry den,

Nefunhuje platab kartou na strankach pozitek.cz a skotska-whisky.cz ale funhuje na strankach http://www.rumy.cz/ , nevim cim to je, 

Merchand ID : M1MIPS0620

Dekuji.

**Comment by ratajskym** [comment]
Na produkčním prostředí vidím chybu v podpise 
Invalid paymentInit signature for M1MIPS0620

Může to být způsobeno např. špatným klíčem nebo špatným sestavením podpisu

**Comment by westkir** [comment]
Na 2 domenach to funhuje ale na 2 ostatnich ne jak jeto mozne , kod se nemeni?

**Comment by westkir** [comment]
Zmernil klic stale to same

**Comment by ratajskym** [comment]
Pokud máte stejný kód, ale chyba v podpise přetrvává, pak je to určitě chyba v klíčích. Pro všechny Vaše domény máte stejný privátní klíč? Nebo máte pro každý projekt jiný klíč?

**Comment by westkir** [comment]
pro kazde domeny mam stejny privatni klic

**Comment by westkir** [comment]
na 2 to funhuje na 2 ostatnich ne

**Comment by ratajskym** [comment]
A ten veřejný klíč, nahrál jste to správně přes formulář? Jaké jsou ostatní id ?

**Comment by westkir** [comment]
verejnej klic mam stazenej od github.com mips_platebnibrana.csob.cz.pub

Id ceho prosim ?

**Comment by ratajskym** [comment]
Píšete, že na dvou shopech Vám to funguje a na dvou ne. Poslal jste jedno merchant id. Napište i zbývající merchant id. 

Ohledně veřejného klíče jsem měl na mysli Váš veřejný klíč, nikoliv veřejný klíč brány. V jednom z issue jsem to vysvětloval takhle:

Vygenerujete si privátní a veřejný klíč

privátní slouží pro zašifrování Vaší odpovědi
veřejný slouží pro PLATEBNÍ BRÁNU, aby pomocí něj dokázala ověřit podpis
Stáhněte si veřejný klíč platební brány z Githubu zde

platbení brána vlastním privátním klíčem zašifruje odpověď pro Váš eshop
stažený veřejný klíč slouží pro ESHOP, aby pomocí něj dokázala ověřit podpis
Takže ... v adresáři keys budete mít klíč pojmenovaný mips_platebnibrana.csob.cz.pub a v administraci u veřejného klíče napíšete mips_platebnibrana.csob.cz.pub

Je to stejný postup jako na testovacím prostředí. Případně se poraďte s někým, kdo Vám to nastavoval

**Comment by westkir** [comment]
merchant id je jedno pro vse ? chova se to jako 1 shop ale pod ruznyma domenami , jinak stahl jsem pres ten formular i privat key i publik key.

**Comment by westkir** [comment]
Postup:

Merchant ID: M1MIPS0620

Název obchodního místa: pozitek.cz

1. Generování produkčních klíčů pro platební bránu

Pro generování produkčních klíčů pro produkční prostředí klikněte na níže uvedený odkaz, zadejte Merchant ID a e-mail kontaktní osoby pro technickou implementaci, který je vyplněn ve smluvní dokumentaci.

https://platebnibrana.csob.cz/keygen/

Následně Vám bude odeslán jednorázový kód.

2. Aktivace produkčních klíčů pro platební bránu

Nahrání certifikátu potvrďte zadáním jednorázového kódu do produkční aplikace POS Merchant.

https://posman.csob.cz/posmerchant

Po splnění výše uvedených kroků můžete začít používat svou platební bránu od ČSOB.

Veškeré technické parametry a podporu naleznete zde:

https://github.com/csob/paymentgateway

**Comment by ratajskym** [comment]
Ano a předpokládám, že podobný email jste musel obdržet i pro ostatní domény.

**Comment by westkir** [comment]
jo ale 2 krat stejnej email a ostatni domeny vubec ne davali , ale vyslo naopak ze oni funhuji a 2 ktere dali do banky ne

**Comment by westkir** [comment]
ted jeste to shrnu
Pozitek.cz - zadana do systemu banky, - nefunhuje
www.skotska-whisky.cz/  zadana do systemu banky, - nefunhuje
rumy.cz - nezadana do systemu banky - funhuje
http://www.brandy.cz/ - nezadana do systemu banky - funhuje

**Comment by ratajskym** [comment]
Ok, tak pojďme postupně. Dnes cca ve 14hod jste vygeneroval pro Pozitek.cz nové klíče. Vygeneroval se Vám nový veřejný klíč, ten jste tlačítkem odeslal na platební bránu. Privátní klíč, který se vygeneroval, nahradil jste jej v aplikaci? Jeden už jste tam měl, takže bylo potřeba ho nahradit. Tento krok bohužel nedokážu ověřit.

**Comment by westkir** [comment]
Jo presne tak , byla tam moznost stahnout 2 klice - pub-privat , oba stahnul a nahral do aplikace, nasledne potvrdil heslem v bance

**Comment by westkir** [comment]
Kod je stejnej na vsech 4 strankach (php) chovase to jako jeden shop , akorat meni pouze domeny, tak ze teoreticky kdyz funhuje jeden tak funhuji 3 ostatni , je tam nejak blokace ze strany banky

**Comment by ratajskym** [comment]
V logu nyní vidím, že Vám dotaz na stav transakce ( operation payment/status (v1.6) ) proběhl úspěšně, tzn. klíče jsou v tomto případě u M1MIPS0620 v pořádku. Zkuste tedy transakci ještě jednou, pokud to selže, bude chyba definitivně u Vás.

**Comment by westkir** [comment]
ted jsem to skusil , zase jak rikam nic ne menim v kodu ale tam to funhuje a na pozitek.cz ne

**Comment by westkir** [comment]
ted proved to same na rumy.cz a v poradku se dostal na stranky platby

**Comment by ratajskym** [comment]
Pod id M1MIPS0620  v čase 15:16:40.226 vidím úspěšnou transakci resp zobrazení brány. Takže z pohledu platební brány je vše nastaveno v pořádku.

**Comment by westkir** [comment]
jj akorat nefunhuje to na domene pozitek.cz

**Comment by westkir** [comment]
email poslan ok Array ( [merchantId] => M1MIPS0620 [orderNo] => 20436 [dttm] => 20160926152255 [payOperation] => payment [payMethod] => card [totalAmount] => 146700 [currency] => CZK [closePayment] => true [returnUrl] => http://www.pozitek.cz/kosik/ [returnMethod] => POST [cart] => Array ( [0] => Array ( [name] => Shopping at ... [quantity] => 1 [amount] => 129300 [description] => Požitek.cz... ) [1] => Array ( [name] => doprava [quantity] => 1 [amount] => 17400 [description] => ) ) [description] => Požitek.cz [merchantData] => MjA0MzY= [customerId] => 20568 [language] => CZ [signature] => JGnw4TW59pqtPhyrRor+9Y9M57GtCLrAx4cBKq/rPva+fNyodcn1eb9AjVO+2ZTW7X1rGHxdtmgpC2VOpobn3HhyB6XSXNMgG2DZN2C1GJtGmpKjHqREZE2XBLG8RRt0XG2G+3m78gmyqrcW698TbhdCWwvwkAnhbm8zPbROBmuGQMSnR+Rr1vaZN3ySyfD3MJIwJ3vn2ASB0M2e/1tPi53+NoosI8CCYlnlJIISn8vJ8LGekQQBb09dLOYYg4mGdV5j9tr/42/EslUYEZimEuu/jDzvaYDwIlzgVaiDssM/FeNBv39PwNodeQkvvZOi0Cq09rcQzUH5YSSQzuNE7A== )

**Comment by ratajskym** [comment]
Všechny weby máte na stejném serveru? Všechny 4 weby používají jednu konfiguraci ??

**Comment by westkir** [comment]
ano vse je stejne

**Comment by westkir** [comment]
uplne vse, a nevim jak jeto mozne

**Comment by ratajskym** [comment]
No, to prostě není možné. Pokud všechny aplikace používají stejné merchant id a stejný privátní klíč tak to musí fungovat.

**Comment by westkir** [comment]
To prave ja si rikal take! Ale 2 funhuji a 2 ne (hlavne ze funhuji ty ktery nedali do bank systemu)

**Comment by westkir** [comment]
vidite vse s logu , jinak pokusim se jeste neco udelat ale nevim

**Comment by westkir** [comment]
nemate bloklou domenu pozitek.cz a http://www.skotska-whisky.cz/

**Comment by ratajskym** [comment]
Tím že používáte jedno merchant id, tak nemůžu dohledat co je špatně. Dejte mi přístup na FTP.

**Comment by westkir** [comment]
FTP neni , pouze ssh bude to stacit ?

**Comment by vzich** [comment]
Zašlete prosím přístupy na mail akceptacekaret@csob.cz, zmiňte také, že se odkazujete na toto github issue. Děkuji.

**Comment by westkir** [comment]
Odeslal , dekuji

**Comment by ratajskym** [comment]
Ještě se vrátím k nastavení merchant id. Podle toho co vídím, tak máte založeno pouze jedno merchant id tzn. že když budou zákazníci nakupovat na libovolném webu, uvidí vždy nastavení pro bránu pozitek.cz

M1MIPS0620 - Pozitek.cz
neexistuje - www.skotska-whisky.cz
neexistuje - rumy.cz
neexistuje - www.brandy.cz

**Comment by westkir** [comment]
no jeto skoro tak

**Comment by westkir** [comment]
skotska-whisky.cz ma take nejake id protoze bylo zalozeno v bance

**Comment by westkir** [comment]
M1MIPS0620 - Pozitek.cz
NEJAKE ID  - www.skotska-whisky.cz
neexistuje - rumy.cz
neexistuje - www.brandy.cz

**Comment by ratajskym** [comment]
Pod touhle doménou na produkčním prostředí ne. Pokud Vám přišel email, pošlete mi jeho id

**Comment by westkir** [comment]
odeslal pozadavek majiteli stranek , snad to najdou

**Comment by westkir** [comment]
vlasnte asi ne , mate pravdu 
M1MIPS0620 - Pozitek.cz
neexistuje - www.skotska-whisky.cz
neexistuje - rumy.cz
neexistuje - www.brandy.cz

protoze nevidim skotska-whisky.cz v admin v bancce posman.csob.cz/

**Comment by westkir** [comment]
Dobry den, mam to vyreseno, muzete zavirat, dekuji!
