### ISSUE TITLE
Výzva k aktualizaci prohlížeče

### ISSUE THREAD

**Issue by bretislavstepan** [csob/paymentgateway#23]
Pokud chci provést platbu v okně, které se otevírá při přihlášení k wifi hotspotu, nelze provést platbu.
I když se jedná o zařízení s nejnovějším iOS 8.4.

![img_1995](https://cloud.githubusercontent.com/assets/10938626/8955324/df9781c2-35eb-11e5-9c59-c3f5b45b147b.PNG)

**Comment by ratajskym** [comment]
Dobrý den, 

vyzkoušejte prosím ještě jednou a dejte nám vědět.

Děkuji

**Comment by bretislavstepan** [comment]
Díky, je to vyřešeno.
