### ISSUE TITLE
Volanie GET metod z ASP.NET

### ISSUE THREAD

**Issue by TikyConte** [csob/paymentgateway#230]
Zdravim,
snazim sa implementovat metodu payment/status.

Ked url vlozim do browsera tak mi funguje, ked sa tu istu url snazim volat z aplikacie program si ju vzdy upravi, a tym padom skoncim na 404.

Skusil som 5 sposobov vsetky koncia na 404.

Nevie mi niekto ukazat ako volat GET metody ?

Tu su dotnet sposoby ktore som vyskusal, kazdy s niekolkymi nastaveniami:
`Dim getUrl As String = String.Format("{4}api/v1.6/payment/status/{0}/{1}/{2}/{3}",
                                 HttpContext.Current.Server.UrlEncode(merchantId),
                                 HttpContext.Current.Server.UrlEncode(payId),
                                 HttpContext.Current.Server.UrlEncode(datum),
                                 HttpContext.Current.Server.UrlEncode(podpis),
                                                 baseUrl)`

            Using wc As New WebClient
                Dim x = wc.DownloadString(getUrl)
                Dim y = 0
            End Using

            Using wc As New Net.Http.HttpClient
                Dim x = Await wc.GetAsync(New Uri(New Uri(getUrl), getUrl))
                Dim y = 0
            End Using

            Dim request As WebRequest = WebRequest.Create(getUrl)
            request.Credentials = CredentialCache.DefaultCredentials
            request.Method = Method.GET
            request.ContentType = "application/x-www-form-urlencoded"
            Dim response As WebResponse = request.GetResponse()
            Dim dataStream As Stream = response.GetResponseStream()
            Dim reader As New StreamReader(dataStream)
            Dim responseFromServer As String = reader.ReadToEnd()
            reader.Close() : response.Close()

            Dim client = New RestClient(baseUrl)
            Dim Request = New RestRequest(getUrl, Method.GET)
            request.Resource = baseUrl & getUrl
            Dim response = client.Execute(request)

            If response.StatusCode = HttpStatusCode.OK Then
                Dim jss = New Script.Serialization.JavaScriptSerializer()
                Dim CSOBResponse As CSOBPlatbaInitResponse = jss.Deserialize(Of CSOBPlatbaInitResponse)(response.Content)

            End If

            Dim client = New RestClient(baseUrl)
            Dim Request = New RestRequest("api/ v1.6/payment/status", Method.GET)
            Dim response = client.Execute(request)
            request.AddParameter("merchantId", HttpContext.Current.Server.UrlEncode(merchantId))
            request.AddParameter("payId", HttpContext.Current.Server.UrlEncode(payId))
            request.AddParameter("dttm", HttpContext.Current.Server.UrlEncode(datum))
            request.AddParameter("signature", HttpContext.Current.Server.UrlEncode(podpis))

            If response.StatusCode = HttpStatusCode.OK Then
                Dim jss = New Script.Serialization.JavaScriptSerializer()
                Dim CSOBResponse As CSOBPlatbaInitResponse = jss.Deserialize(Of CSOBPlatbaInitResponse)(response.Content)

            End If

**Comment by Mspisar** [comment]
Dobrý den,

Váši žádost o podporu k platební bráně jsme zaregistrovali. O dalším postupu Vás bude informovat odpovědný kolega.

s pozdravem

Spisar

**Comment by vzich** [comment]
Dobrý den, 
můžete zaslat Vaše merchant ID a např. přibližný čas, kdy jste se pokoušel volat payment/status, pro prověření konkrétních pokusů?
Nicméně na první pohled bych vyzkoušel Content-Type: application/json namísto application/x-www-form-urlencoded.

**Comment by TikyConte** [comment]
No.
tento get je aktualne vytvoreny, funkcny zadanim do browsera v case 15:21
cca.
https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/status/M1MIPS0964/75a0dc7fdedc6BJ/20161006151013/nzULQNAf6EW8K0jGoOjoij%2bukuCs57MkD%2bYsBnSeISKZLtB1hovadVIxGk6Ic5%2b8tvz6i8Rzb9f1sVNU8BsLFYiUUHq%2fmATTrqpQ29rjK0sRDkG8GKXj9yDutbBv9Cotr27IP4hIyIo0rMI1CrMISMAVUQMUdZxOP%2f4jHjgBwbf9jOJucwK1bWdXe%2fOd4ReDrcqCFm8OvSP%2fg1NmbkgEJdJENeRMSAHaicYA1qqeJZoAZyNHF1IrrRfFydxx9kwYTAyOswZ3xJeEJjw%2f0lIrJozhY4M%2fuVf2rLTTmYKphDgZRHmQcQcAcAdMaiAa2On5AVw5oJaGx3zFTWXJB2SKmw%3d%3d

zavolanim ho tymto sposobom dostanem eror 400 tiez z toho casu.

merchant id je: M1MIPS0964

Dim request As WebRequest = WebRequest.Create(getUrl)
            request.Credentials = CredentialCache.DefaultCredentials
            request.Method = Method.GET
            request.ContentType = "application/json"
            Dim response As WebResponse = request.GetResponse()
            Dim dataStream As Stream = response.GetResponseStream()
            Dim reader As New StreamReader(dataStream)
            Dim responseFromServer As String = reader.ReadToEnd()
            reader.Close() : response.Close()

ked ten reuqest odchitim cez fiddler tak proste hocijaka netova kniznica tu
url finalne upravi a neviem preco.



2016-10-06 8:52 GMT+02:00 Vítězslav Zich <notifications@github.com>:

**Comment by vzich** [comment]
Dobrý den,
potvrzuji, že Váš pokus z browseru prošel jak uvádíte. Nicméně s implementací v dotnetu Vám nepomůžeme, podporu máme pouze pro php a javu.

**Comment by TikyConte** [comment]
A ten co neprechadza nemate nejake blizsie info k nemu?

Dňa 6. 10. 2016 15:51 používateľ "Vítězslav Zich" <notifications@github.com>
napísal:

**Comment by vzich** [comment]
Evidujeme ze včera v aplikačním logu dva úspěšné requesty, které vám vrátili stav platby (15:21 a 15:36). A 5.10. jste na requesty paymentStatus obdržel 404, jak jste již uváděl.

**Comment by TikyConte** [comment]
Ako som pisal dotnet tu linku sam menil.
Toto je riesenie:
Private Sub ForceCanonicalPathAndQuery(uri As Uri)
        Dim paq As String = uri.PathAndQuery
        ' need to access PathAndQuery
        Dim flagsFieldInfo As FieldInfo = GetType(Uri).GetField("m_Flags", BindingFlags.Instance Or BindingFlags.NonPublic)
        Dim flags As ULong = CULng(flagsFieldInfo.GetValue(uri))
        flags = flags And Not CULng(&H30)
        ' Flags.PathNotCanonical|Flags.QueryNotCanonical
        flagsFieldInfo.SetValue(uri, flags)
    End Sub

Najdene tu s popisom:
http://stackoverflow.com/questions/781205/getting-a-url-with-an-url-encoded-slash
