### ISSUE TITLE
Payment gate error [woocommerce]

### ISSUE THREAD

**Issue by olejan25** [csob/paymentgateway#231]
Good day!

I'm using wordpress and woocommerce eshop with you payment gate plugin. I install plugin, check if it work on test public key and changed it to production. But after checkout i have this error "Přesměrování na platební bránu se nezdařilo". What i doing wrong? maybe my account isnt activated yet? Thanks for help. I have an merchant id and merchant private key.

**Comment by ratajskym** [comment]
Hello, without your merchant id we can not presage what is going on

**Comment by olejan25** [comment]
Thanks for reply,
my id - M1MIPS0694

**Comment by vzich** [comment]
Hi,
actually you are blocked on production environment. Before switching to production, you have to pass tests in integration (test) environment and confirm the validation in POSmerchant system. You can find more info about tests on our wiki website- [link](https://github.com/csob/paymentgateway/wiki/How-to-Switch-to-the-Live-Environment).
Best regards,
VZ

**Comment by olejan25** [comment]
I made all tests except "Payment reversal". But where i can get login and pass for POSmerchant system

**Comment by vzich** [comment]
Login should be your company identification number and you should've received your password via SMS after you've signed contract with bank (phone number should be mentioned there). By the way if you won't be using reversals in your eshop but in POSmerchant system, you can write mail to akceptacekaret@csob.cz that you want to switch to production environment.

**Comment by olejan25** [comment]
Yes, problem was solved, big thanks for your help.
