### ISSUE TITLE
Nekonzistence mezi dokumentací a reálném chování ohledně `paymentStatus`

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#232]
Dobrý den,

ohledně `paymentStatus` v responsu se v dokumentaci píše: `Vyplněno v případě, že resultCode je 0`. Stejnou informaci jsem dostal od @vzich v tomto vlákně https://github.com/csob/paymentgateway/issues/196
Přesto `paymentStatus` dostávám minimálně i při resultCode 150. Můžete prosím uvést do dokumentace detailnější informace o přítomnosti `paymentStatusu`? Po pravdě s aktuálním chováním při `150` jsem spokojený, nemusím dělat další request, abych se dozvěděl aktuální status. Jenom mě trochu děsí, že tato vlastnost je v rozporu s dokumentací :)

**Comment by joskera** [comment]
Dobrý den, 

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by dmarek** [comment]
V dokumentaci to upresnime, paymentStatus je vyplnen "vzdy kdyz je to mozne", v pripade resultCode 0 je vyplnen vzdy, dale je vyplnen u nekterych chybovych kodu a je to dodatecna informace (vyplnuje se vzdy, kdyz je napr. trx mozne dohledat a ma smysl jej plnit)

**Comment by pepakriz** [comment]
@ratajskym S odpovědí od @dmarek jsem spokojený, ale dokumentace stále tvrdí něco jiného.
