### ISSUE TITLE
Error logy

### ISSUE THREAD

**Issue by BroliCzech** [csob/paymentgateway#233]
Dobrý den,
převáděl jsem stávající bránu z paymuzo. Postupoval jsem podle návodu, v testovacím prostředí transakce proběhne, ale po přepnutí na produkční data skončím s hláškou:

> Platba nemůže být provedena
Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.

Potřeboval bych vědět, kde je problém. Jsou někde dostupné nějaké logy, z kterých bych se dozvěděl něco specifičtějšího? Jako veřejný klíč brány používám "mips_platebnibrana.csob.cz.pub". Je to tak správně?

**Comment by ratajskym** [comment]
Dobrý den, potřebujeme znát minimálně Vaše merchant id

**Comment by BroliCzech** [comment]
M1E3CB3304

**Comment by vzich** [comment]
Dobrý den, 
21.10. jste si generoval produkční klíče, ale nepotvrdil jste jednorázovým kódem odeslání veřejného klíče do banky v Posmerchantu. Jednorázový kód byl zaslán na mail technické podpory vaší platební brány.

**Comment by BroliCzech** [comment]
Klíč jsme potvrdili, ale stav je stejný

**Comment by BroliCzech** [comment]
Beru zpět, teď mi transakce prošla, takže to vypadá nadějně. Děkuji.

**Comment by mrazekl** [comment]
Dobrý den,

Ano máte pravdu, v 18:23 vidím v logu úspěšnou transakci na 1,-Kč.

**Comment by BroliCzech** [comment]
1 Kč? Mělo by to být 1 EUR

**Comment by mrazekl** [comment]
Máte samozřejmě pravdu, transakce byla na 1 Euro, nikoliv Koruny, omlouvám se za zmatek.
