### ISSUE TITLE
Account Funds + platba kartou

### ISSUE THREAD

**Issue by JakubSchejbal** [csob/paymentgateway#234]
Dobrý den,

prosím o pomoc s problémem. Na webu www.laser-books.cz využíváme plugin Account Funds ( https://woocommerce.com/products/account-funds/ ), který umožňuje zaplatit buď plně nebo částečně objednávku zakoupeným kreditem.

Problém máme právě s částečným hrazením a doplacením kartou pomocí csob/paymentgateway.

Příklad: Zákazník si objedná knihu za cenu 179 Kč, využije kreditu 100 Kč cena se mu poníží tedy o 100 Kč na 79 Kč. (Připočte se částka se zvoleným poštovným.) Ale po přechodu na platební bránu se zobrazí k úhradě částka plná, jako by nevyužil kreditu.

![image](https://cloud.githubusercontent.com/assets/22091966/19961535/7095e1e4-a1b3-11e6-9f11-d3cf1b0d557b.png)

![image](https://cloud.githubusercontent.com/assets/22091966/19961555/8f47bd7e-a1b3-11e6-8b5d-9ad9a2764ff7.png)

Je možné toto prověřit, případně existuje nějaký hotfix nebo řešení?

Díky moc za podporu a pomoc.

Jakub Schejbal

**Comment by JakubSchejbal** [comment]
Takto to vypadá v pokladně ( http://www.laser-books.cz/pokladna/ ):

![image](https://cloud.githubusercontent.com/assets/22091966/19961814/f8255e90-a1b4-11e6-96fc-c77e59025f69.png)

**Comment by mrazekl** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by ratajskym** [comment]
Dobrý den, 

vypadá to, že se plugin nedozví o tom, že byla sleva aplikována. Na platební bráně se zobrazí to, co mu pošle eshop (tedy plugin). Vámi popisované spojení dvou pluginů jsem nezkoušel. Ve volné chvíli to vyzkouším.

**Comment by JakubSchejbal** [comment]
@ratajskym Díky moc, vypadá to tak, jak říkáte. Přitom než dojde k samotné platbě tak i výsledná částka je ponížena o ten "kredit" v náhledu. Cena celkem tomu odpovídá, ale platební brána si to vezme, jako by tam kredit vůbec nebyl. Každopádně ještě jednou díky za ochotu.

**Comment by JakubSchejbal** [comment]
V nejnovější verzi pluginu OK, opraveno.
