### ISSUE TITLE
Platba nenalezena

### ISSUE THREAD

**Issue by RadZah** [csob/paymentgateway#235]
Dobrý den,

testuji nastavení opakování platby po návratu do eshopu po neúspěšném pokusu o zaplacení.
Z eshopu následně vytvořím nový požadavek na bránu, tentokrát zadám správné údaje a validní kartu. Celý proces proběhne v pořádku, kolečko se dotočí,  a pak se objeví hláška v červeném okně - "Platba nenalezena ... ". Z tohoto stavu se nelze dostat jinak. nežli navigací zpět v browseru.  A teď to nejzajímavější - po kliknutí zpět se najednou objeví hláška v zeleném okně, že platba byla provedena. Nedojde k žádnému přesměrování na eshop, ani není tlačítko pro návrat není. Prostě je platba najednou provedena, a konec. Opravdu nerozumím, co se děje. 

Jedná se o Merchant ID M1MIPS0988. 

Můžete prosím zkontrolovat např. poslední platbu.

Děkuji.

**Comment by mjanek** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by vzich** [comment]
Dobrý den,
prověřil jsem Váš request ze dne 12.11 v 00:16 a zasíláte v payment/initu nevalidní url adresu a proto jste nebyl přesměrován zpět na eshop. Posíláte ji jako relativní, nicméně by url adresa měla být absolutní.

**Comment by RadZah** [comment]
Dobrý den, 
skutečně jsem posílal v druhém případě chybnou url. 
Děkuji.
