### ISSUE TITLE
Vaše platba byla zamítnuta z důvodu blokace karty

### ISSUE THREAD

**Issue by davidkalla** [csob/paymentgateway#236]
Dobrý den,

implementuji platební bránu na kino-5d.cz.server.atlanticstudio.cz a při platbě kartou se mi vrací chyba "Vaše platba byla zamítnuta z důvodu blokace karty..."

Dle mého je vše nastaveno správně. Můžete mi prosím poradit, kde je problém?

S pozdravem

David Kalla

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek jsme zaznamenali. O dalším postupu Vás bude informovat odpovědný kolega.

s pozdravem

Spisar

**Comment by Mspisar** [comment]
Dobrý den, pane kallo,

Ujistěte se prosím, že používáte správné testovací karty.

dle odkazu:
https://github.com/csob/paymentgateway/wiki/Testovac%C3%AD-karty

s pozdravem

Spisar

**Comment by davidkalla** [comment]
Děkuji, to bude ono :)

S pozdravem

David Kalla
