### ISSUE TITLE
Reverzal

### ISSUE THREAD

**Issue by hawkey** [csob/paymentgateway#237]
Zdravím

Je možné přejít z integračního do produkčního prostředí bez provedení reverzované platby? V minulosti jsem instaloval nové brány s použitím API pro GPwebpay, dnes když to zkouším, tak udělám úspěšnou, zrušenou i zamítnutou objednávku, ale reverzní přes to původní API nedokážu.

**Comment by mrazekl** [comment]
Dobrý večer,

pokud nebudete v produkčním prostředí funkci reverzování využívat, pošlete žádost o aktivaci na akceptacekaret@csob.cz, kde uveďte podrobnosti. Jinak můžete platbu reverzovat z prostředí PosMerchant.

**Comment by hawkey** [comment]
O reverzování přes PosMerchants jsem se právě snažil a nenašel jsem. Poradíte mi kde?

**Comment by hawkey** [comment]
Tak už nic, hodinu jsem zkoumal a nenapadlo mne kliknout na červený symbol dolaru, až teď mne osvítilo :) Díky moc za pomoc

**Comment by mrazekl** [comment]
Přesně tak, funkci reverzovat provedete pomocí ikony dolaru v záložce transakce > platební brány.
