### ISSUE TITLE
payment/init failed, http response: 400

### ISSUE THREAD

**Issue by antsoft1967** [csob/paymentgateway#238]
I'm testing eAPI with the local hosting. I use examples for PHP. My actions:
1. Generated key at https://platebnibrana.csob.cz/keygen/, received files public and private key. I put them in a folder /key/.
2. In file setup.php changed the values of the variables $merchantId and $privateKey.
3. Launched index-json.php and page init-json-result.php received the result:
"payment/init failed, http response: 400"
What could be the problem? Thank you!

**Comment by mrazekl** [comment]
Hello,

you must generate testing keys at https://iplatebnibrana.csob.cz/keygen.
Will be nice to know your Merchant ID for the next time.

**Comment by antsoft1967** [comment]
Hello,
My Merchant ID: M1MIPS1043.
Thank you! I re-generated keys, all perfectly working.
