### ISSUE TITLE
Extensions se musí nechat zapnout

### ISSUE THREAD

**Issue by simPod** [csob/paymentgateway#239]
Ve wiki chybí info o tom, že je třeba si zažádat o zaktivování extensions. Strávil jsem pár hodin zkoumáním, proč tam extensions nemám a pár dní čekání na reakci supportu

**Comment by vzich** [comment]
Dobrý den,
děkujeme za připomínku, dokumentaci jsme upravili.
S pozdravem
VZ

**Comment by ratajskym** [comment]
Dobrý den @simPod ,

píšete, že jste čekal několik dní na reakci supportu. Chci se zeptat, kam jste Váš dotaz posílal.

Děkuji

**Comment by simPod** [comment]
Dobrý den, platebnibrana@csob.cz nebo tak nejak, tam jsem se za cca 2 dny dozvedel, ze mam napsat na akceptacekaret@csob.cz. Mohli to tam asi uz predat oni no, na akceptacekaret jsem cekal jen den

**Comment by ratajskym** [comment]
Dobrý den, pro jistotu jsem prověřil jednotlivé kroky viz. níže. To zpoždění jde bohužel vidět.

27.11.2016 21:38 - píšete dotaz na platebnibrana@csob.cz
29.11.2016 10:09 - předáno na support
29.11.2016 10:15 - zaevidováno supportem
29.11.2016 11:54 - odpověď ze supportu
29.11.2016 13:15 - zakládáte Github issue
29.11.2016 13:26 - Issue vyřešeno, dokumentace doplněna

**Comment by simPod** [comment]
se stava, hlavne ze wiki je ok, tak se na tom ostatni nezaseknou :) asi close?

**Comment by ratajskym** [comment]
Souhlas, děkuji za podnět.

**Comment by radehorak** [comment]
Dobrý den,
moc děkujeme za upozornění a budeme se snažit zajistit nápravu.
Radek Horák
