### ISSUE TITLE
Migrace - heslo a klíče

### ISSUE THREAD

**Issue by hawkey** [csob/paymentgateway#24]
Zdravím

Snažím se převést GPwebpay na novou CSOB platební bránu, aniž bych musel programovat nové eAPI a nedaří se mi.

Mám tři dotazy:
- GPwebpay používal soukromý klíč, který jsem si sám zahesloval, tady jsem ale dostal soukromý klíč již vygenerovaný a heslo neznám, znamená to že tam žádné není a můžu volat bez hesla?
openssl_get_privatekey("key.pem", "");

- Na GPwebpay jsem měl veřejné certifikáty typu .pem (obsahovaly -----BEGIN CERTIFICATE-----) ale tady jsou jen soubory typu .pub nebo .cer, se kterými mi to nefunguje a skončí na chybě https://platebnibrana.csob.cz/pay/merchant-error.html

- GPwebpay používal jeden certifikát při odeslání platby a druhý pro validaci (test/prod). Tady je ale jen jeden certifikát (test/prod), mám ho tedy používat pro obojí?

**Comment by ratajskym** [comment]
Dobrý den,

- vygenerovaný privátní klíč je bez hesla, parametr ve funkci tehdy nechte prázdný
- to, že Vám nefunguje platba ještě neznamená, že je problém s klíčem. K tomu, abychom mohli Váš problém více diagnostikovat je potřeba znát merchant id a přibližný čas transakce. Pošlete tyto informace na adresu platebnibrana@csob.cz spolu s informací, jestli jdete proti testovacímu nebo produkčnímu prostředí
- na testovacím prostředí použijte pro ověření zprávy klíč mips_iplatebnibrana.csob.cz.pub, na produkčním prostředí použijte klíč mips_platebnibrana.csob.cz.pub

**Comment by hawkey** [comment]
Zdravím

Díky za reakci, poslal jsem konkrétní údaje na mail.
Ještě k tomu třetímu bodu. Samozřejmě chápu, že je jiný klíč pro testovací a jiný pro produkční.
Psal jsem ale o tom, že na gpwebpay byly odlišné klíče pro odeslání a pro ověření platby, zatímco zde je pouze jeden klíč (ve dvou verzích pro test a prod)

**Comment by ratajskym** [comment]
V krátkosti shrnu co jsme probrali napřímo a co zafungovalo:

Na testovacím ani na produkčním prostředí jste si nevygeneroval klíče.  
Vygenerovaný privátní klíč dejte do skriptu. 
Vygenerovaný veřejný klíč je potřeba přes tlačítko odeslat do banky.

**Comment by hawkey** [comment]
Zdravím

Ano, podařilo se mi již zaplatit testovací kartou, ale ted přicházejí na
řadu ty veřejné klíče, na které jsem se ptal na začátku
Nedaří se mi ověření transakce veřejným klíčem
Když zkouším
https://github.com/csob/paymentgateway/blob/master/eshop-integration/keys/mips_iplatebnibrana.csob.cz.cer

tak se ani nenačte: openssl_verify() [function.openssl-verify
<http://www.kamerove-systemy-cpplus.cz/gpwebpay/function.openssl-verify>]:
supplied key param cannot be coerced into a public key

Když zkouším
https://github.com/csob/paymentgateway/blob/master/eshop-integration/keys/mips_iplatebnibrana.csob.cz.pub
tak se klíč načte, ale objednávka se nevaliduje.

$data = M1E3CB2806|CREATE_ORDER|201566131|0|0
$digest =
SkQt0GmZp0gRM5/39O/8jfMHLBLqbiBDLUu7/OEPiMzpCM/SmUZMJB+SwFBpvZKRz7MpYdkcLYhit3NceKrcdggrTdaL1W7zdLRDz9xx6w96yBmOAwwhY0dYEoa6uBdiE45B/H0sIFpjHFPJW1fWSe/b0rtL8gOJ7apAibcKi4+WgSyQ1Oa+01V/mPy4PylrcnabidNrqWu8A3F3CX8wffil5+9QL4ztLjaZID2qETBUQMwGUTt1BoENiF3UG/3pOi8K3fJhPTP/gwLrcU4FTp85mQ9GT0n2I3WQ5/lOdB5MeXBFYhb23Pp1dnb+uS26eH0gb3ERezOJ1m+7Llcmog==

 $pubkeyid = openssl_get_publickey(načtený integrační klíč .pub);
 $signature = base64_decode($digest);
 $vysledek = openssl_verify($data, $signature, $pubkeyid);

Takhle to fungovalo na gpwebpay. Poradíte mi, co je zde špatně?
Radek Dresler





Dne 30. července 2015 13:46 Martin Ratajský <notifications@github.com>
napsal(a):

**Comment by ratajskym** [comment]
Dívám se do logu a přijde mi, že na testovacím prostředí Vám to funguje. Vidím transakci v potvrzeném stavu. 

Není problém v tomto?
Pro testovací prostředí slouží veřejný klíč brány: mips_iplatebnibrana.csob.cz.pub
Pro produkční prostředí slouží veřejný klíč brány: mips_platebnibrana.csob.cz.pub

**Comment by hawkey** [comment]
Zdravím

Ano, na straně brány všechno proběhne v pořádku a potvrdí se platba.
Ale tato informace by měla být předána zpátky na shop, kde se to má ověřit
přes ten veřejný klíč. A to ověření správně neproběhne.
Mám tam klíč pro integrační prostředí
https://github.com/csob/paymentgateway/blob/master/eshop-integration/keys/mips_iplatebnibrana.csob.cz.pub

Proto jsem se ptal na ty klíče, na GPwebpay byl ten veřejný klíč mnohem
delší, s koncovkou .pem a začínal -----BEGIN CERTIFICATE-----
Pokud vy máte jiný typo, tak se patrně bude muset nějak upravit i to
zpracování validace


Dne 30. července 2015 14:49 Martin Ratajský <notifications@github.com>
napsal(a):

**Comment by ratajskym** [comment]
Pošlete mi prosím do mailu hodnoty, které jste od brány přijal a jak z toho skládáte řetězec pro výpočet podpisu.

**Comment by hawkey** [comment]
Zdravím

Přijal jsem toto (serialized)
a:7:{s:14:"MERCHANTNUMBER";s:10:"M1E3CB2806";s:9:"OPERATION";s:12:"CREATE_ORDER";s:11:"ORDERNUMBER";s:9:"201566132";s:6:"SRCODE";s:1:"0";s:6:"PRCODE";s:1:"0";s:6:"DIGEST";s:344:"aNs7Ydev/wbG5NMvtKKRusQShcMmKo2fPGbULFQZH2CMxqUDQBqNUk/KRn0FaUj0RS3J3TzU3p/5rH1rzQ7ESpQ11pR87S4aL8uedyJWO6268usWPazvWPN9BZn8U6p3WYhG418UuNHxuc2cG8uZelaKJTrJxbJkhqLLFwCrIBu40Lq35dp41djGmi/hEQZRzIoKcg325iYxSdjvfTts3P9m8fPi7GbG7ImFS9hN53ToulHqDdHvxtvHQWb6WbI+kfgX/XG4XcaBrr1e5K6+HgEQ6H7bZtBxi4UhTMm1cqZjagfxOoQMabi9E0DKL/tH7wwJQ/LUQew6p4nlrPmbJg==";s:7:"DIGEST1";s:344:"YZE91Ff2VrsF6Jw0uSvaaa+Je7S3r6aoWo9XjbEshEMEF4TbUBYi+p7XcytkLUQ+opQMTiHfenPWGccjQJZKTt+KUEYPY/rU50rw+t6YjgQ16F7l3u7g1hHmr+Ua/uls4idARLUQXn7+yEAFJ59gkCKDmwDNq60qK6X1hvhU5FVHaqn+/lvFwUS7fYNiWsjQ0+PyA99FoOxx3phNOIJ3k4ODvsU5Q1bdVKcQXiUakCkFw3GqFIlHk/GhbQ/7gzvfPbjUTL1iTRpH6G50E214J8Cft974YnlmBiQJjVphwI5J0AN+qu4DQlLH1GMKEd6TzV73GHew+WKTwvlQfl1bGw==";}

Ze všeho kromě digestů složím řetězec M1E3CB2806|CREATE_ORDER|201566132|0|0
do $data
a nechám verifovat s digestem
aNs7Ydev/wbG5NMvtKKRusQShcMmKo2fPGbULFQZH2CMxqUDQBqNUk/KRn0FaUj0RS3J3TzU3p/5rH1rzQ7ESpQ11pR87S4aL8uedyJWO6268usWPazvWPN9BZn8U6p3WYhG418UuNHxuc2cG8uZelaKJTrJxbJkhqLLFwCrIBu40Lq35dp41djGmi/hEQZRzIoKcg325iYxSdjvfTts3P9m8fPi7GbG7ImFS9hN53ToulHqDdHvxtvHQWb6WbI+kfgX/XG4XcaBrr1e5K6+HgEQ6H7bZtBxi4UhTMm1cqZjagfxOoQMabi9E0DKL/tH7wwJQ/LUQew6p4nlrPmbJg==

který je v proměnné $signature

  $pubkeyid = openssl_get_publickey($this->verejny);
  $signature = base64_decode($signature);
  $vysledek = openssl_verify($data, $signature, $pubkeyid);
  openssl_free_key($pubkeyid);

$this->verejny je načtený klíč
https://www.kamerove-systemy-cpplus.cz/gpwebpay/data/cert.pub

Pak je tam ještě jedno verify s DIGEST1, ale k tomu se ani nedostanu

Dne 30. července 2015 16:31 Martin Ratajský <notifications@github.com>
napsal(a):

**Comment by ratajskym** [comment]
Brána vracela i merchant id, tento parametr ovšem do podpisu nevstupuje. Upravili jsme aplikaci tak, aby merchant id nevracela.

**Comment by PeterBMP** [comment]
Dobrý deň,

mám podobný problém s overením DIGEST po spracovaní platby.  Pre vytvorenie reťazca použijem hodnoty v poradí ako sú poslané:
OPERATION|ORDERNUMBER|SRCODE|PRCODE|MERORDERNUM 
napr.  CREATE_ORDER|1397690652|0|0|0000146084

Pre overenie používam verejný kľúč https://github.com/csob/paymentgateway/blob/master/eshop-integration/keys/mips_platebnibrana.csob.cz.pub

V čom robím chybu?

**Comment by ratajskym** [comment]
Zkoušíte to na testovacím nebo na produkčním prostředí? Neznám Vaše merchant id, takže je opravdu těžko říct, kde je něco špatně.

**Comment by hawkey** [comment]
Zdravím

Jak jsem se dostal já do tohohle tasku?

Radek Dresler

Dne 17. srpna 2015 14:53 Martin Ratajský <notifications@github.com>
napsal(a):

**Comment by PeterBMP** [comment]
Na produkčnom prostredí, Merchant ID nebudem tu zverejňovať, keďže sa používa na overenie DIGEST1. Písal som aj na platebnibrana@csob.cz, ak mi odpíšte pošlem Merchant ID.
