### ISSUE TITLE
Jak udělat oneclick payment na button a dát customerovi info o stavu

### ISSUE THREAD

**Issue by simPod** [csob/paymentgateway#240]
Zkouším oneclick payment na button. Po kliku na button se zavola `payment/oneclick/init` a `payment/oneclick/start`. Pak se hned volá `payment/status`, ale platba je ve stavu `pending (2)`. Trvá cca 1-2s, než spadne do stavu `confirmed (4)`. Chtěl bych ale po kliku na button vypsat, jestli byla platba úspěšná nebo ne. Jak tohle logicky řešit? Nechce se mi serveru říkat, aby čekal 2s, než zkontroluje status platby, ani dělat nějakou rekurzi, která bude pálit payment/status tak dlouho, dokud nedostanu odpověď. Už jste se s tím setkali?

To samé pak při nějakém automatickém placení, kdy na pozadí spouštím větší dávku oneclick plateb. Dávat tam nějaký wait je docela overkill, co slušně prodlouží běh scriptu. Se starou metodou `payment/recurrent` tento problém nebyl.

Díky

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod: TSGSMIPS-2524 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem

**Comment by dmarek** [comment]
Autorizace platby může obecně trvat až několik vteřin (zjednodušeně řečeno, nezávisí to jen na platební bráně ale i na bance, ve které má zákazník účet a kerá mu vydala platební kartu). 

Proto jsou ať už normální platby na bráně (za přítomnosti zákazníka) anebo oneclick platby (prováděné pomocí volání "zadem" mezi serverem e-shopu a platební bránou) navržené jako asynchronní zpracování. Spustí se autorizace platby a pak buď zákazník čeká na dokončení (na bráně se zobrazuje "provádí se autorizace ...") anebo se provádí zpracování oneclick platby a je na serveru eshopu, aby si zjišťoval status platby. E-shop by měl (podobně jako to provádí platební brána) zobrazovat zákazníkovi informaci o tom, že se provádí autorizace platby do té doby, než zjistí výsledek (autorizace má nastaven max limit na 30 sec).

Dřívejší `payment/recurrent` byl z tohoto pohledu navržen synchronně, nevýhodou bylo, že volání bylo blokující a z tohoto pohledu neoptimální.

**Comment by simPod** [comment]
děkuji, rozumím. btw, kolikrát za jaký čas mohu poslat dotaz na status platby, než dostanu nějaký soft ban? :)

**Comment by dmarek** [comment]
payment/status můžete volat kdykoliv, není to nijak časově omezeno. Pro oneclick autorizace doporučujeme cca po 2-3 vteřinách po startu autorizace, pokud není znám výsledek tak zkoušet např. po  10 sec.

**Comment by simPod** [comment]
kk, děkuji
