### ISSUE TITLE
Produkce / Testovací

### ISSUE THREAD

**Issue by represent-cz** [csob/paymentgateway#241]
Dobrý den,
vzhledem k tomu, že už jsem v produkční verzi platební brány ale chtěl bych si ji nějak dále rozvíjet a pracovat s ní. Můžu se znovu přepnout do "vývojového" / testovacího prostředí a pak zase bez problému zpátky ??

Děkuji
Marek

**Comment by ratajskym** [comment]
Dobrý den, 

obě prostředí jsou na sobě nezávislé. Můžete používat produkční prostředí a mezitím vyvíjet nové fičury na integraci.

**Comment by represent-cz** [comment]
Super. Máte zájem o to, abych vám pushoval něco sem do repozitáře ? Upřímně integrace pro Wordpress je dost bídná.

**Comment by ratajskym** [comment]
Pull request můžete poslat kdykoliv, takže směle do toho
