### ISSUE TITLE
Reset jednorázového kódu

### ISSUE THREAD

**Issue by ondrejvymetalik** [csob/paymentgateway#242]
Dobrý den,

jsem takměř u dokončení procesu implementace na Woocommerce, ale potřebuji potvrdit public key a k tomu potřebuji jednorázové heslo, které ale nemáme. Je možného ho něják vyresetovat?
Děkuji

<img width="312" alt="screen shot 2016-12-01 at 14 14 20" src="https://cloud.githubusercontent.com/assets/20541229/20796920/87291f74-b7d0-11e6-8b0c-c7c61070329b.png">

**Comment by aKocian** [comment]
Dobrý den,

Jednorázové heslo obdržíte na mail technické podpory.
Pokud heslo nenaleznete, můžete ho vyresetovat znovu zaslánim public key do banky.

**Comment by ondrejvymetalik** [comment]
Myslíte tento email co je zapsaný v detailu brány?? Tak tam bohužel nedorazilo.

Zkusím teda znovu zaslat public key do banky.

<img width="358" alt="screen shot 2016-12-01 at 14 33 48" src="https://cloud.githubusercontent.com/assets/20541229/20797568/3e84c2c0-b7d3-11e6-9aa2-b457e75c3952.png">

**Comment by ondrejvymetalik** [comment]
Tak jsem to udělal znovu a ted by mi na email měl přijít ten kod? Zatím teda nic nepřichází.

<img width="837" alt="screen shot 2016-12-01 at 14 36 27" src="https://cloud.githubusercontent.com/assets/20541229/20797638/9a53072e-b7d3-11e6-87db-081787749b5e.png">

**Comment by aKocian** [comment]
Pokud vám stále nic nepřišlo, můžu Vám potvrdiť zavedení public key.

**Comment by ondrejvymetalik** [comment]
Dobrý den, ne nic nepřišlo. Prosím o potvrzení. Děkuji

**Comment by aKocian** [comment]
Klíč byl zaveden.

**Comment by ondrejvymetalik** [comment]
Děkuji!
