### ISSUE TITLE
Platba faktur kartou - zákazník sám zadává částku

### ISSUE THREAD

**Issue by ondrejvymetalik** [csob/paymentgateway#243]
Dobrý den,

od kolegy mi bylo řečeno, že brána by měla umět i platby zálohových faktur, kdy zákazník sám navolí částku a zaplatí ti kartou.

Je to možné?

Děkuji

**Comment by joskera** [comment]
Dobrý den,
tohle je spíše otázka na programátora Vašeho eshopu. Pro založení platby je nezbytné aby byla vyplněna částka v metodě payment/init, jakým způsobem je zde částka vyplněna záleží čistě na Vás.

S pozdravem,
Jiří Oškera
