### ISSUE TITLE
Testovací platební brána v1.7

### ISSUE THREAD

**Issue by rstefeksluno** [csob/paymentgateway#244]
Dobrý den,
na adrese: https://iapi.iplatebnibrana.csob.cz/ nám veškeré požadavky, i ty přímo zkopírované z dokumentace k implementaci, házejí chybu 400 Bad Request. 
Je tam nějaký problém, nebo je opravdu s requesty něco špatně. Zkoušeli jsme různé varianty, s vyplněním polí i bez. Pokud zadáme požadavek úplně špatně, tak vrací služba správně chybu Internal Error 900.

**Comment by rstefeksluno** [comment]
Příklad z volání přesně dle dokumentace:
$ curl -v –X POST https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/init \
>   -H "Content-Type:application/json" \
>   -d '{
>     "merchantId":"012345",
>     "orderNo":"5547",
>     "dttm":"20140425131559",
>     "payOperation":"payment",
>     "payMethod":"card",
>     "totalAmount":1789600,
>     "currency":"CZK",
>     "closePayment": true,
>     "returnUrl":"https://vasobchod.cz/gateway-return",
>     "returnMethod":"POST",
> "cart":[ {
>         "name": "Nákup: vasobchod.cz",
>         "quantity": 1,
>         "amount": 1789600,
>         "description":"Lenovo ThinkPad Edge E540"
> }, {
> } ],
>     "description":"Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
>     "merchantData":"some-base64-encoded-merchant-data",
>     "language":"CZ",
>     "signature":"base64-encoded-signature-of-payment-request"
> }'
* Rebuilt URL to: –X/
* IDN support not present, can't parse Unicode domains
* Could not resolve host: –X
* Closing connection 0
curl: (6) Could not resolve host: –X
* Rebuilt URL to: POST/
* Could not resolve host: POST
* Closing connection 1
curl: (6) Could not resolve host: POST
*   Trying 193.245.34.231...
* Connected to iapi.iplatebnibrana.csob.cz (193.245.34.231) port 443 (#2)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: iplatebnibrana.csob.cz
* Server certificate: Verizon Public SureServer CA G14-SHA2
* Server certificate: Baltimore CyberTrust Root
> POST /api/v1.7/payment/init HTTP/1.1
> Host: iapi.iplatebnibrana.csob.cz
> User-Agent: curl/7.49.1
> Accept: */*
> Content-Type:application/json
> Content-Length: 679
> 
* upload completely sent off: 679 out of 679 bytes
< HTTP/1.1 400 Bad Request
< Server: nginx
< Date: Tue, 06 Dec 2016 11:45:33 GMT
< Content-Length: 0
< Connection: keep-alive
< Cache-Control: no-cache, no-store, must-revalidate
< Expires: 0
< Pragma: no-cache
< Set-Cookie: BIGipServerasors_iplatebnibrana.csob.cz_6443_pool=v5Z8cPE8L4gUvEP2cApHA3ipB5UJ52HeHq7EB1jtxZ/Gtsm9gp6mpGp7wHOEJYC51AEmIoDWEvj1NoEAAAAB; path=/; Httponly; Secure
< 
* Connection #2 to host iapi.iplatebnibrana.csob.cz left intact

**Comment by ratajskym** [comment]
Dobrý den, jak jste přišel na verzi 1.7 ? Zároveň obchodník 012345 taky není správně, musíte mít vygenerované vlastní merchant id.

Aktuální verze je 1.6

**Comment by rstefeksluno** [comment]
Dobrý den,
verzi 1.7 implementujeme pro zákazníka, který chce MasterPass platbu (dostupnou podle nám dodaných informací od v1.7 - máme k ní k dispozici dokumentaci).
Pokud budu mít špatné MerchantID, spadne to na 400 BadRequest?

**Comment by ratajskym** [comment]
Merchantid musíte mít spárované se správně vygenerovanými klíči. Err 400 je špatný podpis.

**Comment by rstefeksluno** [comment]
Posílám reálný požadavek, který je udělaný pomocí klíčů / merchant na Legacy API:

{ "merchantId": "A1117jhVmX", "orderNo": 91743, "dttm": "20161206125910", "payOperation": "payment", "payMethod": "card", "totalAmount": 232100, "currency": "CZK", "closePayment": true, "returnUrl": "http://makro-katalog.u-sluno.eu/cs/order/csobeapi/91743/", "returnMethod": "POST", "description": "VS-2016127", "language": "CZ", "signature": "wXufAPdMWUuCD+MX0/lGEdA9ewFe5FFwjooKan0O19qwzAEC1q/eCGpNVIy39TTKsIsVvASt3uDxXLTuF9pQZNCGm48FiwJAX7SBWQch5wTbXn1Sc+azltzJyE9meEI9S/m19KslWwJCN4eBlydsZ56HN8RJ6OQABYbPqpzU+mf6PQljRInZYjEnYdg57Jr929bHjHvSiP7iSVuWwbbcWN1/TlhPbexxPxsnWUENm2wXj5E+ax9qUYGpSIHZwul/w/D3idw7Jnw0HUJGb2VM6CZxGf599rCWJhwt/HYav92xtckLBfs8BIY1BZprqT0O/iA79t7uDbv4bfW53jl7DQ==" }

Liší se certifikáty pro Legacy a eAPI?

**Comment by ratajskym** [comment]
Ne, neliší. Pod vaším merchant id si vygenerujete požadované klíče a jestli následně používate Legacy nebo eAPI je platební bráně jedno.

**Comment by rstefeksluno** [comment]
Tím pádem to co jsem poslal jsou data reálně podepsaná funkčními test certifikáty. Opravdu je signatura na základě těchto dat špatně?

**Comment by ratajskym** [comment]
Doporučuji začít jednoduchou metodou echo, která je triviální na implementaci a zároveň si jednoduše otestujete, že máte klíče v pořádku.

**Comment by rstefeksluno** [comment]
Dobrý den,
v dokumentaci se trochu protiřečí v rámci tvorby textu pro signature string. Pro náš požadavek má být:
A1117jhVmX|91743|20161206131749|payment|card|232100|CZK|true|http://makro-katalog.u-sluno.eu/cs/order/csobeapi/91743/|POST

???

V dokumentaci tam není ani description ani language.

**Comment by ratajskym** [comment]
Začněte metodou echo. Následně budeme řešit tu složitější část.

**Comment by rstefeksluno** [comment]
Tak echo je funkční, vrací na požadavek:
{ "merchantId": "A1117jhVmX", "dttm": "20161206133120", "signature": "E2Ac8nPD+BLtLh1zXKSJfuk7t36E0vjM/Y8UuP3xg8kTHTFpPfdaAcpNEwDORgfQM5tDQrtlDUuDLNLaNbp/WfyDEz11jc3jOnQ0A5zQjLdWvfhIeG+4bPLWmCk03ZCoDVQGXJZ3MtsBUmV08cOfdQfupKotVAVTrWsTntvKYi7eBhy1p/zdUcR6Pkm1bMhypLDfx5LoQLEBZrT++JWtY0ReOF1xjwAhmny5sxBVfPymP0zxYcD6KNV8ajyqcIT8+bjOjD22kLzW5PPtXsNUelIsf0pbC/jvSxQwpAvrdW28ZtvTm9z9UuF8csTDIIFCVGZe7Gc1fTpRxHSgQ3A69g==" }

Výstup:
object(stdClass)#29 (4) {
  ["dttm"]=>
  string(14) "20161206133145"
  ["signature"]=>
  string(344) "eCVMxtkRymTngdWD4UNuUOvDYruqfAO9BJN3tWqlCrnoCivANp0D29A5wm1KfGGBG2aOf8Bsa5Rf4yKmc5wvRUa4DOjgHOIDD36wQEw18D1iFOSTG75gpOf1ar/hx30/90vEJy2W7NR0+hRcYqIGgKr4+XpsDn2PG++WTqj2vGWCreuqMlb5YQIYr0sB0igVjwG2/8MEo4dMNrwAqwZQ9SiO7tQgjkNmIIgV2GTzbhOjdRce0Lx/8T2rim8a8OC81/hJ5cWdiIeQbih40BlC2sdRewguv5fZ22NAWTTX+SiZFgQOO93O0A/PQuga95jbHrRE/ZYO1M76G3Aq5RpuCg=="
  ["resultCode"]=>
  int(0)
  ["resultMessage"]=>
  string(2) "OK"
}

Pravděpodobně je tedy problém jen v tom, která pole a jak mají být součástí signature.

**Comment by ratajskym** [comment]
Bezva, klíče máte tedy v pořádku. Nyní se můžete podívat jak správně sestavit podpis
https://github.com/csob/paymentgateway/wiki/eAPI-1.6

Sekce - Příklad sestavení podpisu pro požadavek posílaný pomocí metody POST

**Comment by rstefeksluno** [comment]
Děkuji, podle dokumentace k 1.6 se mi nakonec podařilo správně sestavit signature. Moc jsme mi pomohl.

**Comment by ratajskym** [comment]
Dokumentace k verzi 1.7 vychází z verze 1.6. V čem byl tedy problém, že se to podle 1.7 nepodařilo ?

**Comment by rstefeksluno** [comment]
Dokumentaci jsme dostali vyexportovanou v PDF a chyběl tam celý ukázkový RETEZEC_ZPRAVY
Podle té online pro 1.6 už bylo jasno, díky.
