### ISSUE TITLE
PayID je case sensitive nebo insensitive

### ISSUE THREAD

**Issue by arxeiss** [csob/paymentgateway#245]
Dobrý den,

chtěl bych se zeptat, zda-li je PayID case sensitive nebo insensitive. Neboli jestli `5ab4` je to stejné jako `5AB4`.

Při vyhledávání objednávky v mé DB pomocí PayID totiž MySQL hledá jako case insensitive. Zajímalo by mě, jestli je možné že poté nalezne 2 objednávky, právě kvůli jedinému rozdílu ve velikosti malých/velkých písmen. V dokumentaci to specifikováno není, a PayID obsahuje velké i malé písmena nyní tak si nejsem jist.

Děkuji

**Comment by mjanek** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by dmarek** [comment]
`payId` je case sensitive.

**Comment by dmarek** [comment]
muzeme zavrit?

**Comment by arxeiss** [comment]
Ano. děkuji
