### ISSUE TITLE
Problém s diakritikou

### ISSUE THREAD

**Issue by OndreVo** [csob/paymentgateway#246]
Dobrý den,

při implementaci platební brány mi nefunguje diakritika v popisu transakce. Konkrétně když do /payment/init (testovací brána) odešlu následující JSON:

`{
	"merchantId": "MojeMerchantId",
	"orderNo": "70001708",
	"dttm": "20161215122347",
	"payOperation": "payment",
	"payMethod": "card",
	"totalAmount": 62900,
	"currency": "CZK",
	"closePayment": true,
	"returnUrl": "http://www.cockyshop.cz/_system/PayMUZO.aspx",
	"returnMethod": "GET",
	"cart": [{
			"quantity": 1,
			"amount": 62900,
			"name": "Nákup",
			"description": "Nákup"
		}
	],
	"language": "CZ",
	"signature": "MggQyPOeUBmoeaYu67Xl9lFAW+N/ggtxWunlJyIkvjeR1iNzUKPxOu/YKzc9sQlmiJrS+rGkZRIrNIuBJR7eummfNGxRmP2Suh6oN8jbZHYrZRiSlJMYwn1bJ68sfq+B7dAuTPAXSyg+ZwsVrZT/ICbuIYfnCTxQWhL6c8Dt+5onGmKIo0c6Ab/+iw9S7F80y7fDaS1VRF0J3xuWx2hAE796fA940z1jNuugi2i2FiCSEnd60Q1shNyb9iVTiAVRUPR1D7tmOw3wxJxkd4KNrHtxa/dLOFAZneKC4XosbyZTb9DhEJQy2jKTth0rX5sIyXzGGk1KdpHqhYjEmgihLw==",
	"description": "Nákup"
}`

k podpisu je použita následující zpráva:
`MojeMerchantId|70001708|20161215122347|payment|card|62900|CZK|true|http://www.cockyshop.cz/_system/PayMUZO.aspx|GET|Nákup|1|62900|Nákup|Nákup|CZ`

dostanu odpověď:
`{"resultCode":900,"resultMessage":"parsing JSON failed"}`

Když odstraním diakritiku ("Nákup"->"Nakup") tak vše funguje. 

Při podepisování používám UTF8:
`System.Text.Encoding.UTF8.GetBytes(message)`

V čem by prosím mohl být problém?

Děkuji,

Ondřej Vošta

**Comment by mjanek** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by ratajskym** [comment]
Dobrý den, omlouvám se, za prodlení.

Ve Vašem požadavku je problém s diakritikou viz request, se kterým se snaží brána pracovat. I proto se Vám vrací resp code 900 (interní chyba).

Payload: {"merchantId":"M1E3CB0569","orderNo":"70001708","dttm":"20161215122347","payOperation":"payment","payMethod":"card","totalAmount":62900,"currency":"CZK","closePayment":true,"returnUrl":"http://www.cockyshop.cz/_system/PayMUZO.aspx","returnMethod":"GET","cart":[{"quantity":1,"amount":62900,"name":"N�kup","description":"N�kup"}],"language":"CZ","signature":"MggQyPOeUBmoeaYu67Xl9lFAW+N/ggtxWunlJyIkvjeR1iNzUKPxOu/YKzc9sQlmiJrS+rGkZRIrNIuBJR7eummfNGxRmP2Suh6oN8jbZHYrZRiSlJMYwn1bJ68sfq+B7dAuTPAXSyg+ZwsVrZT/ICbuIYfnCTxQWhL6c8Dt+5onGmKIo0c6Ab/+iw9S7F80y7fDaS1VRF0J3xuWx2hAE796fA940z1jNuugi2i2FiCSEnd60Q1shNyb9iVTiAVRUPR1D7tmOw3wxJxkd4KNrHtxa/dLOFAZneKC4XosbyZTb9DhEJQy2jKTth0rX5sIyXzGGk1KdpHqhYjEmgihLw==","description":"N�kup"}
