### ISSUE TITLE
paymentStatus 7 a nemění se

### ISSUE THREAD

**Issue by OndreVo** [csob/paymentgateway#247]
Dobrý den,

při implementaci brány jsem narazil na problém, že při používání platby na klik se platba nedostává do finálního stavu 8, ale zůstává ve stavu 7. Pro placení používám kartu 4125010001000208.

např. platba 4ab4a03d4cf09BL

Děkuji za pomoc,

Ondřej Vošta

**Comment by mrazekl** [comment]
Dobrý den,

Váš dotaz jsme zaregistrovali. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by joskera** [comment]
Dobrý den,
ve stavu 7 jsou transakce již řazeny do fronty a dle nastavení zúčtovacích pravidel banky zpracovávány. Konkrétní doba zaúčtování transakcí v tomto stavu je o půlnoci daného dne kdy byla transakce uskutečněna, tedy nyní je již zmíněná transakce ve stavu "zúčtována".

S pozdravem
Jiří Oškera
