### ISSUE TITLE
Extensions v testovacím prostředí

### ISSUE THREAD

**Issue by OndreVo** [csob/paymentgateway#248]
Dobrý den,

jak je prosím možné aktivovat extensions v testovacím (integračním) prostředí? Konkrétně mi jde o rozšíření maskClnRP. Status volání mi nevrací pole extensions.

Děkuji,

Ondřej Vošta

**Comment by mrazekl** [comment]
Dobrý den,

Váš dotaz jsme zaregistrovali. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by ratajskym** [comment]
Dobrý den,

veškeré nastavení provádí backoffice banky. Pošlete email na akceptacekaret<at>csob.cz žádost spolu s Vaším merchant id.

**Comment by ratajskym** [comment]
@OndreVo Dobrý den, povedlo se Vám nastavit vše potřebné? Můžeme issue uzavřít?
