### ISSUE TITLE
Problém "Platba nemůže být provedena"

### ISSUE THREAD

**Issue by vexladdie** [csob/paymentgateway#249]
Dobrý den,

narazil jsem na problém při integraci vaší brány. 

Nacházím se v integračním prostředí (testovacím). Předvytvoření platby proběhne v pořádku, redirect  proccess se také zdá být v pořádku. Ovšem ihned po přesměrování na bránu vyskočí hláška "Platba nemůže být provedena".

Zkoušel jsem zde vyhledat v issues předchozí problémy uživatelů spojené s touto hláškou, ovšem žádná z rad které jsem našel mi nefunguje.

Mohli by jste se prosím podívat do logů co je kde špatně ? Moc děkuji

ID :
M1MIPS1137

Dominik Douděra

**Comment by vzich** [comment]
Dobrý den, pane Douděro,
založení platby ve vašem pokusu proběhlo v pořádku, nicméně v přechodu na platební bránu pomocí payment/process máte chybu v podpisu. Používáte jako veřejný klíč, klíč banky, který stáhnete na zde na githubu ve složce [keys](https://github.com/csob/paymentgateway/tree/master/keys)?

**Comment by vexladdie** [comment]
Dobrý den,
děkuji za reakci, již se mi povedlo vyřešit. Bylo způsobeno mou chybou v signature linku.
Pěkný zbytek dne
