### ISSUE TITLE
Stáří založené/probíhající platby

### ISSUE THREAD

**Issue by jaygridley** [csob/paymentgateway#25]
Dobrý den, měl bych dotaz, zda na bráně existuje nějaký limit, po kterém by platba ve stavu 1 (založena) nebo 2 (probíhá) byla bránou automaticky označena jako zamítnutá, resp. zrušená.

Jde mi o use-case, kdy uživatel započne platbu, ale z nějakého důvodu ji nedokončí a ani se jí nepokusí zaplatit. Tedy např. zákazník přijde z e-shopu na bránu a vypadne mu proud a proud mu 2 dny nepůjde. Přejde platba v tomto případě třeba po 30 minutách do jednoho z negativních koncových stavů?

Děkuji za informaci.

**Comment by ratajskym** [comment]
Dobrý den, 

timeout je to konfigurační záležitost a v tuto chvíli je to přesně 30 minut.

**Comment by jaygridley** [comment]
Dobrý den,

platí stále tato hodnota? Řeším situaci, kdy na platební bráně byla transakce založena dle brány v 20151217114601. Následně v 20151217121702 brána vrátila pro tuto transakci stav 1 (platba založena), nicméně v tuto dobu již měla být transakce v nějakém z koncových stavů (konkrétně pro tuto transakci zamítnuta)

**Comment by ratajskym** [comment]
Sdělte mi prosím pay id, podívám se na to

**Comment by jaygridley** [comment]
Jedna se o transakci ebcf55573713cAL.

**Comment by jaygridley** [comment]
@ratajskym Dobrý den, připomínám se s tímto issue.

**Comment by dmarek** [comment]
Dobrý den, počítejte s tím, že to může být o nějakou tu minutu delší (expirace transakcí je prováděna davkovou úlohou spouštěnou jednou za 2 minuty), 

v tomto případě, 
11:46:01.880 založení transakce
12:18:00.249 expirace transakce
12:18:03.126 dotaz na stav platby vrací 6, declined
