### ISSUE TITLE
MasterCardMobile

### ISSUE THREAD

**Issue by pavelkja** [csob/paymentgateway#250]
Dobrý den, 
zatím máme platební bránu v testovací verzi a ta nenabízí jako formu platby MasterCardMobile. V nastavení platební brány máme jako platební metodu zaškrtnuté jak karty, tak právě i MasterCardMobile. Je někde na naší straně problém nebo je to například tím, že testovací verze neumí MasterCardMobile?
Děkuji za info.
ID brány: M1MIPS1149
Jan Pavelka

**Comment by vzich** [comment]
Dobrý den, pane Pavelko,

MasterCardMobile je dočasně v testovacím prostředí vypnuta, bude nahrazena novější platební metodou MasterPass.

S pozdravem

VZ

**Comment by pavelkja** [comment]
Děkuji za odpověď. Takže si s tím nemám dělat starosti a v produkci bude MasterPass fungovat? Klientovi totiž práve na MasterPass hodně záleží a vybíral si bránu podle toho :) 
Jde mi o to, jakou informaci mu mám předat. Děkuji

**Comment by vzich** [comment]
V produkčním prostředí je nyní možnost platby přes MCM.

**Comment by pavelkja** [comment]
Předpokládám, že z hlediska uživatele se jedná o podobný princip: vezmu mobil s aplikací a pomocí ní zaplatím, aniž bych musel hledat peněženku s kartou, ne? :-)
Děkuji za odpověď

**Comment by vzich** [comment]
Ano, v obou případech nemusí klient zadávat číslo karty, ale použije mobilní aplikaci.
