### ISSUE TITLE
Unable to load card for payment/oneclick

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#251]
Co prosím znamená resultMessage "Unable to load card for payment/oneclick"? Je to dočasná chyba nebo payId vzorové objednávky už nebude nikdy platné?

```
payId "68ff8bf0b524eCA"
resultCode  900
resultMessage "Unable to load card for payment/oneclick"
paymentStatus => 6
```

**Comment by joskera** [comment]
Dobrý den, 

Váš požadavek byl zaznamenán a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by vzich** [comment]
Dobrý den,
v tomto případě se jedná o chybu. Dané payID už nebude možné použít pro platbu na klik. Doporučuji, aby si klient znovu kartu uložil.

**Comment by janlanger** [comment]
Myslíte že by se tyto chybové hlášky daly zdokumentovat? Teď jsme třeba narazili na code 180 s message "oneclick payment series expired". Znamená to to samé jako "Unable to load card for payment/oneclick"?

**Comment by Mspisar** [comment]
Dobrý den, pane Langere,

Váš požadavek jsme zaznamenali a předali k projednání.

s pozdravem 
Spisar

**Comment by vzich** [comment]
Dobrý den, pane Langere,
tyto chybové hlášky budou doplněny do dokumentace při následujícím releasu verze eAPI. Co se týče zprávy "oneclick payment series expired", tak je v tomto případě karta nepoužitelná pro one click platby z důvodu vyexspirování platnosti.

**Comment by janlanger** [comment]
Díky
