### ISSUE TITLE
Cizoměnové transakce vs EET

### ISSUE THREAD

**Issue by lojza3d** [csob/paymentgateway#252]
Dobrý den,

po pročtení specifikace https://github.com/csob/paymentgateway/wiki/Specifikace-API-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-EET to vypadá, že případné cizoměnové transakce (resp. převodní kurzy) řeší zákazník ve svém systému.

Plánuje ČSOB případné rozšíření tohoto API tak, aby bylo možné zprocesovat např. platbu v EUR, která bude na straně banky převedena do CZK, zaevidována do EET a v návratových hodnotách bude uvedena také výsledná částka v CZK, resp. použitý kurz?

Děkuji za informaci.

**Comment by mjanek** [comment]
Dobrý den,

Váš dotaz jsme zaregistrovali. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by dmarek** [comment]
Dobrý den, tyto změny v plánu nejsou, platební brána nezná přesný kontext (kolik a jaký rozpad nahlásit, případně odhlásit), ten zná pouze obchodník.
