### ISSUE TITLE
Schválení loga

### ISSUE THREAD

**Issue by PremyslBrezovic** [csob/paymentgateway#253]
Dobrý den,
zajímalo by mě na jakém principu funguje schvalování loga. ZKouším už nekolikátý pokus a vždy je logo zamítnuto. Máme moc malé okraje? Už mne nic více nenapadá. Děkuji za pomoc ... 
![logo_sonnentor_3](https://cloud.githubusercontent.com/assets/25477080/22500626/9ac7bc1e-e865-11e6-86c8-df3b2ed8fe4b.png)

**Comment by aKocian** [comment]
Dobrý den,

Můžete mi prosím napsat merchantID nebo IČO.
Podívam se na důvod zamítnutí, případně pošlu požadavek do banky na schválení loga.

S pozdravem
Alexander Kocian

**Comment by PremyslBrezovic** [comment]
Naše Merchant ID je: 46342958.
Díky.

Přemek Březovič

**Comment by aKocian** [comment]
Logo z mého pohledu splňuje veškeré podmínky.
Zasílam požadavek o schválení do banky.

**Comment by PremyslBrezovic** [comment]
OK, děkuji. Dělal jsem vše podle návodu a dle mého logo taky všechny podmínky splňuje ...
