### ISSUE TITLE
Woocommerce plugin + EET

### ISSUE THREAD

**Issue by SumLord** [csob/paymentgateway#254]
Dobrý den,
rád bych se zeptal, zda uvažujete o rozšíření woocommerce pluginu o komunikaci s finanční správou (případně kdy).
Předem děkuji za odpověď

**Comment by aKocian** [comment]
Dobrý den,
 
     
Váš požadavek byl zaevidován pod: TSGSMIPS-2998 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 

S pozdravem

**Comment by vzich** [comment]
Dobrý den,
momentálně o rozšíření pluginu pro Woocommerce o komunikaci s FS neuvažujeme.
S pozdravem
VZ
