### ISSUE TITLE
EET testovaci prostredi

### ISSUE THREAD

**Issue by ZbynekS** [csob/paymentgateway#255]
Dobry den
Chci se zeptat, zda o povoleni extensions EET v testovacim prostredi je treba nejak aktivovat? Vraci mi to popis chyby : Extension eetV3 disabled for A2284tqRIx
V dokumentaci se pise ze transakce muze byt zamitnuta i v pripade nevalidnich parametru EET, nicmene mam pocit ze JSON je v poradku : 

{
	"merchantId": "A2284tqRIx",
	"orderNo": "2016008751",
	"dttm": "20170218191850",
	"payOperation": "payment",
	"payMethod": "card",
	"totalAmount": 28400,
	"currency": "CZK",
	"closePayment": true,
	"returnUrl": "https://www.shop-dodax.cz/kosik/",
	"returnMethod": "POST",
	"cart": [{
		"name": "Nákup na shopu.",
		"quantity": 1,
		"amount": 28400,
		"description": "..."
	}],
	"description": "Nákup na shopu.",
	"merchantData": "2016008751",
	"language": "CZ",
	"signature": "gk2o6uI3vmOcmJQXcI7In3z0aD8ztzj2JAFdFSTiKIGtcyu8v5bRF7j9GuDVPLqhYZ4idAJkVPxRehtbw07ZXSM2lxKnhZmxMTxzGgPbOqR+EK0VrcT9ZcRAJY2QuzcJCVVzRtC3dgl7zeHaXAjj2QCaQ6vWulo9JoZZVrJtIo8Fm0L9rSsJMGgwQovnoesQCDhZtKLPu2ftn2cXqTx+5n4l7EKvQTYrVmq6Gl+3GoAJ4lcWPUZkKhqJQS8y1dFE70b0R/YM112qfhSoNkxteigxhzRFkeYNpmO56B5JVSNDIi1rQC2PZpGY3JvX2K4pi4si2YkCNK4hS5taI8zqmw==",
	"extensions": [{
		"extension": "eetV3",
		"dttm": "20170218191850",
		"data": {
			"premiseId": 2563,
			"cashRegisterId": "E3",
			"totalPrice": 284.00
		},
		"signature": "INDRPk5CfiVkOeunzweRuBS7/LLhE5dqXj494VKwGqlEKBfDF2pl7RqRzrdA5+gjBoz8teEoH9rnNz/ycbPAuT0FC82mK+kKIBd9cuty98plJJJZtIAyB2Q+nVyYN/AQdUlP1HJO1gI0XAFEzpQ4uriB/5OLovTy1qegWaF4IYVeJoE/tnGZBupqEs1jmns+h9SFa9gBgSYt3zDU2I9zArN6BGSFwzIMLJliZAXtCNtx+DdJO4+fo67geYUzgTLiTFzLyUp/K127VwDMh6/l2Fhdj6i3VvLpu2kMKDCaPIvoVTQVV36713i2C2eWLM7QqOZn9J59LXx2SDBtY/EQKg=="
	}]
}

Do podpisu EET posilam : eetV3|20170218191850|2563|E3|284.00

Dekuji za odpoved
ZS

**Comment by joskera** [comment]
Dobrý den,
máte pravdu, EET extension je potřeba nejdříve aktivovat. Předávám tedy tento požadavek na kolegu, který má aktivaci EET v kompetenci.

**Comment by vzich** [comment]
Dobrý den, 
pro aktivaci EET extension je třeba kontaktovat akceptacekaret@csob.cz.

**Comment by ZbynekS** [comment]
Dobry den
Na vyse uvedeny mail jsem napsal. Vcera mi prisel mail z platebnibrana@csob.cz ktery se me ptal na ICo, I kdyz jsem presne nechapal k cemu, tak jsem to poslal a od te doby se nic nedeje. Transakce se nadale zamita a vraci mi to porad : Extension eetV3 disabled for A2284tqRIx

Slo by to trosku popohnat, preci jen uz moc casu neni.
Dekuji
ZS

**Comment by hanuss** [comment]
Integrační prostředí s vygenerovaným Merchant ID dle Vašeho popisu (tj. bez nutnosti uzavření smlouvy s bankou) je bez EET extension. EET extension je přístupné pouze v testovacím režimu / prostředí a to po uzavření smlouvy s bankou. Banka následně přidělí Merchant ID ve tvaru M1MIPSxxxx u kterého následně lze zpřístupnit EET.

**Comment by ZbynekS** [comment]
No ale ja nechci uzavirat smlouvu preci, ja to delam pro jine klienty. A jak jsem pochopil z vedlejsiho vlakna 258 , tak tam se taky povoluje EET pro merchat zacinajici A...
Nebo se pletu?

**Comment by ZbynekS** [comment]
No vidim ze na konci toho vedlejsiho vlakna uz taky pozadujete M...

**Comment by ZbynekS** [comment]
Dobry den
Tak jsem vymenil merchatId. Misto A2284tqRIx, jsem dal M1MIPS0968.
Pri tom testovacim pokud byla platba bez EET tak prosla v poradku, pokud jsem zapnul EET , tak je transakce zamitnuta. 
Pri merchant ID M1MIPS0968, at s EET nebo bez vse konci :  (400) Chybný požadavek.
Je treba jeste nejak aktivovat testovaci prostredi pro ostry merchantId ?
Dekuji za info.
ZS

**Comment by hanuss** [comment]
Dobrý den, 
ano, EET extension je nutné pro každý merchant ID povolit. 
M1MIPS0968 jsme Vám nyní povolili. 
hanuss

**Comment by ZbynekS** [comment]
Dekuji
Funguje
zs
