### ISSUE TITLE
EET extension

### ISSUE THREAD

**Issue by mobilttl** [csob/paymentgateway#257]
Dobrý den,

posílám data včetně rozšíření "eetV3", rozšíření podepisuji stejným klíčem jako samotný požadavek (je to správně? )

brána mi nevrací žádnou chybu, vše se zdá, že je OK, ale zpět mi nevrací žádná data k rozšíření

požadavek:
{ 
"merchantId": "A1029DTmM7", 
"orderNo": "580", 
"dttm": "20170221094834", 
"payOperation": "payment", 
"payMethod": "card", 
"totalAmount": 47500, 
"currency": "CZK", 
"closePayment": "true", 
"returnUrl": "http://beta.koloshop.cz/index.php?volba=objednavka&payment_back=1", 
"returnMethod": "POST", 
"cart": 
[ { 
"name": "Nákup na koloshop.cz", 
"quantity": 1, 
"amount": 39000, 
"description": "a2z ato 160 mm brzdovy kotouc cerve..." 
}, { 
"name": "Poštovné a balné", 
"quantity": 1, 
"amount": 8500, 
"description": "Platba za dopravu a platbu" 
} ], 
"description": "a2z ato 160 mm brzdovy kotouc cerve", 
"merchantData": null, 
"customerId": "1455", 
"language": "CZ", "signature": "BprU46gOBstpjAq10sFsBhGnwkTp0LtpMPrzsu2fd1i3fTPT4HpFJoxlh7OcPr7AatNHXVfi3Mk6fFdkP4sEj33SbXNM8WMfwCH30TfxhtBGhBn6ZStgeFooypTWlxNTHuVKZmvM1n7ULAbaGmNzYc3T+FJQ/BH10k+Ha+NP/BGsay5vGnjucmn0NcFjNw7E/XWmU1pOBgr9WwptNzmf0qiskwEgm/PekWZIzs7+wVlnIzeRziVLTNaXvEC/Q7jUzrTir8VPVmH89PXBR2htxMuayEUZ9+PHbPs1aGlrGJEdoz+iDuEWrp+dBJcDElpcyURFclB0ekOIY1FMqC7yAA==", 
"extensions": 
[ { 
"extension": "eetV3", 
"dttm": "20170221094834", 
"data": 
{ 
"premiseId": 181, 
"cashRegisterId": 
"www.koloshop.cz", 
"totalPrice": "85.00" 
}, 
"verificationMode": true, 
"signature": "X4JD9yDpAetQG7ytoafz9gp0z6tEQmLtCsbcJ3tUj0o6+f8W1PWTicMiW8IY0xfBJZbcb2VL/uXSO3k6cNrHN3WVIsyDJ4q0/kNOpV/BH2DPPgpIxJZ0wKsQff3QEmQeKbeU3/SipiSVWtrP8hIE5onjrVHc+8C8v7FOWgA/f/ftR0mZsiD5P+kXu5eM/CkFWTVIlKezH3pjRtZ5cXQvotjRlSNZXJL1FbyrsZt1i1DlVSyTV0BIsqTODAxkq71aPClS7shA/Qa0VD5yEBxq8gF31N9b+lo3s0GmD5QZtjhFMj8bnDX7RhjtCWEPfihxxHTeygRdICzNcatbaCUV/g==" 
} ] } 

díky

**Comment by ratajskym** [comment]
Dobrý den, 
podpis máte správně, proto se Vám nevrací žádná chyba. Co se týká informací ohledně eet, musíte se na ně  doptávat přes metodu payment/status

**Comment by mobilttl** [comment]
díky! už chápu!!
