### ISSUE TITLE
EET testovací prostředí - TSGBANME-18

### ISSUE THREAD

**Issue by ondrakoupil** [csob/paymentgateway#258]
Dobrý den,

řeším podobný problém jako #255, potřeboval bych aktivovat EET extension a pokud možno i všechny ostatní funkce, které nejsou standardně aktivované na anonymních mechant ID - obě extension z v1.6, oneclick, platby tlačítkem. MerchantID, které používám, je A2282xbiYg, případně si můžu založit jiné. 

Úplně to stačí jen pro integrační prostředí, neplánuji později přejít na produkční, potřebuji to kvůli praktickému otestování správného fungování PHP knihovny https://github.com/ondrakoupil/csob.

Na akceptaceplatebnichkaret@csob.cz jsem psal předevčírem, ale neobdržel jsem zatím žádnou odpověď.

Díky

**Comment by ratajskym** [comment]
Dobrý den Ondřeji, za chvíli Vám to nastavím. Dám vědět.

Mimochodem, správná adresa je akceptacekaret@csob.cz (teda pokud nemají alias)

**Comment by ratajskym** [comment]
Nastavil jsem. Issue nechám zatím otevřené.

**Comment by radovanx** [comment]
Dobrý den, 

Mám stejný požadavek pro aktivaci eet extension - také jsem psal na akceptacekatet. 
Bohužel dva dny bez odpovědi. 
MerchantID : A2273VOP0Y

Potřebujeme doplnit eet do platebního modulu.

Děkuji

**Comment by ratajskym** [comment]
@radovanx Nastavil jsem i pro Vaše anonymní merchant id. Bude trvat max 10min než bude aktivováno. 

Bohužel netuším, proč zůstávají Vaše emaily bez odpovědi. Na zmiňovanou mailovou schránku nemám přístup.

**Comment by radovanx** [comment]
Dobrý den,

Děkuji prosím ale o kontrolu z brány se mi vrací:
payment/init failed, reason: No DIC set for A2273VOP0Y

**Comment by Mspisar** [comment]
Dobrý večer,

a posíláte tuto hodnotu v požadavku?
viz část testovacího požadavku:
 "extension": "eetV3",
      "dttm": "20170125131559",
      "data": {
        "premiseId": 181,
        "cashRegisterId": "00/2535/CN58",
        "totalPrice": 17896.00,
        **"delegatedVatId": "CZ00006947"**
s pozdravem

Milan Spisar

**Comment by dmarek** [comment]
pozor, delegatedVatId je DIČ pověřujícího poplatníka, coz je jina polozka nez DIC (DIC poplatnika doplnuje/zna platebni brana). Proverime nastaveni.

**Comment by ratajskym** [comment]
Při nastavovaní anonymního merchanta jsem zapoměl na hodnotu dič, která se v u reálných obchodníků nastavuje automaticky. Opraveno.

@ondrakoupil @radovanx  Vyzkoušejte prosím

**Comment by ratajskym** [comment]
Pro naše interní potřeby doplním issue TERMAPP-2621

**Comment by radovanx** [comment]
Děkuji, již se mi vrací správná odpověď

**Comment by ondrakoupil** [comment]
Volání funkcí s EET rozšířením mi již funguje. payment/init projde, v payment/status pak mám odpověď z rozšíření. Budu se tomu teď věnovat, kdybych ještě na něco narazil, napíšu.

Ohledně e-mailu - psal jsem na akceptacekaret@csob.cz, jen do issue jsem to napsal špatně... Nevadí, hlavně že se to vyřešilo.

Díky.

**Comment by ETNyx** [comment]
Dobrý den, nechci zbytečně otevírat nové issue mám stejný problém, prosím o aktivaci EET pro účet A2271aJrHF, asi jsem se při komunikaci s akceptacekaret@csob.cz nevyjadřoval přesně a response na email přes 24h,.. zde pan Ratajský komunikuje rychleji a ví o co se jedná. Děkuji

**Comment by MVeselka** [comment]
Dobrý den, máme stejný problém jako kolegové nade mnou. Na akceptacekaret@csob.cz nikdo už několik dní nereaguje. Prosím tedy touto cestou o aktivaci EET rozšíření na testovacím prostředí pro merchant ID: M1E3CB3760

Díky.

**Comment by mjanek** [comment]
Dobrý den, vaše požadavky jsme přijali a pokusíme se urychlit proces.

**Comment by hanuss** [comment]
@MVeselka - M1E3CB3760 aktivováno EET extension.

**Comment by hanuss** [comment]
@ETNyx - prosím o zaslání ID platební brány

**Comment by ETNyx** [comment]
@hanuss ID platební brány myslíte položku položku merchant ID?
Merchant ID: A2271aJrHF

**Comment by hanuss** [comment]
@ETNyx Ano potřebujeme merchant ID, to je ale v jiném tvaru, než píšete - má být buď M1MIPSxxxx, nebo M1E3CBxxx.

**Comment by ETNyx** [comment]
Tohle je Mercahnt id které jsem dostal vygenerované (viz README.md)
```
Klíče pro iBránu (otevřené vývojové prostředí přístupné beze smlouvy) si můžete vygenerovat na https://iplatebnibrana.csob.cz/keygen/
```
funguje na requesty na https://iapi.iplatebnibrana.csob.cz/api/v1.7

jakým způsobem žískám Merchant ID ve formátu který po mně chcete? Mé IČ ve vaší databázi nemáte to si již ověrovali na emailu akceptace,...

**Comment by hanuss** [comment]
Integrační prostředí s vygenerovaným Merchant ID dle Vašeho popisu (tj. bez nutnosti uzavření smlouvy s bankou) je bez EET extension. EET extension je přístupné pouze v testovacím režimu a to po uzavření smlouvy s bankou. Banka následně přidělí Merchant ID ve tvaru M1MIPSxxxx.

**Comment by ETNyx** [comment]
@hanuss Děkuji za Váš čas a trpělivost, kontaktuji klienta aby mi tyto klíče zajistil.

**Comment by radovanx** [comment]
Dobrý den,
Mám dotaz je možné že jste EET pro A2273VOP0Y vypnuli  ?
Děkuji

**Comment by radovanx** [comment]
Dobrý den,
Je možné že jste podporu eet pro A2273VOP0Y zrušili ?
Děkuji za odpověď

**Comment by hanuss** [comment]
Dobrý den, na "A" merchant ID nemohla být EET extension nikdy aktivní.

**Comment by rmar01** [comment]
Dobrý den, sleduji diskuzi a rovněž bych požádal o aktivaci. Přes uváděný e-mail akceptacekaret ani po třech dnech není aktivováno.

Poprosím tedy o aktivaci EET extension pro zákazníka "M1MIPS1125". 
Děkuji

**Comment by radovanx** [comment]
@hanuss a @ratajskym 
A četl jste diskuzi ? Váš kolega @ratajskym napsal:

@radovanx Nastavil jsem i pro Vaše anonymní merchant id. Bude trvat max 10min než bude aktivováno.

**Comment by radovanx** [comment]
@hanuss 
Prosím o aktivaci pro M1MIPS1094 

Email bohužel nekomunikuje

Děkuji

**Comment by hanuss** [comment]
@radovanx Máte pravdu, na žádost banky se změnil přístup k anonymním ID. Toto prostředí je pouze pro seznámení programátora s logikou integrace platební brány, veškeré extensions pak budou (po aktivaci) dostupné pouze po uzavření smlouvy s bankou.

**Comment by hanuss** [comment]
@rmar01 - EET extension aktivováno na M1MIPS1125

**Comment by radovanx** [comment]
Dobrý den,

Děkuji jen že mne ta změna zastihla při testování. Je tedy možné aktivovat pro M1MIPS1094 smlouva by měla být uzavřena

**Comment by hanuss** [comment]
@radovanx Za tu nečekanou změnu se omlouváme, na M1MIPS1094 je aktivováno EET extension, nicméně je potřeba dořešit dodatek ke smlouvě ohledně EET. Budou Vás (zástupce společnosti) kontaktovat kolegové z banky kvůli jeho uzavření.

**Comment by tjj001** [comment]
M1MIPS1125 - děkuji za aktivaci EET,
inicializace platby projde v pořádku. 
Po zadání údajů k platbě na platební bráně se vypíše chyba "Omlouváme se za nepříjemnosti, platbu se z technických důvodů na naší straně nepodařilo zpracovat. Platbu můžete zkusit znovu."
Je možné, že jsem něco zadal špatně, nebo je chyba skutečně na Vaší straně a mám čekat na nápravu?

Děkuji za opověď.

**Comment by campari** [comment]
Prosím o aktivaci EET rozšíření pro integrační prostředí pro merchant ID: M1MIPS1178, napsáno na akceptacekaret@csob.cz. Zatím bez odpovědi.

Děkuji.

**Comment by hanuss** [comment]
Dobrý den, 
pro M1MIPS1178 nemáte bohužel uzavřený dodatek ke smlouvě na EET - předal jsem tuto informaci na Vašeho obchodního zástupce v ČSOB, bude Vás kontaktovat.

**Comment by ratajskym** [comment]
Dobrý den všem,

doplnil jsem informaci do FAQ na [wiki](https://github.com/csob/paymentgateway/wiki/%C4%8Cast%C3%A9-ot%C3%A1zky-k-EET#mohu-si-eet-na-platebn%C3%AD-br%C3%A1n%C4%9B-n%C4%9Bjak-vyzkou%C5%A1et)

**Comment by jirisykora83** [comment]
Dobrý den,
rovněž mám problém s komunikací přes email akceptacekaret@csob.cz.
Prosím o aktivaci EET rozšíření pro integrační prostředí pro merchant ID: M1MIPS1233

**Comment by hanuss** [comment]
@jirisykora83 Dobrý den, EET rozšíření pro M1MIPS1233 bylo povoleno. Bude Vás kontaktovat obchodní zástupce ČSOB k dořešení smlouvy na EET.
