### ISSUE TITLE
payment/status failed, http response: 400

### ISSUE THREAD

**Issue by mobilttl** [csob/paymentgateway#259]
Dobrý den,

již mám funkční verzi v implementačním prostředí a z ničeho nic mi všechny požadavky končí na chybě 400.

Je nějaký momentální problém? jedná se o "merchantId": "A1029DTmM7"

děkuji,

**Comment by ratajskym** [comment]
Máte špatný podpis.
Invalid paymentInit signature for A1029DTmM7,
