### ISSUE TITLE
Migrace platební brány - klíče

### ISSUE THREAD

**Issue by turcovsky** [csob/paymentgateway#26]
Dobrý den,

pokouším se zmigrovat platební bránu pomocí změny parametrů. Nicméně nyní používáme tzv. pfx soubor pomocí něhož podepisujeme požadavek. 
Nyní je uveřejněn veřejný klíč platební brány mips_platebnibrana.csob.cz.pub
Dále dvojice vygenerovaných klíčů rsa_XXXXX.key a rsa_XXXX.pub

Chtěl bych se informovat jak podepsat požadavek v případě implementace na prostředí .NET.
Pro podpis potřebuji certifikát s privátním klíčem mám ale pouze privátní klíč rsa_XXXXX.key.

Děkuji.
Turcovský

**Comment by ratajskym** [comment]
Dobrý den, možná Vám pomůže tohle

//vygenerujete si certifikát
openssl req -x509 -new -key rsa_XXXXX.key -out public.pem 

//vygenerujete si pfx 
openssl pkcs12 -export -in public.pem -inkey rsa_XXXXX.key -out mycert.pfx

**Comment by turcovsky** [comment]
Děkuji to skutečně pomohlo nicméně nyní se pokouším ověřit odpověď pomocí veřejného certifikátu mips_platebnibrana.csob.cz.cer pomocí kterého se mi to nedaří ověřit jelikož .NET technologie vyhazuje chybu, že daný certifikát neobsahuje veřejný klíč. Nevíte jak lze tedy využít soubor *.cer nebo *.pub?

Děkuji.

**Comment by turcovsky** [comment]
již vyřešeno. Prosím uzavřít. děkuji

**Comment by ratajskym** [comment]
Nechcete se podělit o způsobu vyřešení Vašeho problému?

**Comment by turcovsky** [comment]
Vyřešeno viz. http://stackoverflow.com/questions/11506891/how-to-load-the-rsa-public-key-from-file-in-c-sharp

Bylo potřeba také upravit pořadí řetezce na novou podobu:
OPERATION|ORDERNUMBER|MERORDERNUM|PRCODE|SRCODE

kde v původní implementaci byly obsaženy i RESULTTEXT, který se nyní již neposílá.

Dále probíhalo i ověření pomocí DIGEST1, které se nyní již v URL také neposílá tudíž je zapotřebí jej vypnout.
