### ISSUE TITLE
php integrační příklad pro eapi 1.6

### ISSUE THREAD

**Issue by petrpruner** [csob/paymentgateway#261]
Dobrý den,

mohu použít váš [php integrační příklad pro eapi 1.6](https://github.com/csob/paymentgateway/tree/master/Integration%20Examples/eAPI%20v1.6/php) v aplikaci, kde bych rád v budoucnu napojil rozšíření EET? Mate mě, že v [nastavení](https://github.com/csob/paymentgateway/blob/master/Integration%20Examples/eAPI%20v1.6/php/setup.php) se volá endpoint verze 1.5

Díky

**Comment by aKocian** [comment]
Dobrý den,
 
     Váš požadavek byl zaevidován pod: TSGSMIPS-3141 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem

**Comment by ratajskym** [comment]
@petrpruner 

Dobrý den, php plugin v tuto chvíli nepodporuje EET rozšíření. Co se týká enpointu, tak máte pravdu, je to chyba. V url opravíme na správnou verzi API.

**Comment by petrpruner** [comment]
Díky,

můžeme uzavřít
