### ISSUE TITLE
Kontrola stavu objednávky skončí 404 - TSGSMIPS-3142

### ISSUE THREAD

**Issue by jirek** [csob/paymentgateway#262]
Dobrý den,

implementujeme pro eshop metodu pro zjištění stavu platební transakce na platební bráně. Problém máme v tom, že dotaz pro zjištění stavu, končí kódem HTTP 404.
Dotaz na zjištění stavu probíhá v době, kdy je objednávka založená, úspěšně zadané údaje o kartě a zákazník je přesměrován zpět k nám do aplikace (celý proces od založení po dotaz o stav cca do 1 minuty).

Vše zatím testujeme v integračním prostředí.

URL na kterou se dotazujeme:

https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/status/M1MIPS0332/150707ed1a275CB/20170223151126/fQ2EGGEnwo1lWq/v1HVfUDO...

Kdyby bylo třeba, mohu dodat další informace, např. podpis požadavku a zasílané pro založení platby.

Zaplaceno platební kartou 4125010001000208 .

Předem děkuji za odpověď.
Jiří Král

**Comment by aKocian** [comment]
Dobrý den,

Váš požadavek byl zaevidován pod: TSGSMIPS-3142 a předán k řešení.
O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

**Comment by joskera** [comment]
Dobrý den,
v tomto konkrétním příkladu máte chybu v podpisu, podpis nesmí obsahovat lomítka.

**Comment by jirek** [comment]
Mockrát děkuji.
Mohl bych se ještě zeptat na druhý problém? Pokouším se odeslat informace spojené s EET při založení objednávky ( na url'https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/init' ) . Výsledek ale končí chybou HTTP 400. 
Pokud zkusím založit platbu bez EET informací, tak výsledkem jsou správná data.

Ukázka dat:
```python
 "extensions": [{"extension": "eetV3", "dttm": "20170224122350", "data": {"premiseId": 31, "cashRegisterId": "B.O.S.S. Enterprise", "totalPrice": 10988.0}, "signature": `"Gvf+vEQkss+FihUR8cHS8qG6MsTuKInqbWSt/X2YQoR/hgIaxXcGoPeobwjkKLreaBV633q6RD33Rg1RNY0bDXayG+ZGl9sMZp6GyH4IyBPfL9C+xLyZfHRjs5kOvvbU2W4enZZ9uCsejHb9sqG6+GvEg/n3HIeGflyP/wwMEsyPgCpRBj+is8BtzOzmCiTaQDhJfbxejmPBA6EQta21S10f0d+H1qVpPaGZs1Nf+yi6WMajo2MaDG58W5HBTTam3aMVRUtmcWUeOMHc9xn5OicXePbt59tiKozniGg8Mqhjiw5a70jI4uYV0CPeMFTlDkjW6oAo5IRCjVKECN1cTA=="}]
```

Nejsem si jistý cenou, která se do JSONu vkládá, protože v základních datech je bez desetinné tečky, ale v datech pro rozšíření je s tečkou. 
[https://github.com/csob/paymentgateway/wiki/Specifikace-API-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-EET#p%C5%99%C3%ADklad-vol%C3%A1n%C3%AD-paymentinit-s-eet-roz%C5%A1%C3%AD%C5%99en%C3%ADm-na-eapi-v17](url)
`"totalAmount":1789600  vs "totalPrice": 17896.00`

**Comment by hanuss** [comment]
Dobrý den, EET extension je potřeba samostatně povolit, vzhledem k tomu, že dle informace banky máte uzavřený dodatek k EET, aktivovali jsme M1MIPS0332 pro EET.

**Comment by jirek** [comment]
O vyřízení povolení jsme včera požádali správce eshopu.
Zkoušel jsem nyní, ale stále stejný výsledek (HTTP 400).

Přikládám kompletní zasílaná data.

```python
{"merchantId": "M1MIPS0332", "orderNo": 73543, "dttm": "20170224140136", "payOperation": "payment", "payMethod": "card", "totalAmount": 1098800, "currency": "CZK", "closePayment": "true", "returnUrl": "https://test.mp.cz/eshop/cart/pay-by-card/", "returnMethod": "POST", "cart": [{"name": "N\\u00e1kup zbo\\u017e\\u00ed", "quantity": "1", "amount": 1098800, "description": "N\\u00e1kup na www.mp.cz"}, {"name": "Doprava", "quantity": "1", "amount": 0, "description": "Doprava"}], "description": "N\\u00e1kup na www.mp.cz a doprava", "merchantData": "d3d3Lm1wLmN6", "language": "CZ", "signature": "CUYBIo4I81diCvY1P+o1UpE1pYTOyJW0EXg8C9668LP8RcHjGKhcHu99Vhd4HI+mDDxNO4KHsXQKepb02kEVpyEfLWdAQhVH4G2Xb6XKpflTDNTF39HL9YrEQzQr+qEV5cUYuGSsZ9mzQRmFO7y9QRkox2WmTkthno6atRc0d/GNt/GaLsdTvTcbp+3pDUu0R4fl8oBi6J2+vG4XadBOvYcgmC5BKI6r0KLzzYaNQHyYQ5712leAPjaiD8i0EJZhCKB3AY4u5mRSDw8dMw+4VQnVZlIkiTYL9goS88YH1TPkf+joX8fJFDsS5WJnkCUzZWjUkl8zm/YxBeLFVhISBw==", "extensions": [{"extension": "eetV3", "dttm": "20170224140136", "data": {"premiseId": 31, "cashRegisterId": "B.O.S.S. Enterprise", "totalPrice": 10988.0}, "signature": "gqknr0Nl4bM03SHWf+QD4RkyNd+HaqhXBe9D3F1S1g+XRYlhiJSS6KpYMfNywQO8NMqJpS44s+LM6UazC6iilmXevEvXT4bW7pDH6iYj7cop6TIiFPwDTuMy2qkv6WNksGrNK9A6tzPTYOIJnp67Sf2JK2XnbK2EiVVH2n0TMtaujCnm40W/OFGGJbRLnKXiW13B8h2ZoHZSZL9WTN6MfYnig6dMxX95ju/T94TS48N2C+DOwsxrP63FgpgL0h6kQUXbxKo+2A634kujF9/eneZP5/Du/h9XPRuYSXZlZi9YIOhmKW9gIKUNY334aakgbAESivltEPEDBK8hCgWE1A=="}]}'}.
```

**Comment by jirek** [comment]
Omlouvám se, ale mohl bych poprosit o vyjádření. Vzhledem ke spuštění druhé vlny EET a času potřebnému k otestování je pro nás zasílání informací klíčové.
Mockrát děkuji.

**Comment by hanuss** [comment]
Z mého pohledu je EET extension korektně povolené pro M1MIPS0332, certifikát vložený a ID provozovny zadáno. Pokud je problém v sestavení requestu, musím požádat kolegy ze supportu.

**Comment by aKocian** [comment]
Dobrý den,

V logu vidíme hlášku "Invalid paymentInit extension signature for M1MIPS0332"
Můžete nám zaslat data použitá k podpisu?

S pozdravem

**Comment by jirek** [comment]
Pro EET se používají 'eetV3|20170224163243|31|B.O.S.S. Enterprise|6290.0'
a výsledný podpis je Z6TPYHV4JGv+iwJaSiKYTT+m/ii6ZFXZVXWuOdDYmAUFzVnp33RDv8oVNNonDW/hEvOum7Aqz8D0xYbUf89zQfX+vbHB+/PqIEvO0+kUZ1jK1s8U3C87CV6+sJpFvSK/vT5yUvIIlMBJT4L3e61Nc9AKjITtmOojEp5Rzdtz/pypIoQ+7DA0h5G65GfSUtasfAldW5lBe4VCfirxgKTNnWK4yrMVrTZ5UpOZsrrjz3KtKdV6pEPKSljQc25joh/jHsgT0vxHJXTMFxbH8L3azBzy0SBmqxHyFr0i4eS7si/IGYty906ELXU4xa1AC83Al1Vg/GrFjiOGR6nSgQV4DA==

Pro ostaní data je řetězec 'M1MIPS0332|73584|20170224163243|payment|card|629000|CZK|true|http://mp.localhost.com/eshop/cart/pay-by-card/|POST|Nákup zboží|1|629000|Nákup na www.mp.cz|Doprava|1|0|Doprava|Nákup na www.mp.cz a doprava|d3d3Lm1wLmN6|CZ'

bXsfuxqru87gsWSzCpKvGraOM+8g97HJzYEtyS5xShURHiyRUQ22K6V4cSIfuSPhTSfkz4/mGM3GH6z32vJz3mvM19d8xbOWfjldZC3QS14GLmpgC4TCEB8foRDKA1/nV+6Rdm21zl2f63Lyt8HSoS4IS+dJPpU7ezppaj5QDftuyumKngQalLu4MP9grkeoCeIPTOA5fqHuC0zk7ah5mhyP1Fe6LRRmn7XJlYaXf/wcn2j+u9OtKPrTMznNp/3qsgrBUMuGGfQTbyMOEz7RXZ6fwBUjCvg+3rGGRcn5+iygZjvhNpkCaQXKDJXgdSv3yT4Hwg6BVWY1PB6UhRQLWQ==

**Comment by aKocian** [comment]
Položka total price musí být formátována 2 desetinná místa  B.O.S.S. Enterprise|6290.0**0**'

**Comment by jirek** [comment]
Mockrát děkuji za pomoc. Nyní již úspěšně odesíláme EET informace. Snad už poslední otázka, po zadání testovací karty pro úspěšnou autentizaci (4125010001000208) se správně zobrazí přehled platby a informace o úspěšném autentizaci, po té dlouho probíhá _Spojujeme_ se s vaší _bankou…_, která ve finále skončí zpět na formuláři pro zadání platební karty s hláškou

_Omlouváme se za nepříjemnosti, platbu se z technických důvodů na naší straně nepodařilo zpracovat._
_Platbu můžete zkusit znovu._

Mockrát děkuji za odpověď.

**Comment by mrazekl** [comment]
Dobrý den,

Váš požadavek byl doplňen pod: TSGSMIPS-3142 a předán k řešení.
O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

**Comment by jirek** [comment]
Dobrý den,
omlouvám se, ale mohl bych se opět zeptat jaký je stav?
Předem děkuji za odpověď.

**Comment by ratajskym** [comment]
@jirek Dobrý den, omlouvám se za prodlení v řešení Vašeho problému. 

Můžete prosím vyzkoušet transakci ještě jednou a napsal sem payID? Podíval bych se do aktuálního logu.

Děkuji

**Comment by jirek** [comment]
Dobrý den,
děkuji za odpověď. Vyzkoušel jsem znovu transakci s payID='d9866cde1c589CB' a výsledek opět stejný.
Děkuji.


Ukázka zasílaných dat:
{
"merchantId": "M1MIPS0332",
 "orderNo": 73550, 
"dttm": "20170228102700",
 "payOperation": "payment", 
"payMethod": "card",
 "totalAmount": 629000, 
"currency": "CZK", 
"closePayment": "true", 
"returnUrl": "https://test.mp.cz/eshop/cart/pay-by-card/",
 "returnMethod": "POST", 
"cart": [{"name": "N\\u00e1kup zbo\\u017e\\u00ed", "quantity": "1", "amount": 629000, "description": "N\\u00e1kup na www.mp.cz"}, 
{"name": "Doprava", "quantity": "1", "amount": 0, "description": "Doprava"}],
 "description": "N\\u00e1kup na www.mp.cz a doprava",
 "merchantData": "d3d3Lm1wLmN6", 
"language": "CZ", "signature": "nJ5dB761u6ezzOIZUmTTB6AfGvlxr0g3p+eANoFKNokKfoMgDCE35HKxLWrZ6qS82+/N4Xy6kaKNuK5G6gSzoFVFxK5IGZqBEMogUotdxmIPDlai10stEVbpEGE3XpJhUtn9ueYMBdOX+MFHCyIhuksUQECbzc+qwM9tJWG/SxE/LE1/4k02u4CFJmYk9s3DYeys37b8dfyPEn9ywGa0F8XvUgK1V9O2fQ+1J8f9s93ePKgZcHTt21DTfLEkT9LCH0zSmOMwV6A1fz8oiRxiqJgiL47bawjvORM505nY0VtyEjOfFvDkLliHshs5rX91pS3raj0OsQmFCptX1W2DhA==", 
"extensions": [
{"extension": "eetV3", 
"dttm": "20170228102700",
 "data": {"premiseId": 31, 
"cashRegisterId": "B.O.S.S. Enterprise",
 "totalPrice": "6290.00"},
 "signature": "EFMrnegQlQ0yv9osH0OVJRbyn+V7RSIiJRY89Z1CvVIB1wWOilRBwcXRif1ksl8vfXwE006Ss6lv5lcrWOTzImhRSXYOADCpbsp1qFMQLP8TL9JL4sSgduYxJ/mvlNz8vitNM3HEOKeb3vNcQvyvIM0NmKcAD8W5vbZeZnCcBOGdC48meSm1+FqMiNuDbi1zWuUmx0RSpbLxjl5EF5F03mBaYpqyFvG2M4I9B2LoOIbHjbGfGqi/sVxrGSmRBgY/UQb9dGuKihnmuUmYETvIceHTGvpRYV4ZTAB9uqGInfzlbiq+H3Q09jKgx8tZAzJFi1uzcajTK2ySMWIHe86dMg=="}
]
}

**Comment by ratajskym** [comment]
Unable to load EET key for merchant M1MIPS0332

Pro Vašeho obchodníka posílate EET transakci, ale nemáte zavedený certifikát pro komunikaci s FÚ.

**Comment by jirek** [comment]
Zavedením certifikátu myslíte v aplikaci POSMerchant v záložce Obchodník?

**Comment by ratajskym** [comment]
Ano

**Comment by ratajskym** [comment]
@jirek Vidím potvrzenou transakci. Takže to pomohlo ?

**Comment by jirek** [comment]
Ano. Mockrát děkuji. Chtěl sem napsat, až budeme mít ověřeno i na produkčním.

**Comment by ratajskym** [comment]
Dobře, pro tuto chvíli jsem tedy assignoval issue na Vás. Jakmile bude potvrzeno, uzavřeme

**Comment by jirek** [comment]
@ratajskym Už máme otestováno i na produkčním.
Ještě jednou mockrát děkujeme všem za pomoc. Můžete uzavřít.
Přeji pěkný den.
