### ISSUE TITLE
Problém s odesláním platby s údaji o eet

### ISSUE THREAD

**Issue by michalsafranek** [csob/paymentgateway#263]
Dobrý den,
máme problém s produkční bránou - pokud odešleme data včetně eet extension, vše proběhne v pořádku, dojde k přesměrování na bránu, ovšem po zadání platebních údajů a 3d secure kódu probíhá cca 2 minuty "Spojujeme se s vaší bankou" a pokus skončí vždy neúspěšně. Z banky máme ověřené, že EET ext. je povolené. Může nám s tím někdo pomoci?

**Comment by mjanek** [comment]
Dobrý den,

Mohl byste nám zaslat ID brány, abychom mohli prověřit ? 

Děkuji

M.Janek

**Comment by michalsafranek** [comment]
Dobrý den,
díky za rychlou dopověď. ID je M1MIPS0263, na testovacím rozhraní fungovalo vše ok. Připojuji ještě údaje z initu platby.

https://api.platebnibrana.csob.cz/api/v1.7/payment/init/ <https://api.platebnibrana.csob.cz/api/v1.7/payment/init/>
{
    "merchantId": "M1MIPS0263",
    "orderNo": "86",
    "dttm": "20170227090943",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 33900,
    "currency": "CZK",
    "closePayment": "true",
    "returnUrl": "https://www.hayashi.cz/pay-status.php <https://www.hayashi.cz/pay-status.php>",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Nákup na hayashi.cz",
            "quantity": 1,
            "amount": 33900
        }
    ],
    "description": "Nákup na hayashi.cz",
    "merchantData": "ODZ8MzM5",
    "language": "CZ",
    "signature": "PWyptaQ87x06ywZwZlpHh1RNvGqEX2l0ZTNUApUPp0eggTZLeoeW8DfMRHAfgksAy+joA/3+MhnKrQJ5bAZ9Jo5va7gSzJ9WJFI6K3SflL1YAiGFsZzi+I85fELITChMsOa2uqsSMyuLjxOe9XHMwh1fh2pRxlcMVjbtvp7sNJXPaq5HvGCsm+vtqL/qZrOOASwiLdLAUQw3hRC6s3RMFTH5uEG6DHhx7EkMzG1CeIbHmK35MmqcPSckTH0hb+0Fk2MXjj+L01C97yrZexiXrIlQ3pLZfZ0vuAOMIQrRCmHXh9clH+VRbJHghRwHCaiuj0eqjJhSHIRQ27p2IPxlcw==",
    "extensions": [
        {
            "extension": "eetV3",
            "dttm": "20170227090943",
            "data": {
                "premiseId": "31",
                "cashRegisterId": "1",
                "totalPrice": "339.00",
                "priceStandardVat": "280.17",
                "vatStandard": "58.83"
            },
            "signature": "hKXNOi3CL/Kq8tPn/9gNJZd0JIIxr/VSSJifTdCIgI4JRnLYIy0T88oshySBuwt6EKAxHjvTw9SNq75bl+6dZQZEatx9ZAFpZMD0GNGTP9+Caxfq8pRovSnpRjbUvQpgV8kfP1oAWU3BjPq5wZFA+50+AbBw6P7UiX3kjBtFY46YhrBVLv+Iw0ZimY+ZnXr3G0KC1JX+aArF58Lx6Bf9d09/A9MKn3TrZiJCzOQ2pM4AgQORCgm8HtMAemPyqjOp8MLSoOKsK9xv9TNk6goEQeukK3W/JHtC1hTAoW/IRL6juf2lx8wiS1sO4/JH2tg4zmLXTNsq8GXFAJZ6XUXsZA=="
        }
    ]
}
a odpověď na payment/status:

{"dttm":"20170227091836","signature":"ojpmg7UK0YFjejHqAr8Dgn5oVqOPKmkU0r5oYR6m/H5XpH83SD3CuiJ5HVwVB26CygiKv6KFCdBzgvViT+nnmxcMQ48LUIxYCdIaRGFWPPhtWtbNb1Uo7PIgj9Z7JHqAU67I9AKngW45iSux7oG9dk3iFUVldWgYuK4LkT3QAuECsY00+rnoJTXyL/vTc6JuhuXmTCJ7M+o3xmnPl0Bs/clvs4LXkr2l/hzEEkiThwfN2EaD/BdJzCuO+g6lF2jMFMu9bGa+gDiJFEr+YlzYjfnDR6sXEMybAnkViiE3FQkf9CV3e4DMy1Cfj8GxwZu6w4B9XHEnRCqyeu1aal2S6g==","payId":"41e4c0cbe98a3CB","resultCode":0,"resultMessage":"OK","paymentStatus":1,"extensions":[{"dttm":"20170227091836","signature":"pQ/HGbGBriBKVNBSYFj2AC4VT/rsWVSMiEO+bOzjMrOR35n4V7NPICr15vtjSevGsOeFdpT+aNRjjJKBijuNt/RRvTnl51wYKZO6q9Dl3ZuOfnZP7ixPFA8Jhjqbg+dwduv4z0RFfQQmMYiWCljU5J8tZmRNiFkSGmL6QMJM48Yl49uN8djtVTBU51Bg85fdgSRULcjNtRgokIC4zt1wwcHoi9XoN4BIJ8qLwb9UkU4Ej5A13xI/WxGmQQwV93GuAf0mXJLAxkWfmtXFEOieoUwV0xGVFJIMfyTcG/wnEC9EWSeeeMcKCfXcCRExeMjudjWyHc5kB0UwJkTB9qdhYA==","extension":"eetV3","report":{"eetStatus":1,"data":{"premiseId":31,"cashRegisterId":"1","totalPrice":339,"priceStandardVat":280.17,"vatStandard":58.83},"verificationMode":false,"vatId":"CZ03472591"}}]}

S pozdravem

Michal Šafránek, Dobříš.NETwork
Network administrator
Tel.: 775 610 810
E-mail: michal.safranek@dobris.net

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek jsme zaregistrovali. O dalším průběhu budete kontaktován odpovědným kolegou.

s pozdravem

Spisar

**Comment by michalsafranek** [comment]
Vyřešeno aktivací certifikátu u platební brány.
