### ISSUE TITLE
Problém pri odosielaní EET - TSGBANME-21

### ISSUE THREAD

**Issue by DenisKrcho** [csob/paymentgateway#264]
Dobrý deň,

máme problém s vygenerovaní kľúča pre platobnú bránu ak povolíme extension EET. Ak EET zruším (zakomentujem "extensions"), tak presmerovanie na bránu prebehne bez problémov. EET máme povolené, cerfitikát sme nahrali.

Prikladám aj volanie, ktoré posielame platobnej bráne (v 1.7).

[http://pastebin.com/RnFgBCH5](http://pastebin.com/RnFgBCH5)

Ďakujem za pomoc.

**Comment by mafrez** [comment]
Dobry den,
mame stejny problem. Koncime na chybe 500 - "payment/init failed". Dela to jen rozsireni pro EET.

Testovaci MerchantID: A23067Kin0

**Comment by hanuss** [comment]
@mafrez Na anonymním Merchant ID není EET extension povolováno. Pokud máte uzavřenou smlouvu na EET s bankou (ČSOB), pak prosím o zaslání Merchant ID začínajícího "M" (ve tvaru M1MIPSxxxx nebo M1E3CBxxxx) a my Vám EET extension povolíme.

**Comment by ratajskym** [comment]
Dobrý den všem, 

doplnil jsem informaci do FAQ na [wiki](https://github.com/csob/paymentgateway/wiki/%C4%8Cast%C3%A9-ot%C3%A1zky-k-EET#mohu-si-eet-na-platebn%C3%AD-br%C3%A1n%C4%9B-n%C4%9Bjak-vyzkou%C5%A1et)

**Comment by DenisKrcho** [comment]
Ja používam správne Merchant ID a posielam aj "Příznak ověřovacího módu odesílání". Môj problém to teda nevyriešilo.

Ďakujem za odpoveď.

**Comment by ratajskym** [comment]
@DenisKrcho Ve vašem "pastebin" máte [verificationMode] => 1 ... zkuste prosím použít true, jak se píše ve wiki

**Comment by DenisKrcho** [comment]
http://pastebin.com/GaRbysga momentálne to odosiela takto. Ak sú potrebné podpisy tak ich môžem zaslať.

**Comment by ratajskym** [comment]
Extension musíte dát do pole stejně jako dáváte pole "cart"
