### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by Pally20** [csob/paymentgateway#265]
Dobry den,

snazim sa sprovoznit full refund, ale stale dostavam odpoved: 

Response Object ( [payId] => b2b7bd6610b5fCB [dttm] => 20170228092230 [resultCode] => 150 [resultMessage] => Payment not in valid state [paymentStatus] => 7 [authCode] => [merchantData] => [signature] => VASENBWhyVfe3xlgB5Cf7UVHNyVBOe6IQJPYnpL/Y7VMPIzw0e0eGjnsEczHl8f56VCVVFnwgZCRXijAoWmfgUTl4tCSDUWb4JsWFuPLWbWCjsKwfETNA/yDRWcxnoY5xOvlfS+fDiUq3vWV4uYjQo3kCcUV/hrtyaMQVaccXzpWndKqMROawQmjhJBN8t8J8N8GhJ8MIfnH7yM38hhHsPPKE3JcLqJC6yOqFF4Ow0drCEx3+X1w1qyuGdfh97Fgy16b30RzMywj7f0BB5kVK05Dfwx7WlF/Tfm2AmaGnQ3J/+VQzM7NNsF7dkoZ9A7YU2bwprIKKyeNzk+aNJmnIA== )

podle "paymentStatus" vidim ze platba se jeste zauctovava, tak som skusil "reverse" ale i tam mi to hlasi:

Response Object ( [payId] => b2b7bd6610b5fCB [dttm] => 20170228095446 [resultCode] => 150 [resultMessage] => Payment not in valid state [paymentStatus] => 5 [authCode] => [merchantData] => [signature] => obrBxdqJGniaCKTWiIgopudsz0cMwpAWu3k/NvZyiIJge+kYZaACW7eitFKvK6yOpvNS9dOczN5+dVJf2ce2Kn5DvrQjq5VSgqqc7/+mM2YCrfN/ZjiW45cwT09IDU8Ev7Y0ltbgUigtn6INXwnyM3lwbdP9gcedVyyWLOvGNmt1N1q44jHVTh4WqSWKLsfHgBprj/Z/rqVPc4/voS+3zpGgQRGHH1X5t3ESp9E70Cq6t2mrhE7Kpg1S4dQnTi2Oonmi9ZXEpTgSPtZB5lz+gr0zlliYDzbGkAIgJnN759Bfpk9jrC6JeLkvROmnzxHXTn9ifCy91N8Rux3FI/weWw== )

"resultCode" => 150
"resultMessage" => Payment not in valid state

Vedeli by ste mi stym helpnut ?

Dekuji.

**Comment by Pally20** [comment]
Omlouvam se uz chapu ze platba jeste ceka na zuctovani ([paymentStatus] => 7) 

Jeste jednou se omlouvam.

**Comment by ratajskym** [comment]
Dobrý den, operaci refund je možné volat až po uzavření transakce tzn. až bude ve stavu 8. 

Možná vás zajímá [payment/reverse](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#put-httpsapiplatebnibranacsobczapiv17paymentreverse-)

**Comment by Pally20** [comment]
Dobry den, ano viem a kopirujem znova:

podle "paymentStatus" vidim ze platba se jeste zauctovava, tak som skusil "reverse" ale i tam mi to hlasi:

Response Object ( [payId] => b2b7bd6610b5fCB [dttm] => 20170228095446 [resultCode] => 150 [resultMessage] => Payment not in valid state [paymentStatus] => 5 [authCode] => [merchantData] => [signature] => obrBxdqJGniaCKTWiIgopudsz0cMwpAWu3k/NvZyiIJge+kYZaACW7eitFKvK6yOpvNS9dOczN5+dVJf2ce2Kn5DvrQjq5VSgqqc7/+mM2YCrfN/ZjiW45cwT09IDU8Ev7Y0ltbgUigtn6INXwnyM3lwbdP9gcedVyyWLOvGNmt1N1q44jHVTh4WqSWKLsfHgBprj/Z/rqVPc4/voS+3zpGgQRGHH1X5t3ESp9E70Cq6t2mrhE7Kpg1S4dQnTi2Oonmi9ZXEpTgSPtZB5lz+gr0zlliYDzbGkAIgJnN759Bfpk9jrC6JeLkvROmnzxHXTn9ifCy91N8Rux3FI/weWw== )

"resultCode" => 150
"resultMessage" => Payment not in valid state

Dekuji

**Comment by ratajskym** [comment]
Původně jsem si toho nevšiml, ale transakci jste již reverzoval dnes ráno - 28.02.2017 09:53:08

**Comment by ratajskym** [comment]
@Pally20 Je tedy vše v pořádku, nebo můžu zkontrolovat ještě něco ?
