### ISSUE TITLE
Platba na klik po registraci

### ISSUE THREAD

**Issue by janfabian** [csob/paymentgateway#266]
Dobrý den, 
potřebuji dovolit uživateli vyplnit svou kreditní kartu při registraci. Tuto kartu poté nabídnout při placení ve stylu platby Na klik. 

Jinými slovy uložit šablonu platby na klik už když se uživatel zaregistruje a vyplní kreditku. Je to možné? 

Díky 
Fabián

**Comment by hanuss** [comment]
Dobrý den, 
ano tuto funkce je dostupná, jako extension. Popis je na odkazu níže.
https://github.com/csob/paymentgateway/wiki/eAPI-1.6-maskovane-cislo-karty
Jak je napsáno v návodu, tuto funkci musíte mít povolenu v Platebních metodách v aplikaci POSmerchant.
hanuss

**Comment by janfabian** [comment]
díky za odpověď, upřesním dotaz

příklad - stáhnu si jako uživatel aplikaci Uber, při registraci vyplním kreditku, hned první platba, kterou provedu v aplikaci mi strhne peníze z kreditky, aniž by mě přesměrovala na platební bránu. Jde to pomocí csob gateway?

**Comment by dmarek** [comment]
Prvotni transakce, ktera je potreba pro nasledne oneclick platby, se odehrava za ucasti klienta na platebni brane (resi se 3DS overeni a zadavani CVC), nelze ji provest mimo platebni branu.

**Comment by janfabian** [comment]
OK, děkuji
