### ISSUE TITLE
Nespravna mena pri platbe pres plugin.

### ISSUE THREAD

**Issue by d4ng3rart** [csob/paymentgateway#267]
Dobry den. Pri platbe pomoci brany posila plugin jinou menu. Napriklad, klient objednava zbozi za 120 eur, macka na tlacitko "Platit pomoci karty", pak ho system presmeruje na branu, kde je napsano misto 120 eur - 120 kc. V cim je, prosim, problem? Woocommerce posila currency:"EUR", ale v logech vidim currency:"CZK". Cim to muze byt zpusobeno? V obchode mam 3 meny: EUR, CZK a RUB, pouzivam WPML pro woocommerce, veskere nastaveni mam zrejme v poradku.

**Comment by joskera** [comment]
Dobrý den, 
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by ratajskym** [comment]
@d4ng3rart 
Dobrý den, 
v pluginu je možné nastavit pouze jednu měnu viz tento [soubor](https://github.com/csob/paymentgateway/blob/master/WooCommerce%20Plugin/www/monetWebPay/crypto.php)

**Comment by d4ng3rart** [comment]
Dobry den. To znamena, ze musime delat konvertace meny pred odesilanim ceny do brany, a brana bude vyuctovat v CZK?

**Comment by ratajskym** [comment]
Pokud posíláte platby z Woocommerce pluginu, musíte u sebe převést částku na měnu, kterou máte nastavenou v konfiguraci pluginu.

**Comment by ratajskym** [comment]
@d4ng3rart 
Dobrý den, máte k dispozici i testovací instanci, např. proti integračnímu prostředí ?

**Comment by ratajskym** [comment]
@d4ng3rart 
Dobrý den, v repozitáři je aktualizovaný plugin pro podporu multicurrency.
