### ISSUE TITLE
Error: We are experiencing technical difficulties and are therefore unable to authorize your payment...

### ISSUE THREAD

**Issue by graceman9** [csob/paymentgateway#268]
Hello, I have added EET extension to my code. And everything seems fine, before I were redirected to the CSOB bank page, the page where credit card input is needed. I'm getting this error constantly:
![csob-26-technical-difficulties](https://cloud.githubusercontent.com/assets/237712/23453259/550b16fa-fe70-11e6-8acb-ba003e6610c6.png)

I've used these cards to pay (cards for successful payment), I've used 11/20 and 100 as date and cvv2. The same error appears all the time.
https://github.com/csob/paymentgateway/wiki/Credit-Cards-for-Testing

Here are my debug data - requests, json, payloads, urls:
https://gist.github.com/graceman9/aa9ef4f0622a2f35280448d83515fa67

Could you help me please to find out what does this error means?

**Comment by ratajskym** [comment]
It is caused, because you dont have EET certificate. It must be inserted via POSMERCHANT application.

**Comment by ratajskym** [comment]
I can see succesfull transactions at the moment. Can we close this issue ?

**Comment by graceman9** [comment]
Thanks a lot! :+1: you saved me one more time ;)
