### ISSUE TITLE
nefunkční EET rozšíření na produkci

### ISSUE THREAD

**Issue by MVeselka** [csob/paymentgateway#269]
Dobry den,
u platebnich bran M1E3CB3760 a M1MIPS0796 nam nefunguje EET rozsireni na produkcnim prostredi.
- v testovaci verzi posmerchat vidime v detailu platebni brany tllacitko na moznost volby platebni metody pro EET, v produkcnim prostredi toto tlacitko neni.
- stejne tak v testovacim prostredi vidme u kazde platby ikonku v slupecku EET (sedy nebo zeleny puntik), ale na produkcnim prostredi toto nevidime.
- podle csob mame vse aktivovane (certifikat nahrany, u obchodniho mista - stav aktivni, certifikat u platebni brany taktez) ale proste to tam neni a nefunguje to. Je divne ze to dela u obou platebnich bran (dva nezavisle systemy).
- z tohoto duvodu jsme museli platby kartou vypnout a nevime co s tim, nikdo nam neni schopen odpovedet, nebo to zprovoznit - ani v CSOB ani na helpline Monet+.

M.V.

**Comment by ratajskym** [comment]
Dobrý den,

vaše požadavky posíláte na api 1.5. EET je podporováne od verze 1.6
/api/v1.5/payment/init/

**Comment by MVeselka** [comment]
díky za radu, rozšíření již funguje, jen tedy nevidíme v aplikaci POS MERCHANT to tlačítko pro výběr platebních metod EET

**Comment by ratajskym** [comment]
Tak to je dobrá zpráva. 

Tlačítko v pos merchantu bude doplněno v nejbližší možné době. Nicméně na funkčnost eet to nemá žádný vliv.
