### ISSUE TITLE
Platební brána paymuzo

### ISSUE THREAD

**Issue by zackx1** [csob/paymentgateway#27]
Dobrý den,
po konzultaci s majitelem eshopu shop5.cz jsem zjistil, že tento eshop Vaši novou platební bránu nepodporuje, lze ji však realizovat pomocí starší služby paymuzo, k té však nemám potřebnou dokumentaci pro nastavení. V nastavení jsou uvedené parametry:
paymuzo - merchant_number		
paymuzo - privatni klic		
paymuzo - verejny klic		
paymuzo - heslo k privatnimu klici		
paymuzo - verejny cert. paymuzo		
paymuzo - url order
Předpokládám, že merchant number, url order a klíče budou shodné jako u nové platební brány, nevím však, kde najít zbylé parametry.
Děkuji za odpověď,
Dolenský

**Comment by ratajskym** [comment]
Dobrý den, 

pokud migrujete, projděte si dokumentaci zde https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

**Comment by zackx1** [comment]
Dobrý den,
děkuji za odpověď, já však nemigruji, ale snažím se bránu nastavit na eshopu, kde ještě nebyla. V odkazu, který jste mi poslal, jsou pouze pokyny pro přenastavení již funkční brány, pokyny pro nastavení služby PAYMUZO nemohu nikde najít.

**Comment by ratajskym** [comment]
Dokumentaci ke službě paymuzo nemám a neznám. Můžeme to zkusit uhádnout

merchant_number - obdržel jste z banky, případně na testu anonymní účet
privátní klíč - vygenerovaný zde https://platebnibrana.csob.cz/keygen/ 
veřejný klíč - vygenerovaný zde https://platebnibrana.csob.cz/keygen/
heslo k privátnímu klíči - žádné heslo
verejny cert. paymuzo - netuším, nemá se zadat třeba veřejný klíč brány https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys ? 
url order - viz dokumentace https://github.com/csob/paymentgateway/wiki

**Comment by zackx1** [comment]
Děkuji, nakonec se toho ujal přímo majitel hostingu, ten po mně však požaduje převést klíče do formátu .pem, k čemuž jsem sice info zde našel (https://github.com/csob/paymentgateway/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy),
ale neovládám ani jeden z uvedených programovacích jazyků, existuje nějaká utilita nebo ideálně oficiální nástroj pro převedení formátu těchto klíčů? 

Děkuji za odpověď a hlavně za trpělivost. :)

**Comment by ratajskym** [comment]
@zackx1 

Dobrý den, jak to vypadá s Vaší implementací?

**Comment by zackx1** [comment]
Dobrý den,
komunikoval jsem s panem Hrňou, který mi poradil, jak správně vytvořit potřebné klíče, po jejich nastavení však e-shop hlásí chybu a nepřesměřuje mě na platební bránu. Jako jediné řešení asi vidím spojit se s majitelem shopu, aby mi poskytl potřebné logy.

**Comment by ratajskym** [comment]
Dobře, nechám tedy task ještě otevřený.
