### ISSUE TITLE
Postup při přechodu na eAPI z ČSOB brány kompatibilní s GP WEBPAY

### ISSUE THREAD

**Issue by wdtbrchan** [csob/paymentgateway#270]
Dobrý den,
v současnosti používáme pro naše e-shopy platby přes ČSOB platební bránu v CZK a EUR, ale ve verzi kompatibilní s GP WEBPAY. Rádi bychom přešli na novou verzi eAPI. Jaký je postup? Jedná se zároveň o to, aby do doby, než nasadíme novou verzi, tak současné platební brány fungovaly. Je potřeba vygenerovat nové testovací a produkční klíče nebo budou fungovat stávající?

**Comment by ratajskym** [comment]
Dobrý den, 

[tady](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7) máte k dispozici všechny potřebné údaje. Máte v podstatě dvě možnosti:
- můžete si vygenerovat anonymní merchant id a vyvíjet s tímhle id
- můžete si na integračním prostředí používat Vaše stávající id 

V jakém stavu máte klíče netuším, neznám Vaše merchant id. Případně se můžeme zkontaktovat napřímo a můžeme to probrat po telefonu.

**Comment by wdtbrchan** [comment]
Zatím jsme to připravili s anonymním Merchant ID, jde nám teď pouze o fázi testování a přechodu na produkční prostředí, tzn. zda máme vygenerovat nové klíče nebo půjdou použít stávající, ale zároveň musí během testování fungovat i původní řešení se stejnými klíči, které teď běží v produčním režimu. Pošlu Vám Merchant ID, napište mi prosím na brchan@wdt.cz.

**Comment by ratajskym** [comment]
Můžete i nadále používat Vaše privátní klíče. Více info v emailu.

**Comment by ratajskym** [comment]
Vzhledem k tomu, že to řešíme napřímo přes email, toto issue zavírám
