### ISSUE TITLE
Error: Your payment was declined by your card issuer without quoting any specific reason. Please use another card or return to...

### ISSUE THREAD

**Issue by graceman9** [csob/paymentgateway#271]
Basically we were having two instances - two folder on the server:
payment/ - old version which uses v1.5 of CSOB API
and 
payment2/ - new version - v1.7

After solving #268 (on payment2/) we have moved the code to the "payment/".
Then I did tests for test env - OK, and then I've switched to prod environment - FAILED.
Again, on the "payment2" both tests were OK.

Please tell me what that error means?
![csob_132-your-payment-wasdeclined-by-your-card-issuer](https://cloud.githubusercontent.com/assets/237712/23461400/75d0d89e-fe92-11e6-9ab6-550fe2fa0c45.png)

Json payload is here:
https://gist.github.com/graceman9/dc6ed6ffe1a94cf644db0cd29a00fc8b

I've used this card: 
https://github.com/csob/paymentgateway/wiki/How-to-Switch-to-the-Live-Environment

**Comment by ratajskym** [comment]
Transaction was declined by your bank with status=56, text=UNK_56

Unfortunatelly, i cannot say what exactly does it mean

**Comment by graceman9** [comment]
But... It was a not real card, it's only test card from https://github.com/csob/paymentgateway/wiki/How-to-Switch-to-the-Live-Environment

Should it work? or is there any other card for test?

**Comment by ratajskym** [comment]
Well, you are on the production system where test cards are not valid anymore. So thats the reason of decline of the transaction. Use real card if you want to test your production setup.

**Comment by graceman9** [comment]
Ok, thanks
