### ISSUE TITLE
EET - evidence tržby offline

### ISSUE THREAD

**Issue by arxeiss** [csob/paymentgateway#272]
Dobrý den,

je možné nějak otestovat na iBráně nedostupnost EET a tedy navrácení hodnot BKP a PKP?
Pokud ne, šlo by to třeba řešit přidáním platební karty, která by prošla, ale následně by EET vrátilo kód E4, neboli offline evidenci.

Děkuji

**Comment by ratajskym** [comment]
Dobrý den, podívejte se na tuto [stránku](https://github.com/csob/paymentgateway/wiki/Testov%C3%A1n%C3%AD-EET-a-p%C5%99echod-do-produkce) 

Nastavováním cashRegisterId byste měl docílit požadovaného výsledku

**Comment by arxeiss** [comment]
Omlouvám se, tuto stránku jsem viděl několikrát, ale nikdy mi to nedošlo, že to jsou údaje k simulování.
Děkuji

**Comment by arxeiss** [comment]
Asi jsem se trochu unáhlil s uzavíráním.
Nyní jsem to vyzkoušel, a ať dělám, co dělám, stále dostávám návratový kód 3.

Posílám data jako jsou ilustrovány níže. Po návratu z brány mi ale EET status se zobrazí jako 3.. Zkusil jsem i místo `"cashRegisterId": "E6"` zvolit pouze `"cashRegisterId": "6"`, ale nepomohlo
```
"extensions":[
    {
      "extension": "eetV3",
      "dttm": "20170303005030",
      "data": {
        "premiseId": 11,
        "cashRegisterId": "E6",
        "totalPrice": "100.00"
      },
      "signature": "..."
    }
  ]
```

**Comment by dmarek** [comment]
V pripade, ze nastavite cashRegisterId na "E3", vygeneruje brana po autorizaci (presneji po zarazeni transakce do zuctovani) kody FIK a BKP, vraci stav 3 (online nahlaseni)

Pokud nastavite "E4", vrati platebni brana kody PKP + BKP, vraci stav 4, tzn. offline zpracovani a danou trx se pokousi dorucit pozdeji.

V pripade, ze nastavite "E5", vraci simulator EET platebni brane chybu "5, Neplatny kontrolni bezpecnostni kod poplatnika (BKP)", platebni brana transakci zamitne, v payment/status se vraci payment status 6, eet status 5

Simulace stavu E6 a E7 je mozna jen zcasti, do eet stavu 6 se trx dostane az po dalsim pokusu o nahlaseni ze stavu E4 (cca 1 hod po prvnim pokusu), stav 7 je podobny stavu 5 (trx se zamitne)

upravime dokumentaci /  zapracujeme vyse uvedene poznamky

**Comment by dmarek** [comment]
Dobry den, pomohl vyse uvedeny popis, muzeme zavrit?

**Comment by arxeiss** [comment]
Dobrý den,

ano, po využití kódu E4 již vše funguje.

Děkuji
