### ISSUE TITLE
MasterPass - payId při GET na callbackUrl

### ISSUE THREAD

**Issue by lubomirpokorny** [csob/paymentgateway#273]
Dobrý den,

aktuálně provádím integraci basic varianty MasterPass a není mi zřejmá jedna věc - při obsluze GET požadavku na callbackUrl obchodníka není předáváno `payId`? Jestli tomu rozumím dobře, tak reakcí na tento požadavek by mělo být volání `masterpass/basic/finish`, ale k tomu potřebuji znát payId...?

Vycházím z [tohoto odstavce](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#endpoint-pro-callbackurl) na wiki.

Děkuji za odpověď.
Lubomír P.

**Comment by joskera** [comment]
Dobrý den, 
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by dmarek** [comment]
MasterPass API  umožnuje predat zpet jen parametry mpstatus, oauth_token a nepovinné checkout_resource_url a oauth_verifier. 
Musite si tedy předávat identifikaci objednávky (anebo payId) v rámci callbackUrl, následně volat masterpass/basic/finish.

**Comment by dmarek** [comment]
dobry den, muzeme zavrit?

**Comment by lubomirpokorny** [comment]
Můžete, díky za odpověď.
