### ISSUE TITLE
payment/button vrací HTTP 400

### ISSUE THREAD

**Issue by senik** [csob/paymentgateway#274]
Dobrý den,

snažím se do platební brány ComGate integrovat platební tlačítka ČSOB/Poštovní spořitelny a nedaří se mi dokončit platbu. Volání payment/init proběhne korektně, dostanu zpět payId, ale volání payment/button vždy vrací HTTP 400.

Přikládám výpisy z logu, odmazal jsem JSON payloady kvůli délce výpisu, ale důležitá data zůstala:

`2017-03-08 13:01:53.541235 Signing string "M1MIPS0131|20170308130153"`
`2017-03-08 13:01:53.541324 Will send request to method echo`
`2017-03-08 13:01:53.541475 URL to send request to: https://iapi.iplatebnibrana.csob.cz/api/v1.7/echo`
`2017-03-08 13:01:53.631133 String for verifying signature: "20170308130153|0|OK"`
`2017-03-08 13:01:53.631396 OK`
`2017-03-08 13:01:53.631462 Connection test POST successful.`
`2017-03-08 13:01:53.633613 payment/init started for payment with orderNo 26653143`
`2017-03-08 13:01:53.633701 Will send request to method payment/init`
`2017-03-08 13:01:53.633779 URL to send request to: https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/init`
`2017-03-08 13:01:53.825640 String for verifying signature: "6c6a8fbaa0b7dCC|20170308130153|0|OK|1"`
`2017-03-08 13:01:53.825924 OK`
`2017-03-08 13:01:53.825993 payment/init OK, got payId 6c6a8fbaa0b7dCC`
`2017-03-08 13:01:53.826073 prepared for button`
`2017-03-08 13:01:53.826139 sign for button`
`2017-03-08 13:01:53.826200 arry for button: array ('merchantId' => 'M1MIPS0131','payId' => '6c6a8fbaa0b7dCC','brand' => 'csob','dttm' => '20170308130153')`
`2017-03-08 13:01:53.826257 string to sign: M1MIPS0131|6c6a8fbaa0b7dCC|csob|20170308130153`
`2017-03-08 13:01:53.828195 payment/button started for payment with orderNo 26653143`
`2017-03-08 13:01:53.828260 Will send request to method payment/button`
`2017-03-08 13:01:53.828322 URL to send request to: https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/button`
`2017-03-08 13:01:53.888974 API response:`
`2017-03-08 13:01:53.889093 Failed: returned HTTP code 400`
`2017-03-08 13:01:53.890558 Fail, got exception: 0, API returned HTTP code 400, which is not code 200. Probably wrong signature, check crypto keys.`

Pro echo, payment/init a payment/button používám stejný klíč, stejné metody pro podpis požadavků.
Můžete zkusit prověřit transakci s payId "6c6a8fbaa0b7dCC" proč neprošla validace podpisu?

Případně může být důvodem chybná konfigurace (nepovolené metody pt@shop, staré klíče).

Děkuji za pomoc.

**Comment by dmarek** [comment]
kontrolovali jsme podepisovani payment/button na ibrane a opravime kontrolu podpisu na nasi strane, chyba byla ve spatnem poradi parametru

**Comment by dmarek** [comment]
nasazena oprava, muzete otestovat

**Comment by senik** [comment]
Oprava zafungovala, request na payment/button funguje, nyní mi to vrací result code 400 - sice je chybový, ale to už si dořeším s naší kontaktní osobou.

Děkuji.

**Comment by dmarek** [comment]
ok, zaviram
