### ISSUE TITLE
Přístup k testovacímu prostředí platební brány

### ISSUE THREAD

**Issue by ETNyx** [csob/paymentgateway#275]
Dobrý den,
mohli by jste ověřit zda-li má M1E3CB2491 přístup do testovacího prostředí platební brány? Má implementace mi vrací "HTTP/1.1 400 Bad Request" jiné merchan ID (anonymní) funguje bez problému.

Děkuji

**Comment by vzich** [comment]
Dobrý den,
pro uvedené merchantID nemáte vygenerované klíče. Vygenerovat si je můžete pro integrační prostředí [zde](https://iplatebnibrana.csob.cz/keygen/).
