### ISSUE TITLE
Reverse platba vrací  404

### ISSUE THREAD

**Issue by kapik2003** [csob/paymentgateway#276]
Dobrý den,
snažím se implementova tuto platební bránu. Vše funguje jak má a do plné validace brány mi zbývá už jen nasimulovat platbu se stavem reverzováno. Bohužel po zavolání požadavku mi to vrací http kód 404 a odpověď je prázdná (jedná se o platbu se stavem 4). Přepokládám, že se platbu nepodařilo dohledat, dle dokumentace zdroj nebyl nalezen.

Zde uvádím url, které posílám
https://iapi.iplatebnibrana.csob.cz/api/v1.5/payment/reverse/M1MIPS0878/1d70d5bcc5108CC/20170312135242/higTvFhOyiYXxyJUJlwF9jsaL8hlCGyLO%2FrQ2yRjANZlrUaWI6pdaLBsA0VAz7hizuEIInrOzm2K7AVdeeDDi%2FM6b6yUTjdA2K9rfnCJ5n8Peb8IIIgKrfpGfvaPFYecwGP8M23AAL8gV%2BLmvGsd9gqCn488lE%2BmTAiHrNGRwnd1iTP8gQqoy2ltsvS7geqXFVt6h2z82zZ7rMqQEhh6oRMmIDO85%2Fr8PyEqWyP%2FRY%2Bx9BYeJnjwC0qGfy59RG2NsPJhj1c0pdAYOQu1%2Fmz6tQLQ46girytwKrfLf%2FdzWjRY5Be9KpMr6ira4Tiw0kJHKHg1FP8WbGFf0c5SQjvY1A%3D%3D

Trochu mě překvapuje, že url je encodováno, neboť se zde jedná o PUT metodu. Dotaz na status platby problíhá normálně.

Budu rád za jakýkoliv názor.

S pozdravem
David Kaprál

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem
Alexander Kocian

**Comment by vzich** [comment]
Dobrý den,
dle aplikačního logu posíláte parametry jak v payloadu, tak i v url. Vyzkoušejte zaslat v URL https://iapi.iplatebnibrana.csob.cz/api/v1.5/payment/reverse namísto vámi uváděného requestu viz. [dokumentace](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#put-httpsapiplatebnibranacsobczapiv17paymentreverse-)

**Comment by kapik2003** [comment]
Dobrý den,
díky moc, to bylo ono. Mě to tam zůstalo z GET volání a tak se tam parametry opakovaly 2x. Už to funguje jak má.

Hezký den,
David Kaprál
