### ISSUE TITLE
Generování klíče

### ISSUE THREAD

**Issue by jan1971** [csob/paymentgateway#277]
Dobrý den. Pro merchantID M1MIPS1263 se snažím vygenerovat klíče pro testovací integrační prostředí. Stále s hláškou "nesprávný MerchantID nebo email". Není třeba ještě nějak povolit generování klíče v POS?
Děkuji. (Klienta pro ověření, zda mi poskytl správný email, jsem také kontaktoval.)

**Comment by vzich** [comment]
Dobrý den,
zadáváte chybný mail pro generování klíčů. Klient vám poskytl kontaktní mail, nikoli mail technické podpory, který je třeba zadat pro generování klíčů.
