### ISSUE TITLE
404 odpoved

### ISSUE THREAD

**Issue by radovanx** [csob/paymentgateway#278]
dobry den,
nasazujeme na produkcni prostredi eet brana vsak vraci 404 zasilana data se zdaji v poradku
kam se muzeme obratit pro overeni ?

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem
Alexander Kocian

**Comment by vzich** [comment]
Dobrý den, 
při založení platby posíláte v url dvojté lomítko. Proto se vám vrací 404.
https://.../api/v1.6//payment/init/

**Comment by radovanx** [comment]
dobry den
dekuji Nyni se vraci 400 zasilana data se zdaji v poradku
jedna se o obchodnika M1E3CB3000

**Comment by vzich** [comment]
Ve vašem posledním requestu máte špatný podpis. Nejprve ověřte správnost klíčů, tzn. zda opravdu používáte produkční privátní klíč a veřejný klíč banky dostupný [zde ](https://github.com/csob/paymentgateway/tree/master/keys) na githubu.

**Comment by radovanx** [comment]
dekuji verejny klic by mel byt v poradku.

**Comment by radovanx** [comment]
Nemuze chyba souviset s EET rozsirenim ? Je opravdu povoleno pro tento ucet ? Hodilo by se kdyby brana vracela konkretni chybu misto 400

**Comment by vzich** [comment]
EET extension máte na produkci povolenou, prověřil bych na vaší straně ještě jak posíláte některé z parametrů, orderNo zřejmě posíláte jako Number namísto stringu, v případě parametrů eet extension posíláte premiseID a všechny rozpisy částek jako string namísto number. Viz. dokumentace [eAPI](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#-post-httpsapiplatebnibranacsobczapiv17paymentinit-) a [EET](https://github.com/csob/paymentgateway/wiki/Specifikace-API-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-EET)

**Comment by radovanx** [comment]
Dobry den,
Zasilana data se zdaji jiz v poradku


data to sign eet: "eetV3|20170316221901|31|test|1199.00|600.00|495.01|103.99|0.00|0.00|0.00|0.00|true" data to sign: "M1E3CB3000|5484|20170316221901|payment|card|119900|CZK|true|http://www.ventilatory-shop.cz/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&unimodul=CSOB|POST|Teplovzdušný ventilá|1|59900|Teplovzdušný ventilátor ASTRO WHITE S...|Doprava|1|60000|Doprava|(Ord.No.:5484)|CZ"


 {"merchantId":"M1E3CB3000","orderNo":"5484","dttm":"20170316221901","payOperation":"payment","payMethod":"card","totalAmount":119900,"currency":"CZK","closePayment":"true","returnUrl":"http:\/\/www.ventilatory-shop.cz\/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&unimodul=CSOB","returnMethod":"POST","cart":[{"name":"Teplovzdu\u0161n\u00fd ventil\u00e1","quantity":1,"amount":59900,"description":"Teplovzdu\u0161n\u00fd ventil\u00e1tor ASTRO WHITE S..."},{"name":"Doprava","quantity":1,"amount":60000,"description":"Doprava"}],"description":"(Ord.No.:5484)","merchantData":null,"language":"CZ","signature":"alrPLp\/Soxo7amp\/xUNOdCWvGl72FqQv\/yzvSZXy6YTQ48FYJ0O87luRMzLIQNKR+QVbw75GL3x720TdQKOUNPFfirFCG\/sGCp5QgtJSs02Sf8rcfrO3UVg+9Ntm7m5XBLIUnsPffpVfRmty0S+3z5LskedOBtLfxUOqDElBZAzMuu9JhHge+9u6C3zW\/axd72Ceyn6o68pJ5uYatru8d0t4y1yl8ihgId3yGGhNZsjwdzS65mlPfBQ\/\/Q8C4iCbcSHFg0brda5fhe6A49\/ZqifVleifzY8iZvAo9M5QQSg\/VH36NgjysBnv6ENYoPR6ocbihYEn6+bRDrTONHxRQg==","extensions":[{"extension":"eetV3","dttm":"20170316221901","data":{"premiseId":31,"cashRegisterId":"test","totalPrice":1199.00,"priceZeroVat":600.00,"priceStandardVat":495.01,"vatStandard":103.99,"priceFirstReducedVat":0.00,"vatFirstReduced":0.00,"priceSecondReducedVat":0.00,"vatSecondReduced":0.00},"verificationMode":"true","signature":"SsDlA4AnSrmMFbKt3V3yyFOKdX2PtupEwSbSZq7ZcZQ+cYtnK6oJZfeCiM\/fA1xWlQ9MMaBo6nSDr50dTWbYmXDSoanYmtz+JijkKfEtq8X9WQuQLDJxhyzyAhZzBIpKkCjTeSr71kWVHaJVNP6PWW0B7SLS6AI3HNw6dSBxReA\/oLhopf9OK1GR2WMt3vTJ1kzdZe2WhhG3OO+EONcodtvvZ3kQDP7gyPFIYN9W86\/zo1t+SK\/01BI959YBOvz7GHz9wPJntmPkYeMDwCnq09UXc2qfw9CMDTdhheUMCAcLeu4jlSjolhdHbBkJqw4GnIYpxdpqfCvdqhz8Ufvs6A=="}]}

**Comment by vzich** [comment]
Dobrý den,
pořád máte chybu v podpisu.
Podle zaslaného requestu bych ještě prověřil zda posíláte parametr closePayment a verificationMode v eet rozsireni jako boolean (v případě, že používáte php, se do řetězce pro podpis nevkládá povolená hodnota true nebo false ale hodnota 1 nebo 0 viz. [časté technické dotazy](https://github.com/csob/paymentgateway/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy#p%C5%99i-odesl%C3%A1n%C3%AD-po%C5%BEadavku-na-native-api-se-vrac%C3%AD-http-status-400-bad-request)). Pokud si budete jist, že posíláte všechny parametry správně, tak je možné, že k podpisu používáte špatné klíče. Pokud Vám ale fungovalo zakládání plateb před implementací EET, tak by klíče ve vašem případě neměly být problém.
K vygenerování nových klíčů, případně uložení veřejného klíče, můžete použít generátor na linku - [platebnibrana.csob.cz/keygen/](https://platebnibrana.csob.cz/keygen/)

**Comment by radovanx** [comment]
Zda se ze posilam vse spravne eshop prechazi z gpwebpay certifikaty jsou vygenerovany nove

data to sign eet:"eetV3|20170323004608|31|test|1199.00|600.00|495.01|103.99|0.00|0.00|0.00|0.00|true
"data to sign:"M1E3CB3000|5491|20170323004608|payment|card|119900|CZK|true|http://www.ventilatory-shop.cz/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&unimodul=CSOB|POST|Produkty|1|59900|Produkty|Doprava|1|60000|Doprava|(Ord.No.:5491)|CZ"

{  
   "merchantId":"M1E3CB3000",
   "orderNo":"5491",
   "dttm":"20170323004608",
   "payOperation":"payment",
   "payMethod":"card",
   "totalAmount":119900,
   "currency":"CZK",
   "closePayment":true,
   "returnUrl":"http:\/\/www.ventilatory-shop.cz\/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&unimodul=CSOB",
   "returnMethod":"POST",
   "cart":[  
      {  
         "name":"Produkty",
         "quantity":1,
         "amount":59900,
         "description":"Produkty"
      },
      {  
         "name":"Doprava",
         "quantity":1,
         "amount":60000,
         "description":"Doprava"
      }
   ],
   "description":"(Ord.No.:5491)",
   "merchantData":null,
   "language":"CZ",
   "signature":"Tq0v9NlXzu1RlW0V1PQCyuKR\/e+BYI05XqPXwbZladnNrNAnEGHDvvqLe0KJo+La2q2qmNOkEOWstbe0DfEWZNMiZQY6jj37lqZfMWu997gIbf232Qh81HU1NQrP5qiVmLVMEzOy3ysIvxfIqiLA93AcMRShajjQhQSepQMMps9xqBKWDgonzCkVUDGNrP88ibyTmkpvFNhmyNYUE0JSoKPPlsgQq6DoxtPpBuNHx7KKEbeAc9dShtCT7zMOuMyCum1hhPMRf6+f5802eums+0uUPwqIYRrckSZW1QMlCyXzzXKy1m+YFTqLtgsS8H+4UY8JzCtugi64Gde22oZIkA==",
   "extensions":[  
      {  
         "extension":"eetV3",
         "dttm":"20170323004608",
         "data":{  
            "premiseId":31,
            "cashRegisterId":"test",
            "totalPrice":1199.00,
            "priceZeroVat":600.00,
            "priceStandardVat":495.01,
            "vatStandard":103.99,
            "priceFirstReducedVat":0.00,
            "vatFirstReduced":0.00,
            "priceSecondReducedVat":0.00,
            "vatSecondReduced":0.00
         },
         "verificationMode":true,
         "signature":"Lu+84+FEnLfs+qKT1a\/1JMm3d5maiaRDEDkPoYJeBG97GmHUkBFcZALhrcnDFAccjtihjVWy+vjzOiZJ057f66bC4eD04rVI8xkjuCKR1UL2h2kUnoLkJDmuAqO6o0pMdCzQDoTJvia1\/PsBW+8J32d\/BRhw6eeLisX16p1eVSCkucKOAP8K+VYh6YS+1T7o4fPACnDNvvUR1heaXA1R7q7iFqE30T0UzYUMZhXIGqIYRjjZlXvw22vacBnOiJiqIvtP3lQRqFUUgdTwhN9yom7RMnx8ZGeRykenWdrL0I0P\/l13zIxU8bbhhoEzeZODs+6Uq5pkEY+FIH8KEnAp9Q=="
      }
   ]
}

**Comment by radovanx** [comment]
dobry den
prosim o reakci ze zasilanych udaju nevidim kde by mohl byt problem

data to sign eet:"eetV3|20170323233029|31|test|1199.00|600.00|495.01|103.99|0.00|0.00|0.00|0.00|true"data to sign:"M1E3CB3000|5493|20170323233029|payment|card|119900|CZK|true|http://www.ventilatory-shop.cz/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&unimodul=CSOB|POST|Produkty|1|59900|Produkty|Doprava|1|60000|Doprava|(Ord.No.:5493)|CZ"{  
   "merchantId":"M1E3CB3000",
   "orderNo":"5493",
   "dttm":"20170323233029",
   "payOperation":"payment",
   "payMethod":"card",
   "totalAmount":119900,
   "currency":"CZK",
   "closePayment":true,
   "returnUrl":"http:\/\/www.ventilatory-shop.cz\/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&unimodul=CSOB",
   "returnMethod":"POST",
   "cart":[  
      {  
         "name":"Produkty",
         "quantity":1,
         "amount":59900,
         "description":"Produkty"
      },
      {  
         "name":"Doprava",
         "quantity":1,
         "amount":60000,
         "description":"Doprava"
      }
   ],
   "description":"(Ord.No.:5493)",
   "language":"CZ",
   "signature":"gfAsZWrcxsaB94n+o2YBnEBCxOd+PnAbBaNjLRmjEGPeFwe6E2eVhf2B9N+rN93wMVyZQJFRXCgyLBGPTZktILqOtGmSivQOwDRlQP5cw7Rl3UnAsP3FAMcjIMiEQtax41UpsgA92xC\/Vp8DV0ohQRQlRl2\/+IdiF0Fot9TZ1W4gv049ptZafdYvp\/ne8nKs4T+8KXSeF3R1t0By\/Jylah0fAjmT+9XPB2Kt+RPVrxsSVQS0FAWIvrn\/qPQD4AU6gNG+eOD3SWHeaauEVgge8X2w9JfbrMK1l\/GC2zGyXqvGpiZAzQ1VBM931zlqUZQq+0ZbA1yIAfDAbffHnwpCqQ==",
   "extensions":[  
      {  
         "extension":"eetV3",
         "dttm":"20170323233029",
         "data":{  
            "premiseId":31,
            "cashRegisterId":"test",
            "totalPrice":1199.00,
            "priceZeroVat":600.00,
            "priceStandardVat":495.01,
            "vatStandard":103.99,
            "priceFirstReducedVat":0.00,
            "vatFirstReduced":0.00,
            "priceSecondReducedVat":0.00,
            "vatSecondReduced":0.00
         },
         "verificationMode":true,
         "signature":"EICWChe6eI9z+2FVTukj1BrzigTvAKR9EsKyE4wZXzVE1QqLahSorGIS0uraJ8v3EWmb+C3wsPweIzSMpM\/QwCul1KKgcOB7hp44WPc03jL56HSu4bxyawgp8hYly7fT3eq0B6D4o625Ok29d+MbhRJ0fRH24oMQgGKgSMiBq02xuA25NAmpTTsI9MIIgs\/P1Xq001gwMCpDQMvBzamlf+B43aETBjfJSJjBcnBnu4zkNl6FlAa0aNa8qGR9MzfStSEELbf6UH85YUeqksTRuD6FMXjlGT768D0xmmrn61A+CGJXMX7tNYCfYkrOc+6uTeDIlWACEyWTz8taZyO\/gw=="
      }
   ]
}

**Comment by Mspisar** [comment]
Dobrý večer,

Váš požadavek jsme zaregistrovali a předali k řešení. O dalším postupu Vás bude informovat odpovědný kolega.

s pozdravem

Spisar

**Comment by vzich** [comment]
Dobrý den, 
podle vašeho příspěvku vypadá, že posíláte parametry a skládáte řetězec pro podpis korektně. Vyzkoušejte  operaci [payment/echo](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#getpost-httpsapiplatebnibranacsobczapiv17echo-), abyste si ověřil, že máte produkční klíče v pořádku.

**Comment by radovanx** [comment]
Dobry den,

Problem bude tedy v certifikatu. Nedovedu si dost dobre vysvetlit kdyz predtim fungoval - muzete prosim overit zda mame vygenerovat novy ?
Mimochodem toto volani projde v poradku:

data to sign eet: "eetV3|20170328183839|181|pokladna|54.20|0.00|44.79|9.41|0.00|0.00|0.00|0.00|true" data to sign: "M1MIPS1094|495|20170328183839|payment|card|5420|CZK|true|http://woocommerce.localhost/wp-content/plugins/WooCommerceAdapter/Reply.php?unimodul=CSOB|POST|Flat Rate...|3|3000|Flat Rate...|Posta|1|2420|Doprava|(Ord.No.:495)|1|CZ" prepared payment/init request: { "merchantId": "M1MIPS1094", "orderNo": 495, "dttm": "20170328183839", "payOperation": "payment", "payMethod": "card", "totalAmount": 5420, "currency": "CZK", "closePayment": "true", "returnUrl": "http://woocommerce.localhost/wp-content/plugins/WooCommerceAdapter/Reply.php?unimodul=CSOB", "returnMethod": "POST", "cart": [ { "name": "Flat Rate...", "quantity": 3, "amount": 3000, "description": "Flat Rate..." }, { "name": "Posta", "quantity": 1, "amount": 2420, "description": "Doprava" } ], "description": "(Ord.No.:495)", "merchantData": null, "customerId": 1, "language": "CZ", "signature": "dmx6Y8u2G3Crc5wOjK27rYYF+QxZ7/Y8knCC3PXn606Dlst/FpcE/z/4tQG4dFQm9h3RdBL4PpTMceSniY4AWeBQajlj4n2YM/gs2uAqqZbdfV7PCsQriUTlQa8BuuzJ0ycyCr9s/iRfki6TPFgkUxThAYRcLI98Zag6fHXHKYBQIv/iHbZz9tR39JsRn0P8HN7s43y4C4E09nW67krg/HH3vXmrI0nk71hSaVPB7sP3Ks6w9bmIKLUFPFarlSRuiepKJ/x1ewI9KVSU7MXth9coDS6uZkiJpXDQnHNHelAb0CtPuKEciYlkLUdjFBIwxNSlCFouxAm01IejhrXekw==", "extensions": [ { "extension": "eetV3", "dttm": "20170328183839", "data": { "premiseId": "181", "cashRegisterId": "pokladna", "totalPrice": "54.20", "priceZeroVat": "0.00", "priceStandardVat": "44.79", "vatStandard": "9.41", "priceFirstReducedVat": "0.00", "vatFirstReduced": "0.00", "priceSecondReducedVat": "0.00", "vatSecondReduced": "0.00" }, "verificationMode": "true", "signature": "ItvHevKhNOCZ2Pmfv7ePGVqt3DLUZHwEA+5wz+tse/xgIACrUpvqmht3OpNNX649U4izzTC9GjOHTE8koNPqd8e72dQP2WtXpXKYpAIi2IbZemUJe7wUPV6RMIHKkbbFT1kJaxDPJeI755XFatYAJCesLXGTUxkS8OB9JSyoPCuVOi7mgkedpuUPUWeMyTuTClrYDyYmbnfcQjxgH9l7WaATaSqdKVBTOCNVkbeWKho/J9AXKfOQ4vThJWeYLRAq23+oSZdQ4/6jBnFxI88PlQXSXk/wdT9zZI6zd5mv0Oj3iJqD80WwGH7Y1sLUybbZ4eXGxulHER6mLthZjseEHw==" } ] }

**Comment by Mspisar** [comment]
Dobrý večer,

Váš požadavek jsme zaregistrovali a předali k řešení. O dalším postupu Vás bude informovat odpovědný kolega.

s pozdravem

Spisar

**Comment by vzich** [comment]
Dobrý den, 
v aplikačním logu vidím, že sem vám vracela 400 i na metodu echo. Problém by tedy měl být v klíčích.

**Comment by radovanx** [comment]
Dobry den, dekuji za odpoved 
V pos merchant vidim pro EET ze certifikat neni overen jak tedy postupovat ?

CZ25025597	31	Není ověřen	Ano

**Comment by vzich** [comment]
Dobrý den,
stále máte chybu v podpisu, doporučuji tedy použít správné produkční klíče, případně vygenerovat nové na https://platebnibrana.csob.cz/keygen/. 
Co se týče vašeho EET certifikátu, tak nebyla kombinace vámi použitého certifikátu a DIČ ověřena na FS. Jako nejpravděpodobnější varianta neověření certifikátu bude špatně zadané DIČ. Ověřte tedy zda pro vámi uložený certifikát uvádíte správné DIČ.

**Comment by vzich** [comment]
Dobrý den,
vyřešil jste váš problém? Můžeme issue uzavřít?

**Comment by radovanx** [comment]
Dobry den,

Bohuzel cekam na spravne klice od klienta. Nicmene je otazka jak je mozne ze brana drive s certifikaty fungovala a po prechodu na eet fungovat prestala - je tedy problem v eet certifikatu ?

**Comment by vzich** [comment]
Pokud vám neprocházela metoda echo, tak se tváří jako jediná možnost chyba v klíčích. (S EET certifikátem metoda echo vůbec nepracuje).
Poté mě ještě napadá , že ještě mohli změnit způsob vytváření podpisu oproti vaší verzi bez EET, viz. [wiki](https://github.com/csob/paymentgateway/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy#jak%C3%BD-algoritmus-nastavit-p%C5%99i-vytv%C3%A1%C5%99en%C3%AD-a-ov%C4%9B%C5%99ov%C3%A1n%C3%AD-podpisu)

**Comment by radovanx** [comment]
Dobrý den,
Certifikát jsme znovu vygenerovali bohuzel porad se stejnym problemem.
Zkousel jsem s certifikatem od jineho obchodnika a byl jsem presmerovan na branu.
Prosim o overeni z Vasi strany

**Comment by radovanx** [comment]
Dobrý den, Prosím o odpověd brána s jiným certifikátem funguje ale s nově vygenerovaným ne

Děkuji

**Comment by ratajskym** [comment]
Dobrý den, zasvěťte mě prosím co Vám nefunguje? 
- testovací prostředí ?
- produkční prostředí ?

- klíče vygenerované pro platební bránu?
- EET certifikát ?

**Comment by radovanx** [comment]
Dobrý den,
Pokračuji v předešlé konverzaci. 
Nefunguje přechod na bránu vrací se 400. 
Pro produkci. S tím že brána dříve fungovala. Přechod na bránu dokonce funguje i s jiným certifikátem ale ne bohužel s nově vygenerovaným.

**Comment by ratajskym** [comment]
Když vygenerujete nový klíč pro komunikaci s platební bránou, potvrzujete tento klíč v aplikaci Posmerchant ?

**Comment by ratajskym** [comment]
Dívám se do historie a vidím, že jste generoval klíče 
Vygenerování klíčů - 16.05.17 22:27:25
Vygenerování klíčů - 17.05.17 21:39:52

K platební bráně máte nyní přiřazen klíč ze dne 16.5. ! přestože jste jej potvrdil právě 17.
Potvrzení klíčů - 17.05.17 20:43:04

Viděl bych nesoulad právě tady

**Comment by radovanx** [comment]
Dobry den,
Vygeneroval jsem jeste jednou a cekam na potvrzovaci klic problem ktery popisuji se ale stal s klicem z 16.5 - potvrzeny klic nefungoval jiny vsak ano. Jak dlouho po potvrzeni trva nez zacne byt produkcni klic aktivni u Vas ?

**Comment by ratajskym** [comment]
**Není možné**, aby Vaše brána fungovala s jiným klíčem. Pod Vaším merchant id vidím pouze 4 trx a všechny ze 17.5.5

**Comment by ratajskym** [comment]
Píšete, že jste vygeneroval nový klíč. Já však v produkčním logu tuto aktivitu nevidím. 
Opravdu generujete na produkční keygen aplikaci ? 
Opravdu generujete s merchant id M1E3CB3000 ?

**Comment by radovanx** [comment]
Dobry den,
Ano generuji pro merchand id M1E3CB3000. 
Vygenerování klíčů - 17.05.17 21:39:52 - cekam na potvrzovaci kod.
Brana fungovala na stejnem webu s jinym klicem a jinym merchand id - z toho usuzuji ze bude problem v klicich - klice jsem znovu vygeneroval 17.5 a vyzkousim s temito

**Comment by ratajskym** [comment]
Potvrzovací kód chodí okamžitě po vygenerování tzn už jej dávno musíte mít. Pokud jej nemáte, můžu Vám jej sdělit. Vzhledem k tomu, jaký zmatek v tom nyní je, doporučuji vygenerovat úplně znovu a jít krok po kroku. Projdeme to spolu.

**Comment by radovanx** [comment]
Dobry den ano prosim tedy o sdeleni kodu

**Comment by ratajskym** [comment]
OTP pro heslo ze 17.5. je 5IoTdrO1NM

**Comment by radovanx** [comment]
dobry den,
bohuzel se stejnym vysledkem. Mam tedy generovat certifikat znovu nebo to overite ?
Dekuji

**Comment by vzich** [comment]
Dobrý den, 
správnost privátního klíče který používáte, bude nejjednodušší vyzkoušet pomocí metody [echo](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#getpost-httpsapiplatebnibranacsobczapiv17echo-). Pokud se vám vrátí 400 tak používáte nesprávný privátní klíč.

**Comment by radovanx** [comment]
Ano zda se to tak ale klic je stazen z Vaseho generatoru je mozne overit u Vas ?

**Comment by vzich** [comment]
Dobrý den,
zašlete váš privátní klíč na mail servis@monetplus.cz a ověříme správnost.

**Comment by radovanx** [comment]
zaslano na mailto:servis@monetplus.cz

**Comment by vzich** [comment]
Ještě vás poprosím o vyzkoušení metody echo na produkčním prostředí, případně proveďte pokus o založení platby a uveďte řetězec, který podepisujete, ať máme aktuální data.

**Comment by vzich** [comment]
Ověřil jsem a používáte již správné klíče. Nicméně máte ještě problém v podpisu eet extension, v payloadu zasíláte "verificationMode": "true" , ale podepisujete false.

**Comment by vzich** [comment]
Vidím, že jste se již přesměroval na platební bránu s EET extension. Issue tedy zavírám.
