### ISSUE TITLE
Connecting with WooCommerce

### ISSUE THREAD

**Issue by zorronoic** [csob/paymentgateway#279]
Hello, 

I'm having slight difficulties integrating the files from https://github.com/csob/paymentgateway
into WooCommerce.

I've downloaded all of these files from this page:
https://github.com/csob/paymentgateway

and uploaded it via FTP to the wp-content - plugins folder...but it seems to have had no effect on my site and was not integrated.
I have followed the various instructions, but no luck.

Please advise.

Thank you very much.

Regards,

**Comment by aKocian** [comment]
Hello,

your request is registered as an issue and forwarded to responsible service technician. 

Regards

**Comment by vzich** [comment]
Hello,
have you also copied folder  "monetWebPay" as you can see [here](https://github.com/csob/paymentgateway/tree/master/WooCommerce%20Plugin/www)? Not just the files from the wp-content/plugins/... ? 
If you followed all instructions from our readme, which versions of WP and woocommerce do you have on your site, so we can investigate your issue? Thank you.
Best regards.

**Comment by zorronoic** [comment]
Hi vzich, 

I copied "monetWebPay" to wp-content > plugins.
I copied "WooCommerceMonetGateWay" also to wp-content > plugins.

It actually was transferred fine this time, and one new plugin showed up in my plugins, called something like "Payment Gateway for CSOB......." .. I don't remember the exact name.
Is there supposed to show up only one or two new plugins?

However, when I activated this plugin, my Wordpress became inaccessible and showed an error:
"The www..... page isn't working"
"www..... is currently unable to handle this request.
"HTTP ERROR 500"

and on my plugins page:
"The plugin WooCommerceMonetGateWay/start.php has been deactivated due to an error: Plugin file does not exist."
But this message above was shown after I deleted the plugins manually in FTP.

I was unable to access the site until I went and deleted the plugins via FTP. When I deleted both plugins, I was able to access the site again.

My WP version: 4.7.3
My WooCommerce version: 2.6.14

Hope this info helps.

Thank you very much and looking forward to your advice.

Regards,

**Comment by vzich** [comment]
Hello,
you have to copy monetWebPay folder to your www root folder (not to the wp-content plugins folder). It might caused the issue you have described. 
Best regards,
VZ.

**Comment by zorronoic** [comment]
Hi vzich, 

thanks for your advice. Do I have to upload both monetWebPay and WooCommerceMonetGateWay into the www root folder or WooCommerceMonetGateWay into plugins, and monetWebPay into root?

thanks

**Comment by vzich** [comment]
Hello,
you have to upload monetWebPay into root www folder and WooCommerceMonetGateWay into wp-content/plugins/.

**Comment by zorronoic** [comment]
Hi vzich, 

Thank you for your advice.
It worked.

Regards, 
Dario
