### ISSUE TITLE
Nefungují testovací karty na simulátoru

### ISSUE THREAD

**Issue by michalsanger** [csob/paymentgateway#28]
Zkouším váš example, jsem přesměrován na `https://iplatebnibrana.csob.cz/pay/shop.example.com` kde ale nefunguje žádná [testovací karta](https://github.com/csob/paymentgateway/wiki/Testovac%C3%AD-karty#seznam-testovac%C3%ADch-mastercard-karet).

Error přímo nad inputem je "Obchodník tuto kartu nepřijímá". Funguje pouze [ČSOB karta](https://github.com/csob/paymentgateway/wiki/Testovac%C3%AD-karty#seznam-testovac%C3%ADch-%C4%8Csob-karet)

**Comment by ratajskym** [comment]
Dobrý den, 
neznám Vaše mechant id, ale pokud používáte id založené z banky, tak Vaše nastavení kopíruje Vaše budoucí nastavení v produkci. 
- můžete požádat banku, aby Vám nastavení upravila
- můžete použít anonymní účet

**Comment by michalsanger** [comment]
Dobrý den,
Merchant Id je v example `A1029DTmM7`

**Comment by ratajskym** [comment]
Dobrý denm, 
vygenerujte si prosím vlastní merchant id. To které zmiňujete je používáno více developery a není zajištěno, že bude mít vždy stejné nastavení

https://iplatebnibrana.csob.cz/keygen/
