### ISSUE TITLE
Certifikát - Přechod ze staré GP Webpay

### ISSUE THREAD

**Issue by koblamic** [csob/paymentgateway#280]
Dobrý den,
řeším přechod z existující implementace GP Webpay, nechceme implementovat novou verzi ale zůstat u starého principu. 
Ve staré implementaci byl využit certifikát X509. Vím, že 509 může vzniknout kombinací .pfx a .crt souboru.
Nově ale https://platebnibrana.csob.cz/keygen/ poskytuje .key a .pub soubory. 

Pro mě to tedy znamená, že se musím buď nějak dostat k X509 souboru nebo změnit implementaci (se souborem ve formátu X509 v naší implementaci počítáme). 

Děkuji, za rady, případně doplnění dokumentace v této věci.

**Comment by vzich** [comment]
Dobrý den, 
pro vygenerování pfx souboru můžete využít postup řešený v issue [#26](https://github.com/csob/paymentgateway/issues/26). 
V případě dalších otázek jsem k dispozici.
S pozdravem 
VZ

**Comment by koblamic** [comment]
Paráda Děkuji.
