### ISSUE TITLE
Aktivace produkčních klíčů pro platební bránu

### ISSUE THREAD

**Issue by rjansky** [csob/paymentgateway#281]
Dobry den,
zalozili jsme pod nasim uctem druhou platebni branu (M1MIPS1206) a po testech ji chceme spustit do produkcniho prostredi. Prisel mi email, ze "aktivaci produkčních klíčů pro platební bránu proveďte v produkční aplikaci POS Merchant vložením tohoto jednorázového kódu...". Kdyz se ale prihlasim do naseho POS Merchantu, tak tam tuto novou branu nevidim a nevim kam vlozit ten aktivacni kod.

Diky
R. Jansky
Gruber Feinkost s.r.o.

**Comment by vzich** [comment]
Dobrý den,
přihlašujete se pod účtem s rolí prodejna, která je vázaná k jiné prodejně/platební bráně než kterou výše uvádíte. S vašim účtem s rolí obchodníka můžete vaší platební bránu vidět, momentálně je ale ve stavu blokovaný. Doporučuji tedy kontaktovat akceptacekaret@csob.cz, kteří mají v kompetenci odblokování účtů na posmerchantu.
