### ISSUE TITLE
Http response: 400

### ISSUE THREAD

**Issue by rotacak** [csob/paymentgateway#282]
Dobrý den,

nedaří se mi získat jakoukoliv jinou odpověď než 400 pro merchanta M1MIPS0880. Stačí stáhnout exampl v php, spustit a odpověď je 400. Když mu změním údaje na moje, nic se nezmění, odpověď je 400. 

Co dělám špatně? 

BTW: Nešlo by posílat nějakou smysluplnou response, minimálně v testovacím prostředí, ať vůbec člověk ví na čem je?

**Comment by vzich** [comment]
Dobrý den, 
na jakou url, případně prostředí, zasíláte vaše requesty? U merchantID M1MIPS0880 neevidujeme kromě generování klíčů žádnou aktivitu. 
Nahrál jste vygenerovaný privátní klíč do složky "keys" do php examplu? 

S pozdravem

VZ

**Comment by rotacak** [comment]
Example už funguje s vlastními klíči. Nemusí se po generování chvíli čekat, než to začne fungovat? Nic jsem neměnil a najednou to jde.

**Comment by vzich** [comment]
Ano, je třeba chvíli počkat. Jinak potvrzuji aktivitu na integraci.

**Comment by rotacak** [comment]
Můžete mi ještě poradit, kde vezmu správné testovací údaje pro:
premiseId
cashRegisterId
?

Proklikal jsem testovací prostředí https://iposman.iplatebnibrana.csob.cz/posmerchant snad pětkrát a nic takového jsem tam nenašel a odkaz na nápovědu zobrazí prázdnou stránku.

**Comment by vzich** [comment]
Pro parametr premiseId zadejte ID provozovny pod kterým jste na Posmerchantu aktivoval váš certifikát.  U parametru cashRegisterId je na vašem uvážení jaké ID pokladny budete zasílat na FS.

**Comment by rotacak** [comment]
V testovacím prostředí už fungovalo vše ok, na produkčním je zase chyba 400, je nějaký způsob, kde najít podrobnější informace o chybách?

**Comment by vzich** [comment]
Dobrý den, 
requesty stále posíláte na integrační prostředí (pravděpodobně požíváte již produkční klíče, tak proto dostávate 400). Nejčastější chyby naleznete ve [FAQ](https://github.com/csob/paymentgateway/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy) zde na githubu. 
Pokud budete používat EET i na produkci, tak je třeba aktivovat certifikát u vaší platební brány. Aktuálně nemáte vložen žádný certifikát.

**Comment by rotacak** [comment]
Požadavky posílám už na produkční prostředí, certifikát tam aktivovaný je a hlásí to "Unable to load EET key for merchant". Kde může být problém teď?

**Comment by vzich** [comment]
Certifikát máte registrovaný pod obchodníkem, nicméně v případě platebních bran je třeba aktivovat certifikát v nastavení platební brány. Aktivujete jej pro id provozovny, které zasíláte při založení platby v paymentInit.

**Comment by rotacak** [comment]
Tak teď už platba proběhne, ale ve vráceném FIK údaji je "ukazkovy-test-fake-test-specimenxfik-ff". Co to znamená?

**Comment by vzich** [comment]
Dobrý den, 
hlásíte tržbu na FS v ověřovacím módu. Pokud chcete tržby již evidovat v ostrém módu, tak posílejte "verificationMode":false a obdržíte již FIK po zaevidování. Viz. [specifikace](https://github.com/csob/paymentgateway/wiki/Specifikace-API-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-EET#parametry-eet-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-operace-paymentinit-paymentoneclickinit-paymentclose-a-paymentrefund)

**Comment by rotacak** [comment]
Děkuji za pomoc, už to konečně funguje. Jen bych opravil odkaz na specifikaci, kterou jsem přečetl několikrát a nikde tam není vysvětleno, co to ten ověřovací mód je (je tam jen jak se použije). To je vysvětleno jen v 38 stránkovém popisu EET zde: http://www.etrzby.cz/assets/cs/prilohy/EET_popis_rozhrani_v3.1.1.pdf Ale ta fake hláška nejde dohledat ani tam. Alespoň teď už to najde google tady :)
