### ISSUE TITLE
Prechod ostre prostredie

### ISSUE THREAD

**Issue by Pally20** [csob/paymentgateway#283]
Dobry den,

snazim se prehodit branu na ostre prostredi, vsechny testy resp. ukony som udelal jiz drive ale nedostal som sa k presunu na ostre. Podle  navodu mal by som potvrdit test na https://iposman.iplatebnibrana.csob.cz , ale tam se bohuzel nedokazu dostat,  zajimave je ze do https://posman.csob.cz se bez problemu prihlasim. MerchantId: M1MIPS0905, Kdyz chci na https://iposman.iplatebnibrana.csob.cz si poslat heslo tak to hlasi "Zadaný uživatel nebo e-mail nebyl v systému nalezen", muzete mi prosim pomoci jak mam presunout branu na ostre prostredi?

Dekuji.

**Comment by aKocian** [comment]
Dobrý den,

Zkuste při funkci zapomenuté heslo použít email **info@namastery.cz** a uživatelské jméno IČ : **05349257**
Je možné, že jste použil nesprávne uživatelské jméno nemo email. Přístup do posmerchantu máte povolený.

S pozdravem 
Alexander Kocian

**Comment by Pally20** [comment]
Zdravim, 

uz som na ostrej verzii dekuji. Ale spozoroval somjeden problem, malo by prist jednorazove heslo na aktivaciu certuifikatu do kontaktneho emailu, ale nic zatial neprislo. Muzete resp. da se poslat znova ?

Dekuji

**Comment by Mspisar** [comment]
Dobrý den,

email s heslem pro aktivaci klíče na produkčním prostředí odešel na adresu martins***@gmail.com

s pozdravem

Spisar

**Comment by Pally20** [comment]
Dobry den,

kolega ktory vlastny dany email mi tvrdi ze mu stale nic od Vas neprislo, ani v Spame... Je mozne ze email od Vas gmail blokuje ? nejaky silnejsi spam. filter ???

**Comment by joskera** [comment]
Dobrý den,
jak již psal kolega, podle logu jednorázové heslo bylo skutečně odesláno na email Vaší technické podpory a to 28.03.2017. Pokud se Vám toto heslo nedaří dohledat, můžete si produkční klíče vygenerovat opakovaně.

**Comment by Pally20** [comment]
Zdravim,

tak uz jsme prisli na to kde je problem a to je chyba emailu. Muzete mi poradit jak muzu zmenit technicky kontakt ? chyba tam jeste cislo ...89@gmail.com

Dekuji.

**Comment by joskera** [comment]
Dobrý den,
pro změnu emailu technické podpory se obraťte na adresu: akceptacekaret@csob.cz

S pozdravem

J. Oškera
