### ISSUE TITLE
EET chyba 400 - TSGSMIPS-3538 

### ISSUE THREAD

**Issue by andrewvaca** [csob/paymentgateway#284]
Dobrý den, 

dokážete mi prosím také pomoci? Stažím se implementovat rozšíření pro EET na testovacím serveru pro MerchantId M1MIPS0888, ale stále dostávám chybu 400. Bez rozšíření inicializace projde, takže z toho usuzuji, že mám chybně podpis v rozšíření. Zde je kus Extensions mého požadavku a jeho řetězec pro podpis:

"extensions":[  
      {  
         "extension":"eetV3",
         "dttm":"20170328150910",
         "data":{  
            "premiseId":11,
            "cashRegisterId":"1",
            "totalPrice":"828.00",
            "priceFirstReducedVat":"637.39",
            "vatFirstReduced":"95.61",
            "priceStandardVat":"79.17",
            "vatStandard":"15.83"
         },
         "signature":"G...w=="
      }
]
Podpis: eetV3|20170328150910|11|1|828.00|637.39|95.61|79.17|15.83

**Comment by Mspisar** [comment]
Dobrý den,

zaváděl jste certifikát a ID provozovny v Posmerchantu?

s pozdravem

Spisar

**Comment by andrewvaca** [comment]
Nezaváděl, domníval jsem se že je to potřeba pouze pro produkční prostředí, jelikož testovací nekomunikuje s API EET. Můžete mě prosím navést, kde to je? Nemohu to v Posmerchantu najít.

**Comment by Mspisar** [comment]
Dobrý den,

první musíte přímo pod názvem obchodníka zavést certifikát ( ikonka certifikátu hned první) . Poté v platebních branách přidáte ID obchodního místa ( stejná ikonka poslední v řadě ).

s pozdravem

Spisar

**Comment by andrewvaca** [comment]
Dobrý den, certifikát jsem zavedl a je vidět v seznamu certifikátů jako aktivní. Poté jsem chtěl přidat ID obchodního místa "11" ale ať zadám jakékoliv číslo do kolonky ID provozovny, zobrazí se hláška "Certifikát byl úspěšně uložen", ale v hodní tabulce "Existující certifikáty" se nic nezobrazí a brána stále vrací chybu 400.

**Comment by vzich** [comment]
Dobrý den,
máte pravdu s tím, že je chyba v podpisu extension. Posíláte rozpisy částek jako Number a ne jako string?

**Comment by andrewvaca** [comment]
Zkoušel jsem obojí, v prvním postu jsem posílal ukázku s cenami jako string, nyní jsem znovu zkusil čásky jako Number:

{  
         "extension":"eetV3",
         "dttm":"20170329162630",
         "data":{  
            "premiseId":11,
            "cashRegisterId":"1",
            "totalPrice":828,
            "priceFirstReducedVat":637.39,
            "vatFirstReduced":95.61,
            "priceStandardVat":79.17,
            "vatStandard":15.83
         },
         "signature":"U...g=="
      }

Podpis: eetV3|20170329162630|11|1|828.00|637.39|95.61|79.17|15.83

stále chyba 400 ... není to tedy tím, že stále nemám povolenou provozovnu? Viz můj poslední post.

**Comment by ratajskym** [comment]
Dobrý den, 

eet parametry posílate v jiném pořadí, než je uvedeno v dokumentaci. Následně pak tedy počítáte podpis jinak, než jej spočítá platební brána. Zkuste poslat data, jak to uvádím níže.

```
	"data": {
		"premiseId": 11,
		"cashRegisterId": "1",
		"totalPrice": 828.00,
		"priceStandardVat": 79.17,
		"vatStandard": 15.83,
		"priceFirstReducedVat": 637.39,
		"vatFirstReduced": 95.61
	},
```

**Comment by andrewvaca** [comment]
Dobrý den, děkuji za pomoc, bylo to pořadím, inicializace již proběhla. Stavěl jsem pole dynamicky podle produktů v objednávce a jelikož měl první 15%, pořadí bylo prohozené.

**Comment by ratajskym** [comment]
Děkuji za informaci. Issue tedy zavírám
