### ISSUE TITLE
Nefunkční EET na testovací platební bráně - TSGSMIPS-3552

### ISSUE THREAD

**Issue by marekkrivan** [csob/paymentgateway#285]
Dobrý den,

na testovací platební bráně Vám to vrací u EET chybu 500 po 4 hodinovém hledání chyby v mé aplikaci jsem našel chybu ve vaší... z ničeho nic zmizel přidělený EET certifikát u platebního místa a nejde přidělit, po zadání čísla provozovny to napíše "certifikát byl uspěšně ulože" ale ve výpisu existujících certifikátu se neukáže. 

Zkoušeno i na jiném scriptu na který jsem týden nešahal resp už přešel do produkce, ale test mám a tam to dělá totéž INT payment EEROR 500.

Dále v dokumentaci v sekci "Číselník návratových kódů" máte chybu dříve to bývala tabulka, nyní je to směst nenaformátovaných znaků, hodně blbě se pak ten error 500 hledal :)

**Comment by mrazekl** [comment]
Dobrý den,

certifikát je nutné přidělit pro platební bránu, nikoli obchodní místo. Dále je důležité, aby byl certifikát nahrán do integračního PosMerchantu, pokud testujete v integračním prostředí.
Poprosím Vás o ID brány, popřípadě IČO, abychom mohli zjistit více.
Děkuji.

**Comment by marekkrivan** [comment]
Dobrý den,

možná jsem to napsal špatně, psal jsem to z hlavy.  

Postup byl
1. obchodník (zde jsem zavedl nový certifikát)
2. zvolil jsme platební brány ve výpisu klikl na ikonku certifikátu a napsal ID provozovny (které je 11) následně to napsalo hlášku co jsem již psal "certifikát byl úspěšně uložen" a tedy se měl objevit v seznamu existujících certifikátů

Tohle jsem dělal 24.3.2017 a vše prošlo bez problému i platby s EET tam jsou 25. a 27.3 dnes to z ničho nic přestalo fungovat. 

Zkoušel jsem i celý postup nahrání certifikátu a přidělení certifikátu dnes znova.

ID brány je M1MIPS0934 pro IČ 02276801

Děkuji za prověření.

**Comment by ratajskym** [comment]
@marekkrivan 

Dobrý den, problém je skutečně na straně integrační platební brány. Na odstranění pracujeme, nicméně v tuto chvíli nejsem schopný odhadnout, jak dlouho to potrvá. 

Omlouváme se za způsobené komplikace

**Comment by ratajskym** [comment]
Zdá se, že problém je odstraněn. Vyzkoušejte prosím.

**Comment by marekkrivan** [comment]
Vyzkoušen celý proces a vše funguje.

Děkuji
