### ISSUE TITLE
eAPI verze 1.7 nebo EET rozšíření pro 1.6 - kde stahnout?

### ISSUE THREAD

**Issue by beeonline-cz** [csob/paymentgateway#286]
Dobrý den,

stáhl jsem si soubory z odkazu https://github.com/csob/paymentgateway ale žádný z nich asi neobsahuje odkaz na EET ve svém těle. Například, podle dokumentací https://github.com/csob/paymentgateway/wiki/Testov%C3%A1n%C3%AD-EET-a-p%C5%99echod-do-produkce

Sekce “Přechod do produkčního prostředí po otestování na iBráně”

"pomocí eAPI 1.6 nebo vyšší provést operaci payment/init s vyplněným EET rozšířením s parametrem verificationMode nastaveným na hodnotu true, provést autorizaci transakce a případné zařazení do zučtování (pokud není nastaveno automatické zařazení do zúčtování"

Žádný soubor z balíku paymentgateway-master.zip ktere se dá stáhnout z https://github.com/csob/paymentgateway/archive/master.zip neobsahuje slovo “verificationMode” nebo “eet” a není žádný odkaz v tyhle souborech na EET.

Stránka eAPI 1.7 neobsahuje žádný odkaz pro stažení https://github.com/csob/paymentgateway/wiki/eAPI-v1.7 stejně jako i odkaz https://github.com/csob/paymentgateway/tree/master/Integration%20Examples nemá žádnou verzí 1.7

Poprosím o pomoc se stažením.

Dekuji.

**Comment by ratajskym** [comment]
Dobrý den, v tuto chvíli nejsou jednotlivé příklady (ať už Java nebo PHP) ani Woocemmerce plugin připraven pro EET.
