### ISSUE TITLE
Nefunkční EET na testovací bráně

### ISSUE THREAD

**Issue by e2221** [csob/paymentgateway#287]
Dobrý den, nejspíš nemám povolené testování EET rozšíření na testovací bránu, prosím tedy o kontrolu
merchant ID: M1MIPS0840 a M1MIPS0841
Testuji zatím pro id M1MIPS0840 a vrací mi to to: payment/init failed, http response: 500

Děkuji

**Comment by Mspisar** [comment]
Dobrý den,

nemáte zavedený certifikát.

s pozdravem

Spisar

**Comment by e2221** [comment]
Certifikát jsem znovu zavedl pro merchant ID M1MIPS0840.
V POS Merchantu (testovací) jsem v záložce obchodník zavedl nový certifikát a v sekci "platební brány" jsem dal "aktivovat certifikát", zadal jsem č. provozovny 41 a zobrazilo se mi potvrzovací hláška, že certifikát byl aktivován, ale stejně mi to vrací http response: 500.

**Comment by joskera** [comment]
Dobrý den,
Váš požadavek byl předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by vzich** [comment]
Dobrý den,
problém bude v tom, že neposíláte extensions jako pole viz. [dokumentace](https://github.com/csob/paymentgateway/wiki/Specifikace-API-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-EET#p%C5%99%C3%ADklad-vol%C3%A1n%C3%AD-paymentinit-s-eet-roz%C5%A1%C3%AD%C5%99en%C3%ADm-na-eapi-v17). 
Poté ještě neformátujete částku v EET extension na dvě desetinná místa.

**Comment by vzich** [comment]
Dobrý den,
můžeme uzavřít? Založení platby s EET extension vám očividně funguje.

**Comment by e2221** [comment]
Dobrý den, ano. A děkuji za pomoc.

**Comment by ZbynekS** [comment]
Dobry den
Slo by povolit EET na testovaci brane pro merchant M1MIPS1280
Dekuji

**Comment by joskera** [comment]
Dobrý den,
pro povolení EET na plat. bráně je nejprve nutné sepsat dodatek ke smlouvě. Tedy je nutné kontaktovat banku, ideálně obchodního zástupce, se kterým jste podepisoval smlouvu k Vaší plat. bráně.

S pozdravem,
Jiří Oškera

**Comment by MythosCzech** [comment]
Dobrý den,
mám problémy s EET extension, na testovacím i produkčním serveru mi vrací brána "resultCode":900,"resultMessage":"Internal error". Používám API 1.6, a posílám extensions tag dle dokumentace, částka s desetinou tečkou.
Na testovacím serveru mi nejde nastavit certifikát u platební brány - vždy napíše uloženo, ale certifikát se nezobrazí. Na produkčním serveru mi nastavení funguje, ale brána vrací stejný stav.
MerchanID M1E3CB0880
Příklad dat můžu poslat.
Děkuji
Michal Václavík

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem

**Comment by joskera** [comment]
Dobrý den,
prověřil jsem Vaši plat. bránu a na produkci nevidím žádnou aktivitu. V integračním (testovacím) prostředí se Vám EET certifikát podařilo úspěšně vložit, ale nemáte ho aktivovaný u plat. brány viz v záložce "platební brány":
![image](https://cloud.githubusercontent.com/assets/22092117/24941511/67bfe20c-1f4b-11e7-9515-a7f8d2341112.png)
Zde stačí zadat ID provozovny, které Vám bylo přiděleno finanční správou.

S pozdravem,
Jiří Oškera

**Comment by vzich** [comment]
Dobrý den, 
problém bude v tom, že neposíláte parametr extensions jako pole. Viz. [specifikace](https://github.com/csob/paymentgateway/wiki/Specifikace-API-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-EET#p%C5%99%C3%ADklad-vol%C3%A1n%C3%AD-paymentinit-s-eet-roz%C5%A1%C3%AD%C5%99en%C3%ADm-na-eapi-v17).

**Comment by MythosCzech** [comment]
Dobrý den,

děkuji za rychlé odpovědi.

Že nemám pole v extensions jsem nějak přehlédl, moc děkuji za nakopnutí.

Co se týká toho certifikátu u platební brány, tak když tam právě chci přidat certifikát, tak zadám ID provozovny 31, dám uložit, napíše mi to "Certifikát byl úspěšně uložen", ale žádný certifikát se pod "Existujícími certifikáty" nezobrazí. Když jsem tohle zkoušel na produkčním prostředí, tak mi to fungovalo.
![image](https://cloud.githubusercontent.com/assets/27306430/24954532/1b6044a8-1f80-11e7-86d9-fa481720b97a.png)

Nicméně po opravě extension mi už init platby prošel a je v bráně ve stavu založena, tak je to snad v pořádku.
