### ISSUE TITLE
Stav platby po volání /basic/finish

### ISSUE THREAD

**Issue by lubomirpokorny** [csob/paymentgateway#288]
Pokud v peněžence MasterPass na testovacím prostředí zamítnu platbu, tak v odpovědi volání ```basic/finish``` dostávám stav ```paymentStatus=2```, čili "Platba probíhá". 

Bude chování v produkčním prostředí stejné? Nebo se obecně nelze spolehnout na návratovou hodnotu ```basic/finish```? Při zpracování volání ```callbackUrl``` na straně eshopu by bylo dobré znát skutečný stav platby, aby zákazník po zavření peněženky věděl, zda platba skutečně proběhla či nikoliv.

Děkuji za odpověď,
Pokorný

**Comment by mjanek** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem
Miroslav Janek

**Comment by dmarek** [comment]
Ano, chovani v produkcnim prostredi bude stejne. Volanim /masterpass/basic/finish se pouze "nastartuje" dokonceni transakce - predavaji se data z MasterPass (platebni brana si vola server MC a ziskava udaje pro autorizaci), nasledne platebni brana odesila pozadavek na autorizaci issuerske bance. Pro ziskani vysledku autorizace musite provolat payment/status.

**Comment by dmarek** [comment]
Vyse uvedene plati pro pripad, kdy klient platbu potvrdi. 
Pri zamitnuti trx v penezence se pri volani /masterpass/basic/finish ihned vyhodnocuje mpstatus a transakce se zamita, v response na volani /masterpass/basic/finish se vraci paymentStatus 6 (declined). Nicmene proverime chovani na ibrane ...

**Comment by dmarek** [comment]
jak jsem psal vyse, pri zamitnuti transakce v penezence se pri naslednem volani /masterpass/basic/finish

```
{
  "merchantId":"M1MIPSxxx",
  "payId":"03fa86c1aa1beCD",
  "dttm":"20170404143001",
  "callbackParams": {
    "mpstatus":"failuire",
    "oauthToken":"0041642176572335673783653560660078384666"
  },
  "signature":"c2..."
}
```

transakce zamitne, brana vrati reponse

```
{
  "dttm": "20170404145211",
  "signature": "PNVgLVT...",
  "payId": "03fa86c1aa1beCD",
  "resultCode": 270,
  "resultMessage": "MasterPass canceled by user",
  "paymentStatus": 6
}
```

**Comment by dmarek** [comment]
zkuste prosim jeste jednou a pripadne pridejte payId, proverime

**Comment by lubomirpokorny** [comment]
Ano, chová se tak, jak popisujete. 

Pokud zvolím "Cancel" v simulátoru peněženky, tak je platba okamžitě _zamítnuta_. Případ, který popisuji výše, odpovídá přiloženému obrázku - vyberu MC kartu, která bude zamítnuta a potvrzuji pomocí "Continue". 

![image](https://cloud.githubusercontent.com/assets/26252223/24659667/a627e64c-194d-11e7-856d-aca8f158deaa.png)

Můžete prosím nastínit, jaký podíl plateb končí neúspěchem?

**Comment by dmarek** [comment]
Ano, jsou to dva odl;isne pripady, pomoci tlacitka "cancel" je simulovana uzivatelem zrusena (nepotvrzena, nedokoncena) MasterPass transakce (tam je transakce ihned zamitnuta).

Pokud vyberete kartu ***0815 a potvrdite pres "Continue", simuluje se stav, kdy uzivatel dokoncil vyber/potvrdil platbu v MasterPass penezence, zamitnuti je az na urovni autorizace transakce u vydavatele karty (napr. na uctu ke kteremu je dana karta navazana je malo prostredku apod, karta je u issuera blokovana apod). V tomto pripade plati, co jsem popisoval v prvnim komentari, je nutne vyckat na dokonceni autorizace a volat payment/status pro zjisteni stavu transakce.

v pripade mpass@shop mate nicmene moznost v pripade zamitnuti transakce nabidnout zakaznikovi moznost zaplatit jinak ...

**Comment by lubomirpokorny** [comment]
Jak dlouho obyčejné trvá autorizace platby? Po zavření peněženky je
uživateli potřeba indikovat úspěch či neúspěch.

Dne 4. 4. 2017 3:56 PM napsal uživatel "Daniel Marek" <
notifications@github.com>:

**Comment by dmarek** [comment]
autorizace trvá zpravidla několik málo sekund,  Doporučená doba 2-3 vteřiny po volání /masterpass/basic/finish, pokud je stav platby stále 2 (platba probíhá), doporučujeme periodicky volat co 5 vteřin (celková doba autorizace závisí na zpracování požadavku s systémech VISA/MC a může být v opravdu nejhorším případě až 60 vteřin).

**Comment by lubomirpokorny** [comment]
Díky za doplnění informací. Věřím, že by bylo užitečné i pro ostatní implementátory toto doplnit do wiki..:-)
