### ISSUE TITLE
400 při pokusu o spojení - TSGSMIPS-3591

### ISSUE THREAD

**Issue by kevujin** [csob/paymentgateway#289]
Dobrý den,
pro platební bránu M1MIPS0335 se mi nedaří spojit se s testovacím prostředím. I při pokusu o echo dostávám 400, což předpokládám, že je problém s certifikátem. Ovšem netuším, kde problém může být. Dokonce jsem i vygeneroval dnes nové, veřejný jsem nahrál na gateway, vlastně jsem postupoval stejně jako u M1MIPS0156, která funguje (pokud u požadavku zaměním privátní klíč a merchantId za to fungující, požadavek proběhne korektně).
Můžete mi, prosím, pomoci?
Díky
Jan Řehák

**Comment by joskera** [comment]
Dobrý den, 
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by ratajskym** [comment]
Dobrý den, 

vidím, že jste generoval nové klíče na integračním prostředí 05.04.17 16:57:56

I v čase 20:49:32,774 však máte špatný podpis. Píšete, že jste privátní klíč vyměnil. V tuto chvíli netuším, jak Vám pomoci, ale bude to na Vaší straně. Můžete nasdílet řetězec, který podepisujete?

**Comment by kevujin** [comment]
Dobrý den,
děkuji za reakci.

Pro generování podpisu (pro celkovou komunikaci s bránou) používám 
knihovnu od Ondry Koupila (poslední verzi).

Můžete, prosím, ověřit, zda máte zaveden veřejný klíč, který posílám v 
příloze? Protože klíče jsem generoval v 16:00 (podle času vytvoření 
souboru).

Děkuji za Váš čas
Jan Řehák

Zde trace log

2017-04-05 20:49:22  ::1             Signing string 
"M1MIPS0335|20170405204922" using key 
D:\web\tgi\tgiclub\www\application/../data/keys/rsa_M1MIPS0335.key, 
result: 
aAEtgs3Qn0xFwXuuGFsCST0+szfyRAdSRNqxK1Q1zwueIB7NVkFYdyu0grthI6cARbYF4V3XX6eHT3pL1L6x7W7uWWSpruQBYbqgKRQ/MMw9UG/jzJ7+bLH/kdg03Dya1gqZrSOmTavk67+SDWxj97x9BpG1Zx0tbAr8/Ayf5FhgTkKpfcJ+2g9iR4uVKCG6yHT0loXyPyfDrX54O+QbwBSAKfQ7CQ40vflUen+cjOj/imt8q9depYI/aSlM+GoDEYqCiH1F236q5cDFVezLBSwRGIzjYlk2tXf6dZFEtULBXHp1EqRLICPeeJvKu1dbKHH3DwDbhnVjl8X2rzLt0Q==
2017-04-05 20:49:22  ::1             Will send request to method echo
2017-04-05 20:49:22  ::1             URL to send request to: 
https://iapi.iplatebnibrana.csob.cz/api/v1.7/echo
2017-04-05 20:49:22  ::1             JSON payload: 
{"merchantId":"M1MIPS0335","dttm":"20170405204922","signature":"aAEtgs3Qn0xFwXuuGFsCST0+szfyRAdSRNqxK1Q1zwueIB7NVkFYdyu0grthI6cARbYF4V3XX6eHT3pL1L6x7W7uWWSpruQBYbqgKRQ\/MMw9UG\/jzJ7+bLH\/kdg03Dya1gqZrSOmTavk67+SDWxj97x9BpG1Zx0tbAr8\/Ayf5FhgTkKpfcJ+2g9iR4uVKCG6yHT0loXyPyfDrX54O+QbwBSAKfQ7CQ40vflUen+cjOj\/imt8q9depYI\/aSlM+GoDEYqCiH1F236q5cDFVezLBSwRGIzjYlk2tXf6dZFEtULBXHp1EqRLICPeeJvKu1dbKHH3DwDbhnVjl8X2rzLt0Q=="}
2017-04-05 20:49:22  ::1             API response:
2017-04-05 20:49:22  ::1             Failed: returned HTTP code 400

------ Original Message ------

**Comment by ratajskym** [comment]
Tohle je Váš veřejný klíč zavedený na straně integrační platební brány
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt87ULVUfdza2ukcuCLlH
G9s4vbCb0wzEgEn6o0lD2kicyO6gtsYdiAR7hwvHlXQRWQ6hbCvLXdJdE+sOaRCO
kDoppLBNPWx9K7EvczoBSjLMYInM4k4vRkYlJISKuf15i4K+Pfk3W8STGy2MulNs
c7wpX+ZxFIP0d4cAQaIvzf9XZ7F6/IfEN3/P8+OomIN2Q/pzKPMEE56OgfHLjIqN
vHrmrrM66xalCNt0wIU8CHyhJGPq84+duqadwIHPRr0uvcrtwHlhRW4vZWc1yG3M
k4Hj0LTojPujApcYnbAmoIlOPmDsMa6Z32tMKY2YOH9C9j+/tiksVSgSjd5MmBuu
KQIDAQAB
-----END PUBLIC KEY-----
```

**Comment by kevujin** [comment]
Ten odpovídá - to by mělo být správně. Nenajdete v logu konkrétní důvod 
té chyby 400? Např. že se nepodařilo dekódovat ten řetězec?

------ Original Message ------

**Comment by ratajskym** [comment]
Konkrétní chyba je (bohužel) špatný podpis. Můžete mi poslat Váš privátní klíč, kterým tyto zprávy podepisujete ? Vyzkouším tu echo zprávu podepsat sám .

**Comment by kevujin** [comment]
V příloze je onen privátní klíč, zkuste, prosím.

------ Original Message ------

**Comment by ratajskym** [comment]
@kevujin Pošlete mi ten klíč prosím na adresu servis@monetplus.cz

**Comment by ratajskym** [comment]
Zkontroloval jsem veřejný klíč u merchantů M1MIPS0335 a M1MIPS0156. Tento veřejný klíč je v obou případech stejný. Z toho usuzuji, že jste klíč pro M1MIPS0335 uploadoval ručně. Privátní část, kterou jste mi poslal do emailu, ale NEODPOVÍDÁ těmto veřejným částem.

**Comment by kevujin** [comment]
Díky za pomoc, záměna klíčů mě nenapadla, zvláště, když se ukládaly z 
java aplikace se svým jménem (rsa_M1MIPS0335.pub) navíc do jiné složky. 
Odpovídá i časové razítko souboru, tudíž odpadá i možnost, že bych si to 
nějak přepsal.
Vygeneroval jsem vše znovu a znovu nahrál a nyní již spojení funguje.
Velice děkuji za vyřešení problému.

------ Original Message ------

**Comment by kevujin** [comment]
Ještě bych Vás poprosil o dotaz, zda je integrační prostředí napojeno na playground EET, díky.

**Comment by vzich** [comment]
Dobrý den,
integrační prostředí není přímo napojeno na EET, nicméně odpovědi na ibráně formátově odpovídají skutečným datům z FS. Na ibráně si můžete odzkoušet jednotlivé stavy pomocí vhodně zvoleného parametru cashRegisterId, viz. [dokumentace](https://github.com/csob/paymentgateway/wiki/Testov%C3%A1n%C3%AD-EET-a-p%C5%99echod-do-produkce#testov%C3%A1n%C3%AD-%C5%BEivotn%C3%ADho-cyklu-tr%C5%BEby)
