### ISSUE TITLE
Nedorazily jednorázové kódy pro potvrzení klíčů

### ISSUE THREAD

**Issue by jirisalek** [csob/paymentgateway#29]
Odeslal jsem klíče platební brány po vygenerování do banky přes aplikaci. Ze 4 aplikací dorazil jediný. Zkoušel jsem opakovaně generovat klíče, poslat a opět nic. Ve spamu to není! Je alternativní metoda, jak získat jednorázový kód např. SMS? Čísla požadavků sdělím na vyžádání. Díky

**Comment by ratajskym** [comment]
Dobrý den, 

alternativní metoda existuje, ale napřed bychom rádi diagnostikovali důvod neodeslání OTP. Vzhledem k citlivým údajům, které potřebujeme bude lepší, když toto nebudeme řešit zde na Githubu.  Napište prosím na platebnibrana@csob.cz
- uveďte své merchant id, pro které jste klíče generoval
- prostředí, kde jste je generoval (testovací, produkční)
- odkaz na toto issue
