### ISSUE TITLE
Odpověď 404

### ISSUE THREAD

**Issue by beeonline-cz** [csob/paymentgateway#290]
Dobrý den,

pro tento dotaz payment/init mám HTTP 400, což asi je špatný podpis ale furt nemohu zjistit co to je.

Merchant: M1MIPS0325

generoval jsem podpis s heslem, bez hesla, už zkusil jsem spoustu variant, včetně dvou různých certifikátů, ale je to furt HTTP 400

prepared payment/init request:
{
    "merchantId": "M1MIPS0325",
    "orderNo": "123456",
    "dttm": "20170407153831",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 100,
    "currency": "CZK",
    "closePayment": "false",
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 100,
            "description": "Lenovo ThinkPad Edge E540..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 0,
            "description": "PPL"
        }
    ],
    "description": "Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
    "merchantData": null,
    "customerId": "1234",
    "language": "CZ",
    "signature": "============",
    "extensions": [
        {
            "extension": "eetV3",
            "dttm": "20170407153831",
            "data": {
                "premiseId": 1,
                "cashRegisterId": "test",
                "totalPrice": 1.00
            },
            "verificationMode": true,
            "signature": "============"
        }
    ]
}

data to sign:
"M1MIPS0325|123456|20170407153831|payment|card|100|CZK|false|https://vasobchod.cz/gateway-return|POST|Shopping at ...|1|100|Lenovo ThinkPad Edge E540...|Shipping|1|0|PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|1234|CZ"

EET data to sign:
"eetV3|20170407153831|1|test|1.00|true"

Otázka zní: co může být důvodem chybného podpisu? Jsou řetězce na podpis v pořádku? Něco dalšího?

Děkuji.

**Comment by mjanek** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by mjanek** [comment]
Ano, vidím zde chybu v podpisu. Zkontrolujte, zda si opravdu generujete klíče pro produkční prostředí na https://platebnibrana.csob.cz/keygen/ a veřejný klíč banky dostupný na githubu. https://github.com/csob/paymentgateway/tree/master/keys.

**Comment by beeonline-cz** [comment]
Dobrý den,

používám certifikát .key, kterým podepisuji označené výš řetězce. Tento soubor .key jsem si vygeneroval ze souboru .p12, který je úspěšně nahrán a nastaven na obchodní místa. Každopádně, podepisování stále nefunguje a mám chybu 400 s použitím hesla použitého pro p12 pro podepisování nebo bez hesla - jednou nefunguje.

Certifikát, který mám, je správným.

Poprosím o pomoc. Myslím si, že by to bylo 100krát rychleji vyřešit problém zavoláním někomu na telefon nebo probráním přes Skype. Děkuji.

**Comment by ratajskym** [comment]
@beeonline-cz Vyzkoušejte prosím nejdříve metodu ECHO, která je implementačně nejjednodušší a zároveň jednoznačně identifikuje špatné klíče.

**Comment by beeonline-cz** [comment]
Podle logiky dokumentací https://github.com/csob/paymentgateway/wiki/eAPI-v1.7, musel bych prostě změnit payment/init na echo a nahrát tam data. Furt mám 400. chybu. Možná, dělám něco špatného?

`data to sign:
"M1MIPS0325|123456|20170410101302|payment|card|100|CZK|false|https://vasobchod.cz/gateway-return|POST|Shopping at ...|1|100|Lenovo ThinkPad Edge E540...|Shipping|1|0|PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|1234|CZ"

EET data to sign:
"eetV3|20170410101302|1|M1VRFI2740|1.00|true"

prepared /echo/ request:
{
    "merchantId": "M1MIPS0325",
    "orderNo": "123456",
    "dttm": "20170410101302",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 100,
    "currency": "CZK",
    "closePayment": "false",
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 100,
            "description": "Lenovo ThinkPad Edge E540..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 0,
            "description": "PPL"
        }
    ],
    "description": "Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
    "merchantData": null,
    "customerId": "1234",
    "language": "CZ",
    "signature": "hCQsJPtcjVfx1GobfVknh9+5pg5QoMPDzV5F8phNYjDLS0QCYUCVcTmggPJUf3DeABoxMo4ZKwx9ptlOhss1o9rbgYzQQXN5luiEIaSgWAbdtMu3R3Rcj+ubxkzhWHSdGI28voUQV4zraqcG3srvWA38tkoPdo9SsjNa7yFv2Uc/K7w176zLDc/AyWRzSvSFlyXQyqtBxBHpkBdnNgH/48VyDM6uyBanPm3ViXaFFxBXEHJbz9Pt/AzS5P3ye0pAANHTyr6CZxEjhkRuO3bfXfPLmtcAi92RuwUagJoxESBR+qzCCv1INAn8VCOvLIWFbX465xr6ae3usCXrO4e7Yg==",
    "extensions": [
        {
            "extension": "eetV3",
            "dttm": "20170410101302",
            "data": {
                "premiseId": 1,
                "cashRegisterId": "M1VRFI2740",
                "totalPrice": 1.00
            },
            "verificationMode": true,
            "signature": "F1TuLQD9RWcpm0wwtc99Q03Fwecevo5Kh3MZ7OtSQlhVQIApRPw37Fz/L56DNqeNxUgon5vx8MdW+cFVS6MHKQJU9jpaD8gE36tr4yKWcJnwVu26nEaZ1jCul5xUaeJ2NJWKBLNjcnObiup3T8pu2JF8xu37ZwTEz0A27sjo1YI4QYMVruqtbs4QecKwbyfLAKgfzx3nFG/9bozFZw0n7eghQzFc3+HiaNVxKPTZ9V9+i2+zROblCQb2b6lOQgSgNpXqYbpdTn/VJDW2lxcLkS/EwUHMijSRn8QCSOzF3wCWVMsYkwhemvRi8FToHrJ5kL1MPDcQ0qh8FCeKEVCPnw=="
        }
    ]
}`

Ve výstupu mám

/echo/ failed, http response: 400 HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 10 Apr 2017 10:13:03 GMT
Content-Length: 0
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Expires: 0
Pragma: no-cache
Set-Cookie: BIGipServerasors_platebnibrana.csob.cz_6443_pool=8zfy8hvBSfjwfN32cApHA3ipB5UJ57Qwv4QikM3GZ8hBU7qIWBdbo8/V0Ed29hM+HDeWOHRfnQ/c0qUAAAAB; path=/; Httponly; Secure

**Comment by ratajskym** [comment]
Ano, posíláte to celé špatně. Operace echo je [zde](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#echo-operation) a vidíte, že obsahuje pouze dva parametry a to merchantId a dttm + samozřejmě podpis.

Zkusme na to jít postupně. Takhle těžko hledat kde přesně v postupu děláte chybu. Pochopil jsem, že máte vlastní .key. Uploadoval jste na platební bránu k němu odpovídající veřejný klíč ?

**Comment by beeonline-cz** [comment]
Dobrý den,

nahrál jsem p12 přes Obchodník->Obchodník

![image](https://cloud.githubusercontent.com/assets/26108809/24857786/d10e0f58-1de9-11e7-9885-0ffd5de4b301.png)

![image](https://cloud.githubusercontent.com/assets/26108809/24857845/fdab8734-1de9-11e7-8ef7-c219fcddbb0f.png)

Je to jediné místo, kde jsem našel, kde mohu nahrát SSL certifikát.

Pak jsem aktivoval všecho na obchodmích místech

![1](https://cloud.githubusercontent.com/assets/26108809/24858035/c324eff0-1dea-11e7-9281-d301a941bf29.jpg)

![image](https://cloud.githubusercontent.com/assets/26108809/24858067/eb7989f2-1dea-11e7-9b32-4c176665143a.png)

![image](https://cloud.githubusercontent.com/assets/26108809/24858087/00c1962e-1deb-11e7-9358-e3c950ccaa86.png)

+ aktivoval jsem v Platební Brány -> Platební Brány 

![image](https://cloud.githubusercontent.com/assets/26108809/24858336/3b5cd522-1dec-11e7-9e91-55d31cc21328.png)


Pak pomoci openssl jsem si z tohoto .p12 vygeneroval soubor .key, který používám pro podpisování dat a používám váš příklad v.1.6 kam přidal ještě blok pro zpracování dat pro rozšíření.

Řetězec pro podpisování platebních dat je standardní z v 1.6, řetězec pro EET je "můj" (viz příklady výš).

setup.php je

$url = "https://api.platebnibrana.csob.cz/api/v1.6";
$publicKey = "mips_platebnibrana.csob.cz.pub";

$merchantId	= "M1MIPS0325";

$privateKey		= "790346228.key";
$privateKeyPassword	= "xxxxxx";
$privateKeyEET		= "790346228.key";
$PrivateKeyPasswordEET	= "xxxxxx";

$premiseId	= 1; //ID Provozovny
$cashRegisterId	= "M1VRFIxxxx";

Děkuji za pomoc

**Comment by ratajskym** [comment]
Odprostěte na chvíli svou mysl od EET. K tomu, abyste udělal echo test nic z toho co píšete nepotřebujete. 
1. - potřebujete klíč pro podepisování požadavků z eshopu na platební bránu
1.1. - buď si je vygenerujete zde https://iplatebnibrana.csob.cz/keygen/
1.2. - nebo máte svůj klíč a ten uploadujete na tom samém linku

2. privátní klíčem podepíšete řetezec a odešlete na platební bránu

Jakmile se Vám podaří toto, přejdeme k dalšímu kroku. Souhlasíte ?

**Comment by beeonline-cz** [comment]
ok, podle obrázků, bylo to tak:

![image](https://cloud.githubusercontent.com/assets/26108809/24859041/1981d42c-1def-11e7-8405-608533eff4c3.png)

![image](https://cloud.githubusercontent.com/assets/26108809/24859059/3063dcb2-1def-11e7-82aa-11fd6de9c8e2.png)

**Comment by beeonline-cz** [comment]
Ok vygeneroval jsem všechno. Stáhl si soubory a nahrál.

![image](https://cloud.githubusercontent.com/assets/26108809/24859183/c648ad48-1def-11e7-8c87-1cad9a0b030e.png)

Podepsal jsem každý řetězec souborem "rsa_M1MIPS0325.key", poslal na payment/init a je to znovu HTTP 400  :-(

data to sign:
"M1MIPS0325|123456|20170410111453|payment|card|100|CZK|false|https://vasobchod.cz/gateway-return|POST|Shopping at ...|1|100|Lenovo ThinkPad Edge E540...|Shipping|1|0|PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|1234|CZ"

EET data to sign:
"eetV3|20170410111453|1|M1VRFI2740|1.00|true"

prepared /payment/init/ request:
{
    "merchantId": "M1MIPS0325",
    "orderNo": "123456",
    "dttm": "20170410111453",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 100,
    "currency": "CZK",
    "closePayment": "false",
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 100,
            "description": "Lenovo ThinkPad Edge E540..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 0,
            "description": "PPL"
        }
    ],
    "description": "Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
    "merchantData": null,
    "customerId": "1234",
    "language": "CZ",
    "signature": "ZAhK/aV6S2+ZRI7ozp/1QpKamZHq27n4uxJo097Wz2q/CnCQIJQBejqCY6A4otgMdke46hYYoyi77sCY0hHtoDJIlngXygLlMQWoGQGfnFZd0TbDfI6OErI+buOtbp5pM32GoBMSK6P7krxdOuGywg1dS5uTC/fd1XV0KhvAMJ1Opj/D88HDgoT84O63dOEj97uFdkkHTpfblsTu2KkJjtr0g/vlxzMdtUpc1gzQksWOzSbvb5UhzoQp+MXOaBCDy2bje0bspTf5LpN6bo7PWD93WzkDid2WfKb75m/j7UQXHtSGr9ex+i3vNHuKM+bqOuHa24iXG4mLst93kdhJYg==",
    "extensions": [
        {
            "extension": "eetV3",
            "dttm": "20170410111453",
            "data": {
                "premiseId": 1,
                "cashRegisterId": "M1VRFI2740",
                "totalPrice": 1.00
            },
            "verificationMode": true,
            "signature": "PgVy0oXJy56QfJ5iGhUoxy7We8oJcTwHyiqprXxYbvi9d6r4WnZKE//0OleXnZ30UGUkothcW3fslE5rwqABNbi2xqiLeBWJ1a4KDRflOkewICnfnFx+RB3X9h2357A4xgkZohCtKc8s136Q6nvVOxHJUbqqgznYB/cDHsOQooVJ/qk2E93nLmTnmbtRu/M+0MQDnAYG0Pi8Q5kzKXVpNK/csIDx4XA1SfE5jevoJKbjwZBuaYubnfEEZgXk9FABOW6IF+Gntm1HR/uRRRJW+xMAnJVlrzRObSnf/hxz9WxAn9a6G25dybpevzEz3naxMMVvaIe1cBn6qHP/Su2Ipw=="
        }
    ]
}

**Comment by ratajskym** [comment]
Když jsem psal řetězec, měl jsem na mysli ECHO. Je to triviální na implementaci a zároveň nejrychlejší metoda jak ověřit správnost klíčů.

Ještě mi vysvětlete, proč to zkoušíte proti produkčnímu prostředí a ne proti testovacímu?

**Comment by beeonline-cz** [comment]
ok udělám echo teď

**Comment by beeonline-cz** [comment]
ok ověřil jsem několikrát různými způsoby, stejně 400

<?php

require_once ('logger.php');
require_once ('crypto.php');
require_once ('setup.php');

$sData = '{
  "merchantId":"M1MIPS0325","dttm":"20170410101302","signature":"hCQsJPtcjVfx1GobfVknh9+5pg5QoMPDzV5F8phNYjDLS0QCYUCVcTmggPJUf3DeABoxMo4ZKwx9ptlOhss1o9rbgYzQQXN5luiEIaSgWAbdtMu3R3Rcj+ubxkzhWHSdGI28voUQV4zraqcG3srvWA38tkoPdo9SsjNa7yFv2Uc/K7w176zLDc/AyWRzSvSFlyXQyqtBxBHpkBdnNgH/48VyDM6uyBanPm3ViXaFFxBXEHJbz9Pt/AzS5P3ye0pAANHTyr6CZxEjhkRuO3bfXfPLmtcAi92RuwUagJoxESBR+qzCCv1INAn8VCOvLIWFbX465xr6ae3usCXrO4e7Yg=="
}';

$ch = curl_init ( $url . NativeApiMethod::$echo );
curl_setopt ( $ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt ( $ch, CURLOPT_CUSTOMREQUEST, "POST" );
curl_setopt ( $ch, CURLOPT_POSTFIELDS, $sData );
curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
curl_setopt ( $ch, CURLOPT_HEADER, true );
curl_setopt ( $ch, CURLOPT_HTTPHEADER, array (
		'Content-Type: application/json',
		'Accept: application/json;charset=UTF-8'
));

$result = curl_exec ( $ch );

print $result;

if(curl_errno($ch)) {
	echo (NativeApiMethod::$echo).' failed, reason: ' . htmlspecialchars(curl_error($ch));
	return;
}

$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
if($httpCode != 200) {
	echo (NativeApiMethod::$echo).' failed, http response: ' . htmlspecialchars($httpCode) . ' ' . $result;
	return;
}

curl_close($ch);

**Comment by beeonline-cz** [comment]
require_once ('logger.php');
require_once ('crypto.php');
require_once ('setup.php');

$sData = '{
  "merchantId":"M1MIPS0325","dttm":"20170410101302","signature":"hCQsJPtcjVfx1GobfVknh9+5pg5QoMPDzV5F8phNYjDLS0QCYUCVcTmggPJUf3DeABoxMo4ZKwx9ptlOhss1o9rbgYzQQXN5luiEIaSgWAbdtMu3R3Rcj+ubxkzhWHSdGI28voUQV4zraqcG3srvWA38tkoPdo9SsjNa7yFv2Uc/K7w176zLDc/AyWRzSvSFlyXQyqtBxBHpkBdnNgH/48VyDM6uyBanPm3ViXaFFxBXEHJbz9Pt/AzS5P3ye0pAANHTyr6CZxEjhkRuO3bfXfPLmtcAi92RuwUagJoxESBR+qzCCv1INAn8VCOvLIWFbX465xr6ae3usCXrO4e7Yg=="
}';

$ch = curl_init ( $url . NativeApiMethod::$echo );
curl_setopt ( $ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt ( $ch, CURLOPT_CUSTOMREQUEST, "POST" );
curl_setopt ( $ch, CURLOPT_POSTFIELDS, $sData );
curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
curl_setopt ( $ch, CURLOPT_HEADER, true );
curl_setopt ( $ch, CURLOPT_HTTPHEADER, array (
		'Content-Type: application/json',
		'Accept: application/json;charset=UTF-8'
));

$result = curl_exec ( $ch );

print $result;

if(curl_errno($ch)) {
	echo (NativeApiMethod::$echo).' failed, reason: ' . htmlspecialchars(curl_error($ch));
	return;
}

$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
if($httpCode != 200) {
	echo (NativeApiMethod::$echo).' failed, http response: ' . htmlspecialchars($httpCode) . ' ' . $result;
	return;
}

curl_close($ch);

**Comment by ratajskym** [comment]
Potvrdil jste tento nově vygenerovaný klíč v aplikaci Posmerchant? 
Proč si to napřed nevyzkoušíte na testovacím prostředí ?

**Comment by beeonline-cz** [comment]
require_once ('logger.php');
require_once ('crypto.php');
require_once ('setup.php');

$sData = '{
  "merchantId":"M1MIPS0325","dttm":"20170410101354","signature":"'.sign ( "M1MIPS0325|20170410101354", $privateKey, $privateKeyPassword, "payment/init data to sign:").'"
}';

//$ch = curl_init ( $url . NativeApiMethod::$echo );
$ch = curl_init ( $url . NativeApiMethod::$echo );
curl_setopt ( $ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt ( $ch, CURLOPT_CUSTOMREQUEST, "POST" );
curl_setopt ( $ch, CURLOPT_POSTFIELDS, $sData );
curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
curl_setopt ( $ch, CURLOPT_HEADER, true );
curl_setopt ( $ch, CURLOPT_HTTPHEADER, array (
		'Content-Type: application/json',
		'Accept: application/json;charset=UTF-8'
));

$result = curl_exec ( $ch );

print "Private key: ".$privateKey."\r\n";

if(curl_errno($ch)) {
	echo (NativeApiMethod::$echo).' failed, reason: ' . htmlspecialchars(curl_error($ch));
	return;
}

$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
if($httpCode != 200) {
	echo (NativeApiMethod::$echo).' failed, http response: ' . htmlspecialchars($httpCode) . ' ' . $result;
	return;
}

curl_close($ch);

**Comment by beeonline-cz** [comment]
Private key: rsa_M1MIPS0325.key
/echo/ failed, http response: 400 HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 10 Apr 2017 12:00:49 GMT
Content-Length: 0
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Expires: 0
Pragma: no-cache
Set-Cookie: BIGipServerasors_platebnibrana.csob.cz_6443_pool=shqqIhan5MhVBxn2cApHA3ipB5UJ57Ne8SHEvrb2sRdwCW4o2Y9IeoAefGyz63tAZqFKWMo32Uy3q9EAAAAB; path=/; Httponly; Secure

**Comment by ratajskym** [comment]
Vaše zvěřejněné kódy měly být odpovědí na kterou z následujících otázek ?

Potvrdil jste tento nově vygenerovaný klíč v aplikaci Posmerchant?
Proč si to napřed nevyzkoušíte na testovacím prostředí ?

**Comment by ratajskym** [comment]
Na testovacím prostředím
- není potřeba vygenerované klíče potvrzovat v PosMerchantu

V produkčním prostředí
- je potřeba vygenerované klíče potvrdit v PosMerchantu

**Comment by beeonline-cz** [comment]
Děkuji mockrát za vysvětlení, ale v posmerchant nikde nevidím, kde je potvrdít.

![image](https://cloud.githubusercontent.com/assets/26108809/24860887/ea4e1942-1df6-11e7-9cca-04bf518ce17b.png)

Teď se přepnu do testovacího prostředí a podívám se jak to vypadá s testovacím.

**Comment by ratajskym** [comment]
Protože jste v sekci, kde řešíte certfikát pro EET.

Konkrétní nastavení Vašeho merchant id (klíče, loga, barevné schéma.. ) je v sekci Platební brány.

**Comment by beeonline-cz** [comment]
Je to tady?

![image](https://cloud.githubusercontent.com/assets/26108809/24861165/fa5b4098-1df7-11e7-9648-9c0fa00e8b52.png)

**Comment by ratajskym** [comment]
![image](https://cloud.githubusercontent.com/assets/9882463/24861286/8b662800-1df8-11e7-9570-e9fc61905e55.png)

**Comment by beeonline-cz** [comment]
aha, díky

**Comment by ratajskym** [comment]
Klíče - slouží pro podepisování požadavků při komunikaci s platební bránou.
Certifikát EET - slouží pro komunikaci platební brány s finanční správou. Vy s tímto certifikátem na úrovni eshopu nijak neoperujete

**Comment by beeonline-cz** [comment]
OK payment/init dal mí "resultCode":0,"resultMessage":"OK","paymentStatus":1 v testovací verzí

Teď otázka zní:

budu potřebovat nahrát starý .p12 od majitele učtu , asi po nahrání budu musel zeptat se ho o potvrzovacím kódu z emailu?

Děkuji.

**Comment by ratajskym** [comment]
Payment init Vám nestačí. Udělejte i payment proces. Projděme prostě samotnou transakcí a teprve následně EET.

**Comment by beeonline-cz** [comment]
Ale ohledně nahrání starého certifikátu - budu muset potvrdit kódem z emailu po jeho nahraní, ano?

**Comment by ratajskym** [comment]
Testovací prostředí
- po vygenerování klíčů nic nepotvrzujete, klíče jsou potvrzeny automaticky

Produkční prostředí
- po vygenerování klíčů Vám přijde na email heslo, kterým tyto nově vygenerované klíče v aplikaci Posmerchant aktivujete

Certifikát pro EET nikde nepotvrzujete.

**Comment by beeonline-cz** [comment]
Děkuji.

**Comment by beeonline-cz** [comment]
A ještě otázka: certifikát pro EET musím používat pro podepisování jenom EET rozšíření, a pro platební sekce musím používat klíč, vygenerovaný přes keygen?

**Comment by ratajskym** [comment]
Všechno co posíláte na platební bránu podepisujete klíčem vygenerovaným přes keygen. Viz moje odpověď výše [link](https://github.com/csob/paymentgateway/issues/290#issuecomment-292932977)

**Comment by beeonline-cz** [comment]
Děkuji moc za Váši odpovědi a za dobrou podporu!

**Comment by ratajskym** [comment]
Snad jsem Vám pomohl dobrat se požadovaného výsledku.

MaR.
