### ISSUE TITLE
Vygenerování klíče

### ISSUE THREAD

**Issue by beeonline-cz** [csob/paymentgateway#291]
Dobrý den,

když se snažím vygenerovat nový klíč pro Merchant 04316347 na stránce https://platebnibrana.csob.cz/keygen/ s emailem, uvedeným v sekcí "Info o uživateli", mi se furt vrátí chyba "You entered invalid e-mail or Merchant ID". Prosím o pomoc. Dekuji.

**Comment by joskera** [comment]
Dobrý den,
Vaše Merchant ID je M1MIPS0325 a jako email je nezbytné zadat email Vaší technické podpory, který jste si zvolil při zakládání plateb. brány.

S pozdravem,
Jiří Oškera

**Comment by beeonline-cz** [comment]
Po nahrání nových klíčů obdržel jsem takovou zprávu:

The public key was sumbitted successfully. Your request has ID: 2618 (For your Merchant ID M1MIPS0325). Sandbox and Integration Gateway keys can be used immediatelly. You will need to confirm the Production gateway key in the POS Merchant app. Please refer to the GitHub Wiki for more information

Ale furt vidím v certifikátech starý klíč p12 nahraný ještě 07-04

Z04316347 	1 	07.04.2017 16:57:54 	07.04.2020 09:47:53

Nic jiného nevidím.

Poprosím o pomoc.

**Comment by joskera** [comment]
Dobrý den,
certifikát, který zmiňujete, slouží pouze k umožnění EET transakcí přes finanční správu. Klíče které jste si právě vygeneroval slouží k Vaší autentizaci na plat. bráně (privátním klíčem podepisujete požadavky směřované na plat. bránu a veřejný klíč jste úspěšně zaslal do banky). Dále je potřeba v prostředí PosMerchant potvrdit Váš veřejný klíč jednorázovým kódem, který byl zaslán na email Vaší technické podpory.
