### ISSUE TITLE
returnUrl - protokol?

### ISSUE THREAD

**Issue by beeonline-cz** [csob/paymentgateway#292]
Dobrý den,

zda se, v nastaveních "returnUrl" a nikde v sadě souborů co máme, nikde není HTTPS, jenom HTTP, namísto tohoto platební brána vrátí uživatele na HTTPS.

Kam se mám podívat aby změnit HTTPS na HTTP nebo je to obyčejné chování platební brány?

Děkuji.

**Comment by vzich** [comment]
Dobrý den, 
pokud máte nastaveno v parametru returnUrl https, tak se na něj také přesměrováváte. Pokud se chcete z brány přesměrovat na http, tak stačí upravit parametr returnUrl.
