### ISSUE TITLE
Jak zjistit FIK a BKP kódy?

### ISSUE THREAD

**Issue by beeonline-cz** [csob/paymentgateway#293]
Dobrý den,

pročetl jsem v manuálu, že aby zjistit FIK kód, je třeba poslat dotaz na payment/status

Posílám a mám 404 odpověď.

Merchant M1MIPS0325, transakce existuje, payId e2abdb455b7a8CD.

Tak jak mohu zjistit FIK a BKP kódy?

Metoda echo pracuje.

Prosím o pomoc.

**Comment by vzich** [comment]
Dobrý den,
payment status nezasíláte podle [specifikace](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#get-httpsapiplatebnibranacsobczapiv17paymentstatus-) proto se vám vrací 404, a poté ještě váš podpis není url encoded.

Váš request
```
/api/v1.6M1MIPS0325/e2abdb455b7a8CD/20170419142240//nbcX738t+DIq05BRzL7N/sPuQHvW302sO0Des8vHvQoQu162RdglZF4JiQhRYLf8NS+RBhtSFRe3kKnzzQ9cAbrJhnExVONZRkIBg2m30VBnCOfReULLq0u1KHCgu8bY1qzVjqFHIG42nBXOzmihRI5
CP2Z8TaDC8qhKizZ5yXCFr+lWRqmLHaW4Y6q3bs75rbfYm9QBxQNSZF9tviyF9APchHeOZjx4Qab7q8/2SPbTyHKeEPfmAUrKfEsolOHYmWiHRNADZLu9uj/VeL+uEUz07ove+WXG+upRkW71BCYIixbHS6KZlhlRIWh5SUFXp8W7nKKi89DpooJcqHcKcg==/payment/status/
```
Správný formát
```
/api/v1.6/payment/status/M1MIPS0325/e2abdb455b7a8CD/20170419142240/nbcX738t%2BDIq05BRzL7N%2FsPuQHvW302sO0Des8vHvQoQu162RdglZF4JiQhRYLf8NS%2BRBhtSFRe3kKnzzQ9cAbrJhnExVONZRkIBg2m30VBnCOfReULLq0u1KHCgu8bY1qzVjqFHIG42nBXOzmihRI5CP2Z8TaDC8qhKizZ5yXCFr%2BlWRqmLHaW4Y6q3bs75rbfYm9QBxQNSZF9tviyF9APchHeOZjx4Qab7q8%2F2SPbTyHKeEPfmAUrKfEsolOHYmWiHRNADZLu9uj%2FVeL%2BuEUz07ove%2BWXG%2BupRkW71BCYIixbHS6KZlhlRIWh5SUFXp8W7nKKi89DpooJcqHcKcg%3D%3D
```

**Comment by vzich** [comment]
Jakmile sestavíte request správně, tak se vám na paymentStatus v odpovědi vrátí hodnoty BKP a FIK.
