### ISSUE TITLE
Platba nemůže být provedena

### ISSUE THREAD

**Issue by radovanx** [csob/paymentgateway#294]
pro obchodnika MERCHANTNUMBER=M1E3CB3354 který používá legacy api
se při přechodu na platební bránu objeví informace:

Platba nemůže být provedena
Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.

Bohužel v logu nevidím kde je chyba můžete mi  prosím pomoci identifikovat proč brána platbu odmítá ?

**Comment by vzich** [comment]
Dobrý den,
máte špatný podpis. Vidím, že 3.4. vám ještě transakce procházeli a 11.4. jste generoval nové klíče. Pokud jste nic jiného ve vaší implementaci neměnil, prověřil bych správnost klíčů. 
S pozdravem 
VZ

**Comment by radovanx** [comment]
Dekuji muzeme tedy uzavrit
