### ISSUE TITLE
implementace eAPI v1.7 - reverse

### ISSUE THREAD

**Issue by davemacblack** [csob/paymentgateway#295]
Dobrý den,
implementuji pro zákazníka eAPI v1.7, vše mi zatím funguje správně (echo, init, process, status) a jako poslední krok pracuji na reverse. Domnívám se, že vše dělám správně, ale při požadavku na reverzování platby (je ve stavu 7) vždy dostanu odpověď s resultCode 900 (Internal Error).

Požadavek odesílám přes PUT na adresu:
https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/reverse

Odeslaná Json data:
{"merchantId":"M1E3CB1111","payId":"a5ae05f0b939fCE","dttm":"20170501210609","signature":"CR437+Lm5/f8FrbMdvS6Arr+DHD4W0uSK+fjsWzPfEA/P9tvqbhu9YvBaeqM9a+2BpgxACdE6cYHNsgpoWFV6q9tZ+SAFBD8uspfikuff29C9mxcbWyGx+Ew8lbG/mPTP6Jwt1UVOBxiUZqvaVK2Fp7VXc/J3BaG1vIeltTc8qjI/qTwxHmoaOmq8sA5uqe5AEMFHQZads4h1iY9U2ga9aCwj4iQqrz/ZUX+uS2EjpU5TtInjBht9WEhtsWEdQWcQ80kWN8YX6r/n+VY58geo51Ri9sLfME2K2MeAqP9C9ObQ9dvEXAbOKY4u7K5rVwPeg7v/9Mf2g2I1XAY0d7Ulg=="}

Vrácená Json odpověď:
Method Not Allowed {"resultCode":900,"resultMessage":"Internal error"}

Chtěl bych vás tedy pořádat o pomoc s hledáním chyby.

Děkuji

**Comment by mrazekl** [comment]
Dobrý den,

požadavek jsme přijali. Jakmile budeme mít informace k vašemu řešení, budete zde kontaktován.

**Comment by vzich** [comment]
Dobrý den, 
prověřil jsem jeden z vašich včerejších pokusů (21:06) a uvedený request neposíláte jako PUT ale jako POST, proto dostáváte response "Method not allowed".
S pozdravem
VZ

**Comment by davemacblack** [comment]
Dobrý den,
děkuji za prověření mých pokusů a posunutí správným směrem, reverse už mi funguje, jak má.
DH
