### ISSUE TITLE
Cislo platobnej brany

### ISSUE THREAD

**Issue by Andrea358** [csob/paymentgateway#297]
Dobrý deň,
píšem vám v mene spoločnosti Dateio. Zaoberáme sa cieleným marketingom a spolupracujeme s mnohými českými aj zahraničnými obchodníkmi. Niektorí naši partneri - obchodníci majú platobnú bránu od vašej spoločnosti. Aby sme vedeli priradiť transakcie uskutočnené cez platobnú bránu k danému obchodníkovi, potrebujeme vedieť jej číslo (napr. 00002397|63351523, |445268873996, E3KB0171|9627161009). Niektorí naši obchodníci však toto číslo brány nevedia ani netušia kde ho môžu nájsť. Preto by som sa vás chcela opýtať, či by ste mi napísali návod/postup ako číslo vašich platobných brán zistiť. V budúcnosti tak budeme vedieť obchodníka, ktorý má bránu od vás a nevie jej číslo, inštruovať kde toto číslo nájsť. Vopred ďakujem za odpoveď.

S pozdravom,

Andrea Pernicová

**Comment by vzich** [comment]
Dobrý den, paní Pernicová,
vaši klienti se dozví merchantID (číslo platební brány) po podpisu smlouvy. Pokud obchodník přesto nebude merchantID znát, tak při aktivaci obchodníka do integračního prostředí. případně produkčního, obdrží každý obchodník mail ve kterém je uvedeno jejich merchantID.

S pozdravem
VZ
