### ISSUE TITLE
reset orderNo

### ISSUE THREAD

**Issue by ms502040** [csob/paymentgateway#298]
Dobry den,
pri payment/init a pouziti jiz drive pouziteho orderNo k inicializaci platby nedojde. V popisu API uvadite, ze cislo muze mit max. 10 znaku, zajimalo by mne kdy muzu zacit pouzivat ciselnou radu znovu od 1.

**Comment by mjanek** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by prochac** [comment]
historie transakcí se drží v aktivní databázi 14 měsíců. Po 14 měsících se tyto záznamy odmazávají z aktivní databáze (resp. se archivují) a OrderNo jsou tedy opět k dispozici.

**Comment by vzich** [comment]
Dobrý den,
ještě dodám, že existuje možnost kontrolu orderNo zrušit po dohodě s bankou (akceptacekaret@csob.cz).
