### ISSUE TITLE
premiseId (Označení provozovny) a cashRegisterId(Označení pokladního zařízení poplatníka)

### ISSUE THREAD

**Issue by lamvanduyet** [csob/paymentgateway#299]
Dobrý den, pracuju zrovna teď na EET a chtěl bych se zeptat, kde můžu zjistit premiseId (Označení provozovny) a cashRegisterId(Označení pokladního zařízení poplatníka)? Děkuji.

**Comment by aKocian** [comment]
Dobrý den.

PremiseID by jste měl najít na stránkach finanční správy.
Tohle ID jste taky použil při aktivaci EET certifikátu v rozhrání POSmerchant (pokud jste již tuhle akci udělal).
cashRegisterID - tento parametr si můžete pojmenovat libovolně.

S pozdravem
Alexander Kocian
