### ISSUE TITLE
ČSOB Brána REST API - Knihovna pro ASP.NET

### ISSUE THREAD

**Issue by PremyslNeuman** [csob/paymentgateway#30]
Pro našeho klienta jsme vytvořili kompletní knihovnu pro snadnou implementaci platební brány pro ASP.NET. V případě zájmu o tuto knihovnu nás neváhejte kontaktovat na adrese: info@ncompany.cz případně na www.ncompany.cz 
:)

**Comment by ratajskym** [comment]
S dovolením toto issue uzavřu, nicméně i nadále budu klienty odkazovat na Vaše stránky.
