### ISSUE TITLE
nefunguje EET na testovacím prostředí

### ISSUE THREAD

**Issue by lamvanduyet** [csob/paymentgateway#300]
Dobrý den,
dostavávám tenhle error v testovacím prostředí:
"API returned an error: resultCode "180", resultMessage: Unable to load EET key for merchant M1MIPS1380"
Certifikát mám uploadnutý na https://posman.csob.cz/posmerchant v sekci Obchodník. Nevím v čem je chyba. Děkuji za odpověď.

**Comment by mrazekl** [comment]
Dobrý den,

certifikát jste zavedl do produkčního prostředí. Pokud chcete testovat, musíte jej vložit v integračním prostředí, tedy https://iposman.iplatebnibrana.csob.cz . EET rozšíření máte aktivováno, tudíž by pak už nic nemělo bránit v úspešných pokusech.

**Comment by lamvanduyet** [comment]
Děkuji za odpověď, otestuju a dám vědět jak to dopadlo.

**Comment by lamvanduyet** [comment]
Už mi to funguje, ale v testovacím POSMERCHANT nemůžů zobrazit transakce pro EET? Nebo to není možné v testovacím prostředí? Děkuji.

**Comment by Mspisar** [comment]
Dobrý den,

transakci a její stav  ( EET ) vidíte ve sloupci Stav EET. Po kliknutí na zelený "puntík" se Vám zobrazí dodatečné informace.

s pozdarvem

Spisar

**Comment by lamvanduyet** [comment]
Děkuji už to vidím.
