### ISSUE TITLE
Nedaří se ověřit podpis banky v testu

### ISSUE THREAD

**Issue by petr-briza** [csob/paymentgateway#301]
Vycházím přesně z ukázkové aplikace v .NETu. Bohužel v ní přímo není metoda Crypto.Verify nikde použita, takže nemohu porovant svou funkčnost s funkčností vzoru. Každopádně například toto je odpověď na status transakce: {"dttm":"20170522115950","signature":"oSS0NpTHkM2I4auqzO6p9Fi5ywQZAbQPBng5TgbS5P6yDGeSzOWyJFyxO26toFcQyMSBXgwUzdoAOBUV2NNFr4SJwRdJ+Cno3wTQ7E8R9cnZGFF98B+7/oEGafPzEfndM5bydrNkuriwUtn9EGZYGaJ4SEPR+DS19a3gP/TDfZoIzXeGmxrsrfORfZixR3IiwOwamRDEtHQVN0+Yd7h1s4fNQ8wbZnbcHLOCiS7MmLddHGQ7wtFl5PcbyTNbKxoxOWUMk1P3kg0nxokx0grihoM/DYkp+45ypWknxAsf42QPXhch7Ga8gFE8ljIU40+CumT4enKkPumLnHW6qaRERQ==","payId":"e5015f01d7adfCE","resultCode":0,"resultMessage":"OK","paymentStatus":6}
Ověřuji tedy podpis proti tomuto řetězci: e5015f01d7adfCE|20170522115950|0|OK|6
Používám k ověření veřejný klíč, který byl přiložen přímo u Vaší ukázky v .NETu.
Třídu Crypto jsem v ukázce neměnil.
A metoda Verify mi vrací false.
Máte nějaký tip, co dělám špatně?

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod: TSGSMIPS-3877 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem

**Comment by vzich** [comment]
Dobrý den, 
v příkladu pro .NET viz. [link](https://github.com/csob/paymentgateway/tree/master/Integration%20Examples/eAPI%20v1.6/dotNET/CsobGTWDemo/CsobGatewayClientExample/Assets) je uveden privátní i veřejný klíč obchodníka, předpokládám tedy že pro vaše testování používáte tento veřejný klíč obchodníka. Pro ověření je nicméně třeba veřejný klíč banky, který naleznete [zde](https://github.com/csob/paymentgateway/tree/master/keys), veřejný klíč s názvem _mips_iplatebnibrana.csob.cz.pub_ slouží pro integrační prostředí.

**Comment by petr-briza** [comment]
Aha jasně, to je ono, už to funguje, díky moc.
