### ISSUE TITLE
API returned HTTP code 400, which is not code 200. Probably wrong signature, check crypto keys.

### ISSUE THREAD

**Issue by lamvanduyet** [csob/paymentgateway#303]
Dobrý den,
přešel jsem z testovacího prostředí do produkčního. Vygeneroval jsem si nové klíče, nastavil jsem veřejné klíče banky a změnil jsem i API, ale pořád mi hází chybu: "API returned HTTP code 400, which is not code 200. Probably wrong signature, check crypto keys". Musím potvrdit produkční platební bránu nebo musím ještě udělat? Děkuji za odpověď.

**Comment by mjanek** [comment]
Dobrý den,

Pro prověření bude potřeba zaslat Vaše Merchant ID (ID brány).

**Comment by lamvanduyet** [comment]
Mám tedy poslat merchant ID na email: akceptacekaret@csob.cz?

**Comment by hanuss** [comment]
Bude stačit napsat zde - z jiného vlákna tuším, že by to mohlo být M1MIPS1380 ... ?

**Comment by lamvanduyet** [comment]
Ano náš MerchantID je M1MIPS1380.

**Comment by joskera** [comment]
Dobrý den, 
prověřil jsem Vaše ID a nemáte potvrzený privátní klíč v PosMerchant jednorázovým kódem, který byl zaslán na email Vaší technické podpory.

**Comment by lamvanduyet** [comment]
Aha tak to jsem nevěděl, hned se na to podívám a dám vám vědět. Jinak děkuji.

**Comment by lamvanduyet** [comment]
Už jsem vložil jednorázový kód. Mohli byste to ověřit? Děkuji.

**Comment by joskera** [comment]
Nyní již máte privátní klíč potvrzen, ale dostáváte chybu podpisu (Invalid paymentInit signature for M1MIPS1380). Z toho usuzuji, že chyba může být opět v použitých klíčích nebo posíláte nekorektně některý z parametrů. Pro ověření zda chyba je skutečně v klíčích vyzkoušejte metodu echo:
https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#getpost-httpsapiplatebnibranacsobczapiv17echo-

**Comment by lamvanduyet** [comment]
Už mi vše funguje děkuji.
