### ISSUE TITLE
Generování orderNo na straně obchodníka je náročné

### ISSUE THREAD

**Issue by svobom57** [csob/paymentgateway#304]
Dobrý den,
implementujeme platební bránu a máme následující problém: Dle vaší dokumentace je při inicializaci platební brány povinnou položkou **orderNo**, které se následně ve výpisech transakcí zobrazuje jako variabilní symbol. Kladený požadavek na tento variabilní symbol je, aby byl unikátní v rámci daného obchodníka. To sebou nese následující problémy:

1. Co se stane když přeteče maximální hodnota variabilního symbolu?
2. My integrační prostředí testujeme tak, že každý z našeho vývojového týmu má aplikaci lokálně zprovozněnou a tudíž je nemožné zajistit unikátnost variabilních symbolů zasílaných vaší bráně. Toto pak nevyhnutelně vede k chybovým hláškám při zakládání platební brány, pokud je již variabilní symbol spojen s platbou, která je v ukončeném stavu.
3. Je problematické, pokud je _stejná objednávka_ inicializována vícekrát se stejným variabilním symbolem a pouze jedna z nich dokončena (kromě toho, že tato platba bude ve výpisu transakcí vidět vícekrát)? Toto se mi jeví jako rozumná úspora variabilních symbolů.

Navrhovaným řešením problému 2 a 3, by bylo zodpovědnost generování unikátních symbolů přenechat vám, na straně platební brány, tj. položku **orderNo** nechat nepovinnou. Pokud by obchodnící, z nějakého pro mě neznámého důvodu, chtěli generovat variabilní symboly, stále by mohli platební bráně tento symbol zaslat.

**Comment by joskera** [comment]
Dobrý den, 
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by vzich** [comment]
Dobrý den,
podle vámi popisované situace bych Vám doporučil kontrolu orderNo zrušit. Pro zrušení kontroly je nicméně třeba zaslat žádost na mail akceptacekaret@csob.cz. 
Také bych dodal, že transakcí můžete se stejným VS založit několik, nesmí ale existovat již autorizovaná transakce se stejným VS (stav 4,7,8) pro vaše merchantID (v případě, že je kontrola duplicity aktivní). 
S pozdravem
VZ

**Comment by svobom57** [comment]
Je možné kontrolu orderNo zrušit také na produkční platební bráně? Dále by mě zajímalo, co všechno obnáší "zrušení kontroly". Pokud bude kontrola zrušena, nemusíme platební bráně vůbec zasílat orderNo? Jaké variabilní symboly pak platba bude mít?

**Comment by vzich** [comment]
Dobrý den,
parametr orderNo je povinný, je tedy nutné jej vždy v requestu pro založení platby zasílat. 
Zrušení kontroly na obou prostředích má v kompetenci akceptacekaret@csob.cz, z hlediska platební brány to pro vás znamená, že budete moci autorizovat více plateb se stejným orderNo.

**Comment by svobom57** [comment]
Tzn. i pokud jsou ve stavu 4,7,8?

**Comment by vzich** [comment]
Ano i v těchto stavech, kdy je transakce autorizovaná.

**Comment by landsman** [comment]
Tohle mě teď taky slušně potrápilo :[
