### ISSUE TITLE
Platba nenalezena - Testovací prostředí

### ISSUE THREAD

**Issue by Mitanni** [csob/paymentgateway#305]
Dobrý den,
zkouším testovací prostředí, ale po přechodu na platbu mi brána napíše, že platba nebyla nalezena, i když payId bylo vytvořeno (viz obrázek).
<img width="991" alt="snimek obrazovky 2017-06-08 v 9 17 13" src="https://user-images.githubusercontent.com/23051745/26916674-87008a1a-4c2b-11e7-8f6b-1aeaaaf1ca3d.png">
Pokud ovšem zkouším platby z localhostu, tak mi to vše funguje a problém nehlasí. Problém je jen ze serveru na testovacím prostředí (používám stejné certifikáty jak na localhost tak na testu). Produkční prostředí je taky v pořádku.

Můžete se mrknout proč to nejde?
MERCHANT ID: M1MIPS1367
Verze: 1.6

Děkuji.

**Comment by mjanek** [comment]
Dobrý den,

založení platby proběhne korektne , ale v paymentProcess vracíte jen první písmeno z payID a z toho důvodu hlásí, že neexistuje tato platba. 

June 8th 2017, 09:16:53.263	Received paymentProcess request M1MIPS1367 / b
June 8th 2017, 09:16:52.658	Received paymentInit request M1MIPS1367 / bc40d148ac5b4CF, orderNo 1017

**Comment by Mitanni** [comment]
Dobrý den,
děkuji za info. Ano je to tak. Na serveru se mi objevili dva skripty (jeden z velkým počátečním písmenem a jeden z malým, case sensitive), které platbu zpracovávali a system bral v potaz ten starši, který vracel jen payId a ne celé návratove pole, tak se mi tam dostalo jen to prvni pismenko.
Děkuji za pomoc, jinak bych chybu hledal další půl den.
