### ISSUE TITLE
Dotaz k 'workflow' eshopu

### ISSUE THREAD

**Issue by desss1** [csob/paymentgateway#306]
Dobrý den, mám několik dotazů týkajících se napojení platební brány na eshop

- po dokonční nákupního procesu vytvářím platbu (payment/init) abych měl možnost vytvořit uživateli odkaz pro zaplacení na PB
- zároveň v tomto kroku přes EET extension posílám data do EET a to pouze CELKOVOU CENU NÁKUPU (včetně dopravy), PREMISE_ID (přiděleno z fin. správy) a CASH_REGISTER_ID (mnou zvolený string), to je myslím minimum pro EET, je "nutné" ještě něco? nedělám např. rozpad cen podle DPH
- pokud uživatel zaplatí a vše proběhne v pořádku, je přesměrován zpět na eshop, kde já dostávám kódy FIK a BKP, s platbou již nic nedělám (je "nutné" ji přes API uzavřít?)
- pokud nastane problém (např. uživatel platbu zruší), je uživatel přesměrován zpět na eshop, kde mu dávám na výběr znovu zaplatit platbu -- abych toto mohl udělat, musím založit novou platbu přes payment/init, abych opět mohl vygenerovat odkaz pro zaplacení na PB -- je to správný postup?
- v aplikaci iposman potom vzniká více "plateb" k jedné objednávce, stav EET je "tržba ve stavu založena" -- je "nutné" toto nějak řešit z mojí strany? (tzn. např. po týdnu se podívám do aplikace iposman a je tam 10 plateb ve stavu "tržba ve stavu založena", protože 10 lidí "zrušilo" platbu na PB)
- mohu sám nějak nasimulovat "pád EET serverů" = připravit se na to, že jsou servery offline? co mám v takové situaci dělat, majiteli eshopu předat pouze BKP kód? je potřeba psát cron, ktery bude hlídat dostupnost EET serverů a v případě dostupnosti vyžádá chybějící FIK kódy?

Děkuji za odpověď

**Comment by vzich** [comment]
Dobrý den,

> zároveň v tomto kroku přes EET extension posílám data do EET a to pouze CELKOVOU CENU NÁKUPU (včetně dopravy), PREMISE_ID (přiděleno z fin. správy) a CASH_REGISTER_ID (mnou zvolený string), to je myslím minimum pro EET, je "nutné" ještě něco? nedělám např. rozpad cen podle DPH

Parametry, které jste vyjmenoval, tak jsou povinné z hlediska platební brány. Ostatní parametry jsou volitelné.

> pokud uživatel zaplatí a vše proběhne v pořádku, je přesměrován zpět na eshop, kde já dostávám kódy FIK a BKP, s platbou již nic nedělám (je "nutné" ji přes API uzavřít?)

FIK a BKP zjistíte pomocí payment/status viz. [specifikace](https://github.com/csob/paymentgateway/wiki/Specifikace-API-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-EET#parametry-eet-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-operaci-paymentstatus). Pokud používáte metodu paymentClose pro dodatečné poslání k zúčtování, tak je třeba zaslat rozpis pro EET i v tomto request pro uzavření. 

> pokud nastane problém (např. uživatel platbu zruší), je uživatel přesměrován zpět na eshop, kde mu dávám na výběr znovu zaplatit platbu -- abych toto mohl udělat, musím založit novou platbu přes payment/init, abych opět mohl vygenerovat odkaz pro zaplacení na PB -- je to správný postup?

Pokud váš klient klikne na tlačítko zrušit objednávku a vrátí se do eshopu, tak je již transakce v konečném stavu 3. Je tedy třeba založit novou objednávku.

> v aplikaci iposman potom vzniká více "plateb" k jedné objednávce, stav EET je "tržba ve stavu založena" -- je "nutné" toto nějak řešit z mojí strany? (tzn. např. po týdnu se podívám do aplikace iposman a je tam 10 plateb ve stavu "tržba ve stavu založena", protože 10 lidí "zrušilo" platbu na PB)

Transakce ve stavu "E1 tržba založena", u které tržba nevznikne skončí ve stavu E14 Tržba nevznikla. Viz [životní cyklus tržby](https://github.com/csob/paymentgateway/wiki/%C5%BDivotn%C3%AD-cyklus-tr%C5%BEby#pr%C5%AFchod-tr%C5%BEby-%C5%BEivotn%C3%ADm-cyklem).

> mohu sám nějak nasimulovat "pád EET serverů" = připravit se na to, že jsou servery offline? co mám v takové situaci dělat, majiteli eshopu předat pouze BKP kód? je potřeba psát cron, ktery bude hlídat dostupnost EET serverů a v případě dostupnosti vyžádá chybějící FIK kódy?

Odpovědi na tyto a další otázky z hlediska eshopu naleznete [zde](https://github.com/csob/paymentgateway/wiki/%C5%BDivotn%C3%AD-cyklus-tr%C5%BEby#konkr%C3%A9tn%C3%AD-dopady-%C5%BEivotn%C3%ADho-cyklu-tr%C5%BEby-a-stav%C5%AF-tr%C5%BEby-na-implementaci-v-e-shopu), cituji odpovědi na vámi pokládanou otázku: 
_Nepodaří-li se tržbu nahlásit z důvodu nemožnosti komunikovat s Finanční správou, předá brána obchodníkovi kódy BKP a PKP, které jsou určeny na účtenku. Následně se brána snaží tržbu nahlásit online. Doporučujeme volat jednou za dvě hodiny payment/status, ze kterého se dozvíte nejen stav hlášení tržby, ale i FIK (jakmile se tržbu podaří nahlásit online)._

_Nepodaří-li se bráně nahlásit tržbu ani během 48 hodin od vygenerování offline kódů BKP a PKP, musí situaci řešit obchodník sám. Tato situace může nastat z důvodu extrémního výpadku systému Finanční správy, síťové infrastruktury apod._

**Comment by desss1** [comment]
Dobrý den,

> Pokud používáte metodu paymentClose pro dodatečné poslání k zúčtování, tak je třeba zaslat rozpis pro EET i v tomto request pro uzavření.

Co přesně znamená "dodatečné poslání k zúčtování" / jaké jsou rozdíly oproti tomu, když uživatel úspěšně zaplatí a já platbu "nechám být" (= paymentClose explicitně nevolám)?

> Transakce ve stavu "E1 tržba založena", u které tržba nevznikne skončí ve stavu E14 Tržba nevznikla. Viz životní cyklus tržby.

Je nějaký časový limit, po kterém se tržba sama převede do stavu "E14 Tržba nevznikla"? Nebo je nutné, abych tyto třžby "hlídal" a např. po týdnu je sám uzavíral? Ptám se, protože např. platby, které jsem testoval před týdnem mají v aplikaci iposman stav "Zamítnuto", ale zároveň EET stav "Tržba ve stavu založena"

Díky

**Comment by vzich** [comment]
Dobrý den, 
pokud vidíte v posmerchantu - "zaúčtováno", tak předpokládám, že při inicializaci platby zasíláte v paymentInit parametr: "paymentClose":true. Transakce se vám tedy hned pošle k zúčtování a dojde k proplacení objednávky. Pokud byste zasílal s hodnotou "false", tak nedojde k okamžitému odeslání k zúčtování (transakce zůstane ve stavu 4), k zúčtování je ji tedy možné poslat později (např. jakmile obchodník odešle zboží tak transakci pošle k zúčtování pomocí metody paymentClose, případně je možné ji uzavřít na menší částku - viz. [link](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#za%C3%BA%C4%8Dtov%C3%A1n%C3%AD-na-men%C5%A1%C3%AD-%C4%8D%C3%A1stku-). V tom případě by bylo třeba zaslat rozpis pro EET, to se ale vašeho řešení podle vašeho popisu netýká.
Co se týče stavu E14, tak není třeba "uzavírat". Pokud je transakce zamítnuta, tak se transakce dostane do stavu E14 automaticky. Pokud byste si v aplikaci posmerchant rozkliknul detaily EET, tak u této transakce uvidíte stav E14 - Tržba nevznikla. 
Pro zjištění konečného stavu EET transakce, můžete provolávat payment/status do doby než se bude nacházet v jednom z konečných stavů.

**Comment by desss1** [comment]
Dobře, díky moc za pomoc

můžeme uzavřít
