### ISSUE TITLE
Povolení oneclick payment

### ISSUE THREAD

**Issue by janfabian** [csob/paymentgateway#307]
Dobrý den, v dokumentaci https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#platba-na-klik- se píše

> Funkce Platby na klik není přístupná univerzálně, musí být ze strany ČSOB pro konkrétního obchodníka povolena. 

Prosím o doplnění wiki, kam se podává request o zpřístupnění? 

Toto rozšíření je povoleno automaticky poté, nebo je potřeba zažádat znovu? https://github.com/csob/paymentgateway/wiki/eAPI-1.6-maskovane-cislo-karty

Id brány: M1MIPS1446

Díky Fabián

**Comment by mrazekl** [comment]
Dobrý den,

v obou případech se musíte s žádostí obrátit na oddělení akceptace platebních karet , přes emailovou adresu akceptacekaret@csob.cz

**Comment by janfabian** [comment]
Odpověď po 2 dnech 

> Dobrý den,
>  bohužel zatím tuto službu neposkytujeme. 
> 
> S přáním hezkého dne
> 

Zkusím to ještě jednou s odkazem na zdejší wiki

**Comment by vzich** [comment]
Dobrý den,
přeposlal jsem váš požadavek k vyřešení.
