### ISSUE TITLE
EET rozšíření - Extension eetV3 disabled for M1MIPS1367

### ISSUE THREAD

**Issue by Mitanni** [csob/paymentgateway#308]
Dobrý den,
měli bychom mít EET rozšíření aktivní, ale když chci provést testy pro přechod do produkce, tak mi hlásí:
> https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/init/ failed, reason: Extension eetV3 disabled for M1MIPS1367

V nastavení obchodníka (POS MERCHANT - testovací prostředí) mám nahrán certifikát a je aktivní. V platební bráně jsou všechny položky pro platební metodu EET aktivní.

Musí se ještě někde něco povolit, aby bylo rozšíření aktivní?

Děkuji za informace.

**Comment by vzich** [comment]
Dobrý den, 
zkontroloval jsem nastavení vašeho ID a extension eetV3 nemáte povolenou. Pro povolení extension je třeba kontaktovat akceptacekaret@csob.cz.

**Comment by Mitanni** [comment]
Děkuji za informace :)
