### ISSUE TITLE
Umí eAPI pracovat i s business účtem ČSOB?

### ISSUE THREAD

**Issue by JanPagac** [csob/paymentgateway#309]
Hledám optimální řešení nikoliv pro provedení online platby, ale naopak kontrolu příchozích plateb na business účtu ČSOB pro účely spárování s eshop objednávkami dle variablních symbolů atd.

Tyto platby nemusí mít nic společného s online platbami, může se jednat o převody z účtů, může se jednat o jakoukoliv kreditní transakci, kterou je potřeba zkontrolovat, zda nepatří k nějaké objednávce eshopu.

V rámci dokumentace eAPI ČSOB jsem ovšem na tuto funkci nenarazil, disponuje eAPI podobnou možností? 

Děkuji za pomoc.

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl předán na odpovědného kolegu a v nejbližší době budete kontaktován s odpovědí.

s pozdravem

Milan Spisar

**Comment by vzich** [comment]
Dobrý den,
Vámi popisované řešení eAPI nenabízí. Nicméně by vám mohla pomoci pro vaše řešení - aplikace ČSOB Business Connector.
Více informací naleznete např. na webu https://businessconnector.csob.cz/.

**Comment by JanPagac** [comment]
Děkuji za info, je případně ještě nějaká jiná možnost než instalace desktop aplikace BConnector? Ideálně, aby webová aplikace eshopu zvládala data získat svépomocí bez nutnosti manuálního zásahu člověkem?

**Comment by vzich** [comment]
Dobrý den,
pro zjištění, zda existuje jiná alternativa k Business Connectoru, doporučuji zavolat na infolinku ČSOB  na telefonním čísle 800 150 150, případně můžete využít [kontaktního formuláře](https://www.csob.cz/portal/kontakty/napiste-nam#ic1=HP-CSOB~Kontaktni-formular~Menu).

**Comment by JanPagac** [comment]
ok, moc děkuji za nasměrování, budu dále řešit s tel. podporou ČSOB
