### ISSUE TITLE
Migrace z WebPay

### ISSUE THREAD

**Issue by VitMichalek** [csob/paymentgateway#31]
Zdravím,

přecházíme z původního paymuzo.
Nové certifikáty jsem nastavil, vytvořím i požadavek na testovací server.
Ale ten mi zobrazí jen informaci : 

Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem. 

Je možné se dozvědět o jakou chybu se jedná, nějaký log?

Děkuji

**Comment by ratajskym** [comment]
Dobrý den,

ano, logy je možné dohledat. Podívejte se prosím na toto issue

https://github.com/csob/paymentgateway/issues/24

**Comment by VitMichalek** [comment]
Děkuji to jsem nějak minul.
Ještě jeden dotaz.
Pokud bych přecházel na vaše nové API, musím splnit všechny testy, které popisujete aby bylo možné přejit na produkční prostředí - to je mi jasné.
Ale je nutné tyto testy splnit i při migraci z WebPay?

**Comment by ratajskym** [comment]
Při migraci z WebPay testy plnit nemusíte. Předpokládá se, že máte již funkční řešení, které není potřeba retestovat.

**Comment by VitMichalek** [comment]
No to právě není.
Je to 11 let stará aplikace a je tam jen platba kartou,zpracování odpovědí(chybové stavy) nic dalšího to neumí.

**Comment by ratajskym** [comment]
Pokud nějaká implementace shopu neumí všechny podporované funkce, kterou jsou na straně brány, pak Vás samozřejmě nikdo nebude nutit do toho, abyste je doprogramoval.

**Comment by VitMichalek** [comment]
Ještě bych měl dotaz. Pokud implementuju bránu na stránky s inzercí - tedy nejedná se o klasický eshop. Musím i tak do košíku přidávat - dopravné? Pokud to odstraním hlasí to samozřejmě chybu.

**Comment by ratajskym** [comment]
Dobrý den, 

ve specifikaci se píše, že musí být minimálně 1 položka https://github.com/csob/paymentgateway/wiki/eApi-v1-CZ#cart-items

Pokud Vám systém vrací chybu, zkuste to u sebe ještě prověřit.

**Comment by VitMichalek** [comment]
Když se dívám do ukázkového skriptu crypto.php je funkce createCartData  kde je pole o velikost 2 - 
Pozice 0 - > zboží
Pozice 1 -> dobrava

Když odstraním pozici 1, vrací mi následně INIT, status 400

**Comment by ratajskym** [comment]
Dobrý den, 

podařilo se Vám systém zmigrovat? Můžeme toto vlákno uzavřít?

Děkuji za informaci
