### ISSUE TITLE
MasterPass: Merchant not onboarded for MasterPass

### ISSUE THREAD

**Issue by JanPagac** [csob/paymentgateway#310]
Zdravím, implementujeme MasterPass tlačítko a při použití anonymních vývojových klíčů z keygenu nám API vrací error 230 - Merchant not onboarded for MasterPass.

Je možné pro vygenerované vývojové MerchantId někde nějak zajistit toto oprávnění k použití MasterPass a odladění?

Děkuji, Pagáč

**Comment by vzich** [comment]
Dobrý den,
anonymní ID nabízí pouze možnost vyzkoušet si základní funkcionalitu platební brány. Pro aktivaci MasterPass je třeba mít uzavřenu smlouvu s bankou.
S pozdravem
VZ

**Comment by JanPagac** [comment]
Rozumím, jaké info o dalším vhodném postupu máme předat klientovi, má zavolat linku ČSOB a tam je někdo navede nebo na pobočku a řešit tam?

**Comment by vzich** [comment]
Pokud klient nemá podepsanou smlouvu k platební bráně, tak ano, doporučuji zajít na pobočku, případně kontaktovat svého bankéře.

**Comment by JanPagac** [comment]
OK, děkuji za informace, předám dále. Zatím, Pagáč.
