### ISSUE TITLE
Chybejici singnature v "Internal error" odpovedi

### ISSUE THREAD

**Issue by JindrichPilar** [csob/paymentgateway#311]
Dobry den,

pri dostatecne spatnem pozadavku dostanu odpoved ktera neobsahuje signature. Coz je oproti zbytku API volani anomalie, ktera komplikuje proces zpracovani.

```json
{
  "resultCode":900,
  "resultMessage":"Internal error"
}
```

Aplikace
 - Vytvori pozadavek
 - Preda ho PaymentGatewayService
 - Dostane odpoved
 - Zachova se podle resultCode v odpovedi

 PaymentGatewayService 
 - Zakoduje pozadavek
 - Odesle API pozadavek
 - Dekoduje odpoved
 - Zkontroluje signature (pokud neprojde hodi exception)
 - Vrati aplikaci odpoved
 
Napriklad pro ``/payment/init`` je  [signature v odpovedi oznacena tucne - jako povinna](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7-EN#return-values-) , ale v odpovedi neni. 

Pochopil jsem spatne dokumentaci? Je muj proces zpracovani nelogicky?

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod: TSGSMIPS-4193 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem

**Comment by dmarek** [comment]
Platební brána u každého požadavku provádí kontrolu na tzv. "základní validaci", pokud se jedná o nevalidní požadavek (chybějící parametry merchantId nebo signature v requestu, požadavek ze zakázané ip adresy nebo domény anebo nevalidní podpis requestu), vrací platební brána http response code 400/403/500, přičemž signature v response není uvedena. 

Povinnost parametrů v odpovědi platí pro situace, kdy proběhnou tyto základní validace a provádí se následné kontroly (ostatní parametry, formát dat). Doplníme do dokumentace podrobnější popis.

**Comment by JindrichPilar** [comment]
Dekuji za odpoved.
