### ISSUE TITLE
Cekani na vyrizeni platby

### ISSUE THREAD

**Issue by JindrichPilar** [csob/paymentgateway#312]
Dokumentace rika ze pri ```payment/oneclick/start``` muze zpracovani trvat az 60 vterin. 

Tyka se to i jinych volani?

Zejmena:
- Vytvorim payment:  ```payment/init``` s parametrem ```closePayment```   
- Uzivatel zada OK kartu
- brana presmeruje zpet 

Musim nyni pollovat status, nebo se mohu spolehnout na status se kterym je uzivatel presmerovan?

> We recommend to call payment/status not earlier than 2-3 seconds after payment/oneclick/start call. Should the payment status be still 2 (in progress), please poll the status every 5 seconds. The gateway depends performance of multiple systems beyond our control while authorising the transaction, which can (in the worst case) take up to 60 seconds.

**Comment by vzich** [comment]
Dobrý den,
pokud se klient vrátí zpět na eshop z platební brány, tak není třeba volat payment/status, výsledný status transakce obdržíte s přesměrováním. Pokud se ale klient nevrátí (např. zavře okno prohlížeče), tak paymentStatus doporučuji volat.

**Comment by JindrichPilar** [comment]
Dekuji za odpoved, to je skvela zprava.

Ze zvedavosti: Proc platba ze stejne kreditky jednou trva "chvilku" a jednou az 60 vterin?

**Comment by vzich** [comment]
Záleží, zda vydavatel platební karty danou platbu autorizuje obratem, nebo odpověď trvá déle.

**Comment by JindrichPilar** [comment]
A v pripade kdy uzivatel zadava udaje o karte se tedy cela autoriz

**Comment by vzich** [comment]
Pokud myslíte před přesměrováním z platební brány zpět na eshop tak ano. Uživatel zadá údaje o kartě na platební bráně, poté proběhne autorizace transakce u vydavatele a po úspěšné autorizaci proběhne redirect na vaši návratovou URL s výsledkem platby.

**Comment by JindrichPilar** [comment]
To je presne to co jsem si chtel overit. To kam tech az 60 vterin "zmizi".  

Dekuji za velmi rychlou odpoved.
