### ISSUE TITLE
Testovací prostředí - nahrání EET certifikátu

### ISSUE THREAD

**Issue by Mitanni** [csob/paymentgateway#313]
Dobrý den,
pokouším se nahrát certifikát, který jsem stáhl z Daňové správy (EET). Dle postupu v nápovědě, jsem jej nahrál v nastavení obchodníka. Vypsala se hláška: **Certifikát byl úspěšně uložen. Nyní jej můžete aktivovat na jednotlivých obchodních místech.**
Přejdu tedy na obchodní místo, ale tam možnost aktivovat certifikát není.

V ostré / produkční verzi se mi podařilo vše udělat dle nápovědy a proběhlo to v pořádku včetně aktivace certifikátu u obchodního místa. 
Jen v testovacím prostředí bohužel nemohu aktivovat vložený certifikát u obchodního místa.

MERCHANT ID: M1MIPS1367

Můžete mi poradit?

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaregistrován o dalším postupu Vás bude informovat odpovědný kolega.

S pozdravem

Spisar

**Comment by Mspisar** [comment]
Dobrý den,

v testovacím prostředí vidím certifikát i ID provozovny uloženo.

s pozdravem 

Spisar

**Comment by Mitanni** [comment]
Dobrý den,
ano. Bohužel jsem před pár dny musel certifikát na daňové správě regenerovat. Chtěl jsem to tedy nastavit jako na produkčním prostředí s ID provozovny 21.
A nyní mám podezření, že se nový certifikát nenahrál a zůstavá tam starý nebo možná nahrál, ale nejde nový přiřadit k obchodnímu místu.
Je možné na TESTOVACÍM prostředí ten certifikát uplně odstarnit a já bych si to už nastavil jako na produkci?

**Comment by Mspisar** [comment]
Dobrý den,

kontaktoval jsem kolegu ohledně této situace. Odpovíme Vám ihned jakmile to bude možné.

s pozdravem

Spisar

**Comment by vzich** [comment]
Dobrý den,
certifikát je pro platební brány nutné aktivovat v menu Platební brány, ikona - Aktivovat certifikát platební brány.
Viz. printscreen
![image](https://user-images.githubusercontent.com/17046375/28017626-5bdb6c66-657a-11e7-96a1-02305abbaab3.png).
Zde můžete nastavit nový certifikát pro vaše ID provozovny 21.

**Comment by Mitanni** [comment]
Dobrý den,
to jsem se samozřejmě snažil provést, ale píše mi to AKCE SELHALA (viz printscreen).

<img width="643" alt="snimek obrazovky 2017-07-10 v 16 30 07" src="https://user-images.githubusercontent.com/23051745/28023141-48909830-658d-11e7-947e-8cce48c1512b.png">

**Comment by vzich** [comment]
Dobrý den,
vyzkoušejte aktivovat certifikát znovu.

**Comment by Mitanni** [comment]
Dobrý den,
už je to v pořádku. Už se mi k ID provozovny podařilo aktivovat ten certifikát. Děkuji za pomoc :)
