### ISSUE TITLE
Nefunkční přihlášení do testovacího prostředí

### ISSUE THREAD

**Issue by vitek499** [csob/paymentgateway#314]
Dobrý den,

implementujeme Vaše řešení platební brány, získali jsme přihlašovací údaje, bohužel nedaří se nám přihlásit do testovacího rozhraní na adrese https://iposman.iplatebnibrana.csob.cz/posmerchant . Do ostrého prostředí se přihlásit lze! Pokoušeli jsme se získat heslo skrze funkci "zapomenuté heslo" a bohužel i zde dostáváme informace, že kombinace email a IČ neexistuje.

IČ: 01894242

Děkuji za odpověď

**Comment by Mspisar** [comment]
Dobrý den, 

s dotazy ohledně účtu, přihlášení či požadavku obnovení hesla se prosím obraťte přímo na banku a to na kontaktní email:

akceptacekaret@csob.cz - z kontaktního emailu zákazníka 

s pozdravem

Spisar

**Comment by vitek499** [comment]
S odpovědí jste mě příliš nepotěšil, každopádně děkuji.
