### ISSUE TITLE
Chyba testovací platební brány

### ISSUE THREAD

**Issue by marekkrivan** [csob/paymentgateway#315]
Dobrý den,

na platební bráně dostávám zpět stavový kód 400. Dle dokumentace je to chybná URL nebo data

URL je dle mého správně https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/init/ a data též viz níže. Jelikož to ještě asi před měsícem fungovalo zcela v pořádku (nic se od té doby neměnilo). Můžete se na to prosím podívat.

Děkuji

{  
   "merchantId":"M1MIPS1009",
   "orderNo":1499682986,
   "dttm":"20170710113628",
   "payOperation":"payment",
   "payMethod":"card",
   "totalAmount":36000,
   "currency":"CZK",
   "closePayment":true,
   "returnUrl":"https://zarukov.cz/?do=paymentReturn",
   "returnMethod":"GET",
   "cart":[  
      {  
         "name":"Prodloužení záruky",
         "quantity":1,
         "amount":40000,
         "description":"Cena vč. případné množstevní slevy"
      },
      {  
         "name":"Sleva 10%",
         "quantity":1,
         "amount":-4000,
         "description":"Sleva za online platbu."
      }
   ],
   "description":"Prodloužení záruky pro váš klid",
   "merchantData":1499682986,
   "language":"CZ",
   "extensions":[  
      {  
         "extension":"eetV3",
         "dttm":"20170710113628",
         "data":{  
            "premiseId":"11",
            "cashRegisterId":"zarukov.cz",
            "totalPrice":"360.00"
         },
         "signature":"X8FRIxaXbjH3RwEfGympiZivGnSebpiIGhl6PvgNUI+faw2M5s88SmO0T/VNj9x3Fn2Sfzo2scP6LpPU2mIyGOqrEGkWkcKtMjP4yoUGw0gqwUeDnAAOUvjKi8myrPvBbsaLhQUqCjTuTn7yy3qmccf3JkkJlZNyI9YkbGUI8XJCCzMFOXoBr7zRktixrzKM55jlMan151G1JNvnM1VgvwZHjaqfia3oLXJFnwDx/i7CZkMDaSzAbPpTtjHFIp9ihRNZ+eqphart5dpDXLsW3GYVPOHNAMpSwuxW3lXUAIw+m6P/ckXysbDMRqIBxWNR7ISZeWVRU/yzRIj5fSYMzg=="
      }
   ],
   "signature":"IvDc8YVcx+XyVOUiGSXnwkggn9/FUxd8UC/ScFItz6i2ybz3dwgGAJekm2PhNMxJLs5kxDk62SxKbOnxlOSdNrWxKDUNMoKrzRpcitmtd0ktQ1+O/xVgTYT8NRoqmzJNm3gwQfSyCkDR8ENNscP3LNi0Aoz99q4IvzPM2pIXwkkXiX9R70UFWpkSNwBghBmbJV5wjYxTdb+7/+QQzm94FG/eUOs0iewXWiHg+IdhxhGVBOPhqu2tRSroO1NDxVfgU+4bQnjCLt9fvkhycLVtHC3/tIjh9yCi3MdwhwtCX+T+mAJ/yT/ochWBjLIkW3fRbNNJ+ZncDu1XNQkj1e9S7A=="
}

**Comment by mrazekl** [comment]
Dobrý den,

Váš požadavek jsme zaregistrovali a v současnosti jej prověřujeme.

**Comment by vzich** [comment]
Dobrý den,
parametr merchantData nezasíláte jako string a také není kódováno v base64. Prověřil jsem jeden z vašich requestů z minulého měsíce a to jste zasílal hodnotu _null_, proto jste mohl kódování opomenout. Viz. [dokumentace](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#-post-httpsapiplatebnibranacsobczapiv17paymentinit-). Zkuste tedy upravit a poté prosím vyzkoušejte znovu. 

S pozdravem

VZ

**Comment by marekkrivan** [comment]
Dobrý den,

toto je v pořádku, ale narážím na jinou chybu. Jak je možné, že náhodně platebná brána vrací error 500. Odešlu dostanu error 500 za minutu udělám totéž aniž bych upravil kod a vše projde normálně. Je to problém jen testovaícho prostředí nebo se to děje i v realu? Nerad bych měl každý 10request na bránu error 500 :) Jestli logujete každé requesty, tak byste to mohli vidět v cca 10.07.2017 22:24 byl request co skončil chybou 500 a ve o 4 minuty později tedy ve 22:28 byl request co prošel normálně.

**Comment by vzich** [comment]
Ve vašem requestu z 22:25 jste zasílal v eet extension parametr totalPrice v nevalidním formátu, konkrétně:
**"totalPrice":"647.1.00"** a na něj se vám vrátilo 500. 
V requestu v 22:28 jste zaslal "totalPrice":"360.00", a ten prošel korektně. Prověřte tedy formátování v případě "haléřových" částek.

**Comment by marekkrivan** [comment]
Dobrý den, hloupá chyba... děkuji.
