### ISSUE TITLE
Help with HTTP 500, result 900

### ISSUE THREAD

**Issue by Vesuvium** [csob/paymentgateway#316]
Hi there!
I have been trying to make requests against the integration api, with sandbox credentials from the keygen.
When I try to make a request against *payment/init * all I am getting is an internal error response with result code 900.

Is there any way I can get the exact error for my requests? My merchant id is A26020xJNH

**Comment by mjanek** [comment]
Hello,

Your request has been registered. You will be informed by a responsible colleague.

Best regards

Miroslav Janek

**Comment by vzich** [comment]
Hi,
I checked your last request at 17:54 and you are not sending anything in your cart, specifically - _"cart": "",_ you should send in your requests atleast one item. However yesterday at 16:31, you've sent _ "cart": [{"name": "Tesovaci nakup", "quantity": 1, "amount": 1000000}],_ and your transaction initialization was succesfull.

**Comment by Vesuvium** [comment]
I see, some part of my code was removing the cart. Dekuju :)
