### ISSUE TITLE
Platební brána a EET (různé měny)

### ISSUE THREAD

**Issue by Mitanni** [csob/paymentgateway#317]
Dobrý den,
chtěl bych se zeptat. Na svém webu prodáváme produkty pro evropu a ceny jsou v EUR.
Při prodeji chci hlásit platbu (EET) na FS. Kde přepočítám částku, dle aktuálního kurzu, na CZK. Ale pokud jsou částky v podpisu pro extension EET a platební bránu jiné, vyhodí to chybu 500. Pokud se obě částky shodují, pak platba i EET projde (vyzkoušeno na testovacím prostředí).
Je nějakým způsobem tedy možné, aby zákazník platil na platební bráně v EURech a na EET se posílali CZK? Nebo musím částku i na platební bráně přepočítat na CZK (což může být matoucí, třeba pro zahraniční klienty).

Děkuji za odpověď.

**Comment by vzich** [comment]
Dobrý den,
pokud se jedná o ID M1MIPS1367, tak vidím problém v tom, že používáte jako oddělovač tisíců čárku, nicméně podle dokumentace je třeba zasílat celkovou částku pro hlášení tržby bez ní, viz. [ukázka](https://github.com/csob/paymentgateway/wiki/Specifikace-API-roz%C5%A1%C3%AD%C5%99en%C3%AD-pro-EET#p%C5%99%C3%ADklad-vol%C3%A1n%C3%AD-paymentinit-s-eet-roz%C5%A1%C3%AD%C5%99en%C3%ADm-na-eapi-v17). Z toho důvodu se vám vrací HTTP 500.
Např. dnes v 9:50 jste posílal: 
_"totalPrice":"6,544.17"_

**Comment by Mitanni** [comment]
Dobrý den, jj. Máte pravdu. Nevšiml jsem si, že tam formatovaci funkce haže "defaultně" čárku jako oddělovač tisíců.
Děkuji za info.
