### ISSUE TITLE
Problém s parametry po návratu z platební brány

### ISSUE THREAD

**Issue by kapik2003** [csob/paymentgateway#318]
Dobrý den,
mám momentálně s platební bránou takovýto problém. Inicializace platby i její realizace proběhne ok, ale po návratu zpět na doší webvé aplikace nejsou dostupné žádné parametry o provedené platbě (doposud to fungovalo dobře a vše bylo v asociativním poli $_POST - php implementace). Díky tomu nejsem schopen platbu spárovat. Netušíte, čím by to mohlo být?

Možná to může souviset s tím, že tuto bránu používáme na dvou doménách a využívají se stejné klíče. Je to tak v pořádku a nebo se musí pro každou doménu vytvořit samostatný účet. Klient mi tvrdí, že stačí prý jen jeden.

Díky moc za vysvětlení.

S pozdravem
David Kaprál

**Comment by mjanek** [comment]
Dobrý den, 

Váš požadavek byl zaevidován. O dalším průběhu Vás bude kontaktovat odpovědný technik.

S pozdravem 

Miroslav Janek

**Comment by vzich** [comment]
Dobrý den,
ve využívání stejných klíčů by neměl být problém. Můžete uvést konkrétní příklad payID, které můžeme detailněji prověřit?

**Comment by kapik2003** [comment]
Zdravím,
tak jsem platbu provedl znova (produkční prostředí) a dopadlo to úplně stejně. Poprosím tedy o kontrolu platby s payID b3af951ea18cdCG zda lze něco o tom zjistit.

Díky

**Comment by vzich** [comment]
Dobrý den, 
prověřil jsem průběh platby a při přesměrování na váš eshop jsme vám předávali všechny návratové hodnoty dle specifikace. U druhé domény podobný problém nemáte? Nebo se to týká obou vašich eshopů?

**Comment by kapik2003** [comment]
Dobrý den,
tak jsem to celé řádně otestoval. Na doméně artmen.cz je vše bez problémů, na sendmen.com se jednak zobrazuje po zaplacení přiložená hláška a navíc pole $_POST i $_REQUEST jsou prázdná. To ukazuje druhý soubor po návratu z brány. Vážně nevím, kdehledat chybu, neboť funkce jsou naprosto totožné. Kdybych z brány obdržel potřebné paramtetry, tak by se to dalo nějak odladit, takto bohužel nikoliv a tuhle chybu já neovlivním.

![gateway_error](https://user-images.githubusercontent.com/26360601/28622331-7830d774-7214-11e7-9980-db96377c697a.png)

![gateway_return](https://user-images.githubusercontent.com/26360601/28622347-817af88c-7214-11e7-9e4d-e7cd1c3589a3.png)

Díky

**Comment by kapik2003** [comment]
Zde se jednalo o platbu s payID fc64226281c50CG, ale předpokládám, že to bude stejné jako u předchozí platby, kterou jste kontroloval.

**Comment by vzich** [comment]
Vypadá to, že při založení platby uvádíte adresu pro přesměrování http 
_"returnUrl":"http:\/\/www.sendmen.com\/kompletace-platby"_,  ale podle screenu očekáváte parametry na url https://www.sendmen.com/kompletace-platby? Je to tak?

**Comment by ratajskym** [comment]
Když pošlu POST požadavek na adresu https://www.sendmen.com/kompletace-platby, vidím Váš debug
```
array(1) {
  ["post"]=>
  string(3) "123"
}
array(2) {
  ["url"]=>
  string(17) "kompletace-platby"
  ["post"]=>
  string(3) "123"
}
```

Když pošlu POST požadavek na adresu http://www.sendmen.com/kompletace-platby, vidím Váš debug
```
array(0) {
}
array(1) {
  ["url"]=>
  string(17) "kompletace-platby"
}
```

Tedy bez POST pole. Problém je tedy na Vaší straně

**Comment by kapik2003** [comment]
Díky moc, už to funguje. Bylo to opravdu v tom https protokolu. Zvláštní však, že to v tomto nastavení dříve fungovalo. No nic, hlavně, že už je to ok.

Ještě jednou díky a přeji hezký den.
