### ISSUE TITLE
Nelze vygenerovat nove klice

### ISSUE THREAD

**Issue by mfeuermann** [csob/paymentgateway#319]
Dobry den,

snazim se vygenerovat nove klice k merchantId M1E3CB3838 
ale hlasi mi to Zadali jste nesprávný merchant ID nebo e-mail.

jako email zadavam vit.ros....@
Bylo by prosim na tuto adresu (ktera je zaroven administrativni kontakt) zaslat jakou emailovou adresu tam mame zadavat ?

Zrejme je chyba prave v tomto emailu...
Dekuji 
Marek Feuermann

**Comment by mrazekl** [comment]
Dobrý den,

Jako e-mail se zadává e-mail technické podpory, ve Vašem případě: pavel.humpolec@trip.market
Na e-mail jsem Vám zaslal kopii.

S pozdravem Mrázek

**Comment by mfeuermann** [comment]
Dobry den, dekuji nicmene to take nefunguje...
https://iplatebnibrana.csob.cz/keygen/
M1E3CB3838 email zadavam pavel.humpolec@trip.market
vysledek ale je 
Zadali jste nesprávný merchant ID nebo e-mail.
Děkuji Vam za podporu

**Comment by mfeuermann** [comment]
Stejny problem je i na https://platebnibrana.csob.cz/keygen/
Jeste koukam, ze stav teto brany je 'blokovany', nemuze byt problem v tom ?
Dekuji Vam

**Comment by mjanek** [comment]
Dobrý den, 

právě jsem se na to díval a problém bude opravdu v tom, že máte stav blokovaný. 

Pro odstranění problémů je nutné kontaktovat akceptacekaret@csob.cz s žádostí o odblokování.

Přeji hezký den

**Comment by mfeuermann** [comment]
Dekuji Vam, obratime se na Vami uvedenou emailovou adresu...
Mam jeste jeden dotaz. V  nasi aplikaci a business reseni nevyuzivame a vyuzivat nebudeme vsechny pripady, ktere mate uvedeny v certifikaci - napr refundaci nikdy volat pres api nebudeme (bude mozna jedine opravnenym pracovnikem pres posmana)... Je i tak nutne vsechny volani pres API integrovat ? Mockrat dekuji za info

**Comment by ratajskym** [comment]
Dobrý den, 

pokud nebudete refund používat tak to implementovat nemusíte.

**Comment by mfeuermann** [comment]
Dekuji Vam za informaci
