### ISSUE TITLE
Implementace eAPI .NET - (400) Bad Request

### ISSUE THREAD

**Issue by turcovsky** [csob/paymentgateway#32]
Zdravím,

prosím o radu. Pokouším se implementovat nové eAPI. Mám však problém s tím, že při požadavku payment/init mi prohlížeč vrací (400) Bad Request.

Požadavek odesílaný v JSON formátě vypadá následovně:
{"merchantId":"M1E3CB3639","orderNo":"15990233","dttm":"20150810110900","payOperation":"payment","payMethod":"card","totalAmount":31000,"currency":"CZK","closePayment":false,"returnUrl":"http://www.test.a-razitka.cz/exec/card/muzo/paymuzoback.aspx","returnMethod":"POST","cart":[{"name":"Nákup na webu","quantity":1,"amount":100,"description":"Polozka"}],"description":"Nákup na webu","language":"CZ","signature":"fM6eMsaeN1V3zMrPaGAQKq6CqZgHUH3aQYROXcgIYs1d+la7QCVuucs1mKxH02gdATdLFgO72JEebfrT36jVPAeSznwRvKbtPZGfKCUGgRgRam2vs13PHtBO/i33+9n4rKi1kvFYPKyhrtGccHwZiRBgxmyJMQ8SITHOzDfc1w6tdnDU99kDHHk3X5RVlSYIOcz+kExLub0uZbQW1qXssCeEU789ojkM+2Q72MY8h8eB0bzysyVxieJ/f3JULH5YUMKGa4u0q1zvkXdHtSiMhP8g+F0ias0mj8bD+ODbfNuPI3wRj0+Kkgw5K/9s6fabodD9NI4i7oiCci6ZbxFqhQ=="}

a řetězec pro sestavení podpisu následovně:
M1E3CB3639|15990233|20150810110900|payment|card|31000|CZK|false|http://www.test.a-razitka.cz/exec/card/muzo/paymuzoback.aspx|POST|Nákup na webu|1|31000|Polozka|Nákup na webu|CZ

Pro podpis využívám privátní klíč generovaný pro integrační prostředí.
Vše je také voláno pro integrační prostředí:
https://iapi.iplatebnibrana.csob.cz/api/v1/payment/init

Můžete mi prosím sdělit co mám zde špatně, že dostávám odpověď serveru 400 - Bad request?

Prosím o urychlenou odpověď.
Klient velice tlačí na implementaci.

Děkuji mockrát.
Turcovský.

**Comment by ratajskym** [comment]
Dobrý den, máte špatný podpis (log: Invalid paymentInit signature)

Pokud máte problém s implementací, zkuste se obrátit zde https://github.com/csob/paymentgateway/issues/30

**Comment by turcovsky** [comment]
Mohu se ještě zeptat, zda existuje testovací rozhraní POS Merchant? Nebo jakým způsobem mohu vidět úspěšné platby provedené v integračním prostředí?
Děkuji.
Turcovský

**Comment by ratajskym** [comment]
Dobrý den, 

ano existuje. https://iposman.iplatebnibrana.csob.cz/posmerchant

**Comment by turcovsky** [comment]
Děkuji.

Toto vlákno je možné uzavřít.
Vše již funguje jak má.
děkuji.
Turcovský
