### ISSUE TITLE
Upload loga

### ISSUE THREAD

**Issue by mfeuermann** [csob/paymentgateway#320]
Dobry den,

pokousim se u nasi instance M1E3CB3838 nahrat logo...
I pres to ze vkladam logo zminovaneho rozmeru ve formatu png mi to neprojde...

Bylo by mozne zjistit kde je chyba ?
Dekuji 
Marek Feuermann

![logo 480x200](https://user-images.githubusercontent.com/146955/29269053-e3a3ffc4-80ef-11e7-9fc6-49968af8afaf.png)

**Comment by joskera** [comment]
Dobrý den,
ujistěte se, že vaše logo splňuje následující podmínky:
1. Podporované rozměry: šířka 240px, výška 100px nebo šířka 480px, výška 200px
2. Doporučená barva pozadí: průhledná nebo bílá
3. Maximální velikost: 500kB
4. Formát: PNG

Napište zde jak máte soubor pojmenován.

**Comment by mfeuermann** [comment]
Problem byl v rozliseni, omlouvam se, ceka na schvaleni dekuji zaviram...
