### ISSUE TITLE
Opakovaná platba - 150:Payment not in valid state

### ISSUE THREAD

**Issue by premekkoch** [csob/paymentgateway#321]
Dobrý den,
implementuji funkcionalitu plateb na klik a narážím na problém, kdy je platba na klik autorizována jen v případě, kdy je na stejnou částku jako původní (autorizační) platba. Pokud se částka liší, je platba zamítnuta a API mi vrací error 150 - payment not in valid state. Můžete mi prosím poradit? 
MerchantId: M1MIPS1541

Díky!

**Comment by mjanek** [comment]
Dobrý den,

Váš požadavek byl zaevidován. O dalším průběhu Vás bude informovat odpovědný servisní technik. 

Miroslav Janek

**Comment by ratajskym** [comment]
Tento návratový kód je v případě, že originální transakce není v požadovaném stavu tzn není potvrzená.

**Comment by premekkoch** [comment]
V tom případě je otázka, proč jsou následné platby na klik se stejnou částkou jako "orginální transakce" úspěšné.?.

**Comment by ratajskym** [comment]
Pojďme se prosím bavit o nějaké konkrétní transakci. Postněte payId, které rozporujete

**Comment by premekkoch** [comment]
Autorizační transakce má payId = cf4629d98ae0dCH
na jejím základě pak:
Platba na klik na stejnou částku (autorizace potvrzena) má payId = b422f28bcceceCH
Platba na klik na rozdílnou částku (zamítnuto) má payId = c984d26e1ad7cCH

**Comment by ratajskym** [comment]
Vyzkoušejte prosím nižší částku, než je originální transakce např. 2,-

**Comment by premekkoch** [comment]
Ano, nižší částka prošla - payId = 294322c0fea0fCH

**Comment by ratajskym** [comment]
V pořádku. Chování aplikace je způsobeno nastavením Vašeho profilu. Při oneclick transakci musíte použít stejnou měnu a stejnou nebo nižší částku jako originální transakci. Toto chování (restrikci) je možné změnit, ale to je potřeba vyjednat s bankou.

**Comment by premekkoch** [comment]
Paráda, díky moc za pomoc. 

_Možná by stálo za to, uvést to do dokumentace. Pokud to tam ovšem už není, já to nenašel._  

Ještě jednou děkuji!
