### ISSUE TITLE
Platební brána nevrací údaje o provedené platbě

### ISSUE THREAD

**Issue by Sysova** [csob/paymentgateway#322]
Dobrý den.
Při platbě přes naší aplikaci na bránu M1MIPS1334 se realitně často stává, že nedostaneme informaci o provedené platbě. Momentálně objednávka 000021503640104, VS 2017000565, kterou vidím v POS Merchant jako úspěšně autorizovanou, ale brána neposlala žádné údaje.
Je to jeden z více případů. Můžete vysvětlit a poradit?
Děkuji
Sýsová Marie

**Comment by jzahradnik** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem
Jan Zahradník

**Comment by Sysova** [comment]
V tuto chvíli jsou ve stejné stavu 4 požadavky - 3 jsou potvrzené a dostali jsme zpět informaci.
Sýsová

**Comment by ratajskym** [comment]
Vyřešeno mailovou komunikací
