### ISSUE TITLE
EET + opakované platby

### ISSUE THREAD

**Issue by tomasodl** [csob/paymentgateway#323]
Dobrý den,
Při implementaci brány potřebujeme implementovat opakované platby a zároveň mít vyřešeno EET.
Podle dokumentace vidím, že opakované platby lze provádět jen přes eApi 1.5 (ta nemá EET) přitom máte už 1.7 (ta má zase EET).
Jak je tedy možné toto řešit, abychom měli jak EET + opakované (pravidelné) platby kartou?

Děkuji
Tomáš Odl

**Comment by ratajskym** [comment]
Dobrý den, 

podívejte se prosím na následující dokument https://github.com/csob/paymentgateway/wiki/Platba-Na-klik 

To by Vám mělo pomoci

**Comment by tomasodl** [comment]
Dobrý den,
nejsme si jist zda je to řešení, které potřebujeme.
Integrujeme platební bránu pro neziskovou organizaci a chceme zavést pravidelné platby tedy každý měsíc se dárci strhne XKč (odobně jako byst zadal trvalý příkaz). Obdobně například zde https://www.darujme.cz/darovat/853?custom-amount=&portalWidget=1&referrer=https%3A%2F%2Fwww.darujme.cz%2Fprojekty&frequency=monthly 

Děkuji

**Comment by ratajskym** [comment]
Prvotvní transakce musí proběhnout za účasti zákazníka. Následující transakce již obsluhuje eshop. A to je podle mě přesně to, co potřebujete.

**Comment by tomasodl** [comment]
Děkuji moc. Máte pravdu.
