### ISSUE TITLE
implementace vlastnimi silami

### ISSUE THREAD

**Issue by pivaha** [csob/paymentgateway#324]
Dobrý den, máte prosím k dispozici materiály, pomocí kterých by si dokázal zprovoznit platební bránu na e-shopu běžný človek - tedy člověk s uživatelskou znalostí IT bez znalosti toho, jak fungují platební brány. Náražím zejména na provádění testovacích transakcí. Tohle  https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD mi opravdu nic neříká a nijak nepomůže.
Díky!

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod: TSGSMIPS-4560 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem

**Comment by vzich** [comment]
Dobrý den, 
pro běžného uživatele Vám můžeme nabídnout plugin pro Woocommerce - kód i návod na instalaci naleznete na linku - https://github.com/csob/paymentgateway/tree/master/WooCommerce%20Plugin. Pokud vám dané řešení nevyhovuje, doporučuji se porozhlédnout po pluginu pro platební bránu ČSOB na internetu, který by vyhovoval vašim požadavkům. Případně můžete kontaktovat programátora, který by vám vytvořil řešení na míru.

**Comment by zipajmichal** [comment]
Dobrý den,

připojím se se stejným dotazem.
Použil jsem plugin pro Woocomerce, dle návodu nastavil, vygeneroval testovací klíče a nahrál do složky /keys.
Testovací transakce dle návodu také nedokážu provést, lze to provést i jiným způsobem? Např. testovací rozhraní, kde se ověřují transakce a testovací karty oproti simulátoru?

Zkouším dělat testovací objednávky, ale po provedení objednávky mi hlásí "Inicilizace platby na platební bráně se nezdařila, nepodařilo se ověřit podpis odpovědi".
Na testovacím portále POSMerchant pak vidím transakci jako zamítnutou.

Mechant ID: 05639310

Díky,

**Comment by vzich** [comment]
Dobrý den,
jste si jist s vaším merchantID? Standardně začínají M1MIPSxxxx.

**Comment by zipajmichal** [comment]
Dobrý den,

pardon, místo ID jsem zaslal IČ.
MerchantID je M1MIPS1644.

Nicméně mezitím jsem se tím již prokousal, podařilo se mi otestovat v integračním prostředí a zvalidovat...nyní budu pokračovat do produkčního prostředí.

Zatím děkuji za podporu.

**Comment by vzich** [comment]
Děkuji za info.

**Comment by zipajmichal** [comment]
Dovrý den, ještě navážu, viz. email komunikace, narazil jsem u přechodu do produkčního prostředí.

Nemůžu vygenerovat privátní klíč na  https://platebnibrana.csob.cz/keygen/ protože nefunguje kombinace MerchantID: M1MIPS1644 a emailu, která fungovala bez problémů při generování testovacích klíčů zde https://iplatebnibrana.csob.cz/keygen/ 

Platební brána je navíc v produkční POSMerchant stále blokovaná.

Díky.

**Comment by vzich** [comment]
Dobrý den, 
jak píšete, jste stále ve stavu blokovaný. Odeslal jste požadavek do banky pro aktivaci (založka v integračním posmanu pro validaci)? Pokud ano, tak vás ještě v bance neaktivovali. Jakmile budete aktivován, tak přijde na mail vaší technické podpory zpráva o aktivaci. Až poté budete moci produkční klíče vygenerovat.

**Comment by zipajmichal** [comment]
Dobrý den,

ano, požadavek na aktivaci odeslán. budu tedy čekat na potvrzení bankou.
Děkuji.
