### ISSUE TITLE
Nefunkční test API

### ISSUE THREAD

**Issue by kopecmi8** [csob/paymentgateway#325]
Dobrý den,
ještě minulý týden mi v pohodě fungovalo testovací API https://iapi.iplatebnibrana.csob.cz/api/v1.6
Dnes od rána mi žádná z plateb pomocí "validních" testovacích karet neprochází. Dostanu vždy chybovou hlášku: _Bohužel se nepodařilo ověřit Vaši transakci u vydavatele karty. Zkuste, prosím, transakci provést znovu a v případě přetrvávajících problémů kontaktujte banku, která Vaši kartu vydala._
Při tom platba v simulátoru projde úspěšně 3D secure ověřením.
Ještě upřesním, že k testování používám anonymní MarchantID a vygenerované klíče.

**Comment by jzahradnik** [comment]
Dobrý den,

Váš požadavek byl zaevidován pod: TSGSMIPS-4559 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem
Jan Zahradník

**Comment by vzich** [comment]
Dobrý den,
vyzkoušejte prosím znovu, platba testovacími 3DS kartami by již měla být ok.

**Comment by kopecmi8** [comment]
Děkuji za rychlé vyřízení, už to funguje.
