### ISSUE TITLE
Krátká platnost klíčů

### ISSUE THREAD

**Issue by pacholik** [csob/paymentgateway#326]
Dobrý den,
klíče vygenerované pomocí _Create Sandbox ID_ na [ČSOB Payment Gateway Key Generator](https://iplatebnibrana.csob.cz/keygen/) mají mít podle popisu měsíční platnost.
Bránu lze však používat ani ne den a pak vrací už jen kód 400.

**Comment by ratajskym** [comment]
Dobrý den, postněte sem prosím Vaše merchant id.

**Comment by pacholik** [comment]
Nejdříve jsme dlouho používali A2105zq1hE, minulý týden však přestal fungovat. Vygeneroval jsem tedy A274250sSx a poté A27475wNM5, oba nevydržely ani den.
Dnes jsem vygeneroval A2761a780j.

**Comment by ratajskym** [comment]
Na testovacím prostředí dochází ve tři ráno k promazání anonymních id. Bohužel došlo ke smazání i nově vygenerovaných. Toto chování co nejdříve přenastavíme. 

Omlouvám se za komplikace

**Comment by ratajskym** [comment]
Problém s mazáním anonymních id byl odstraněn. Issue zavírám
