### ISSUE TITLE
Problem s implementaci

### ISSUE THREAD

**Issue by gerenok** [csob/paymentgateway#327]
Dobrý den,

Zákaznik poprosil nás o implementaci platební brany ČSOB. Během implementaci došlo k dalším problemů:

Proč dostáváme dálši odpověd:

----- Mon, 02 Oct 2017 14:33:29 +0000 ----- orderNumber 23
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- parts of orderNumber 23, 
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- Checking order 23, orderId 23
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- SELECT * FROM monetTransaction WHERE orderNumber=23
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- after select
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- cart created
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- loaded paymentStatus:  PayId: 
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- payment not inicialized OR payment cancelled or declined OR detected cart changes
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- payment/init, url: https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/init/
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- payment/init sign: M1E3CB2455|23|20171002143329|payment|card|2000|CZK|true|http://open.testa.pp.ua/wp-content/plugins/WooCommerceMonetGateWay/returnUrl.php?orderNumber=23|GET|Product name 1|1|2000|Test...|Product name 2|1|0|Objednavka 23|1|CZ
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- payment/init data: {"merchantId":"M1E3CB2455","orderNo":"23","dttm":"20171002143329","payOperation":"payment","payMethod":"card","totalAmount":2000,"currency":"CZK","closePayment":"true","returnUrl":"http:\/\/open.testa.pp.ua\/wp-content\/plugins\/WooCommerceMonetGateWay\/returnUrl.php?orderNumber=23","returnMethod":"GET","cart":[{"name":"Product name 1","quantity":1,"amount":2000,"description":"Test..."},{"name":"Product name 2","quantity":1,"amount":0}],"description":"Objednavka 23","merchantData":null,"customerId":1,"language":"CZ","signature":"idKJH5BwDlDhVVOLf2lLbV8INSAeofzxMBpHGIboMlycS6PKC7\/7iQyYiKvAZP4hjKf\/XpLfnFFrQOOx6eIvmdwW5F0IwZV\/VpHUAJriaphZsPGgYw5SaHeirpkAMvmxn+L1QKz+z665eyUH1zvRfGnOTYP+6v4AeaxiWl1aCLDWX9wb9cL8P\/myWW2rj1RLZfk77kbHrWaFVrh5YjJ1mZ7w7IJqAxVvZdDPqZCTyCEswokar1OZUWd3nWmHoU9QVPVtNoHiTOukqOtHqNuTjxEDgeYqyCU5S0A\/DjawB6xvDl2Sm+kr831THmmAkV\/1NEALU+kp5iEANHDqx2SDYQ=="}
----- Mon, 02 Oct 2017 14:33:29 +0000 ----- payment/init result:

Jak by měli to dělat abych to pracovalo v produkčním prostředi na https://aquavita-travel.ru/?

Jestli klíče se važou na domenu, proč dostavamé takovou odpověd?

S pozdravem,
Gerenok

**Comment by jzahradnik** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem
Jan Zahradník

**Comment by mrazekl** [comment]
Dobrý den,

Klíče jsou vázány k merchant ID, nikoliv k doméně. Ve Vašem případě máte chybu v podpisu, což může být způsobeno chybně vygenerovanými klíči, popřípadě když nedošlo k odeslání veřejné části klíče do banky. Doporučuji vygenerovat nové INTEGRAČNÍ klíče zde:
https://iplatebnibrana.csob.cz/keygen/
a veřejný klíč odeslat do banky.  Také je potřeba stáhnout veřejný klíč BANKY zde:
