### ISSUE TITLE
Implementace MasterPass (volání Ajax.get)

### ISSUE THREAD

**Issue by mlc73** [csob/paymentgateway#328]
Dobrý de n mohu poprosit o infromaci, kde stáhnu knihovnu, která implementuje valanou funkci Ajax.get a Ajax.redirect? Která je uvedena v ukázce (https://github.com/csob/paymentgateway/wiki/eAPI-v1.7):

function handleBuyWithMasterPass() {
    console.log("handleBuyWithMasterPass started ...");
    Ajax.get("/index.php?mpass-checkout-handler=a").then(function (data) {

	var mpassCallback = function(response) {
	     console.log(response);
	     Ajax.redirect(data.callbackUrl, 'get', response);
	};

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod: TSGSMIPS-4799 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem
Alexander Kocian

**Comment by vzich** [comment]
Dobrý den,
v příkladu to bylo myšleno pouze jako ukázka get redirectu.

**Comment by mlc73** [comment]
Dobrý den, to mně moc nepotěšilo. Asi budu tedy muset počkat než uděláte nějakou funkční ukázku do příkladů.

**Comment by janlanger** [comment]
@mlc73 má to jednoduše jen přidat k vaší callbackUrl GET parametry z response a přesměrovat na výsledek

ale bylo by fajn kdyby dokumentace říkala co má klient udělat, abychom nemuseli hádat co chtěli nějakým `Ajax.redirect` říct...
