### ISSUE TITLE
login na https://iposman.iplatebnibrana.csob.cz

### ISSUE THREAD

**Issue by pekoko** [csob/paymentgateway#329]
Dobrý den, 

chci se zeptat, jaké údaje mám použít pro přihlášení do testovacího prostředí POS Merchant.

zkouším údaje pro ostré prostředí a ty nefungují, na ostrém fungují. O jiných zvlášť pro testovací prostředí jsem nenašel ani zmínku.

Co dělám špatně? prosím o radu či vysvětlení.

s pozdravem,

Petr Kokoška
GrandIT s.r.o.

**Comment by mrazekl** [comment]
Dobrý den,

pokud zadáváte IČO a přidělené heslo a nemůžete se přihlásit do integračního(testovacího) prostředí, obraťte se, prosím, na akceptacekaret@csob.cz, kde v emailu uveďte ID brány, popřípadě IČO a Vaši situaci.

**Comment by pekoko** [comment]
Dobrý den,

udělal jsem jak jste mi poradil už v pátek minulý týden. Jak dlouho se čeká? Můžu udělat ještě něco?

děkuji,

S pozdravem,

Petr Kokoška

**Comment by lukasjanikcz** [comment]
Zdravím,
měl jsem ten samý problém. Tak dlouho jsem prudil technickou podporu, až mi změnili heslo na testovacím POS Merchant heslo a pak vše fungovalo. Celou dobu mi tvrdili, že je u nich vše v pořádku a že se tam přihlásit mohou :)

**Comment by pekoko** [comment]
Zdravím,

nakonec mi dnes (od pátku, takže mimo víkend, jsou to 3 dny) přišel email od: Platební brána [platebnibrana@csob.cz] s odpovědí na můj požadavek, který jsem posílal sem: Akceptace karet <akceptacekaret@csob.cz> s novým heslem pro iPOS Merchant rozhraní. Nikdo netvrdil, že jim to u nich jde :) - to už by bylo příliš.

Píšu sem pro ostatní s mým problémem.

Přeji všem hezký den,

Petr Kokoška
GrandIT s.r.o.
