### ISSUE TITLE
eAPI - přechod do produkčního prostředí

### ISSUE THREAD

**Issue by turcovsky** [csob/paymentgateway#33]
Dobrý den,

při implementaci nového eAPI píšete, že po provedení úspěšných testovacích scénářů máme toto potvrdit v POS Merchant. Prosím o navedení, kde se toto potvrzení v POS Merchant nachází.

Děkuji mockrát.
Turcovský

**Comment by ratajskym** [comment]
Dobrý den,

sloupec Akce -> ikona lupy (title Validace)

Stisknout tlačítko "Provést validaci"

**Comment by turcovsky** [comment]
Děkuji mockrát.
Turcovský

**Comment by turcovsky** [comment]
Ještě se zeptám po úspěšné validaci jsem odeslal požadavek na zprovoznění produkčního prostředí. Informaci o možnosti spustit produkční prostředí dostanu emailem registrovaným v POS Merchant nebo jakou cestou budu informován?
Děkuji
Turcovský

**Comment by ratajskym** [comment]
Budete informován ze strany banky.

**Comment by turcovsky** [comment]
Děkuji za informaci.
Turcovský.

**Comment by turcovsky** [comment]
Dobry den jiz je to vice jak jeden tyden co mame schvalene testy pro prechod do produkcbiho prostredi. Z banky CSOB nas vsak stale nikdo nekontaktoval. Jak dlouho trva nez mne banka kontaktuje a je nejaky kontakt kde bych mohl urgovat? 
Dekuji za odpoved.
Turcovsky

**Comment by radehorak** [comment]
Dobrý den, můžete nám poslat ID platební brány na mail platebnibrana@csob.cz.
Děkuji moc.
Radek Horák

**Comment by ratajskym** [comment]
@turcovsky 
Dobrý den, jak to vypadá s Vaším přechodem do produkce?

**Comment by turcovsky** [comment]
Dobry den. 
Mame schvaleno, takze pokracujeme na produkcnim prostredi.

Turcovsky
Odeslano z mobilniho zarizeni

----- Původní zpráva -----
Od:"Martin Ratajský" <notifications@github.com>
Odesláno:‎28. ‎8. ‎2015 9:04
Komu:"csob/paymentgateway" <paymentgateway@noreply.github.com>
Kopie:"turcovsky" <tomasturcovsky@gmail.com>
Předmět:Re: [paymentgateway] eAPI - přechod do produkčního prostředí (#33)

@turcovsky 
Dobrý den, jak to vypadá s Vaším přechodem do produkce?
