### ISSUE TITLE
When cancel payment redirect to success page

### ISSUE THREAD

**Issue by ketannsangani12** [csob/paymentgateway#331]
Hello,

When I have clicked on cancel payment in payment gateway it redirects me to url which specified in returnurl?I want to it redirects me to my home page

Please help me

**Comment by vzich** [comment]
Yes, you are correct. It redirects you to the link you specified in payment/init.

**Comment by ketannsangani12** [comment]
But I want to redirect when cancel on other link and when payment successfull redirect should on other link

**Comment by vzich** [comment]
Then you have to do it on eshop side, according to payment status which the payment gateway returns(e.g. 3 and 6 will have different behaviour than status 4 or 7 - [documentation](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7-EN#return-values-)). You can define only one returnUrl in payment/init call.

**Comment by ketannsangani12** [comment]
Thanks
