### ISSUE TITLE
Opakovaná platba  - 150:Payment not in valid state

### ISSUE THREAD

**Issue by klimoma** [csob/paymentgateway#332]
Dobrý den,
od dnešního dne mi nefungují na testovacím prosředí opakované platby a dostavám vždy odpověd 150:Payment not in valid state. 

MerchantId: A2784qhz1F
Autorizační transakce má payId = b346e58a46bb0CJ
Následná transakce má payId = cff47e4fb608cCJ

Můžete mi prosím poradit, kde by mohl být problém?
Děkuji

**Comment by vzich** [comment]
Dobrý den,
reverzované transakce nelze použít jako šablony pro oneclick platby, pokud chcete návrátit prostředky a použít ji prvotní platbu jako šablonu. Je nutné aby prošla clearing a poté až provést refund transakce.

**Comment by klimoma** [comment]
Ale do nedávna toto fungovalo. 
Pokud teď registrační platbu v hodnotě o 1kč nezruším dostanu se do stejného stavu.
Autorizační transakce má payId = b953cd72de7b3CJ
Následná transakce má payId = f263a575652ddCJ

Potřebuji udělat registrační platbu hodnote 1kč, kterou následně mohu používat jako šablonu pro všechny následující platby.

Děkuji

**Comment by vzich** [comment]
Po reverzaci transakce (tzn. jakmile se dostala do stavu 5), nebylo nikdy možné použít jako šablonu. Co se týče registračních plateb, tak je třeba aby prošly clearingem, dostaly se do stavu 8. Poté je již můžete refundovat a šablona můžete i nadále používat.
Prověřil jsem transakci f263a575652ddCJ a byla korektně autorizovaná, v čem je tedy problém?

**Comment by klimoma** [comment]
Ja dostavám stale resultCode 150.
aktualne na transakci cf976ee975131CJ.

**Comment by vzich** [comment]
Můžete poskytnout váš log? Posledni resultCode 150 evidujeme u vaší brány pro payID -c5ab66dcb8020CJ. 
Na vaší transakci cf976ee975131CJ jste si zavolal i payment/status a vrátil se vám status 7 - autorizováno.

**Comment by JanPolan** [comment]
Dobrý den, 
    Pracuji na stejném systému jako klimoma. Problém s resultCode 150 se týká naší kontroly, kde se kontroluje stav provedené platby. 
Problém spočívá v tom, že očekáváme platbu ve stavu 4 - Platba potvrzena. Zjištěný stav platby je ve stavu 7 ( již automaticky zaúčtována ). V systému potřebujeme volat zakončení platby později na finální částku. 

Nyní, pokud je template platba již zaúčtována, platba byla provedena v režimu bez automatického zakončení ( zakončení je prováděno jako samostetné volání API payment/close  ). Následná „Platba na klik“ je již zpacována v režimu automatického zaúčtování.

Moje otázka tedy zní, je možné provést „platbu na clik“ v režimu bez automatického zaúčtování?  

Děkuji

**Comment by vzich** [comment]
Dobrý den, 
pokud chcete oneclick platbu poslat do zúčtování pomocí metody payment/close, tak musíte i vaši prvotní platbu poslat do zúčtování až později. Tzn. při založení prvotní platby zasílat parametr _"closePayment":false_. Oneclick platby dědí toto nastavení ze své prvotní platby.

**Comment by JanPolan** [comment]
Ano, takto postupujeme.
Template platba:  e1d8485a01f83CJ   - nastaveno closePayment":false
„Platba na klik“  0a49a1393cbc3CJ - automaticky se vrací stav 7 i bez volání zakončení ( voláme init a start ).

MerchantId:  A2784qhz1F

Mohl bych Vás požádat o prověření této platby, pro zjištění, kde by mohl být problém?

Děkuji

**Comment by vzich** [comment]
Dobrý den,
omlouvám se za prodlení. Můžete prosím vyzkoušet znovu? Vaše platby na klik by již měli zůstat ve stavu 4.

**Comment by JanPolan** [comment]
Dobrý den,
  provedli jsem nové testy a následná platba na klik již zůstává ve stavu 4.
 Děkuji
