### ISSUE TITLE
Problém s generací klíčů pro integraci

### ISSUE THREAD

**Issue by pekoko** [csob/paymentgateway#334]
Dobrý den,

nejdou mi vygenerovat klíče pro integraci. Hlásí špatné MID (MerchantID) nebo email. Funguje pouze s anonymním MID pro sandbox na jakýkoliv email. 

Zkoušel jsem MID co jsme dostali ve formuláři pro registraci obchodníka a také ID označené jako MID v emailu po aktivaci do intergrace: " na základě smlouvy o akceptaci platebních karet bychom Vás tímto chtěli informovat, že Váš internetový obchod byl aktivován v integračním prostředí pod následujícím označením:......" ID v tomto emailu označené také jako MerchantID je ve skutečnosti ID platební brány...

Každopádně ani jedno generátor nebere. Email pro komunikaci mám správný, několikrát jsem kontroloval se smluvní dokumentací a zkusil pro jistotu i jiné použité emaily.

Psal jsem na akceptacekaret@csob.cz a platebnibrana@csob.cz, zatím bez odpovědi. (1 a 2 dny zpět)

Může mi někdo z kolegů poradit, jestli tam dávám prostě špatné údaje nebo je chyba jinde?

S pozdravem,

Petr Kokoška

**Comment by jzahradnik** [comment]
Dobrý den, 

Ujistěte se prosím, že jste skutečně na stránce generátoru klíčů pro integrační prostředí. https://iplatebnibrana.csob.cz/keygen/
Zde zadejte jako merchant ID :  ID platební brány (M1MIPS****)
jako e-mail: email technické podpory.

Pokud bude problém přetrvávat, tak bych vás poprosil o poskytnutí MerchantID, abychom mohli řešit konkrétní problém, na konkrétní platební bráně. 

S pozdravem 
Jan Zahradník

**Comment by vladimirmatl** [comment]
Dobrý den,
mám stejný problém.
Email technické podpory je jaký? helpdeskeb@csob.cz? platebnibrana@csob.cz (obojí jsem zkoušel a nic).
Merchant ID je M1MIPS1602.

díky za prověření.
Vladimir Matl

**Comment by ratajskym** [comment]
Dobrý den, 
jako email technické podpory uvádíte SVŮJ email technické podpory, který jste uvedli do smlouvy o platební bráně

**Comment by pekoko** [comment]
Dobrý den,

Návrh na změnu ve Wiki:

Toto:

"První fáze integrace následuje po sjednání poskytování služeb eCommerce v bance, kde obdržel obchodník své MerchantID a **uvedl, ze které emailové adresy bude s bankou komunikovat.** V tomto okamžiku již jeho identita v systému platební brány existuje a vyčkává na další kroky takto:"

Na:

"První fáze integrace následuje po sjednání poskytování služeb eCommerce v bance, kde obdržel obchodník své MerchantID (ID platební brány) a uvedl, ze které emailové adresy bude s bankou komunikovat. Jedná se o email technické podpory, který jste vyplnili do formuláře pro registraci obchodníka. Také ho naleznete v detaile platební brány na rozhraní POS Merchant. V tomto okamžiku již jeho identita v systému platební brány existuje a vyčkává na další kroky takto:"

U mě se ještě stalo k mému zmatení, že emaily co jsme zadali do formuláře pro registraci mám v detaile platební brány v POSu vyplněné obráceně!

**Comment by ratajskym** [comment]
Děkujeme za podnět. 

Všechny návrhy na vylepšení wiki nebo aplikace jsou vítány. Pokud máte nesoulad v emailech, obraťte se prosím na mail akceptacekaret@csob.cz a věřím, že dojde k narovnání situace.

**Comment by pekoko** [comment]
Hlavně ho použijte :)

Po pochopení těchto zásadních drobností je integrace velmi snadná a pohodlná, validace testů přes rozhraní je parádní. Nekažte si to.

Děkuji za podporu.
