### ISSUE TITLE
Verifikace při přechodu z GPWebpay

### ISSUE THREAD

**Issue by jan1971** [csob/paymentgateway#336]
Dobrý den.
Naše MerchanID: M1E3CB3547
Máme problém při verifikaci návratových hodnot při přesměrování z brány. Přecházíme z GPWebpay.
Klíč pro platbu i přechod na bránu jsou OK.
Návratová adresa:
http://www.xxxxxx.cz/shop/kosik/online-platba/paymuzo/response/7428203290/?OPERATION=CREATE_ORDER&ORDERNUMBER=289&MERORDERNUM=2799&MD=&PRCODE=50&SRCODE=0&RESULTTEXT=Cardholder%20canceled%20payment&DIGEST=HmQuC%2FBCZnoCNDuwdiYBoqno%2Fb5Og5AdKOEd1PQyuHya4iFpa1ygSvIPdlKpZEkf%2FRMFokXzArZEhuFsfySaSTmI2tKx3M7x51Pnw2ev%2BJtmdDBxOvvHaC8NP%2Btbz8yspZLpJutlshgvepbPEvBfWLj18qewLCurVtaIw%2FJznem8sDcydlB9Se2AEBFCHhkSCU63BmA0tv7Y8ucNsXwKy7Upm7G00PbncOU8VHbbfqbBcBjbMd39TE24ywZGcgoYBtR48if078wMiFihP%2BsJUdAOzkFF25TZULwBpxoqp1E5lB59DtKK7faaGDn8Tmjnd7aX8s73EMyQGxOn0YZWEQ%3D%3D&DIGEST1=R5%2BGO29nLsC04jWAkRLCWE02CT7g%2F5%2FJLKWKdR4z3%2B%2F0Ox9fmntFNIN%2FwaixyQEDSXClGMo0PMgeINOyVNEDqZsNmQ8aV6aqn4Z%2FA5yBZk7EwysfL%2BjE6elkJlpQnJKo22bO8xnGE7rjY5Ra5SxNk2JJyhX0Zo33ENztQ19fp8SnVd3skkbjfZU7hvD0B1rWXBK4nIeioQiZauUuTlANPH8%2FE%2Brc1ayh0z9LJUWZlz3k3mBkFmzZ9V9sYafmuYIz4As4Md3mWnjz85tPZzVAvnZvp6c7%2Fj37xN3uRBnY9WPdXz8IaGFpPAnAi75BCEvo%2BP%2FSZKVZlnDccNIJ0tQVIg%3D%3D 
Text:
CREATE_ORDER|289|2799|50|0|Cardholder canceled payment

openssl_verify z použitým .pub klíčem vrací 0 :(

Děkuji za radu.
Pěkný den.

**Comment by ratajskym** [comment]
Dobrý den, používáte správny .pub klíč ?

**Comment by jan1971** [comment]
rsa_M1E3CB3547.pub - ten který se vygeneroval z rsa_M1E3CB3547.key, který zdá se funguje, protože do brány se dostaneme.
Odsud: https://iplatebnibrana.csob.cz/keygen/
Děkuji!

**Comment by ratajskym** [comment]
Komunikace Eshop -> Platební brána
rsa_M1E3CB3547.key - Váš privátní klíč, kterým podepisujete požadavky odesílané na platební bránu
rsa_M1E3CB3547.pub - Váš veřejný klíč, který jste odeslal pomocí tlačítka na platební bránu, a který bude sloužit platební bráně pro ověřování podpisu požadavků, které odesíláte

Komunikace Platební brána -> Eshop
platební brána podepíše požadavek svým privátním klíčem
Eshop pomocí veřejného klíče ověří správnost podpisu - tento veřejný klíč naleznete zde https://github.com/csob/paymentgateway/tree/master/keys

Postupujte prosím podle návodu zde
https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

**Comment by jan1971** [comment]
I s klíčem mips_iplatebnibrana.csob.cz.pub vrací openssl_verify 0 :(
Děkuji

**Comment by jan1971** [comment]
Děkuji za pomoc. Není chyba v textu?
CREATE_ORDER|289|2799|50|0|Cardholder canceled payment
Narazil jsem na info, že se možná nemá posílat Resulttext...

**Comment by ratajskym** [comment]
Máte zalogované, co Vám vrátila platební brána? Můžete nasdílet včetně podpisu, který se snažíte ověřit ?

**Comment by jan1971** [comment]
30.10.2017 13:37:33 -- Odesláno do brány:https://iplatebnibrana.csob.cz/pay/entry/merchant?MERCHANTNUMBER=M1E3CB3547&OPERATION=CREATE_ORDER&ORDERNUMBER=302&AMOUNT=19200&CURRENCY=203&DEPOSITFLAG=1&MERORDERNUM=2816&URL=http%3A%2F%2Fwww.grena.cz%2Fshop%2Fkosik%2Fonline-platba%2Fpaymuzo%2Fresponse%2F16913494976%2F&DESCRIPTION=Objednavka+z+eshopu&MD=&DIGEST=Ac8GCanf8eEVog2%2BPsq7eA2OovlkLPDy249VI9k7BXGXH2J9wL2qWX2iQq2HTzcRjZbeERqTMKT0tJxe0p8uRKwiDsjJhTzglRSHOSr6bYTdR05iBtTiS7XEotuhuqmQc6LZ5djPnRitJOU6RBTLPfO9XWxK0j%2BI69qvBX70jFR%2FIc55FxYNTKobcIUw%2FbbiPPjLAa%2BmV2rTkbYlHOTC27%2BfYx5JS7O1qoNWEpii9OrFH2vPrixu%2FoPjs27bHGY3uoKZfqvsKKQYNr4JxPHmrHa7SjaXMmjPoGPz19teeOxmcau0%2FZPCW6pDvTU4c4DsjE0WL98vqTWsviPnW7xqnQ%3D%3D

30.10.2017 13:37:43 -- Přijato z brány:CREATE_ORDER|302|2816|50|0|Cardholder canceled payment-----Digest:E/Smln1+F9p0IErR+PEqaD2Mfttlhy9Cp/kB/5aHWKem+Vpz6AoSFENYUg/1UcI7fF9MkwGTH2VkAXdsJ6edX5s59rhk84XRZYBhDjZ1IQzPwUoX6eDLEufLmUJPA2MKRUsSh1DBBp4t5RWg7LaXbw7u8HYLcOcXJoyaKnuuf0g8R2h+A4JPOHmeRqmMAdfLAofSSonJ3UCS4wrim+vUPK4zybrrSJd0bOIRT9FXKEABnsXeAvN8Rz1eJdiuYWAogr1Bg8bvavrfnFSplvkl+8ZbT/HguErUAJO0QGw3h40Qp07sPIUkWR5dAGXSPA+LCZIK5en430czWaw4lPMJXg==

**Comment by jan1971** [comment]
Dobrý den.
Testovací platba (testovací karty) projde přes bránu, vše OK.
Ale neobjeví se v https://iposman.iplatebnibrana.csob.cz/
Zapisuje se se zpožděním?
Děkuji za pomoc.

**Comment by jan1971** [comment]
Už ji vidím. Děkuji.
