### ISSUE TITLE
Response signature verification

### ISSUE THREAD

**Issue by Vesuvium** [csob/paymentgateway#337]
Hi :)
I am having trouble in verifying the response signature in the testing environment. I can submit requests successfully, but I can't manage to verify the signature, neither by using the public key or signing again the payload with the private key, or matching it with the signature I have sent.

The documentation says that the response has a signature, but the gateway does not store the private key, so I am puzzled at how I should verify the signature. Am I missing something?

I am using A2859E0Wjm as merchant id

**Comment by aKocian** [comment]
Hello,
Did you try download paymentgateway public key?
Try this option to verify signature.
You can download it there : https://github.com/csob/paymentgateway/tree/master/keys
production: mips_platebnibrana.csob.cz
test: mips_iplatebnibrana.csob.cz

**Comment by Vesuvium** [comment]
That was it. I must have missed the part that says to downloads CSOB's public key. Thanks!
