### ISSUE TITLE
Opět chyba 400

### ISSUE THREAD

**Issue by michalpetrek** [csob/paymentgateway#338]
Dobrý den.
Minulý týden jsem začal nově s implementací vaší platební brány. Zahájil jsem intergraci a při pokusu provést platbu se mi vždy vrací errorCode 400. Jak v mém kódu tak i když se snažím vyzkoušet přímo Váš example code php v1.6 - bez úprav na stejném stroji (nevadí že testuji ve vitřní síti ? response url ale nastavuji na veřejný server aby to Vase API melo kam poslat).
Ani z jednoho to neprojde a skončí 400. Zkoušel jsem najít řešení zde v Issues, zkusil jsem pár tipů ale stejně. Také jsem dnes zkusil vygenerovat a použít nové klíče a merchantID (Your request has ID: 4569) ale to také nepomohlo. Prosím o pomoc při implementaci a řešení tohoto problému.

Děkuji
Michal

----------------------

url => "https://iapi.iplatebnibrana.csob.cz/api/v1.6/payment/init/" (58)
content_type => NULL
http_code => 400
header_size => 379
request_size => 984
filetime => -1
ssl_verify_result => 0
redirect_count => 0
total_time => 0.079875
namelookup_time => 0.004149
connect_time => 0.010972
pretransfer_time => 0.044275
size_upload => 815.0
size_download => 0.0
speed_download => 0.0
speed_upload => 10203.0
download_content_length => 0.0
upload_content_length => 815.0
starttransfer_time => 0.079857
redirect_time => 0.0
redirect_url => ""
primary_ip => "193.245.34.231" (14)
certinfo => array ()
primary_port => 443
local_ip => "192.168.156.43" (14)
local_port => 47716

--------------------------------------------

{ "merchantId": "A2909gSiq7", "orderNo": 1, "dttm": "20171113112757", "payOperation": "payment", "payMethod": "card", "totalAmount": "492", "currency": "CZK", "closePayment": 0, "cart": [ { "name": "tajne...", "quantity": 1, "amount": "492", "description": "BLA BLA BLA od 14.11.2017 do 17.11.2017" } ], "description": "BLA BLA - rezervace", "language": "CZ", "returnUrl": "http://tajne/rezervace/dokonceno", "returnMethod": "POST", "customerId": 151, "signature": "L22X0uBb1s3QlPzOLSTSuGH40MgB1lXjA+/tzeUQcNv6Goo6nOeHo3Skt/VE7ZubpfY9DsRUeo1sQYaIwINITi8+5ukFL7ev5nI1H4S5tKPj9cCZagZY3kq/sXh7w44ijSuugzrZmN/zwkhotAChf+FLarQAhDH0Ff++V96ufOpNUxcOVArGst9yEbL5+cvkxZbL3f4yDd36Fc8F0M3TaKawF+38hlmV/PnDPkYun9vw6i5gdQ0m3uL5+NLuheoSF9kdyxl2nWKxuxsQROiwlRznVYIEysyYseO8DOsB62ZYYtBptz4OCBQkQHTFJW9dzSIVBG1d3aXJa8/w9q1Urg==" } 

--------------------------------------------

data to sign: "A2909gSiq7|1|20171113115033|payment|card|492|CZK|0|http://tajne/rezervace/dokonceno|POST|blabla|1|492|BLA BLA BLA od 14.11.2017 do 17.11.2017|BLABLA.cz - rezervace|151|CZ"

Signature: WYYBV1Pyrv3BbMn3fqsRtddbevzSa4xEFbpJP3jM4m3h/hRb078DyaCsH+IXPR4l2KpgxgKW35qIDBKupuzGGAgyJwsbqG8y+UxvAzvSKCEVB6oSBBKo/mRQ6AwVane03rE13JrOUfcqFAJ/7TT9BqzXzX64MuZoWNM5c5mIMrqNeji4V1qldDBjN3uHMImIJpklApDOSadxbfzpEPXpCpqfo6RYhs2wGoOdOgYF4uYQjufu4EMi7/xh+K5VEScycMXRGoemoRDeRpC6OuxYB/F+TmysbvnKF4FBZwJZ23VI9JW8aE8IoaKHm3z1yzDGBgvrL3Mk0ipGUNrQ7rE37w==

**Comment by mjanek** [comment]
Dobrý den, 

v první řadě zkuste změnit parametr closePayment na "false" a zkontrolujte zda používáte opravu správný privátní klíč, který jste si vygeneroval. 

M.Janek

**Comment by michalpetrek** [comment]
Dobrý den,

ano tak closePayment jsem upravil zpet na False (to jsem zkusil dnes rano dat 0 pac jsem se nekde docetl ze pro PHP pouzit 0 nebo 1) - upraveno.
V metode signPaymentData jsem vypsal klíč který používám a je to "rsa_A2909gSiq7.key". Coz je shodny s nove vygenerovanym A2909gSiq7.

**Comment by vzich** [comment]
Dobrý den,
posíláte parametr "merchantData":null, v tomto případě je přidat "pajpu" do vašeho řetězce. Tzn. podepisoval byste podle vašeho příkladu tento řetězec, "A2909gSiq7|1|20171113124347|payment|card|492|CZK||http://tajne/rezervace/dokonceno|POST|Blablabla|1|492|BMW i316 Sedan bezín od 14.11.2017 do 17.11.2017|BLABLA - rezervace||151|CZ"

Případně pošlete nějaká data v base64 v parametru merchantData.

**Comment by michalpetrek** [comment]
Dobrý den,

upravil jsem merchantData na hodnotu base64, dále jsem si v parametru closePayment zmenil z True na "True" a už to jede...  :-D ja vim.... a mockrat dekuji...
