### ISSUE TITLE
"Platba nenalezena" - integrační prostředí

### ISSUE THREAD

**Issue by itstudiocz** [csob/paymentgateway#34]
Dobrý den,

přecházím z GP WebPay na ČSOB a mám problém, při zaslání tohoto požadavku:

```
https://iapi.iplatebnibrana.csob.cz/pay/entry/merchant?MERCHANTNUMBER=A1136U7DWF&OPERATION=CREATE_ORDER&ORDERNUMBER=1500018010&AMOUNT=12000&CURRENCY=978&DEPOSITFLAG=1&MERORDERNUM=1500018&URL=skryto&DESCRIPTION=test%20test&MD=&DIGEST=fQm6PDAbKMTIMPBWuv%2Bqizb%2Fxb63G123LLu55kdoS41GpcTGnjBHkH625N0gDRb8ZbvbzzStwMNN2zZhnhoivTSnSh1%2FKyvKM1v8Bb%2BOC7Qn%2FvTHuN3uX9iVHYUA2PQyUFWm3A9VNwS2BfJ2X0udQtokVb%2F84zpN5smfV%2BzIxsP86UYM%2FLpBdXy1OwYaka14bdloAMaYiiirqv2IOdCTGDB1UzKBTTvkfRXueKerStFKhbWj%2BD%2F1p2pqkG23uzYndQiSrFqv1X%2Fcbhh96yOSLKAlRgejPRSMMboaBk5FTXl5HAeO80YB%2BzLouk86%2BNWKnnm%2FRJCtMjxCWVlWxUVD3w%3D%3D
```

mě brána přesměruje na tuto adresu: https://iplatebnibrana.csob.cz/pay/not-found.html
Klíč jsem vytvořil a zprávu s ním podepsal, merchant number lze vidět v URL.

V dokumentaci jsem bohužel o této chybě nic nedohledal, prosím tedy o detailnější informace.

**Comment by ratajskym** [comment]
Dobrý den, 

svůj požadavek posíláte na špatnou url. Věnujte prosím pozornost tomuto článku
https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

**Comment by itstudiocz** [comment]
Dobrý den,

děkuji, tím se to vyřešilo (stačilo odmazat iapi. z URL), nicméně si myslím, že by i tato adresa měla být v článku o přestupu z GP WebPay na ČSOB. Buď jsem to přehlédl, nebo se integrační adresa v článku nevyskytuje a musel jsem po ní pátrat v jiných částech dokumentace.
