### ISSUE TITLE
Problem s neaktualnim stavem transakce

### ISSUE THREAD

**Issue by mfeuermann** [csob/paymentgateway#340]
Dobrý den, 

obracím se na Vás s následujícím problémem, který se nám dnes objevil na produkčním prostředí.
Nas MechantId je M1E3CB3838. Pokud někdo udělá transakci na platební bráně, transakce proběhne v pořádku, informace o správném stavu se nám vrátí, stav transakce na Posman je Autorizace potvrzena/Posláno k zaúčtování. 

Problém je v tom, že jsme v době, kdy je transakce ve stavu potvrzeno snažili mnohokrát dotazovat brány na status platby pomocí /api/v1.7/payment/status/ nicméně brána nám správný stav platby nevracela... 

V minulosti se brána chovala správně, takto nám to běží několik měsíců. Dnes bez změny jakéhokoliv kódu na produkci se to ale chovalo jinak.

Brána prostě pomocí /api/v1.7/payment/status/ nevracela aktuální stav.

Měli jste prosím evidovaný nějaký výpadek ? Případně může se stát, že stav platby pomocí statusu není aktuální ?

Předem děkuji za support!

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek jsme zaevidovali a předali k řešení odpovědnému kolegovi. 

s pozdravem

Spisar

**Comment by mfeuermann** [comment]
Diky!

**Comment by ratajskym** [comment]
Dobrý den, 

výpadek na platební bráně nebyl. Vámi popisované chování je velmi nestandardní. Pojďme se prosím zaměřit na něco konkrétního. Dokážete říct, který konkrétní payment/status jste volal, co jste očekával a jaká hodnota se vám vrátila ?

**Comment by mfeuermann** [comment]
ID transakci, u kterych jsme nedostali spravnou odpoved : d4ec00d52a76dCK e09dd691108cdCK
u f7ea8ed202534CK bych se zastavil, to tam mame stale...  
Od brany ocekavame stav 7, 6 pripadne 3 (mame nastaveno automaticke zuctovani) ani jeden z techto stavu se ale zda, ze se nevraci... Z logu take vidim, ze v urcite casove useky napr dnes v 8:23 cca 15 minut nebyla brana dostupna vubec a pri dotazech na branu byla chyba dostupnosti. Jeste bych podotknul ze u plateb na ktere cekame se brany dotazujeme kazde cca 2 minuty u jednotliveho pripadu... tzn fakticky cca 8 dotazu za / 2m... bylo by prosim mozne u zminovanych plateb overit jestli zde neni nejaky problem ? Dekuji

**Comment by ratajskym** [comment]
Ani u jedné transakce, které uvádíte nevidím na serveru dotaz na status. Což je divné, protože u jiných transakcí vás vidím
d4ec00d52a76dCK - žádný požadavek 
f7ea8ed202534CK - žádný požadavek
e09dd691108cdCK - žádný požadavek 

Postněte prosím přesnou adresu (celou url), kterou v těchto případech voláte

**Comment by mfeuermann** [comment]
Dobrý den,
ještě jsem problém zanalyzoval a objevil jsem chybu, která způsobovala to, že jsme se brány ptali v poslední době příliš často. Chtěl jsem se zeptat, jsou zde definovány nějaké limity a omezení které nás v důsledku odpojí ? Děkuji za informaci.

**Comment by ratajskym** [comment]
Tohle jsem s Vámi chtěl probrat později. O limitu bohužel nevím, nicméně si dokážu představit, že pokud se budete ptát opravdu přiliš často, zařízne Vás infrastruktura na podezření z DDOS.

I přesto bych měl v logu vidět některou z uvedených transakcí. Nespojujme dvě issue, pojďme dořešit volání status. Nebo již není potřeba a vyřešil jste na své straně ?

**Comment by mfeuermann** [comment]
Omlouvam se, ano vyresil jsem na sve strane, zjistil jsem, ze mi brana v urcity cas prestala odpovidat. Po znovuspusteni procesu jsem dostal spravnou odpoved na zminovanou transakci. Je kazdopadne jiste, ze se tato vec stala pri vetsim poctu uhrazenych objednavek a objevil jsem, ze se nasi chybou ptame zrejme casto. Opravili jsme hotfixem, ktery brzo budeme nasazovat do produkce... Pokud tedy informaci o limitech nemate dekuji Vam za cas a podporu...
