### ISSUE TITLE
HTTP 404 při masterpass/basic/checkout

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#342]
Dobrý den, dostávám při volání masterpass/basic/checkout na testovací bráně odpověď HTTP 404

Máme něco špatně nastaveno, nebo kde je chyba?

```
Nov 21 13:44:23 csobGateway: POST payment/init 200 {"merchantId":"M1E3CB0860","orderNo":"7057528514","payOperation":"payment","payMethod":"card","totalAmount":399000,"currency":"CZK","closePayment":true,"returnMethod":"GET","language":"CZ"} 
{"payId":"12bfa91b147c7CK","resultCode":0,"resultMessage":"OK","paymentStatus":1}


Nov 21 13:44:23 csobGateway: POST masterpass/basic/checkout 404 {"merchantId":"M1E3CB0860","payId":"12bfa91b147c7CK","callbackUrl":"https://slevomat.local/objednavka/masterpass/finish/..."} 
```

minulý týden vše fungovalo

**Comment by jzahradnik** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu 
Vás bude informovat odpovědný servisní technik.

S pozdravem
Jan Zahradník

**Comment by vzich** [comment]
Dobrý den,
volání mpass basic checkout je dostupné až od verze eAPI 1.7., dnes jste ale zasílal requesty s verzí eAPI 1.6. Použijte tedy novější verzi.
Kontroloval jsem pokusy z minulého týdne a to jste eAPI 1.7 použil. 
S pozdravem 
VZ

**Comment by janlanger** [comment]
🤦

díky :)
