### ISSUE TITLE
Chování js obsluhy masterpass na integrační bráně

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#343]
V dokumentaci mpass@shop (https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#platba-pomoc%C3%AD-masterpass-) je uvedeno, že po potvrzení platby z peněženky dojde k zavolání javascriptového callbacku (v dokumentaci `mpassCallback`) který zajistí přesměrování na endpoint kde se má zavolat `masterpass/basic/finish`

Přijde mi že se tenhle callback v integrační bráně vůbec nevolá, ale rovnou odněkud z vašeho JS dojde k přesměrování na `callbackUrl`. Chová se to stejně při úspěšné platbě i zrušení.

Kdy se ten callback zavolá? Jak se chová produkční masterpass?

**Comment by mrazekl** [comment]
Dobrý den,
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu
Vás bude informovat odpovědný servisní technik.

**Comment by dmarek** [comment]
Náš simulátor na ibráně prozatím implementuje pouze ten legacy způsob, tzn. přímy redirect na callbackUrl (takto se to u MasterPass chová v produkci v případě nějakého staršího prohlížeče anebo v případě, že wallet expanduje do fullscreenu, což se může stát v případě, že není předán na mpass jeden z parametrů v rámci inicializace session).
 
Doplníme tedy do simulátoru volání js callbacku (nejspíš včetně možnosti provolat buď jeden nebo druhý způsob).

**Comment by janlanger** [comment]
@dmarek to doplnění by mohlo být v jakém časovém horizontu?

**Comment by dmarek** [comment]
příští týden by to mohlo být na ibráně

**Comment by dmarek** [comment]
na integracnim prostredi nasazena nova verze mpass sim obsahujici nove moznost volani js callbacku, upravena dokumentace v kapitole https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#integrace-javascript-vol%C3%A1n%C3%AD-do-eshopu
