### ISSUE TITLE
Podpora Legacy API

### ISSUE THREAD

**Issue by ssteklik** [csob/paymentgateway#345]
Na hlavní stránce dokumentace se píše: "Legacy API nebude již nadále rozvíjeno a proto doporučujeme v horizontu do léta 2016 vyvinout ve vašem e-shopu podporu eAPI. Jedině tak budete moci využívat všechny chystané funkce nové platební brány." 

Uvažuje se o v nejbližších měsících o vypnutí Legacy API? Rádí bychom ho přechodně (cca do konce února) používali, než implementujeme novou platební bránu (přecházíme z GP Webpay).

**Comment by jzahradnik** [comment]
Dobrý den, 

Legacy API bude do konce února určitě v provozu. Není tak problém s jeho dočasným užíváním. 

S pozdravem 
Jan Zahradník

**Comment by ssteklik** [comment]
Díky, ještě pro ujištění - při použití Legacy API není třeba provádět testovací scénáře pro přechod do produkčního prostředí?

Šimon Steklík

**Comment by jzahradnik** [comment]
Při použití Legacy API skutečně není třeba provádět testovací scénáře na přechod do produkce.
