### ISSUE TITLE
Result code 180 při zrušení masterpass platby

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#346]
Dobrý den,

při zrušení mpass@shop uživatelem brána na finish request někdy vrací divný result code 180 - operation not allowed. Jindy vrací result code 270 - mpass canceled by user který bych očekával.

Je to správné chování? A pokud ano, mohli byste to zdokumentovat?

Požadavek např. `POST masterpass/basic/finish 200 {"merchantId":"M1E3CB0860","payId":"c1d2a3eed7b4eCK","callbackParams":{"mpstatus":"cancel"}} {"payId":"c1d2a3eed7b4eCK","resultCode":180,"resultMessage":"Operation not allowed"}`

**Comment by aKocian** [comment]
Dobrý den,

Váš požadavek byl zaevidován pod: TSGSMIPS-5152 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem
Alexander Kocian

**Comment by dmarek** [comment]
opravili jsme validaci parametrů u volání masterpass/basic/finish a masterpass/standard/extract - nyni se jiz bude korektne vracet  result code 270 - mpass canceled by user, oprava validace spocivala v tom, ze se pouze pro mpstatus=success nyni kontroluje zda se predava oauthToken, ktery odpovida drive inicializovane masterpass transakci, nasazeno na ibranu bude dnes, na produkci az v lednu 2018

**Comment by dmarek** [comment]
nasazeno na produkci, pokud souhlasite, muzeme zavrit...
