### ISSUE TITLE
Alternativní implementace, nevyžadující POST ze serveru

### ISSUE THREAD

**Issue by smarek** [csob/paymentgateway#348]
Dobrý den,

je možná alternativní implementace platební brány, která by nevyžadovala POST z našeho aplikačního serveru na iAPI/API endpoint ?

Máme problém se starou verzí PHP, cURL, OpenSSL, a než se začne produkce stavět znovu, chtěl bych si být jist, že to je jediná možnost.

Konkrétní problém je v tom, že OpenSSL 0.9.8 nepodporuje ECDHE šifry, takže přestože podporuje TLSv1.0, není možné požadavek z našeho serveru provést pomocí cURL/get_file_contents nebo jiného (integrace PHP)

iapi.iplatebnibrana.csob.cz
![iapi.iplatebnibrana.csob.cz](https://user-images.githubusercontent.com/384824/33430600-5fe07122-d5d1-11e7-8c1e-1fd7b9b89766.png)

Děkuji a jsem s pozdravem

**Comment by jzahradnik** [comment]
Dobrý den, 

V nastavení API jsou defaultně povoleny šifry TLS_ECDHE i TLS_RSA. Na nastavení iAPI máte pravdu byli nastaveny šifry jenom TLS_ECDHE toto bylo z důvodu zvyšující se bezpečnosti trochu přísněji. Nyní jsou šifry povoleny i s TLS_RSA konkrétně aes.

Zvyšující bezpečnost, ale vyžaduje podporu minimálně TLS v1.2. Pokud tedy implementujete něco nového je potřeba již počítat s touto podporou, protože již od června 2017 nejsou doporučovány starší TLS k použití u aplikací a je otázka času, kdy toto bude aplikováno plošně.

**Comment by smarek** [comment]
Děkuji, vyřešeno :)
