### ISSUE TITLE
PHP Example - špatné zacházení s parametrem closePayment

### ISSUE THREAD

**Issue by smarek** [csob/paymentgateway#349]
Dobrý den,

parametr closePayment je handlován jako string, ale v example (index-json.php) je uveden jako boolean.

Díky tomu sign místo textové hodnoty true/false použije při sestavování podpisu hodnotu 0/1 (json_decode a adresace $data["closePayment"])

Místo toho by v metodě signPaymentInitData v crypto.php mělo být následovně

Místo
```php
$data2Sign = $data["merchantId"] . "|" .  $data["orderNo"] . "|" . $data["dttm"] . "|" . $data["payOperation"] . "|" . $data["payMethod"] . "|" . $data["totalAmount"]
		."|". $data["currency"] ."|". $data["closePayment"]  . "|". $data["returnUrl"] ."|". $data["returnMethod"] . "|" . $cart2Sign . "|" . $data["description"]
```
Toto
```php
$data2Sign = $data["merchantId"] . "|" .  $data["orderNo"] . "|" . $data["dttm"] . "|" . $data["payOperation"] . "|" . $data["payMethod"] . "|" . $data["totalAmount"]
		."|". $data["currency"] ."|". ($data["closePayment"] ? 'true' : 'false')  . "|". $data["returnUrl"] ."|". $data["returnMethod"] . "|" . $cart2Sign . "|" . $data["description"]
```

**Comment by ratajskym** [comment]
Předtím, než se zavolá příslušná funkce, tak je tento parametr přetypován
$data["closePayment"] = ($data["closePayment"] == '1') ? "true" : "false";

Takže dále se posílá jako string. Mělo by ty tedy být v pořádku
$data["signature"] = signPaymentInitData($data, $privateKey, $privateKeyPassword);

**Comment by smarek** [comment]
Chápu a vidím, že funkce `createPaymentInitData` přetypování provádí. Problém je v kontrole v metodě `signPaymentInitData`, která předpokládá, že k přetypování došlo v předchozím flow. Z mého pohledu, jelikož jsem upravoval implementaci `index-json.php` nedošlo k volání `createPaymentInitData`, ale tento objekt jsem dle dokumentace složil manuálně.

V podstatě jde především o problém dokumentace, kdy pokud funkce `signPaymentInitData` musí být volána s výsledkem metody `createInitPaymentData` jako prvním argumentem, tak to není zmíněno, a při vytvoření `paymentInitData` manuálně, potom neprobíhá žádná typová kontrola, před podepsáním vytvořeného datového objektu.

Můj názor je, že by example metoda měla provést typovou kontrolu atributů datového objektu a indikovat nesrovnalosti, pokud toto není přístup, který chcete aplikovat, klidně ticket uzavřete.

Děkuji

**Comment by dmarek** [comment]
upraveno pro php example eAPI 1.8, vytvoření řetězce pro podpis prováděno pro `closePayment` v rámci metody `signPaymentInitData`
