### ISSUE TITLE
Chybný datový typ parametru v dokumentaci

### ISSUE THREAD

**Issue by blackfox00** [csob/paymentgateway#35]
U pole "closePayment" máte uvedený datový typ Boolean, ve skutečnosti ale váš server přijímá pouze String nabývající hodnoty "true" nebo "false". To je ovšem velký rozdíl! Pokud se tam pošle skutečně Boolean (tedy true nebo false bez uvozovek, což JSON rozlišuje), vrací server 400 Bad Request. Pokud se člověk řidí dokumentací, tak se taková chyba velmi špatně hledá!

**Comment by dmarek** [comment]
Můžete uvést, kdy a na jakém prostředí jste výše uvedené zkoušel?

parametr `closePayment` ve skutečnosti *je* Boolean a pokud zkouším zadat ve vstupním JSON požadavku pro `payment/init` hodnoty

```
"closePayment": true,
```

případně

```
"closePayment": "true",
```

požadavek je akceptován (odmítnut jako nevalidní je cokoli mimo true, false, "true", "false")

**Comment by blackfox00** [comment]
Testovací prostředí, teď opět odzkoušeno a chyba replikována, v případě 
```php
"closePayment": true
```
mi server vrátí 400 Bad Request a v případě 
```php
"closePayment": "true"
```
je vše v pořádku (měněn pouze tento parametr). 
Nechce se mi sem uvádět merchant ID, proto v logu můžete zkusit dohledat podle OrderNo: 1684868.

**Comment by dmarek** [comment]
Díky za info, porovnali jsme poslední dva pokusy, problém je v chybném podpisu. Můžete prosím zkontrolovat a porovnat řetězec který podepisujete? V obou dvou případech by tam měl být stejný řetězec `...CZK|true|http://...`
