### ISSUE TITLE
Payment/init: sslv3 alert handshake failure

### ISSUE THREAD

**Issue by petrkadlec** [csob/paymentgateway#350]
Na testovací platební bráně začala najednou vyskakovat tato chyba při pokus o přesměrování na platební bránu. Chyba začala zdánlivě "zničehonic" při intenzivním vývoji, ale do volání API nikdo nesahal ani nenastaly zrovna žádné změny v serverovém prostředí. Na produkční bráně je vše v pořádku.

Celá chyba:
`payment/init failed, reason: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

Předem díky za pomoc

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
M. Janek

**Comment by mjanek** [comment]
Tak mám informaci, že na integračním prostředí byla v souladu s bezpečnostními předpisy ukončena podpora protokolů nižších než TLS 1.2. Pro komunikaci s platební bránou je tedy třeba používat protokol TLS 1.2 a vyšší. Stejná změna se plánuje i na produkčním prostředí. Notifikace o této změně Vám bude s dostatečným předstihem oznámena.
