### ISSUE TITLE
404 payment/process eAPI v1.7

### ISSUE THREAD

**Issue by stovmascript** [csob/paymentgateway#351]
Zdravím, snažím se udělat `payment/process` v testovacím prostředí iBrána.

Merchant ID: A2992k0HYe

Echo mi projde, takže podepisování by mělo být ok - projde mi i ověření podpisu odpovědi echa. Následně dělám `payment/init`. Dotaz proběhne, odpověď je `0|OK` - ověření podpisu odpovědi už ale selže. Následně narážím na 404 při pokusu o `payment/process`.

Pokud bude potřeba, dodám ukázky kódu.

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek jsme zaevidovali a předali k řešení. O dalším postupu budete kontaktován odpovědným kolegou.

s pozdravem

Spisar

**Comment by vzich** [comment]
Dobrý den,
request posíláte jako POST, nicméně payment/process musíte zasílat jako GET. 
Viz. [specifikace](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#get--httpsapiplatebnibranacsobczapiv17paymentprocess-)

**Comment by stovmascript** [comment]
@vzich Tak jsem to právě zkusil GETem a úplně stejný výsledek (404). Payload requestů jsem už několikrát kontroloval, ale asi mi stále něco schází.

**Comment by Mspisar** [comment]
Pošlete prosím kopii řetězce, který posíláte na bránu.

**Comment by vzich** [comment]
V aplikačním logu jsem našel u vašeho posledního GET requestu včera okolo 17:45 pouze 
`https://iapi.iplatebnibrana.csob.cz/api/v1.7/api/v1.7/payment/process`, další parametry tzn merchantID, payID, dttm a podpis vám chybí - proto ta 404. 

Váš payment/process request by měl vypadat zhruba takhle:
`https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/process/A2992k0HYe/4cf1da72cff27CL/20171213174501/base64-encoded-request-signature`

**Comment by stovmascript** [comment]
@Mspisar @vzich Díky za pomoc. Přehližel jsem ty chybějící GETové parametry.
