### ISSUE TITLE
Chyba na platební bráně po zadání špatného CVC ale správného 3D secure kódu - TSGSMIPS-5407

### ISSUE THREAD

**Issue by naex** [csob/paymentgateway#352]
Dobrý den,

zdá se, že máte chybu na produkční platební bráně, a to následující: Po zadání existujícího čísla karty a nesprávného data expirace a CVC kódu brána nabídne zadání 3D secure kódu (což je samo o sobě zajímavé). Po zadání správného 3D secure kódu brána správně napíše, že platba byla zamítnuta vydavatelem karty, ale v prostoru detailu košíku vypíše nesmyslné texty - viz příloha a sekce vyznačená šipkou (některé informace jsem zabělil).
![chyba_platebni_brany](https://user-images.githubusercontent.com/2276830/34712937-e031c2be-f524-11e7-885a-7182ebf6451b.jpg)

**Comment by ratajskym** [comment]
Dobrý den, 

prosím o detail transakce (stačí pay_id), abychom to mohli prověřit. 

Děkuji

**Comment by naex** [comment]
Dobrý den, bude to jedno z těchto: "2c78898fa59cbDA", "4e8ce166afc84DA".

**Comment by ratajskym** [comment]
Fyi, Vámi reportované issue nezapadlo. Bohužel se nám uvedené chování nedaří nasimulovat. Testujeme novou verzi šablonovacího systému.

**Comment by ratajskym** [comment]
Dobrý den,  

nedávno jsme nasadili novou verzi šablonovacího systému. Pokud byste na uvedeného chování narazil, dejte nám prosím vědět.
