### ISSUE TITLE
Změny chybových hlášek při nefunkční zapamatované kartě - TSGSMIPS-5422

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#353]
Dobrý den, vypadá to že dnes došlo k nějaké aktualizaci na pl. bráně a změnily se chybové hlášky které brána vrací při expirované nebo nepoužitelné identifikaci zapamatované karty.

Můžete prosím napsat jaké je aktuální znění nebo to vrátit do původní podoby? Z ničeho jiného totiž nefunkční recurring detekovat asi nelze.

```
ResultCode === 140 && ResultMessage === 'orig payment not found'
ResultCode === 150 && ResultMessage === 'orig payment not authorized'
ResultCode === 180 && ResultMessage === 'oneclick payment series expired'
ResultCode === 180 && ResultMessage === 'orig payment not oneclick payment template'
ResultCode === 900 && ResultMessage === 'Unable to load card for payment/oneclick'
```

**Comment by dmarek** [comment]
aktualne se vraci tyto kombinace

```
// v pripade ze se v ramci payment/oneclick/init nenajde sablona platby pro zadane origPayId, vraci se
ResultCode === 180 && ResultMessage === 'orig payment not found'

// v pripade ze v ramci payment/oneclick/init je nactena podle origPayId sablona, ktera neni validni (napr. expirovala karta)
ResultCode === 150 && ResultMessage === 'orig payment not authorized' 

// v pripade ze v ramci payment/oneclick/init je nactena podle origPayId sablona, ktera neni validni (karta nebyla pouzita vice jak rok pro oneclick platbu)
ResultCode === 180 && ResultMessage === 'oneclick payment series expired' 

// systemova chyba (nenalezena karta pro danou sablonu oneclick platby)
ResultCode === 900 && ResultMessage === 'Unable to load card for payment/oneclick'
```

**Comment by janlanger** [comment]
Ok, u "orig payment not found" se tedy změnil kod z 140 na 180.

Chybu "orig payment not authorized" pak dostáváme ve tvaru "orig payment not authorized, oneclick payment series expired" s kodem 150

**Comment by janbrasna** [comment]
@janlanger PS: Na podzim se zmenila pro [v1.8 struktura](https://github.com/csob/paymentgateway/blob/00bffc0f6a6b90cdf98d2056da2b6332908a9f90/CHANGELOG.md#v18-102019) tak, aby jednak slo provolat stav oneclick sablony separe funkci, a take jsou na to samostatne navratove kody aby to nebylo potreba "lovit" ze stringu generickeho kodu. Je to takto lepsi, dostacujici, nebo byste potrebovali jeste nejak chytreji nakladat s tim stavem? Diky!

**Comment by janlanger** [comment]
@janbrasna hledali jsme v tom informaci že onclick je neplatný. Jiná možnost tehdy nebyla, teď už používáme echo, které nám stačí.

**Comment by janbrasna** [comment]
@janlanger 👍 Super, diky za info. Na zaklade tohoto ticketu totiz vznikla puvodni idea na `echo`, s konkretnim ucelem a mensim overheadem, takze jsem rad ze se to potkalo. Kazdy podobny report chovani nebo stavu nam pomaha udelat si lepsi obrazek o usecasech co resite, a dat nam vstupy na pripadne zlepseni tech procesu — diky za ne!
