### ISSUE TITLE
Testovací projekt - Bad request

### ISSUE THREAD

**Issue by jechtom** [csob/paymentgateway#355]
Pokud si stáhnu poslední verzi testovacího projektu a spustím knihovnu pro verzi 1.6 API v .NET, končí requesty chybou `Bad request`.

Přikládám ukázkové požadavky pro echo a init payment ve formátu HTTP archive (Fiddler apod.): [csob-test-bad-request.zip](https://github.com/csob/paymentgateway/files/1625879/csob-test-bad-request.zip)

Ještě doplním, že jsem neměnil přihlašovací údaje (klíče, merchantId apod.) - vše jsem nechal na výchozích hodnotách.

**Comment by jechtom** [comment]
Vyzkoušel jsem použít i testovací credentials vytvořené na https://iplatebnibrana.csob.cz/keygen/ a výsledek je stejný.

**Comment by Mspisar** [comment]
Dobrý den,

požadavek jsme zaevidovali a předali k řešení. O dalším postupu budete kontaktován.

s pozdravem

Spisar

**Comment by Mspisar** [comment]
můžete prosím zaslat nové merchant ID?

děkuji

**Comment by jechtom** [comment]
@Mspisar 
MerchantId: `A3059GdvWm` 
Certificates: [test.zip](https://github.com/csob/paymentgateway/files/1635222/test.zip)
Test echo request with response from your server: [test-request.zip](https://github.com/csob/paymentgateway/files/1635225/test-request.zip)

**Comment by ratajskym** [comment]
Tohle nevypadá na validní request
https://iapi.iplatebnibrana.csob.cz/api/v1.6/echo/A3059GdvWm/**YYYY**0116141840/

**Comment by jechtom** [comment]
Pravda. Při sestavování requestu jsem použil formát, který je zapsaný na `ApiBase` a je špatně. [Oprava](https://github.com/csob/paymentgateway/pull/354/commits/1a350f8173d9a5b56e2b3c44cec85e785fa273a4) je součástí mého [pull requestu](https://github.com/csob/paymentgateway/pull/354/commits/1a350f8173d9a5b56e2b3c44cec85e785fa273a4).

Nicméně i po opravě vidím problém stejný: [csob-test2.zip](https://github.com/csob/paymentgateway/files/1642538/csob-test2.zip)

**Comment by Mspisar** [comment]
Dobrý den,

při generování merchant ID odeslal jste veřejný klíč do banky?
![image](https://user-images.githubusercontent.com/14308940/35096989-7ed1f490-fc4e-11e7-966d-70a071672b36.png)
systém hlásí: Invalid echo request: **merchant key not found for**

s pozdravem

Spisar

**Comment by jechtom** [comment]
@ratajskym Díky za pomoc, to bylo ono, zavírám!
