### ISSUE TITLE
Warning: require_once(/data/web/virtuals/102216/virtual/www/domains/shop.omnifera.eu/wp-settings.php) - TSGSMIPS-5433

### ISSUE THREAD

**Issue by Borek1** [csob/paymentgateway#356]
Dobrý den, eshop mě přesměruje na platební bránu, nicméně pokud kliknu na " Zrušit platbu a vrátit se do obchodu". Brána mě nepřesměruje zpět a objeví se následující hláška:

Warning: require_once(/data/web/virtuals/102216/virtual/www/domains/shop.omnifera.eu/wp-settings.php): failed to open stream: No such file or directory in /data/web/virtuals/102216/virtual/www/domains/shop.omnifera.eu/wp-config.php on line 122

Fatal error: require_once(): Failed opening required '/data/web/virtuals/102216/virtual/www/domains/shop.omnifera.eu/wp-settings.php' (include_path='.:/data/web/virtuals/102216/virtual') in /data/web/virtuals/102216/virtual/www/domains/shop.omnifera.eu/wp-config.php on line 122

Napadá Vás kde je problém? 

Děkuji, Kráčmar

**Comment by mjanek** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

Miroslav Janek

**Comment by ratajskym** [comment]
Dobrý den, 

tohle je ale chybová hláška z Vašeho eshopu / hostingu. Tohle nemá s platební branou nic společného. Nicméně chybová hláška je poměrně jasná. Nedaří se nalézt soubor .. shop.omnifera.eu/wp-settings.php

**Comment by Borek1** [comment]
Dobrý den, ano, tomu rozumím. Mám nestandardní rozložení instalace wordpress a wp-settings je v jiném adresáři. Je možné změnit cestu k němu? Děkuji

**Comment by ratajskym** [comment]
Dobrý den, pravděpodobně to možné je, netuším. 

Máte nějaký konkrétní problém s platební bránou?

**Comment by Borek1** [comment]
Dobrý den,

ještě drobnost. Na platební bráně mi to píše poštovné zdarma. Ikdyž je poštovné před přesměrovaním na platební bránu vyčísleno v souhrnu.

Borek Kráčmar

+  +  +  +  +  +  +  +  +  +  +
 
Ing. Borek Kráčmar

OMNIFERA s.r.o.
Na Lužci 734, Lázně Bohdaneč, 
53341, Czech Republic 
www.omnifera.eu | FACEBOOK | borek@omnifera.eu
tel: +420 725 918 895 | ID/IČ: 03215156
VAT ID /DIČ: CZ03215156 | EORI: CZ03215156

15. 1. 2018 v 8:50, Martin Ratajský <notifications@github.com>:

**Comment by ratajskym** [comment]
Jakou máte nastavenou částku u druhé položky v košíku ? viz [dokumentace](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#item---polo%C5%BEka-ko%C5%A1%C3%ADku-objekt-cart-)

**Comment by Borek1** [comment]
Dobrý den,

omlouvám se, nevím co tím myslíte. Přikládám printscreen souhrnu pokladny
ve woocommerce.

Kráčmar


+  +  +  +  +  +  +  +  +  +  +

Ing. Borek Kráčmar

OMNIFERA s.r.o. | *Na Lužci 734, Lázně Bohdaneč, 53341, Czech Republic *
www.omnifera.eu | FACEBOOK <http://www.facebook.com/omniferaslings> |
borek@omnifera.eu | tel: +420 725 918 895
ID/IČ: 03215156 | VAT ID /DIČ: CZ03215156 | EORI: CZ03215156


2018-01-15 12:19 GMT+01:00 Martin Ratajský <notifications@github.com>:
