### ISSUE TITLE
http response 400

### ISSUE THREAD

**Issue by vosly1** [csob/paymentgateway#358]
Hi there,
 would it be possible to find out where exactly is the problem with the following request? The respose is 400. Merchant Id is M1E3CB3332.
----- Sun, 07 Jan 2018 20:35:05 +0000 ----- payment/init data to sign:: 'M1E3CB3332|21952|20180107203505|payment|card|118000|CZK|true|http://elega.cz/shop/wp-content/plugins/WooCommerceAdapter/Reply.php?unimodul=Csob|POST|Pánská peněženka Ele|1|110011.48|Pánská peněženka Elega Brend modrá Č...|Doprava|1|7988.52|Doprava|1x Panska penezenka Elega Brend modra|CZ'
*** Sun, 07 Jan 2018 20:35:06 +0000 payment/init failed, http response: 400

Thank you

**Comment by mrazekl** [comment]
Hello,

i checked your request. 
Can you please complete your request without "dot" in parametr Value in cart item? Use price in hundredths of the currency. Like 11001148 instead of 110011.48

**Comment by radovanx** [comment]
Hello,
In the doc we can see -

totalAmount - Total amount in hundredths of the basic currency.  
and
cart - amount -  Total price for the quantity of the items in hundredths of the currency.
the value 11001148 its not correct when total price is 118000

**Comment by ratajskym** [comment]
In hundreds of currency, it means there is definetly no dot. 
If something cost 10,- you must send 1000 (10 * 100)
If something cost 1,48 you must send 148 (1,48 * 100)

**Comment by vosly1** [comment]
Hi there, 
thank you for your help. I corrected the amounts and unfortunately the request still comes back with the http code 400
the request looks like this
 ----- Wed, 24 Jan 2018 22:34:26 +0000 ----- payment/init data to sign:: 'M1E3CB3332 ELEGA.CZ|22232|20180124223426|payment|card|58000|CZK|true|http://elega.cz/shop/wp-content/plugins/WooCommerceAdapter/Reply.php?unimodul=Csob|POST|Kožená kabelka Elega|1|50000|Kožená kabelka Elega Cora béžová Čes...|Doprava|1|8000|Doprava|1x Kozena kabelka Elega Cora bezova|CZ'
*** Wed, 24 Jan 2018 22:34:26 +0000 payment/init failed, http response: 400

Could it be the czech language or certificates? Is there a way to find out?

Thank you
