### ISSUE TITLE
Have you an example of integration for ver. 1.7 ?

### ISSUE THREAD

**Issue by serkat** [csob/paymentgateway#359]
Or tutorial how to integrate it ? Thanks

**Comment by mjanek** [comment]
Dear sir,
here you have documentation of the payment gateway according to which you can implement. 

https://github.com/csob/paymentgateway/wiki/eAPI-v1.7-EN

**Comment by serkat** [comment]
Thanks. I use example 1.5. Another question - can i send email of success
payment or not success payment. In your example after success payment
immediately redirect to url?


23 янв. 2018 г. 1:55 AM пользователь "Miroslav Janek" <
notifications@github.com> написал:

Dear sir,
here you have documentation of the payment gateway according to which you
can implement.

https://github.com/csob/paymentgateway/wiki/eAPI-v1.7-EN

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/csob/paymentgateway/issues/359#issuecomment-359615232>,
or mute the thread

**Comment by mjanek** [comment]
I think it is job of shop. You can find out a transaction status when you call "payment/status" and in next step shop may be send information about successful or not successful transaction.

**Comment by serkat** [comment]
Ok. will look at payment/status/ Thanks


2018-01-23 3:21 GMT+02:00 Miroslav Janek <notifications@github.com>:

**Comment by serkat** [comment]
Could you tell me - can i get all lifecycle's status via your example for ver.1.5 ?

Or i need to use my cert and key - to make live payment to see all status ?
Thanks.

**Comment by mrazekl** [comment]
Hello,

you have to do real transactions, for seeing their status. With your own MerchantID and generated keys, as described in the documentation.

**Comment by serkat** [comment]
Ok. Thanks
