### ISSUE TITLE
textová avíza GPE vs CSOB

### ISSUE THREAD

**Issue by senik** [csob/paymentgateway#36]
Dobrý den,

používáme platební bránu GPE a nyní připravujeme napojení na bránu ČSOB, předpokládáme souběžný provoz. Textová avíza zpracováváme strojově, jak od sebe rozeznám platby, které byly provedeny na bráně GPE od těch, které byly provedeny na bráně ČSOB?

V současné chvíli rozeznáváme terminály od online plateb pomocí regulárního výrazu `^CSOB[0-9]{4}$` a `^E3CB[0-9]{4}$`, budu se moci na něco podobného spolehnout i v případě avíz z brány ČSOB? Tedy že např. první 4 znaky v čísle POS budou fixní a měnit se budou až poslední 4 znaky?

Děkuji za informaci.

**Comment by radehorak** [comment]
Dobrý den,
textová avíza Vám budou chodit úplně stejně jako v případě brány od GPE. Identifikace bude stejná jako u GPE.
Radek Horák
