### ISSUE TITLE
Example for php - TSGSMIPS-5526

### ISSUE THREAD

**Issue by serkat** [csob/paymentgateway#361]
Hi. i'm using your example for php on test page with your key and merchantid
http://skatline.com/oktravel/
after clicking "test" btn i see data and result 
payment/init failed, http response: 400

Could you help me - what am i doing wrong in your example?

**Comment by serkat** [comment]
Also if i want to check echo

https://api.platebnibrana.csob.cz/api/v1.7/echo/A1029DTmM7/20180129214856/VWfAB4FH97iX75viSZbGPuLrh2PMpixSmKxlorR/XhmyRAnlwq2CcZCbhYttjVMq/nvBnY0PeEhufHWEO/dtum3GI8dSlS4iJBTi0Z0YbDp15u0y5LmM8FDkV/ib+rWTCcbL1LcLjxAP8HGOB+SivRcC6CI4/Ny0aGIrPyMR5HO6HYk7HVJFaEpuMu1J7fwSPXQH/WsHHUiNWnojKZCCdMzPC7muXlKnLlhzpNXLOIa6wMIMzy4u3Dj879M8bHe8lhdfX5HDCptmlkbePO5HtoKnj30RB/peuod7SPwIfl9+TGKri/yT6qOZGYfpyyq6juETWTIZQ9GFsdeMYVADSQ==

i see that page can't be found

**Comment by mjanek** [comment]
Dear Sir,
your request is registered and forwarded to responsible service technician. 
Best regards

**Comment by serkat** [comment]
Thanks. Waiting for your response

**Comment by ratajskym** [comment]
You are sending your request to production environment. But using anonymous merchant. 
You must use production merchant id and send it to production or you must you your anonymous merchant id and send it to sandbox. It depends what you want to do

**Comment by serkat** [comment]
Could you send production credentials and sendbox, please?

**Comment by ratajskym** [comment]
You must sign contract with CSOB to get production credentials

**Comment by serkat** [comment]
is there a sendbox url to test the payment?

**Comment by serkat** [comment]
i generate a sandbox public key and private key. Also when i start sign-verify-test.php with sandbox public and private keys - i get

sign & verify test ...
signing text 'some text to sign' using private key rsa_A309616bIT.key
signature is 'U3feXX2Pm0l73InoMZ5Pgz3Zi8ybTfFDt7gP2uTRIBVCnXbI195bEBBWcL0wcHWa0BS6g6kPMHwlEFhJhmpDViB8Jfgq3+E4IGuKyzBogl7OkID7LE20no7CMXv6opxGVb7TfGKmirkBUzRfe7gAZKHiobZgL/kb+kmyyBBJaQ1PxGlODDXSliQEX73AEocbbQXUR6M5yjKFQDVSS5qkTL+bEzO+DJk1wwQXlNX3uGX1xtG9+0y20Glp7LNR7SU9nuH8bClBs3n/zOLKlT2A0mil+jjhj9vwI3GkNi7WCJiP+WXqBoYByXKcIUV1fWoffx5MpY9VTd6zoyBgCqmkEg=='
verifying signature using public key rsa_A309616bIT.pub
verify result: ok

but then http://skatline.com/payment/ - will say to me that 


processing payment/init request ...

payment/init failed, http response: 404

**Comment by serkat** [comment]
is there workable php example with sandbox url where i will change merchantId, add public and private keys - and it will work ?

**Comment by ratajskym** [comment]
As you can see, your request was succesfull payId":"f453cd983716eDA","resultCode":0,"resultMessage":"OK","paymentStatus":1

BUT, verification of response failed. That means that you have wrong public key (check that you have the right one https://github.com/csob/paymentgateway/tree/master/keys )
