### ISSUE TITLE
Pískoviště

### ISSUE THREAD

**Issue by jahr** [csob/paymentgateway#362]
Dobrý den, chtěl bych se zeptat, jestli volání payment/status v testovacím prostředí vrací rozšíření maskClnRP při inicializaci oneclick platby. Děkuji

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by mjanek** [comment]
Pokud využíváte anonymní merchantID, tak můžete využít jen základní funkcionality brány. Tyto rozšíření můžete používat až po podpisu smlouvy s bankou.
