### ISSUE TITLE
Zmena udaju v detailu obchodnika

### ISSUE THREAD

**Issue by mfeuermann** [csob/paymentgateway#364]
Dobry den,

potrebovali bychom zmenit udaje u obchodnika (MerchantId 04591399)
Zmena bude u parametru Nazev, Domena, Kontaktní e-mail,
Bohuzel jsme zjistili, ze jsou tyto udaje v rozhranni POSMAN read-only.

Muzete nam prosim pomoci se zmenou ?

Dekuji 
Marek Feuermann
Trip.Market

**Comment by jzahradnik** [comment]
Dobrý den, 
Pro editaci těchto údajů, se prosím obraťte přímo na akceptaci karet na adrese akceptacekaret@csob.cz.

S pozdravem
