### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by serkat** [csob/paymentgateway#365]
Hello.
Could you help me with this error
data to sign: "A3129jqbil|165289720610|20180212203915|payment|card|1378000|CZK|false|http://test.ok-travel-praga.com/?view=results|POST|Shopping at ...|1|1378000|Ð”ÐµÑ‚ÐµÐ½Ð¸Ñ†Ðµ...|Shipping|1|0|PPL|sergiosgresr.test@gmail.com 89114954046|NULL||CZ" payment/init failed, reason: SSL certificate problem: self signed certificate in certificate chain

**Comment by mrazekl** [comment]
Hello, 
which version of SSL/TLS protocol are you using? Only versions 1.2 and higer are supported in integration environment. It last from december 2017.

**Comment by serkat** [comment]
TLS 1.2
but there is no ssl certificate
http://test.ok-travel-praga.com/

**Comment by serkat** [comment]
two weeks ago test payment was succesfull - but now there is ssl certificate poblem

**Comment by serkat** [comment]
https://www.htbridge.com/ssl/?id=ZRWuXd5C - here is result of testing tls

**Comment by serkat** [comment]
Need i use SSL certificate with TLS - or using only TLS is a minimal requirement?

**Comment by serkat** [comment]
Is anybody there?

**Comment by mrazekl** [comment]
Yes, sure. We had to forward your request to our network specialists. 
When they know the solutions, you will be informed immediately.
I would like to ask you for more patience. 
Thank you

**Comment by serkat** [comment]
Thank you, Mrazekl.
Sorry about my impatience, cause of calling from bank and telling me that old system will be closed soon/ So i need to change payment system. Will wait for an answer from network specialists.

**Comment by ratajskym** [comment]
From my point of view, transaction from last night was sucessfull. We received your transaction init and send response to your host

```
2018-02-13 22:00:24
Payload: {
	"dttm": "20180213220024",
	"signature": "yourSignature",
	"payId": "0f64e4c26622eDB",
	"resultCode": 0,
	"resultMessage": "OK",
	"paymentStatus": 1
}
```

**Comment by serkat** [comment]
Hello. I made another try to pay now
data to sign: "A3129jqbil|189243675785|20180214093005|payment|card|1378000|CZK|false|http://test.ok-travel-praga.com|POST|Shopping at ...|1|1378000|Личный гид по Праге только для Вас...|Shipping|1|0|PPL|Сергей Рябининsgresr@gmail.com 89114954046|NULL||CZ" payment/init failed, reason: SSL certificate problem: self signed certificate in certificate chain

**Comment by serkat** [comment]
and as you can see
payment/init failed
and i didn't go to payment page of bank to make payment because of this error.
Could you tell me how can i fix this problem: SSL certificate problem: self signed certificate in certificate chain

**Comment by ratajskym** [comment]
This is wierd .. i can see transaction from last night but i cannot see transaction from today
I am looking for merchant id A3129jqbil

**Comment by serkat** [comment]
smth weird. as you can see - payment init failed - so i cannot reach bank payment page to pay. That is the problem.

**Comment by ratajskym** [comment]
Yes, it is part of the problem. How can i analyze it, if i can see your request from yesterday and not from today. Something changed

**Comment by serkat** [comment]
maybe you see succesfull transaction from another server where i use same key.
the last try which i send you earlier - the last one is from the site - where i need to change payment system. And there is a SSL problem. So, is there any solution to fix this SSL certificate problem?
Are there requirements to use your payment system? for example TLS 1.2 (which is already installed) or i need to add SSL certificate - (for example let'sencrypt)

I cannot understand why some days ago - everything was worked but know - there is an error with SSL certificate

**Comment by ratajskym** [comment]
You dont need SSL certificate. You only need TLS 1.2 

I am really sure, that this is problem on your side, not CSOB payment gateway. As you wrote, it is working from one of your system but doesn`t work from another one

**Comment by serkat** [comment]
part of php.file
Could you check - that all parameters are right?    $publicKey, $url ... 

$publicKey = "mips_iplatebnibrana.csob.cz";
$privateKey = "rsa_A3129jqbil.key";
$privateKeyPassword = null;
$merchantId = "A3129jqbil";

$url = "https://iapi.iplatebnibrana.csob.cz/api/v1.7";
$merchantNumber = 'A3129jqbil';

$totalAmount = 0; 
$description = ''; 
$goods_desc = 'some description about tour'; 
$shippingAmount = 0;


$customerId = '';
$returnMethodPOST = "yes";
$closePayment = "false";
$merchantData = "NULL";
$ItemTotalPrice = 0;
$productName = '';

$dttm = (new DateTime ())->format ( "YmdHis" );

**Comment by serkat** [comment]
week ago i can get payment page of bank.
but of this error - now i cannot get it
maybe - initial parameters are wrong, perhaps

**Comment by ratajskym** [comment]
There was no change, on our side. If your script works on one environment but wont work on other one, it is not problem of CSOB payment gateway

**Comment by serkat** [comment]
i understand that, thanks.
What about fields? $url and $oublicKey - are correct for sendbox?

$publicKey = "mips_iplatebnibrana.csob.cz";
$privateKey = "rsa_A3129jqbil.key";
$privateKeyPassword = null;
$merchantId = "A3129jqbil";

$url = "https://iapi.iplatebnibrana.csob.cz/api/v1.7";
$merchantNumber = 'A3129jqbil';

$totalAmount = 0;
$description = '';
$goods_desc = 'some description about tour';
$shippingAmount = 0;

$customerId = '';
$returnMethodPOST = "yes";
$closePayment = "false";
$merchantData = "NULL";
$ItemTotalPrice = 0;
$productName = '';

$dttm = (new DateTime ())->format ( "YmdHis" );

**Comment by ratajskym** [comment]
Is this issue solved on your side ? I would like to close this issue
