### ISSUE TITLE
Is it OK ? i pay 1Euro

### ISSUE THREAD

**Issue by serkat** [csob/paymentgateway#366]
For example, exchange course CZK and EUR is 1= 27.56
I pay 1 euro via test payment and see that in CZK it equals to 2756,00 
http://nimb.ws/IZnlYg
Is it normal?

**Comment by serkat** [comment]
A3129jqbil

**Comment by Mspisar** [comment]
Test payment gateway with anonymity merchant ID hasn´t got all functionality. I´ll redirect your request to my colegue.

best regards

Milan Spisar

**Comment by ratajskym** [comment]
In your init request, you are sending amount in CZK - 275600|CZK. Behaviour of payment gateway is right

**Comment by serkat** [comment]
this amount 275600 not equals to 1 EUR, am i right? i suppose that 2756 equals to 1 Euro

**Comment by ratajskym** [comment]
If you want to pay one euro, just send one eur in request. Amount and currency in your request is what you will see on payment gateway

**Comment by ratajskym** [comment]
Do you have another question ? If not, i will close this issue
