### ISSUE TITLE
stejný variabilní simbol pro více transakcí TSGSMIPS-5716

### ISSUE THREAD

**Issue by pringel01** [csob/paymentgateway#367]
Dobrý den, Klient vystavuje objednávku pud určitým číslem, které je následně použito jako vs. Objednávku umožňuje platit na splátky/měs ale požaduje pro jednotlivé splátky stejný vs. Jedná se o platbu na klik. pokud posílám při inicializaci stejné OrderNo, které jsem již jednou použil, brána požadavek zamítne viz:
{"dttm":"20180301063355","signature":"dq2ZKA9f34O/0833gOgirJGGor8Qu0IHIDhfFaP9/y6MOZ80Nvpbr9bu2Ki1y3eHI7YeXTSkbC1dnIZjebyQwgSqd/zOFEQIU7tCGhGA/EvdPxq6Gsp7yxhrQc3gBi8xWL3N+REBYrt3ZbkXWRT1fz4j8QmGrj+YkBVwbEOgC00srJuhhCjrb1TAwCGnOPXWlTWMQ+ar8smPfGp8dE8PXu+mf21x7PORR4Ytj1Vdr1i5hb0Hbild9SRQEHoCASqoPukvmhYjJesraMQy8hrBICXQOHaLbEtUZAUnxcom4lahHJXqw6UpQr2F7shvprlHzz9knGTdUOST9quak1HffA==","payId":"97be197a10d5bDC","resultCode":0,"resultMessage":"authorized trx for orderNo 1388 already exists","paymentStatus":6}
Jak docílit několika plateb pod stejným vs ?

**Comment by vzich** [comment]
Dobrý den,
pro zrušení kontroly VS pro vaše merchantID kontaktujte akceptacekaret@csob.cz.
