### ISSUE TITLE
legacy api

### ISSUE THREAD

**Issue by radovanx** [csob/paymentgateway#368]
Dobry den,

Obchodnik vola legacy api 

takto
*** Thu, 01 Mar 2018 22:16:22 +0100 MAKING_ORDER_URL https://iplatebnibrana.csob.cz/pay/entry/merchant?MERCHANTNUMBER=M1MIPS1126&OPERATION=CREATE_ORDER&ORDERNUMBER=20028&AMOUNT=15800&CURRENCY=203&DEPOSITFLAG=1&MERORDERNUM=20028&URL=https%3A%2F%2Fdev.kafone.cz%2Fmodules%2FPrestaAdapter%2Fvalidation.php%3FuniModul%3DGPWebPay&DESCRIPTION=%28Ord.No.%3AELTTLZPCQ%29+Kafone&MD=X&DIGEST=tHB3KLAKqgGYRQ0YMcKjexqqkr%2F5iy6Bjo5UGWdZUl%2BaOVLP8mdFE2a1jld89sEqYQqR2eDes6kfeHxXjv8pVs%2FzOe6QimaXujT5e5oFeH584AWuH5ykaa3Ei6PZCUsDlwKIdi4hguxhZqukdZ3D%2BMhOFP9NIEoNq5rkFFqG%2FLrUNDWdw1KNQv%2FCaro5VE9nJWm8LTe84vmb%2BDx7uFbzx%2FEkRrxflIJKdIDAA2Dwn9ayJCtvVsjKKdasnngOF%2FZIlXYoFlbaFwsSOGh8m99aiuxON%2B%2Bbg9yhy%2BLdhRBI4c6dziYhFW6pV7eNdTkdHAaYXaDTtSKaV3HAZ1zzYyZ1xw%3D%3D&LANG=cs&EMAIL=radovanmail%40gmail.com   127.0.0.1 /modules/PrestaAdapter/redirect.php?uniModul=GPWebPay&subMethod=

Prosim o informaci co je konkretne spatne certifikat by mel byt v poradku
Dekuji

**Comment by Mspisar** [comment]
Dobrý večer,

Váš požadavek byl zaevidován a předán k řešení. O dalším postupu budete kontaktován odpovědným kolegou.

s pozdravem

Spisar

**Comment by vzich** [comment]
Dobrý den, 
pokud máte správný privátní klíč (vidím že jste si včera přegeneroval klíče). Můžete zaslat řetězec, který podepisujete?

**Comment by radovanx** [comment]
string(175) "M1MIPS1126|CREATE_ORDER|20032|15800|203|1|20032|https://dev.kafone.cz/modules/PrestaAdapter/validation.php?uniModul=GPWebPay|(Ord.No.:BXBZRXCTC) Kafone|X|radovanmail@gmail.com"

**Comment by vzich** [comment]
Dobrý den, 
vyzkoušejte zaslat transakci bez nepodporovaného parametru EMAIL. Ostatní parametry jsou OK.

**Comment by vzich** [comment]
Vidím, že jste nakonec s uvedeným ID přešel na eapi. Můžeme uzavřít?
