### ISSUE TITLE
http response: 500

### ISSUE THREAD

**Issue by Madla** [csob/paymentgateway#37]
Dobrý den, 

chtěl bych Vás požádat o radu. Pří inicializaci platby z Vašeho příkladu z PHP se mi vrací návratový kód payment/init failed, http response: 500

V logu mám tento řetězec:
----- Fri, 21 Aug 2015 17:39:01 +0200 ----- payment/init data to sign:: 'M1MIPS0079|201505|2015-08-21 17:38:48|payment|card|100|CZK|false|http://www.vmest.cz/CSOB/return-gw.php|POST|Doc. Jana Nová|1|100|Registrace na IMPP 2015...|||||Registrace na IMPP 2015|CZ'

HTML:
preparing payment init data ...
preparing cart data:
[{"name":"Doc. Jana Nova","quantity":1,"amount":100,"description":"Registrace na IMPP 2015..."}]

data to sign:
"M1MIPS0079|201505|2015-08-21 17:53:39|payment|card|100|CZK|false|http://www.vmest.cz/CSOB/return-gw.php|POST|Doc. Jana Nova|1|100|Registrace na IMPP 2015...|||||Registrace na IMPP 2015|CZ"

prepared payment/init request:
{"merchantId":"M1MIPS0079","orderNo":"201505","dttm":"2015-08-21 17:53:39","payOperation":"payment","payMethod":"card","totalAmount":100,"currency":"CZK","closePayment":"false","returnUrl":"http:\/\/www.vmest.cz\/CSOB\/return-gw.php","returnMethod":"POST","cart":[{"name":"Doc. Jana Nova","quantity":1,"amount":100,"description":"Registrace na IMPP 2015..."}],"description":"Registrace na IMPP 2015","language":"CZ","signature":"........"}

processing payment/init request ...

payment/init failed, http response: 500

Mohli by jste mi prosím poradit co mám špatně? 

Děkuji

**Comment by ratajskym** [comment]
Dobrý den,

vygeneroval jste utilitu keygen klíče a odeslal je do banky?

**Comment by Madla** [comment]
Dobry den,

Vygenerovani klicu proběhlo a po přečtení dokumentace je tam doopravdy zmínka o tom,ze se musí odeslal klíč do banky. Omlouvám se,ale dokumentace se mi zda neprehledna a důležité informace jsou roztroušené. Mohl by jste mi poslat emailovou adresu, kam se ma klíč poslat?

**Comment by ratajskym** [comment]
Dobrý den,

utilita Vám klíč odešle sama, není potřeba nic posílat ručně na mailovou adresu.

![image](https://cloud.githubusercontent.com/assets/9882463/9460157/9f3ee61a-4b03-11e5-9721-c107fed249fc.png)

**Comment by Madla** [comment]
Dobrý den,

děkuji Vám za informaci. Pomohlo mi to. 

Ale chtěl bych se Vás zeptat, jak dlouho trvá zařazení veřejného klíče v bance? Protože mi to hlásí teď jinou chybu:

prepared payment/init request:
{"merchantId":"M1MIPS0079","orderNo":"201505","dttm":"20150825172452","payOperation":"payment","payMethod":"card","totalAmount":100,"currency":"CZK","closePayment":"false","returnUrl":"http:\/\/www.vmest.cz\/CSOB\/return-gw.php","returnMethod":"POST","cart":[{"name":"Doc. Jana Nova","quantity":1,"amount":100,"description":"Registrace na IMPP 2015..."},{"name":"Shipping","quantity":1,"amount":0,"description":"PPL"}],"description":"Registrace na IMPP 2015","language":"CZ","signature":"mlgP4innJ1UAD40sY8pKi\/nXksxND4PPZUi5Xfx1o8kxbXMOLMGrGn+8NF1oF71oNyc\/8CCfy81iqsn7OoAziFpafdJ0\/O+HBNUEX54jHx\/LRMhxdpXqLFOtOJf1dpr5WryTKhgcfTgjWpgYYiVs6RvyFnHrTBYdhPZ7sGcJthKFbx9OwqPxxnUQ8H7nzsTj5IId8eBOhAIbgSvseIYHgW0uQ9anqSfhwfrV1AtR4AM0vkjDEwRhiaaH8I4iwIeWutwWpNf8SF+gFIhslLLxuWhfBvbgKWi9+lDNLagThCeX39cJxmn47I6SWGLf3XbpOBqds2nAK2Xyg15dxC8TKA=="}

processing payment/init request ...

payment/init result:
{"dttm":"20150825172455","signature":"EA3CAeXu+hFIffP8M7xTiUqSuJ2kJECSMo5hjJkKDe6z1JFvrt/1alijU+walMg04GJQYFl9n0uPgQc/UN9woBtMjQj9jADkPenY9ON51lGzqI0T0vOqCn11Qh/P5/Qq8gPRpa4diJKRzeJsEt5iG6RMqQ4X5dDS03bPtzGW3Rrts7v/XOWecBP8pf0dPXLLMhqC8ashlDJI02sEbXVyTYcr5f5A2yycNfi15xkaXZdVQv+2oP7cSrHtAc7+sRViDcIHQjJ7PgP34nL0ugsAwbDieYmeJ5FKp5AV05Gd04hPOUOBTAJ0sn8dP9V2A3AqaWSqa3T/8Sv5KQi2dfXAiA==","payId":"97c6db15611d43b","resultCode":0,"resultMessage":"OK","paymentStatus":1}

payment/init failed, unable to verify signature


Děkuji

**Comment by ratajskym** [comment]
Dobrý den, 

po odeslání klíče přijde na email, který byl uveden do smlouvy s bankou, jednorázové heslo. Tímto heslem pak v aplikaci PosMerchant vygenerovaný klíč potvrdíte.

**Comment by ratajskym** [comment]
Dobrý den, tak znovu a lépe.

Vaše požadavky posíláte na testovací prostředí (automaticky jsem bral, že do produkce)
V testovacím prostředí je klíč schválen automaticky. Váš požadavek payment/init jsme přijali a odeslali Vám odpověď. Podle všeho nedokážete ověřit podpis této odpovědi. Jsou dvě možnosti
- používáte špatný veřejný klíč platební brány
- špatně skládáte podpis

Jaký tedy používáte klíč?

**Comment by Madla** [comment]
Dobrý den,

děkuji za vyjádření.

- používáte špatný veřejný klíč platební brány
  = tento klíč jsem stáhl společně se soukromým klíčem 
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoQ5vtkueoj8bL7RnmLdp
xsPCcwk8dEO7+eo0gL/JGz87p06lJFPEpUb9az4GJDjEr+PF6CvSgF6GCpZ+zX61
+3MjiSonFPkU+SfFLtGgiVwQIh9TQDEEES4xQR4Jbb4fRzkM0SARGnxiWfB4iZVc
/XQQtqufZPTErqEXjO128wa0re4CB8k9tvizc1kiTI3omlqA0xZ9//hEPUJGt+F/
f9Spqe0mms/VbuZ7tQjOFEgZD7z6M55w4f4h8CT/HSoSzOzjVFZyK698gKMMhwee
x19G5rmWYwl48pAXJoYtCx5l2Pz2RZzIdnFqV4I0N7AOwMY8ChSxlonq0IYccynT
nQIDAQAB
-----END PUBLIC KEY-----
- špatně skládáte podpis
  = podpis se skládá pomocí Vašeho PHP příkladu (http://www.vmest.cz/CSOB/example/) ... jediné co jsem v php upravoval bylo vytváření hodnoty $dttm = date("YmdHis");

Bohužel, nevidím důvod proč by to nemělo fungovat :(

**Comment by ratajskym** [comment]
Dobrý den, zkusím to podrobněji. Obávám se, že pro ověření podpisu brány používáte jiný klíč než je potřeba

*Request - Tohle Vám chodí, tohle je v pořádku.*
v aplikaci pro generování klíčů jste vygeneroval vygeneroval privátní a veřejnou část klíče.
- privátní částí částí vytváříte podpis zprávy
- veřejnou částí, kterou jste odeslal do systému banky, dokážeme ověřit správnost podpisu.


*Response*
Platební brána vygeneruje a odesílá Vám odpověď. Abyste mohl ověřit podpis, potřebujete veřejný klíč brány, který je ke stažení [zde](https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys) 

Pozor, jsou dva typy veřejných klíčů
- pro testovací prostředí - mips_iplatebnibrana.csob.cz.pub
- pro produkční prostředí - mips_platebnibrana.csob.cz.pub

**Comment by Madla** [comment]
Dobrý den, 

děkuji Vám za radu.

Ověření funguje.
