### ISSUE TITLE
Legacz API

### ISSUE THREAD

**Issue by Nowis75** [csob/paymentgateway#370]
Dobrý den, bohužel se nám nedaří rozchodit Legacy API na nové bráně. Postupuji podle návodu, jsou vygenerované certifikáty, klíče. Jsou potvrzený v Merchant POS. Neustále se zobrazuje hláška o chybě (Platba nemůže být provedena
Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.)

Náš řetězec je 
M1E3CB1120|CREATE_ORDER|15204507481148|74900|203|1|20181148|http://www.floresco.cz/index.php|1148

**Comment by Mspisar** [comment]
Dobrý večer,

Váš požadavek byl zaevidován. O dalším postupu Vás bude kontaktovat odpovědný kolega.

s pozdravem

Spisar

**Comment by Mspisar** [comment]
Dobrý večer,

požadavky posíláte střídavě do testovacího a produkčního prostředí. Ujistěte se prosím, že používáte správné klíče k danému prostředí.

s pozdravem

Spisar

**Comment by ratajskym** [comment]
Dobrý den @Nowis75 , v jakém stavu se právě nacházíte ? Můžeme issue uzavřít ?
