### ISSUE TITLE
Fatal error: Call to undefined function openssl_get_privatekey

### ISSUE THREAD

**Issue by KohoutJan** [csob/paymentgateway#371]
Dobry den,
mám problem s testovanim, nelze se spojit s branou, kde jsem si prosel vsechny moznosti co mne napadlo, ale stale bez vysledku.

hazi mi to hlasku:

Fatal error: Call to undefined function openssl_get_privatekey() in /www/doc/www.purecoco.cz/www/monetWebPay/crypto.php on line 188

![problem](https://user-images.githubusercontent.com/37406359/37465071-8044455c-285a-11e8-9609-4d2b4ca212e3.jpg)

Klice jsou uploudovany do banky. Pos merchant je aktivni. Tak uz nevim kde muze byt problem. Klic jsem zkontroloval, jelikoz se to tu uz nekolikrat resilo. 

dekuji za rady.

**Comment by mrazekl** [comment]
Dobrý den,

ověřte si na hostingu  v nastavení, že máte spuštěný modul openSSL. Podle popsaného erroru to vypadá, že není spuštěn.

**Comment by KohoutJan** [comment]
dekuji, byl problem ve verzi PHP. Po upgrade na php 5.6 to jede. A tim padem i openSSL.

**Comment by mrazekl** [comment]
Děkuji za zprávu, může posloužit dalším jako příklad. Zavírám.
