### ISSUE TITLE
Confirm the execution of all test cases and submit for review

### ISSUE THREAD

**Issue by serkat** [csob/paymentgateway#373]
Hello. I want to confirm all tests and after going to this link https://iposman.iplatebnibrana.csob.cz/posmerchant - i cannot log in. "Failed to log in to system"
But if i log in here - https://posman.csob.cz/posmerchant/ - i can log in

Need i confirm all test or i can just change bank public key and Api key for production ?
Thanks

**Comment by aKocian** [comment]
Hello, 
if you want to confirm integration tests and you can't log into https://iposman.iplatebnibrana.csob.cz/posmerchant you should write here for password change : akceptacekaret@csob.cz or you can change password by yourself with function password recovery.

**Comment by serkat** [comment]
Is it required condition to confirm all tests?

**Comment by aKocian** [comment]
Yes, you need to confirm all tests if you want switch to production enviroment.

**Comment by serkat** [comment]
Thank you

**Comment by serkat** [comment]
One more question - if i didn't confrim tests - i could not make a payment with real card ?

**Comment by mjanek** [comment]
Hello, if you are not confirm tests, you don't pay with real card.

**Comment by serkat** [comment]
Thanks again!

**Comment by serkat** [comment]
some problems with password recovery - i use real username and email - with which i can login here
https://posman.csob.cz/posmerchant/tNhWuSE4gao/tNhdd

But when i want to recover password here https://iposman.iplatebnibrana.csob.cz/posmerchant - it writes  
"The specified user or e-mail was not found on the system"

**Comment by mjanek** [comment]
Tell me your merchant id.

**Comment by serkat** [comment]
username:  27406865
merchantId:   M1E3CB3388

**Comment by mjanek** [comment]
You didn't fill contact email in your user acount at integration enviroment. Now you can't change password. The last password change  on this profile is in 2015. If you want change it, you need to write email at akceptacekaret@csob.cz with request about change password.

**Comment by serkat** [comment]
Ok i understand.

**Comment by serkat** [comment]
But in profile i have a contact Email
http://nimb.ws/V0ztd8

**Comment by mjanek** [comment]
You can change passwd at production environment?

**Comment by serkat** [comment]
Yes - i successfully change password

**Comment by Mspisar** [comment]
Hello,
best possible way to change or recover your account information is write an email on adress akceptacekaret@csob.cz like my colleague wrote.
best regards
Milan Spisar

**Comment by serkat** [comment]
Hello, Milan. Nobody answer on email

**Comment by serkat** [comment]
Today is the last day of working old payment gateway. We need to use eAPI today

**Comment by serkat** [comment]
How can we solve this problem?

**Comment by serkat** [comment]
@Mspisar , @mjanek

**Comment by ratajskym** [comment]
I have forwarded your problem to the bank. You MUST wait.

**Comment by serkat** [comment]
Ok it will be nice to solve this problem
Thanks, Martin Ratajský

**Comment by marekdub** [comment]
Hello, the new password was sent on this phone number +420774150329.

**Comment by serkat** [comment]
Thanks. With this password i can confrim all tests and use key on production, am i write?

**Comment by marekdub** [comment]
This password is for production enviroment https://posman.csob.cz/posmerchant where you have to activate your public key by verification code.

**Comment by serkat** [comment]
Request to introduce a key for payment gateway: M1E3CB3388 You have no new request for a key to be implemented.
From this link i need to confirm tests and make a request https://iposman.iplatebnibrana.csob.cz/posmerchant  ?

**Comment by serkat** [comment]
Because this link is written here https://github.com/csob/paymentgateway/wiki/How-to-Switch-to-the-Live-Environment#confirm-the-execution-of-all-test-cases-and-submit-for-review

**Comment by serkat** [comment]
i need to confirm from production site? or i can confirm from test site and after that testing with real card - make changes to production site?

**Comment by aKocian** [comment]
Hello,

If you want to use "reversal" function on payment gateway, you need to do at least one reversed transaction to confirm integration tests.
In the other case if you dont want to use this function, we can confirm tests by ourself.

**Comment by serkat** [comment]
if i want this "reversal" function  in the future - it will be possible to add it?

**Comment by marekdub** [comment]
The production interface was already activated, sou you do not have to confirm tests in test enviroment. So now you have to generate a production certificates and confirm public key by validation code that will be send on email oktravelpraga@gmail.com.

**Comment by serkat** [comment]
Thanks! You save us! Will wait for email

**Comment by marekdub** [comment]
One more thing, the validation code is generated after you generate the production certificates on this site: https://platebnibrana.csob.cz/keygen/ 
have a good day.

**Comment by serkat** [comment]
Thats great.

Another question from production - on test site if i cancel payment from bank's page - i see that POST returns from https://platebnibrana.csob.cz/ with status 200 - and everything is fine - i can catch errors.

But on production site - if i cancel payment from bank's page - i see that POST returns with status 301 - and $_POST is empty.

Why it could be? 
(screens from prod and test sites)

![prod](https://user-images.githubusercontent.com/9426503/38118212-96f46e66-33b9-11e8-8024-c5705564e150.png)
![test](https://user-images.githubusercontent.com/9426503/38118213-97231b9e-33b9-11e8-8db4-00f366cdfd49.png)

**Comment by Mspisar** [comment]
Hello,
your request has been redirected to a responsible colleague and will be answered as soon as possible.
best regards 
Milan Spisar

**Comment by serkat** [comment]
Ok

**Comment by serkat** [comment]
Thanks to all. I fix this problem by myself. The error was in return url - it was without "www"
