### ISSUE TITLE
Got 400 error code in eAPI v1.5

### ISSUE THREAD

**Issue by GekMDN** [csob/paymentgateway#374]
Hi,

I am using eApi 1.5 for payments and send all data as described in documentation and stated that

When a request is being processed, basic parameters are checked first and the request signature is verified. If an error is detected, the response contains only a general HTTP status code, in terms of security, such as 400 Bad Request

This is my input json :

preparing payment init data ...

preparing cart data:
[
    {
        "name": "Shopping at ...",
        "quantity": 1,
        "amount": 950000,
        "description": "Lenovo..."
    },
    {
        "name": "Shipping",
        "quantity": 1,
        "amount": 50000,
        "description": "PPL"
    }
]

data to sign:
"M1MIPS1813|2018/00001|20180328114752|payment|card|1000000|CZK|false|http://ariana-koberce.cz/csob/|POST|Shopping at ...|1|950000|Lenovo...|Shipping|1|50000|PPL|Nákup na ariana-koberce.cz (Lenovo)|1234|CZ"

prepared payment/init request:
{
    "merchantId": "M1MIPS1813",
    "orderNo": "2018/00001",
    "dttm": "20180328114752",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 1000000,
    "currency": "CZK",
    "closePayment": "false",
    "returnUrl": "http://ariana-koberce.cz/csob/",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 950000,
            "description": "Lenovo..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 50000,
            "description": "PPL"
        }
    ],
    "description": "Nákup na ariana-koberce.cz (Lenovo)",
    "merchantData": null,
    "customerId": "1234",
    "language": "CZ",
    "signature": "IX4hcsYBx92c9X9xq5YxOJxhOD8KXQ1fRlPJ83cyYOqB6NjDYN5uEvj1bjhR0EHXg4Pv144sSaSthgEQ+nmOI6NJda2o0cR0U6JFQIKmPnt1ySM2REPqTQbCDsDWHta6awuBO2vr1TF8ZnHLpQajkFyBShiYJLxyDki5RtDmFBtfpeOg7z9HlrVIggWlwwA7N0PMBgmTz38UlRa84xHdDmFtrlCc0t2vSn6p5A83h9YrSSP6rm4tziI6vl4o/HYABkLToz7VAD++DqanUgSCYqvEN3HSBLRapTiwcL2RN0HVTspjFC9op8MA7yLeFykI2FCMn+dgsTGl3z9fHOldzA=="
}

processing payment/init request ...

payment/init failed, http response: 400

how can i verify these things?
Please help.

Link to test page.
http://ariana-koberce.cz/csob/

**Comment by Mspisar** [comment]
Hello,
your request was redirected to responsible colleague and will be answered as soon as possible. 
best regards 
Milan Spisar

**Comment by vzich** [comment]
Hello, I tried your test page and it returned HTTP 400 aswell. It seems you are using wrong private key (you should use the key, which you generated 2.4. 2018 at 10:21). Best option to check validity of your keys is operation echo - [link](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7-EN#getpost-httpsapiplatebnibranacsobczapiv17echo-).

**Comment by GekM** [comment]
Everything now ok. Thank you!
