### ISSUE TITLE
RU language of bank page.

### ISSUE THREAD

**Issue by serkat** [csob/paymentgateway#375]
Hello. Is there any possibility to see paymant page on russian language?  When buyer go to payment page from your site.
Thanks

**Comment by aKocian** [comment]
Hello, 
Yes, you can use parameter language in payment/init.
_https://github.com/csob/paymentgateway/wiki/eAPI-v1.7-EN#-post-httpsapiplatebnibranacsobczapiv17paymentinit-_

**Comment by serkat** [comment]
Thanks!
