### ISSUE TITLE
Nefunguje inicializace oneclick - TSGSMIPS-5970

### ISSUE THREAD

**Issue by jahr** [csob/paymentgateway#376]
Dobrý den,

zkouším v prostředí "pískoviště" provést inicializaci oneclick platby. Bohužel, inicializace se nepodaří, ať používám libovolnou testovací kartu. Nejprve se objeví stránka ACS server simulator, na které je uvedeno, že se autorizace podařila, ale poté se již zobrazuje jen hláška Probíhá autorizace vaší platby. Vždy to skončí  chybou
Omlouváme se za nepříjemnosti, platbu se z technických důvodů na naší straně nepodařilo zpracovat. Platbu můžete zkusit znovu.
a dojde k timeoutu.
Před několika týdny tato funkcionalita fungovala a procesování běžných plateb funguje stále.
Děkuji za radu.

**Comment by ratajskym** [comment]
Dobrý den, o problému na integračním prostředí víme a řešíme to. O vyřešení Vás budu tady informovat

**Comment by ratajskym** [comment]
Vyzkoušejte prosím nyní

**Comment by jahr** [comment]
Děkuji, nyní už to funguje.
