### ISSUE TITLE
návratová URL - TSGSMIPS-6016

### ISSUE THREAD

**Issue by maleklukas1** [csob/paymentgateway#378]
Dobrý den,

pro testování využíváme vzor https://github.com/csob/paymentgateway/tree/master/Integration%20Examples/eAPI%20v1.6 a vygenerované Merchant ID - A32499urMF.
Vše se zdá v pořádku, máme nastavené $returnURL, akorát bychom potřebovali do nastavit návratovou adresu, pakliže uživatel dá na platební bráně "Zrušit". Nyní jsou obě stejné. Při zrušení by měla mít hodnotu včetně ID transakce od banky - www.xxx.cz/neco?error=0&preruseno=1&orderid=X&transakceid=X .

Neuměli by jste nám s tím pomoci? 

Předem děkuji

Lukáš Málek

**Comment by mrazekl** [comment]
Dobrý den,

hodnota returnUrl je vždy stejná. Na straně e-shopu můžete dále přesměrovávat dle stavu transakce z paymentStatus v návratových hodnotách, viz. https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#n%C3%A1vratov%C3%A9-hodnoty-

**Comment by ratajskym** [comment]
Dobrý den, 

$payId se do návratové url dostat nedá. Tato se nastavuje při volání payment/init, tedy ve chvíli, kdy ještě $payId neznáte. Při návratu z bránu dostáváte payId, neměl by tedy být problém ho dále použít ve Vašem skriptu.
