### ISSUE TITLE
Payment/init failed, reason: <url> malformed

### ISSUE THREAD

**Issue by GekMDN** [csob/paymentgateway#379]
Good day.
During the intergration of the payment system, I experienced the following error, "payment/init failed, reason: <url> malformed". What could be the problem? And how can I solce it? MerchantID - M1MIPS1813. 
Best regards,
Evgneii Modniy.

**Comment by aKocian** [comment]
Dear Evgneii,

your request is registered as an issue TSGSMIPS-6061 and forwarded to responsible service technician. 

Best regards,
Alexander Kocian

**Comment by mrazekl** [comment]
Hello,

please, tell me when u try this order? I saw two trying with Merchant ID M1MIPS1813 from yesterday , but both of these has payment/init successfuly.

**Comment by GekMDN** [comment]
Excuse me, at the cart of http://ariana-koberce.cz/ when I try initialize payment by cart. 
Succsesfull payment was made here http://ariana-koberce.cz/csob/.

**Comment by ratajskym** [comment]
What is url that you are sending request to ? According to your log, it seems that is somehow malformed.

**Comment by zheselevko** [comment]
https://secure.web-payment-software.com/gateway

**Comment by zheselevko** [comment]
----- Thu, 19 Apr 2018 11:19:48 +0000 ----- payment/init data to sign:: 'M1MIPS1813|136|20180419111948|payment|card|1000000|CZK|false|http://ariana-koberce.cz/index.php?route=tmdqc/tmdcheckout|POST|Shopping at ...|1|1000000|test...|Shipping|1|0|PPL|test|test|CZ'

**Comment by ratajskym** [comment]
This is not url of CSOB payment gateway

**Comment by zheselevko** [comment]
this is what the log file writes

**Comment by zheselevko** [comment]
$url = "https://iapi.iplatebnibrana.csob.cz/api/v1.5"; this address is in the settings

**Comment by zheselevko** [comment]
<div id="final-button" class="col-md-8 col-md-offset-2">preparing cart data:
[
    {
        "name": "Shopping at ...",
        "quantity": 1,
        "amount": 1000000,
        "description": "test..."
    },
    {
        "name": "Shipping",
        "quantity": 1,
        "amount": 0,
        "description": "PPL"
    }
]

data to sign:
"M1MIPS1813|141|20180419122813|payment|card|1000000|CZK|false|http://ariana-koberce.cz/index.php?route=tmdqc/tmdcheckout|POST|Shopping at ...|1|1000000|test...|Shipping|1|0|PPL|test|test|CZ"

prepared payment/init request:
{
    "merchantId": "M1MIPS1813",
    "orderNo": "141",
    "dttm": "20180419122813",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 1000000,
    "currency": "CZK",
    "closePayment": "false",
    "returnUrl": "http://ariana-koberce.cz/index.php?route=tmdqc/tmdcheckout",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 1000000,
            "description": "test..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 0,
            "description": "PPL"
        }
    ],
    "description": "test",
    "merchantData": null,
    "customerId": "test",
    "language": "CZ",
    "signature": ""
}

processing payment/init request ...

payment/init failed, reason: &lt;url&gt; malformed
</div>

**Comment by ratajskym** [comment]
You have succesfull transaction from todays morning 2018-04-19 09:13:45

What did you change since then ?

**Comment by zheselevko** [comment]
payment/init failed, reason: Merchant blocked.  please unlock Merchant I need a couple more tests to do

**Comment by Mspisar** [comment]
Hello,

please send your request to an email: akceptacekaret@csob.cz.

thanks

best regards

Milan Spisar

**Comment by zheselevko** [comment]
Hey. can not get payment status. paid for it or not. Do not tell me how to get it?

**Comment by mjanek** [comment]
Hello, it is ok. What number is in your "paymentStatus":  ??? 

"payId":"d165e3c4b624fBD",
  "dttm":"20140425131559",
  "resultCode": 0,
  "resultMessage":"OK",
  "paymentStatus": 1,
"

**Comment by zheselevko** [comment]
paymentStatus 3 and 4

**Comment by mjanek** [comment]
If you read https://github.com/csob/paymentgateway/wiki/eAPI-v1.7-EN#transaction-life-cycle
you learn that it is ok. 

3 - payment cancelled
4 - payment confirmed - in this step, you need to go to posmerchant and confirm this transaction. Or if you want automatic settlement you need change method "closePayment" like this: "closePayment": true
