### ISSUE TITLE
Specifikace jazyka pro platební bránu

### ISSUE THREAD

**Issue by itstudiocz** [csob/paymentgateway#38]
Dobrý den,

platební brána GP WebPay automaticky nastavovala jazyk platební brány dle jazyka prohlížeče. Po testování zjišťujeme, že platební brána ČSOB toto ale bohužel nepodporuje - potřebujeme u platební brány pro jednoho z našich klientů nastavit automaticky jazyk DE. Můžeme to nějak udělat zároveň s přechodem pomocí Legacy API, nebo můžete pro obchodníka nastavit defaultní jazyk Vy?

Děkuji za odpověď.

**Comment by ratajskym** [comment]
Dobrý den, tato funkcionalita není na platební bráně podporovaná.

**Comment by itstudiocz** [comment]
Dobrý den, to je ale docela problém, jelikož se jedná o e-shop mířený pouze na německý trh. Vzhledem k tomu, že platební brána GP WebPay toto podporovala, očekával bych, že to budete podporovat i Vy (rozpoznání jazyka dle preferovaného jazyka prohlížeče), viz:

*GP webpay umožňuje přijímat platby nejen v českých korunách a eurech, ale i v amerických dolarech, britských librách, maďarských forintech, polských zlotých a ruských rublech.* **Zákazníkům ze zahraničí se také automaticky přizpůsobí jazyk platební brány.**

Plánujete tuto funkcionalitu doprogramovat?

**Comment by ratajskym** [comment]
Dobrý den, doplním mou předchozí informaci.

v LegacyAPI se nově řídí default jazyk nastavením prohlížeče. Pokud budete mít default jazyk prohlíže např. Angličtina, zobrazí se v tomto jazyce i platební brána. Pokud budete mít nastaven jiný jazyk, než který je podporovaný, bude brána zobrazena v češtině (nasazeno bude do konce týdne).

NativeAPI - default jazyk se řídí parametrem LANGUAGE (nezmiňoval jsem to, ptal jste se na Legacy)

**Comment by JosefJu** [comment]
Dobrý den. Nám platí lidé z dalších zemí, kteří mají nastaven jako výchozí jazyk prohlížeče třeba španělštinu, italštinu, korejštinu, japonštinu. Pokud je my nemůžeme poslat na stránku s výchozím textem anglickým, bylo by optimální, kdyby při nepodporovaném výchozím jazyku jiném než blízkých slovanských jazycích (sk, pl) nabíhala jako výchozí angličtina.

**Comment by ratajskym** [comment]
Dobrý den, 

pokud bude jazyk prohlížeče jiný, než podporuje platební brána, bude defaultně zobrazena angličtina. Připravujeme update aplikace, kterou nasadíme v průběhu příštího týdne.
