### ISSUE TITLE
Platebni tlacitko

### ISSUE THREAD

**Issue by mfeuermann** [csob/paymentgateway#380]
Dobry den,

chtel jsem se zeptat jestli je mozne pomoci testovaciho rozhrani otestovat uspesnou platbu pres Payment tlacitko. Jak je mozne prosim otestovat uspesnou platbu pres payment tlacitko ?

Dekuji

**Comment by aKocian** [comment]
Dobrý den.

Ano, platební tlačítko by ste měl být schopný otestovat i v integračním prostředí.
Zasílám Vám odkazy kde je platební tlačítko popsáno : 
https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#platba-pomoc%C3%AD-platebn%C3%ADho-tla%C4%8D%C3%ADtka-%C4%8Csob--po%C5%A1tovn%C3%AD-spo%C5%99itelny-
https://github.com/csob/paymentgateway/wiki/Platebn%C3%AD-tla%C4%8D%C3%ADtko-%C4%8CSOB-a-Po%C5%A1tovn%C3%AD-spo%C5%99itelny
https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#post-httpsapiplatebnibranacsobczapiv17paymentbutton-

S pozdravem
Alexander Kocian

**Comment by mfeuermann** [comment]
Dekuji toto jsem cetl nicmene u nasi produkcni platebni brany se objevila v transakcich zaznam s priznakem PT-CSOB. Predpokladam tedy, ze nekdo vyuzil platebni tlacitko primo v rozhranni platebni brany. Je mozne toto vyzkouset aniz by se tlacitko muselo integrovat ? Dekuji

**Comment by vzich** [comment]
Dobrý den, 
ano transakci přes platební tlačítko je možné inicializovat přímo z FE platební brány. Pokud pošlete ve volání payment/init, parametr payOperation:"payment" a máte aktivní platební tlačítko. Tak by se vám mělo platební tlačítko zobrazit.

**Comment by mfeuermann** [comment]
OK ja to ale myslim jinak. Na testovaci platebni brane jiz mam tlacitko, to tlacitko je ale neaktivni.
Potreboval bych vyzkouset tlacitkem v testovacim prostredi zaplatit... To znamena zobrazit testovaci platebni branu s tlacitkem, na tlacitko kliknout, tim potvrdit platbu... Je toto mozne v testovacim prostredi ? Dekuji za info

**Comment by mfeuermann** [comment]
Rad bych si v testovacim prostredi overil platbu na tlacitko od zacatku az do konce...

**Comment by mfeuermann** [comment]
V testovacim prostredi platebni brany je totiz tlacitko neaktivni... nic to nedela a neni tak mozne otestovat platbu od zacatku az do konce...

**Comment by vzich** [comment]
Předpokládám, že nemáte platební tlačítko v eshopu (pt@shop) aktivní. Pro aktivaci je třeba kontaktovat akceptacekaret@csob.cz. Pokud zašlete merchantID, tak můžeme prověřit nastavení/případně logy.

**Comment by mfeuermann** [comment]
Dobry den, na zaklade nasi telefonicke dohody posilam merchantId testovaci brany 
jedna se o MerchantID - M1E3CB3838

**Comment by aKocian** [comment]
Issue dořešené s klientem po telefonu.
