### ISSUE TITLE
Výzva k aktualizaci prohlížeče

### ISSUE THREAD

**Issue by miloslavkostir** [csob/paymentgateway#381]
Dobrý den

v integračním prostředí (https://iapi.iplatebnibrana.csob.cz) se mi po přesměrování na platební bránu zobrazí výzva k aktualizaci prohlížeče. Aktuálně mám Google Chrome ve verzi 66.0.3359.117, což se tváří jako aktuální. Ve Firefoxu, Opeře a Internet Exploreru běží. V ostrém provozu jsem to nezkoušel. Ještě dnes ráno to fungovalo.

![screen_ 2018-04-2302](https://user-images.githubusercontent.com/5463235/39127438-54c04664-4705-11e8-9245-ebcf6a34d426.jpg)
![screen_ 2018-04-2303](https://user-images.githubusercontent.com/5463235/39127449-599166c8-4705-11e8-90c8-a09e575a3752.jpg)

**Comment by aKocian** [comment]
Dobrý den,
 
Váš požadavek byl zaevidován pod: TSGSMIPS-6090 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
 
S pozdravem
Alexander Kocian

**Comment by miloslavkostir** [comment]
Dobrý den,

funguje, díky.
