### ISSUE TITLE
Nefunkční Masterpass platba

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#382]
Dobrý den,
od včerejška nás kontaktovalo několik zákazníků že jim nefunguje platba masterpass. Po potvrzení platby QR kodem se v lightboxu objeví Platba zrušena a platba skončí zamítnutím.

Např. payId 312a571eea6f3DD, 3670a790811e2DD, 10f46389dd0a6DD

Prosím o prověření.

**Comment by mrazekl** [comment]
Dobrý den,

transakce prověříme a jakmile budeme znát detaily, obratem Vám je sdělíme.

**Comment by vzich** [comment]
Dobrý den, 
312a571eea6f3DD - zamítnuta od vydavatele karty, pro více informací musí klient kontaktovat vydavetele.
U payID 3670a790811e2DD a 10f46389dd0a6DD, klienti byly přesměrování na masterpass peněženku, nicméně se vrátili na platební bránu/shop zavřením peněženky. Podle těchto indicií se zřejmě jednalo o problém na straně mpass peněženky.
