### ISSUE TITLE
Nefunkční oneclick platby v testovacím prostředí

### ISSUE THREAD

**Issue by jahr** [csob/paymentgateway#383]
Dobrý den,

zkouším oneclick platby v Testovacím (implementačním) prostředí pro platební bránu (tedy s už přiděleným merchant ID). Podaří se mi zaregistrovat testovací kartu pro oneclick (pomocí payment/init, payOperation = oneclickPayment), ale poté, při inicializaci samotné platby (pomocí payment/oneclick/init) dostanu odpověď
resultCode: 0
resultMessage: "payment/oneclick amount exceeds origin payment amount"
paymentStatus: 6
Rád bych se zeptal, v čem může být problém. Pokud stejný postup zkouším v prostředí pískoviště, funguje to bez problému.

Děkuji

**Comment by vzich** [comment]
Dobrý den,
podle uvedené hlášky zasíláte v opakované platbě částku vyšší než byla prvotní autorizovaná transakce(šablona). Pokud chcete uvedené omezení zrušit, je třeba kontaktovat akceptacekaret@csob.cz

**Comment by jahr** [comment]
Dobrý den,

děkuji za odpověď. Rád bych se tedy zeptal, jak nastavit v šabloně tuto částku. Jestli jsem to dobře pochopil, je potřeba při inicializaci oneclick zaplatit určitou malou částku (1 Kč). Tato částka je uvedena v parametru totalAmount a majiteli platební katry je stržena. V parametru cart (který je podle podle dokumentace povinný) je také jedna položka se stejnou cenou. Do kterého parametru mám tedy dát maximální výši platby pomocí oneclick?

Děkuji

**Comment by vzich** [comment]
Dobrý den,
při opakovaných platbách je kontrola, zda je výsledná autorizovaná částka prvotní platby menší nebo rovna této částce (tzn. parametr totalAmount v payment/init), pokud je větší tak je inicializace zamítnuta.
Mimochodem v košíku můžete poslat i dvě položky, jejich výsledná cena ale musí souhlasit s částkou v totalAmount.

**Comment by jahr** [comment]
Dobře, děkuji, obrátím se na uvedenou mailovou adresu.
