### ISSUE TITLE
Nemuzu se prihlasit do implementacniho prostredi posmerchant

### ISSUE THREAD

**Issue by alexmorgan9975** [csob/paymentgateway#384]
Dobry den, mam problem. Sjednali jsme platebni brany od CSOB, a mame pristup do ostre verze posmerchant. Ale nemame do implementacni verze posmerchant. Klice jsme vygenerovali, vse uspesne, nainstalovali (nas eshop od atomer jiz ma modul platebni brany csob), provedli jsme testovaci platbu ale nemuzeme branu aktivovat, protoze musime platbu potvrdit v test posmerchantu. Kdyz se snazime v test posmerchantu zazadat o nove heslo tak nam to pise ze uzivatel nenalezen. Prosime o pomoc nebo aktivaci nasich bran (mame jich celkem 5: M1MIPS2451,M1MIPS2452,M1MIPS2453,M1MIPS2454,M1MIPS2455). Nase uzivatelske jmeno je: 25452207 a kontaktni email: ubs@unitrade.cz - ale kdyz toto zadavame na test posmerchant na zaslani hesla - tak pise uzivatel nenalezen. A do ostre verze pristup mame. Take uvadim ze verejne klice jsme uploadovali do banky. Ale stale brany jsou blokovane.
Predem moc dekujeme za pomoc.Platebni brany potrebujeme zprovoznit co nejrychleji.
S pozdravem
V.Morgovsky
Jednatel UBS s.r.o. #

**Comment by alexmorgan9975** [comment]
Dobry den, moc krat dekuji za rychlou opoved. Ano, REVERZAL pouzivat nebudeme.  Budeme tedy dnes sledovat v posmerchantu zda brany byli aktivovane. Opravdu potrebujeme uz to zprovoznit co nejdrive. 
Jeste jednou moc dekuji za Vasi pomoc.

**Comment by alexmorgan9975** [comment]
Dobry den pane Mrazek,
Obracim se na Vas s stejnym problemem jako minuly rok. Nyni se snazim aktivovat platebni branu na e-shop www.ntlprime.eu , Klice jsem vygeneroval a nahral, verejny klic jsem poslal do banky. Testovaci transakce byla uspesna. Ale zase se nemuzu dostat do testovaciho prostredi, abych povrdil transakci a aby brana byla aktivovana. Mam pouze zas pristup do ostreho prostredi POSTMerchant. Uzivatelske jmeno je: 05330131. Heslo jsem zmenil na nove. Stav brany ID: M1MIPS7021 - blokovany. Nemohl by jste prosim branu aktivovat? Stejne jako minule, neplanujeme pouziti REVERZAL. Predem moc dekuji za Vasi pomoc. S pozdravem Alex.M Technický správce Ntlprime.eu

**Comment by mrazekl** [comment]
Dobrý den,

pro ID brány M1MIPS7021 nevidím všechny požadované transakce. Udělejte prosím znova úspěšnou, zamítnutou a zrušenou transakci a zašlete e-mail na akceptacekaret@csob.cz s žádostí o aktivaci do produkčního prostředí bez možnosti reverzalu.
Zároveň zde můžete popsat situaci z Vašeho commentu.

**Comment by alexmorgan9975** [comment]
Dobry den,
Dekuji moc za odpoved. Dnes jsem vyzkousel vsechny simulace platby z stranky: https://github.com/csob/paymentgateway/wiki/Credit-Cards-for-Testing Email na akceptacekaret napisu. Vim ze minule jsem tam jiz psal a nakonec pomohl jste Vy. :-) Prosim Vas jestli by jste nemohl provest aktivaci brany M1MIPS7021 ?  Predem moc dekuji za Vasi pomoc. 
S pozdravem Alex.M Technický správce Ntlprime.eu

**Comment by patkis** [comment]
Dobry den prajem,

tiez to isty problem, nevieme prihlasit do implementacnej verzii postmerchant. Testovacie platby sme spravili. Mozete prisim aktivovat nasu branu id M1MIPS7419? Dakujem pekne.

**Comment by mrazekl** [comment]
Pro aktivaci do produkce, v případě že se nemůžete přihlásit do portálu PosMerchant slouží primárně kontakt akceptacekaret@csob.cz, kde zároveň můžete zažádat o z vygenerování nového hesla pro integraci i produkci
