### ISSUE TITLE
Návrat v podivném stavu životního cyklu transakce

### ISSUE THREAD

**Issue by arxeiss** [csob/paymentgateway#386]
Dobrý den,

dnes nastala zvláštní situace. Po návratu z platební brány byl stav objednávky **2 -  Platba probíhá**, což podle diagramu ve [Wiki](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#%C5%BDivotn%C3%AD-cyklus-transakce-) je stav, ve kterém by nemělo dojít k návratu do obchodu. Alespoň podle textu, opět z Wiki:

> ... Tyto kroky jsou pro obchodníka skryty za průběhem platby, zajímá ho až samotná výsledek. Ten může být: ...

Následně jsou vyjmenovány stavy 3, 6, 4 a 7. Nikoli stav 2. Proto jsem nákup označil jako neúspěšný a stornoval jej. Zákazník ale psal, že peníze byly strženy z účtu a po kontrole opravdu transakce byla ve stavu **7 - Čekání na zúčtování**. Protože mezitím byl proveden další nákup, tuto transakci jsem stornoval.

Jedná se chybu, nebo jen špatné popsání stavů ve Wiki? Jednalo se o transakci s payID: _191df30215090DE_

**Comment by ratajskym** [comment]
Dobrý den, když se dívám do logu, tak se vám na eshop vrátil stav 7 - potvrzeno
{"payId":"191df30215090DE","dttm":"20180514122940","resultCode":"0","resultMessage":"OK","paymentStatus":"7" ..

Ve stejný okamžik jste poslal payment/status a ten Vám skutečně vrátil stav - 2, tedy probíhá (toto ještě prověřujeme)

**Comment by arxeiss** [comment]
Dobrý den,

používám implementaci od [Slevomatu](https://github.com/slevomat/csob-gateway) a v README.md je ukázka, jak zapracovat příchozí stav. Navíc jsem si tam dodělat podporu pro EET rozšíření, proto je ve stejný okamžik odeslán nový request. Výsledný kód z POSTu je tedy ignorován a získán z nového requestu.

Díky
