### ISSUE TITLE
Chyba "Přesměrování na platební bránu se nezdařilo" [WooCommerce]

### ISSUE THREAD

**Issue by otevrel** [csob/paymentgateway#387]
Dobrý den,

před podpisem smlouvy chci otestovat integraci do WooCommerce. Postupoval jsem dle návodu zde na GitHUBu (klíče a ID jsem vygeneroval zde: https://iplatebnibrana.csob.cz/keygen/ ), ale po odeslání objednávky dostávám následující hlášení:
![image](https://user-images.githubusercontent.com/39554254/40418765-838a932e-5e83-11e8-800d-2b9577eb2fec.png)

nastavení vypadá takto:
![image](https://user-images.githubusercontent.com/39554254/40418986-249b37dc-5e84-11e8-9e73-acc644dfac08.png)

Předem děkuji za radu.

**Comment by vzich** [comment]
Dobrý den,
podle aplikačního logu jste Vaše klíče uložil ale neodeslal jste veřejný klíč do banky. Viz. screen při vygenerování anonymního ID.

![image](https://user-images.githubusercontent.com/17046375/40421595-c09f66fa-5e8c-11e8-8db7-d0ca684e37b9.png)

**Comment by otevrel** [comment]
To bylo ono. Problém vyřešen.
