### ISSUE TITLE
Integrace - krok za krokem?

### ISSUE THREAD

**Issue by janiv4** [csob/paymentgateway#388]
Dobrý den, prosím o step-by-step návod k provedení integrace platební brány, stávající materiály jsou zjevně určené vývojářům, ne koncovým uživatelům (jako já).
Mám: 
- veřejný klíč mips_iplatebnibrana.csob.cz z repozitáře github
- vygenerovaný privátní klíč z iplatebnibrana.csob.cz

Co s nimi? Nahrát na hosting? Uvést kompletní znění klíče v administraci Monet Payment Gateway? Uvést tam název souboru...? Potřebuju zjistit, jak nastavit Monet Payment Gateway v administraci WordPressu tak, abych se vůbec mohl dostat dál...

Na tyto triviální dotazy jsem ve stávající dokumentaci nenašel odpověď... Berte to, prosím, jako zpětnou vazbu k nesrozumitelnosti postupu podle stávajících materiálů.

**Comment by ratajskym** [comment]
Dobrý den, pro zprovoznění pluginu pro WP je k dispozici readme [zde](https://github.com/csob/paymentgateway/tree/master/WooCommerce%20Plugin)

**Comment by ratajskym** [comment]
Dobrý den @janiv4 , povedl se Vám problém s klíči vyřešit ?
