### ISSUE TITLE
Zapojení platební brány

### ISSUE THREAD

**Issue by jitkavagnerova** [csob/paymentgateway#39]
Dobrý den,

mám dotaz, jestli je možné nastavit platební bránu bez znalostí s programováním? Používáme web založený na platformě miowebu (šablona webu, na které si jen přidáváme sekce, aniž bychom museli programovat). 

Je možné poslat nějaký návod, jak platební bránu implementovat do našeho webu, nebo to laik nezvládne a máme se obrátit na nějakého webmastera? 

Prozatím jsme vygenerovali testovací klíče (veřejný a soukromý), otevřeli POSMerchant a u test komunikace nám vyšlo response code OK. 

Jak máme postupovat dále? 

Předem mnohokrát za odpověď. Jitka

**Comment by ratajskym** [comment]
Dobrý den, 

vzorovou implementaci najdete [zde](https://github.com/csob/paymentgateway/tree/master/eshop-integration/eAPI/v1) . Váš systém neznám, těžko říct jaké tam máte možnosti.
