### ISSUE TITLE
Moznost pouzitia eAPI na Slovensku ?

### ISSUE THREAD

**Issue by ps-aux** [csob/paymentgateway#390]
Dobry den,

je mozne pouzivat eAPI na Slovensku ? Pri implementacii eshopu (v Jave) sme dostali len info k GP Webpay ale chceli by sme pouzivat novsiu API. 

Je toto mozne v pripade Slovenskej CSOB ?

**Comment by mjanek** [comment]
Dobrý den,
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

M.Janek

**Comment by ps-aux** [comment]
To je skoda :)  Dakujem za informacie.
