### ISSUE TITLE
Časový interval změny stavu a dotaz na deploy

### ISSUE THREAD

**Issue by jformanek** [csob/paymentgateway#391]
Dobrý den,

po jaké době se změní stav platby na stav 6 (Platba zamítnuta), pokud uživatel zavře okno brány? Tzn. status zůstane viset na 2 (Platba probíhá)? Nikde se mi to nepodařilo najít.

A druhý dotaz - pokud mám implementaci brány hotovou a má se odeslat k ověření, musí už běžet přímo na "ostré" doméně? Deploy testovací verze totiž provádím na jiný server, než na kterém poběží produkční verze.

Děkuji,
Jakub F.

**Comment by vzich** [comment]
Dobrý den, 
životnost transakce je defaultně stanovena na 30min. Pokud životnost chcete upravit, tak je možná úprava pomocí parametru ttlSec v requestu payment/init - viz. [dokumentace ](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#-post-httpsapiplatebnibranacsobczapiv17paymentinit-) a to v rozmezí 5 - 30 minut.

**Comment by jformanek** [comment]
Dobře, díky. A ještě prosím jak s deploy - je nutné mít projekt buildnutý na produkčním prostředí akorát s testovacím rozhraním brány, aby mohlo dojít k ověření? Nebo může dojít k ověření i na testovacím serveru?

Děkuji,
Jakub F.
