### ISSUE TITLE
CSOB Asset Management REST API pro fondy, etc.

### ISSUE THREAD

**Issue by dmpe** [csob/paymentgateway#392]
Ahoj CSOB, 
Vim, ze to sem nepatri, ale jelikoz je to tady jidiny repo, tak by mě zajimalo zda nabizite REST API pro fondy co jsou dostupne treba zde: <https://www.csobam.cz/portal/asset-management/produkty-a-sluzby/aktualni-hodnoty-a-vykonnost>? Pripadne za jakych podminek (💰 , ⌛️ , apod.).

Typicky quering na jejich cenu, nazev, atd. Klidne mi napiste na email v profilu na koho bych se mohl obratit. 
Dekuji.

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaregistrován a předán k řešení. O dalším postupu budete informován.

s pozdravem

Spisar
