### ISSUE TITLE
DragonflyBrandCom

### ISSUE THREAD

**Issue by dragonflybrandCOM** [csob/paymentgateway#393]
Dobrý den,

aktuálně doděláváme kompletně nový eshop u jiné firmy a spolu s novým eshopem bychom přešli na novou ČSOB bránu. Eshop budeme spouštět během cca 2-3 týdnů.
Je možné ještě počkat, než nám GPwebpay vypnete? Nemá smysl napojovat novou bránu do starého eshopu kvůli pár týdnům provozu.

děkuji za pochopení

-- 
S pozdravem

Petr Líbenek

**Comment by ratajskym** [comment]
Dobrý den, 

tohle není issue, se kterým bychom Vám mohli pomoci. Kontaktujte prosím svého bankovního zástupce, se kterým řešíte smlouvu o provozu platební brány.
