### ISSUE TITLE
Variabilní symbol  - párování plateb

### ISSUE THREAD

**Issue by 18622933** [csob/paymentgateway#394]
Dobrý den,

Mám jednu žádost, využíváme platební  bránu, ale na výpisech o transakcích uskutečněných platebními kartami nejsme schopni identifikovat podle variabilního symbolu platby. Rezervační systém vygeneruje letenku a sumář s vlastním variabilním symbolem, ale brána přiřadí vlastní variabilní symbol který se objevuje na výpise. 
Bylo by možné do variabilního symbolu přenášet číslo z rezervačního systému? 
V příloze (variabilní symbol z rezervačního systému Galileo - příloha 1,  výpis transakcí s jiným asi přiděleným bránou variabilním symbolem – příloha 2, Detail platby - příloha 3)

V současné době nemáme jak párovat a identifikovat platby. Komplikuje nám to dost práci.

Předem děkuji za reakci a přeji pěkný den.
Daniel Haller
Marketing Manager
Cestovní kancelář
NEMO & SELECTA , s.r.o.  (člen Travel Alliance a.s.) 
Politických vězňů 1658/8, 110 00 Praha 1, Czech Republic
IČO: 18622933, DIČ: CZ 18622933
mobile: +420 602 750 970 | phone: +420 224 228 627 | 
e-mail: haller@nemoletenky.cz|skype: d-haller
[Priloha_1.pdf](https://github.com/csob/paymentgateway/files/2205339/Priloha_1.pdf)
[Priloha_2.pdf](https://github.com/csob/paymentgateway/files/2205340/Priloha_2.pdf)
[Priloha_3.pdf](https://github.com/csob/paymentgateway/files/2205341/Priloha_3.pdf)

**Comment by mjanek** [comment]
Dobrý den, 
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem
Miroslav Janek

**Comment by vzich** [comment]
Dobrý den,
při založení platby přes platební bránu se Vám do výpisu propíše parametr orderNo podle kterého můžete párovat objednávky. Ve vašem případě Váš eshop zasílal (pro 2 transakce z přílohy 2) orderNo 210411 a 210533. Pokud chcete tedy plnit hodnotu z "Galilea" bude třeba upravit na straně eshopu, tak aby plnil touto hodnotou parametr orderNo.
