### ISSUE TITLE
problém s generováním klíče pro produkci

### ISSUE THREAD

**Issue by radovanx** [csob/paymentgateway#396]
Po úspěšném otestování se nám nedaří vygenerovat klíč na https://platebnibrana.csob.cz/keygen/
Zadávám údaje které vidím na https://posman.csob.cz/posmerchant
Vrací se 
Zadali jste nesprávný merchant ID nebo e-mail.

**Comment by mrazekl** [comment]
Dobrý den,

Pro vygenerování je nutné uvést email technické podpory, v tom bývá nejčastější problém. Přišel Vám potvrzovací e-mail o aktivaci v produkčním prostředí? Popřípadě uveďte, prosím, jaké používáte Merchant ID.

**Comment by radovanx** [comment]
Merchant ID je  M1MIPS3666

**Comment by mjanek** [comment]
Dobrý den, 
pro úspěšné přepnutí do produkčního přostředí je potřeba ještě provést na vašem ID  testovací transakci se stavem autorizována/poslána k zaúčtování a poté odeslat validaci. Až v tento moment Vás možné přepnout do produkčního prostředí.

**Comment by radovanx** [comment]
to jsem provedl jiz dvakrat

**Comment by radovanx** [comment]
klice nelze stale vygenerovat

**Comment by mjanek** [comment]
Vyčkejte na email z ČSOB o provedené aktivaci produkčního prostředí. Tento proces nějakou chvíli trvá. Jakmile Vám příjde email, bude možné provést nové generování klíčů.

**Comment by radovanx** [comment]
ok dekuji muzeme uzavrit
Zdravi

**Comment by radovanx** [comment]
Dobry den,
Znovu otviram z banky odpovedeli takto.
Produktové klíče se generují až po validaci platební brány poté co
projde přes testovací prostředí. Zatím není dokončeno. 
Vy pisete toto 
Nyní vidíme všechny 4 transakce vpořádku - v testovacím posmerchant kliknete na tlačítko "Provést validaci" a poté na "odeslat požadavek".

V cem je problem ?

**Comment by radovanx** [comment]
Dobrý den,

Protože nebylo schváleno tak se musí test opakovat ?

**Comment by mrazekl** [comment]
Dobrý den,
postupoval jste správně. Pokud budete žádat o aktivaci emailem, testy znova provádět nemusíte, jen uveďte, že již máte všechny testovací transakce hotovy.
Stav, ve kterém je transakce, je pro testy stěžejní. Očekává se zrušená, zamítnutá a reverzovaná transakce - tyto stavy se bez zásahu admina již nemění. Poslední transakce se očekává ve stavu autorizovaná/poslaná k zaúčtování - tento stav je dočasný, jakmile se transakce zaúčtuje, přejde do stavu "zaúčtováno".

**Comment by bogdandovgopol** [comment]
Dobrý den, mam podobný problém. Mohu se přihlásit do produkčního POS Merchantu, ale nemohu do Integračního POS Merchantu, a taky si nemohu si vygenerovat produkční klíče, hlásí stejnou chybu "Zadali jste nesprávný merchant ID nebo e-mail" Merchant ID M1MIPS7969
