### ISSUE TITLE
Currency EUR not allowed

### ISSUE THREAD

**Issue by viktorzavadil** [csob/paymentgateway#397]
Dobrý den,

API platební brány mi hlásí `Init payment failed: Currency parameter EUR not allowed`, jedu proti `https://iapi.iplatebnibrana.csob.cz/api/v1.7/`, je tato měna v testovacím režimu povolena? S měnou `CZK` mi to funguje.

Děkuji za reakci.

**Comment by mrazekl** [comment]
Dobrý den,
různé měny jsou v testovacím prostředí podporovány, musí však být povoleny pro obchodníka a ve Vašem případě zřejmě povoleno nemáte. Pokud chcete testovat v EUR, obraťte se prosím na banku(akceptacekaret@csob.cz) pro povolení.

**Comment by viktorzavadil** [comment]
Dobrý den,
neřešil jsem to, protože mi to příde nešťastné. Mám vygenerovaný dočasný `merchantId` a asi nechci pro každý takový žádat banku o povolení EUR.
Každopádně díky za info, až bude potřeba, udělám to :) Vy s tím procesem schvalování asi nic dělat nemůžete a nebudete, tak to klidně můžeme uzavřít.
