### ISSUE TITLE
OCR kreditní karty

### ISSUE THREAD

**Issue by landsman** [csob/paymentgateway#398]
Dobrý den,

velice by se nám líbila funkce možnost sejmout číslo karty fotoaparátem.
Máme zaimplementovanou bránu v mobilní aplikaci, kde nám to dává smysl.

Uvažovali jste o tom?
Bylo by možné tuto funkci přidat, kdy?

díky

**Comment by Mspisar** [comment]
Dobrý den, 

Váš požadavek /návrh na zlepšení jsme postoupili na patřičné oddělení.

s pozdravem

Spisar

**Comment by marekdub** [comment]
Dobrý den,
@landsman danou funkcionalitu zadáme na vývoj. Dám vědět, kdy by mohla být na platební bráně k dispozici.
pěkný den.
Marek Dub

**Comment by landsman** [comment]
Perfektní, máte nějaký odhad?

**Comment by landsman** [comment]
Dobrý den,

máte nějaký odhad z vývoje?

**Comment by landsman** [comment]
Dobrý den,
tak iOS 12 to vyřešilo za vás :) Teď ještě nějaké řešení pro Android.

![ios](https://user-images.githubusercontent.com/3184228/46738949-b696c280-cc9f-11e8-884d-d3b62b9090ef.png)

**Comment by landsman** [comment]
Dobrý den,

napadlo Vás nějaké řešení?

**Comment by janbrasna** [comment]
@landsman iOS to podporuje od verze iOS8 (stejne jako brana), na Androidu to byla otazka kdy se Google nauci spravne atributy inputu, ale nekdy cca od podzima take:

![screenshot_20180913-231148](https://user-images.githubusercontent.com/1784648/51284892-64c3ae00-19ed-11e9-8178-fa1fe3e4f521.png)

**Comment by landsman** [comment]
Android 8.1.0 zatím nic. Předpokládám, že je to screenshot z verze 9.

**Comment by janbrasna** [comment]
(Screenshot pochazi z uplne cisteho "out-of-the-box" systemu 8.0.0 bez jakychkoliv aktualizaci, s tehdejsi verzi Chrome browseru, cca 68.0.x v te dobe.)

Chrome (tj. vc. Androidu) se loni na jare naucil `inputmode` https://caniuse.com/#feat=input-inputmode tzn. to mimo jine spolu s #114 najednou dokaze obsluhovat pole jako cislo karty. Nicmene asi zavisi na jednotlivych firmwarech a vendorech, jake verze Blinku/chromia maji ve svem releasu, a zda a jak jsou podporovane Autocomplety, Autofilly (nove pridavany Autofill_Sync ktery v posledni dobe prinesl nekolik problemu s regresemi jiz davno opraveneho divneho chovani ap.) — jinymi slovy jsem jen chtel rict, ze pockat je potreba jen na jednotlive dodavatele a podporu v jejich systemech, bohuzel:/ Brana jako takova tyto systemove karetni skeny podporuje od zacatku — zbytek je na OS.

Jedine specifikum je systemovy prohlizec vs. webview v nativni aplikaci — tam se pravidla jeste lisi, a ano ani iOS jeste nedavno nepodporoval podobne Keychainove oprace uvnitr WebViews, resp. navic bylo potreba pro "materskou" aplikaci povolovat pristup ala `NSCameraUsageDescription`, ale to uz neni otazka webstandardu, ale spis podrobnosti nastaveni a pravidel SDK pro nativni appky kazdeho vydavatele…

**Comment by landsman** [comment]
Šlo řešit vlastím tlačítkem, které vyvolá scanování karty a fungovalo by to všude na 100%.
WebView na Android 9 + Chrome stále neumí.

**Comment by landsman** [comment]
Dobrý den,

zrovna jsem opisoval kartu do aplikace Rekola.cz, mám nejnovější iOS.

Můžete to prosím opravdu na Vaší straně připravit tak, aby na mobilních zařízeních (lze detekovat javascriptem, či přes CSS media query na šířku okna) bylo tlačítko skenovat kartu a vyvolalo buď systémovou aplikaci, či Vaší implementaci čtečky?

Určitě by to pomohlo tisícům Vašich zákazníků.

děkuji

**Comment by janbrasna** [comment]
Jak jsem uz psal, pravidla pro ruzne zabalene webviews do nativni aplikace se lisi, a k nim konkretne podporu nedokazeme nabidnout, o tom si lepe pohovorite se svymi vyvojari.

Jen zevrubne: ani `UIWebView` ani `WKWebView` nepovoluji pristup ke kartam v klicence (aktualne pouze k heslum) tj. ani ke skenovani, pouze `SFSafariViewController` to ma povolene, ptze bezi v separatnim procesu.

Takze je to otazka implementace v samotne aplikaci. Na strane brany (z pohledu HTML5, autofillu, klicenek atp.) je vsechno pro skenovani karet uz nekolik let jak ma byt.

**Comment by janbrasna** [comment]
PS: Ani v Safari kontroleru to ale neni jiste, driv bylo potreba si "po vlastni ose" vyresit entitlement na kameru jinak kontroler nic nevidel a dostaval jen cernou obrazovku a o privilege si rici sam neumel, atp. … jak se podobne bugy povedlo vyrobcum vyresit nemam info.

PS2: Co se tyce Chromu tak nektera zarizeni mela v lokalnim OCR horsi (=nespolehlive) vysledky nez jina, a proto je Google vyvojari podle uspesnosti vysledku rozdelili na takove, kterym lokalni skenovani karet zapnout, a kterym ho naopak umyslne vypnuli, daji se k tomu dohledat informace ve vyvoajrskych/produktovych komunitach chromia; jestli je to vyjadreni nekde public netusim, ale toto selektivni chovani je potvrzeno od Google engineeringu.
