### ISSUE TITLE
Automatické strhávání z karty

### ISSUE THREAD

**Issue by KristynaRuzickova** [csob/paymentgateway#399]
Dobrý den,
je prosím možné u platební brány nastavit předautorizaci platby či zapamatování karty? Zajímá mě konkrétně pravidelná platba za úklidové služby, kdy zákazník souhlasí s uložením jeho karty a my jako firma máme možnost bez dalšího svolení částku za službu strhnout.

**Comment by Mspisar** [comment]
Dobrý den, paní Růžičková,

Ano je to možné.
pro eAPI 1.5
https://github.com/csob/paymentgateway/wiki/eAPI-1.5#opakovan%C3%A1-platba-
pro vrze eAPI 1.6 a výše
https://github.com/csob/paymentgateway/wiki/Platba-Na-klik

s žádostí o rozšíření této funkce kontaktujte prosím banku na adrese:

akceptacekaret@csob.cz

s pozdravem

Spisar

**Comment by KristynaRuzickova** [comment]
Děkuji za rychlou reakci a přeji hezký víkend.

*Kristýna Růžičková*
Team manager

Tel: +420-773 949 905
Mail: kristyna@VasePokojska.cz
www.VasePokojska.cz






so 8. 9. 2018 v 12:08 odesílatel Milan Spisar <notifications@github.com>
napsal:
