### ISSUE TITLE
Getting 400 bad request error

### ISSUE THREAD

**Issue by krunal131987** [csob/paymentgateway#4]
I am using this url for payment init
https://iapi.iplatebnibrana.csob.cz/api/v1/payment/init

my request is.
{"returnUrl":"https:\/\/www.print-pix.eu\/functions\/csob_return_payment\/","cart":[{"amount":6,"description":"PrintPix - photos printing","quantity":1,"name":"Order of photos"}],"payOperation":"payment","dttm":"20150602110415","currency":"USD","orderNo":"43","description":"PrintPix APP order 43","returnMethod":"POST","totalAmount":"6","closePayment":"true","merchantId":"A1050uj4XS","language":"EN","signature":"QTEwNTB1ajRYU3w0M3wyMDE1MDYwMjExMDQxNXxwYXltZW50fGNhcmR8NnxVU0R8dHJ1ZXxodHRw\nczovL3d3dy5wcmludC1waXguZXUvZnVuY3Rpb25zL2Nzb2JfcmV0dXJuX3BheW1lbnQvfFBPU1R8\nT3JkZXIgb2YgcGhvdG9zfDF8NnxQcmludFBpeCAtIHBob3RvcyBwcmludGluZ3xQcmludFBpeCBB\nUFAgb3JkZXIgNDN8RU4=\n","payMethod":"card"}

my message data string is, 
A1050uj4XS|43|20150602110415|payment|card|6|USD|true|https://www.print-pix.eu/functions/csob_return_payment/|POST|Order of photos|1|6|PrintPix - photos printing|PrintPix APP order 43|EN

please, tell me, is there any wrong in my request?

Thank you,
Krunal

**Comment by krunal131987** [comment]
is there any reference for generating signature in android?

**Comment by dmarek** [comment]
In java / android use

```
Signature instance = Signature.getInstance("SHA1withRSA");
instance.initSign(key);
instance.update(plainData.getBytes("UTF-8"));
byte[] signature = instance.sign();
return Base64.encodeBase64String(signature);
```

**Comment by krunal131987** [comment]
"key" whithin initSing function , is it private key?
it is, then how can i use private key in this function

I have this 2 files
1. rsa_A1050uj4XS.key
2. rsa_A1050uj4XS.pub

**Comment by dmarek** [comment]
Please checkout and inspect following example implementation
https://github.com/csob/paymentgateway/tree/master/eshop-integration/eAPI/v1/java/eAPI-v1-connector

this class contains crypto operations
https://github.com/csob/paymentgateway/blob/master/eshop-integration/eAPI/v1/java/eAPI-v1-connector/src/main/java/cz/monetplus/mips/eapi/v1/service/CryptoServiceImpl.java
