### ISSUE TITLE
Recurrent payment

### ISSUE THREAD

**Issue by ThomasMaterna** [csob/paymentgateway#40]
Dobrý den,

mohu se zeptat na možnost opakované platby v eAPI? V integračním prostředí lze v metodě payment/init nastavit parametr payOperation na recurrentPayment, ale na volání payment/recurrent je odpověd http status 405. Je možné tuto metodu používat, nebo je chyba v požadavku?  

Adresa volání:
https://iapi.iplatebnibrana.csob.cz/api/v1/payment/recurrent/

požadavek:
{"merchantId":"A1162IqFS8","origPayId":"4f95faf83abf488","dttm":"20150901073116","orderNo":5,"totalAmount":1000,"currency":"CZK","signature":"KiGNBSIRWZcWizRX91B33Xn4acCrcCiUsMH2iLGSZXB+ormrEHKfyPLW3/X93yl2f8dKc73VngbX0znu8huUQQ1Vni6zqD26lYz01QHi6HnYkd1FlFAoRu5k400Sjg8AUaGLpsSbY7wNStWiQsd6nFAfU6VsUOPsEnSIAga5mxrjAhilaR+fDRKFYEZL++paZpgJ0TwVlQGeXQQaC91uPGFXr6KA7A92W47+6ss66pjREdCNB1XhwT/DF1ETHZTxSgVQU4uycLeeM/Dt97OjWGPrp8E6fsSvRpBjXx9+2Ceq3UNRrpi1OhDYyRFYPyzmYslM9S6YaxTSjB9/iLDOEA=="}

odpověď:
payment/recurrent failed, reason: 405

Děkuji.

**Comment by dmarek** [comment]
Místo PUT použijte POST
