### ISSUE TITLE
Merchant does not accept this card

### ISSUE THREAD

**Issue by viktorzavadil** [csob/paymentgateway#400]
Dobrý den,

máme vytvořeného anonymního obchodníka a přišli jsme na to, že nelze platit s kartou vydanou v USA. Viz https://github.com/csob/paymentgateway/wiki/Testovac%C3%AD-karty karta **4543320001000205**. Je to ten samý případ jako s issue https://github.com/csob/paymentgateway/issues/397? Je potřeba pro obchodníka povolit platby pro karty vydané mimo ČR nebo banka vůbec takové platby nepovoluje?

Děkuji za rychlou reakci.

S pozdravem
Viktor Zavadil

![usa-card](https://user-images.githubusercontent.com/19145428/46189151-7f163680-c2ed-11e8-9ae2-cd6f3c45d230.png)

**Comment by viktorzavadil** [comment]
Prosím, urguji reakci, díky.

**Comment by Mspisar** [comment]
Dobrý den,

omlouvám se za delší dobu reakce. Anonymní ID v test. prostředí slouží pouze pro testy platební brány, kde **máte povoleny pouze testovací karty.** V produkci máte možnost rozšířit akceptované regiony žádostí na akceptacekaret@csob.cz - to Vám, ale nezaručí že daný prefix karty bude 100% fungovat vždy záleží na vydavatelské bance.

s pozdravem

Spisar

**Comment by viktorzavadil** [comment]
Dobře. Ale tohle je výsledek po zadání testovací karty, která je uvedená na vaší wiki.

**Comment by Mspisar** [comment]
Dobrý den,

v tomto případě je to v pořádku. Tato zkušební karta simuluje stav kdy máte daný region v nastavení platební brány zakázán.

s pozdravem

Spisar

**Comment by ratajskym** [comment]
@viktorzavadil Jste s odpovědí spokojen a můžeme toto issue uzavřít ?

**Comment by viktorzavadil** [comment]
@ratajskym Myslím, že by na wiki mělo být uvedeno, že platba touto kartou neprojde a měla by tam být, podle mého názoru, i karta vydaná mimo EU, která projde. Ale ano, střípky jsem si dal dohromady a už neprahnu po hlubším poznání :) Díky.
