### ISSUE TITLE
API returned HTTP code 400, which is not code 200. 

### ISSUE THREAD

**Issue by Nowis75** [csob/paymentgateway#401]
Dobrý den, neustále se nám nedaří integrovat platební bránu. Na testovacím prostředí funguje všechno perfektně, ale při přechodu na produkční nám hlásí: API returned HTTP code 400, which is not code 200. Probably wrong signature, check crypto keys.
Zkoušeli jsme několikrát přegenerovat klíče, vše překontrolovali, ale na produkčním prostředí pořád nic.
Děkuii za rychlou reakci. 
Merchant ID: M1E3CB1120

**Comment by Nowis75** [comment]
Tak nyní to hlásí: Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date

**Comment by mjanek** [comment]
Dobrý den,
s největší pravděpodobností jste si nevyměnili integrační klíče za produkční. Zkuste zkontrolovat, zda máte nastavený produkční veřejný klíč banky na mips_platebnibrana.csob.cz.pub

**Comment by mjanek** [comment]
Invalid paymentInit signature for M1E3CB1120 - zkontrolujte si:

1. Zda jste vygenerovaný klíč ze stránky https://platebnibrana.csob.cz/keygen/ odeslal do banky.
2. nebo zda jste si stáhl správný veřejný klíč banky na: https://github.com/csob/paymentgateway/tree/master/keys. (pro produkční verzi se jedná o: mips_platebnibrana.csob.cz.pub )
3. Popřípadě si můžete vygenerovat klíče znova a postup opakovat.
4. Pokud jste si jist, že jste vše udělal správně a problém přetrvává, může být chyba v PODPISU, vzorový příklad podpisu:
plain data: 'A1029DTmM7|12311456|20151020090740|payment|card|100|CZK|false|http://3ds.purelab.cz/produkce2/|POST|Shopping at ...|1|100|Lenovo ThinkPad Edge E540...|Shipping|1|0|PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|1234|CZ'

**Comment by Nowis75** [comment]
právě, že vše je tak, jak uvádíte, aby bylo. Pouze vyměním testovací klíče za produkční a nastane ona situace: Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date.
Již jsem vše nekolikrát přegeneroval.

**Comment by mjanek** [comment]
Vyzkoušejte metodu echo, tím zjistíme, zda máte dobré klíče, v případě že bude volání vpořádku, bude chyba někde jinde. https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#getpost-httpsapiplatebnibranacsobczapiv17echo-

**Comment by mjanek** [comment]
Vidím první úspěšnou transakci. Kde byla chyba ?

**Comment by Nowis75** [comment]
Chyba byla v bordelu v certifikátech :) Díky za pomoc.
Nyní řešíme u jiného zákazníka problém s tím, že se nemůžeme dostat do integračního prostředí, abychom potvrdili, že chceme přejít na prostředí produkční. Nefungují nám zaslané přístup: Merchant ID je M1MIPS4626 Můžete nám pomoci?

**Comment by RoForst** [comment]
Dobrý den,
o vygenerování nových přístupových údajů musíte kontaktovat banku a to na emailu akceptacekaret@csob.cz.
