### ISSUE TITLE
Transakce bila zamítnuta

### ISSUE THREAD

**Issue by MakingCG** [csob/paymentgateway#402]
Ahojte,

Mam mensi problem s napojenim a po hlbsej analyze som nenasiel riesenie a uz vobec neviem kde este hladat tak sa na Vas obraciam. Po zalozeni platby ma presmeruje na danu stranku banky no ihned sa zobrazi hlaska 'Transakce bila zamítnuta'. V odpovedi som dostal 'paymentStatus' 6 (platba zamietnuta) s 'resultMessage' Ok, cize to mi vela nepovie kde som mohol urobit chybu. Ak niekto pozna riesenie, budem vdacny, dakujem.

Zalozenie platby 1
<img width="939" alt="46296456-b4937c00-c59a-11e8-8889-43fa148ef10d" src="https://user-images.githubusercontent.com/17012967/46351632-1ebe2680-c658-11e8-92a5-767c98577467.png">

Zalozenie platby 2
<img width="911" alt="46296607-06d49d00-c59b-11e8-8f94-115b10b612b0" src="https://user-images.githubusercontent.com/17012967/46351640-254c9e00-c658-11e8-9f0c-bdd968ca6270.png">

Presmerovanie na platobnu branu
<img width="736" alt="46296498-c9700f80-c59a-11e8-9b08-beb3669c3b61" src="https://user-images.githubusercontent.com/17012967/46351658-28e02500-c658-11e8-9117-a012feb5653f.png">

Odpoved po presmerovani na stranku
<img width="376" alt="46296521-d4c33b00-c59a-11e8-97e6-512139bbf145" src="https://user-images.githubusercontent.com/17012967/46351665-2bdb1580-c658-11e8-98b9-5fd620e2dc42.png">

Diki moc.

Pouzita kniznica
https://github.com/slevomat/csob-gateway

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
Miroslav Janek

**Comment by dhozik** [comment]
Dobrý den,

zkontrolujte si prosím zadávané klíče. Veřejný klíč banky naleznete na GitHubu na adrese https://github.com/csob/paymentgateway/tree/master/keys .

Dále to vypadá, že název Vašeho Merchant ID neodpovídá názvu privátního klíče, ověřte, zda se jedná opravdu o vygenerovaný klíč pro tohle Merchant ID.

Zamítání transakcí je však v tom, že platbu zadáváte v EUR. Nyní máte vygenerované anonymní merchant ID, kde tato měna není povolena.

S pozdravem
David Hozík

**Comment by MakingCG** [comment]
Dakujem za odpoved,

problem bol teda s tou menou EUR, uz to ide. Dakujem pekne
