### ISSUE TITLE
Prilozeny php kod (priklad) nefunguje - no signature, error 400

### ISSUE THREAD

**Issue by pepetko007** [csob/paymentgateway#403]
Dobry den,
premyslim nad implementaci CSOB brany a tak jsem si chtel vyzkouset priklad, ktery mate prilozeny, ale nefunguje. Nevytvari signature (teda predpokladam, ze to je chyba).
Kde muze byt problem?
Dekuji

http://adaptermodulesmarket.com/pgw

**Comment by mrazekl** [comment]
Dobrý den,

v tomto vzorovém příkladu je použito anonymní MerchantID, které má určitou dobu platnosti, která již expirovala. Z tohoto důvodu je test neúspěšný.
Můžete si na stránce https://iplatebnibrana.csob.cz/keygen/ vygenerovat své anonymní ID + klíče a začít testovat.

**Comment by pepetko007** [comment]
Super, dekuji. To pomohlo. Jsem o krok dal. Aktualne mam hlasku
"payment/init failed, unable to verify signature", coz mi pripada jako neplatny public key "mips_iplatebnibrana.csob.cz.pub", ktery tam je. Je to tak? Jak to prosim vyresit?
Dekuji,
Peter Jarunek

**Comment by pepetko007** [comment]
OK, zakomentoval jsem ten kus kodu, kde se verifikuje odpoved a to mi ted jako priklad staci.

Mozna bych jen doporucil informaci o nutnosti generovani anonymniho merchantID, klicu, zaslani klicu do banky, upravy setup.php atd v jasnych krocich dopsat do readme.txt. Myslim, ze vam to ubere trochu prace v budoucnosti a bude to hned jasny vsem lidem, kteri chteji testovat.

Jako novacek jsem byl take lehce zmaten z popisu fungovani brany a nejak jsem se nedokazal orientovat. Pak jsem zjistil, ze mate uplne skvely popis celeho procesu, ale mate to linkem eAPI v1.7, coz implicitne generuje dojem referencni prirucky API v1.7, ne popisu celeho procesu i s vysvetlenim.

Prozatim ale dekuji za pomoc.
Peter Jarunek
