### ISSUE TITLE
Problém s 3D secure

### ISSUE THREAD

**Issue by landsman** [csob/paymentgateway#404]
Dobrý den,

zákazník se na nás obrátil, že po zadání karty mu nedorazí SMS 3D Secure kód.

Když se obrátil na svoji banku - Airbank, 
tak mu bylo sděleno, že zaslání požadavku o 3D secure inicializuje brána a musí být chyba někde na straně obchodníka / brány.

Nemám k tomu asi žádné logy a přemýšlím, jak toto řešit.
Vrací brána v tomto případě nějaký response, dá se to debugovat?

Díky

**Comment by mjanek** [comment]
Dobrý den, 
Váš požadavek jsme zaevidovali.
Máte nějaký záchytný bod? Abychom mohli něco prověřit, budeme potřebovat například id brány, payID, datum a čas transakce, kdy byla provedena tato neúspěšná transakce apod. 

Miroslav Janek

**Comment by landsman** [comment]
Dobrý den,

ID brány: ` M1MIPS0603`
Datum cca: `2018-10-10 12:08:31` (v db evidujeme jako počátek transakce)

Transakci jako takovou zde vůbec nevidím, což je hodně zvláští, čekal bych že budu vidět alespoň nějaký timeout.

**Comment by mjanek** [comment]
Dobrý den,
věděl byste částku, na kterou se transakce prováděla?  

M. Janek

**Comment by landsman** [comment]
Dobrý den,

jednalo se pravděpodobně o částku 399 Kč, či 1 Kč.

**Comment by mjanek** [comment]
Dobrý den,

vidím platbu ve 12:06  na částku 787,- a jedná se o opakovanou platbnu na klik. V případě platby Na klik dává klient svolení k provádění následných transakcí bez zadávání CVC a bez 3D-Secure autentizace. 

více info [ZDE] (https://github.com/csob/paymentgateway/wiki/Platba-Na-klik)

M. Janek

**Comment by mjanek** [comment]
Žádný takový požadavek na bránu v uvedený čas nepřišel. Ani v databázi ho nevidíme.

**Comment by landsman** [comment]
A máte možnost projít celý ten den na zamítnuté transakce z Airbank?

**Comment by mjanek** [comment]
Takovou možnost nemáme. 
Prověřil jsem vše co jsem mohl. Pokud chcete vědět podrobnější informace, napište přesné údaje o platbě (konkrétní payID) na akceptacekaret@csob.cz.

**Comment by landsman** [comment]
Tam trvá odpověď 5 dní, to musíme řešit nejlépe vlastní silou a obratem :/

Díky za snahu.
