### ISSUE TITLE
Problém s platbou

### ISSUE THREAD

**Issue by landsman** [csob/paymentgateway#405]
Dobrý den,

můžete mi prosím ověřit tuto platbu?

Brána: `M1MIPS0603`
Objednávka: `b31ec76a6884fDJ`

Zase vidím pouze `Obecné zamítnutí` a netuším co mám zákaznici poradit.
Bylo by možné dát více informací do služby POSMerchant, abych vás s tímto nemusel otravovat?

díky

**Comment by mrazekl** [comment]
Dobrý den,

tato transakce byla zamítnuta z důvodu, který uvádíte. Jedná se o obecné zamítnutí ze strany vydavatele banky - proč, to nenáme jak zjistit.  Zákaznici bych doporučil, aby se obrátila na svou banku.

**Comment by landsman** [comment]
OK
