### ISSUE TITLE
Platba nenalezena

### ISSUE THREAD

**Issue by floofa** [csob/paymentgateway#406]
Dobry den,

provadim platbu na testovacim prostredi. Platbu se na strane serveru podari vytvorit, ale nasledne po presmerovani na platebni branu vyskoci hlaska 'Platba nenalezena'. Testovani provadim z localhostu.

Muzete se prosim podivat, z jakeho duvodu k teto chybe dojde? Jedna se o Merchant ID 'M1MIPS4377'.

Dekuji.

**Comment by floofa** [comment]
Dobry den,

pro komunikaci s platebni branou pouzivam knihovnu, kterou doporucujete v dokumentaci (https://github.com/ondrakoupil/csob). Kdyz jsem koukal do kodu, tak se pozadavek sklada z techto hodnot:

merchantId
payId
dttm
signature

Tedy po inicializaci platby, ktera mi vrati tyto hodnoty:

[dttm] => 20181015083905 
[payId] => ff19328243b31DJ 
[resultCode] => 0 
[resultMessage] => OK 
[paymentStatus] => 1
[signature] => OrXlmzc0fDp+U262VkApIgGG1+rGDjFkzgbFsP80QKLQXUkWR5OE+XO+EeIaIQSGIM0OASszqu8HacdDAxgs2t/oeYbJ/N02+xg7lxefKp1IlqJBUw05TE7yLeyV7AAl8iVphWH6jed9+bC6CDujOtybloEkmGSgpTwVgxFfgb+9fjBNVeu9V01B9HolRlidfjPIr/SUaQCUUz8ZkQfHWVAR1tBVQkeWHC0zu00CQNEXiS/rC9lJOrdOtZPJRGhaOErl0FfmV0u85uOmkXmkiypQg3u2KHe6f8aR2W+3kJOLFkLzWKwZCh70gMBgePKf2fStUfL0A2Y+N0kdGyOP0g== 

presmerovavam nasledne na tuto url:

https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/process/M1MIPS4377/ff19328243b31DJ/20181015083800/aT6Wc6v1fC3uCUi9Vcbg%2FC6P2udjwZDO8ruF0PTJMA%2FvDbAiE8BLdHisvN24m5VEYglkdEcc6%2BVaPGvNLk7x7CkQ1vClFk0GNxlGDQU2PQmG%2B3Gc9YI%2FU4knaUsP0f9N6W%2BGswwV8os%2Bra3hWSQO%2BpWtJ4MoZtET12jIaks3CjFcQnFnmaasg%2BKSIPtVM7k2TnbNZvmSaWo20sKdVxIKb0UGWMjcCAWsXrnYpmQ3NO38Bn%2BWubdMMGUxcNqPpLyLDVttAq1GxN9f9YQ2DI9oYFTWUSJqolxcQ%2BY4QQX4p5GAvGH2E9b7kiFslS4qqEUNuOpCZ5xUZXLiJJYHHuINYA%3D%3D

kde signature je spocitan prave z hodnot merchantId, payId a ddtm.

Kde je tedy v danem postupu chyba?

Dekuji.

**Comment by Mspisar** [comment]
Dobrý den,

v případě že máte problém s PHP knihovnou kontaktujte tedy přímo autora jak je v popisu.

s pozdravem

Spisar

**Comment by floofa** [comment]
Dobry den,

dle meho nazoru je prave vse v poradku a odesilaji se udaje spravne dle vasi dokumentace. Dokazete mi tedy rict, jaky paramtetr se neposila nebo se posila chybne?

Dekuji.

**Comment by floofa** [comment]
Dobry den,

stale se mi nedari dostat pres uvedeny problem. Pri presmerovani na platebni branu vzdy vyskoci zprava 'Platba nenalezena'. Zkousel jsem i API od Slevomatu a take vlastni reseni, vzdy stejny vysledek.

Neni mozne z nejakeho logu vycist, v cem konkretne je problem?

Dekuji.

**Comment by Mspisar** [comment]
Dobrý den,

nezdá se mi složení požadavku na přesměrování. Proto doporučuji kontaktovat autora knihovny. 

naše **standardní** řešení je popsáno zde:

https://github.com/csob/paymentgateway/wiki/eAPI-v1.7

s pozdravem

Spisar

**Comment by floofa** [comment]
Dobry den,

stahl jsem si vasi testovaci implementaci - https://github.com/csob/paymentgateway/wiki/eAPI-v1.7.  Vysledek opet stejny, tedy dojde k zalozeni platby, ale po presmerovani na eshop opet hlaska 'Platba nenalezena'. Pokud to dela i ve vasi implementaci, strana bude asi jinde, nez v zasilanych parametrech.

Posilam vystup ze skriptu:

`preparing payment init data ...

preparing cart data:
[
    {
        "name": "Shopping at ...",
        "quantity": 1,
        "amount": 100,
        "description": "Lenovo ThinkPad Edge E540..."
    },
    {
        "name": "Shipping",
        "quantity": 1,
        "amount": 0,
        "description": "PPL"
    }
]

data to sign:
"M1MIPS4377|123456|20181021113733|payment|card|100|CZK|false|http://localhost/test/csob/gateway-return|POST|Shopping at ...|1|100|Lenovo ThinkPad Edge E540...|Shipping|1|0|PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|1234|CZ"

prepared payment/init request:
{
    "merchantId": "M1MIPS4377",
    "orderNo": "123456",
    "dttm": "20181021113733",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 100,
    "currency": "CZK",
    "closePayment": "false",
    "returnUrl": "http://localhost/test/csob/gateway-return",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 100,
            "description": "Lenovo ThinkPad Edge E540..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 0,
            "description": "PPL"
        }
    ],
    "description": "Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
    "merchantData": null,
    "language": "CZ",
    "customerId": "1234",
    "signature": "bhoWPXcWkXuMsfZ+OcwGDojVezX7Wm4zKtJjUUIycMlf7hESbxV9zcP9PJ/Y4CYlwES4XUnrCc9fmvaIBGI/jmKnBdrdQdWI0XvR7LQd79VzQZ7Ddy/JITYbmm1N/sV1bZSBHxxlTuzCzV0SdR12a6RaduLvUYHRgQhALS6kIH7wcYdOgBToRNeHmUBEFL3HjVpCA9CHqA3/OQ1zZSxyrTfioMRxOtisiuvrmIT9ybdwh2MpubflzBeMwHPX/0KNRGPPgRga0IxFlEkYfDP84mkAjrFwBV+Vvl3Lafu2J0xacM2FHNPUCiqt6o+C0ab58p/xxQRHuS6shfOU+2KdHA=="
}

processing payment/init request ...

payment/init result:
{"dttm":"20181021113846","signature":"A3KZrgYxsOqoV5n9OGu3P+Uw3Oiw67lbfvB4BRJit/3/5WlA+TOluCxwYIcDJW0EkWu8ODU9Y+pC57nGmDAoEaCmDJEaMa3qRIFknbI1MrTNjYxqEI22sfF+YcuCnxhxhZ3XUSTf6/nOg9QCLfkP6XjwJaUDJtHrv2a3crQ9rhwV2J6P+TUHMkT6rIlRlmtOurFInAid4MEjl0MQXMbNsi6sly+ReMjA0Btg8qYgXObQB0Ypsw3H58UYpZ6UwWz1m/aW52rILz98eK685VvXXWZ9sdJgnsxyE4epxkMA48OFrFo/HeRB+PBm8uUDnMRX4ImsWtP+8YvBvB9M9EVW3g==","payId":"3290700d4e9d6DJ","resultCode":0,"resultMessage":"OK","paymentStatus":1}`

**Comment by mjanek** [comment]
Dobrý den, 
problém bude dělat dle mého způsob, kterým komunikujete se serverem, změnte http na https a dejte vědět jestli to pomohlo. 
Miroslav Janek

**Comment by floofa** [comment]
Dobry den,

zmenil jsem na https, ale vysledek je stale stejny. Neni nejake omezeni pro testovani z loclhostu nebo neco takoveho?

Prikladam vystup ze skriptu:

`preparing payment init data ...

preparing cart data:
[
    {
        "name": "Shopping at ...",
        "quantity": 1,
        "amount": 100,
        "description": "Lenovo ThinkPad Edge E540..."
    },
    {
        "name": "Shipping",
        "quantity": 1,
        "amount": 0,
        "description": "PPL"
    }
]

data to sign:
"M1MIPS4377|123456|20181021174118|payment|card|100|CZK|false|https://localhost/test/csob/gateway-return|POST|Shopping at ...|1|100|Lenovo ThinkPad Edge E540...|Shipping|1|0|PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|1234|CZ"

prepared payment/init request:
{
    "merchantId": "M1MIPS4377",
    "orderNo": "123456",
    "dttm": "20181021174118",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 100,
    "currency": "CZK",
    "closePayment": "false",
    "returnUrl": "https://localhost/test/csob/gateway-return",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 100,
            "description": "Lenovo ThinkPad Edge E540..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 0,
            "description": "PPL"
        }
    ],
    "description": "Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
    "merchantData": null,
    "language": "CZ",
    "customerId": "1234",
    "signature": "A/67z7RHRLF41tTHL04n/46BHG1NwJ6+66gvBK60ZTqVpve+WyUQo3IJ0k2loDT2iUn7dVmvudiIV/PFi5NfINDHl5Y6t5wwK4v/XsRjRWn/nZcL+dqwdFggSdlibvTQGld7RpAxHAAzzeEV9rIIIH74cmfCt2EhvFB50CB9a02OHeugCJFJfPL2HnOo33RZt/yKlvxZqEzgTNB8xdovl7H/CR97SmTTD3lYPMKmNAf+T32RhJ+lcYoFvd8CmrcT+iBsYRMhYHseS8YBqxPXv/YxVUT7pM20PINy2otoQAz2EM4OpdABob8Q5gxKt98o5xJysJQKFWMFnnd0p7fNOg=="
}

processing payment/init request ...

payment/init result:
{"dttm":"20181021174232","signature":"uTNwSt3UDVizNqr4A8NVMtXu2K1aJCK5oAcNqAteYlqqi3/O/uFqRrbRXLfoiE3hyI1lV9VBQ75Kd8xZfXRiquDVqrrJtVbp922rjkExnrg0lzjRUElVufURk7+kmkBsBUlldzmH6huVjQEccdnFBM2CZKfZLA2gItqrkvn+2Lc+MyGYs1Lr5V3xrY3HQjssVg3EOf98QV57s+DbeovFg9O1vyzPh00KBcXETgZiQcQySpt72uwcyLJPmILu7Xtgz/9zyloqmIjFjYMokGZiJ9ovVF/CUpg5qxbzuOKF6xmkFJpZCQGR7YXgScfmcXrfc8K0nWvPnIRbvQqTAg3EiA==","payId":"5f07489a9a116DJ","resultCode":0,"resultMessage":"OK","paymentStatus":1}`

**Comment by ratajskym** [comment]
21.10.2018 vidím úspěšný skok na platební bránu. Podařilo se Vám tedy vyřešit problém a je tedy vše v pořádku ?

**Comment by floofa** [comment]
Nepovedlo, stale stejny problem. Po presmerovani na platebni branu se mi zobrazi 'Platba nenalezena'. Zkousel jsem nyni znovu a stale stejny problem. 

Inicializace platby probehne v poradku. PayId: ac0b1c8cf9d5eDJ.

Dale klikam na odkaz payment/process, ktery vede na tuto url:

https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/process/M1MIPS4377/ac0b1c8cf9d5eDJ/20181023103638/JKVJXpDmH2UGCXRXJwEInLNrJQuQjs9mMU9Us950gz6QW4ANVb%2FpH9n%2BOAIQnoYTsDGTEaOFwnqpPu9Y7FCXOF6LKZ3DPU3vtAxjhn7eXEy0VusTF%2Fa6rZ%2BoQ55y2irUb1AOFxFvcCFfchpp%2FMbDvNVNj9zb2PrRRusX%2BAoRkUIiEYAesFX7EutjYuzHZiNhtUyAMGkAvBvPwo2CuXGS15A7HQnjBgoh3ZfLTdPwVqq0taVfVkXf0xu9ZUa%2FFhm%2F%2F2sE67wRQTm36WuF5pE%2FDuhxZjtdAAlTxYYr7%2FW7mjaTCIr%2BRt7J1bkUuVi4XWiSIFbDxJzlxm8f4q12jSobNQ%3D%3D

Po presmerovani na platbeni branu vidim tuto url:

https://iplatebnibrana.csob.cz/pay/hayashi.cz/výroba/ea435b0f-46fa-4960-8500-05e9023be379/

A tam se zobrazi 'Platba nenalezena'.

**Comment by mjanek** [comment]
Dobrý den, 
ještě mě napadá, zda není problém se spárováním platby, protože zasíláte v každém requestu stejné číslo objednávky (VS) - toto číslo musí být unikátní viz.: https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#jednotliv%C3%A9-kroky-platebn%C3%ADho-procesu

![obrazek](https://user-images.githubusercontent.com/22815840/47457839-7b84ab00-d7d8-11e8-9ed6-583a1f1b7665.png)

**Comment by floofa** [comment]
Dobry den,
provedl jsem testovaci platbu s jinym cislem objednavky, ale vysledek stale stejny, opet po presmerovani zobrazena stranka 'platbe nenalezena'.

Chtel bych se zeptat, nemuze pusobit problem, ze v nastaveni platebni brany je v url diakritika? Nemuze to zlobit kvuli tomu z nejakeho duvodu?

**Comment by mjanek** [comment]
Dobrý den, 
určitě přečtěte ještě k čemu slouží parametr "merchantData". Ve vašem requestu vidím, že tam máte hodnotu "null".

],
  "description":"Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
  "merchantData":"some-base64-encoded-merchant-data",
  "language":"CZ",
  "signature":"base64-encoded-signature-of-payment-request"
}'

zkuste upravit request podle: https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#-post-httpsapiplatebnibranacsobczapiv17paymentinit-

**Comment by floofa** [comment]
Dobry den,

ano, to je skutecne ten problem. Nyni uz se platebni brana zobrazi.

Dekuji za pomoc.

PS: tato chyba je primo v kodu vaseho repozitare, ktery jsem pouzil k testovani - https://github.com/csob/paymentgateway/blob/master/Integration%20Examples/eAPI%20v1.7/php/init-result.php#L27

**Comment by mjanek** [comment]
Tak to mě těší. 

Nechám to zkontrolovat a pošlu informaci dále. 

Můžu tedy issue uzavřít?

**Comment by ratajskym** [comment]
@floofa Merchant data by v tom nemělo hrát roli, jedná se o nepovinnou položku.

Problém bude ve Vaší url (která mi ale v tuto chvíli přijde již v pořádku, nedošlo náhodou k nějaké změně ?)

Tohle je url, na kterou Vás to přesměrovávalo
https://iplatebnibrana.csob.cz/pay/hayashi.cz/výroba/ea435b0f-46fa-4960-8500-05e9023be379/

Logika parsování url je následující
https://iplatebnibrana.csob.cz/pay/url-eshopu/id-objednavky-na/

tzn ve Vašem případě se jako id objednávky bralo 'výroba' a toto id (logicky) neexistuje
