### ISSUE TITLE
Safari produkce Content-length: 0

### ISSUE THREAD

**Issue by PrucmaFactorio** [csob/paymentgateway#408]
Platební brána pro ostrý provoz donutí Safari (verze 11.1.1), při návratu do obchodu, udělat request s headrem Content-length: 0 viz první obrázek. Je zajímavé, že brána pro testování funguje v pořádku viz druhý obrázek.
![csob_produkce](https://user-images.githubusercontent.com/32953123/47413034-7e968180-d76d-11e8-8edd-7c2c29b525c3.png)
![csob_testovaci](https://user-images.githubusercontent.com/32953123/47413035-7f2f1800-d76d-11e8-9e36-196b06dc273d.png)

**Comment by ratajskym** [comment]
Celé se mi to nějak nezdá. V tom Vašem screenshotu je vidět HTTP response 500 - internal server error. Takhle se Vám to chová při každé transakci, nebo to byla nějaká shoda náhod ?

**Comment by PrucmaFactorio** [comment]
Header Content-length: 0 je invalidní hodnota pro takový request, jelikož má data v body [zde](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length). Server díky tomu odpovída 500. Pokud je to v Chromu nebo v testovací bráně (kde se správně posílá header Content-length), tak vše probíhá v pořádku.

**Comment by PrucmaFactorio** [comment]
Dobrý den, je nějaký vývoj v této věci?

**Comment by janbrasna** [comment]
Navrat do obchodu obstarava prohlizec klienta, via formular ktery mu brana predvyplni k odeslani a posle. Takze je to spise o konfiguraci UA nebo site daneho uzivatele:/

Overte si, ze za to nemuze proxy po ceste od klienta/useragenta posilajici ten request. Muj odhad je, ze Safari neposle `Content-Length` hlavicku, a dana proxy (`"Via: 1.1 vegur"`) si ji domysli jako prazdna == 0.
