### ISSUE TITLE
Přechod z GpWebpay na CSOB

### ISSUE THREAD

**Issue by gobbl3r** [csob/paymentgateway#41]
Dobrý den,

1) vygeneroval jsem nové certifikáty prosřednictvím https://platebnibrana.csob.cz/keygen/
2) puvodní volaná url byla https://3dsecure.gpwebpay.com/csob/order.do?OPERATION=CREATE_ORDER&MERCHANTNUMBER=....
3) nová url po dokončení objednávky je https://platebnibrana.csob.cz/pay/entry/merchant?OPERATION=CREATE_ORDER&MERCHANTNUMBER=
4) zákazník je automaticky ihned přesměrován na https://platebnibrana.csob.cz/pay/merchant-error.html
5) zobrazená chyba je : 

Platba nemůže být provedena

Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.
6) poprosím o informaci, zda se musí nějak měnit tvar url, napr názvy GETových parametru a podobně

S pozdravem
David Kuna

**Comment by ratajskym** [comment]
Dobrý den, 

bez detailnější informace nejsme schopni Vaši situaci analyzovat. Pošlete prosím na adresu platebnibrana@csob.cz své merchant id s odkazem na toto issue.

Děkuji

**Comment by gobbl3r** [comment]
Ďekuji za infomaci, email je odeslán i s časem vytvoření objednávek.

**Comment by ratajskym** [comment]
Dobrý den, 

doplním postup k bodu číslo 1. Vzhledem k Vámi uvedené url tedy řešíme produkční prostředí

1) vygeneroval jsem nové certifikáty prosřednictvím https://platebnibrana.csob.cz/keygen/
- privátní klíč uložíte k sobě
- veřejnou část odešlete tlačítkem "odeslat do banky" 
- přijde Vám emailem jednorázový kód
- potvrdíte v aplikaci PosMerchant

**Comment by gobbl3r** [comment]
Dobrý den,

ďěkuji za informaci, posunuli jsme implementaci ješte do testovacího režimu. Aktuálně tedy pracujeme s bránou https://iplatebnibrana.csob.cz/pay/entry/merchant. Předpokládam, že je nutno vykonat potvrzení v https://iposman.iplatebnibrana.csob.cz/posmerchant . Po přihlášení ale nemužu najít input na jednorázový kód. Výše popsaný problém totiž přetrváva i v testovacím prostředí.

S pozdravem
David Kina

**Comment by ratajskym** [comment]
Na testovacím prostředí jsou klíče schválené automaticky. Zmiňované potvrzování se týká pouze produkčního prostředí.

**Comment by gobbl3r** [comment]
Problém tedy přetrváva:

1) vygeneroval jsem nové certifikáty 
2) puvodní volaná url byla https://3dsecure.gpwebpay.com/csob/order.do?OPERATION=CREATE_ORDER&MERCHANTNUMBER=....
3) nová url po dokončení objednávky je https://iplatebnibrana.csob.cz/pay/entry/merchant?OPERATION=CREATE_ORDER&MERCHANTNUMBER=
4) zákazník je automaticky ihned přesměrován na https://iplatebnibrana.csob.cz/pay/merchant-error.html
5) zobrazená chyba je :

Platba nemůže být provedena

Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.
6) poprosím o informaci, zda se musí nějak měnit tvar url, napr názvy GETových parametru a podobně

7) Email na platebnibrana@csob.cz  sme zaslali už včera

S pozdravem
David Kuna

**Comment by ratajskym** [comment]
add 1 - když jste vygeneroval nové klíče, stiskl jste tlačítko "odeslat do banky" ?

**Comment by gobbl3r** [comment]
Nejsem si jisty, každopádně tu se píše, že není nutno klíč do banky odesílat v testovacím prostředí - https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

**Comment by ratajskym** [comment]
Jak na testovacím tak na produkčním prostředí je potřeba vygenerovaný klíč odeslat do banky, aby se uložil do databáze. 

Na testovacím prostředí není potřeba tento klíč potvrzovat přes aplikaci Posmerchant, klíč je automaticky schválen

Na produkčním prostředí je potřeba tento klíč potvrdit přes aplikaci Posmerchant pomocí OTP, které Vám přijde mailem.

**Comment by gobbl3r** [comment]
1. Cely proces jsme tedy projeli začátku 
 a) vygenerovani klicu pro testovaci prostredi na https://iplatebnibrana.csob.cz/keygen/
 b) odeslani verejneho klice do banky prostrednictvim tlacitka "Odeslat verejny klic do banky"
2. Problem pretrvava 
 - po dokonceni objednavky a pokuse o zaplaceni je uzivatel presmerovan na https://iplatebnibrana.csob.cz/pay/merchant-error.html
-----------------------------------------------------------------------------
1. Tento stav se tedy nemeni jiz par dni
2. Odpoved z platebnibrana@csob.cz jsme neobdrzeli
3. Na strane poskytovatele platebni brany neexistuji zadne logy s jasnym popisem chyby pri neuspesnem pokusu o zaplaceni?
4. Tento problem by jsme dnes radi konecne doresili


Dekuji

**Comment by ratajskym** [comment]
V logu vidím informaci o nevalidním podpisu
- můžeme rozdílně skládat podpis (i když tohle je málo pravděpodobné)
- ve skriptu používáte jiný privátní klíč, než který odpovídá veřejnému klíči, který jste odeslal do banky

add 3) Do dnešního dne jste neměl vygenerované nebo potvrzené klíče. Dnes je stav jiný
add 4) Mám pocit, že se Vám věnuji poměrně aktivně
add 5) Logy na straně brány existují, proto jsem schopen Vám říkat co máte špatně
add 6) Věřte mi, že bych Váš problém taky rád uzavřel.

**Comment by gobbl3r** [comment]
Vím, že se nám věnujete aktivně, děkuji. Pár dní by jsme si mohli ušetřit kdyby návody byli napsané přesně krok za kromem ve stylu očíslovaného postupu. 

+ Neuvažovali jste nad nějakým rozhraním s přístupem k logum? Napr podobně to má Agmo-Comgate kde je možné si po přihlášení do aplikace prohlédnout logy úspěšných/neúspěšných plateb. Díky tomu odpadne velká část komunikace s podporou.

**Comment by ratajskym** [comment]
Děkuji za podnět. Nad něčím takovým v tuto chvíli neuvažujeme. Implementace obchodníků probíhá, až na vyjímky, plynule a bez problémů

**Comment by gobbl3r** [comment]
Dobrý den,

aktuálně máme další problém - testovací prostředí iplatba nechce akceptovat platební kartu při pokusu o zaplacení ze Slovenska. Zobrazená hláška je "Vaša platba bola zamietnutá vydavateľom karty. Použite prosím iná kartu..." Karta je v pořádku, již byla využívaná při platbě online.

S pozdravem

**Comment by ratajskym** [comment]
Můžete mi poslat id objednávky nebo čas transakce, abych mohl Vaši transakci dohledat ?

**Comment by gobbl3r** [comment]
Dekuji za reakci, jiz se mi ozvali i z podpora@csob.cz s vysvetlenim. V pripade problemu jeste napisu,
