### ISSUE TITLE
předautorizace platební karty

### ISSUE THREAD

**Issue by landsman** [csob/paymentgateway#410]
Dobrý den,

bylo by prosím možné přidat tuto funkcionalitu do Vaší platební brány?
Rád bych měl možnost zablokovat částku na například 7 dní a po tomto období peníze uvolnit.

děkuji

**Comment by zdenasamkova** [comment]
Dobrý den, pan Landsman
předpokládala jsem, že blokace fin. částek na několik dní je jíž součástí
platební brány. Ale asi je to třeba vyzkoušet.
Můžeme to vyskoušet.
zs


st 21. 11. 2018 v 14:04 odesílatel Michal Landsman <notifications@github.com>
napsal:

**Comment by landsman** [comment]
@zdenasamkova I s možností blokaci zrušit, nastavit si libovolné období? Je k tomu nějaká dokumentace prosím?

**Comment by mrazekl** [comment]
Dobrý den,

na platební bráně je tato "předautorizace" běžná. Stačí, aby při založení objednávky měl prametr hodnotu closePayment:false a po úspěšné autorizaci se objednávka neodesílá do zaúčtování. Platba je ve stavu potvrzena a prostředky jsou blokovány. Pokud do 7 dnů nedojde k uzavření(payment/close) nebo reverzování(payment/reverse), prostředky na kartě plátce se automaticky uvolní. Navíc od verze eAPI v1.5 je možné zaúčtovat na nižší částku, než byla původně platba autorizována.

**Comment by mrazekl** [comment]
@zdenasamkova  
Dokumentace je dostupná zde, kde jsou popsány stavy, kterých můžou transakce během celého procesu nabýt a jejich vysvětlení:
https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#%C5%BDivotn%C3%AD-cyklus-transakce-
Doba expirace je nastavena automaticky na 7 dní, během které však můžete peníze odblokovat dříve(payment/reverse) a nebo dříve zaúčtovat(payment/close).

**Comment by landsman** [comment]
@mrazekl skvěle, je možné dobu 7 dní prodloužit například na 14 pomocí parametru? Příkladem je třeba kauce na výpujčku auta na 14 dní, pak bychom chargnuli třeba pouze 1000 Kč za cenu služby.

**Comment by mrazekl** [comment]
@landsman 
Nastavená doba je pevně daná pro všechny obchodníky a je neměnná. Ve Vašem případě můžete po zaúčtování využít částečný refund(payment/refund), kdy jde vracet prostředky po menších částkách až do nuly.

**Comment by landsman** [comment]
OK, teoreticky lze zadat refund a ihned navázat další transakci, jakožto prodloužení? Jaká je tam prodleva?

**Comment by mrazekl** [comment]
Co popisujete, není prodloužení. Musela by se v rámci platební brány uskutečnit nová objednávka pro stejného klienta. Požadavky jsou vyřizovány okamžitě po dokončení. Jen dodám pro upřesnění:
Reverzal je odvolání nezaúčtované transakce.
Refund/částečný refund je navrácení prostředků pro zaúčtované transakce.

**Comment by landsman** [comment]
Ano, tomu samozřejmě rozumím.

Ptám se na prodlevu mezi: Reverzal a novou objednávkou, aby se nestalo, že klientovi zablokuji třeba 2x tu samou částku nebo klient stihne s čáskou po Reverzal manipulovat a nebude dostatečný disponibilní zůstatek na kartě.

Počet předautorizací * částka, za celý měsíc, se nesčítá do limitu na kartě, správně?

**Comment by mrazekl** [comment]
Po technické stránce jsou tyto operace vyřizovány okamžitě a odesílány na patřičné bankovní oddělení. Jaké jsou reálné doby při zaúčtování/odblokování je otázkou bankovního sektoru, nikoliv platební brány.

**Comment by landsman** [comment]
ok, vyzkouším si to tedy..
