### ISSUE TITLE
customerId - nezapamatovani karty pro dalsi platbu

### ISSUE THREAD

**Issue by forker000** [csob/paymentgateway#412]
Dobrý den, chci realizovat platby se zapamatováním čísla karty (ať uživatel nemusí na platební bráně znovu popisovat kartu), nastavil jsem proto v payment/init customerId, ale při další platbě nevidím uloženou kartu z předešlé platby. Je možné, že je třeba nastavit něco z vaší strany? na testovacím prostředí mi následně customer/info vrací 810 Customer found, no saved card(s)

**Comment by dhozik** [comment]
Dobrý den,

Váš požadavek byl zaevidován pod TSGSMIPS-7529 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem
David Hozík

**Comment by dhozik** [comment]
Dobrý den,
prosím Vás ještě o ID brány, na které platbu provádíte, a příklad platby.

**Comment by mrazekl** [comment]
Dobrý den,

pokud zkoušíte s ID brány M1MIPS4760, tak bohužel nemáte povolenou možnost uložení karty v nastavení obchodníka. Pro povelení kontaktujte prosím akceptacekaret@csob.cz
