### ISSUE TITLE
Platba přes platební bránu selžen na payment/init, resolved code 400

### ISSUE THREAD

**Issue by Fragous** [csob/paymentgateway#413]
Dobrý den,
dle systému je platebá brána aktivní, ale neadří se nemám realizovat jakoukoliv transakci.
Platba se zasekne na payment/init, resolved code 400.

Máme nahrány správné klíče jak public, tak private.

Netušíte, kdy by mohla být chyba?

ID Brány: M1MIPS4838

**Comment by Madla** [comment]
Dobrý den,

možná jsem udělal nějaký postup s daným problémem ... zaměnil jsem API URL z https://iapi.iplatebnibrana.csob.cz/api/v1.7 => https://api.platebnibrana.csob.cz/api/v1.7 a už mi brána začla vracet jiný kód "chyba validace klíčů". 

payment/init result:
{"dttm":"20181204161952","signature":"{SOME SIGNATURE}","payId":"12eaeb2b4cbc9DL","resultCode":0,"resultMessage":"OK","paymentStatus":1}
payment/init failed, unable to verify signature

Nové klíče jsme vygenerovali na této stránce https://platebnibrana.csob.cz/keygen/ a zadali aktivační kód na adrese https://posman.csob.cz/posmerchant/ 

"Požadavek na zavedení klíče platební brány: M1MIPS4838 
Nemáte žádný nový požadavek na zavedení klíče"

Netušíte, kde by mohla být chyba?

Děkujeme za pomoc

**Comment by mrazekl** [comment]
Dobrý den,

postup který popisujete je správně. Na platební bráně již vidím požadavky, ale chyba bude v podpisu. Zkontrolujte ještě verzi veřejného klíče banky, který používáte, jelikož pro produkční prostředí je potřeba použít mips_platebnibrana.csob.cz.pub/cer

**Comment by Madla** [comment]
Dobrý den,

děkuji za rychlou reakci. 

Aktuální nastevení platební brány je tohle:
//$cfg['csob'][0]['publicKey'] = "mips_iplatebnibrana.csob.cz.pub"; 
$cfg['csob'][0]['publicKey'] = "rsa_M1MIPS4838.pub"; 
$cfg['csob'][0]['merchantId'] = "M1MIPS4838";
$cfg['csob'][0]['privateKey'] = "rsa_M1MIPS4838.key";

Já jsem myslel, že pro publicKey je nutné použít nově vygenerovaný klíč rsa_*.pub. Mohl bych Vás požádat o pomoc, jakým způsobem vygenerovat mips klič?

Děkuji

**Comment by Madla** [comment]
Dobrý den, 

vyřešeno, soubor jsem našel na GITu
