### ISSUE TITLE
Po provedení testovacích plateb není možné se přihlásit do POS - WooCommerce

### ISSUE THREAD

**Issue by Musilda** [csob/paymentgateway#414]
Nainstaloval jsem plugin, vygeneroval klíče a provedl platby. Přesto se nemůžeme přihlásit do POS a na info lince nám tvrdí, že jsme neudělali všechny platby. Id obchodníka M1MIPS4760

Díky za pomoc.

**Comment by RoForst** [comment]
Dobrý den,

pokud se snažíte přejít do produkčního prostředí musíte provést validaci v implementačním prostředí, k úspěšné validaci vám chybí udělat jedna testovací Reverzovaná transakce, pokud tuhle funkcionalitu nebudete na Vašem webu využívat musíte napsat email na akceptacekaret@csob.cz o překlopení do produkčního prostředí s tím že reverzované transakce nebudete používat. 

S pozdravem
Robin Forst

**Comment by mrazekl** [comment]
Z Woocommerce reverzal nevyvoláte, v tomto případě budete i v produkčním prostředí reverzovat/refundovat transakce přes PosMerchant. Doporučuji provést ještě autorizovanou transakci pro dosažení transakce ve stavu "posláno k zaúčtování" a obrátit se s žádostí o aktivaci do produkčního prostředí na akceptacekaret@csob.cz jak popisuje kolega Forst výše. V žádosti uveďte i problémy s přihlášením do PosMerchant.

**Comment by Musilda** [comment]
Nejsem si jist, zda rozumím. V eshopu jsem provedl jednu úspěšnou platbu, jednu platbu zrušenou a jednu platbu s vypršením platnosti. A tu refundaci. Je třeba ještě něco? 
Děkuji za váš čas, ale potřebuji pochopit proces, protože se na mne občas obrací zákazníci s požadavkem na implementaci.

**Comment by mrazekl** [comment]
Pokusím se to objasnit. Reverzal jde realizovat dvěma způsoby - přes APi rozhraní pomocí payment/reverse a nebo manuálně přes prostředí PosMerchant, jelikož ne včechny způsoby rešení obchodníků reverzal podporují, což je i Váš případ s Woocommerce. 
Dále je vyžadována transakce ve stavu "Autorizace potvrzena/Posláno k zaúčtování" u které je problematické to, že tyto transakce po půlnoci nabudou stavu "Zaúčtováno". 
A jelikož se do Posmerchant nepřihlásíte pro provedení reverzalu  a poslední autorizovanou transakci máte ze 4.12(dnes už ve stavu "zaúčtováno"), máte splněny pouze 2 zrušené/expirované transakce, což jste se dozvěděl i na infolince.
Z tohoto důvodu není možné zažádat o aktivaci do produkčního systému přes standartní automatizovaný systém a obrátit se přímo na útvar banky - aakceptacekaret@csob.cz.
Žádné další testovací transakce již z Vaší strany nejsou potřeba.

**Comment by Musilda** [comment]
Dobrý den, 
ještě prosím ne, nemám od klienta potvrzeno, že se jim to podařilo na ČSOB vyřídit.

**Comment by mrazekl** [comment]
Mezi těmito pojmy je drobný rozdíl:
Reverse(reverzal) - je odvolání **nezaúčtované ** transakce a zrušení blokace prostředků na účtu záakazníka
Refund  - je vrácení prostředků u již **zaúčtované** transakce

**Comment by Musilda** [comment]
Děkuji, vyřešeno.

**Comment by Musilda** [comment]
Tak nevyřešeno. 

Nenalezena transakce se stavem: Autorizace potvrzena/Posláno k zaúčtování
Musíte udělat alespoň jednu autorizovanou nezaúčtovanou transakci
Nenalezena transakce se stavem: Reverzováno
Musíte udělat alespoň jeden reverzal.

Přestože jsme požádali o zrušení reverzalu a o zaúčtované transakci jste říkal, že již dělat nemusíme

**Comment by Musilda** [comment]
Tak ještě mám problém s produkčními klíči. 
Vygeneroval jsem klíče, veřejný jsem odeslal a povrdil v merchanut kódem. 
Nově vygenerované klíče jsem vložil do složky na webu a změnil jejich název v nastavení pluginu. 
P5esto mi to stále hlásí, že se nepodařilo ověřit podpis.

**Comment by ratajskym** [comment]
Dobrý den, pokud se nepodařilo ověřit podpis na straně eshopu, tak to vypadá, že jste nevyměnil veřejný klíč platební brány. Pro testovací a produkční prostředí se tento klíč liší.

**Comment by Musilda** [comment]
Ověřoval jsem to, kód klíče v POS i ten co je na eshopu jsou stejné.

**Comment by ratajskym** [comment]
Špatný podpis === špatné klíče

Pustíte mě na vaše FTP abych se na to podíval ? Login samozřejmě mailem
nebo sms

ne 16. pro 2018 18:52 odesílatel Musilek Vladislav <notifications@github.com>
napsal:

**Comment by Musilda** [comment]
Dobrý den, 
mohu poprosit o emailový kontakt? Nejsem schopen s tím hnout, veřejný klíč je zavedený a stejný je i na FTP.

**Comment by mrazekl** [comment]
Zašlete na email servis@monetplus.cz
