### ISSUE TITLE
Spatny navratovy kod PaymentStatus po operaci Refund

### ISSUE THREAD

**Issue by pepetko007** [csob/paymentgateway#415]
Dobry den,

pri testovani jsem si vsiml, ze po provedeni operace Refund vraci brana PaymentStatus = 8. Mela by vracet 9 nebo 10. Po nasledem status checku vraci 10, coz je OK, ale to by melo prijit uz v odpovedi na refund.

S pozdravem,
PJ

**Comment by Mspisar** [comment]
Dobrý den,
Váš požadavek jsme zaevidovali a předali k prověření. O výsledku budete informován odpovědným kolegou. 
s pozdravem
Spisar

**Comment by mrazekl** [comment]
Dobrý den,

tohle chování je naprosto v souladu s oficiální dokumentaci, která je definovaná na githubu:
"Zpracování u této operace je asynchronní, parametr paymentStatus v návratových hodnotách proto obsahuje aktuální stav platebního požadavku (Platba zúčtována), stav platebního požadavku je možné sledovat přes payment/status."
Více zde: https://github.com/csob/paymentgateway/wiki/eAPI-1.6#puthttpsapiplatebnibranacsobczapiv16paymentrefund-
