### ISSUE TITLE
Zapamätaná karta v chrome sa použije s nesprávnym mesiacom expirácie

### ISSUE THREAD

**Issue by FreHu** [csob/paymentgateway#416]
Zdravím,

narážam už dlhšie na pomerne otravné chovanie, kde mám v chrome* zapamätanú kartu s expiráciou napr. 09/21, no pri použití funkcie predvyplnenia sa mi vyplní 10/21. Dialo sa mi to aj s predošlou kartou. Tipol by som si, že posunutie je chyba spojená s neintuitívnym indexovaním mesiacov od 0 v javascripte.

*netestoval som prehliadače iné než chrome

S pozdravom,
Frederik

**Comment by ozaoral** [comment]
Dobré odpoledne, díky moc za info, otestováno a děje se mi to taky. Opravíme.

Díky!
OZ

**Comment by janbrasna** [comment]
To byl par let zpatky potvrzeny bug v Chromu:

- https://bugs.chromium.org/p/chromium/issues/detail?id=587640
- https://bugs.chromium.org/p/chromium/issues/detail?id=590048
- https://codereview.chromium.org/1753463002
- https://codereview.chromium.org/1699993002

Opraveny byl kolem verze 50.0.x, nicmene to vypada ze nyni se zmenami v Autofill_Sync od nejakych verzi cca 68.0.x se to objevilo zpatky jako regrese 🤦‍♂️

**Comment by janbrasna** [comment]
@FreHu Uz je na to Chrome chovani nasazeny workaround, az budete mit pocit ze se to prestalo dit, muzete zavrit. Diky za nahlaseni!

**Comment by FreHu** [comment]
Dnes som si všimol, že to funguje správne. Vďaka!
