### ISSUE TITLE
Problém s voláním reverse

### ISSUE THREAD

**Issue by siccous** [csob/paymentgateway#417]
Dobrý den,
implementuji bránu pomocí API v1.6 do Magento 2.

Narazil jsem na problím s implementací volání reverse.

Posílám následující data:

merchantId: M1MIPS5042
payId: 4c282fcf05686EA
dttm: 20190104164549

A brána mi vrátí HTTP result code 406, ostatní volání echo, init, process, status fungují v pořádku.

Můžete mi prosím poradit, co dělám špatně?

Díky moc

**Comment by siccous** [comment]
Vyzkoušel jsem i s verzí 1.7 a chování je stejné.

**Comment by Mspisar** [comment]
Dobrý den,
Váš požadavek jsme zaevidovali a již je v řešení o dalším postupu budete informován.
s pozdravem
Spisar

**Comment by mrazekl** [comment]
Dobrý den,

jaký typ metody pro toto volání používáte? Pro změnu stavu transakce je určena metoda PUT, nikoli GET nebo POST, které jsou podporovány v ostatních typech volání, které Vám prochází.

**Comment by siccous** [comment]
Chyba byla na mé straně v kódu.

Díky moc za pomoc.
