### ISSUE TITLE
Implementace

### ISSUE THREAD

**Issue by manestis** [csob/paymentgateway#418]
Pořídili jsme si platební bránu ČSOB, ale bohužel se nám ji nepodařilo implementovat do woooommerce. 
Postupoval jsem dle tohoto návodu: https://github.com/csob/paymentgateway/tree/master/WooCommerce%20Plugin 
a taky https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#postup-integrace-kl%C3%AD%C4%8De-a-kde-je-vz%C3%ADt

V tom prvním návodu verze s api v.1.6.

Ani v jednom případě se mi brána na e-shopu neukáže. Plugin jsem nahrál přes FTP manažera, vložil jsem do něj vygenerované klíče, tak jak je popsáno v těch návodech, provedl jsem taky nastavení přímo v administraci woocommerce (WooCommerce -> Nastavení -> Pokladna -> WC_Monet_Payment_Gateway).

Při nákupu, (zvolení způsobu platby kartou) se mi vůbec neukáže rozhraní platební brány. Vyjede mi pouze stránka s rekapitulaci (malé 4 sloupečky, info o produktu ceně, dopravy a způsobu platby).
Navíc se taky nemohu dostat do POS Merchant na adrese: https://iposman.iplatebnibrana.csob.cz/posmerchant  . Nevím jaké tam zadat přístupy - uživatelské jméno a heslo.
Potřebuji udělat ty testovací transakce, abych mohl provést validaci a my mohli posléze přejít do produkčního prostředí.

Potřeboval bych nějaký srozumitelný, aktualizovaný návod jak implementovat platební bránu.

Děkuji

S pozdravem
Michal Anestis

**Comment by mrazekl** [comment]
Dobrý den,

postupujme od začátku. Vidíte ve woocommerce -> nastavení -> pokladna  záložku "ČSOB Platební brána" ?
![obrazek](https://user-images.githubusercontent.com/21953556/51027332-dc7a7e80-1590-11e9-9d27-077882eaf52e.png)

Pro přihlášení do POS merchant použijte své IČO jako uživatelské jméno a heslo jste měl obdržet formou sms. Pokud neznáte heslo, obraťte se na akceptacekaret@csob.cz pro opětovné zaslání.

**Comment by manestis** [comment]
Dobrý den, tak jsem zaslal požadavek na akceptacekaret@csob.cz, a přišlo mi to heslo v SMS. Nejde se tam, ale dostat. E-mailem mi přišlo, že se tam dostanu až následující pracovní den. V tom woocommerce tu záložku vidím. Dále mě to vybídne vyplnit ID, adresu brány a klíče.

**Comment by mrazekl** [comment]
Klíče je nutné si vygenerovat(pokud jste tak již neučinil) zde: https://iplatebnibrana.csob.cz/keygen/
a nahrát do patřičného adresáře(monetWebpay/keys)
Dále je nutné stáhnout si integrační veřejný klíč banky zde: https://github.com/csob/paymentgateway
přes odkaz "Clone or Download -> downloadZIP" - soubor mips_iplatebnibrana.csob.cz.pub
Ve Woocommerce je nutné vyplnit následující položky, podle následujícího vzoru:
![obrazek](https://user-images.githubusercontent.com/21953556/51044401-4f035280-15c1-11e9-8600-35ec31236904.png)
Dále je pro správnou funkčnost potřeba vyplnit pole s názvem první a druhé položky košíku.

**Comment by manestis** [comment]
Dobrý večer
Tak se mi tenhle krok provedl. Potřeboval bych teď provést ty testovací transakce a potvrdit je validací v testovacím prostředí aplikace POS Merchant. Do POS Merchant se už také normálně dostanu.

Podle https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD jsem provedl testovací transakce - úspěšně autorizovanou, uživatelem zrušenou platbu a reverzovanou platbu. Transakce vidím ve výpise v POS MERCHANT. 

Jak provést ty testy autorizace (echo post, echo get) ? 
Co znamenají všechny ty kroky kromě kroku 2 ?

**1 provést inicializaci platby (payment/init) a následné přesměrování na platební bránu (payment/process)**
2 na platební bráně zrušit platbu kliknutím na odkaz "Zrušit platbu a návrat zpět do e-shopu"
**3 zkontrolovat response code (200 OK)**
**4 ověřit podpis odpovědi (pomocí public klíče platební brány pro integrační prostředí)**
**5 ve vráceném JSON response zkontrolovat resultCode (0), dále paymentStatus (3)**

Následně bych měl ty ty testovací transakce potvrdit validací. Rád bych taky trochu pozměnil design brány (logo, barva..).

Chtěl bych také vyzkoušet resp. aktivovat iFrame (otevřené okno bez přesměrování).

3D Secure: vzhledem k tomu, že při těch testovacích transakcích jsem nevyužil svou kartu, nemohlo tak dojít k ověření karty a nemohla mi přijít ani žádná SMS Předpokládám, že v ostré verzi je už 3D Secure aktivní?

Děkuji

**Comment by mrazekl** [comment]
Testy komunikace - ECHO - provádět nemusíte a Woocommerce je ani nepodporuje.
Pro aktivaci do produkčního prostředí  je třeba udělat transakce tak, jak jsou popsané v návodu, na který se odkazujete. Jelikož používáte Woocommerce, je pro Vás dostačující po přesměrování na platební bránu zadat údaje dle návodu pro Úspěšně autorizovaná platba, Uživatelem zrušená platba, Expirovaná (zrušená) platba. Reverzovaná platba - není z Woocommerce podporovaná, můžete vyvolat z POSmerchant ve výpisu transakcí pomocí ikony "modrého dolaru". Jakmile budete mít splněno, v POSmerchant v sekci Platební brány pomocí ikony "lupa" provedete validaci.
Logo a barevné schéma je popsáno zde https://github.com/csob/paymentgateway/wiki/Zm%C4%9Bna-barevn%C3%A9ho-sch%C3%A9matu-br%C3%A1ny a zde https://github.com/csob/paymentgateway/wiki/Logo-obchodn%C3%ADka
iFrame je možné používat pouze na povolení z banky.
3DSecure - v integračním prostředí je pouze simulátor, v produkčním prostředí je samozřejmě plně funkční

**Comment by manestis** [comment]
Dobrý den
tak testovací transakce jsem provedl, dneska to dám i validovat. Logo jsem taky nastavil, barvy asi měnit ani nebudu. Ty co tam jsou původně, jsou dobré. Ještě bych potřeboval změnit jeden údaj - jak je v prostředí platební brány, v levém sloupci jak je: cena, pod tím zrušit platbu a vrátit se do obchodu, tak pod tím jsou firemní údaje

Název obchodu
Adresa
Telefon 
Email a
**www adresa**

Potřeboval bych změnit tu url adresu. Jelikož eshop máme na subdoméně, která "nebere" www a z téhle podoby subdomény to přesměrovává na doménu, tak bych to potřeboval opravit. Z www.eshop.mojedomena.cz na https://eshop.mojedomena.cz. Vím, že to není ani hypertextový odkaz, který by po kliknutí přesměroval do obchodu, ale lepší by bylo kdybychom to měli správně.

Děkuji

**Comment by manestis** [comment]
Dobrý den, tak jsem tam psal a zatím mi nikdo neodpověděl. Validaci jsem úspěšně provedl. Co teď? Jak přejít do produkčního prostředí? Přijde mi nějaký mail s přístupy do produkčního POS Merchant?

Děkuji

**Comment by mrazekl** [comment]
Jakmile bude váš požadavek schválen, budete aktivován do produkčního prostředí a přijde Vám oznamovací email o aktivaci. 
Postup je obdobný jako v TESTU, je potřeba vyměnit TESTOVACÍ klíče za PRODUKČNÍ:
vygenerovat klíče: https://platebnibrana.csob.cz/keygen/
Na email obdržíte heslo, které je potřeba vložit v POSmerchant v sekci platební brány přes ikonu "klíče".
A stáhnout veřejný klíč banky: https://github.com/csob/paymentgateway
přes odkaz "Clone or Download -> downloadZIP" - soubor mips_platebnibrana.csob.cz.pub
Tyto klíče nahradit v patřičné složce a přepsat názvy ve Woocommerce.
Posledním krokem je změna "Adresa brány" ve Woocommerce na: https://api.platebnibranacsob.cz/api/v.17
Přihlášení do produkčního POSmerchant je se stejným loginem a heslem jako na testu

**Comment by manestis** [comment]
Vygeneroval jsem ty klíče, na email mi přišlo heslo, ale nelze se mi přihlásit do produkčního prostředí POS Merchant (stejné přihlašovací údaje jako v test. prostředí). Zkoušel jsem heslo obnovit, ale vyhodilo to hlášku: Zadaný uživatel nebo e-mail nebyl v systému nalezen.

Do testovacího prostředí POS Merchant se mi normálně přihlásit jde.

**Comment by mrazekl** [comment]
Bohužel nezbývá, než se opět obrátit na akceptaci karet, že máte problém s přihlášením do produkčního posmerchant, s největší pravděpodobností obdržíte nové heslo.
