### ISSUE TITLE
prechod z testovaci na produkcni

### ISSUE THREAD

**Issue by dubcznic** [csob/paymentgateway#42]
Dobry den,
presel jsem z testovaci verze na produkcni nasledujicim postupem.
jedna se o uz.cislo: 27205711 a id brany M1MIPS0155

-zazadal jsem o validaci na "iposman.iplatebnibrana.csob.cz".
-vygeneroval jsem nove klice a ulozil je na server
-v setupu jsem zmenil adresu z "https://iapi.iplatebnibrana.csob.cz/api/v1" na "https://api.platebnibrana.csob.cz".
-v "posman.csob.cz/posmerchant/" jsem zadal jednorazovy kod pro heslo

v administraci vidim ze brana je aktivni, ale testy ktere mi fungovali mi fungovat prestali a kdyz odesilam novou objednavku, skript mi hlasi " processing payment/init request ... payment/init failed, http response: 404" viz screenshot http://screencast.com/t/2p4Exmfb

nejspis jsem jeste neco nekde zapomel potvrdit nebo mam cekat na schvaleni? testy mi padaji na payment/init a metoda ECHO vraci 404. pred prechodem na produkcni mi testy fungovali a vraceli pekne cislo 200.

diky moc za pomoc, nevim si s tim uz rady.

**Comment by ratajskym** [comment]
Dobrý den, 

Vaše transakce vidím na testovacím prostředí, nikoliv na produkci. Opravdu jste změnil cílovou url v setupu ?

**Comment by dubcznic** [comment]
Ano, i kdyz menim public key na ten ktery jsem vygeneroval tak to nefunguje. O tom ale nic v navodu nepisete, tak jsem ho nechal na hodnote "mips_iplatebnibrana.csob.cz.pub"

**Comment by ratajskym** [comment]
Píšete, že se snažíte přejít z testu do produkce. Já ale vidím Vaše transakce (merchant id z přiloženého screenshotu) na testovacím prostředí. Poslední je "September 7th 2015, 14:03:17.759". Takže z mého pohledu to máte u sebe ve skriptu špatně nakonfigurované.

**Comment by dubcznic** [comment]
OK diky za pomoc, radsi sem pregenroval znovu klice a potvrdil je jednorazovym kodem, abych si byl jisty ze jsem je vygeneroval na produkcnim keygenu.
nyni mi testy metodou ECHO vraci spravne 200, ale metoda INIT mi pise chybu "payment/init failed, unable to verify signature". prikladam radsi obsah souboru setup. Nikde neni napsano jestli mam menit public key, proto jsem ho nemenil, ale zkusil jsem ho i zmenit, ale podpis je stale neovereny. http://screencast.com/t/3VXjgSgw

uz vidite objednavky z produkcni domeny?

diky

**Comment by ratajskym** [comment]
Výborně, 

ano,už Vás vidím správně. Nicméně na základě Vašeho screenshotu vidím, že používáte špatný veřejný klíč pro ověření odpovědi

Podívejte se prosím na tento [link] (https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys)

Jsou tam dva klíče. Jeden pro produkční a jeden pro testovací prostředí. Je to napsané v readme.txt

**Comment by dubcznic** [comment]
Jasne vsimnul jsem si toho nez sem si precetl odpoved. Diky moc za pomoc uz jsem byl fakt zoufaly.

jen bych doporucil lepe sepsat postup kroku pro prechod na produkcni, idealne v bodech. napriklad to ze mam stahnout klic z odkazu co jse popsal jsem v dokumentaci nenalezl a vzorova aplikace se skriptem setup.php by byla asi taky intuitivnejsi, kdyby tam byly priklady pro testovaci a produkcni, kde by bylo jasne videt jak se ma menit adresa a klice.
ale jeste jednou diky moc za pomoc.

**Comment by ratajskym** [comment]
Jsem rád, že jsme to společně zvládli. 

Task uzavírám.
