### ISSUE TITLE
Please explain me that is the meaning?

### ISSUE THREAD

**Issue by johnybom** [csob/paymentgateway#420]
I am trying to do the gate payment for my e-shop, but I get stuck in this part:
https://github.com/csob/paymentgateway/wiki/eAPI-v1.7-EN#item---cart-item-object-cart-

//CAUTION: At least 1 item (e.g. “Your purchase”) and at most 2 items must be in the cart (e.g. “Your purchase” and “Shipping & Handling”).//
The CAUTION, it mean that in the shopping cart It must have at least 1 product AND at most 2 products? is that correct? 
If yes, what happen when customers order more than 2 products?
If no, Please explain me what is the meaning of that "CAUTION".
Thank you guys so much for your helping.

**Comment by Mspisar** [comment]
Hello,

It means only 2 items in cart you can use. 

1 - your ordered stuff
2 - transport fee

if you use more items your order cannot be processed.

best regards 

Milan Spisar

**Comment by johnybom** [comment]
> Hello,
> 
> It means only 2 items in cart you can use.
> 
> 1 - your ordered stuff
> 2 - transport fee
> 
> if you use more items your order cannot be processed.
> 
> best regards
> 
> Milan Spisar

Thank you Milan for your answer, 
So the price will show up the total price of the stuffs customer buying? 
in that case:
" {
      "name": "Purchase on yourshop.com",
      "quantity": 1,
      "amount": 1789600,
      "description":"Lenovo ThinkPad Edge E540"
    },
    {
      "name": "Shipping",
      "quantity": 1,
      "amount": 0,
      "description": "DHL Express"
What is the description of the "products name"?

**Comment by mrazekl** [comment]
Hello,

The final price depends on the value of the parameter totalAmount, must be equal to amounts from cart.
Product name - Item’s name, maximum length 20 characters - your own text, will be displayed to customer on payment gateway

**Comment by johnybom** [comment]
Thank you so much for all of your help. I did solve all of them out. One more question I would like to ask, 
How I can get my merchantID and the username, password to login Merchant POS? 
I signed contract with the bank, but no one gave me that information. Now I need to confirm all the test case to switch the gateway to live environment. @mrazekl  @Mspisar

**Comment by Mspisar** [comment]
Hello,
this kind of questions ( posmerchant account, transactions info and add new functionality to your payment gateway ) solve bank itself. You must contact them on email akceptacekaret@csob.cz for support. Yes for pass to production environment is necessary did all tests.
best regards
Milan Spisar
