### ISSUE TITLE
Přechod na produkci: Nenalezena transakce se stavem: Autorizace potvrzena/Posláno k zaúčtování

### ISSUE THREAD

**Issue by jaromirmuller** [csob/paymentgateway#422]
Dobrý den,

můžete prosím poradit, kde je problém s touto chybou: Nenalezena transakce se stavem: Autorizace potvrzena/Posláno k zaúčtování

![Snímek obrazovky(25)](https://user-images.githubusercontent.com/194480/55217953-055df780-5201-11e9-906f-6fe3335db839.png)

Podle dokumentace máme naimplementované všechny kroky.

Děkuji.

JM

**Comment by mrazekl** [comment]
Dobrý den,

nejedná se o chybu, ale vlastnost a sice takovou, že v momentě kdy na integračním prostředí provedete úspěšně autorizovanou transakci, tak nabyde stavu "Posláno k zaúčtování". O půlnoci se ale tento stav změní na "Zaúčtováno" a proto nesplňuje podmínky pro validaci, i když je vše v pořádku. Řešením je zopakovat úspěšně autorizovanou platbu a validaci provést vrámci stejného dne.

**Comment by jaromirmuller** [comment]
Dobrý den,

děkuji za vysvětlení. Je toto někde z dokumentováno? Podle popisu v přechodu na produkční prostředí jsem měl za to, že stačí transakci provést a faktor času nehraje roli.

Děkuji za info.

JM

**Comment by mrazekl** [comment]
Detailní popis, který jsem uvedl výše zde k dispozici není, lze si jej však logicky vyvodit ze životního cyklu transakce, popsaného na Githubu zde:
https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#%C5%BDivotn%C3%AD-cyklus-transakce-
a stavu transakce zobrazeného v sekci transakce -> platenbní brána na PosMerchant

**Comment by jaromirmuller** [comment]
Ok. Raďeji bych nedomýšlel jak brána funguje, ale někde danou informaci dočetl.

Tak jestli to teda chápu správně, tak je potřeba udělat kompletní ověření transakcí v jeden den a ten samý den je potřeba zkontrolovat, že jsou transakce na bráně a ukončit integrační testy a požádat o produkční klíče? 

Pokud tedy v jeden den uděláme integrační testy, dle popisu https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD a ověření na POS událáme až následující den, tak dostanu "chybu", kterou jsem uvedl na začátku vlákna. Souhlasí?

Děkuji za upřesnění.

**Comment by mrazekl** [comment]
Ano, je to tak, ostatní tři transakce svůj stav nemění ani nemůžou, pouze autorizovaná může nabývat více stavů. 
Všechny transakce je možné realizovat během cca. 30 minut(čas pro expiraci transakce) a poté provést validaci, proto se předpokládá že se validace odehraje během jednoho dne.

**Comment by jaromirmuller** [comment]
vyřešeno. díky za pomoc.
