### ISSUE TITLE
Mobilné zobrazenie iframe

### ISSUE THREAD

**Issue by iGavrilo** [csob/paymentgateway#423]
Zdravím,

vo firme riešime implementáciu platobnej brány pre klienta a požiadali sme o iframe prístup. Akurát máme problém so zobrazením na mobilných zariadeniach viz. https://www.dropbox.com/s/zx1v5zangxdg03e/Screenshot%202019-03-28%2013.12.43.jpg?dl=0

**Comment by mrazekl** [comment]
Dobrý den,

iFrame je dost specifická záležitost, pro kterou ani neexistuje oficiální dokumentace. Každý, kdo má toto rozšíření povoleno, si individuálně dělá řešení na míru, přesně pro své potřeby. V tomto případě si budete muset poradit sami a technická podpora v tomto směru není nabízena.
