### ISSUE TITLE
API místo kódu jazyka požaduje kód země.

### ISSUE THREAD

**Issue by zbohm** [csob/paymentgateway#424]
Dobrý den,
v [dokumentaci](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#popis-parametr%C5%AF-jednotliv%C3%BDch-metod) se píše, že pro češtinu je platný pouze kód "CZ". To je špatně, protože podle specifikace kód "CZ" není kód jazyka, ale kód země!!! Viz https://cs.wikipedia.org/wiki/Locale

Na kód jazyka "CS" vrací API chybu 110 - "Invalid language parameter, value not allowed".

**Comment by dhozik** [comment]
Dobrý den,
Váš požadavek předávám odpovědnému technikovi k vyjádření.
S pozdravem
David Hozík

**Comment by rataja** [comment]
Dobrý den, děkujeme za podnět. 

Držte se ale prosím vydefinovaného seznamu a použijte parametr s hodnotou CZ. Hodnota CS není v tuto chvíli podporovaná. Jedná se o "náš vlastní" výčet hodnot, neodkazujeme se na kód jazyka, ani na kód země. Tuším to není takhle explicitně uvedeno ani v dokumentaci a jsou tam uvedeny pouze povolené hodnoty

**Comment by ratajskym** [comment]
Dobrý den, děkujeme za podnět.

Držte se ale prosím vydefinovaného seznamu a použijte parametr s hodnotou CZ. Hodnota CS není v tuto chvíli podporovaná. Jedná se o "náš vlastní" výčet hodnot, neodkazujeme se na kód jazyka, ani na kód země. Tuším to není takhle explicitně uvedeno ani v dokumentaci a jsou tam uvedeny pouze povolené hodnoty

**Comment by janbrasna** [comment]
@zbohm Hezky den, to zjisteni bylo samozrejme naprosto spravne — enum kody v API prisly uz takto podedene ze starsiho systemu, a ten byl vazany na tld domeny resp. ponekud jinou logiku, a nikdo do toho tehdy nechtel zasahovat. Mel to nahradit system, ktery by parsoval "jakekoliv" jazyky i ve formatu mm_NN (i vc. quality score atp.) a na ne mapoval nejlepsi vhodny z dostupnych jazyku ap., ale nakonec se jeden konkretni jazyk stal povinnym vstupem od obchodnika, a skoncil jen takto pevnym vyctem.

Takze situace, ze to ve vysledku nejsou ISO jazyky, neni idealni — a uz se resi nahrada, a to tak, aby i stare puvodni enumy zustaly funkcni zpetne kompatibilni.

Diky za zpetnou vazbu. Resi se.
