### ISSUE TITLE
Barva textu položek v košíku je různá na telefonu a desktopu

### ISSUE THREAD

**Issue by landsman** [csob/paymentgateway#425]
Dobrý den,

bylo by prosím možné sjednotit pozadí položek košíku tak, aby bylo vždy stejné na desktopu i na telefonu? 

Ideální by bylo přidat ještě možnost nastavit si barvu textu položek košíku zvlášt.

Teď se dostávám do situace, že mám tmavé pozadí, bílý text a díky tomu, že máte napevno pozadí položek košíku - bílé, tak nejde text přečíst. Naopak na mobilu bílé pozadí položek košíku zmizí a je tmavé = lze přečíst dobře.

Úplně nejlepší řešení by bylo přidat dvě další proměnné a to:
- barva textu položek košíku
- barva pozadí položek košíku (a tu neměnit v responzivní variantě)

Půjde to prosím?
Děkuji

**Comment by mrazekl** [comment]
Dobrý den,

barevnému schématu je věnován oddíl zde:
https://github.com/csob/paymentgateway/wiki/Zm%C4%9Bna-barevn%C3%A9ho-sch%C3%A9matu-br%C3%A1ny

**Comment by landsman** [comment]
Dobrý den, to jsem četl a otestoval.

Funguje to přesně tak, jak jsem napsal výše, tedy z mého pohledu by to šlo opravit, aby bylo chování předvídatelné.

**Comment by landsman** [comment]
Zkuste si schválně nastavit stav, kde chcete mít maximum té plochy v jedné barvě, tj. třeba: `#7000a4`. Dostanete se do stavu, který jsem popsal - desktop a telefon nesjednotíte.

**Comment by janbrasna** [comment]
@landsman Zdravim, na kosiku budou probihat upravy, presneji receno priblizeni desktop logiky a renderu i v mobilni verzi, mohu se pak ozvat s nejakymi "pilotnimi" pokusy, ze bychom si vzali konkretni bud stavajici schema, nebo zamyslene cilove ktere byste potrebovali, a zkusili aplikovat v novem systemu zda to takto bude vyhovovat lepe?

**Comment by landsman** [comment]
Už vás nepoužíváme, díky.
