### ISSUE TITLE
Chybné produkčné kľúče - TSGSMIPS-8398

### ISSUE THREAD

**Issue by iGavrilo** [csob/paymentgateway#426]
Zdravím,

snažím sa o prechod na produkčnú verziu brány. Ale kľúče ktoré nám systém vygeneroval nie sú správne dostávame 400 s chybou že kľúče sú nesprávne.

https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD Toto sme úspešne absolvovali a braná je označená ako aktívna. 

Technická podpora nedvíha telefón tak to teda skúšam tu.

Ďakujem

**Comment by dhozik** [comment]
Dobrý den,

prosím Vás o sdělení ID brány. Situaci prověříme.

S pozdravem
David Hozík

**Comment by iGavrilo** [comment]
Tu je: M1MIPS5782

**Comment by Mspisar** [comment]
Dobrý den,

zkontrolujte si řetězec, který posíláte na platební bránu a ověřte přednostně produkční adresu. Tedy: **https://api.platebnibrana.csob.cz/**  nemáte v řetězci chybně uvedenou testovací adresu:  https://iapi.iplatebnibrana.csob.cz/ ?

s pozdravem

Spisar

**Comment by iGavrilo** [comment]
Reťazec na ktorý posielam požiadavky je https://api.platebnibrana.csob.cz/api/v1.7.

**Comment by ratajskym** [comment]
Dobrý den, adresu máte správně. Payment/init má špatný podpis. 

Vidím, že jste 2x potvrzovali produkční klíče . Ujistěte se tedy, že pro podpis používáte ten, který byl vygenerován 4.8.2019
2019-04-06 22:17:43,958000000
2019-04-08 13:18:55,279000000

Pokud si nejste jistí, vygenerujte klíče znovu, potvrďte je v aplikaci Posmerchant a vyzkoušejte znovu. 

Jako vždy doporučuji pro správnost klíčů použít triviální metodu **echo**, kde je minimální šance na implementační chybu.

**Comment by iGavrilo** [comment]
Vytvoril som si nové kľuče a následne ich schválil a nahradil staré. Vytvoril som si testovaciu funkciu ktorá mi neprejde cez getTest.

Chybová hláška: API returned HTTP code 400, which is not code 200. Probably wrong signature, check crypto keys.

Konfigurácia je určite správna s testovacími kľúčmi sme nemali žiadny problém.

**Comment by ratajskym** [comment]
V aplikačním logu je chyba jasná
10.04.2019 09:48:12.144 Invalid echo signature for merchant M1MIPS5782

Pošlu Vám email

**Comment by iGavrilo** [comment]
Môžem Vás poprosiť na dominik@blueweb.sk 

Ďakujem

**Comment by ratajskym** [comment]
A protože mi to nedalo, zkusil jsem echo i pomocí knihovny od Ondry Koupila

```
<?php

require_once './csob-client.php';

$config = new OndraKoupil\Csob\Config(
	"VaseMerchantID",
	"./privatniKlicCoJsteMiPoslal.key",
	"./mips_platebnibrana.csob.cz.pub",
	"Echo Test",

	// Adresa, kam se mají zákazníci vracet poté, co zaplatí
	"https://www.my-eshop.cz/return-path.php"
);

$config->url = 'https://api.platebnibrana.csob.cz/api/v1.7';

$client = new OndraKoupil\Csob\Client($config);

try {
	$client->testGetConnection();
	$client->testPostConnection();

} catch (Exception $e) {
	echo "Something went wrong: " . $e->getMessage();
}
```

A tohle mi zafungovalo v pořádku

**Comment by iGavrilo** [comment]
Chyba bola v privatnom kľúči. Pán Ratajský mi ochotne pomohol.

Ďakujem
