### ISSUE TITLE
Nelze verifikovat response operace GET payment/status

### ISSUE THREAD

**Issue by viktorzavadil** [csob/paymentgateway#428]
Tato operace mi na integračním prostředí vrací následující:
```
{
    "dttm": "20190529190807",
    "signature": "WRg1gNnn0sZrz4Zb/+jHXSdut4cVsztn1ycGhY6zPrAqc5i2bsKt3mXTGAZYWAcZhpoAweJF+8u8a4d9aIOZA/11wqVwQ+km3gb/UC5l0rB8Z4cIDtgENECVAIaV9OhD3l7wtdFPV6ChY75pPG4+eTQezRLJIY5uAFADakisrV0m+erVTIYEi2D4gLkLVb3wxG2NKSldqJDlOoMJhFTN5Lvnbws2YniFQJ13B1xCzYrqpegHFW32eKjikzFaxxBRFRzOL5uIF1ZRtdCoG6BENtgoErAmDHCfh0ZA7YYni9a2Vi1LIhtnNfEunzbiqjYCqDJ6lCxanNbdF5oseb8ZCQ==",
    "payId": "c2817b49c7a4eEE",
    "resultCode": 0,
    "resultMessage": "OK",
    "paymentStatus": 7,
    "authCode": "771447"
}
```
Řekl bych, že je problém v pořadí vlastností `dttm` a `signature` (`signature` ale nevadí, protože se neverifikuje).

Pokud popřeházím vlastnosti následovně, již to proběhne v pořádku:
```
{
    "payId": "c2817b49c7a4eEE",
    "dttm": "20190529190807",
    "resultCode": 0,
    "resultMessage": "OK",
    "paymentStatus": 7,
    "authCode": "771447",
    "signature": "WRg1gNnn0sZrz4Zb/+jHXSdut4cVsztn1ycGhY6zPrAqc5i2bsKt3mXTGAZYWAcZhpoAweJF+8u8a4d9aIOZA/11wqVwQ+km3gb/UC5l0rB8Z4cIDtgENECVAIaV9OhD3l7wtdFPV6ChY75pPG4+eTQezRLJIY5uAFADakisrV0m+erVTIYEi2D4gLkLVb3wxG2NKSldqJDlOoMJhFTN5Lvnbws2YniFQJ13B1xCzYrqpegHFW32eKjikzFaxxBRFRzOL5uIF1ZRtdCoG6BENtgoErAmDHCfh0ZA7YYni9a2Vi1LIhtnNfEunzbiqjYCqDJ6lCxanNbdF5oseb8ZCQ==",
}
```
Prosím o prověření, uměle měnit pořadí se mi nechce. Díky.

**Comment by viktorzavadil** [comment]
V javascriptu jsem udělal workaround, který spočívá ve vytvoření objektu, v kterém se inicializují hodnoty ve správném pořadí, ale chtělo by se na podpis spolehnout i bez zásahu.

**Comment by viktorzavadil** [comment]
Zdá se, že nefunguje u všech operací, které mají stejnou definici jako `payment/init`, ověřeno u
- `payment/init`
- `payment/oneclick/init`
- `payment/oneclick/start`

**Comment by Mspisar** [comment]
Dobrý den,

omlouváme se za prodlevu v reakci. Požadavek předávám na kolegu.

s pozdravem

Spisar

**Comment by mrazekl** [comment]
Dobrý den,

pro ověření je opravdu nutné dodržet posloupnost parametrů tak, jak jsou popsány v dokumentaci. To je platné pro všechny a všechny typy operací, jinak se podpis nepodaří verifikovat a požadavek není platný.

**Comment by viktorzavadil** [comment]
Navrhuji popsat v dokumentaci, že si klient musí seřadit hodnoty dle pořadí v tabulkách.
