### ISSUE TITLE
Dotaz ohledně stavu platby 6 - zamítnuto

### ISSUE THREAD

**Issue by viktorzavadil** [csob/paymentgateway#429]
Dobrý den,

mám dotaz ohledně stavu zamítnuto. V dokumentaci se píše:
> 6) Platba zamítnuta   Tento stav byl již popsán výše, důvodů zamítnutí platby je více a jsou detailně rozlišeny v návratovém kódu operace.

(Viz v kapitole [životní cyklus transakce](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#%C5%BDivotn%C3%AD-cyklus-transakce-))

Pak ale dále v kapitole [návratové hodnoty](https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#n%C3%A1vratov%C3%A9-hodnoty-):

Položka | Typ | Popis
-- | -- | --
paymentStatus | Number | Stav platby, viz životní cyklus transakce, vyplněno v případě, že resultCode je 0

Zde vidím nekonzistenci, v jednom se píše, že důvody budou detailně rozlišeny v návratovém kódu, v druhém, že status `paymentStatus` (tedy i 6) bude vyplněn pouze, pokud bude `resultCode` 0.

Prosím o objasnění, jak se systém zachová, pokud provedu platbu _Na klik_ a platba bude zamítnuta například z důvodu, že uživatel nemá prostředky. Co vrátí volání `GET payment/status`? Co bude v polích `resultCode` a `resultMessage`? Díky

```
{
    "payId": "abcdabcd123456",
    "dttm": "20190530181000",
    "resultCode": "?",
    "resultMessage": "?",
    "paymentStatus": 6,
    "authCode": "123456",
    "signature": "base64",
}
```

**Comment by mrazekl** [comment]
Dobrý den,

nejedná se o nekonzistenci. Jedná se o stav, kdy se nevrátí stav 0, ale jiný s příslušným popisem v poli reultMessage, proč byl požadavek neúspěšný a paymentstatus je zde zbytečný.
Pokud je nedostatek prostředků na kartě, nejedná se o koncový stav transakce, zákazníkovi se tato informace zobrazí a může třeba dokončit stejnou objednávku jinou kartou. Stejně tak má možnost zrušit tuto objednávku pomocí tlačítka, zavřít prohlížeč atd....v tomto případě se vrátí
"resultCode": "0",
"resultMessage": "OK",
"paymentStatus": 3,    - platba zrušena(tlačítkem)   nebo 
"paymentStatus": 6,    - platba zamítnuta(zavření prohlížeče)  nebo
"paymentStatus": 7,    - pokud objednávku dokončí

**Comment by viktorzavadil** [comment]
Dobrý den,

a co se stane v případě, že se jedná o platbu *Na klik* a uživatel nemá prostředky? Co vrací operace `GET payment/status`?

**Comment by mrazekl** [comment]
Dobrý den,

v tomto případě se vrátí pouze "paymentStatus": 6 - platba zamítnuta. To je pro obchodníka konečný stav, informující že objednávka nebyla uhrazena.

**Comment by viktorzavadil** [comment]
Prozatím to bude vše, děkuji.
