### ISSUE TITLE
Implementace platby Na klik

### ISSUE THREAD

**Issue by viktorzavadil** [csob/paymentgateway#430]
Dobrý den,

snažím se realizovat platbu _Na klik_, ale volání `payment/oneclick/start` vrací `resultCode` _150_ se zprávou `Payment not in valid state`. Šablona pro platbu je již zúčtovaná:

![template](https://user-images.githubusercontent.com/19145428/58955303-f022bd80-879b-11e9-82ca-c1c102e41c8b.png)

Platby, které neprošly (podle `payId`) pro `M1MIPS4581`:
- a23c72ed3cafcEF
- 283ae953c7420EF
- a další...

Prosím o pomoc, díky.

**Comment by dmarek** [comment]
Dobrý den, trx jsou založeny v integračním prostředí, je to tak správně? Spouštíte to proti správnému prostředí?

**Comment by viktorzavadil** [comment]
Dobrý den,

měli bychom to mít nastavené na obou prostředích. Ale ano, tyto transakce jsou proti integračnímu prostředí.

**Comment by dmarek** [comment]
po zalozeni je oneclick trx zamitnuta z duvodu duplicity na orderNo, nektera drivejsi autorizovana trx ma toto orderNo uz prirazene (je nutne bud posilat jine orderNo anebo mit s CSOB domluvene nastaveni obchodnika, kdy se nekontroluje unikatnost orderNo)

Trx M1MIPS4581 / a23c72ed3cafcEF declined: authorized trx for orderNo 1955131080 already exists

**Comment by viktorzavadil** [comment]
Aha, díky. Už jsem zaslal požadavek.

**Comment by dmarek** [comment]
ok, zaviram, pokud budete potrebovat neco doresit, muzete to znovuotevrit ...

**Comment by viktorzavadil** [comment]
Dobrý den, od včera bychom měli mít nastavené zrušení kontroly VS, ale platební brána se chová pořád stejně. Viz platby `08e1d77366055EF` nebo `d9b54ccbe0206EF`. Byla zde použita template platby `c6df593bf1cf5EF`, která je ve stavu _Zaúčtováno_.

**Comment by dmarek** [comment]
V nastavení obchodníka M1MIPS4581 je stále nastavena kontrola duplicity orderNo, Prověříme na straně ČSOB.

**Comment by marekdub** [comment]
@viktorzavadil Zkuste to prosím znovu, kontrola VS byla vypnuta na platební bráně. Díky.

**Comment by viktorzavadil** [comment]
@marekdub Funguje, děkuji Vám za spolupráci.
