### ISSUE TITLE
Chyba pro duplicitní platbu

### ISSUE THREAD

**Issue by miloslavkostir** [csob/paymentgateway#431]
Dobrý den,

k duplicitním platbám by nemělo docházet, před platbou si zavolám status a zjistím, zda není platba zaplacena. Teď už to vím, ale dříve mi chodila chyba 110 (Invalid paymentInit request: authorized trx for merchantId xxxxxx and orderNo xxxxxx already exists)

Chybový kód 110 je ale Invalid parameter {name}

Chápu, že při duplicitní platbě zadávám vlastně špatný parametr orderNo, ale technicky vzato jde o úplně jinou chybu. Nezasloužila by si duplicitní platba vlastní chybový kód?

**Comment by mrazekl** [comment]
Dobrý den,

děkujeme za podnět.
V principu se však jedná o nevalidní parametr, jelikož orderNo musí být unikátní, jak zní jeho definice.
A z vráceného popisu že objednávka číslo XX již existuje přímo vyplývá, že se jedná o duplicitu.

**Comment by miloslavkostir** [comment]
Dobrý den,

ještě ten můj dotaz trochu upřesním. Status si zavolám jen tehdy, pokud mám payId. Jinak nemám možnost ověřit, zda už nebyla platba provedena. Je to tak?    
Takže pokud chci rozlišit chybu implementace brány (respektive chybu volání init požadavku) od uživatelské chyby (dvojí pokus o zaplacení - například stránka načtená ve 2 oknech, nebo 2 uživatelé přihlášeni k jednomu účtu snažící se zaplatit), jediná možnost je něco takového?

```php
if ($code === 110 && preg_match('/authorized trx for merchantId (.*) and orderNo (.*) already exists/', $message)) {
    $error = 'Tato platba již byla zaplacena.';
} else {
    $error = 'Během platby se vyskytla chyba a proces byl ukončen.';
}
```
A samozřejmě musím doufat, že se text zprávy nezmění.

**Comment by mrazekl** [comment]
Dobrý den,
ano, bez payID metodu status neověříte, přiděluje ji platební brána po příchozím požadavku payment/init. Naopak hodnotu orderNo generujete vy, pokud nastavíte inkrementaci tohoto parametru po každém volání payment/init bez ohledu na výsledek této operace, nemůže k duplicitě dojít.
Pokud je stránka načtená ve dvou oknech, každé tohle okno vznikne vrámci nového payment/init a tím pádem i s novým orderNo.

Text pro duplicitu je pevně daný a neměnný.
