### ISSUE TITLE
Časový limit pro automatickou expiraci nedokončení platby

### ISSUE THREAD

**Issue by nufue** [csob/paymentgateway#433]
Dobrý den, navazuji na https://github.com/csob/paymentgateway/issues/25. Chtěl bych se zeptat, jak dlouhá je aktuální doba, po které nedokončená platební transakce expiruje? Historicky to bylo 30 +/- 2 minuty, včera se nám stalo, že platební brána i po 40 minutách od založení hlísila stav 2 (čeká na platbu). Předem díky za odpověď.

**Comment by mrazekl** [comment]
Dobrý den, 
časový limit se neměnil a je stále 30 minut. Pokud byla platba dokončena, došlo k nějakému nestandartnímu stavu a pro ověření bychom potřebovali znát payID.

**Comment by nufue** [comment]
@mrazekl Jedná se o payID `d60475d889bc9EF`. Díky.

**Comment by mrazekl** [comment]
Máte pravdu, v tomto případě došlo k delší prodlevě, transakce byla zaúčtována ihned, ale správný status se vracel až po cca. 2 hodinách. Vyjímečně se to mohlo stát, v pondělí bude vydána aktualizace po které k těmto ojedinělým případům docházet nebude.

**Comment by nufue** [comment]
Díky za reakci a za vyřešení.
