### ISSUE TITLE
supplied key param cannot be coerced into a public key

### ISSUE THREAD

**Issue by zackx1** [csob/paymentgateway#436]
Dobrý den,

při nastavení platební brány eshop při snaze o spojení vygeneruje tyto chyby:

Warning: openssl_verify(): supplied key param cannot be coerced into a public key in /data/http/shop5/class/_class.csob.php on line 237

Warning: openssl_free_key() expects parameter 1 to be resource, boolean given in /data/http/shop5/class/_class.csob.php on line 238
Chyba: payment/init failed, unable to verify signature

Dle podobných issues v tomto repo jsem zkontroloval soubor veřejného kliče brány, který odpovídá požadovanému formátu.

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuo0GzBCQMl1wDJJrJHTQ
ykGlh2Kon7QfQjKVTPv7fPIVE8PhHeJueWBfydqTQKVeIVMB9VAUYlaPjwFhAuJ6
zqoaCG9m+q81L7CehsQThntxacOPwRd4SSyS5o+kPzTIFji0Z3c8s6pYJJoF+YfE
atCWRW2frgrgbHbl+84AOvItt7NReYz1z4P7J+Uv4UbifFHVP7oIEh+5CJSj6puv
jHh1QHrzE+dTaoKDhtOfSkTTelHqod/hUt4QIcHai6I8X/R5nEv3y40MWoi1FxbQ
6IgtVMloneN0XaHR5U88eMeKJJyqR859I4xfun6Z6RyfyaIl5Ph3f2daeMeENPUR
BQIDAQAB
-----END PUBLIC KEY-----

**Comment by mrazekl** [comment]
Dobrý den,
jaké máte přidělené ID platební brány? Zkoušíte na produkčním/integračním prostředí?

**Comment by zackx1** [comment]
Dobrý den,
zkouším integrační prostředí a Merchant ID je M1MIPS7156. 

![Výstřižek](https://user-images.githubusercontent.com/13586469/60666958-a398d380-9e68-11e9-8f66-4e68bf58b396.PNG)

**Comment by zackx1** [comment]
Dobrý den,

vygeneroval jsem novou sadu klíčů a vše již funguje, jak má.
