### ISSUE TITLE
Nelze se přihlásit do implementačního (testovacího) prostředí POS merchant

### ISSUE THREAD

**Issue by vinadac** [csob/paymentgateway#437]
Dobrý den,

pro pl. bránu M1MIPS7184, už. jméno 05069238 se mi nedaří přihlásit se do integračního prostředí platební brány ČSOB. Klíče vygenerovány, veřejný zaslán na ČSOB. Ostrá verze bez problémů - přihlásit se lze. Přístup nelze vyřešit ani pomocí resetu hesla - kombinace uživatelské jméno + kontaktní email nefunguje.
Prosím o pomoc.

S pozdravem

J. Štok

**Comment by Mspisar** [comment]
Dobrý den, pane Štoku,

pro obnovu přístupu ( platí jak pro produkční tak testovací prostředí ) zašlete email s žádostí na: akceptacekaret@csob.cz

s pozdravem

Spisar
