### ISSUE TITLE
expirace serverového certifikátu informacni email

### ISSUE THREAD

**Issue by radovanx** [csob/paymentgateway#438]
Dobrý den,

Prosím o bližśí informaci co konkrétně znamená expirace certifikátu pro klienty s již nainstalovanou platební bránou. Děkuji za odpoved

viz
na doméně platební brány ČSOB https://api.platebnibrana.csob.cz/ dojde 18. 10. 2019 k exspiraci serverového certifikátu. V případě, že Váš e-shop ověřuje důvěru aktuálního certifikátu na dané doméně, bude nutný technický zásah i na Vaší straně. Bližší informace ohledně výměny certifikátu naleznete ZDE v online dokumentaci na GitHubu.
V průběhu srpna a září Vás budeme o změně serverového certifikátu platební brány znovu informovat.

**Comment by Mspisar** [comment]
Dobrý den,

výměnu certifikátu prosím vyřešte s tím kdo Vám bránu implementoval. V odkazu jsou veškeré potřebné informace. 

S pozdarvem

Spisar

**Comment by radovanx** [comment]
Dobrý den,

Prosím o odpověd

**Comment by Mspisar** [comment]
Dobrý den,

požadavek předávám na kolegu k podrobnějšímu popisu.

s pozdravem

Spisar

**Comment by mrazekl** [comment]
Dobrý den,
pokusím se vysvětlit v bodech:
- ano, změna se týká vyýměny bezpečnostního certifikátu serveru https://api.platebnibrana.csob.cz/ , tedy    z Vašeho pohledu na naší straně
- nové klíče generovat **nemusíte**
- během měsíce zaří bude zveřejněno, kdy dojde k výměně a následně bude tento certifikát poskytnut ke stažení, dříve není možné nový certifikát získat ani otestovat
- více součinnosti není potřeba
- tato výměna se týká jen e-shopů, které používají k ověření serveru platební brány bezpečnostní certifikát(tohle si můžete zjistit u někoho, kdo vám e-shop vytvořil nebo spravuje)
- v praxi to bude vypadat tak, že si nový certifikát budete moci s předstihem importovat do svého truststore souboru a v den zavedení nového certifikátu tuto změnu nijak nezaregistrujete

**Comment by radovanx** [comment]
Dobrý den,
@mrazekl Děkuji za odpověd. Věřím že bude užitečné i ostatním.

**Comment by mrazekl** [comment]
Certifikát je k dispozici ke stažení zde:
https://github.com/csob/paymentgateway/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy#v%C3%BDm%C4%9Bna-certifik%C3%A1tu-httpsapiplatebnibranacsobcz
