### ISSUE TITLE
Odeslání košíku bez dopravy

### ISSUE THREAD

**Issue by WeDesIn** [csob/paymentgateway#439]
Dobrý den, 

používám verzi API 1.6 a snažím se odstranit pro odeslání platby z košíku na bráně dopravu. 
V souboru crypto.php jsem zakomentoval druhý parametr z řady, ale po odeslání objednávky na bránu vrací brána místo původní odpovědi 200 vrací 404. 

Přitom by podle dokumentace mělo být odeslání objednávky pouze s jednou položkou možné. 

Nesetkal se s tím někdo? 

Děkuji, 

Josef

**Comment by mrazekl** [comment]
Dobrý den,
Z vašeho popisu není jasné, jaké používáte ID brány, ani zda se odkazujete na integrační nebo produkční prostředí. Tyto údaje jsou pro prověření nutné.
Nicméně předpokládám, že používáte Woocommerce. Pokud nechcete poštovné jen účtovat, nejsnadnějším řešením je druhou položku košíku pojmenovat "doprava" a zaslat ji s nulovou hodnotou.
V tomto případě se na platební bráně zobrazí jako ZDARMA.

**Comment by WeDesIn** [comment]
Dobrý den, 

jde o produkční prostředí, nepoužívám WooCommerce, jde o vlastní nasazení. Právě že jí mám pojmenovanou doprava, ale jde o poukazy, které chodí mailem, tak to úplně nedává smysl, ač je nastavená na hodnotu "zdarma". 

Adresa brány je https://api.platebnibrana.csob.cz/api/v1.6

Děkuji za pomoc, 

Josef

**Comment by mrazekl** [comment]
Dobrý den,
ID brány bylo myšleno MerchantID, které máte přiděleno. Začínající M1MIPS, popřípadě M1E3CB a čtyrčíslí. Také uveďte den a přibližný čas, abychom mohli zkontrolovat, co bylo na platební bránu ve skutečnosti odesláno a kde by mohl být problém.

**Comment by WeDesIn** [comment]
Dobrý den, 
omlouvám se za odmlku, byl jsem na dovolené. 

ID je M1MIPS2219

Poslední objednávka byla dnes ráno v 9:15. 

Děkuji vám mnohokrát za pomoc. 

S pozdravem, 

Josef

**Comment by mrazekl** [comment]
Objednávka z 9:15 byla úspěšná, ale obsahovala 2 položky košíku.
Na základě Vašeho MerchantID M1MIPS2219 jsem dohledal transakce ze 25.7, např. objednávka 1564048363, 1564048720 kde je vyplněna jen jedna položka košíku ale vrací se http response 400 - chybný podpis. Zohlednil jste přítomnost pouze jedné položky košíku ve výsledném řetězci, ze kterého skládáte podpis celého initu??

**Comment by WeDesIn** [comment]
Dobrý den, 

máte pravdu, tím to je. Viz platby z logu, horní se je špatně, dolní správně: 

----- Thu, 25 Jul 2019 11:52:43 +0200 ----- payment/init data to sign:: 'M1MIPS2219|1564048363|20190725115243|payment|card|50000|CZK|true|http://localhost:8012/endorfin/objednavka/|GET|Nákup v obchodě|1|50000||||||Endorfin Escaperooms|m16482|1234|CZ'
----- Thu, 25 Jul 2019 11:53:44 +0200 ----- payment/init data to sign:: 'M1MIPS2219|1564048424|20190725115344|payment|card|50000|CZK|true|http://localhost:8012/endorfin/objednavka/|GET|Nákup v obchodě|1|50000||Poštovné|1|0|Email|Endorfin Escaperooms|m16488|1234|CZ'
-

Nicméně nemůžu v dokumentaci přijít na to, aby brána neočekávala dva produkty. 

Přes metodu `createPaymentInitData( ( 'cart'          => $cartData, )  )` vkládám 
```
Array
(
    [0] => Array
        (
            [name] => Nákup v obchodě
            [quantity] => 1
            [amount] => 50000
            [description] => 
        )

)
```

Bohužel to právě očekává ještě druhý parametr, ať dělám co chci... 

Můžete mi poradit?

Děkuji, 

Josef

**Comment by ratajskym** [comment]
Dobrý den, podle čeho soudíte, že brána očekává i druhý produkt. Pokud to pošlete jak uvádíte, mělo y to být v pořádku

**Comment by WeDesIn** [comment]
Dobrý den,

soudím podle toho, že když pošlu takto: 

```
Array
(
    [0] => Array
        (
            [name] => Nákup v obchodě
            [quantity] => 1
            [amount] => 50000
            [description] => 
        )

)
```

tak se to neodešle, kdyžto když pošlu takto:

```
Array
(
    [0] => Array
        (
            [name] => Nákup v obchodě
            [quantity] => 1
            [amount] => 50000
            [description] => 
        ),
[1] => Array
        (
            [name] => Odesláno emailem
            [quantity] => 1
            [amount] => 0
            [description] => 
        )

)
```

Tak úplně v pohodě...

Díky, 

Josef

**Comment by mrazekl** [comment]
Dobrý den,
povedla se mi nasimulovat Vaše situace, když jsem odstranil druhou položku košíku a vracel se mi http response 400.
Upravoval jsem kód pro Woocommerce plugin, který je veřejně dostupný zde: https://github.com/csob/paymentgateway/blob/master/WooCommerce%20Plugin/www/monetWebPay/crypto.php
Nejprve jsem odstranil druhou položku košíku z cartData na výslený kód:

$cartData = array(
0 => array(
"name" => mb_substr(trim($firstCartItemDesc), 0, 20, 'utf-8'),
"quantity" => Constants::$SHOP_CART_QUANTITY,
"amount" => $totalAmount - $shippingTotal,
"description" => $titles
)
);
return $cartData;

poté bylo potřeba odstranit druhou položku košíku z dat, které se vkládají do řetězce pro podpis:
$cart2Sign = $data["cart"][0]["name"] . "|" . $data["cart"][0]["quantity"] . "|" . $data["cart"][0]["amount"] . "|" . $data["cart"][0]["description"] ."|";

a v tento moment jsem dosáhl Vašeho stavu se špatným podpisem, jelikož se podpis skládal z řetězce:

A40685FgL3|146|20190812070135|payment|card|29900|CZK|true|http://localhost/wordpress/wp-content/plugins/WooCommerceMonetGateWay/returnUrl.php?orderNumber=146|GET||1|29900|test...||Objednavka 146|1|EN

kde je navíc jeden oddělovač("pipe") a proto je výsledný podpis nevalidní. Po odstranění pipe(zvýrazněna červeně) z cart2Sign je již podpis validní a přesměrování na platební bránu úspěšné pouze s jednou košíkovou položkou.

Věřím, že by Vás to mohlo inspirovat k tomu, kde u sebe v kódu najít nadbytečné data, ze kterých skládáte podpis.
