### ISSUE TITLE
ResultCode: 110, ResultMessage: Currency parameter USD not allowed

### ISSUE THREAD

**Issue by JaroslavDuska** [csob/paymentgateway#440]
Dobrý den,

MerchantId: M1MIPS7116 - z banky máme potvrzeno, že více měn na bráně můžeme využít, nicméně funguje pouze založení platby s CZK:

"Na všech třech doménách máte povolenou multicurrency, tedy akceptaci více měn (konkrétně CZK, EUR a USD). Je ale možné, že jste neprovedli nastavení těchto měn přímo na bráně, což musíte provést – resp. Váš webmaster. Posílám odkaz na github, kde najdete všechny potřebné informace: https://github.com/csob/paymentgateway/wiki"

Wiki, příručku k POSMerchant a podobné problémy jsem prošel, ale možné nastavení měn na bráně, jak zmiňuje odpověď z banky nikde nenašel. Můžete mi prosím poradit, kde je toto nastavení ukryto?

Ještě mám dotaz týkající se založení platby s parametrem PayOperation = oneclickPayment - u takové platby by v případě kladné autorizace mělo být vráceno rozšíření maskClnRP - platbu na klik bychom také měly mít aktivovanou, ale rozšíření v odpovědi payment/status vráceno není, kde by mohl být problém?

Děkuji

**Comment by LucieSnedarova** [comment]
Dobrý den,
Váš požadavek byl předán na odpovědného kolegu.
S pozdravem
Lucie Šnédarová

**Comment by mrazekl** [comment]
Dobrý den,
   eviduji tady pár nesrovnalostí, pokusím se to rozklíčovat. 
Pro Vaše merchantID vidím povoleny pouze transakce v CZK, doporučuji se tedy obrátit na akceptacekaret@csob.cz, zda by na základě smlouvy povolili i další požadované měny.
Žádné další nastavení není třeba, pouze pošlete payment/init s patřičně vyplněným parametrem currency.
   Pro oneclick platby máte vytvořeno několik šablon, neevidujeme však žádný požadavek typu payment/oneclick/init a payment/oneclick/start, přes které se tyto platby inicializují.
   Aby se Vám pro payment/status vracela hodnota maskedCLn, musíte mít povolen rozšíření(extensions) - maskedCLnRP - pro její aktivaci se rovněž obraťte na výše uvedený e-mail.

**Comment by JaroslavDuska** [comment]
Děkuji za váš čas a informace, obrátíme se tedy na akceptacekaret@csob.cz a snad už nám to nastaví správně.
