### ISSUE TITLE
connection was forcibly closed

### ISSUE THREAD

**Issue by mistanek** [csob/paymentgateway#441]
Dobrý den,
Merchant ID: M1E3CB0992
11.8.2019 nám platba hodila tuto chybu: System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
  ErrorCode : 10054

Problém se vyskytl jednou, jinak platby procházejí.
Můžete prověřit čím to může být způsobeno?
Děkuji

**Comment by mrazekl** [comment]
Dobrý den,
ze dne 11.8 vidím jen úspěšné transakce. Mohl by jste uvést variabilní symbol, nebo čas této objednávky? V tento den v rozmezí 3:50 - 4:30 ráno byla platební brána nedostupná z důvodu plánované údržby systémů. Dle uvedé chyby mám tušení, že to bude mít souvislost.

**Comment by mistanek** [comment]
Dobrý den,
VS je 1238005714. Ale myslím, že se opravdu trefil do odstávky.
Děkuji

**Comment by mrazekl** [comment]
Děkuji,  v tom případě uzavírám.

**Comment by mistanek** [comment]
Dobrý den,
ze včerejška máme těsně po 18:00 dvakrát zopakovanou (VS: 1792655953 a 1608002385-tato byla zaplacena později) novou chybu:
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 193.245.34.232:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
  ErrorCode : 10060
Jde o problém na vaší straně?
Děkuji
