### ISSUE TITLE
chyba 10060

### ISSUE THREAD

**Issue by mistanek** [csob/paymentgateway#442]
Dobrý den,
Merchant ID: M1E3CB0992
ze včerejška máme těsně po 18:00 dvakrát zopakovanou (VS: 1792655953 a 1608002385-tato byla zaplacena později) novou chybu:
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 193.245.34.232:443
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
ErrorCode : 10060
Jde o problém na vaší straně?
Děkuji

viz. minulé issue:
Dobrý den,
ze dne 11.8 vidím jen úspěšné transakce. Mohl by jste uvést variabilní symbol, nebo čas této objednávky? V tento den v rozmezí 3:50 - 4:30 ráno byla platební brána nedostupná z důvodu plánované údržby systémů. Dle uvedé chyby mám tušení, že to bude mít souvislost.

_Originally posted by @mrazekl in https://github.com/csob/paymentgateway/issues/441#issuecomment-520336483_

**Comment by mrazekl** [comment]
Dobrý den,

dle mého názoru se nejedná o objednávky, jelikož ty se uskutečnily v ranních hodinách, ale o požadavky typu payment/status. Ty slouží k ověření stavu transakce.

Pro objednávku 4d57fed8d7c23EH, VS:1608002385 je evidujeme v pravidelném hodinovém intervalu, ale mezi 16:59 a 18:59 je mezera v 17:59. Na základě vámi popisované chyby a této skutečnosti je zřejmé, že se tento request na api.platebnibrana.csob.cz neodeslal. Platební brána v té době byla dostupná, v rozmezí 17:55 - 18:10 vyřídila na 6 000 těchto requestů.

Pro detailnější analýzu bychom potřebovali kompletní log k těmto requestům, kde je patrné odkud a kam tento požadavek směřuje, jaké obsahuje data a tak dále, který bychom podstoupili síťovému oddělení v bance. Jelikož může obsahovat citlivé data, doporučil bych tuto žádost směřovat na akceptacekaret@csob.cz kde jsou důvěrné informace v bezpečí.
