### ISSUE TITLE
příprava na Apple Pay

### ISSUE THREAD

**Issue by landsman** [csob/paymentgateway#443]
Dobrý den,

máte k dispozici již nějaké materiály, jak se připravit na integraci Apple Pay, co bude třeba?
Viz. https://www.facebook.com/csob/posts/2128899870490805.

Díky

**Comment by mrazekl** [comment]
Dnes byla na githubu oficiálně oznámena verze API1.8, která podporuje Applepay.
viz: https://github.com/inoxive/eAPI-beta/wiki/Apple-Pay
