### ISSUE TITLE
Jak invalidovat oneclick vzorovou platbu

### ISSUE THREAD

**Issue by bambooCZ** [csob/paymentgateway#445]
Dobrý den,

chtěl bych se zeptat zda a jak je možné invalidovat registrační platbu pro oneclick platby, tak aby prostě už nefungovala pro další oneclick platby?

**Comment by bambooCZ** [comment]
Aha, no mě by přišlo etické vůči uživatelům umět se dobrovolně zbavit možnosti strhávat jim peníze z karty... To mi pak tedy nepřijde šťastné. Konkurenční GP Web Pay to umožňuje.

**Comment by mrazekl** [comment]
Není možné, že jste zaměnil oneclick platbu s opakovanou platbou? Oneclick platba je pouze zjednodušená klasická platba, kdy není zákazník přesměrován na platební bránu a z jeho pohledu se tudíž jedná o platbu na jeden klik. Nejedná se o pravidelně se opakující strhávání stejné částky.

**Comment by bambooCZ** [comment]
Pravděpodobně nezamnenil. Děláme aplikaci na placení v restauracích, kde si zákazník přidá kartu a následně mu z ní strháváme za jeho útratu. Nejedná se o pravidelné strhávání. Z nabízených možností je oneclick platba přesně to, co potřebujeme.

**Comment by bambooCZ** [comment]
Jak mám zavření rozumět? Jako že nebudeme řešit?

**Comment by janbrasna** [comment]
Resit aktualne lze jen teoreticky — jediny kdo o "skutecne" zruseni platebni serie muze zazadat, je drzitel karty — je to tedy proces via jeho vydavatelskou banku. Zpracovatelska banka s tim az tak moc provest nedokaze. Kdyz ID sablony zapomenete/zahodite u vas, je to podobne jako kdyz opakovatelnost sablony omezi brana (autorizovane to bude tak jako tak dokud neubehne platnost serie ad [Kdy platba Na klik končí nebo je zrušena](https://github.com/csob/paymentgateway/wiki/Platba-na-klik#kdy-platba-na-klik-konč%C3%AD-nebo-je-zrušena))

Kazdopadne funkci pro odebrani budouci pouzitelnsosti sablony pro oneclick alespon v eAPI rozhrani zkusime nekdy technicky probrat — jak efektivni to muze byt. Bude-li to davat alespon trochu smysl, dam vedet kdy se to dostane do pipeline.
