### ISSUE TITLE
Jak udělat registrační oneclick platbu a nestrhnout peníze klientovi z účtu?

### ISSUE THREAD

**Issue by bambooCZ** [csob/paymentgateway#446]
Když udělám registrační oneclick platbu a reversuji jí, tak následně nefungují další oneclick platby.

Když jí nereversuji, tak se strhnou peníze? JAk tomu předejít a docílit tak funkcionality "přidání karty" bez poplatku?

**Comment by bambooCZ** [comment]
Však ano, karta přeci prošla 3DS ověřením už když vznikla blokace. Tedy v okamžiku, kdy se dostala do stavu 4.

**Comment by mrazekl** [comment]
Stav 4 je pouze dočasný stav - autorizováno. Pokud do týdne nedojde k zaúčtování - stav 7, tak se transakce ze stavu 4 a 7 zamítnou dojde ke zrušení blokace.

**Comment by bambooCZ** [comment]
Nejsem z toho nadšený, ale OK. Tedy budeme zákazníkům strhávat 1 Kč. Refundace předpokládám něco stojí, takže do toho nejdeme.
