### ISSUE TITLE
PayId is invalid or expired.

### ISSUE THREAD

**Issue by Radag** [csob/paymentgateway#449]
Dobrý den,

Metoda /payment/process mi na testovacím účtu vrací "PayId 9a090adea8ba1EI is invalid or expired." Nevíte čím by to mohlo být ? Dělá to jenom u konkrétního MerchantId, pokud si vytvořím nové testovací MerchantId, tak to funguje. Nevíte čím by to mohlo být ?

**Comment by RoForst** [comment]
Dobrý den,

požadavek předávám na kolegu.

S pozdravem
Robin Forst

**Comment by mrazekl** [comment]
Dobrý den,
ze včerjšího dne pro merchantID/payID M1MIPS7345/9a090adea8ba1EI je v logu neúspěšný payment/init z důvodu nepovolení oneclick. Pokud chcete tuto metodu využívat, musíte si zažádat v bance(akceptacekaret@csob.cz) o její povolení.
Na to byl navázán payment/process - ale tohle payID bylo zneplatněno viz. výše.

**Comment by petrvacha** [comment]
Dobrý den, občas u nás v testovacím prostředí nastane stejná chyba, která po nějaké odmlce odezní. Metodu oneclick bychom měli mít aktivovanou.

Můžete mi, prosím, napsat v čem je problém např. u této transakce? 

> PayId b4e51b26f66feFE is invalid or expired.
