### ISSUE TITLE
chyba ověření podpisu v response

### ISSUE THREAD

**Issue by jan-oliva** [csob/paymentgateway#45]
Vyrobil jsem certifikáty  pro anonymní vývoj (https://iplatebnibrana.csob.cz/keygen/). Podpis v  Requestu mi funguje, ale ověření podpisu v response se mi nedaří. Řetězec pro ověření sestavuji podle příkladu php knihovny Může být nějaký problém s veřejným klíčem ?

**Comment by ratajskym** [comment]
Dobrý den, jaký je název klíče, který používáte pro ověření odpovědí?

**Comment by jan-oliva** [comment]
Název souboru ?
rsa_A1167HG3xB.pub
Ještě jsem zkoušel generovat novou sadu klíčů a tam je to rsa_A1183g1JMi.pub

**Comment by ratajskym** [comment]
Pochopil jsem to tak, že Vám nefunguje ověření podpisu zprávy, kterou Vám zasílá platební brána. 

Je to tak ?

**Comment by jan-oliva** [comment]
Ano je to tak

**Comment by ratajskym** [comment]
K tomu ale potřebujete veřejný klíč platební brány

https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys

**Comment by jan-oliva** [comment]
hmm to bude asi ten problém, chyba mezi klávesnicí a židlí :) 
díky
