### ISSUE TITLE
Brána nepovolí přesměrování po vytvoření platby

### ISSUE THREAD

**Issue by pilec** [csob/paymentgateway#450]
Dobrý den,

upgradujeme systém a v rámci upgradu přecházíme z api 1.6 na 1.7, ovšem dospěli jsme k následující potíži.

Vše probíhá na bráně pískoviště.

Zatím díky anonymnímu merchant id, jsme schopni založit objednávku přes `payment\init` bohužel však při zavolání `payment\process` dostáváme vaši obrazovku s tímto textem. 

```
Platba nemůže být provedena

Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.
```

Merchant ID: **A4160PMDB4**

podepisujeme řetězec `A4160PMDB4|9076f4ea0aab2EI|20190925173848` který by dle dokumentace i příkladové implementace měl být korektní. A stejnou metodou/certifikáty podepisujeme requesty i na `payment\init`, který prochází korektně. Je prosím možno nasměrovat nás podle vašich logů na to, co děláme špatně?

Děkuji

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován pod: TSGSMIPS-9545 a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem
Miroslav Janek

**Comment by mjanek** [comment]
Dobrý den,
při kontrole logu jsem zjistil, že máte chybu v podpisu viz chyba: 
"Invalid paymentProcess signature for merchant A4160PMDB4", transakce poté expirují. 
Prověřte si sestavení Vašeho podpisu nejprve pomocí funkce echo: [https://github.com/csob/paymentgateway/wiki/eAPI-v1.7#getpost-httpsapiplatebnibranacsobczapiv17echo-](url)
M. Janek

**Comment by pilec** [comment]
Dobrý den,

děkuju za nahlédnutí do logů. 

Z naší strany docházelo k dvojtému enkódování podpisu v url.

Už to funguje. Prosím o zavření issue.
