### ISSUE TITLE
Vyvolání brány v en jazyce

### ISSUE THREAD

**Issue by Musilda** [csob/paymentgateway#452]
Dobrý den, 

chci se zeptat, zda je možné v pluginu pro WooCommerce nastavit angličtinu pro vyvolanou bránu.

**Comment by Mspisar** [comment]
Dobrý den,

zkuste dle následujícího odkazu:

https://github.com/csob/paymentgateway/blob/master/WooCommerce%20Plugin/www/monetWebPay/crypto.php#L8

s pozdravem

Spisar

**Comment by ratajskym** [comment]
Dobrý den @Musilda 

issue zavírám. Věřím, že Vám návod pomohl
