### ISSUE TITLE
Platební brána se nevyvolá po odeslání objednávky

### ISSUE THREAD

**Issue by tomasfrank** [csob/paymentgateway#453]
Dobrý den,

na základě společného telefonátu posílám informace k nastavení brány.

Screen z nastavení WooCommerce, screen s umístěním klíčů na hostingu:

![Screenshot_2019-10-24 WooCommerce settings ‹ IGDFSeminar2020 — WordPress](https://user-images.githubusercontent.com/56974973/67509793-120dd580-f694-11e9-800f-a24244ddc071.png)
![ftp-cesta (1)](https://user-images.githubusercontent.com/56974973/67509798-13d79900-f694-11e9-848c-99b09fc85a1d.PNG)

Produkt je možné vyzkoušet na - https://www.igdfseminar2020.com/produkt/breeders-workshop/
Po potvrzení objednávky nedochází k přesměrování, ale rovnou se dostanu na děkovnou stránku, pokud se vrátím o krok zpět, objeví se notifikace - 

Objednávka v e-shopu je uložená, má ale status zrušené s informací "Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled."

Ještě mě tak napadá, není problém že název je obchodního místa je mathilda.cz ačkoliv web bězí na doméně igdfseminar2020.com ?

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
M. Janek

**Comment by ratajskym** [comment]
Dobrý den, na první pohled vidím, že v kolonce veřejný klíč máte svůj vlastní veřejný klíč, ačkoliv je potřeba tam mít veřejný klíč platební brány (pomocí kterého ověříte zprávy z banky)

Podívejte se sem prosím https://github.com/csob/paymentgateway/tree/master/keys

**Comment by mrazekl** [comment]
Dobrý den,
ještě bych doplnil, aby jste ověřil, jak máte nastavenu stránku pokladny v nastavení pokladny:
![obrazek](https://user-images.githubusercontent.com/21953556/67547262-df4cf700-f6fe-11e9-83bc-f35f336b329b.png)

**Comment by tomasfrank** [comment]
Dobrý den,

klíč jsem tedy nahral veřejný (pub) z GITu, jeho název ponechal stejný a vložil do WooCommerce pluginu. Pro jistotu jsem ještě rozdělil košík a podkladnu na dva kroky, nastavení dle screenu je OK. Avšak brána se stejně nevyvolá.

**Comment by ratajskym** [comment]
Nahrál jste klíč integračního prostředí ? Pro int a prod jsou dva různé klíče

**Comment by mrazekl** [comment]
zkontrolujte klíče jak píše kolega, dále máte ale chybně konfiguraci pokladny. Pokud máte nastavenu stránku checkout, pak je chybně nakonfigurována. Jelikož po odkliknutí objednávky jste směřován k vám do eshopu, nikoli na platební bránu:
https://www.igdfseminar2020.com/**pokladna/order-pay/990/?key=wc_order_pijKPTeZN3ajY** 
při správném nastavení je směrováno na URL jako: 
https://iplatebnibrana.csob.cz/**pay/shop.example.com/b9129516-3f3f-46a0-9037-30b6f84de5ab/**

**Comment by tomasfrank** [comment]
Dobrý den,

@ratajskym Kam přesně bych jej měl nahrát? V návodu zde - https://github.com/csob/paymentgateway/tree/master/WooCommerce%20Plugin
se o nahrávání nikde nepíše. Počítám, že zatím pracuji s integračními klíčem a odkazy. Pokud bych měl mít přístupy do https://iposman.iplatebnibrana.csob.cz což jsem tak pochopil z jiných návodů, tak ty jsem nedostal. Pouze jsem dostal mail, s 3 kroky, merchant ID a odkazem na GIT.

Vygeneroval jsem si klíč přes https://iplatebnibrana.csob.cz/keygen/ oba stáhnul, private nahrál na hosting, s public, který si tam mohu stáhnout ale není jasné co mám dělat, kromě odeslání do banky.

@mrazekl asi nevím co přesně je myšleno "chybně nakonfigurována" přesměrování na platební bránu by měl dle mého názoru zajistit váš plugin když jsem si vybral platební metodu přes platbu kartou pomocí Vaší brány.  Já nemám jinak moc možností, co bych na pokladně mohl ještě změnit.  Pokud třeba aktivuji PayPal, ač bez integračních údajů tak mě to normálně přesměruje na jejich bránu.

**Comment by ratajskym** [comment]
Pošlete prosím zase printscreen Vašeho nastavení

**Comment by tomasfrank** [comment]
https://prnt.sc/ppo8mf

Stejný soubor je nahrán i ve složce s klíčem.

**Comment by mrazekl** [comment]
Dne _October 25th 2019, 17:06:31.937_ jste si generoval nové klíče, tím se zneplatní ty staré. Od té doby vidím jen chybný podpis požadavku. Napřed zkusme vyřešit tento problém, nové klíče, které jste si generoval, nahrejte do složky s wordpressem: 
....xxxx\wordpress\monetWebPay\keys
Zde uložte i stažený klíč mips_iplatebnibrana.csob.cz
Poté zkusíme vyřešit, proč se nepřesměrujete na platební bránu

**Comment by tomasfrank** [comment]
Dobrý den, pro jistotu jsem vygeneroval klíč zcela ještě jednou (žádost č.) a nový private hodil na hosting, veřejný odeslal do banky. Platební brána se neobjeví. Mimochodem, neobjeví se ani, když to celé udělam zcela na čisté WP instalaci, kde je jen WooCommerce a Váš plugin. Podle mě nefunguje plugin s aktuální verzi WooCommerce, potom už mě napadá jen webhosting.  Popř. Vám mohu udělat přístupy na hosting a do administrace, protože už fakt netuším.

**Comment by mrazekl** [comment]
Stále vidím chybu podpisu. Můžete mi, prosím, zaslat aktuální privátní klíč na lmrazek@monetplus.cz a verzi wooccomerce kterou máte nainstalovanou?
Ověřím u sebe lokálně že vše funguje.

**Comment by mrazekl** [comment]
Odzkoušeno a vše funguje i ve verzi 3.7.1
zkontrolujte zda máte správně nastaveno: 
![obrazek](https://user-images.githubusercontent.com/21953556/67860628-a0fc7100-fb1e-11e9-8f46-9fd047e220b9.png)

Váš problém jsem nasimuloval když jsem si chybně nastavil:
![obrazek](https://user-images.githubusercontent.com/21953556/67860676-c4272080-fb1e-11e9-8358-01e5402c557c.png)

všimněte si vyýsledné URL na které jsem skončil namísto platební brány:
![obrazek](https://user-images.githubusercontent.com/21953556/67860839-40216880-fb1f-11e9-806e-2cf05e1dcf0b.png)

**Comment by Kotletnik** [comment]
Dobrý den,
mám stejný problém. V testovacím prostředí vše chodilo, nasměrovalo mě to na platební bránu a mohl jsem provádět a testovat platby. Po změně na komerční prostředí se mi nasměruje web na shrnutí objednávky bez možnosti platby. 
![image](https://user-images.githubusercontent.com/58329704/69863602-8cd29d80-129d-11ea-8f36-5c47a0321259.png)
Klíče jsem stáhl znovu, znovu nahrál, poslal do banky. Stále nefunkční. Už si nevím rady :) Nastavení WooCommerce:
![image](https://user-images.githubusercontent.com/58329704/69863714-c1465980-129d-11ea-97cb-3e6a1cede297.png)
Předem děkuji za pomoc :)
