### ISSUE TITLE
Problem pri volani reverse nebo refund na iapi

### ISSUE THREAD

**Issue by msquare-fejfar** [csob/paymentgateway#454]
Dobry den

 bohuzel pro dokonceni testu potrebujeme provolat uspesne reverse sluzbu. Bohuzel pri volani to vraci vzdy tuto chybu - The remote server returned an error: (405) Method Not Allowed.

 Volana adresa je https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/reverse a MerchantId = M1MIPS5983.

 prosim o co nejrychlejsi vyrizeni - chteli bychom jit do produkce.

 dekuji

**Comment by mrazekl** [comment]
Dobrý den,
nepodařilo mi dohledat vaše pokusy, které takto končí. Mohl by jste uvést log požadavku, popřípadě číslo objednávky či variabilní symbol nebo datum?
Zatím můžu poradit, zkontrolujte zda používáte správnou metodu volání, v těchto případech(změna stavu) musí být použita metoda PUT.

**Comment by msquare-fejfar** [comment]
{"merchantId":"M1MIPS5983","payId":"92beccad9e4e4EJ","dttm":"20191030122246","signature":"OO\/euCRKl44bT2c8cU+rmw+aHjdEwSetdxALwa1wzHYfSc7zDwxRpgxfeRe5Y\/1fdwHIo4TNtFu4LWN2OKXPkfLe39N5EJiB1y0voDnxdqb\/9QfV7CRynwfGhqZrW7k+Je\/+UOcjlLBlxS+2s0XBSuQ3bX4YJZrI3+mmmAWJHnpIcXSGSqsTq2tedKQxxt\/wpjau8HXl74Yl\/2463BT661huY9ezZ9HHfWi31xPCjM8mPgouvTM5VwFhfR4byCOsr75Zquc3nvzsKDeNx9lBaH0dEIWPtod2PuWZ3uva1iWJDY4uawmfq\/FadVIW4fjbRX+q\/JN+Lp1eCwizQf1QxQ=="}

The remote server returned an error: (405) Method Not Allowed.

**Comment by mrazekl** [comment]
tahle transakce je autorizovaná, ve stavu 4, lze tedy reverzovat
je však nutné zaslat metodu na reverzal typu PUT, to je důvod proč se vám vrací Method not Allowed

**Comment by msquare-fejfar** [comment]
Funguje to - dekuji. Spis nerozumim tomu proc pro init/process je to pres POST a tady pres PUT. Ale ok, hlavne ze to je funkcni.

**Comment by ratajskym** [comment]
Payment proces transakci vytváří, reversal stav transakce updatuje

> Generally, in practice, always use PUT for UPDATE operations. Always use POST for CREATE operations.
