### ISSUE TITLE
HTTP kód 405 u payment/reverse 

### ISSUE THREAD

**Issue by bubilem** [csob/paymentgateway#455]
V testovacím prostředí v1.7 u operace payment/reverse mi brána odpovídá 405 a {"resultCode":900,"resultMessage":"Internal error"}. 

Pro reverse dotaz mám připravená POST data: {"merchantId":"xxx","payId":"xxx","dttm":"20191101095347","signature":"xxx"}

Používám curl v PHP. Data posílám metodou POST. Kódování UTF-8.

Zkoušel jsem to u plateb ve stavu 4 i 7.

Operace echo, payment/init mi pracují OK. Na bráně lze bez problémů objednávku zaplatit, stornovat... Nelze ji však reverzovat.

Kde bych měl prosím hledat chybu?

**Comment by LucieSnedarova** [comment]
Dobrý den, 
Váš požadavek byl předán na odpovědného kolegu.
S pozdravem
Lucie Šnédarová

**Comment by LucieSnedarova** [comment]
Dobrý den,
při volání používáte metodu POST, v tomto případě to musí být metoda PUT.
Zasílám odkaz, kde byl řešen stejný problém: https://github.com/csob/paymentgateway/issues/454

**Comment by bubilem** [comment]
Problém vyřešen. Děkuji.
