### ISSUE TITLE
implementace platebni brany pres CSOB SK

### ISSUE THREAD

**Issue by STUDIOTyna** [csob/paymentgateway#457]
Dobrý den, 

u CSOB jsem si zridila dve platebni brany. Jedna by měla být bez problémů (implementuje ji můj dodavatel) a druhou se zdá , že nebude možné nastavit. 
Jelikož si ale nejsem jistá, tak se raději ptám přímo Vás. 

Jedná se o platební bránu Merchant ID: M1MIPS7596 k e-shopu na stránkách studiotyna.cz, spole. Chci se hýbat, kontaktní email: k.zrckova@gmail.com.
Stránky jsem vytvářela v šablonách webnode. Když jsem se marně pokoušla platební bránu nastavit, všimla jsem si, že webnode sice spolupracuje s CSOB, ale jen s CSOB SK.
Je možné tento problém nějak vyřešit a nebo mám tuto platební bránu pro e-shop zrušit? 

Přikládám ještě odkaz ze stránek webnode. https://www.gpwebpay.cz/Order#anch2 

Děkuji 

Kristýna Zrcková

**Comment by mrazekl** [comment]
Dobrý den,
dle Vašeho přiloženého odkazu se opravdu nejedná o platební bránu ČSOB, ale jiného poskytovatele služeb.
S její implementací Vám z pochopitelných důvodů nemáme jak poradit. Na jednom e-shopu můžete využít i více MerchantID, záleží na Vašich požadavcích a možnostech. Zrušení jednoho ID po technické stránce nijak neovlivňuje druhé ID.
