### ISSUE TITLE
Platební brána Fastcentrik

### ISSUE THREAD

**Issue by romgaj** [csob/paymentgateway#458]
Dobrý den,
 
Píši ze společnosti NetDirect, která nabízí pronájem eshopů. Jako krabicové řešení FastCentrik máme implementovanou platební bránu ČSOB.
Kontaktoval mne nás společný klient:
společnost : ROMMAR s.r.o.
 
Bohužel pan Gaj se potýká s obtížemi v rámci propojení platební brány a eshopem. Poprosil mne abych danou situaci nějak vyřešil.
Jelikož jsme krabicové řešení, platební brána je pro všechny naše klienty stejná, a tedy není pravděpodobné, že by ostatním našim klientům platební brána běžela v pořádku a tomuto novému klientovi házela chybu. 
Chyba hlásí, že se nedokáže spojit s vašim serverem. Předpokládám tedy, že se bude jednat pouze o špatné identifikační klíče a hodnoty, které k nám klient vkládá.

Bylo by možné z vaší strany prosím překontrolovat:
Zda-li je u vás vše v pořádku povoleno?
Zda-li je brána aktivní a případně zda-li klient má u sebe správná data pro vložení do administrace eshopu?

U nás je platební brána nastavena na testovací režim.
Identifikace obchodníka je vložena jako hodnota: M1MIPS7587
 
Dále se k nám vkládá Veřejný a Soukromý klíč, který by vám klient případně přeposlal ke kontrole.
Pokud bude potřeba mohu vám zaslat demoverzi, na které si budete moct implementaci vyzkoušet.

Děkuji za prověření.
 
S přáním hezkého dne

Daniel Herrmann
Customer Care Team Leader
Daniel.herrmann@netdirect.cz

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem
Miroslav Janek

**Comment by mjanek** [comment]
Dobrý den, 
opravdu se jedná o chybný podpis platební brány "**Invalid paymentInit signature for M1MIPS7587**". Ať si klient vygeneruje testovací klíče a přepošle Vám je. Po provedení testů bude potřeba tyto klíče změnit na produkční. Platební brána pro www.RMeshop.cz je v integračním rozhraní aktivní a je připravena na testování.

**Comment by mjanek** [comment]
V aplikačním logu jsem také našel chybu "**merchant key for M1MIPS7587 not found**" Je potřeba, aby vygenerované testovací klíče uložil a odeslal veřejný klíč do banky.  
![obrazek](https://user-images.githubusercontent.com/22815840/68413581-ce849280-018e-11ea-9e1c-b8c40bf0e1e2.png)

**Comment by romgaj** [comment]
Dobrý den, 
tak jsem vygeneroval nové klíče, vložil do administrace e-shopu a provedl odeslání (žádost č.7359), což jsem dělal i v předešlém (myslím, že č. žádosti bylo 7357).
A opět nedošlo k přesměrování na platební.
Je možné prověřit, kde je tedy chyba ?
Roman Gaj

**Comment by mrazekl** [comment]
Dobrý den, 
s klíči problém není, ověřil jsem v databázi. K přesměrování na platební bránu dojde, zatím ale jen back-endem a končí na chybu podpisu.
V požadavku posíláte prázdnou hodnotu **"extensions":[]** , přitom žádné rozšíření aktivováno nemáte. Inicializujte payment/init bez toho rozšíření.

**Comment by romgaj** [comment]
Dobrý den, 
takže toto může jen odstranit poskytovatel e-shopového řešení ?
Roman Gaj

**Comment by mrazekl** [comment]
Dobrý den,
jedná se o rozšíření samotného payment/init volání viz: 
https://github.com/csob/paymentgateway/wiki/koncept-API-roz%C5%A1%C3%AD%C5%99en%C3%AD#koncept-roz%C5%A1%C3%AD%C5%99en%C3%AD-api-extensions
Skládání celkového payment/init bude ukryto někde v kódu FastCentriku odhaudji, proč je přidaná i tato hodnota nemám tušení. Zkuste se zeptet pana Herrmanna jaké jsou možnosti.
Ostatní data vypadají v pořádku.

**Comment by romgaj** [comment]
Dobrý den,
takže situace se nijak nepohnula a nadále je problém asi někde uprostřed.
Opět jsem znovu vygeneroval nové klíče uložil a pak odeslal veřejný do banky.
Vložil jsem do administrace e-shopu, vytvořil jsem zkušební objednávku a nedošlo k přesměrování na platební bránu.
Je možné, že je z naši strany něco špatně zadáno anebo stále je problém na straně e-shopu v kódu?
Od nich je prý vše v pořádku a ostatní klienti prý nemají problém a funguje jim brána bez problému.

**Comment by mrazekl** [comment]
Dobrý den,
ověřil jsem vaše včerejší pokusy.
V poli "description":"200129 - RMeshop | prodej nářadí" používáte znak "pipe" | , který slouží zároveň jako oddělovač v řetězci pro podpis.
Můžete upravit tento popis aby byl bez tohoto znaku a zkusit zopakovat?

**Comment by romgaj** [comment]
Dobrý den, 
tak jsem provedl novou objednávku a opět nedošlo k přesměrování na bránu.

**Comment by romgaj** [comment]
a není problém, že máme dva e-shopy na každý je zřízená brána a jsme pod jedním IČO akorát jsou jiné názvy ?

**Comment by mrazekl** [comment]
Dnešní pokus byl odeslán na produkci, kde zatím nejste aktivní. Změňte adresu brány na testovací prostředí https://iapi.iplatebnibrana.csob.cz...

**Comment by romgaj** [comment]
tak jsem provedl další dvě testovací objednávky a žádná změna

**Comment by mrazekl** [comment]
stále se odkazujete na produkční prostředí, jakou máte nastavenu adresu platebnií brány?

**Comment by romgaj** [comment]
prověřím to u poskytovatele e-shopu

**Comment by mrazekl** [comment]
včera na testovacím prostředí vidím dva pokusy v časech 16:19:22 a 16:20:58
dnes zatím ani jeden
