### ISSUE TITLE
Životnost transakce

### ISSUE THREAD

**Issue by hvitek** [csob/paymentgateway#459]
Dobrý den,
Životnost transakce, stastavená paramentrem ttlSec, se počítá již od volání payment/init nebo od payment/proccess?

Děkuji 
VH

**Comment by Mspisar** [comment]
Dobrý den,
požadavek byl zaevidován a předán k řešení. Odpovědný technik Vás bude informovat ihned jakmile to bude možné. 
s pozdravem
Spisar

**Comment by mrazekl** [comment]
Dobrý den,
odpočet začíná již payment/init a u většiny plateb může být 300 - 1800 sekund.
Vyjímkou je platba na míru a mallpay platby, kde je z pochopitelných důvodů nastavena životnost v řádu dnů.
