### ISSUE TITLE
api 1.8 a mall pay

### ISSUE THREAD

**Issue by radovanx** [csob/paymentgateway#460]
Dobrý den,
Integrujeme api verze 1.8.

Při použití anonymního klíče pro testy se při zavolání endpoint  https://iapi.iplatebnibrana.csob.cz/api/v1.8/mallpay/init vrací chyba 400.
Nejčastěji se nám to stává u brány ČSOB při špatném klíči. Můžete mi prosím potvrdit že je možné používat tento klíč nebo zaslat testovací který bude fungovat ?
Přikládám ukázku volání brány u které se vrací tato chyba - v dokumentaci je také 
https://github.com/csob/paymentgateway/wiki/Metody-pro-Mall-Pay#mallpay-init-operation
položka 
purchaseId
v příkladu ale již není uvedena v tabulce zda je povinná nebo ne.

data to sign:
"A4233Y6Feq|123456|ZA0019S51966-1|Adam|Malý|+420800300300|adam.maly@example.com|1000000|CZK|210000|CZK|21|BILLING|Radlická 333|Praha 5|15000|CZ|ABC123|iPhone 8S|1000000|CZK|210000|CZK|21|false|20191110222631|86.49.3.29|https://vasobchod.cz/gateway-return|POST"

prepared payment/init request:
{
    "merchantId": "A4233Y6Feq",
    "orderNo": "123456",
    "purchaseId": "ZA0019S51966-1",
    "customer": {
        "firstName": "Adam",
        "lastName": "Malý",
        "phone": "+420800300300",
        "email": "adam.maly@example.com"
    },
    "order": {
        "totalPrice": {
            "amount": 1000000,
            "currency": "CZK"
        },
        "totalVat": [
            {
                "amount": 210000,
                "currency": "CZK",
                "vatRate": 21
            }
        ],
        "addresses": [
            {
                "addressType": "BILLING",
                "streetAddress": "Radlická 333",
                "city": "Praha 5",
                "zip": "15000",
                "country": "CZ"
            }
        ],
        "items": [
            {
                "code": "ABC123",
                "name": "iPhone 8S",
                "totalPrice": {
                    "amount": 1000000,
                    "currency": "CZK"
                },
                "totalVat": {
                    "amount": 210000,
                    "currency": "CZK",
                    "vatRate": 21
                }
            }
        ]
    },
    "agreeTC": false,
    "dttm": "20191110222631",
    "clientIp": "86.49.3.29",
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "returnMethod": "POST",
    "signature": "qhP8dB56hqLk7+Z1iO/d9q/D1ijp05McDwgpthsLbIk/ZIr2oMzLs41WczjLbqlcvdRDQ/FKX8jrI6PD8ho1lDtx24mgaCdLTg7cliJpyjnba/L5FyKmvzzvra2txttR9pe5pXZuPghm7e6vKaccT8DtUN6JAjE/HvOOmqqzYW7WvCTqGboHsvir2jnrMwXcmCtkqu84z2ptTulN5vcvm/jA5SFxC0gJ1A0hg9rym+A2uMN6F1zn61O8wcHpnWNWQE+obFuUukG6VH4QPt45aTa1BibYHvGcq89/N6jjeqIlwiGrzJ8ejOu2ymD0MUDccJmpnCl3Ktd5SqV6pBCA/w=="
}

processing payment/init request ...

'https://iapi.iplatebnibrana.csob.cz/api/v1.8/mallpay/init' (length=57) 
payment/init failed, http response: 400

**Comment by RoForst** [comment]
Dobrý den,

Váš dotaz jsem předal na kolegu.

**Comment by dmarek** [comment]
Dobrý den,
purchaseId jsme z examplu volani `mallpay/init` odstranili, nemá tam být. Zkuste prosím bez něj ...

**Comment by radovanx** [comment]
Dobrý den,
Děkuji za odpověd, bohužel i při odstrenění purchaseId volání vrací 400
Není opravdu problém v použití anonymního klíce ?


data to sign:
"A4233Y6Feq|123456|Adam|Malý|+420800300300|adam.maly@example.com|1000000|CZK|210000|CZK|21|BILLING|Radlická 333|Praha 5|15000|CZ|ABC123|iPhone 8S|1000000|CZK|210000|CZK|21|false|20191115102450|86.49.3.29|https://vasobchod.cz/gateway-return|POST"

prepared payment/init request:
{
    "merchantId": "A4233Y6Feq",
    "orderNo": "123456",
    "customer": {
        "firstName": "Adam",
        "lastName": "Malý",
        "phone": "+420800300300",
        "email": "adam.maly@example.com"
    },
    "order": {
        "totalPrice": {
            "amount": 1000000,
            "currency": "CZK"
        },
        "totalVat": [
            {
                "amount": 210000,
                "currency": "CZK",
                "vatRate": 21
            }
        ],
        "addresses": [
            {
                "addressType": "BILLING",
                "streetAddress": "Radlická 333",
                "city": "Praha 5",
                "zip": "15000",
                "country": "CZ"
            }
        ],
        "items": [
            {
                "code": "ABC123",
                "name": "iPhone 8S",
                "totalPrice": {
                    "amount": 1000000,
                    "currency": "CZK"
                },
                "totalVat": {
                    "amount": 210000,
                    "currency": "CZK",
                    "vatRate": 21
                }
            }
        ]
    },
    "agreeTC": false,
    "dttm": "20191115102450",
    "clientIp": "86.49.3.29",
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "returnMethod": "POST",
    "signature": "O38/d9rFzk4aSfmfaoQ0ul64GYeHksA2pItoUFTfu/nFhMcIEhLKeS2yPYRy/Lwe7AnHGHTgYB3O6lYL+iIfU2Vl0M4dcjYTwdJYxckoqXubir1Q2Cj6vCo/KWYH8ZSCFGJFtVTc3LB00TyNFFGqlCrmw7aWpwqzZIUBZ+pvHDlXObClSIJPbx5a/zjFxlS9uo3J5wGMIpDgHJOPjLJ2oToodxCgaHtk8ecu1I3dboLve/9v3EIBb5iKAA+RSNOFSEcEBz/rhn3xNB+GvKZvlPPexkb15FkRCmuyISB8tUQ7C50YANvdpsA0GGzpJwM+pIzAMnSlF40IE2FMosqQJw=="
}

processing payment/init request ...

/Applications/XAMPP/xamppfiles/htdocs/paymentgateway/Integration Examples/eAPI v1.8/php/init-result.php:63:string 'https://iapi.iplatebnibrana.csob.cz/api/v1.8/mallpay/init' (length=57)
payment/init failed, http response: 400

**Comment by mrazekl** [comment]
Dobrý den,
http response: 400 odpovídá chybě podpisu, s anonymním ID nemá nic společného.
Jakým způsobem máte zašifrovaný podpis? U mall pay a vlastně celé eAPI1.8 je změna v algoritmu, nově se používá SHA256withRSA.
Dále by mohl problém způsobovat řetězec pro podpis, pokud by v něm po odtranění parametru purchaseId zůstala "pipe" (znak | ) navíc.

**Comment by radovanx** [comment]
Dobry den,

Děkuji příklad volání který by měl být stejný jako váš příklad přikládám.
CSOB brána funguje v pořádku v šifrování by tedy problém být neměl.

Níže volání na https://iapi.iplatebnibrana.csob.cz/api/v1.8/mallpay/init vrací odpověd 400

data to sign:
"A4256nLzbb|123456|Adam|Malý|+420800300300|adam.maly@example.com|100000|CZK|21000|CZK|21|BILLING|Radlická 333|Praha 5|15000|CZ|ABC123|iPhone 8S|100000|CZK|21000|CZK|21|true|20191120224003|192.0.2.2|https://vasobchod.cz/gateway-return|POST"

prepared payment/init request:
{
    "merchantId": "A4256nLzbb",
    "orderNo": "123456",
    "customer": {
        "firstName": "Adam",
        "lastName": "Malý",
        "phone": "+420800300300",
        "email": "adam.maly@example.com"
    },
    "order": {
        "totalPrice": {
            "amount": 100000,
            "currency": "CZK"
        },
        "totalVat": [
            {
                "amount": 21000,
                "currency": "CZK",
                "vatRate": 21
            }
        ],
        "addresses": [
            {
                "addressType": "BILLING",
                "streetAddress": "Radlická 333",
                "city": "Praha 5",
                "zip": "15000",
                "country": "CZ"
            }
        ],
        "items": [
            {
                "code": "ABC123",
                "name": "iPhone 8S",
                "totalPrice": {
                    "amount": 100000,
                    "currency": "CZK"
                },
                "totalVat": {
                    "amount": 21000,
                    "currency": "CZK",
                    "vatRate": 21
                }
            }
        ]
    },
    "agreeTC": true,
    "dttm": "20191120224003",
    "clientIp": "192.0.2.2",
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "returnMethod": "POST",
    "signature": "jK1m1U9/16MGmmpXSeCC3AWFJOZ9OWrlHnSFbcXTc6XbkXJk65M0q3tugIhbBRX3++yO6FwkFpnjgmr+dttc8iWbH16KvzRxpuR/fYKtSnjucfyBLbd3WozrHCC+q3admT6JoF8ZLkKhetUmcdWX5OHg7dVYa+lzC3Ik/3JVOiu6MrLgl32SeX9PbsEVUJpH2M9pODjZDwnzLftdvvx2A65/R3mJS2L7HF0LrN6ARshq+Tvjk8scXRTMfvMAAzN2c8egyqxm8q8o+JEWVsfjHR6lUuKp4svimEW+DT7npLWLHoLSxl3z6YXKeJW7Z/QLY2poAsbsBVM6YBez8RUaVA=="
}

**Comment by mrazekl** [comment]
Dobrý den,
zkusil bych se vrátit na začátek. 
Vidím pouze pokusy na mallpay/init, ty končí chybným podpisem.
Jste schopen provést metodu echo na eAPI1.8 , abychom ověřili použité klíče a šifrování?
viz: https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody#metoda-echo-

**Comment by radovanx** [comment]
Dobry den,
Ano, jak jsem psal bezna platba kartou CSOB funguje. Níže posílám test echo.

http method: GET
gateway url: https://iapi.iplatebnibrana.csob.cz/api/v1.8/echo/A4256nLzbb/20191122010349/SfPew92Fg1kE6X9cT4FGKBHX8sHO4B4jc3GjDFmL9p0rOmisI2kA2Rlw5Cx7siyknySR5CKDb6%2BFbD2PkUqxVKlVS1DQs%2FNs6svGzBKwyGAIStkfE70E%2FBusd2wcjpUh75I%2FXLJwMk9ESRFL%2BRtEQ%2FDAdKDEFV0ZkInfumoW%2FjuQi9w4xCyM2UleWNk0nGlrvaWs6LekQIuJ3JpUo0IjJ%2B11nVUp3s8x3l3h2xLcU1KME%2FhAZPgwT8Ex8X9s8RXMTscT9jepY5wNsG502bGJjm8SPtcAbtbBjJ4V0LWNJwyaQsIZi5GYUbgeyom3mvviWBeptnJlY0BYqO2hCId%2FFA%3D%3D

http status: 200

response: {"dttm":"20191122010350","signature":"Q4CPXqEpe1Z4H24jGNQela3bm2hyOfr41Kj8YhFNXSuznaaB1ScEkcBGef9ABVPMwdcnly9JbxG15r9+By31+hTyyOki/8kqTF3/nBuXwzoWVQSwKErnigKiBO9ggxWpQ13azHkUNpWWEQD0dzB5aRN5Jyn+JV1yCQ0Y5h+WvZcW9YC644WKZn02EVvBY88nU6bW640ZKflrl5nBnxTdX6UAozFp+I1Mfho54Au8s6lrkxacWXnWbsiQtwEFBPI8xusVXwJANU24/0WhrTT0abSYDgOAfEw9JXjKeI+HtCONIRDPvyM2BH4ZIxGAUpvBlxMHGg82dCfsnCjLYl6P+Q==","resultCode":0,"resultMessage":"OK"}

**Comment by mrazekl** [comment]
Dobrý den, 
problém může být v diakritice, v logu je vidět že zasíláte diakritické znaky převedené na jiné znaky, viz log:

Payload: {"merchantId":"A4256nLzbb","orderNo":"123456","customer":{"firstName":"Adam","lastName":"**Mal\u00fd**","phone":"+420800300300","email":"adam.maly@example.com"},"order":{"totalPrice":{"amount":100000,"currency":"CZK"},"totalVat":[{"amount":21000,"currency":"CZK","vatRate":21}],"addresses":[{"addressType":"BILLING","streetAddress":"**Radlick\u00e1** 333","city":"Praha 5","zip":"15000","country":"CZ"}],"items":[{"code":"ABC123","name":"iPhone 8S","totalPrice":{"amount":100000,"currency":"CZK"},"totalVat":{"amount":21000,"currency":"CZK","vatRate":21}}]},"agreeTC":true,"dttm":"20191120224003","clientIp":"192.0.2.2","returnUrl":"https:\/\/vasobchod.cz\/gateway-return","returnMethod":"POST","signature":"jK1m1U9\/16MGmmpXSeCC3AWFJOZ9OWrlHnSFbcXTc6XbkXJk65M0q3tugIhbBRX3++yO6FwkFpnjgmr+dttc8iWbH16KvzRxpuR\/fYKtSnjucfyBLbd3WozrHCC+q3admT6JoF8ZLkKhetUmcdWX5OHg7dVYa+lzC3Ik\/3JVOiu6MrLgl32SeX9PbsEVUJpH2M9pODjZDwnzLftdvvx2A65\/R3mJS2L7HF0LrN6ARshq+Tvjk8scXRTMfvMAAzN2c8egyqxm8q8o+JEWVsfjHR6lUuKp4svimEW+DT7npLWLHoLSxl3z6YXKeJW7Z\/QLY2poAsbsBVM6YBez8RUaVA=="} 

to může způsobovat například client, kterého používáte. Můžete vyzkoušet zaslat data bez diakritiky,zda se podpis zvaliduje?

**Comment by radovanx** [comment]
Test bez diakritiky vrací také 400

data to sign:
"A4256nLzbb|78945|Adam|Novak|+420800300300|adam.maly@example.com|100000|CZK|21000|CZK|21|BILLING|Radlicka 333|Praha 5|15000|CZ|ABC123|iPhone 8S|100000|CZK|21000|CZK|21|true|20191122141102|192.0.2.2|https://vasobchod.cz/gateway-return|POST"

prepared payment/init request:
{
    "merchantId": "A4256nLzbb",
    "orderNo": "78945",
    "customer": {
        "firstName": "Adam",
        "lastName": "Novak",
        "phone": "+420800300300",
        "email": "adam.maly@example.com"
    },
    "order": {
        "totalPrice": {
            "amount": 100000,
            "currency": "CZK"
        },
        "totalVat": [
            {
                "amount": 21000,
                "currency": "CZK",
                "vatRate": 21
            }
        ],
        "addresses": [
            {
                "addressType": "BILLING",
                "streetAddress": "Radlicka 333",
                "city": "Praha 5",
                "zip": "15000",
                "country": "CZ"
            }
        ],
        "items": [
            {
                "code": "ABC123",
                "name": "iPhone 8S",
                "totalPrice": {
                    "amount": 100000,
                    "currency": "CZK"
                },
                "totalVat": {
                    "amount": 21000,
                    "currency": "CZK",
                    "vatRate": 21
                }
            }
        ]
    },
    "agreeTC": true,
    "dttm": "20191122141102",
    "clientIp": "192.0.2.2",
    "returnUrl": "https://vasobchod.cz/gateway-return",
    "returnMethod": "POST",
    "signature": "FrmxEy3sGnPf68VUOpNqgEE6MSIGuRlaO7mF48D0cPybSsuverKJuiZ0wwRWtmRvThvrxd7+FS5eGPlPXtaoSZO/5yYPnMEzGAP8uWItqA6JDOhuj7WxWDWsSEAdCO7AWGQHAzUC9KZ7f2Qfq2ljmXyGVxWpNtuJ5k7nsV65pQ7nORMgXV1v+zJvcvN4o69jR6LGmSZI2KzhGcm/DfmTSMiTA3JAf2q1FT1MS2bg/vU/dWVMoGXb5tknAubyWxTKokacPmQhkWb17ibAwaJpqqZ4SEb4pwQEugwC+Hr8UynagrmWsQvK9I+ulpAYGHBvvBkHoN0v/+3JYKxJuRz1oA=="
}

processing payment/init request ...
'https://iapi.iplatebnibrana.csob.cz/api/v1.8/mallpay/init' 
payment/init failed, http response: 400

**Comment by mrazekl** [comment]
Dobrý den,
ještě je zde jeden rozpor a to u parametru returnUrl, 
podepisujete: https://vasobchod.cz/gateway-return 
ale na platební bránu odesíláte: https:\/\/vasobchod.cz\/gateway-return
Můžete vyzkoušet podepsat požadavek s tímto tvarem, popřípadě vypátrat, kde dochází ke záměně symbolů lomítka?

**Comment by radovanx** [comment]
Dobrý den,

Stejný výsledek,
ve vaší správě nění vidět rozdíle mezi https://vasobchod.cz/gateway-return a https://vasobchod.cz/gateway-return

**Comment by mrazekl** [comment]
Můžete nám poslat soubor vašeho privátního klíče na servis@monetplus.cz?
Abychom si nasimulovali zvalidování podpisu při zadání stejných dat.

**Comment by radovanx** [comment]
Děkuji,
email zaslán na  servis@monetplus.cz
