### ISSUE TITLE
MALL Pay API 1.8 - validace předávaných hodnot

### ISSUE THREAD

**Issue by tomasremek** [csob/paymentgateway#462]
Dobrý den,

zjistili jsme, že některé limity pro délku přenášených parametrů (adresa, jméno, název položky apod.) jsou pro některé záznamy z naší db nedostačující.
Například v adrese název města "Kostelec nad Černými lesy" -> služba vrátí chybu. Proto jsme nuceni zkrátit na tvar odpovídajícím limitům (získaných metodou pokus/omyl, protože v dokumentaci jsme nenašli). 
Dle komunikace s kolegy s mallpay se jedná o chybu.

Nyní v případě delšího názvu necháváme poslední celé slovo, které se do limitu vejde a za něj dáme tři tečky. Na příkladu města (limit 20znaků) tedy posíláme "Kostelec nad..."

Děkuji.

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem
Miroslav Janek

**Comment by mrazekl** [comment]
Dobrý den,
aktuálně tento případ, stejně jako dotaz z issue #462 řešíme s protistranou v mallpay. 
Z největší pravděpodobností dojde k úpravě na straně platební brány.
