### ISSUE TITLE
MALL Pay API 1.8 - položka s DPH 0 %

### ISSUE THREAD

**Issue by comnet-s-r-o** [csob/paymentgateway#463]
Při testech jsem narazil na problém, který se mi nedaří najít v dokumentaci ani obejít vypuštěním položky:

**prodej zboží osvobozeného od DPH**

Zpracovávám stejně jako položky, které mají nenulovou sazbu:

```
    "order": {
        ...
        "totalVat": [
            {
                "amount": 0,
                "currency": "CZK",
                "vatRate": 0
            }
        ],
        "items": [
            {
                ...,
                "totalVat": {
                    "amount": 0,
                    "currency": "CZK",
                    "vatRate": 0
                }
            },

```
Brána mi odpoví: Invalid 'amount' parameter, must be positive

Pokud nastavím order.totalVat[].amount = 1 i order.items[].totalVat.amount = 1, pak to projde.

Pokud při nulové sazbě vypustím nulový order.totalVat[], pak dojde k chybě Missing order/totalVat (vypuštění nulového order.totalVat[] funguje, pokud je v zakázce nějaká položka s dph>0 a order.totalVat[] tak není prázdný)

Pokud při nulové sazbě vypustím order.items[].totalVat, pak dojde k chybě Missing 'orderItem/totalVat' parameter

Je povoleno přes platební bránu prodávat zboží osvobozené od DPH? Pokud ano, dělám něco špatně nebo je špatně kontrola na straně platební brány?

**Comment by RoForst** [comment]
Dobrý den, 

dotaz jsem předal na kolegu.

S pozdravem 
Robin Forst

**Comment by mrazekl** [comment]
Dobrý den,
zjišťujeme možnosti. Pravděpodobně dojde k úpravě na straně platební brány.

**Comment by Rosnicka** [comment]
Dobrý den, je zde nějaký posun?
