### ISSUE TITLE
Přesměrování na platební bránu se nezdařilo

### ISSUE THREAD

**Issue by Kotletnik** [csob/paymentgateway#464]
Dobrý den,
Po odeslání objednávky se mi eshop nepřesměruje na platbu. V testovacím prostředí vše chodilo, nasměrovalo mě to na platební bránu a mohl jsem provádět a testovat platby. Po změně na komerční prostředí se mi nasměruje web na shrnutí objednávky bez možnosti platby. 
![image](https://user-images.githubusercontent.com/58329704/69863602-8cd29d80-129d-11ea-8f36-5c47a0321259.png)
Klíče jsem stáhl znovu, znovu nahrál, poslal do banky. Stále nefunkční. Už si nevím rady :) Nastavení WooCommerce:
![image](https://user-images.githubusercontent.com/58329704/69863714-c1465980-129d-11ea-97cb-3e6a1cede297.png)
Předem děkuji za pomoc :)

**Comment by mrazekl** [comment]
Dobrý den,
něco se muselo změnit v nastavení. Předpokládám, že i kdyby jste přenastavil zpět do integračního prostředí, výsledek bude stejný.
Zaměřte se na nastavení: 
![obrazek](https://user-images.githubusercontent.com/21953556/69865532-a970d480-12a1-11ea-9655-21b868a9b3a4.png)
a taky zda jste neupravoval jednotlivé stránky.
Popřípadě to může způsobovat i zásah do souboru crypto.php jako vpřípadě issue #453

**Comment by Kotletnik** [comment]
Dobrý den,

do ničeho jsem právě nezasahoval. Vše jelo jak má, až do okamžiku, kdy 
se překlopilo na komerční prostředí :( Nastavení mám správné (viz. 
příloha), to jsem taky kontroloval. Mohu Vám dát přístupy, pokud budete 
chtít a ochoten mi pomoct.

-- 
S přáním pěkného dne
Ivan Kotleba
Tel.: 777 068 998
E: kotleba@webkrom.cz
W: www.webkrom.cz

Dne 2019-11-29 12:15, mrazekl napsal:

**Comment by mrazekl** [comment]
Dobrý den, 
ještě před zasláním údajů, překontrolujte soubor crypto.php jestli nějakým nedopatřením nebyl změněn.
Přikládám funkční podobu(pokud jej budete chtít použít, musíte změnit koncovku na crypto.php):
[crypto.txt](https://github.com/csob/paymentgateway/files/3905223/crypto.txt)

**Comment by Kotletnik** [comment]
Dobrý den,
tak to vypadá, že drobné odchylky zde jsou. Respektive hodně odchylek :D
![image](https://user-images.githubusercontent.com/58329704/69870664-f1e3be80-12b0-11ea-8cd5-4f41c4618fd7.png)

**Comment by mrazekl** [comment]
Tohle se týká košíku, můžete zkusit upravit, zda bude mít vliv. jen podotýkám, že tento crypto.txt je pouze vzorový a je upraven jen pro zasílání jedné položky v košíku.
pokud by jste chtěl vzorový originál, měl by vypadat nějak takto:
[crypto.txt](https://github.com/csob/paymentgateway/files/3905307/crypto.txt)

**Comment by Kotletnik** [comment]
Pokud byste byl tak hodny a sam porovnal to, co mam ja a co by melo byt, prikladam svuj soubor :)

[crypto_moje.txt](https://github.com/csob/paymentgateway/files/3905314/crypto_moje.txt)

**Comment by mrazekl** [comment]
nejjednoduší je kdybyste si tento soubor stáhl, přejmenoval na crypto.php a nahradil ve složce monetWebPay a zkusil inicializovat platbu

**Comment by Kotletnik** [comment]
To jsem ted vyzkousel a stale stejne :( Muzete vyzkouset na https://plenkykm.cz 
Snad mam vsechny soubory jak maji byt :)
![image](https://user-images.githubusercontent.com/58329704/69871915-53f1f300-12b4-11ea-9fd0-e4fb8de26055.png)

**Comment by mrazekl** [comment]
Tak řešení je mnohem jednodušší, než jsme hledali.  Napřed jsem to přehlížel, odstraňte poslední lomítko z url platební brány a mělo by to fungovat :-)

**Comment by Kotletnik** [comment]
Tak toto jsem necekal, opravdu :D Strasne moc Vam dekuji!!!! :) Kde Vas mohu ohodnotit? :D

**Comment by mrazekl** [comment]
Hodnotit netřeba, hlavně že se podařilo vyřešit :-)

**Comment by Kotletnik** [comment]
Ja myslim, ze by se melo hodnotit za rychly a kladny a prijemny pristup :) Jeste jednou moc dekuji :)
