### ISSUE TITLE
Zamítnuto v systému FDS

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#466]
Dobrý den, co přesně prosím znamená informace v pos merchant "Zamítnuto v systému FDS"? Konkrétně například platba 29cf701260c6dEL na M1E3CB0860 ještě s result message "card declined in fractals ws check"?

Hlášku jsme u platby dostali prvně včera cca ve 12:30

**Comment by Mspisar** [comment]
Dobrý den,
jedná se o hlášku externího fraud modulu, který ověřuje zda karta splňuje veškerá nezbytná kritéria pro úspěšnou platbu. Bližší informace bohužel nemáme.
S pozdravem
Spisar

**Comment by janlanger** [comment]
Máme od včerejška zhruba dvoj - trojnásobek zamítnutí při použití zapamatovaných kartet. Změnilo se něco?

Hláška se objevuje i u applepay.

**Comment by janlanger** [comment]
Vypadá to že se zamítnutí objevuje především u klientů s IPv6 adresou, můžete to prověřit?

**Comment by Mspisar** [comment]
Dobrý den,
váš požadavek jsem předal na prověření. O dalším postupu budete informován.
s pozdravem
Spisar

**Comment by janlanger** [comment]
Tak problém asi netrvá od včerejška, počet zamítnutí u klientů s ipv6 skokově vzrostl po nasazení eAPI 1.8 kde se nově předává IP...

**Comment by mrazekl** [comment]
Dobrý den,
máte pravdu, komplikace nastávají ve spojení IPv6 + fraud systém. Byl naprogramován nový update verzí, který je nyní ve fázi testování a pokud testy dopadnou úspěšně, bude nasazen z kraje příštího týdne.

**Comment by mrazekl** [comment]
Dobrý den,
dnes ráno byla nasazena nová verze aplikace, omezení ve spojitosti s ClientIp ve tvaru IPv6 se již nebude vyskytovat.

**Comment by janlanger** [comment]
Už to vypadá lépe, díky
