### ISSUE TITLE
OrderId format - uuid/string?

### ISSUE THREAD

**Issue by p4veI** [csob/paymentgateway#467]
Nerozumím proč model platby (metoda init/api - https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody#payment-init-operation) api vyžaduje string argument `OrderId` které musí být v numerickém formátu.. takže `'123'` ? Proč??

Proč neumožňuje hodnota využít např. uuid, když už je typu string, a místo toho je omezená na 10 znaků a validovaná zda jde numerickou hodnotu?

**Comment by LucieSnedarova** [comment]
Dobrý den, 
Váš požadavek byl předán na odpovědného kolegu.
S pozdravem
Lucie Šnédarová

**Comment by p4veI** [comment]
..pardon, uz sem to pochopil v prekladu to je variabilni symbol cili pro pripady `0123`, chapu.
