### ISSUE TITLE
Wordpress Integration

### ISSUE THREAD

**Issue by EventFrontiers** [csob/paymentgateway#468]
Hello,

May I ask you how to integrate the ČSOB payment gateway with WordPress?

I have read the issues on that, however could not find any plugins for that.

Is the "Monet Payment Gateway" still available?

Thank you!

**Comment by mrazekl** [comment]
Hello, 
unfortunately, in conjunction with the new release of version eAPI 1.8 official support of woocommerce plugin has been stopped. 
Don't despair,  support  will may be restored in the future.
If there will be any update, I will inform you.

**Comment by EventFrontiers** [comment]
Hello, Thank you for your reply.

In that case, how to integrate it with a website that is on WordPress?

Thanks

**Comment by mrazekl** [comment]
Hi,
in fact that official addon into woocommerce plugin is no longer available, you should make php edit at your own. 
Or looking for some developer which can do it for you. 
We understand it is difficult, but this is the current situation.

**Comment by angelleye-gitcommits** [comment]
GitCommits contributor has sent an offer to work on this issue.

**Offer Amount:** $250.00
**Message:** Hi,
This is deepak, 7+ years experience in WordPress Plugin Development.
I have checked the requirement details, For the CSOB Gateway we can build the Custom Gateway Plugin compatible with WooCommerce, which will work same as other Payment Gateway plugins provided by WooCommerce etc.
I am available to do this Job and discuss more about it. Let me know if you are interested in it then we can discuss about the details and price, Currently i am just entering an amount, but after our chat we will adjust it. Thanks
<hr><a target='_blank' href='https://app.gitcommits.com/offers/maurya-wordpress-integration?action=accept'>Accept Offer</a> | <a target='_blank' href='https://app.gitcommits.com/offers/maurya-wordpress-integration?action=decline'>Decline Offer</a> | <a target='_blank' href='https://app.gitcommits.com/offers/maurya-wordpress-integration?action=counter'>Counter Offer</a>

**Comment by deepakmaurya** [comment]
@EventFrontiers Just following up on this, Do you still need to integrate this in WordPress website? 
Thanks

**Comment by Wolandgrin** [comment]
> addon into woocommerce plugin
Hello, What was that addon name? is it still available somewhere?

**Comment by mrazekl** [comment]
@Wolandgrin officially is not supported, so it is not available to download from github

**Comment by Wolandgrin** [comment]
What was its name?
