### ISSUE TITLE
Ověření podpisu pomocí veřejného klíče

### ISSUE THREAD

**Issue by techi602** [csob/paymentgateway#47]
Dobrý den,

Při přesměrování z platební brány zpět na e-shop bych rád ověřil, že příchozí požadavek není podvržený. Bohužel se mi všechny příchozí požadavky tváří jako podvržené.

Příklad požadavku platební brány s metodou POST

```
signature:muKPk39ApZN7SIr913Z044mHhGtok6eg17fYoW71XMMrVkxpbsScjwvO8Pkn4dkiwU3Gd6f9F4uWd95dzO6pRlghDs0b6jktEITo29tzV7eb51/mlxCBw1zGTxiLE1atPKvcPQLIsFB7kZsPpBes62rug5C8hreUJBk8M4c0ty/SND/c6N+utSQPvCmFexL4coAkvjmGfzpdbCMqceHquPztEAFybs97EwujfriRltY1E+82usTZc0dT7K93MJQy6NmdWJMY6h4CqBt0J8IIf6nz2AnjU82BnlVPblCdJGCEzRLxg4op6bIm418RMmab1xKlEC+70AzcAGIEOYbiPQ==
dttm:20150910235422
resultCode:0
payId:c4c768f13b6c42c
resultMessage:OK
paymentStatus:3
```

Z těchto dat sestavím pomocí funkce verifyResponse() (z ref. implementace) text
`
c4c768f13b6c42c|20150910235422|0|OK|3
`
a to společně s base64 signature předám funkci verify() kde používám svůj veřejný klíč pro testovací bránu. Předpokládám, že na mé straně i na straně testovací platební brány jsou klíče nastaveny v pořádku a jsou totožné, jinak bych ani nebyl schopen poslat ověřený požadavek na platební bránu. 
`openssl_get_publickey()` úspěšně načte můj veřejný klíč s příponou .pub. 
Bohužel `openssl_verify()` vrátí v tomto případě vždy hodnotu 0, tzn. nedošlo k chybě, ale podpis není správný.

Mechant ID `M1E3CB3335`

Nemohu poznat, jestli je problém v mojí implementaci, nastavení klíče nebo konfiguraci platební brány.

**Comment by ratajskym** [comment]
Dobrý den,

nemáte stejný problém jako je popisován [tady](https://github.com/csob/paymentgateway/issues/45) ?

**Comment by techi602** [comment]
Děkuji za odpověď
Ano problém byl v tom, že jsem používal k ověření odpovědi vlastní veřejný klíč namísto klíče platební brány.
