### ISSUE TITLE
Need a way to test cards with max daily limits

### ISSUE THREAD

**Issue by askdesigners** [csob/paymentgateway#470]
I think we have discovered an interesting bug in how the gateway checks for daily limits :) 

We have a credit / voucher system which allows gift cards to be applied during the checkout process, so when we pass the `cart` array to the gateway, we add the voucher amount as a negative number to the cart items. 

This appears to work well, and displays the correct values in the gateway. However there's an issue when making a charge with a saved card, where it looks like the gateway already fails the daily limit check when the first item is over the limit, rather than looking at the sum of the two items. 

Is that possible?

We had a client with a total of 7000, and a 3000 discount have his card rejected due to his 5000/day limit. 

We will make a fix on our end to pre-calculate the final sum, but it seems like it might be a bug worth fixing.

This behavior isn't documented anywhere, but having for instance a CVC number that would simulate a daily limit would be a handy thing to have.

**Comment by mrazekl** [comment]
Hello Ryan,
in product environment, the payment gateway doesn´t check the daily limits of cards, it is processing at other side, in authorization centre of issuing bank. Only bank cards are allowed, gift, fleet, gastro cards etc.. are not supported.
In test environment, cards are authorized against simulator which support test cards only.
You can use CVC = 300 for simulate NOT SUFFICIENT FUNDS, which is similar to daily limit exceeded
If you have total 7000 with 3000 discount, you must set up totalAmount parameter to 4000 in payment/init request.

**Comment by askdesigners** [comment]
Ok great thanks! I hadn't thought of using that code for that. 👍
