### ISSUE TITLE
oneClick/init has clientIp required

### ISSUE THREAD

**Issue by rootpd** [csob/paymentgateway#471]
Since v1.8 the `clientIp` parameter is present and required for `oneClick/init`. This is in principle breaking change since 1.7 as the parameter wasn't there before.

The description of parameter is:

> IP adresa zákazníka (jeho prohlížeče) přistupujícího na e-shop obchodníka, formát ipv4 nebo ipv6.

What should we include, if we're using one click payments for monthly recurring payments and they're initiated with the consent of user (given during initial payment), but they're executed offline server-side? There's no client's IP during that scenario.

Thanks.

**Comment by mrazekl** [comment]
Hello,
if you still using eAPI version 1.7, you don´t have to change anything.
For eAPI 1.8 you must add ClientIp(IP of client browser) parameter to your oneclick/init request.
And in v1.8 is another big change, algorithm for coding signature has changed from SHA1withRSA (eAPI 1.7 and lower) to SHA256withRSA

**Comment by rootpd** [comment]
Thanks for the explanation, no more questions from me at this point :).
