### ISSUE TITLE
integrace platební brány ČSOB do nette

### ISSUE THREAD

**Issue by maggi1** [csob/paymentgateway#473]
Dobrý den, nevíte, existuje řešení integrace platební brány ČSOB pro Nette framework?

**Comment by ratajskym** [comment]
Dobrý den, jestli existuje plugin přímo do nette, to nevím. Zkuste se poptat na fóru https://forum.nette.org/cs/

Velmi hezkou php implementaci má @ondrakoupil k dispozici zde https://github.com/ondrakoupil/csob
