### ISSUE TITLE
dotNET integrace v1.8 - nefunkční úkázka

### ISSUE THREAD

**Issue by TomasHorvath** [csob/paymentgateway#475]
Dobrý den zkoušel jsem vygenerovat anonymní klíče pro otestování integrace. Při použití na testovacím příkladě funguje pouze verze 1.6. verze 1.8 vrací http status 400 bez nějaké bližší specifikace. Je možné zjistit, kde je problém.

**Comment by RoForst** [comment]
Dobrý den,

dotaz předávám na kolegu.

S pozdravem
Robin Forst

**Comment by ratajskym** [comment]
Dobrý den, podle Vašeho popisu si troufám vsadit na tohle 

https://github.com/csob/paymentgateway/wiki#sha-256-podpis-api-po%C5%BEadavk%C5%AF-a-odpov%C4%9Bd%C3%AD-br%C3%A1ny

**Comment by TomasHorvath** [comment]
Dobrý den, využívám přímo příklad z Vašeho git repa. Ověřoval jsem to v kódu a je tam SHA256CryptoServiceProvider ,takze algorytmus by měl být v pořádku. Jedná se o 
MerchantID A4426CvLc3

**Comment by mrazekl** [comment]
Dobrý den,
dne 24.02 vidím úspěšně inicializovanou objednávku pro merchantId A4426CvLc3. Předpokládám tedy, že se vám problém s podpisem podařilo vyřešit. Máte další dotazy, nebo můžeme vlíkno uzavřít?

**Comment by JanSlahar** [comment]
Dobrý večer, jak se to podařilo vyřešit? Stáhl jsem example pro 1.8, vygeneroval Sandbox ID, přidal klíče do Assets a upravil MerchantId. Ale dostávám také odpověď "Bad Request".

**Comment by mrazekl** [comment]
Dobrý den,
@Jan Slahar: jaké používáte merchantID? Abychom to mohli prověřit

**Comment by JanSlahar** [comment]
@mrazekl: MerchantID je A4624XC5nH. v1.8 s SHA256 nefunguje. v1.7 s SHA1 je funkční bez dalších úprav.

**Comment by SilverwareCode** [comment]
Dobrý den,
mám úplně stejný problém. Integruji váš příklad z GitHub. Vygeneroval jsem si nové MerchantId **A4601WhuQk** a k tomu odpovídíající *.KEY a *.PUB klíče. Posílám na adresu platební brány **https://iapi.iplatebnibrana.csob.cz/api/v1.8/payment/init** tento POST request 

`{"orderNo":"554822","payOperation":"payment","payMethod":"card","totalAmount":1500,"currency":"CZK","closePayment":true,"returnUrl":"https://vasobchod.cz/return-gateway","returnMethod":"POST","cart":[{"name":"žluťoučký kůň","quantity":1,"amount":1500,"description":"Lenovo ThinkPad Edge E540"},{"name":"Poštovné","quantity":1,"amount":0,"description":"Doprava PPL"}],"description":"Nákup žluťoučký kůň na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)","merchantData":"c29tZS1iYXNlNjQtZW5jb2RlZC1tZXJjaGFudC1kYXRh","customerId":null,"language":"CZ","ttlSec":300,"logoVersion":0,"colorSchemeVersion":0,"merchantId":"A4601WhuQk","dttm":"20200511101406","signature":"Omp1fGm5JhZwiKewJCrz0t+iSkOP14tGPvclc+kGa0Yu6K3V21tXx5WID9w+GmR0dnpbYiu0I0qBzZWIpBAmpyCUQd/0wFXdiOUcJGXZPJBwfJoOCKWgCcQxmsASxhM10PTQGDyFTnfUr+TJqCzOOGp8vMIuwTUeVy0bj29nVuDr/RTsyhrQBjpDQUHIk9czEakXu6+GIKCxkWf2GMBnHa14Aa6hFGzqifMoFiH2BO23ZaqD/6/ExdzVD14ljXL6tk68ffCA3WwlVzD0l0C7MD6WQ29wXReOQDf2oxP6V8+vloHnStm4Jjs9UhmEej5Ub8YvwZVn4m0oU/m4cGlFmw=="}`

A vrací se mi BadRequest. Můžete mi prosím poradit, kde je chyba. Podle mého názoru postupuji přesně podle vašeho příkladu. Echo mi funguje výborně a vraci Ok (200).

Děkuji Matouš Havránek

**Comment by mrazekl** [comment]
@JanSlahar , SilverwareCode

bylo způsobeno tím, že od verze API 1.8 se již nepočítá s parametrem description.
odeberte tento parametr z dat v Initu a požadavek by měl být úspěšně zvalidován.
opravil jsem to i ve vzorovém JSON payment-init-base.json

**Comment by SilverwareCode** [comment]
Dobrý den,
děkuji za odpověď a potvrzuji, že odstranění Description z payloadu problém vyřešilo :)
Přeji pěkný den,
Matouš Havránek

**Comment by mrazekl** [comment]
díky za zpětnou vazbu
Issue tedy uzavírám.
