### ISSUE TITLE
Apple Pay - Merchant Blocked [Error 120]

### ISSUE THREAD

**Issue by prometheuscz** [csob/paymentgateway#476]
Při implementaci jsme narazili na problém při volání metody applepay/init. Jako odpověď vždy dostaneme errorCode 120.

```
Array
(
    [dttm] => 20200226161432
    [signature] => ff18txIIDNjkOan1wUqvlelqNBz.............
    [payId] => 9639ca5233c94FB
    [resultCode] => 120
    [resultMessage] => Merchant blocked
    [paymentStatus] => 6
)
```

požadavek je dle dokumentace: 

```
Array
(
    [merchantId] => *********
    [orderNo] => 1
    [dttm] => 20200226161432
    [clientIp] => *.*.*.*
    [totalAmount] => 20000
    [currency] => CZK
    [closePayment] => true
    [signature] => cKPN29F/FdHySC/hJO3B89u0vEeSkhTy............
)
```

Platební metoda je na ČSOB povolena.

**Comment by mrazekl** [comment]
Dobrý den,
merchant ID M1MIPS1143 má povolenu applepay metodu pouze na integračním prostředí.
Požadavek payId 9639ca5233c94FB byl odeslán do produkce, kde zatím není nastaveno.
Kontaktujte, prosím, banku pro povolení i v produkčním prostředí.
