### ISSUE TITLE
Jednotlivé kroky platebního procesu

### ISSUE THREAD

**Issue by maggi1** [csob/paymentgateway#477]
Dobrý den, mám prodejní modul v Nette (paralelně s Wordpressem). Do modulu se odkazuje z WP přes link. Zde se načte stránka s formulářem produktu. Zákazník jej vyplní a odešle. Nejprve se v modulu uloží objednávka do databáze a poté dojde automaticky k přesměrování  do složky s csob řešením platební brány staženým zde na Githubu (1.8). Na stránce, kam bylo přesměrováno se nejprve načtou z databáze údaje o objednávce, zákazníkovi se zobrazí rekapitulace objednávky a spustí se payment/init. Kliknutím na tlačítko s odkazem PAYMENT se sputí payment/process a dojde k automatickému přesměrování na platební bránu. Můžete to vidět zde: https://easyweb4u.cz/ibcn/order/1/1 a klidně udělat objednávku...
1. Není mi ale jasné, jak a KDE implementovat metody
- payment/status
- payment/reverse
- payment/close
- payment/refund
V tomto ukázkovém řešení ČSOB byly linky (stejně jako na payment/process), to však zde nelze, protože to je stránka, na které provádí zákazník nákup a platbu. 
2. Jak získám payId?
Děkuji za odpověď, prosím bez teorie, té je tady až až...

**Comment by kkolarikova** [comment]
Dobrý den,
předáno na odpovědného kolegu.
S pozdravem Kolaříková Kateřina

**Comment by mrazekl** [comment]
Dobrý den,
je dost možné, že modul Nette tyto platební metody nepodporuje(stejně jako je nepodporuje například woocommerce plugin do WP) a proto nejsou jeho součástí. Tohle byste si měl ověřit u jeho dodavatele.
V případě že tomu tak opravdu je, změnu stavu transakce můžete provádět ručně v PosMerchant systému, kdy v sekci platební brány -> transakce, přes ikonu ČERVENÉHO dolaru můžete transakci zaslat do zaúčtování(pokud se tak nestalo automaticky, rozhoduje o tom parametr closePayment v payment/init požadavku) a nebo ji reverzovat - nahrazuje metodu payment/close či payment/reverse
Pokud je transakce zaúčtovaná, přes ikonu MODRÉHO dolaru je možné ji refundovat - nahrazuje payment/refund

Pokud není možné pay_id zjistit z nástavby nette či vašeho serveru, můžete ji rovněž získat v PosMerchantu, kde pay_id = objednávka v přehledu transakcí

**Comment by maggi1** [comment]
No dobře, dobře. V Nette mám pouze objednávací formulář, odtud se po potvrzení objednávky přeměrovává již mimo Nette. Tak že Nette neřešme. 
1. v dokumentaci se píše, že je třeba mít naimplementované tyto metody:
payment/status
payment/reverse
payment/close
payment/refund

Z Vaší odpovědi vyplývá, že tyto metody naimplementované mít nemusím - v řešení ČSOB jsou, ale já na ně během platebního procesu neodkazuji (odkazy jsem odstranil). Výše uvedené metody tedy mohu řešit přes  PosMerchant. 
ANO či NE?

2. Jaké parametry a jakou metodou (POST?) vrací brána hlášení o provedení (neprovedení) transakce? Jsou součástí volání $returnUrl?

3. Můžete prosím udělat testovací objednávku: https://easyweb4u.cz/ibcn/order/1/1
a sdělit mi, zda toto mohu považovat za hotové řešení?

Předem děkuji, s pozdravem Milan Makovec

**Comment by maggi1** [comment]
Ještě dotaz, testovací platební brána mi neumožňuje platbu v EUR - platba v EUR není dovolena, když v kódu zadám $currency = 'CZK';

1. mohu EUR někde nastavit?
2. jak to bude s EUR v produkční ostré bráně?
3. co je to Push notifikace?

Děkuji M

**Comment by mrazekl** [comment]
ad1)
Pokud nemáte možnost reverzalu, provedete pouze tři testovací transakce:
1)úspěšně autorizovaná platba
2)uživatelem zrušená platba
3)expirovaná platba
viz: https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD#%C3%9Asp%C4%9B%C5%A1n%C4%9B-autorizovan%C3%A1-platba
Jakmile budou provedeny, je potřeba žádat o aktivaci v produkci přes emailovou adresu akceptacekaret@csob.cz 
ad2)
metodu si zvolíte sám parametrem returnMethod
vrací se payId,dttm,resultCode,resultMessage,paymentStatus
returnUrl je pouze parametr, kam má být zákazník po zaplacení přesměrován
ad3) 
aktuálně je v odkazu server error 500
testovací transakce si musíte realizovat sám
za hotové řešení můžete považovat, když se přesměrujete na platební bránu, provedete platbu a vrátíte se zpět do eshopu
ad4)
o nastavení musíte požádat na stejném kontaktním emailu akceptacekaret@csob.cz
currency EUR se musí nastavit i pro produkční prostředí
push notifikace bude nová funkce platební brány, která bude aktivně informovat eshop, v jakém procesním stavu objednávka aktuálně je. Zatím je v rozpracovaném stavu.

**Comment by maggi1** [comment]
Dobrý den, doteď to fungovalo a najednout toto:


<pre>preparing cart data:
--
  | [
  | {
  | &quot;name&quot;: &quot;Shopping at ...&quot;,
  | &quot;quantity&quot;: 1,
  | &quot;amount&quot;: 1039300,
  | &quot;description&quot;: &quot;Intelligent Offshore Wind O&amp;M Forum 2...&quot;
  | },
  | {
  | &quot;name&quot;: &quot;Shipping&quot;,
  | &quot;quantity&quot;: 1,
  | &quot;amount&quot;: 0,
  | &quot;description&quot;: &quot;&quot;
  | }
  | ]
  |  
  | data to sign:
  | "A43610Wpyn\|1\|20200303154653\|payment\|card\|1039300\|CZK\|true\|http://easyweb4u.cz/paymentgateway/return.php\|GET\|Shopping at ...\|1\|1039300\|Intelligent Offshore Wind O&amp;M Forum 2...\|Shipping\|1\|0\|\|1\|1\|EN"
  |  
  | prepared payment/init request:
  | {
  | &quot;merchantId&quot;: &quot;A43610Wpyn&quot;,
  | &quot;orderNo&quot;: &quot;1&quot;,
  | &quot;dttm&quot;: &quot;20200303154653&quot;,
  | &quot;payOperation&quot;: &quot;payment&quot;,
  | &quot;payMethod&quot;: &quot;card&quot;,
  | &quot;totalAmount&quot;: 1039300,
  | &quot;currency&quot;: &quot;CZK&quot;,
  | &quot;closePayment&quot;: true,
  | &quot;returnUrl&quot;: &quot;http://easyweb4u.cz/paymentgateway/return.php&quot;,
  | &quot;returnMethod&quot;: &quot;GET&quot;,
  | &quot;cart&quot;: [
  | {
  | &quot;name&quot;: &quot;Shopping at ...&quot;,
  | &quot;quantity&quot;: 1,
  | &quot;amount&quot;: 1039300,
  | &quot;description&quot;: &quot;Intelligent Offshore Wind O&amp;M Forum 2...&quot;
  | },
  | {
  | &quot;name&quot;: &quot;Shipping&quot;,
  | &quot;quantity&quot;: 1,
  | &quot;amount&quot;: 0,
  | &quot;description&quot;: &quot;&quot;
  | }
  | ],
  | &quot;merchantData&quot;: &quot;1&quot;,
  | &quot;language&quot;: &quot;EN&quot;,
  | &quot;customerId&quot;: &quot;1&quot;,
  | &quot;signature&quot;: &quot;Opn0U7MrIKR1Ls23xQyhuGj67DDbTjkLlGIVWfU1sHbpHRXGHGUH1G+fGu5bI5+SuwRlS+fKuzj2iyCGAdxCjwPeZJvMYWFJxhBe8dF0vKxVN35bRhd+og10abKoNwE1u0LCaZIrIoaoWzVQe+Az6jouIo/A1SX9FKuGXl2DkSyyZLbh1RQ7KPpEF1Wgu6+x0I8/aVRtrw5Ytp7YANtO4DBimKkbfoNLI3k3Sn9KwvgaU6pIO5dnWvn5i8K3Jw2wHn1MvyR3BbWOr/Rkarv5WPaj+SgmwM8he1owT/wUQFf6H4t17Bzzsk+8RA50zaCHaNRvK2kHGCu2/hQOdiCFow==&quot;
  | }
  |  
  | processing payment/init request ...
  |  
  | payment/init result:
  | {&quot;dttm&quot;:&quot;20200303154653&quot;,&quot;signature&quot;:&quot;sBH5nbhZ9R6/UnbFfyfAAhXr902yfAYPsZjJkhYV554lvX1jzOOQzHZuNzSE7BF7xrGnHVsmAwKnuPUeyDuWaVJR/qNohiQpKGvO3YS4kBcWsSazl9P2oi1Byj8/+4P8fFa/+ytM2lTpm9IWxg8oX1yQVzMscMs9tdJz4j40OWys1gDxI3k3xnNka5KC81IbFCubIFvcwNyrJqzjE6IlTQd8jwPDV0pXE6CuviIBSvxwxC4rmMMAoh4rrgsTbhhq3mUuFOOrsioQIKz3vhiLkKWDdzUgxIv3SzzMOI7xV6vFFV0aEjPwbj4pU3oI0B1w8Oy1cmWyDle/Cny74pYVsA==&quot;,&quot;payId&quot;:&quot;7bec8dc37e55dFC&quot;,&quot;resultCode&quot;:110,&quot;resultMessage&quot;:&quot;Invalid merchantData parameter, not base64 format&quot;,&quot;paymentStatus&quot;:6}
  |  
  | payment/init failed, reason: Invalid merchantData parameter, not base64 format

Proč?

**Comment by mrazekl** [comment]
Dobrý den,
důvod je uveden zde: payment/init failed, reason: Invalid merchantData parameter, not base64 format
parametr merchantData musí být před zakódováním celého podpisu zišifrován v BASE64
tedy místo "1" uveďte "MQ==" apod...

**Comment by maggi1** [comment]
No dobrá encoding jsem vyřešil. Odladil jsem na svém development webu (stále to tam je). Nyní jsem aplikaci s bánou přenesl na ostrý hosting. Nedaří se verify signature...


{
--
  | &quot;name&quot;: &quot;Shopping at ...&quot;,
  | &quot;quantity&quot;: 1,
  | &quot;amount&quot;: 569700,
  | &quot;description&quot;: &quot;Intelligent Offshore Wind O&amp;M Forum 2...&quot;
  | },
  | {
  | &quot;name&quot;: &quot;Shipping&quot;,
  | &quot;quantity&quot;: 1,
  | &quot;amount&quot;: 0,
  | &quot;description&quot;: &quot;&quot;
  | }
  | ]
  |  
  | data to sign:
  | "A43610Wpyn\|8\|20200303213230\|payment\|card\|569700\|CZK\|true\|https://ibcngroup-sale.com/paymentgateway/return.php\|GET\|Shopping at ...\|1\|569700\|Intelligent Offshore Wind O&amp;M Forum 2...\|Shipping\|1\|0\|\|OA==\|8\|EN"
  |  
  | prepared payment/init request:
  | {
  | &quot;merchantId&quot;: &quot;A43610Wpyn&quot;,
  | &quot;orderNo&quot;: &quot;8&quot;,
  | &quot;dttm&quot;: &quot;20200303213230&quot;,
  | &quot;payOperation&quot;: &quot;payment&quot;,
  | &quot;payMethod&quot;: &quot;card&quot;,
  | &quot;totalAmount&quot;: 569700,
  | &quot;currency&quot;: &quot;CZK&quot;,
  | &quot;closePayment&quot;: true,
  | &quot;returnUrl&quot;: &quot;https://ibcngroup-sale.com/paymentgateway/return.php&quot;,
  | &quot;returnMethod&quot;: &quot;GET&quot;,
  | &quot;cart&quot;: [
  | {
  | &quot;name&quot;: &quot;Shopping at ...&quot;,
  | &quot;quantity&quot;: 1,
  | &quot;amount&quot;: 569700,
  | &quot;description&quot;: &quot;Intelligent Offshore Wind O&amp;M Forum 2...&quot;
  | },
  | {
  | &quot;name&quot;: &quot;Shipping&quot;,
  | &quot;quantity&quot;: 1,
  | &quot;amount&quot;: 0,
  | &quot;description&quot;: &quot;&quot;
  | }
  | ],
  | &quot;merchantData&quot;: &quot;OA==&quot;,
  | &quot;language&quot;: &quot;EN&quot;,
  | &quot;customerId&quot;: &quot;8&quot;,
  | &quot;signature&quot;: &quot;i7/q0jzNHtloMeYf4rE+6GzaTX/h6pmvWcNFGl74xYjE8g344EsyyznZgS0dVXEbQyR9tIUO9c+dEuzxEpsSb1SIIvPxczGzisOpt7uwfmSceg8ch95DW8F5xbjzB60ziBqZlquiPZeXSWqV4yuaZbBrZvUz236O9w8tzikgrEOe7kush+5Zr4+5C32qtFszj+SLcWOrhODmuDUDhyAOVXQL3BXjE7cUF1q0Vka+87KvEKP8HisIh+yxdGS6ATP+0q/0b9l7mrr06ijZJlLUf6z0Gdba/6wSDgVHACW282dvvYMifRw50jPrYJ7K22ojdL0gEpEC7DW7Lkqcf7y5bg==&quot;
  | }
  |  
  | processing payment/init request ...
  |  
  | payment/init result:
  | {&quot;dttm&quot;:&quot;20200303213230&quot;,&quot;signature&quot;:&quot;THpXtCFQSnJUEWLlazL4WTb8uzErKoZl0jBjSqT6O9OKprT8PEh3FLEJ0J6v9yYDvPFdUJ60yZPQKp7HGEdDHXWuAl0JMI7SSFoeOXQ4Yh4bzCott5i5vnlA3lewG7SvzLV85dUsqj/kx368qOwwOZwil71+GcDpbay6lvpo5BHKgZtLJeUfwANc7ECGC8Rp2Vp6vP6ZozdP8ZAgxA23a77vZFr1um+TykKNn4cbd151zpjAZXPO1BGn9AxTeto//gC3LAjAANkeRauGsqelmQShw3jIrZpxjz7F54s1Wj7PXPno3+5p/a8mBMmmi/0nawkm095Zi+Z/lh8p5Zfm0A==&quot;,&quot;payId&quot;:&quot;ba8bdefe9188dFC&quot;,&quot;resultCode&quot;:0,&quot;resultMessage&quot;:&quot;OK&quot;,&quot;paymentStatus&quot;:1}
  |  
  | payment/init failed, unable to verify signature

Opět, v browseru místo uvozovek ASCII ampersand+quote;

**Comment by ratajskym** [comment]
Dobrý den, takže se Vám to nakonec povedlo rozjet ? 

Vidím, že už jste se na bránu dostal.
`Received paymentProcess request A43610Wpyn`

**Comment by maggi1** [comment]
Dobržý den, ano dostal, ale na mém devolopment webu easyweb4u.cz/ibcn/order/1/1. Včera jsem ale založil pro klienta nový hosting ibcngroup-sale.com/order/1/1 a tam to nechce ověřit signatruru. 


processing payment/init request ...
--
  |  
  | payment/init result:
  | {&quot;dttm&quot;:&quot;20200304082241&quot;,&quot;signature&quot;:&quot;HfNEFO+ee7mzYNIz82mJVll8a/f0MUuBOqKEFR6jDebF6C/ZUKebgg3J/Nsw7BJ+1gfZsCfvf7mw/BJ3+ChqBw11FfrmdkyV4aor8pDt9RS/6JqpB1yqhALgI6qIzTZlW8651KJZbnZkuqC46Z/tQ33Uob6F5ilrAb6Su9p2KsnMTyscao/PubdaqUXoAFWgTdHRoukR7CistLpsicLoN6c7hpSOL++VV0olDLKt2Y1fYHBsKwnWorjC2AWXbNc4/GX8xQqnHwObxEn4lgDzMdZF5EartjIQwtcksjcucJtrJTvS8aT046wa9T0hTbJuwNLcTueiyzHFUac7nssAtQ==&quot;,&quot;payId&quot;:&quot;8cf5a3fce860fFC&quot;,&quot;resultCode&quot;:0,&quot;resultMessage&quot;:&quot;OK&quot;,&quot;paymentStatus&quot;:1}
  |  
  | payment/init failed, unable to verify signature

Jo možné, že si intergrační brána pamatuje IP adresu či něco jiného a nechce signaturu ověřit z nového místa... Když to na development webu smažu, pomůžu si? Co s tím?

**Comment by ratajskym** [comment]
Je to o tom, že se Vám nepodaří ověřit podpis. Tzn máte na hostingu klíče platební brány v dostupném adresáři ? Máte tam stejné klíče jako na lokále ?

**Comment by maggi1** [comment]
Je to identická kopie. Ale  pozor, ta development verze není na lokále (tam jí mám také), ale na webu.
Devel: easyweb4u.cz/order/1/1 - funguje (byla nejdříve)
Nový: ibcngroup-sale.com/order/1/1 - nefunguje
Opakuji, jedná se o identickou kopii. Klidně vyzkoušejte udělat objednávky.

**Comment by maggi1** [comment]
správně: easyweb4u.cz/ibcn/order/1/1 (editoval jsem comment)

**Comment by ratajskym** [comment]
Bohužel tady nemám věšteckou kouli, abych Vám řekl, proč to na jednom prostředí funguje a na druhém ne. Zvlášť pokud tvrdíte, že se jedná o identickou kopii.

Platební brána přijme Váš payment/init a vrací Vám odpověď. Ověření odpovědi je tedy ve Vašich rukou

**Comment by maggi1** [comment]
No, ona to není úplně identická kopie, je tam trochu jiná struktura folderů, abych z URL dostal jeden parametr. Udělám identickou kopii a testnu to. Sorry

**Comment by ratajskym** [comment]
Před malou chvílí vidím úspěšnou transakci. Takže se Vám to povedlo rozjet ?

**Comment by maggi1** [comment]
No, představte si, že jsem překopíroval klíče a rozeběhlo se to, i v té alternativní struktuře. Veřejný klíč banky měl o něco více kB... Není mi to jasné, jsou to ty samé. Ale sláva. Ještě se zeptám, kde se v Pos Merchantu potvrzují testy? Já to tam nenašel... Děkuji

**Comment by ratajskym** [comment]
Ikona Lupy (validace)

**Comment by maggi1** [comment]
Nebudete mi to věřit, ale ikonu Lupy (validace) fakt nikde nevidím. Nezobrazuje se mi z nějakého důvodu?

**Comment by ratajskym** [comment]
![image](https://user-images.githubusercontent.com/9882463/75864555-7c811000-5e02-11ea-9785-ff8266a2b1be.png)

Jen doplním to, co jistě víte. Testy musíte provést pod Vaším reálným id brány.

**Comment by maggi1** [comment]
No to nevím.  Vůbec nevím, kde bych měl nastavit reálné id brány - v init-result.php to nevidím...

a pak

Test komunikace - echo (GET)
zavolat operaci echo pomocí metody GET
zkontrolovat response code (200 OK)
ověřit podpis odpovědi (pomocí public klíče platební brány pro integrační prostředí)
ve vráceném JSON response zkontrolovat resultCode (0)¨

ani jeden bod mi není zřejmý, jaká metoda echo? Myslíte příkaz echo - výpis, který se provede po payment-init?

**Comment by ratajskym** [comment]
V tuto chvíli používáte anonymní id. Toto id nahraďte platným id, které jste získal při podpisu smlouvy s bankou

**Comment by maggi1** [comment]
Tomu rozumím, ale KDE nahradit?

**Comment by ratajskym** [comment]
Asi v konfiguraci ? Já netuším, jak vypadají Vaše skripty ..

**Comment by maggi1** [comment]
No jak vypadají... Já jsem vzal celý balík API1.8, do init-result.php jsem si přivedl z mého prodejního modulu parametry a dál už jsem nic neměnil. A v těch kódech žádné ID brány nevidím, nejvýše je tam merchantID.

**Comment by ratajskym** [comment]
Ok .. chybně jsem to napsal. ID brány bylo myšleno ID merchanta .. tzn ID Vašeho eshopu, které jste dostal při podpisu smlouvy ..

**Comment by maggi1** [comment]
V Pos Merchantu vidím ID brány - to asi není ono (smlouvu má můj klient). Vložil jsem to do merchantID a hodilo to chybu 400.

**Comment by ratajskym** [comment]
Chyba 400 je špatný podpis. Doporučuji nastudovat následující [postup](https://github.com/csob/paymentgateway/wiki/Postup-integrace,-zabezpe%C4%8Den%C3%AD-pomoc%C3%AD-kl%C3%AD%C4%8D%C5%AF)

**Comment by maggi1** [comment]
1. Na to, na co jsem se ptal jste mi neodpověděl (a předtím jste to trochu zamotal) - zda ID brány v Pos Merchant je totožné z merchantID v konfiguraci (nebo zdamerchantID musím hledat ve smlouvě)

Schválení: Jakmile je integrace dokončena, obchodník o této skutečnosti informuje banku a provede sérii předepsaných testů. Banka ověří jejich výsledky oproti záznamům testovací iBrány a v pozitivním případě obchodníka aktivuje.

Jestli to chápu dobře:
a) před samotnými testy musím informovat banku - pakliže ano, jak koho, můžu Vás?
b) vložím merchantId (v tuto chvíli přesně nevím, viz bod 1) a provedu testy (kolega Mrázek psal, že stačí 3 - provedení platby (paymentStatus 7, zrušení transakce, a vypršení session.

Děkuji za odpověď

**Comment by ratajskym** [comment]
Add 1
Na to, na co jsem se ptal jste mi neodpověděl (a předtím jste to trochu zamotal) 
- uznávám rozhodně moje chyba

.. zda ID brány v Pos Merchant je totožné z merchantID v konfiguraci 
Ano, merchant id najdete v pos merchantu
Ano, merchant id musí být i v konfiguraci, toto id odesíláte ve jednotlivých požadavcích

.. nebo zda merchantID musím hledat ve smlouvě
Ano, toto id naleznete ve smlouvě

add a)
prověďte jednotlivé požadované testy a následně stiskem tlačítka validovat zjistíte, jak jste na tom
add b)
pokud některé z předepsaných testů nejste schopen splnit, protože je nebudete využívat, validace Vás stejně nepustí a budete se muset obrátit na banku akceptacekaret@csob.cz

Změna domény je problém, musíte se obrátit na banku, aby provedli změnu nastavení

Myslím, že testy a změnu konfigurace můžete řešit paralelně.

**Comment by maggi1** [comment]
Věřím, že se k tomu postupně dostaneme

1. v Pos Merchant merchantID nevidím, vidím ID brány v tabulce Platební brány - je to ono (merchantId) nebo to není ono. Když jsem to totiž vložil do konfigurace a pokusil se provést platbu, zahlásilo mi to chybu 400. 

2. v dokumentaci se píše, že testy musím nahlásit bance - pokud ano, komu?

**Comment by ratajskym** [comment]
Já už tomu popravdě přestávám věřit.

1 - ano, je to ono. Proto jsem toto názvosloví používal i já (id brány - ve smyslu id eshopu, na platební bráně. Toto bude s nějvětší pravděpodobností ve tvaru M1MIPSxxxx - pozor, místo křížků tam budou číslice)

2 - viz můj příspěvek o kousek výš ..  a budete se muset obrátit na banku akceptacekaret@csob.cz
Obrátit na banku ve smyslu, poslat email na uvedenou mailovou adresu

**Comment by maggi1** [comment]
Ještě k té chybě 400 - když to funguje s anonymním merchantId, proč to nefunguje se skutečným merchantId? Provede banka po mém nahlášení testů nějaké nastavení, aby to fungovalo se skutečným merchantId?

**Comment by ratajskym** [comment]
K podepisování požadavků používáte klíče. Pro anonymní id máte vygenerované nějaké klíče a platební brána netuší, že pro reálné merchant id má tyto klíče taky použít. Chci tím říct, každé merchant id má svoje klíče. Kdyby každé merchant id mohlo používat cizí klíče, pak bychom se s podepisování zpráv nemuseli obtěžovat.

**Comment by maggi1** [comment]
Ano, ale to mám vygenerovat ostré klíče nebo jsou ještě nějaké testovací klíče. Z Vaší odpovědi toto nevyplývá a ani z dokumentace. Děkuji

**Comment by ratajskym** [comment]
Postup je tady:
https://github.com/csob/paymentgateway/wiki/Postup-integrace,-zabezpe%C4%8Den%C3%AD-pomoc%C3%AD-kl%C3%AD%C4%8D%C5%AF

Ale pokud Vám to z toho nevyplývá, tak je to ve zkratce takhle:
Anonymní id - může použít kdokoliv, bez nutnosti mít s bankou zavřenou smlouvu a může si své řešení otestovat a připravit tzv do šuplíku
Reálné id - integrační (testovací prostředí) - s tímto id už provedete validační testy a banka tedy ví, že tohle reálné id může povolit i v produkčním prostředí - je potřeba si pro toto id vygenerovat klíče právě na integračním prostředí

Reálné id - produkční prostředí - jakmile Vás banka povolí na produkci, budete si moci vygenerovat produkční klíče a používat produkční bránu

Takže odpověď na Váš dotaz:
Pokud slovem ostré myslíte reálné id pak:
 Jste na testovacím prostředí, musíte vygenerovat klíče na testovacím prostředí s ostrým id. 

Pokud slovem ostré myslíte produkční prostředí:
 Jste na testovacím prostředí, musíte vygenerovat klíče na testovacím prostředí s id M1MIPSxxxx (kdy místo křížků budou číslice).

**Comment by maggi1** [comment]
Takže, vygenerovalo jsme klíče pro testovíní - integrační prostředí, pro přidělené merchantId. Klíče jsem vložil do souborů rsa_M1MIPSXXX.pub a rsa_M1MIPSXXX.key. Nejprve jsem nasadil pouze rsa_M1MIPSXXX.key a nechal mips_iplatebnibrana.csob.cz.pub, ve druhém pokusu jsem nasadil  rsa_M1MIPSXXX.key a  rsa_M1MIPSXXX.pub. V obou případech dostávám hlášku payment/init failed, http response: 400
Mohl jsem čekat něco jiného? Nemohl. Co s tím?

**Comment by maggi1** [comment]
Abych to nezdržoval:
zavolat operaci echo pomocí metody GET
zavolat operaci echo pomocí metody POST

už jsem se tu na to ptal, ale odpověď jsem nedostal. Snad by se dalo hovořit o metodách, ty jsem schopen volat, ale zavolat operaci echo (má to snad být příkaz v PHP?), to fakt nevím.

**Comment by ratajskym** [comment]
To že dokážete zavolat php příkaz echo Vám víceméně věřím. Ale bavíme se o operacích / metodách, které voláte proti API platební brány. Zkuste se podívat do dokumentace např. sem:
https://github.com/csob/paymentgateway/wiki/P%C5%99ehled-eAPI-metod

**Comment by ratajskym** [comment]
> Takže, vygenerovali jsme klíče pro testování - integrační prostředí, pro přidělené merchantId. Klíče jsem vložil do souborů rsa_M1MIPSXXXX.pub a rsa_M1MIPSXXXX.key. Nejprve jsem nasadil pouze rsa_M1MIPSXXXX.key a nechal mips_iplatebnibrana.csob.cz.pub, ve druhém pokusu jsem nasadil rsa_M1MIPSXXXX.key a rsa_M1MIPSXXXX.pub. V obou případech dostávám hlášku payment/init failed, http response: 400
> Mohl jsem čekat něco jiného? Nemohl. Co s tím?

S Vaším veřejným klíčem rsa_M1MIPSXXXX.pub nijak nepracujete. Je to napsané v dokumentaci k pluginu, který používáte a je to popsané i v dokumentaci ČSOB. Rád bych Vám pomohl, o což se už několik hodin marně snažím.

**Comment by maggi1** [comment]
Zase jen poloviční odpověď a trochu tajemná. Já jsem to nejprve zkusil s klíčem mips_iplatebnibrana.csob.cz.pub, který na sandboxu fungoval, pak jsem ze zoufalství zkusil ten veřejný vygenerovaný, i když vím, že se s ním nepracuje. Ale co kdyby.

k té operaci echo: https://api.platebnibrana.csob.cz/api/v1.8/echo/{merchantId}/{dttm}/{signature} tomu rozumím, nicméně, kde vezmu {signature} ? Možná by to mohla být hodnota "base64-encoded-request-signature", ale to se mi nezdá. Nebo zkopíruju konkrétní signaturu z výsledku metody payment/init?

**Comment by ratajskym** [comment]
Ad klíče: 
rsa_M1MIPSXXXX.key - tímto klíčem podepisujete požadavky na bránu
rsa_M1MIPSXXXX.pub - tento klíč jste odeslal do banky a díky tomu dokáže platební brána ověřit podpis Vašich požadavků
mips_iplatebnibrana.csob.cz.pub - pomocí tohoto klíče Vy ověřujete požadavky z platební brány na eshop

Ad signature:
Asi Vám doporučím, abyste se obrátil na programátora, který Vám plugin dodal. Signature přece řešíte v každé jedné zprávě, kterou posíláte na platební bránu. Jistě Vám s tím poradí.

**Comment by maggi1** [comment]
Ad klíče, to přece VÍM, ale po nasazení klíče rsa_M1MIPSXXXX.key mi to hlásí chybu 400. A já se Vás ptám proč, když mám vše tak, jak popisujete a když mi před tím sandbox fungoval s anonymním klíčem a merchantId.

**Comment by ratajskym** [comment]
Jak už zaznělo, tak 400 - chybný podpis. Něco jste neudělal správně.

**Comment by maggi1** [comment]
To je všechno co mi řeknete? Můžete se někde podívat, zda se bance vrátil veřejný klíč?

**Comment by ratajskym** [comment]
Co víc Vám můžu říct ? Já nevím, jak to máte nakonfigurované, zda se odkazujete na správné klíče. Pošlete mi přístupy na Vaše FTP a já se tam hold podívám. 

Váš klíč je uložen v integrační databázi platební brány

**Comment by maggi1** [comment]
<?php

$url = "https://iapi.iplatebnibrana.csob.cz/api/v1.8";
$publicKey = "mips_iplatebnibrana.csob.cz.pub";

// set up your merchant ID
$merchantId = "M1MIPS7888";

// place your private key into 'keys' directory and set up key's filename
$privateKey = "rsa_M1MIPS7888.key";
$privateKeyPassword = null;

**Comment by ratajskym** [comment]
Krása. Tento rsa_M1MIPSXXXX.key je ve stejném adresáři jako byl ten původní anonymní ? Má stejnou velikost jako měl ten anonymní ?

**Comment by maggi1** [comment]
rsa_M1MIPSXXXX.key má o 4 kB méně...

**Comment by ratajskym** [comment]
Pošlete mi tento klíč na email servis@monetplus.cz. 

Porovnám, jestli patří ke klíči, co máme uložený v DB

**Comment by maggi1** [comment]
Poslal jsem

**Comment by ratajskym** [comment]
Pošlete mi prosím, ještě ten anonymní (privátní část)

**Comment by maggi1** [comment]
Poslal jsem

**Comment by ratajskym** [comment]
Vaše anonymní klíče spolu sedí, ale M1MIPS klíče ne. Nebudu teď vyšetřovat co jste udělal nebo neudělal. Vygenerujte si prosím nový pár klíčů a zkuste to ještě jednou

**Comment by ratajskym** [comment]
Gratuluji

**Comment by maggi1** [comment]
No, děkuji, spíš gratuluji já Vám :-)) Nyní jsem se pokusil provést testy, s reversovanou platbou - no to fakt nevím ani principielně. Když provedu na bráně úspěšnou platbu a dostanu se na stránku, kde děkuji zákazníkovi, odkud můžu volat tuto metodu? Můžete se prosím podívat na stav mých testů? Děkuji.

**Comment by maggi1** [comment]
Psal kolega mrazekl 
Pokud nemáte možnost reverzalu, provedete pouze tři testovací transakce:
1)úspěšně autorizovaná platba
2)uživatelem zrušená platba
3)expirovaná platba

Já to dělám pro třetí subjekt, nevím, zda mají reverzal a v Pos Merchantu to nevidím

Děkuji

**Comment by ratajskym** [comment]
Zítra tady bude, tak to s Vámi dotáhne.

**Comment by maggi1** [comment]
Jako že dneska končíme? Už jdete domů?

**Comment by maggi1** [comment]
Dobrý den, provedl jsem testování, můžete se prosím podívat, zda vše proběhlo korektně?

**Comment by mrazekl** [comment]
pro merchantID M1MIPS7888 vidím ze včerejšího dne zaúčtovanou transakci, zrušenou i expirovanou transakci 
Můžete tedy zaslat žádost na akceptacekaret@csob.cz pro aktivaci do produkčního prostředí s informací, že nebudete využívat reverzal přes API rozhraní.

**Comment by maggi1** [comment]
Děkuji za informaci. Ještě k tomu reverzalu - Mně není jasné, kdy by se tato metoda volala, když platba proběhla úspěšně. Metodu by měl volat obchodník, předpokládám.

**Comment by mrazekl** [comment]
Ano, metoda se volá ze strany obchodníka, například při reklamaci zboží, pokud není možné odeslat objednávku se všemi produkty a podobně.

**Comment by maggi1** [comment]
Dobrý den

1. vygeneroval jsem produkční klíče
2. veřejný produkční klíč jsem odeslal bance
3. do Pos Merchant jsem vložil kód zaslaný bankou a odeslal
3. nahradil jsem integrační klíče za produkční klíč a veřejný klíč banky (mips_platebnibrana.csob.cz.pub) ve složce keys
4. nastavil jsem $url = "https://api.platebnibrana.csob.cz/";

Výsledek: payment/init failed, http response: 404

**Comment by ratajskym** [comment]
Na integrační prostředí jste měl url
$url = "https://iapi.iplatebnibrana.csob.cz/api/v1.8";

Na produkční jste nastavil
$url = "https://api.platebnibrana.csob.cz/";

Zkuste najít "deset" rozdílů

**Comment by maggi1** [comment]
Nejsem jasnovidec, v manuálu máte https://api.platebnibrana.csob.cz/

**Comment by ratajskym** [comment]
Nebuďte zbytečně skromný, já bych řekl, že jste. Integrační prostředí má adresu https://iapi.iplatebnibrana.csob.cz, přesto jste doplnil povinné parametry z dokumentace /api/verze

**Comment by maggi1** [comment]
To bych nikdy neudělal, nejspíš jsem to někde opsal. Děkuji za spolupráci, snad je to pro tentokrát hotové. Ještě se zeptám, udělal jsem testovací platbu s ordernum 0000541. Když bych číslování faktur nastavil od 0000001 může dojít (časem) k nějakému konfliktu?

**Comment by mrazekl** [comment]
V rámci merchantID se kontroluje duplicita variabilních symbolů autorizovaných transakcí.
Můžete očekávat, že jakmile dojde opět k variabilnímu symbolu 541, bude zamítnut na duplicitu.
Z pohledu eshopu vytvoříte nový payment/init s orderNo 542 a dále nebude nic ovlivněno.
