### ISSUE TITLE
API returned HTTP code 400, which is not code 200. Probably wrong signature, check crypto keys.

### ISSUE THREAD

**Issue by janvalentik** [csob/paymentgateway#478]
Vím, že už se to tu i řešilo, ale mám problém s button/init.
Máme bránu kterou již nějaký měsíc, či dva používáme s platebními kartami a to funguje normálně.
Nyní jsme si nechali aktivovat platební tlačítko, ale button/init vrací zmíněnou hlášku.
Musí se tedy vygenerovat nové klíče aby tlačítko fungovalo nebo by mohla být chyba jinde.
Ke komunikaci používám knihovnu od Ondry Koupila. Když jsem koukal do logu, tak volána byla adresa https://api.platebnibrana.csob.cz/api/v1.8/button/init

Mohu tedy poprosit o kontrolu jestli máme platební tlačítko opravdu povolené. Naše Merchan ID je M1MIPS7744.

Děkuji
Jan Valentík

**Comment by RoForst** [comment]
Dobrý den,

požadavek jsem předal na kolegu.

S pozdravem
Robin Forst

**Comment by ratajskym** [comment]
Klíče jsou samozřejmě pro všechny platební metody stejné.

**Comment by janvalentik** [comment]
Takt to pak netuším kde by mohl být problém. Zkusil jsem nyní ještě jednou z ostrého provozu jelti náhodou včera nebyl problém s tím, že jsem to zkoušel z localhostu. Bohužel ani z ostrého provozu to neprošlo. Zkusím ještě kontaktovat Ondru jestli nebude nějaká chybka v knihovně.

**Comment by mrazekl** [comment]
při kontrole vašeho posledního pokusu ze 2020-03-04 08:17:59
nejsou v příchozím init požadavku vyplněny všechny parametry, příchozí button/init:
Payload: {"merchantId":"M1MIPS7744","payId":"0c8983dadd2a7FC","brand":"csob","dttm":"20200304081759","signature":"......

je zde payID, které zde být nemá, a chybí další parametry viz. dokumentace:
https://github.com/csob/paymentgateway/wiki/Metody-pro-platebn%C3%AD-tla%C4%8D%C3%ADtko#metoda-buttoninit-

**Comment by janvalentik** [comment]
Dobrý den, ano, už víme kde je problém. viz https://github.com/ondrakoupil/csob/issues/28

Děkuji
