### ISSUE TITLE
500 Server Error when calling payment/refund

### ISSUE THREAD

**Issue by kyshnirev** [csob/paymentgateway#479]
When calling test api https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/refund , I get an http error 500. 

Request:

    PUT /api/v1.7/payment/refund HTTP/1.1
    Accept: application/json
    Accept-Charset: UTF-8
    User-Agent: Ktor client
    Content-Length: 436
    Content-Type: application/json
    Host: iapi.iplatebnibrana.csob.cz
    Connection: Keep-Alive
    {"merchantId":"M1MIPS....","payId":"c3e3d6b99834cFC","signature":"EKXK499yOt...","dttm":"20200317080414"}

Response:

    HTTP/1.1 500 Server Error
    Server: nginx
    Date: Tue, 17 Mar 2020 08:04:14 GMT
    Content-Length: 0
    Connection: keep-alive
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    Expires: 0
    Set-Cookie: BIGipServerasors_iplatebnibrana.csob.cz_6443_pool=sMbMJrmiLMdXJWbC5LzsjYGkm+v4euHRpEQbtm9Eh8x4qL+t5CP3gj88JI5UNw8h/eYqEA5jDYvZ2JYAAAAB; path=/; Httponly; Secure

**Comment by Mspisar** [comment]
Hello,

your request has been registered and forwarded to responsible service technician. You will be contacted as soon as possible.

best regards

Milan Spisar

**Comment by mrazekl** [comment]
Hi there,
can you please try it again? There was some trouble here which should be OK for now.

**Comment by kyshnirev** [comment]
The error is gone, thanks!
