### ISSUE TITLE
refundace a opakované platby

### ISSUE THREAD

**Issue by senik** [csob/paymentgateway#48]
Dobrý den,

rád bych se ještě zeptal na dvě věci:

1) Refundace - z dokumentace k API jsem pochopil, že automatizovaně jde provádět pouze úplné refundace, částečné je nutné provést ručně z rozhraní POS Merchant. Uvažujete o rozšíření protokolu tak, aby bylo možné provádět částečné refundace i přes API?

2) Opakované platby - zajímá nás funkcionalita jak opakovaných plateb, tak i stejná, jako má Česká Spořitelna, tj One Click Payments. V dokumentaci jsem žádnou zmínku nenašel, je možné, že jsem to přehlédl? Pokud ano, můžete mne nasměrovat? Pokud ne, budete protokol do budoucna o tyto funkce rozšiřovat?

Předem děkuji za odpovědi.

**Comment by senik** [comment]
Dobrý den,

chtěl bych se připomenou se svým dotazem, dnes do 12h bych potřeboval znát odpovědi.

Mockrát děkuji.

**Comment by kjanek73** [comment]
Dobrý den, 

v rámci implementace jsme narazili na stejný problém (částečná refundace). Prosím o stanovisko jestli bude podpořena a pokud ano kdy se tak stane. Implementujeme eAPI pro velkého zákazníka, který v současné době využívá této funkcionality (v rozhraní GPE) relativně masivně a pokud by bylo nutné toto provádět ručně přes POS Merchant, tak je to pro něj víceméně nepoužitelné. 

Děkuji za (pokud možno rychlejší) odpověď.

**Comment by senik** [comment]
Dobrý den,

chtěl bych se připomenout se svým dotazem.

Děkuji.

**Comment by senik** [comment]
Dobrý den,

rád bych se ještě zeptal na funkci multicurrency - jak přesně funguje a jak ji máme implementovat.

Děkuji.

**Comment by ratajskym** [comment]
Dobrý den,

@kjanek73 - Vámi zmiňované funkcionality byly implementovány viz [dokumentace](https://github.com/csob/paymentgateway/wiki/eAPI-1.5#popis-zm%C4%9Bn-od-eapi-v1)

@senik - nevím přesně jakou funkci máte na mysli, nicméně v inicializačním požadavku zasíláte měnu, ve které bude transakce provedena viz [dokumentace](https://github.com/csob/paymentgateway/wiki/eAPI-1.5#-post-httpsapiplatebnibranacsobczapiv15paymentinit-)
