### ISSUE TITLE
Payment not found - resultcode 140

### ISSUE THREAD

**Issue by Clon-cz** [csob/paymentgateway#480]
Dobry den,

u platby 351c903179affFC v M1MIPS1214 se mi nedari zjistit stav.
V posmerchantu ale platbu dohledam.

stejny problem mam i u 53fc17af77bd6FC v M1MIPS1243

pouzivame verzi 1.7

**Comment by Mspisar** [comment]
Dobrý den,

požadavek byl zaevidován a předán k řešení. Co nejdříve budete kontaktován s odpovědí.

s pozdravem

Spisar

**Comment by Clon-cz** [comment]
Omlouvam se, pristupoval jsem s testovacima udejame

**Comment by Mspisar** [comment]
Dobrý den,
ověřte si prosím řetězec, kterým požadovaný status vyvoláváte. V logu vidím, že zasíláte požadavky jak do testu, tak produkce.
s pozdravem
Spisar
