### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by DavidHromjak** [csob/paymentgateway#481]
Dobrý den, zkouším implementovat vaší platební bránu na woocommerce po vlastní ose a narážím na chybu 400, což je chyba syntaxe zápisu nebo adresy. Url na které posílám požadavek je "https://iapi.iplatebnibrana.csob.cz/api/v1.8".
Data které posílám: "merchantId": "A4484c41nc", "orderNo": 362, "dttm": "20200318172601", "payOperation": "payment", "payMethod": "card", "totalAmount": 2900, "currency": "CZK", "closePayment": false, "returnUrl": null, "returnMethod": "POST", "cart": [ { "name": "Shopping at ...", "quantity": 1, "amount": 2900, "description": "hihihi..." }, { "name": "Shipping", "quantity": 1, "amount": 0, "description": "PPL" } ], "merchantData": null, "language": "CZ", "customerId": 1, "signature": "VO94eQi0Yf4A1m8XNeemlF2wstKWBLdB0FzwgpykI1zYCOOQpZcTccRb+DzNo+D7rxtJrHL6VY7DWlv62iM3J6tPUz1kOgP3GB0FCGm9ImfTO3dkWpum/29J6dm6mK4v9df0UwzB9FEnxx

A4484c41nc|362|20200318172601|payment|card|2900|CZK|false||POST|Shopping at ...|1|2900|hihihi...|Shipping|1|0|PPL

Rád bych věděl, který údaj mám špatně, protože se mi na to zatím nepodařilo přijít,

**Comment by LucieSnedarova** [comment]
Dobrý den, 
Váš požadavek byl předán na odpovědného kolegu.
S pozdravem
Lucie Šnédarová

**Comment by mrazekl** [comment]
Dobrý den,
chyba byla v podpisu požadavku, to se vám, zdá se, podařilo včera vyřešit. V logu vidím úspěšný payment/init, který však není následovám metodou payment/process.
Obdržíte od platebni brány odpověď s hodnotou payID?
