### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by Rosnicka** [csob/paymentgateway#482]
V našem objednávkovém systému stabilně používáme platební bránu ČSOB, nicméně se nám aktuálně nedaří založit platbu na produkci metodou payment/init u klienta (klientské číslo M1MIPS8067). Brána v tomhle směru není moc sdílná a pošle akorát code 400. Posílám požadavek a odpověď brány. Prosím o prověření v čem by mohl být problém, děkuji.

request

```
{
  "data": {
    "cart": [
      {
        "amount": 200,
        "name": "Objednávka",
        "quantity": 1
      }
    ],
    "closePayment": true,
    "currency": "CZK",
    "customerId": "",
    "description": "Objednávka č. 200323002",
    "dttm": "20200323113055",
    "language": "CZ",
    "merchantData": "",
    "merchantId": "M1MIPS8067",
    "orderNo": "6",
    "payMethod": "card",
    "payOperation": "payment",
    "returnMethod": "POST",
    "returnUrl": "https://ugo-rozvoz.cz/csob/callback/hash/ed85c938b8ac0914c41744624d558b7f",
    "totalAmount": 200,
    "ttlSec": 581
  },
  "method": "POST",
  "queries": []
}
```

response
```

{
  "code": 400,
  "data": null,
  "headers": {
    "Cache-Control": "no-cache,no-store,must-revalidate",
    "Connection": "keep-alive",
    "Content-Length": "0",
    "Date": "Mon,23 Mar 2020 10:30:55 GMT",
    "Expires": "0",
    "Pragma": "no-cache",
    "Server": "nginx",
    "Set-Cookie": "BIGipServerasors_platebnibrana.csob.cz_6443_pool=sZb2eSDDmgC1HznC5LzsjYGkm+v4en1hxEnvt0qVt+zzcUKZMQ17E0XfO/8eW8uaNHLd/WDqgE+y+5EAAAAB; path=/; Httponly; Secure"
  },
  "time": 0.36270689964294434
}
```

**Comment by mbazant** [comment]
Dobrý den, předáno na odpovědného kolegu.  Evidováno jako TSGSMIPS-11222.
S pozdravem

Michal Bažant
IT support specialist

M +420 603 197 054
E servis@monetplus.cz

MONET+,a.s.
Za Dvorem 505,
763 14 Zlín - Štípa
Česká republika

www.monetplus.cz

**Comment by mrazekl** [comment]
Dobrý den,
v produkčním prostředí nemáme uložen veřejný klíč pro M1MIPS8067.
Zřejmě ani nebyly vygenerovány produkční klíče. Vygenerovat můžete zde:
https://platebnibrana.csob.cz/keygen/

Na email technické podpory poté obdržíte kód, který je potřeba vložit do PosMerchantu, sekce klíče.

**Comment by Rosnicka** [comment]
Dobrý den,
udělali jsme již druhé kolo generování produkčního klíče. Včetně zadání kódu do POSMerchantu. Stále končíme na stejné chybě. Poslední pokus byl v dnes cca v 16:05.

**Comment by mrazekl** [comment]
Číslo chyb je stejné, ale problém je jiný. Klíče už jsou nahrané, nyní máte chybu v podpisu požadavku. Používáte k šifrování podpisu privátní část klíče?( rsa_M1MIPS8067.pub)
Popřípadě můžete uvést řetězec, který podepisujete pro payment/init ze 16:05??

**Comment by Rosnicka** [comment]
Děkuji za navedení. Teď byla chyba u nás ve špatném klíči. Už je vše v pořádku.
