### ISSUE TITLE
Erorr 404

### ISSUE THREAD

**Issue by VSMarchenko** [csob/paymentgateway#483]
Dobrý den. Mám podobný problém jak i ostatní, chyba 404.
Prošel jsem veškeré brunche, řešení všude skoro stejné - public key neodpovídá private key.
Zkontroloval jsem u sebe toto několikrát a stále script mi vracejí chybu jak na integračním tak i na ostřem prostředí. Prosím, múžete se podívát, tady request a opdpověď, děkuji.

preparing payment init data ...

preparing cart data:
[
    {
        "name": "Shopping at ...",
        "quantity": 1,
        "amount": 40500,
        "description": "Italwax Filmwax zrnka vosku 1 kg..."
    },
    {
        "name": "Shipping",
        "quantity": 1,
        "amount": 9500,
        "description": "PPL"
    }
]

data to sign:
"M1MIPS1171|12312|20200324220326|payment|card|50000|CZK|false|https://oxisecret-eshop.com/|POST|Shopping at ...|1|40500|Italwax Filmwax zrnka vosku 1 kg...|Shipping|1|9500|PPL|11234|CZ"

prepared payment/init request:
{
    "merchantId": "M1MIPS1171",
    "orderNo": "12312",
    "dttm": "20200324220326",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 50000,
    "currency": "CZK",
    "closePayment": false,
    "returnUrl": "https://oxisecret-eshop.com/",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Shopping at ...",
            "quantity": 1,
            "amount": 40500,
            "description": "Italwax Filmwax zrnka vosku 1 kg..."
        },
        {
            "name": "Shipping",
            "quantity": 1,
            "amount": 9500,
            "description": "PPL"
        }
    ],
    "merchantData": null,
    "language": "CZ",
    "customerId": "11234",
    "signature": "jmj4deStKtPayNzQcUaEkms0yDVKJWg9pgRWOhVYlL+QIUqkIdPbTTe7OBNnqkCfz/SKEm8zgLnax6Igk03+RSZEFLDw92QgL9x5KWEvsDCM51nLPzaSiNUB2OXGqB4QDuz/FHibMBh4v9F/QBA2kzIwd3PKm6cVj7sO2Rpnfp1luMV9769p3nIQOCLl4QWXmDkDKx3LyBmSV9yCTi1KQslPcHitnOulJJubYybczvk5o4lkaRfTwB9sGN1pxlRiJ5pwbvcGIPE4yUqTUPWbdJlxOYGfu/3+qvEkm6J3GJNtxDT+YqYvl8jzBOHhlr49MoIw7ZV8/vNTNxTUKp0K7w=="
}

processing payment/init request ...

payment/init failed, http response: 404

**Comment by mrazekl** [comment]
Dobrý den,
vsadil bych na chybnou adresu platební brány. Na základě emailové komunikace na platebnibrana@csob.cz máte nastaveno:
$url = "https://api.platebnibrana.csob.cz/api/1.8";

chybí zde identifikátor verze eAPI "v", změňte na 
$url = "https://api.platebnibrana.csob.cz/api/**v**1.8";

a požadavek by měl být v pořádku odeslán.

**Comment by VSMarchenko** [comment]
Super, děkuji, měnil jsem různé verze (věděl jsem že chyba v odkazu), a na to "v" jsem uplně zapoměl :) 
Ticket je možné uzavřit.
