### ISSUE TITLE
Validní data pro dttm

### ISSUE THREAD

**Issue by Mikulas** [csob/paymentgateway#484]
> V této souvislosti bychom Vás chtěli upozornit, že aktuálně plníte parametr dttm nevalidními daty. Prosíme o kontrolu a úpravu na Vaší straně, je nutné vždy zasílat aktuální datum a čas.
 
Dobrý den,
v dokumentaci se pro parametr `dttm` nezmiňuje časová zóna. Předpokládáme teď UTC, kde není problém s DST a další drobnosti.

Prosím o upřesnění, z jaké časové zóny má být čas v `dttm` a jaká je tolerance.

**Comment by mjanek** [comment]
Dobrý den
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by ratajskym** [comment]
Dobrý den, 

na časové zóně ani na "úplně přesném" čase nezáleží. Důležitý je jen formát zaslaného data

> Datum a čas odeslání požadavku ve formátu YYYYMMDDHHMMSS.

**Comment by mrazekl** [comment]
Dobrý  den,
jen bych doplnil kolegu, aktuální tolerance je nastavena na + / -  130 minut.

**Comment by janbrasna** [comment]
Doplněno.
- [@csob/platebnibrana/wiki/Časté-technické-dotazy#jaké-časové-pásmo-použít-pro-vyplnění-hodnoty-parametru-dttm](https://github.com/csob/platebnibrana/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy#jak%C3%A9-%C4%8Dasov%C3%A9-p%C3%A1smo-pou%C5%BE%C3%ADt-pro-vypln%C4%9Bn%C3%AD-hodnoty-parametru-dttm)
- [@csob/platebnibrana/wiki/Volání-rozhraní-eAPI#dttm-validation](https://github.com/csob/platebnibrana/wiki/Vol%C3%A1n%C3%AD-rozhran%C3%AD-eAPI#dttm-validation)
