### ISSUE TITLE
Internal Error 900

### ISSUE THREAD

**Issue by turcovsky** [csob/paymentgateway#485]
Dobrý den, spravuju e-shop AuditWeb s.r.o a mám hlášení že přestala fungovat platební brána.

Nic se neměnilo a dostávám ResultCode 900: InternalError

Volání probíhá s následujícími daty:
"merchantId":"M1E3CB3639",
"orderNo":"209903497",
"dttm":"20200327134140",
"payOperation":"payment",
"payMethod":"card",
"totalAmount":"3000",
"currency":"CZK",
"closePayment":"true",
"returnUrl":"https://www.a-razitka.cz/exec/card/muzo/paymuzoapiback.aspx",
"returnMethod":"POST",
"cart":[{"name":"Nakup na e-shopu","quantity":"1","amount":"3000","description":"AuditWeb, s.r.o."}],
"description":"Nakup na e-shopu Audit-Web, s.r.o.",
"language":"CZ",
"signature":"mDN84VBHT8rEiRHl999fF7elIgf/7W6RphV7oTQyUzvMA0ECSs+dhkc1jAwAOjM0QUq8DtJtohQttFS4ybmOxY6+4MntZcqVjbK7iZE0eZ9VhQP1bUrbM9ScLSi/KlZdSLLTfKSQHhv5cixvpSurk79MrzkUAkPhw6yRv2vluGoC29lHPVtsX4rmhBHNDE5ZCAMqU6ovZ5U8AEEfeK4rbuco4ln6o5tmrej4mPnpq4LG3ItMNt/B1lBHnKIKQyTgPS8EKv+lsuPRksei8fvbi6Wdc9hzagtpH1VPSHpeq7z/ZNKirtCFihqCms1L5KZbkcISIjTOxRIdU2N1kKP8Ng=="

Můžete mi prosím zjistit, kde je problém? 
Děkuji

**Comment by hanuss** [comment]
Dobrý den, v návaznosti na rozeslaná upozornění všem našim obchodníkům byla včera na platební bráně ukončena podpora TLS 1.0 a TLS 1.1. Předpokládám, že by to mohlo souviset s tímto.

**Comment by turcovsky** [comment]
Měl jsem za to, že s tímto problém nemáme viz. řpiložený screen kde je vidět, že TLS 1.2 využíváme?
![AuditWeb_TLS1 2](https://user-images.githubusercontent.com/13586306/77774654-b92fd800-704b-11ea-954d-f7fa16ce485c.jpg)

**Comment by LucieSnedarova** [comment]
Dobrý den, 
Váš požadavek byl předán na odpovědného kolegu.
S pozdravem
Lucie Šnédarová

**Comment by ratajskym** [comment]
Dobrý den, můžete to vyzkoušet ještě jednou dnes ?

**Comment by turcovsky** [comment]
Dobrý den vyzkoušeno právě nyní a stále nefunkční. Děkuji

**Comment by ratajskym** [comment]
Zvláštní .. v čase 2020-03-28 07:50:27 vidím potvrzenou transakci. Order number 209903512

**Comment by turcovsky** [comment]
Můj test měl ale OrderNumber 209903514. Můžete se podívat jak dopadla tato transakce? Děkuji

**Comment by ratajskym** [comment]
Takové číslo objednávky v systému nemůžu najít. Prošel jsem i aplikační logy. Můžete dodat logy z Vaší strany? Můžu to nějak vyzkoušet / nasimulovat sám?

**Comment by turcovsky** [comment]
logy nemáme, nebo alespoň nevím kde je najít. Můžete si však nasimulovat sám. Máme na to testovací položku na shopu:
https://www.a-razitka.cz/vyroba-razitko/polozka-1-kc-dph/d-71401/
Po jejím zakoupení, na stránce s potvrzením objednávky jsou loga platebních karet na něž když se klikne, dochází k přesměrování na platební bránu. Můžete vyzkoušet.

**Comment by ratajskym** [comment]
Tak z toho testu bohužel nejde poznat vůbec nic, žádná chybová hláška. Bez logů z vaší strany se dál nepohneme

**Comment by turcovsky** [comment]
A můžete mi sdělit co by měl takový log obsahovat? Co je pro Vás klíčové aby jste byl schopni říct, proč vaše strana vrací resultCode:900?

**Comment by ratajskym** [comment]
Co se Vám vrátí na Váš požadavek, chybová hláška například. Tohle je důležité, abych dokázal identifikovat co je špatně. Pletbní brána běží. Z Vašeho merchant id dnes proběhly transakce. Tak je to prostě divné

**Comment by turcovsky** [comment]
Jediné co dostanu od Vás jako odpověď z API je 

{
    "resultCode": 900,
    "resultMessage": "Internal error"
}
Nic víc. Myslel jsem, že dle merchantId a ostatních údajů jste schopni identifikovat proč se vrací od Vás tento result.

Takže některé transakce jsou potvrzené, chápu to správně?

**Comment by ratajskym** [comment]
Pomohl by celý ten request, jako ve Vašem prvním komentáři včetně url na kterou to posíláte.

**Comment by turcovsky** [comment]
Můžete uzavřít, podařilo se vyřešit. Bylo způsobeno opravdu přechodem na TLS 1.2
