### ISSUE TITLE
POS Merchant - Detailní kódy zamítnutí transakce

### ISSUE THREAD

**Issue by JaroslavDuska** [csob/paymentgateway#486]
Dobrý den,
ozval se nám zákazník, kterému brána odmítá kartu a samozřejmě tvrdí, že jeho karta je v pořádku s dostatečnými prostředky. V aplikaci POS Merchant po vyhledání jeho neúspěšných transakcí je vyplněna platební metoda neznámá i když je tam číslo a typ karty a neznámé detailní kódy zamítnutí 304 a 702. Prosím o informaci, kde se dozvím význam těchto kódů, v manuálu k aplikaci POS Merchant jsem nic takového nenašel. Variabilní symboly transakcí: 195529676, 195529680, MerchantId: M1MIPS7116
Děkuji

**Comment by JaroslavDuska** [comment]
Ještě přikládám další dvě objednávky, kdy není v aplikaci POS Merchant kromě "zamítnuto" vůbec nic, jak máme potom zákazníkovi odpovědět na dotaz, proč mu brána kartu nepříjímá?
MerchantId: M1MIPS7116
Transakce s variabilními symboly: 195529808, 195529841

**Comment by mbazant** [comment]
Dobrý den,

Váš požadavek byl zaevidován pod: TSGSMIPS-11317 a předán k řešení. O dalším 
průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

Michal Bažant
IT support specialist

M +420 603 197 054
E servis@monetplus.cz

MONET+,a.s.
Za Dvorem 505,
763 14 Zlín - Štípa
Česká republika

www.monetplus.cz

**Comment by Mspisar** [comment]
Dobrý den,

dle logu objednávek, se vždy jedná o ukončení ve fázi přesměrování na 3ds vydavatelské banky zákazníka a to dle dostupných informací DEUTSCHE BANK AG. Domnívám se, že chyba je na jejich straně.

s pozdravem

Spisar
