### ISSUE TITLE
API v1.6 oneclick/init vrací HTTP 500 Server Error

### ISSUE THREAD

**Issue by hernest** [csob/paymentgateway#488]
Dobrý den,

používáme stále ještě API v1.6 a nedávno jsme zaznamenali zvýšený počet zamítnutých opakovaných (oneclick) transakcí. POS Merchant u nich neuvádí vůbec žádné detaily (Platební metoda Neznámá).
Jsou to transakce s variabilním symbolem např. 17503, 17516. merchantId je M1E3CB2232.

Platby kartou fungují v pořádku, jen pokusy o stažení oneclick plateb se nezdaří. Volání `POST /api/v1.6/payment/oneclick/init HTTP/1.1` vrací `HTTP/1.1 500 Server Error` bez nějakých dalších detailů.   Totéž se děje i na testovací platební bráně. 

Díky za nasměrování

**Comment by Mspisar** [comment]
Dobrý den,

požadavek jsme zaevidovali a po prověření odpovědným kolegou budete neprodleně kontaktován.

s pozdravem

Spisar

**Comment by mrazekl** [comment]
Dobrý den,
objevil jste drobný bug, kdy v rozporu s dokumentací při payment/oneclick/init byl vyžadován i nepovinný parametr totalAmount + currency.
V testovacím prostředí je již opraveno, v produkčním prostředí bude opraveno zkraje příštího týdne.

**Comment by hernest** [comment]
Dobrý den,
potvrzuji, v testovacím prostředí nám to již opravdu funguje.

Díky za rychlou opravu
