### ISSUE TITLE
API v1.8 payment/init vracia HTTP 400 BadRequest

### ISSUE THREAD

**Issue by maros-852** [csob/paymentgateway#489]
Dobry den, 

implementujem pre nasu firmu CSOB platobnu branu v jazyku C#. Stiahol som si vase priklady implementacii a vygeneroval som si aj kluce na testovanie. Ale pri POST metode payment/init mi server vracia 400 Bad request. EchoGet a EchoPost mi idu. 
Prikladam json a pod nim aj vysledok funkcie toSign: 

```json
{
    "orderNo": "5547",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 1789600,
    "currency": "CZK",
    "closePayment": true,
    "returnUrl": "https://vasobchod.cz/return-gateway",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Nákup: vasobchod.cz",
            "quantity": 1,
            "amount": 1789600,
            "description": "Lenovo ThinkPad Edge E540"
        },
        {
            "name": "Poštovné",
            "quantity": 1,
            "amount": 0,
            "description": "Doprava PPL"
        }
    ],
    "description": "Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)",
    "merchantData": "c29tZS1iYXNlNjQtZW5jb2RlZC1tZXJjaGFudC1kYXRh",
    "language": "CZ",
    "ttlSec": 300,
    "logoVersion": 0,
    "colorSchemeVersion": 0,
    "merchantId": "A4573XSfH7",
    "dttm": "20200423151124",
    "signature": "GPkvwUIDYsXaXYcUL9VjmTtGojMFC2tgiLt1CaTcke9Gj135acFMwGdiT0rpAwWlXHA8gkUHH99jIz3pJQ3IAMIFk0F7iPuh/0hONkOy9NTkRAhpE0HU4DzJcTlQsWnaJuG+HxqVlaDV0Snpn5Iqr6nXADF9tr1PJw4BkNpG2gvg0hFaGu8QuwEy+RyKctjl0WOtlfb7T7iysDkU1M38iKULURRW5b6yvqHy0B+WA3gody6kx8KWlb4LHiPHQVAYiDO1YOkOdBjJxtI4FeVjYjpx1l0WIPaI6n8MdcvfiLJH0FMHp03WpQqaNVPsbSYNCuY9DQx7jz2slhG8sI1H1w=="
}
```
Vysledok funkcie toSign():

<pre>A4573XSfH7|5547|20200423165919|payment|card|1789600|CZK|true|https://vasobchod.cz/return-gateway|POST|Nákup: vasobchod.cz|1|1789600|Lenovo ThinkPad Edge E540|Poštovné|1|0|Doprava PPL|Nákup na vasobchod.cz (Lenovo ThinkPad Edge E540, Doprava PPL)|c29tZS1iYXNlNjQtZW5jb2RlZC1tZXJjaGFudC1kYXRh|CZ|300|0|0</pre>

**Comment by Mspisar** [comment]
Dobrý den,
Váš požadavek jsme zaevidovali a předali k řešení odpovědnému kolegovi. 
s pozdravem
Spisar

**Comment by mrazekl** [comment]
Dobrý den,
pokud používáte verzi eAPI 1.8, odeberte z payment/init požadavku parametr description. Od této verze již není podporován.

**Comment by maros-852** [comment]
dakujem uz to funguje
