### ISSUE TITLE
Zobrazení referenčního čísla objednávky v přehledu transakcí

### ISSUE THREAD

**Issue by techi602** [csob/paymentgateway#49]
Dobrý den,

Zarazilo mne, že parametr `orderNo`, tedy *Referenční číslo objednávky využívané pro párování plateb, které bude uvedeno také na výpisu z banky.*
není po dokončení platby nikde uvedeno v přehledu transakcí platební brány v systému POSMerchant. Jako zobrazované číslo objednávky je uvedeno pouze jednoznačné ID platby `payId`.
Jediná možnost jak zobrazit interní číslo objednávky u transakce je vložit ho navíc také do textové poznámky. Ta se zobrazí ale až po rozkliknutí detailu transakce a nelze podle ní filtrovat/vyhledávat.

Nebylo by možné referenční číslo objednávky zobrazovat v přehledu transakcí? Nebo jsem tuto funkci přehlédl?

Děkuji za odpověď

**Comment by dmarek** [comment]
Parametr `orderNo` z eAPI se v aplikaci POSMerchant zobrazuje v přehledu transakcí ve slouci Variabilní symbol

Doplníme přesnější znění do dokumentace, nyní je to v eAPI specifikaci popsáno takto ...

*Referenční číslo objednávky přiděluje e-shop obchodníka. Ve výsledku se referenční číslo objednávky objeví na výpisu transakcí z banky. Použije se tedy v systému obchodníka (účetnictví) pro párování plateb e-shopu proti bankovnímu účtu a musí tedy splňovat podmínku variabilního symbolu - numerickou hodnotu o maximálně deseti místech.*
