### ISSUE TITLE
Proces validace při iframe implementaci

### ISSUE THREAD

**Issue by adamspyboy** [csob/paymentgateway#490]
Dobrý den,

máme naimplementovanou bránu metodou zobrazení v iframe nad e-shopem a nyní potřebujeme projít procesem validace pro přechod do produkčního prostředí. Všechny typy transakcí již máme provedené, až na platbu zrušenou uživatelem. Nevíme, jak tuto transakci provést, protože v iframe verzi není tlačítko pro zrušení transakce zákazníkem.

Mohu požádat o radu, jak máme postupovat, abychom mohli proces validace dokončit?

Děkuji.

**Comment by kkolarikova** [comment]
Dobrý den,
předáno na odpovědného kolegu.
S pozdravem Kolaříková Kateřina

**Comment by mrazekl** [comment]
Dobrý den,
pokud máte implementováno pouze zobrazení platební brány v iFrame, zašlete žádost o aktivaci do produkčního prostředí na email akceptacekaret@csob.cz a odvolejte se na tuto skutečnost, spolu s tím uveďte v žádosti i vaše IČO a merchant ID.

**Comment by adamspyboy** [comment]
Dobrý den,

moc děkuji, vše proběhlo v pořádku.
