### ISSUE TITLE
transakce se nedokončí

### ISSUE THREAD

**Issue by jakub-isols** [csob/paymentgateway#491]
Dobrý den,
 V posledních dnech se nám množí stížnosti od zákazníků na nemožnost dokončit platbu (samozřejmě tvrdí že s kartou je vše v pořádku, banka o ničem neví a jinde se jim daří zaplatit bez problémů). V aplikaci POSMerchant k daným transakcím nelze dohledat detaily krom samotného založení transakce, z vlastních logů jen víme že by se nemělo jednat o chybu při komunikaci obchod - brána. Kde bychom prosím mohli dohledat detaily k daným transakcím? Nemůže se jednat o nějakou chybu na Vaší straně? 

příklady objednávek které takto nebyly dokončeny  (pay_id):
460153d48b1d7FD
98d9394fa0201FD
075699fb26283FD
234795e57d699FD
5d2ab73279cf8FD
39eb34f1b97fbFD

MerchantID: M1MIPS7062

Předem děkuji.

**Comment by Mspisar** [comment]
Dobrý den,
požadavek jsme zaznamenali a již je v řešení. O dalším postupu budete informován.
s pozdravem
Spisar

**Comment by Mspisar** [comment]
Dobrý den,
výsledky u vašich uvedených plateb:
460153d48b1d7FD - zde skončilo proces u přesměrování na platební bránu
98d9394fa0201FD - návrat zákazníka z 3DS ověření nestandardní cestou ( tlačítko zpět atd )
075699fb26283FD - neznámý BIN karty
234795e57d699FD - zákazník přesměrován na 3DS dále stav neznámý - již mimo platební bránu
5d2ab73279cf8FD  - návrat zákazníka z 3DS ověření nestandardní cestou ( tlačítko zpět atd )
39eb34f1b97fbFD - zamítnuto na 3DS ověření

Většina tedy na straně zákazníků, nebo jejich banky.

s pozdravem

Spisar

**Comment by jakub-isols** [comment]
Moc děkuji za rychlou odpověď. Existuje prosím způsob jakým bychom si takovéto informace mohli dohledávat sami, bez nutnosti zakládání ticketů k vám?

**Comment by Mspisar** [comment]
V posmerchantu máte u transakcí sloupec mcodes. Po najetí myší na kód vidíte stav v kterém objednávka skončila.
