### ISSUE TITLE
Chyby ve v1.8 examples

### ISSUE THREAD

**Issue by JanSlahar** [csob/paymentgateway#493]
Dobrý den, příklad obsahuje další chyby.
Rád bych ušetřil čas ostatním.

- pro CallOneClickInitAsync není potřeba paymentId
- payment-oneclick-base.json obsahuje "description"
- přejmenovat "payment/oneclick/init" na "oneclick/init"
- přejmenovat "payment/oneclick/start" na "oneclick/start"
- přejmenovat "customer/info" na "echo/customer

**Comment by mrazekl** [comment]
Dobrý den,
děkujeme za vaší iniciativu. 
payment-oneclick-base.json - je změněno. Ostatní nedostatky jsme oslovili vlastníka integračních příkladů o korekci.

**Comment by kasparkova-arion** [comment]
pridavam chybu v prikladu implementace, kde object pro volani init obsahuje Description (vcetne ToSign() ). Priklad funguje protoze ukazkovy json Description neobsahuje. Volani endpointu s Description vraci Bad request.
