### ISSUE TITLE
e-mailová zpráva "Platební brána ČSOB - plnění parametru dttm"

### ISSUE THREAD

**Issue by JaroslavDuska** [csob/paymentgateway#494]
Dobrý den,
obdržel jsem od vás zprávu "V této souvislosti bychom Vás chtěli upozornit, že aktuálně plníte parametr dttm nevalidními daty.", ale všechny naše požadavky obsahují parametr dttm s vyplněným datumem a časem ve formátu "yyyyMMddHHmmss" (MerchantId: M1MIPS7116). Mohli byste mi prosím napsat konkrétněji, v jakém typu požadavku od nás evidujete špatně vyplněný parametr?
Děkuji

**Comment by Mspisar** [comment]
Dobrý den,

požadavek jsme zaevidovali a předali k řešení. O dalším postupu budete informován.

s pozdravem

Spisar

**Comment by mrazekl** [comment]
Dobrý den,

poslední výskyt u vás evidujeme 28.04, kdy byl na platební bránu přijat payment/process:

paymentProcess request M1MIPS7116 / 0c471a31746adFD

WARN_DTTM M1MIPS7116/20200424095330

který se odvolával na payment/init ze 24.04, včetně parametru dttm:
24.04.2020 09:53:30.008 Received paymentInit request M1MIPS7116 / 0c471a31746adFD, orderNo 195532812

který byl stornován ze strany zákazníka.

**Comment by JaroslavDuska** [comment]
Děkuji za objasnění, čas požadavku payment/process je tedy ve vteřinách stejný jako payment/init, který je ovšem volán o osm tisícin vteřiny později. Parametr dttm je ale vždy vyplněn jen na úroveň vteřin, kde se v porovnání vzalo těch .008s navíc?

**Comment by mrazekl** [comment]
Dobrý den,
to je záznam z logu, který se loguje až na úroveň tisícin sekundy. Parametr dttm je udáván jen ve vteřinách, jak píšete.

**Comment by JaroslavDuska** [comment]
Nerozumím tedy kde je chyba, požadavek payment/init a payment/process nastal ve stejnou vteřinu, to by snad nemělo vyvolat varování a zablokování požadavku. Požadavek payment/process je vytvořen vždy až po odpovědi payment/init s responsecode 200.

**Comment by mrazekl** [comment]
chyba je v tom, že dne 28.04 byl přijat payment/process s dttm: 20200424095330

**Comment by JaroslavDuska** [comment]
Omlouvám se, datum 28. 4. jsem si nespojil s problémovým požadavkem payment/process, v logu požadavků mám payid 0c471a31746adFD jen ze dne 24. 4. a 28. 4. požadavek s payid 0c471a31746adFD zalogovaný nemáme, takže jsem hledal chybu jinde. V případě takové anomálie je zakázání požadavku samozřejmě v pořádku, děkuji za vaši pomoc.
