### ISSUE TITLE
MallPay error 120 merchant blocked

### ISSUE THREAD

**Issue by hubipe** [csob/paymentgateway#495]
Dobrý den,
bohužel jsem v dokumentaci nenašel žádný kontakt na podporu, proto zakládám zde jako issue. Při volání metody mallpay/init v testovacím prostředí vrací platební brána Merchant blocked:

```
dttm => "20200515122610" (14)
signature => "MyUq+w3lrqE0aeCILjAjQ8Ke3cZHjofVX8oVrA/nDEkPTPFQW5nWYlo+tU3HaGV4+p90IozZvNRrIWOGusKgW8SCQ+YaE85FT/wLpY6ucuEOkXgFj9YbikNMEgZVuvw00z/4vwzVz4e+Hvqd11jGJQ ... " (344)
payId => "e01cb83bb7899FE" (15)
resultCode => 120
resultMessage => "Merchant blocked" (16)
paymentStatus => 6
```

Co je to přesně za chybu a jak ji odstranit?

Děkuji

**Comment by kkolarikova** [comment]
Dobrý den,
předáno na odpovědného kolegu.
S pozdravem Kolaříková Kateřina

**Comment by kkolarikova** [comment]
Dobrý den, 

používáte anonymní merchant  id A4647urCw4, pro které nemůže být mallpay aktivováno.
To může být aktivováno pouze pro oficiální merchant ID.

S pozdravem Kolaříková Kateřina

**Comment by hubipe** [comment]
Dobrý den,
děkuji za osvětlení. Můžete mi, prosím, ještě ověřit, zda-li je mallpay aktivováno pro merchant ID M1MIPS0171 a případně rovnou aktivovat?

A pokud byste mohli, tak nahráli do testovacího prostředí tento veřejný klíč? 

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmBefEJlRkdJEImPHmres
8gojxLSZSuqWeBijx4lN8Vj6r1u4s41UwvyWu0zyEbeRh/HUZyADk8d4EopTQXBQ
eZc/AdtVzzaw6x5Fxx9ucQE6WnxhwUdMTEFDj4TCKsvzPaDksaeGwEFQ/Yp/2+gh
nlMQW8wKtbXpO3n5j7Xz/+EV60n9NwxXZCTKRhH0J9XdEDpFVwRLWcxL0TLLQCQ7
J77L+EvWqDTiymAEdh7wOWQY3huty9YYdpGyfFucTKM2Jp1psuVggAyJ3xiuxHD/
ZgWl6Xuk6MfRwxeMI6cRyQINxDQkTBv033Rr43/uD3qm+HgSpWlvfFNUn32y9t53
nwIDAQAB
-----END PUBLIC KEY-----
```

Děkuji

S pozdravem
Petr Hubík

**Comment by kkolarikova** [comment]
Dobrý den, 

pro ID M1MIPS0171 je mallpay aktivován. 
Klíč do testovacího prostředí si můžete nahrát sami zde: https://iplatebnibrana.csob.cz/keygen/ 

S pozdravem Kolaříková Kateřina

**Comment by hubipe** [comment]
Děkuju
