### ISSUE TITLE
Problém s platební bránou a parametrem dttm

### ISSUE THREAD

**Issue by Katkasss** [csob/paymentgateway#497]
Dobrý den, 
přišel mi email s tímto zadáním:
z důvodu zvýšení bezpečnosti bude platební brána nově kontrolovat parametr dttm (datum a čas odeslání požadavku), který je součástí volání metod API. V této souvislosti bychom Vás chtěli upozornit, že aktuálně plníte parametr dttm nevalidními daty.
Doporučujeme zkontrolovat všechna volání na platební bránu, nikoliv pouze metodu payment/init pro založení transakce, kde ve většině případů bude dttm plněn korektně, ale zjm. navazující operace payment/status či payment/proces, kde může být parametr dttm chybně přebírán právě z metody payment/init.

Webový technik mi zkontroloval a jeho odpověď:
V parametru dttm se posílá např toto: 20200520131534, dle vašeho formátu YYYYMMDDHHMMSS.
Pokud je tento formát špatně, tak prosím o zaslání přesnější informace, při jaké operaci posíláme špatné údaje a nejlépe konkrétní ukázku špatného údaje (formátu).

Další odpověď mě odkázala sem. Můžete mi tedy prosím poradit nebo se mám obrátit znovu na někoho jiného???? Změny musí být implementovány do 27.5.
Díky za pomoc,
Katka

**Comment by mrazekl** [comment]
Dobrý den,
formát se nemění, pouze od 27.5 bude nutné v tomto parametru zasílat platné aktuální datum s tolerancí +/- 125 minut z důvodu časových pásem.
Například pokud zašlete dne 21.05.2020 12:00 požadavek, kde bude dttm vyplněno hodnotou   20200520131534 , bude tento požadavek vyhodnocen jako nevalidní.

Pokud chcete konkrétní ukázku, uveďte vaše merchant ID.
