### ISSUE TITLE
Špatné variabilní číslo objednávky

### ISSUE THREAD

**Issue by DomFinta** [csob/paymentgateway#498]
Dobrý den, 
využíváme Vaši platební bránu pro klienta a objevila se nám stížnost, že variabilní symbol objednávky nesedí s číslem objednávky. Jedná se o WordPress e-shop. Při platbě se do VS generuje desetimístné číslo, které nejsem schopný najít v DB, ani .log souboru.

Dokázali byste mi prosím poradit, jak toto vyřešit, nebo jak vložit číslo objednávky, jako poznámku k platbě?

Předem děkuji za pomoc.
S pozdravem,
Dominik Finta.

**Comment by mrazekl** [comment]
Dobrý den,
pokud používáte woocommerce plugin, ten si zřejmě generuje čísla objednávek sám, takže se mu můžete jen přizpůsobit a generovat shoné orderNo.
Pokud se jedná o vložení poznámky, mohl by vám posloužit parametr merchant data:
"Libovolná pomocná data, která budou vrácena ve zpětném redirectu z  platební brány na stránku obchodníka. Mohou sloužit např. pro udržení  kontinuity procesu na e-shopu, musí být kódována v BASE64. Maximální  délka po zakódování 255 znaků."
viz. https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody#metoda-paymentinit-

**Comment by DomFinta** [comment]
Problém je v tom, že posíláme order number ("orderNo":"5154") a v platbě se zobrazuje VS 0222150520 (zřejmě timestamp). Nevíte, čím to je?

**Comment by mrazekl** [comment]
mohl by jste uvést vaše merchantID?

**Comment by DomFinta** [comment]
M1MIPS8243

**Comment by DomFinta** [comment]
Jak docílíme toho, aby bankovní VS byl 5154?

**Comment by mrazekl** [comment]
Tenhle požadavek je nesplnitelný. Můžete zkusit zjistit možnosti na akceptacekaret@csob.cz

**Comment by janbrasna** [comment]
Vice informaci v issue c.: https://github.com/csob/paymentgateway/issues/175#issuecomment-334077699
