### ISSUE TITLE
Nedaří se poslat request - od 22.5.2020

### ISSUE THREAD

**Issue by MarekGrossman** [csob/paymentgateway#499]
Dobrý den,
do minulého čtvrtka (22.5.2020) mi fungovala bez problémů brána/rozhraní pro práci s karetními platbami na adrese "http://api.platebnibrana.csob.cz/api/v1.6", ale od pátku je nefunkční.

Vygeneroval jsem si nové klíče, ale ani toto nepomohlo (pro platby přes https://3dsecure.gpwebpay.com/webservices/services/pgw 
nové klíče fungují).

Nevíte co se mohlo změnit? Případně nedokážete někde v log souboru dohledat jestli posílám něco špatně (ale nejsem si vědom žádné změny v kódu kolem plateb)?

Komunikaci testuji pomocí metody "echo" a poslední pokus byl:
---------------------------------------------------------------------------------------
z IP : 212.47.30.193
na : http://api.platebnibrana.csob.cz/api/v1.6/echo
---------------------------------------------------------------------------------------

Ano, asi dělám něco špatně, ale proč to po několika letech přestalo 21.5. fungovat?

Děkuji za pomoc

**Comment by Mspisar** [comment]
Dobrý den,
požadavek jsme zaevidovali a již je v řešení. Po ověření budete kontaktován.
s pozdravem
Spisar

**Comment by Mspisar** [comment]
merchant ID platební brány je M1MIPS1618 ?
děkui
Spisar

**Comment by MarekGrossman** [comment]
Pardon, nenapsal jsem to.

JSON data requestu : {"merchantId":"M1E3CB0429","dttm":"20200525231901","signature":"*********************************************************************************=="}

Asi mám špatně vygenerovaný podpis, protože ho generuji jinak než pro bránu goPay (načítám private key bez hesla), ale proč to do čtvrtka fungovalo?-)

Mareg

**Comment by MarekGrossman** [comment]
Nejsem si jistý, jestli je vhodné posílat sem i ten podpis, pokud ano, pošlu Vám jej.

**Comment by mrazekl** [comment]
Dobrý den,
chtěl bych si v tom udělat jasno. 
Dle našich záznamů vám echo požadavek neprochází na integračním(testovacím) prostředí - https://iapi.iplatebnibrana.csob.cz 
Zde jste si generoval klíče naposled v roce 2016
Je nutné rozlišovat produkční a testovací prostředí, pro každé prostředí musíte použít odlišný klíč, kterým šifrujete podpis.
Navíc, pokud požadavek odesíláte na verzi API < v1.8 používá se algoritmus SHA-1
pro API v1.8 algoritmus  SHA-256

**Comment by MarekGrossman** [comment]
Aha, takže při pokusech na bránu https://iapi.iplatebnibrana.csob.cz používám špatné (nové) klíče, protože to jsou klíče vygenerované přes tento portál: https://platebnibrana.csob.cz/keygen/ a mám použít testovací klíče z roku 2016. 

Nicméně stále mi vrtá hlavou, proč to od pátku přestalo fungovat? Vy jste nic neměnili? Jakou dobu platnosti mají ty ostré klíče - mohla vypršet platnost? Ale při platbách na goPay nám fungovaly.

**Comment by mrazekl** [comment]
ano, shrnul jste to správně. Pokud chcete generovat testovací klíče, použijte tento odkaz:
https://iplatebnibrana.csob.cz/keygen/
Klíče mají neomezenou platnost, zneplatníte je však vygenerováním nových klíčů, to se vám dle popisu podařilo v produkčním prostředí. Zde vám ale platby prochází, takže jste si s tím poradil.

Na platební bráně se nic neměnilo, ale otázka zní, kam jste vůbec echo požadavky odesílal, protože na testovacím prostředí od ledna 2020 jsou zalogovány až pokusy ze 25.května.
V produkci také neevidujem žádný nevalidní echo požadavek.

**Comment by MarekGrossman** [comment]
No pokusy (špatné, jak jsme si vysvětlili) jsem tento rok posílal až od toho 25. , po té co nám přestalo ( po letech ) fungovat produkční prostředí.
Já ani kolega jsme na serveru nic (alespoň mi to tvrdí) neměnili, tak nevím proč to přestalo fungovat. Ale něco se změnit muselo, tak buď jsme do toho nevědomky šáhli, nebo se stalo něco u vás.
Můžete se podívat do logů v produkci. co se od 22.5. pro naše merchantid nedařilo? Jestli se nám podaří zjistit proč nám to přestalo fungovat?
Děkuji

**Comment by mrazekl** [comment]
zjistil jsem, kde je problém. A není stále vyřešen. Od 22.05 nepřijímáme žádné požadavky payment/close, které slouží k zařazení transakcí do zaúčtování. Bez tohoto uzavření budou po 7-mi dnech automaticky vráceny prostředky na účet zákazníka.  
od 22.05 cca. 16:54 neevidujem žádný takový příchozí požadavek, na platební bráně se nic neměnilo
Než to u sebe vyřešíte, doporučuji uzavřít transakce ručně přes systém PosMerchant, jinak budou vráceny zákazníkům.

**Comment by MarekGrossman** [comment]
Tak nevím.
Při pokusech jsem měl špatně nastavené URL* ( ale to až při těch pokusech, když se dívám do záloh, tak všechny dny zpátky je tam správné). Když jsem URL opravil, tak mi na ostré bráně funguje metoda echo a payment/close. Nefunguje mi payment/status ( asi tam mám něco blbě).

Na testovací bráně mi funguje echo. Jak otestovat další funkce, když nevím payId zatím nevím.
Jaké přihlašovací údaje mám použít pro přihlášení na https://iposman.iplatebnibrana.csob.cz/posmerchant?

*) iapi.iplatebnibrana.csob.cz vs. api.platebnibrana.csob.cz je fakt zákeřné :-) Atomaticky jsem čekal "i" jen v tom "iapi".

Děkuji za pomoc a omlouvám se, že jsem otravoval, chyba při testování byla na mé straně.
Jen stále nevím, proč to přestalo z ničeno nic fungovat a už se to asi ani nedozvím :-(.
Že by nějaký problém s DNS, nebo firewallem?

--
Mareg

**Comment by mrazekl** [comment]
ad payment/status - ujistěte se, že posíláte aktuální dttm parametr, musí být aktuální s tolerancí +/- 125 minut

ad iposman - přihlašovací login je ičo, heslo neznáme, případně požádejte akceptacekaret@csob.cz o reset hesla

z jakého důvodu to přestalo fungovat, něco se muselo změnit na vaší straně, s tím vám nemáme jak pomoci

**Comment by MarekGrossman** [comment]
payment/status - zkontroluji, ale v echu se posílá také a to mi funguje

Jasně, já vím, že s tím mi už nepomůžete. Začal jsme prostě hledat blbě.

Díky

**Comment by mrazekl** [comment]
ano ale echo vytváříte nový request
kdežto ve statusu spousta ocbchodníků přebírá hodnotu dttm z požadavku, jehož status zjišťuje a tedy ve dnešním statusu na včerejší payment/init zasílá včerejší dttm
