### ISSUE TITLE
Getting error Invalid parameter resultCode 110

### ISSUE THREAD

**Issue by krunal131987** [csob/paymentgateway#5]
Payment Init url,
"https://iapi.iplatebnibrana.csob.cz/api/v1/payment/init"

here is my request,
{"merchantId":"A1050uj4XS","orderNo":"59","dttm":"20150604144955","payOperation":"payment","payMethod":"card","totalAmount":6,"currency":"USD","closePayment":true,"cart":[{"name":"Order of photos","quantity":1,"amount":6,"description":"PrintPix - photos printing"}],"description":"PrintPix APP order 59","language":"EN","returnUrl":"https:\/\/www.print-pix.eu\/functions\/csob_return_payment\/","returnMethod":"POST","signature":"omNnGiZTPR+vLBjkYAOim5kBRtOc4hOhvKosayTu4uNY3xuV9gwjjf+na7F\/VMMHQ6kfDQTi9RmIl7qbzJ8QbFa+2JY5f2aKuHwDQ\/lIEptZBx3vIOHAcHeH3zquVp3dC36CQh7skzZvv7NcmUtmnu2kiwO+ujXczdsbSSCjyc+DTeUU5e69J\/DCMr5y+xJHkJ1UBpsRoxE5O2bJJI3P2lkTZEgQsBjDlVwP7R6WEVMSr2cicO\/f79Ct\/7ZiN0rDiq1vSt4ZbV3hvNlzHliCkkSHoIxyRIGQHchFoKTcoMIt6FBNe50gsQbE6TSHeg9VlAaqsPDUmWbrwtF1x5PMRw=="}

getting response from server,
{"dttm":"20150604112124","signature":"YZeRGUcUGyNfRGYMafqLMw/y1howQVgGXGZF7NtrhDdboNAwSEKmRrP5Z4pHbkwvMJplqD7LQuUHB0hoZTvojWOl3uE+MG81Z07HWl5fAI46Jvf/QHe3EeCIJI/ETIsGSpIzps8CsHIUjiLDHiLd4MrZlJijjjIUa8hGLImgDuR6xaGaeH3e0WjQZQGuRy8EC9sby2ORPsnNGO2A9XXqCICWyzhb0T8l7Ic68o8jh+wK87oAp6w5jLjCXkjJbhhSnBt9iEuPgoujNOGZ9ovr3qy5kAWtYb5tFn2iaQFp+dGhFrgTQs6s0bhreubfDIR6aAxeMbRQZ2XLVE7bF8+67A==","payId":"5683502235c044c","resultCode":110,"resultMessage":"Invalid parameter","paymentStatus":6}

Please, tell why this error occured,

Thank you,
Krunal

**Comment by dmarek** [comment]
fixed configuration on integration env, missing exchange rate for USD currency, please try again.
