### ISSUE TITLE
Barvy platebni brany

### ISSUE THREAD

**Issue by Lumeriol** [csob/paymentgateway#50]
Po precteni specifikace barevneho schematu jsme vytvorili schema tak, jak by melo byt. Ovsem pri testech na zkusebni brane je to odlisne:

Barva 1 pro pismo kontaktu ovlivnuje i barvu fontu tlacitka pro zruseni transakce (dle wiki ma byt vzdy cerna a pozadi tak co nejsvetlejsi) a prehled o nakoupenych polozkach (kde pozadi je stale bile a s nasim bilym pismem to tak splyva). I pres tyto nedostatky bylo nase schema schvaleno na produkcnim prostredi jako vhodne.

Jak je to tedy s barvami pisma?

**Comment by dmarek** [comment]
muzete prosim poslat bud merchantId anebo vase barevne schema? Diky!

**Comment by Lumeriol** [comment]
Barva 1: ffffff
Barva 2: 3e2f20
Barva 3: 3e2f20
Barva 4: 985017
Barva 5: 63ca25
Barva 6: 63ca25

MerchantId: M1MIPS0046
Původně měla být barva 5 a 6 definována jako ff0000, ovšem s černým textem by byla nečitelná, proto jsme ji nedávali.
Také na wiki píšete, že může být definováno více barevných schémat -- tato možnost ovšem v rozhraní není, pouze odstranit nebo aktivovat zadané.

**Comment by Lumeriol** [comment]
Nějaké informace ohledně tohoto problému?

**Comment by ratajskym** [comment]
Dobrý den, 

dokumentace předběhla dobu. Více barevných schémat je teprve ve fázi přípravy. V aktuální verzi platební brány je podporováno pouze jedno schéma.

**Comment by Lumeriol** [comment]
A co se týká nečitelnosti barevného schématu s danými barvami? Respektive ohledně první barvy, která ovlivňuje i výpis zboží, což by podle dokumentace neměla?

**Comment by ozaoral** [comment]
Dobré odpoledne, omlouváme se za chybějící informaci v dokumentaci, že barva košíku je vždy bílá a barva 1 nastavuje i písmo v košíku. Dokumentace je již opravena. U barvy písma košíku a bílého pozadí košíku na desktopu je ještě souvislost s mobilem - tam se košík rozbaluje a jeho pozadí je barva 2. Je proto nutné zvolit barvy 1 a 2 tak, aby 1 byla čitelná na bílém pozadí desktopu i na barvě 2 na mobilu. Toto je již v opravené dokumentaci taky popsáno. 

Ješte jednou se omlouvám za tuto díru v dokumentaci. Košík jako funkce se bude v dalších verzích hodně rozvíjet, i produkty typu MasterPass na něj kladou důraz. S dovolením budeme používat i Vaše schéma pro budoucí pilotní testování (v letošním pilotu neměl žádný obchodník takto kontrastní barvy, takže se na tu chybu nepřišlo), abychom Vám dokázali kompletní schéma nabídnout. Momentálně je řešením volba barvy 1 tak, aby byla vidět jak na bílém pozadí, tak na barvě 2 (desktop kontakty, mobilní košík).
