### ISSUE TITLE
Nedaří se ukončit práci v integračním prostředí - nejde iposman

### ISSUE THREAD

**Issue by fiorita** [csob/paymentgateway#500]
Dobrý den,

provedl jsem všechny potřebné úkony (platby testovacími kartami v nejrůznějších režimech, stejně jako platby kartami, uvedenými na stránce https://github.com/csob/paymentgateway/wiki/Přechod-do-produkčního-prostředí

Nemůžu se však dostat do https://iposman.iplatebnibrana.csob.cz/posmerchant abych ukončil práci v integračním prostředí. Nebere to uživatelské jméno (IČ) ani heslo z produkčního posman. Nedá se změnit heslo i stisknutím tlačítka Obnovit heslo a uvedením IČ a emailu technického zaměstnance mé firmy.

Jak prosím na to?

Chci pak ještě zdůraznit, že jsem vysloveně žádal o akceptaci karet regionů Visa a MasterCard Amerika a Jižní Amerika, bylo mi vyhověno, v detailech brány však vidím, že Amerika a JIžní Amerika/Karibik nejsou háčkované. Značná část zákazníků pochází právě z Ameriky, na jiném mém webshopu (ID brány M1MIPS5051) to běží bez problémů.

Laskavě prosím o nápravu a na instrukce jak dál s přechodem na ostrý režim.

Rovnou poprosím abyste neměnili heslo na stávající produkční posman jak jste to udělali dnes ráno.

S pozdravem a přáním krásného dne,
Kirill Gorbunov
ID brány M1MIPS8409

**Comment by kkolarikova** [comment]
Dobrý den, 

ohledně problému s přihlášením na posmerchant se prosím obraťte e-mailem na akceptacekaret@csob.cz 
Rovnou je požádejte o přidání Ameriky, Latinské Amerika a Karibiku do akceptovaných karet.

Také jsem si všimla, že Vám chybí ze zkušebních transakcí reverzovaná platba, kterou je třeba provézt k přechodu do produkčního prostředí. 

S pozdravem Kolaříková

**Comment by fiorita** [comment]
Dobrý den,
děkuji moc za rychlou odpověď. 

Co se týče reverzovaných plateb, nemám možnost to reverzovat přes svoji webové stránky, v případě potřeby to reverzuji přes posmerchant. Na Githubu jsem četl, že tuto operaci můžu tedy vynechat.

S pozdravem, Gorbunov

**Comment by fiorita** [comment]
Podařilo se to poslat na validaci, děkuji moc za podporu))
