### ISSUE TITLE
Sandbox - payment/init failed

### ISSUE THREAD

**Issue by maggi1** [csob/paymentgateway#502]
Dobrý den, založil jsem si sandbox, stáhl klíče a veřejný klíč poslal bance. Do svého eshopu jsem si nainstaloval funkční řešení, které jsem implementoval svému klientovi. 

Sandbox: Žádost má číslo: 8334 (merchant ID A4715aJpHD)

ve složce keys mám
veřejný klíč banky: mips_platebnibrana.csob.cz.pub
a svůj privátní klíč

Výsledek: payment/init failed

Když ale použiji merchantId klienta a jeho privátní klíč, normálně se na jeho bránu dostanu.

Kde je chyba?

**Comment by ratajskym** [comment]
Dobrý den, používáte anonymní id tzn jdete na integrační prostředí.

Veřejný klíč platební brány máte podle všeho produkční
veřejný klíč banky: mips_platebnibrana.csob.cz.pub

**Comment by maggi1** [comment]
Z toho jsem jelen. Vygeneroval jsem si anonymní Id a k tomu stáhl 2 klíče, privátní a veřejný. Veřejný jsem odeslal bance. Do složky keys vložil veřejný klíč banky a privátní klíč, který jsem obdržel při zakládání sandboxu. Opravdu nevím, jaké jiné klíče či řešení bych měl použít. Můžete mi to nějak srozumitelně objasnit?

**Comment by maggi1** [comment]
Zkoušel jsem také místo mips_platebnibrana.csob.cz.pub použít ten veřejný (nejspíš tedy integrační). Výsledek je stejný.

**Comment by maggi1** [comment]
Pak je tu otázka, zda se nesápu na produkční bránu, nejspíš ano: 

$url = "https://api.platebnibrana.csob.cz/api/v1.8";

integrační URL je jiná?

**Comment by mrazekl** [comment]
Dobrý den,
určitě se "sápete" na produkci, integrační rozhraní je:
https://iapi.iplatebnibrana.csob.cz/api/v1.8

Práce s klíči, kterou popisujete, by měla být v pořádku.
Jen bych podotkunul, že s anonymním merchant ID lze provádět jen základní operace.

**Comment by maggi1** [comment]
Díky, už to běží.  Možná by  stálo za to v dokumentaci uvést jednoduchou tabuličku nastaveni pro integrační, resp. produkční prostředí. Byť je to triviální, přeci jen by to pomohlo. Člověk, když to dělá občas, tak to zapomene.

**Comment by janbrasna** [comment]
Diky za feedback, pridano pro referenci k "meta" issue #222 jako soucast problemu prechodu do produkce.
