### ISSUE TITLE
Status 7 - čekání na zúčtování

### ISSUE THREAD

**Issue by vojtechMatocha** [csob/paymentgateway#503]
Dobrý den,

stává se nám, že transakce zůstávají trvale ve stavu 7 - čekání na zúčtování. Jaký je význam tohoto stavu? Lze v tomto stavu vydat zákazníkovi zboží? Jak dlouho v tomto stavu transakce zpravidla setrvávají? Dokumentace je u tohoto stavu poměrně stručná.

V PHP příkladu od Ondřeje Dokoupila se stav 7 již považuje za finální, tj. zákazníkovi se poděkuje a vydá zboží. Je to tak správně? Anebo je platba uhrazena až ve stavu 8?

Zdraví

Vojtěch Matocha

**Comment by Lumeriol** [comment]
Dobrý den,

transakce ve stavu 4 a 7 značí, že peníze jsou již přijaté bankou a do stavu 8 se dostává po jejím zaúčtování, které obvykle probíhá tuším po půnoci následující den. Můžete zkusit ověřit dotazem na status transakce.

Takže můžete zákazníkovi zboží klidně vydat, peníze jsou z jeho karty v tomto stavu již strženy.
Alespoň náš e-shop takto funguje již několik let a nikdy jsme s tím problém neměli, taktéž jsme používali až do verze 1.7 knihovnu Ondřeje Koupila.

**Comment by vojtechMatocha** [comment]
Dobrý den,

děkuji za odpověď!

Vojtěch Matocha

Dne 26.06.20 v 16:10 Lukáš Rajchl napsal(a):

**Comment by janbrasna** [comment]
@vojtechMatocha Hezký den. Pokud máte pocit, že některé transakce zůstaly trvale ve stavu 7, pošlete prosím jejich ID — podíváme se co se s nimi dělo (opravdu by měly půlnocí projít stavem 8 a být zúčtované).
