### ISSUE TITLE
Apple Pay - CompletePayment

### ISSUE THREAD

**Issue by rad3kM** [csob/paymentgateway#504]
Dotaz, po applepay/start zjišťuji stav zpracování platby skrze payment/status, to je OK, ale nejsem si jistý, při jakých situacích mám vlastně na straně ApplePay JS dokončit proces "completePayment" se stavem "STATUS_FAILURE". 
V manuálu Apple uvádí, že se jedná o výslednou hodnotu při [autorizaci platby](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentauthorizationresult), ale nikde jsem nenašel jasnou definici, co to vlastně znamená. 

Je autorizovaná platba, tudíž stav "STATUS_SUCCESS" i zamítnutá platba, například s paymentStatus = 6 a jako chybné označuji pouze resultCode <> 0?

Děkuji

**Comment by janbrasna** [comment]
To nikdo poradne nevi, obecne dokumentace Apple Developer pro Web Payments je dosti nedotazena, takze se jen da tezko domyslet, k cemu vsemu a tedy pro jake stavy platby dane hodnoty posilat.

Ale "mimo zaznam", z nasi zkusenosti s Pay:
- STATUS_FAILURE znamena, ze se nezavre modal payment dialog a chyba se prezentuje do nej — uzivatel ma tedy moznost zvolit jinou kartu atp. jeste nez se cela session ukonci. Dokumentace nicmene ukazuje chybove stavy primarne pro problemy s dodanim (nemoznost zaslat na shipping adresu, nepouzitelna billing adresa drzitele pro nejake regionalni omezujici duvody atp.), ale neumi se nejakym prikladem vyrovnavat s platebnimi chybami z autorizace aj. …
- STATUS_SUCCESS dokoncuje flow, zavira modaly, konci sessnu atp., ale jeste nijak nepredejima, ze bylo zaplaceno (jako treba umistenim polozky do historie Walletu ap. — tam se platba dostane az "pingem" z autorizacniho kanalu, tj. nejen po dokonceni platby v modalu, u obchodnika, u platebni brany, ale az opravdu "propadnutim" k zauctovani u vydavatele) — a protoze v nasem pripade mame pro reseni chyb slozity funnel a rozhodovani, tak vlastne i pri chybe hlasime do Applu _SUCCESS a koncime session, a chyby a jejich reseni vysvetlujeme az u nas (a uzivatel ma moznost znova kliknout Pay a roztocit novou session…), protoze jsme nebyli schopni se nejak rozumne "vejit" do tech chybovych typu, ktere Apple umi predat do samotneho dialogu pro napr. volbu jine karty.
- Nemyslim si ze je to tak idealni reseni, ale je to minimalne "neoficialne" overene jako funkcni — tudiz ze nehlasi do Walletu platby co nikdy nevznikly, ani jine nevhodne chovani, presto ze "lzeme" o osudu/uspesnosti autorizace…

**Comment by rad3kM** [comment]
V tuto chvíli to mám stejně, jednou jsem omylem označil jako STATUS_SUCCES zamítnutou platbu, dialog se uzavřel a do Wallet seznamu transakcí se ta platba dostala s označením jako neprovedená (přeškrtnutá, zřejmě díky následnému ověření v pozadí). 
Je to ale dost rozporuplné, protože tak bych na jednu stranu klientu ukončil AP dialog s "fajfkou" jako success a zároveň byl ve Wallet záznam s chybou.
Nechám to, tak jak to mám a jako STATUS_SUCCESS budu označovat je skutečně zaúčtované platby.
Díky

**Comment by janbrasna** [comment]
Tak uz vim proc jsme zvolili posilat SUCESS a ne realny navrat — on Apple ceka asi jen 30sec nez pripadne session/transakci vytimeoutuje a zrusi. Jenze nikde neni garantovano, ze do te doby stihne probehnout autorizace az do vysledku, pri opravdu nejhorsim scenari je mozne cekat az 60sec na finalni vysledek autorizace, a proto jsme i vzhledem k nasemu pestrejsimu systemu informovani o ruznych typech chyb s platebnim nastrojem z autorizace rozhodli proste necekat na skutecny vysledek, ale pro Apple tu trx dokoncujeme, a pripadne chyby si pak odresime "custom"…

Co se tyce "zelene fajfky", tak vim ze to asi bezny uzivatel uplne nedokaze rozlisit, ale Apple Pay je vlastne jen autentizace, overeni drzitele karty (kryptogram, nahrada neceho jako by bylo treba 3D secure u fyzicke karty), samotna autorizace uz probiha nekde hloubeji. A ta "fajfka" vlastne v realite odpovida tomu, ze se podarilo spravne vytahnout tu kartu, neco jako zadani PINu na terminalu — ale i pak muze jeste terminal ohlasit nejakou chybu nebo podobny jiny nonOK vysledek, a tomu je tato situace virtualnim ekvivalentem. Takze dokud nema platce fyzicky pushku ze opravdu zaplatil, tak to bylo jen "overeni"…

Proto je problematika realne integrace spis otazkou nejakeho vykladu nebo vyvazovani pocitu/spravnosti vs. realneho sveta prip. technickych moznosti a omezeni dvou systemu s ruznymi parametry. Technicky jsme vyzkouseli ze problem neni ani tak, ani onak.

**Comment by rad3kM** [comment]
Děkuji za doplnění informací, máte pravdu, že se jedná spíše o problém UX, než o technické řešení platby samotné.
