### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by bezdutchek** [csob/paymentgateway#505]
Implementovavali jsme platebni branu se zkusebnimi klici a vse fungovalo, nasledne jsme si v integracnim prostredi vygenerovali klice k nasemu Merchant ID. Dosadili jsme tedy nase merchant ID, nasadili nase integracni klice a od te doby nam API vraci error 400, konkretne na metodach testPostConnection() a testGetConnection() tridy OndraKoupil\Csob\Client.
Mohu poprosit o nakopnuti spravnym smerem?
Merchant ID: M1MIPS2375

**Comment by bezdutchek** [comment]
tak uz jsme doplnili i spravny nazev obchodnika a dostaneme se pres ty test metody ... nyni to bohuzel pada na payment/init. Dle dokumentace mame ale vyplnena vsechny povinna pole

**Comment by mjanek** [comment]
Dobrý den, 
Váš požadavek je zaevidován pod: TSGSMIPS-12168 a předán odpovědnému kolegovi.
S pozdravem 
Miroslav Janek

**Comment by mjanek** [comment]
Díval jsem se do logu, a vidím chybu "Invalid paymentInit request: merchant key for M1MIPS2375 not found".

Je potřeba vygenerovat integrační klíče a poté je i odeslat do banky. viz obrázek:
![obrazek](https://user-images.githubusercontent.com/22815840/86396966-38642600-bca3-11ea-8160-f4e7f282c426.png)
