### ISSUE TITLE
Invalid paymentInit request: authorized trx for merchantId A4715aJpHD and orderNo 40 already exists

### ISSUE THREAD

**Issue by maggi1** [csob/paymentgateway#506]
Dobrý den, stala se mi taková zvláštní věc. Na integrační bráně jsem provedl bezpočet úspěšných testovacích plateb. Nyní jsem ale na bráně klikl na "zrušení platby a návrat na web obchodníka". Od té chvíle dostávám při přesměrování na bránu tuto hlášku: Invalid paymentInit request: authorized trx for merchantId A4715aJpHD and orderNo 40 already exists

<b>Notice</b>:  Undefined index: paymentStatus in <b>C:\xampp\htdocs\eshop3.0\www\payment\crypto.php</b> on line <b>134</b><br />
--
  | payment/init failed, reason: Invalid paymentInit request: authorized trx for merchantId A4715aJpHD and orderNo 40 already exists

Přitom orderNo je orderid nové objednávky (platby). V databázi se mi vše zapisuje jak má.

Děje se to, i když jsem zvýšil autoincrement (orderNo) v databázi o +1

Co s tím?

**Comment by ratajskym** [comment]
Dobrý den, posíláte duplicitní ID objednávky vůz chybová hláška

**Comment by maggi1** [comment]
Posílám a neposílám, tak jednoduché to samozřejmě není. V okamžiku, když dochází k přesměrování na bránu, tak by tam číslo nové objednávky nemělo být.

**Comment by rad3kM** [comment]
Netuším jakou verzi API používáte, ale pro 1.8 se číslo objednávky do banky dostane při INIT, které při úspěchu vrací payId a teprve s ním se přesměrováváte na bránu.

**Comment by maggi1** [comment]
Používám 1.8. Odkud bere INIT to orderNo k porovnání s tím, které do aplikace posílám?

**Comment by ratajskym** [comment]
Chybová hláška je jasná. Payment init request. Tzn k přesměrování ani
nedojde, protože se nezaloží samotná platba

Dne čt 2. čvc 2020 16:12 uživatel maggi1 <notifications@github.com> napsal:

**Comment by maggi1** [comment]
Tak jasně, že to skončí u INIT. Tam se nepracuje s hodnotami s Pos Merchant? E-shop mi vygeneruje orderid (autoincrement v tabulce orders), to vkládám do $orderNo (init data). Opět se tedy ptám, s čím se v INIT to moje NOVÉ orederNo porovnává?

**Comment by maggi1** [comment]
Sorry, já už asi vim, pracuju na dvou místech (dvě databáze). V jedné databázi je těch objednávek méně, ty duplicity tam teda asi budou, i když je divné, že se to projevilo až po tom cancel...

**Comment by maggi1** [comment]
Už je to ok.
