### ISSUE TITLE
Chyba v testování platební brány

### ISSUE THREAD

**Issue by carollinum** [csob/paymentgateway#508]
Dobrý den,

testovací platební brána je na naší strašně nastavena, nicméně to vypadá, že není správně nakonfigurována na straně csob. Dostáváme následující chybovou hlášku.

Merchant ID: M1MIPS8202

Ukázka chybové hlášky v příloze, která říká, že účet M1MIPS8202 nemůže přijmout žádnou platbu.

S pozdravem
P.

![error](https://user-images.githubusercontent.com/67782380/86457414-ec0cfa80-bd23-11ea-8cf3-03427b4edd19.png)

**Comment by kkolarikova** [comment]
Dobrý den, 

předáno na odpovědného kolegu.

S pozdravem Kolaříková

**Comment by dkomarek2** [comment]
Dobrý den,

pro Merchant ID: M1MIPS8202 jsem na integračním prostředí nezaznamenal žádnou aktivitu v logu od 26.6.
Můžete mi sdělit přesný čas pokusu, případně jej provést znovu a napsat mi přesný čas kdy se to stalo?

Děkuji

Daniel Komárek
IT application specialist

**Comment by rad3kM** [comment]
Možná je to úplně mimo, ale není to důsledek překročení limitu na výši platby, protože 623,280,- je docela dost

**Comment by dkomarek2** [comment]
Dobrý den @carollinum , 

potvrzuji domněnku @rad3kM , váš denní limit je nastaven na 500 000,00. Dle vašich dnešních pokusů soudím, že jste již tento problém vyřešil.

Nicméně ty dnešní pokusy byly zamítnuty na straně 3DS serveru.

S pozdravem,

Daniel Komárek
IT application specialist
