### ISSUE TITLE
applepay/start "resultCode":900,"resultMessage":"invalid payload (verification/decryption)"

### ISSUE THREAD

**Issue by michal-novacek** [csob/paymentgateway#509]
Dobry den, 

poradite mi prosim jak ma vypadat parametr $payload pro requestFactory.createApplePayStartRequest / StartApplePayRequest?

v phpdoc je to jako /** @var array|mixed[] */ tak z toho nejsem moudry jake tam maji byt klice

do window.ApplePaySession.onpaymentauthorized mi prijde takovyhle event, co Vam mam preposlat jako payload? event.payment? event.payment.token? event.payment.token.paymentData?
```
event: {
   payment: {
      "token":{
         "paymentData":{
            "version":"EC_v1",
            "data":"Zxxxc",
            "signature":"MIxxxA==",
            "header":{
               "ephemeralPublicKey":"MxxxUw==",
               "publicKeyHash":"Dxxxs=",
               "transactionId":"axxxde"
            }
         },
         "paymentMethod":{
            "displayName":"MasterCard 2036",
            "network":"MasterCard",
            "type":"debit"
         },
         "transactionIdentifier":"AxxxE"
      }
   }
}
```
Dekuji, MN

**Comment by janbrasna** [comment]
Je to base64 z paymentData viz dokumentace: 
1. [Metody-pro-Apple-Pay#metoda-applepaystart](https://github.com/csob/paymentgateway/wiki/Metody-pro-Apple-Pay#metoda-applepaystart-)
2. [Apple-Pay#implementace-endpointu](https://github.com/csob/paymentgateway/wiki/Apple-Pay#implementace-endpointu-pro-posl%C3%A1n%C3%AD-autoriza%C4%8Dn%C3%ADho-po%C5%BEadavku)

(Zminovana requestFactory ukazuje na to, ze jde o knihovnu treti strany, mozna proto nema metodu kompletne zdokumentovanou resp. resenou serializaci ap.)

**Comment by michal-novacek** [comment]
Mate pravdu, je to Slevomat knihovna. Dekuji za linky do dokumentace. Vyzkousim a potom zavru.
