### ISSUE TITLE
Přechod z GPWebpay

### ISSUE THREAD

**Issue by rbartu** [csob/paymentgateway#51]
Dobrý den,

vygeneroval jsem nové (testovací) certifikáty na https://iplatebnibrana.csob.cz/keygen/, veřejný klíč byl odeslán do banky, odpověď byla:
Odeslání žádosti proběhlo úspěšně. Žádost má číslo: 1323 (merchant ID M1E3CB3043).

Přenastavil jsem modul GPWebPay v Magento:
- použil nové certifikáty
- nastavil novou URL brány

Při pokusu použít novou platební bránu je zákazník ihned přesměrován na https://iplatebnibrana.csob.cz/pay/merchant-error.html (Platba nemůže být provedena)

GPWebPay generuje URL pro platební bránu:
https://iplatebnibrana.csob.cz/pay/entry/merchant?MERCHANTNUMBER=3043&OPERATION=CREATE_ORDER&ORDERNUMBER=890153004&AMOUNT=29948&CURRENCY=203&DEPOSITFLAG=1URL=http://testla.cz/gpwebpay/index/return/&DIGEST=gR88ENh....

Ohledně MERCHANTNUMBER - musí se použít v celém formátu nebo bez prefixu ' M1E3CB'? Ptám se, protože v admin rozhraní modulu GPWebPay  není možné do pole "Číslo obchodníka" zadat jiné znaky než čísla.

Prosím, můžete zkontrolovat logy na straně poskytovatele nebo blíže specifikovat kroky k úspěšnému nasazení Vaší platební brány.

Děkuji.

**Comment by Miculka** [comment]
Dobrý den. 

Podíval jsem se do logu a problém je ve špatně nastaveném ID Merchant - system vas nepoznava. 

![2015-09-25 09_30_47-errors or warnings - discover - kibana 4](https://cloud.githubusercontent.com/assets/14308839/10095218/5510d0da-6368-11e5-873a-1b4bdd38e922.png)

Máte nastaveno ID : 'M1E3CB3043 littleangel.cz"
Potřebujete nastavit ID jen a pouze : M1E3CB3043

U GPWebPay se používali jen čísla, nyní je možné zadat vaše ID : M1E3CB3043 bez problémů. 

S pozdravem. 

Mičulka

**Comment by Miculka** [comment]
Díval jsem se i do produkce a tam jsem od Vás viděl volání též. Upozornuji tedy, že testovaci certifikaty zkouset jen a pouze v test. prostredi. 

tj. : https://iapi.iplatebnibrana.csob.cz/

**Comment by rbartu** [comment]
A kde mám nastavit ID? Předpokládal jsem, že ID se předává v GET parametru, tak jak je specifikováno v URL, před chvilkou jsem provedl volání s:
MERCHANTNUMBER=M1E3CB3043

2015-09-25T08:46:50+00:00 DEBUG (7): finalUrl: https://iplatebnibrana.csob.cz/pay/entry/merchant?MERCHANTNUMBER=M1E3CB3043&OPERATION=CREATE_ORDER...

A výsledek je stejný:
https://iplatebnibrana.csob.cz/pay/merchant-error.html (Platba nemůže být provedena)

Toto dlouhé ID nám bylo přiděleno pro produkční prostředí, viz email:
ČSOB Payment Gateway: merchant activation in the production environment
"Merchant ID: M1E3CB3043 littleangel.cz"

Nejsem si vědom, že bych zkoušel volal produkční platební bránu, používám jen:
https://iplatebnibrana.csob.cz/pay/entry/merchant...
Z jakého dne to bylo? 

Děkuji a přeji hezký den.

**Comment by ratajskym** [comment]
Jako merchant number nastavte Vaše id M1E3CB3043. Zkuste transakci a následně pošlete čas transakce, abychom ji dohledali v logu.

**Comment by Miculka** [comment]
Již tam vidím pohyb. 

September 25th 2015, 13:47:23.925	imips	INFO	Cancelled by customer M1E3CB3043 / 890153006

**Comment by rbartu** [comment]
Ano, děkuji za support. 
Vyčetl jsem z databázového logu pro modul GPWebPay (Magento), že sice odešle správné ID v URL brány, ale zároveň odesílá nějaké informace bokem a tam pořád zůstávalo staré zkrácené ID (bez prefixu M1E3CB). Změnil jsem zdrojový kód modulu, ID je již odesíláno správně a brána funguje.

**Comment by Miculka** [comment]
Skvěle. Teď už jen vzhůru do produkce. 

Případ tedy uzavírám.
