### ISSUE TITLE
Merchant ID pro EUR ucet

### ISSUE THREAD

**Issue by Jakub-Kopi** [csob/paymentgateway#510]
Prosim o zaslani merchant ID pro nas novy EUR ucet. Platebni brana www.kopiluwak.eu. Dekuji Fiala

**Comment by mjanek** [comment]
Dobrý den,
na jaké ičo by měla být platební brána zaregistrovaná? 
Miroslav Janek

**Comment by Jakub-Kopi** [comment]
04645812

Aficco s.r.o.
Rašínova 10, 60200 Brno, CZ
T:+420603411067
DIC CZ04645812

**Comment by mjanek** [comment]
U obchodníka zde vidím jen jedno Merchant ID M1MIPS1099, které je nyní aktivní. Což bude stávající platební brána.
Zřejmě ještě nedošlo k vytvoření Vašeho nového ID. Pokud máte nějaké konkrétní dotazy, kontaktujte banku přímo na adrese "platebnibrana@csob.cz".
