### ISSUE TITLE
Reverse platby - doba trvání vyřízení

### ISSUE THREAD

**Issue by janfabian** [csob/paymentgateway#511]
Dobrý den, 

dá se obecně říci, jak dlouho trvá proces `reverse` od úspěšného zavolání metody csob brány až do chvíle, kdy zákazník vidí na svém účtu uvolněnou blokaci? 

Jde mi o scénář prodlužování transakce, která může být maximálně 7 dní ve stavu `4`. Pokud provedu `reverse`, poté založím novou platbu, můžu se spolehnout, že tyto operace vyřidí banka seriově a klient neuvidí v daný moment 2 blokace?

Děkuji

**Comment by Mspisar** [comment]
Dobrý den,
Váš požadavek jsme zaevidovali a předali k řešení odpovědnému kolegovi. 
s pozdravem
Spisar

**Comment by dkomarek2** [comment]
Dobrý den,

pokud provedete Reverse a poté vytvoříte novou platbu, pak ta nová je zcela nezávislá od té původní. Klient pak uvidí určitou dobu obě blokace.

Reverse předáváme ke zprocesování ihned ale jak dlouho trvá další krok záleží na systému akceptace karet.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janfabian** [comment]
@dkomarek2 Děkuji za odpověď. Ještě se zeptám, dá se odhadnout ta doba `jak dlouho trvá další krok záleží na systému akceptace karet.` Jestli se bavíme o hodinách nebo dnech?

**Comment by dkomarek2** [comment]
Dobrý den, 

to opravdu nedovedu odhadnout.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@janfabian Jen pro doplneni, zalezi na mnoho faktorech _(rekl bych systemech banky drzitele karty, ale… to je globalni pavouk sluzeb po celem svete, a i treba pro ruzne karty muze vest jinudy, a v ruznych casech je mohou zpracovavat odlisne systemy, takze ani "stejna banka" nema konzistenci v tom, jak se takove transakce dari zpracovavat),_ a bohuzel diky tomu se mohou stat okrajove pripady, kdy se blokace i po vyrazeni ze zpracovani muze u banky drzitele karty stale zobrazovat i treba po dobu dalsich 2-3tydnu.

(Proto nic jako "seriove zpracovani" takovych transakci ani nemuzeme predjimat, podobny use case bude nejspis potreba resit jinou logikou. Mozna kdyz popisete svuj obchodni pripad, treba nas napadne nejake budouci rozsireni funkci brany, ktere by tomu mohlo napomahat…)

**Comment by janfabian** [comment]
@janbrasna Děkuji za upřesnění. 

Můj usecase je být schopen držet blokovanou částku (ve stavu `4`) po dobu delší než 7 dní, konkrétně cca 15 (Jedná se o zálohu, která je uvolněna po navrácení zboží)

**Comment by janbrasna** [comment]
Planujeme slouceni chovani pro operace reverse a refund tak, aby se nedelal rozdil zda byla platba uz zauctovana nebo nikoliv, ale to asi neresi problem, ze nechcete aby se z platby u klienta stal "charge", a ne jen "hold".

Zkusim zjistit jak to resi podobni merchanti, ale asi je vseobecne pouzivane jen "plne" charge+refund.

**Comment by janbrasna** [comment]
Tak bohuzel ze vsech informaci co jsem dokazal zjistit je patrne jen jedine: a to ze se podobne use casy naopak vyrazne zprisnuji, nez ze by vznikaly nove moznosti jak je resit.

Obecne uz ted plati pro predautorizace dost omezena pravidla (travel, petrol), kdy opravdu obchodnik musi byt vedeny jako ten dany typ businessu, a podle toho se lisi i pravidla (napr. jsou vyjimky pro samoobsluzne platby nebo preduatorizace, ale tam je potreba trx uzavrit v radu minut, a co se hotelu tyce, tak tam uz dnes pripadne "kauce" maji nova pravidla, kde asociace vicemene tvrdi "pokud chcete garantovat uhradu pripadnych skod atp., sami zvazte kolik potrebujete navysit ucet, a posleze provedte vraceni castky", zvlaste u debetnich karet, kde se holdy promitaji navic jinak nez u kreditnich karet atp.) — Obzvlast ve svete ecommerce kde se provadi 3D Secure autentizace, kdy na zaklade zautentizovane castky neni mozne pak provest autorizaci na vyrazne vyssi (a opacne ani autentizace na vyssi castku negarantuje, ze penize pujdou po nekolika tydnech autorizovat; napr. pri zruseni karty, zmene dostupneho limitu atp.)  — Jinymi slovy drivejsi praxe kdy se davala nejaka arbitrarni castka do predautorizace, a pak v pripadne skod proste zuctovaly "credentials on file", to uz dnes neni, o to spise v obecne ecommerci. Pokud opravdu potrebujete garantovat "ze si na ty penize sahnete", neni jina cesta nez opravdu autorizovat a uhradit celou zalohu, a pak ji refundovat.

Ted s nove prichazejicim 3D Secure 2 se to jeste zprisni, a vsechny drivejsi "divoke zapady" z dob zehlicek a prehistorickych offline plateb na terminalech a holdech co se zpracovavaly tydny bude vsechno online relativne rozhodovat banka vystavitele karty — zda za danych podminek autentizace, pozadavku na vyjimky, momentu autentizace vs. autorizace necha platbu projit, nebo bude vyzadovat opetovne overeni… a tak.

**Comment by janbrasna** [comment]
Jen pro predstavu, toto jsou utrzky z obchodnicke dokumentace (tyka se POS, pro eCom je to jeste slozitejsi aneb na nektere typy karet nelze podobne operace vubec provadet bez fyzicke pritomnosti (magstripe/chipu)… cele zneni se da procist v manualu, ale toto jen pro predstavu):

> ![Screenshot 2020-09-28 at 14 41 20](https://user-images.githubusercontent.com/1784648/94719560-a0ceac00-0353-11eb-83c6-82bf64f7ff1b.png)

> ![Screenshot 2020-09-28 at 14 43 28](https://user-images.githubusercontent.com/1784648/94719603-ad530480-0353-11eb-9c55-d46bef606405.png)

Jinymi slovy podobne koncepty "pujcovny" bez fyzicke pritomnosti, jen na dalku, nejsou uplne dobre splnitelne aby zaroven byly bezpecne pro vsechny zucastnene strany.
