### ISSUE TITLE
Apple Pay - testovací prostředí - Merchant Blocked

### ISSUE THREAD

**Issue by vojtechMatocha** [csob/paymentgateway#512]
Dobrý den,

při komunikaci s https://iapi.iplatebnibrana.csob.cz/api/v1.8 dostáváme při zahájení platby přes Apple Pay chybu "Merchant Blocked" pro merchanta A4243sEDRw.

Podle všeho se Apple Pay musí povolit v POS Merchantu, ale na testovacím prostředí do něj nemáme přihlašovací údaje (žádné jsme při vygenerování klíčů nedostali). Můžete nám prosím poradit, co děláme špatně?

Zdraví

Vojtěch Matocha

**Comment by vojtechMatocha** [comment]
Objevila by se stejná chybová hláška, pokud bychom neměli Apple Pay Payment Processing Certificate vygenerovaný na základě žádosti z POS Merchant? Pokud ano, jak lze takový certifikát v testovacím prostředí vygenerovat?

**Comment by Mspisar** [comment]
Dobrý den,
požadavek jsme zaevidovali a předali na odpovědného kolegu. O dalším postupu budete informován.
s pozdravem
Spisar

**Comment by dkomarek2** [comment]
Dobrý den,
vaše merchantID je typu Anonymní a pro něj není metoda Apple Pay povolena.

Pro použití Apple Pay budete potřebovat standardní MerchantID do Integračního prostředí.
Pokud jej nemáte, kontaktujte prosím banku aby vám ho přidělila.
Pokud ho máte, tak použijte tento. Upozorňuji, že metodu platby Apple Pay musíte mít povolené od banky.

Více informací na tomto odkazu: https://github.com/csob/paymentgateway/wiki/Postup-integrace,-zabezpe%C4%8Den%C3%AD-pomoc%C3%AD-kl%C3%AD%C4%8D%C5%AF

S pozdravem,
Daniel Komárek

**Comment by dmarek** [comment]
jen doplnění - platební brána nyní (ibrána/produkce) pro `applepay/init` u obchodníků, kteří nemají metodu povolenou (což je případ i anonymních merchantů) vrací resp code 160, Payment method disabled

příklad:
```
{
    "dttm": "20211103140448",
    "signature": "EAe6uxYNfViGjxAOBdxwkc52toUlHOM7r0Iq2L8+L6T8qlSsGL+ceW/n0MGFAYpJXVRcnP5xBmvlUCyawK4Tn9fHuh4nmknynFFqtxNEQ3bYXOiYQfQah0LTomETKrkJjScR2gBElm8E3+GJ7hhWHD4WXp/FeBi1Kp57APjFZ+EYSgDNSkwqK+JzOJhaN7naYaImVRP0fvlINCi3WJkOlQLBz0hBrd3hKeV0v4J1CzzuQvva8Cw0B6P/g72KJIMLaksZV9v1jO+6of325BOaZqf/BuRFyd9MXNvuO/K1SpSVMcG9hJVRTod+3WNWdpo7LbWGW2HWWXWaNeZQ2t1ing==",
    "payId": "798286d4ddb6@GK",
    "resultCode": 160,
    "resultMessage": "Payment method disabled",
    "paymentStatus": 6
}
```
