### ISSUE TITLE
http status 500 oneclick

### ISSUE THREAD

**Issue by radovanx** [csob/paymentgateway#513]
U platby na klik nám brána vrací status 500.
Testovací platby i produkce fungovala v pořádku.
Je prosím možné prověřit konkrétní platbu s údaji níže ?

Děkuji

----- Thu, 16 Jul 2020 08:27:10 +0000 ----- payment/init data to sign:: 'M1MIPS7921|149ad6aab2bd0FG|815092|20200716082710|88.100.166.231|34.00|EUR'
*** Thu, 16 Jul 2020 08:27:10 +0000 child init using orig payment 149ad6aab2bd0FG

**Comment by janbrasna** [comment]
Podle dat v podpisu to vypada, jako kdyby castka odchazela jako desetinna hodnota, nicmene to ma byt cele cislo viz dokumentace (€ 34 je `3400`).

Proc by ale API melo vracet HTTP 500 (="Internal server error") misto HTTP 400 bude muset zjistit nekdo z banky podle logu.

**Comment by Mspisar** [comment]
Dobrý den,
pokud byly splněny veškeré náležitosti pro uložení karty:

**Funkce Platby na klik není přístupná univerzálně, musí být ze strany ČSOB pro konkrétního obchodníka povolena. V nastavení se rozlišuje následná platba (1) do výše první (registrační) transakce, nebo (2) v libovolné výši. Výchozí nastavení omezuje následné platby částkou první transakce. Při aktivaci služby si prosím vyžádejte nastavení, které odpovídá způsobu použití platby Na klik ve vašem e-shopu.**

Posíláte špatný požadavek na oneclick:

viz:
https://github.com/csob/paymentgateway/wiki/Platba-na-klik#n%C3%A1sledn%C3%A9-platby-na-klik

s pozdravem 

Spisar

**Comment by radovanx** [comment]
Dobrý den, děkuji za odpověď v čem konkrétně ? Chyba 500 se vrací z jakého důvodu ?

**Comment by dkomarek2** [comment]
Dobrý den,
dohledal jsem transakci 149ad6aab2bd0FG od M1MIPS7921 a zjistil jsem, že byla zamítnuta z důvodu špatného parametru "dttm" - "20200715210107".

S pozdravem,

Daniel Komárek
IT application specialist
