### ISSUE TITLE
ABO formát výpisu transkací

### ISSUE THREAD

**Issue by jakl15** [csob/paymentgateway#517]
Výpis o transakcích uskutečněných platebními kartami je k dispozici i v XML a TXT, ale jejich vnitřní struktura nám neumožňuje import do účetního programu (Money S3).

Je výpis transakcí z platební brány dostupný i v ABO formátu?

**Comment by Mspisar** [comment]
Dobrý den,
tento dotaz prosím směrujte na email: akceptacekaret@csob.cz
děkuji
s pozdravem
Spisar

**Comment by jakl15** [comment]
Jejich odpověď byla rychlá, ale nepotěšila: " ABO formát neposkytujeme"

Předpokládám, že nejsem sám, kdo řeší import plateb kartou do účetního systému.

Jaké to tedy má řešení?

Existuje nějaký konverter, kterým lze XML vygenerované bránou zkonvertovat do ABO formátu?

**Comment by janbrasna** [comment]
Existuje https://github.com/jvimr/csob-txt2gpc (par let stare, napsane v Ruby), ktere do ABO prevadelo TXT vypisy z IB24 — mozna ten format bude stejny?
