### ISSUE TITLE
Responzivní formulář platební brány v iframe zobrazení

### ISSUE THREAD

**Issue by adamspyboy** [csob/paymentgateway#518]
Formulář pro zadání údajů o kartě v iframe verzi platební brány není responzivní a nepřizpůsobí se velikosti rámce, ve kterém je zobrazený, což nemusí být na menších displejích uživatelsky přívětivé/pohodlné. Plánujete toto poupravit? Nebo je třeba něco přenastavit na naší straně? Děkuji.

![csob-mobilni-iframe](https://user-images.githubusercontent.com/3263925/89098967-3e593e00-d3ec-11ea-91a2-750c27fc2ee0.jpg)

**Comment by janbrasna** [comment]
Checkout metoda je umyslne pouze pro konkretni pevne rozmery — melo by to byt vse v obdrzenych informacich a dokumentaci, stejne jako informace o pouziti (jako ze neni napr. urcena pro mobilni zarizeni viz tento pripad, tam se ma uzivatel posilat na beznou branu hlavne kvuli externim 3D Secure overenim ktere neovlivnujeme atp.)

Nicmene ano, shodou okolnosti se bude behem podzima checkout prizpusobovat novemu EMVCo 3D Secure 2.x, takze spolu s nim dostane take responsivni rozmery misto pevneho.

**Comment by adamspyboy** [comment]
Skvělé, moc děkuji za informaci.

**Comment by janbrasna** [comment]
Na checkout merchanty budou nejspise odchazet informace o zmenach v souvislosti s 3D2, takze i s tim pak budete mit casovou predstavu zmeny layoutu. (Ocekavame cca v druhe pulce rijna, uvidime co okolnosti…)

**Comment by adamspyboy** [comment]
Dobrý den, došlo prosím v této věci k nějakému posunu? Vypadá to, že se na platební bráně zatím nic nezměnilo. Předem děkuji za informaci.

**Comment by janbrasna** [comment]
@adamspyboy Hezky den, nove 3D Secure se spoustelo nad stavajicimi endpointy, tj. zadna nova verze se pro to vydavat nemusela. Zda je to v planu vyhledove dodat je asi otazka na sveho bankere. (Plati ze stavajici forma checkoutu ma tato svoje specifika mj. proto, jak konkretne ji dani merchanti vyuzivaji a prezentuji, a tam asi uplne vule neco menit nepanuje. Co se tyce nevhodnosti pouziti pro mobile tak plati integracni doporuceni, tj. i kvuli ruznym tretim stranam, overovanim u vydavatele ap. na takovych zarizenich otvirat nikoliv iframe, ale plnou "normalni cestu" pres location.)
