### ISSUE TITLE
(400) Chybný požadavek.

### ISSUE THREAD

**Issue by mujkel** [csob/paymentgateway#52]
Dobrý den,
zkouším provolat https://iapi.iplatebnibrana.csob.cz/api/v1/echo přez POST.

JSON:
{"merchantId":"A1212evRQH","dttm":"150929103159","signature":"mDJNbCCOESzJCFIRKkNKOOZfWN4fNJrmui+ksY+WLkU82AZu+qY8bIdo6I8eJNY1MvjBLJ5MvYclo5b2g+kODx9Wt3W2Gho1Duh34r0bHvz5kdzM4zQtFmI0sm7mg5E5rhZrxsVyBM6jbMZfh1si7LPE0uPlc2M5xHwg0peRMaDzFCQoUbfEgEat50jGQpd37vlJReMkPkHMetXlHd6ggLVJJYcv7unt02zdV2QRAgJHY0yGn87JKaaFhaxdDYLNrpKsISSEE+hQkpZ2Vs06l8IMOI0tctAZhkz82842+cy7pY2h593bPjeN1qxZXwucXpk8TmSKEmL4lKejH0J/lA=="}

Data pro podpis string.Format(MERCHANT_ID + "|" + dttm);

Pravděpodobně půjde o špatný podpis. Nemáte ukázku správného podpisu v C# .NET?

**Comment by dmarek** [comment]
algoritmus pro výpočet podpisu je SHA1withRSA (takto je to pojmenované v Java crypto api - viz například https://github.com/csob/paymentgateway/blob/master/eshop-integration/eAPI/v1/java/eAPI-v1-connector/src/main/java/cz/monetplus/mips/eapi/v1/service/CryptoServiceImpl.java)

v C# to bude předpokládám podobné
řetězec vstupující do podpisu by měl být jak píšete 
```
A1212evRQH|150929103159
```

**Comment by mujkel** [comment]
A jste schopen zjistit z logu jestli to mám skutečně špatně podepsané?

**Comment by dmarek** [comment]
ano, jedná se o chybný podpis

**Comment by mujkel** [comment]
Tak mi to proslo pokud jsem jako format datumu pouzil yyyyMMddHHmmss a to jak do dttm tak pro podpis
A1212evRQH|20150929103159

**Comment by dmarek** [comment]
diky, v tom pripade zaviram ...
