### ISSUE TITLE
400 - payment/init 

### ISSUE THREAD

**Issue by hynekk** [csob/paymentgateway#520]
Jiz jsem jednou branu implementoval, takze to nedelam poprve.

Uspesne provedu echo GET a POST, ale pri pozadavku **payment/init** dostavam **400**.

request:
https://iapi.iplatebnibrana.csob.cz/api/v1.5/payment/init

{"merchantId":"M1MIPS8473","orderNo":"202000218","dttm":"20200804204152","payOperation":"payment","payMethod":"card","totalAmount":34800,"currency":"CZK","closePayment":0,"returnUrl":"http:\/\/zdeneksklenar.local\/kosik?step=5","returnMethod":"GET","cart":[{"name":"Purchase - Galerie Zden\u011bk Sklen\u00e1\u0159","quantity":1,"amount":34800,"description":""}],"description":"Your order 202000218 od Galerie Zden\u011bk Sklen\u00e1\u0159","merchantData":"","customerId":"","language":"CZ","signature":"bkX186E2dQ7pQGa1jJ3phGBajUssEdvs6053ipUqGy4xBK1Xrmpc42lMQ1a2++Y08czPKaMLam44NnmlYtaFgeUAp5keZQRn5cOUpcGDzCOftK1EqWcgTfKliE7XxkyTk4pTOJbBLROBUcfrcFoiRUHgBB3HEUmun0Ly\/mer1ZZxApkdpTxgkt0Yd8phr4nmGoqMlEj89b1NEIs9NcSNeksU5A6meD3AEpTMor\/b\/oMpmphvTLqi2NGTmsHQSRSdJpc2yKnQbOhzMtDtpuApdBdebNDpeUaB3afSpP0lqXUFXm4vsHw3ookUrvcSj7v\/F2MkSHPyDSiXefeWchcqAg=="}

Dale bych poprosil jak mohu pristoupit k testovaci verzi posmerchant

https://iposman.iplatebnibrana.csob.cz/posmerchant

dle 

https://github.com/csob/paymentgateway/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy

jsem zkousel **true / false / 0 / 1** pro **closePayment**, takze se mi zda, ze chyba je : řetězec pro výpočet podpisu je chybný, ale netusim jakym zpusobem mohu overovat, zda je retezec v poradku. 

Dekuji za nasmerovani

**Comment by mrazekl** [comment]
Dobrý den,
při kontrole vašich včerejších pokusů je chyba v tom, že zasíláte nevalidní parametr dttm.
Ten musí být aktuální k UTC+2(UTC+1 v případě zimního času) s tolerancí +- 125 minut.
Řetězec pro podpis může být v pořádku.

**Comment by hynekk** [comment]
Dobry den,
dekuji za reakci, mel jsem tam datum vytvoreni objednavky, takze to jsem upravil na soucasny cas, ale furt dostavam 400.

closepayment number

{"merchantId":"M1MIPS8473","orderNo":"202000218","dttm":"20200809133702","payOperation":"payment","payMethod":"card","totalAmount":34800,"currency":"CZK","closePayment":1,"returnUrl":"http:\/\/zdeneksklenar.local\/kosik?step=5","returnMethod":"POST","cart":[{"name":"202000218","quantity":1,"amount":34800,"description":""}],"description":"Objedn\u00e1vka \u010d. 202000218 - Galerie Zden\u011bk Sklen\u00e1\u0159","merchantData":"MjAyMDAwMjE4","customerId":"","language":"CZ","signature":"jI900OEg3YmVZKIzSPO3O+zRDZ1Sw6syyk+5Yh0123hMcfOSZ81RM4pYuO\/RBs5sc8K6rf9CyxsWL9Khi0ILsBmEU57VbCnAydiY7O3\/2qoE2gV0mS3DRXJ\/sTzIOWM3nrgppscManf7n90cmVgNvynNK89sVBD+MCxqEoE7PqNQ0DeP2LQhLma6bTuCuIUwmXoyfVECwoyYtrzaSaUdG9XUo0lVjNAODQoSkbtfJzWKFgGxOw7oDYO8H\/NfsmDLJRBzERV0F2UptXUa3Pwg4+sMBxqF5xVgHZmwwa1ViVfiINhTMvcVNuJjfWCMoFlqaNUR5GeKML8L+PM2Ugfd9A=="}

closePayment bool

{"merchantId":"M1MIPS8473","orderNo":"202000218","dttm":"20200809133815","payOperation":"payment","payMethod":"card","totalAmount":34800,"currency":"CZK","closePayment":true,"returnUrl":"http:\/\/zdeneksklenar.local\/kosik?step=5","returnMethod":"POST","cart":[{"name":"202000218","quantity":1,"amount":34800,"description":""}],"description":"Objedn\u00e1vka \u010d. 202000218 - Galerie Zden\u011bk Sklen\u00e1\u0159","merchantData":"MjAyMDAwMjE4","customerId":"","language":"CZ","signature":"Sn02kU\/l6OB2nG5NJm1sHHuJGOy4gFT0nLJkNXNDiohrjuhjMtRvu5VJ5g8+YU0Wjf40qD43DHXchSr6iE1MxIaTJEoOBuIGH1\/lE2Lf5ceUfYt1JjKEcIdDf99v1gd2zCuUGQrJi5+dq83swE8\/+8aZ\/ZH9lDHmXawf51ZUNSJ3W6qbNc39tbcGqC7ctdPPy2smtkLlbd\/DmMsGbrY6AUxBttjEyApViuA19sI7KAp791faSDghaXGEONNgGrwqvRleUM\/E4LlRIduLCM8ASWphPeJcbvEXcCMeL2lklNBYDh4gNY+6nXiS2XXB8hQE64\/IgFrryUHsEE9SGX58Ww=="}

**Comment by hynekk** [comment]
@mrazekl muzu vas poprosit o reakci nebo nasmerovani jakym zpusobem muzu debuggovat requesty?

Predem dekuji za reakci

**Comment by dkomarek2** [comment]
Dobrý den,

omlouvám se za pozdní odpověď, je vaše potřeba pomoci s implementací stále aktuální a nebo jste již problémy vyřešil?

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by hynekk** [comment]
vyreseno

------------------------------
*Hynek Kvapil*
web developer

hkvapil@gmail.com

Skype: *hhynekk*

+64 274 232 611 (NZ)
+420 777 244 577 (CZ)
