### ISSUE TITLE
Reverzovaná platba - chybná expiracia karty

### ISSUE THREAD

**Issue by maros-852** [csob/paymentgateway#521]
V návode na prechod do produkčného prostredia máte napísané 

na platební bráně zadat testovací kartu 5542860001000224, expiraci 06/20 a CVC 100, po odeslání se provede úspěšná autorizace platby, nakonec se provede přesměrování zpět do e-shopu obchodníka

Expirácia karty je chybná a nejde zadať. Kontrolujete potom v POS merchant aj tento dátum? Pretože keď som tam dal iný budúci dátum (06/21) tak klientovi vypisuje v POS mechant, že nebyla nalezena transakce se stavem Autorizace potvrzena/Posláno k zaúčování ... a pritom som robil testovaciu platbu, kde som nastavil ClosePayment na false ... a zadal kartu 5542860001000224 a CVC 100, len ten dátum som musel zadat iný.

**Comment by Mspisar** [comment]
Dobrý den,
požadavek jsme předali k řešení odpovědnému kolegovi.
s pozdravem
Spisar

**Comment by dkomarek2** [comment]
Dobrý den,

expirace karty u tohoto testu je v textu opravdu již neplatná, zařídím update (Děkuji za upozornění).

Nicméně je v pořádku test provést s platnou expirací, tedy např. "06/21", musí to projít.
Pokud máte problém s dohledáním transakce, napište mi prosím merchantID obchodníka + alespoň čas pokusu, popř. další údaje pro identifikaci transakce a já se ji pokusím dohledat. Pravděpodobně bude mít jiný status, než očekáváte.

Děkuji.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by maros-852** [comment]
teraz som jednu urobil ... jej ID je a4a5a0cd46b8dFH. snad to bude stacit

**Comment by maros-852** [comment]
![image](https://user-images.githubusercontent.com/59181831/90137740-53cc5180-dd76-11ea-8f94-95e56c6ae1f9.png)
toto potrebujem dostat do zeleneho

**Comment by dkomarek2** [comment]
Dobrý den,

dle uvedeného ID transakce se jedná o obchodníka s merchantID M1MIPS8549, který v tento okamžik má splněny všechny testy pro odeslání požadavku na schválení bankou.

![image](https://user-images.githubusercontent.com/67467762/90140475-18cc1d00-dd7a-11ea-9beb-2331ab62cfad.png)

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by maros-852** [comment]
dobre teda ako funguje Přechod do produkčního prostředí? ... pytam sa preto lebo som spravil vsetko podla navodu cize :
1.) echo
2.) Úspěšně autorizovaná platba ... cize som normalne zaplatil 
3.) Uživatelem zrušená platba
4.) Expirovaná (zrušená) platba 
5.) Reverzovaná platba (tu je aj ta autorizovana platba ale dalej v tom bode je pisane ze ju mam reverzovat tak som to spravil)

ked som spravil tychto 5 krokov tak mi klient poslal tento screenshot ze mu chyba ta Transakce se stavem: Autorizace potvrzena/Posláno k zaúčtování. A teraz ked som spravil vlastne len autorizaciu platby ktora nieje uzavreta ale nereverzol som ju tak hovorite ze uz to je OK. Cize nabuduce ked budem pre dalsieho klienta robit takuto integraciu tak musime spravit aj krok "6" kde vytvorime autorizaciu neuzavretej platby ale nereverzneme ju aby bol splneny bod 3 v POS merchant? Chapem tomu spravne?

**Comment by dkomarek2** [comment]
Dobrý den,

dle návodu https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD musíte provést následující testovací scénáře:

1. echo - pomocí metody GET
2. echo - pomocí metody POST
3. Úspěšně autorizovaná platba - klasicky dokončená platba
4. Uživatelem zrušená platba
5. Expirovaná (zrušená) platba
6. Reverzovaná platba - zde musíte vytvořit a dokončit novou platbu a tu pak reverzovat.
Pokud by jste reverzoval transakci z kroku 3, tak vám právě v tom výpisu bude chybět Úspěšně autorizovaná platba (předpokládám, že to byl váš případ).

S pozdravem,

Daniel Komárek
IT application specialist
