### ISSUE TITLE
Nejasná informace, kde vzít veřejný klíč platební brány

### ISSUE THREAD

**Issue by jstorm31** [csob/paymentgateway#522]
Při implementaci mi nebylo jasné, kde vzít veřejný RSA klíč platební brány pro ověření požadavků. [V dokumentaci je napsáno](https://github.com/csob/paymentgateway/wiki/Podpis-po%C5%BEadavku-a-ov%C4%9B%C5%99en%C3%AD-podpisu-odpov%C4%9Bdi#response-verification):
> Ten lze získat z informačního portálu platební brány...

Z toho mi vůbec nebylo jasné, co se myslí informačním systémem platební brány. Přidejte tam prosím [tento odkaz](https://github.com/csob/paymentgateway/tree/master/keys) na klíče z repozitáře spolu s informací, že je třeba je stáhnout. Ušetřilo by mi to 20 minut hledání.

**Comment by mjanek** [comment]
Dobrý den,
požadavek jsem zaevidoval pod a předal na odpovědného kolegu.
Děkujeme. 
Miroslav Janek

**Comment by dkomarek2** [comment]
Dobrý den,

děkujeme za podnět k vylepšení návodu.
Text jsme upravili, doufejme k vaší spokojenosti.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by jstorm31** [comment]
Takhle to je mnohem přehlednější, díky. 👍
