### ISSUE TITLE
castecna payment/reverse ve statusu 7 - reseni?

### ISSUE THREAD

**Issue by jakovec** [csob/paymentgateway#523]
Hezky den,

resim dlouhodoby problem.

1. klient objedna, provedeme blokaci na karte - jsme ve statusu 4
2. objednavka ceka dlouho na vyrizeni, takze napr. paty den strhavam platbu do statusu 7
3. pokud stejny den fakturuji a potrebuji provest castecny refund, napr. z duvodu, ze nedokazeme dodat kompletni zbozi, lze toto nejak provest na platbe ve statusu 7? Tedy ve stejny den, kdy jsem ji strhnul?

Dekuji.

M. Jakovec.

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek jsme zaregistrovali a předali k řešení odpovědnému kolegovi.

s pozdravem

Spisar

**Comment by dkomarek2** [comment]
Dobrý den,

děkujeme za podnět k vylepšení návodu.
Text jsme upravili, doufejme k vaší spokojenosti.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by dkomarek2** [comment]
Dobrý den,
pokud má transakce status 7, pak nelze provést částečný refund.
Nicméně vámi popsaná situace by šla vyřešit tak, že zákazníkovi nebudete účtovat plnou částku (původní hodnotu amount) ale nižší hodnotu. Tzn. při přechodu do statusu 7 změníte hodnotu amount a zákazníkovi se tak odblokuje nižší hodnota. Tím by to mělo být vyřešené.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by jakovec** [comment]
Hezky den, tomu rozumim a tak to samozrejme delame. Nicmene pokud mame pri odeslani objednavky pouze blokaci (status 4), ta ma nejakou platnost, pak se automaticky uvolni. Hlidame si tedy termin a v pripade, ze se platnost blizi ke konci, castku si automaticky strhneme do statusu 7, abychom o blokaci neprisli. Pokud se ale stane, ze nasledne zbozi stejny den dorazi, ale potrebujeme strhnout mene, resp. v tu chvili uz vratit cast, protoze jsme ve stavu 7, neni to mozne - tim chci rict, ze by bylo super (a povazoval bych to za standardni), aby se nemuselo cekat, az probehne nejaky "mezistatus" na strane banky/kar. asociace a mohl jsem ten refund provest hned a banka si ho nasledne zpracovala interne, az to bude mozne, to uz je mi vlastne celkem jedno. Takhle tu vznika "hluche obdobi", kdy neni mozne provest nic, prestoze by to stav prakticky umoznoval (penize jsou blokovany).

Dalsi, s tim souvisejici vec, je to, jak banka zpracovava prechod ze statusu 4 do statusu 7 s ponizenou castkou - fakticky neprobehne jedna transakce, ale ve vypisu se objevi kompletni strhnuti cele blokace a nasledne refund, coz je take "zvlastni". Pokud blokuji ve stavu 4 1000,- CZK, nasledne prejdu do statusu 7 s uvedenou hodnotou amount 800,- CZK, neprijde mi jen 800,- CZK, jak bych cekal a na jinych branach je bezne, ale prijde mi 1000,- CZK a odejde 200,- CZK.

Dekuji.

**Comment by dkomarek2** [comment]
Dobrý den,

chápeme, že vámi popisovaná situace je z vašeho pohledu nepříjemná ale v tuto chvíli jiné řešení platební brána neumožňuje. Refund lze korektně provést až se statusem 8.

Ohledně druhého problému jsem se radil s kolegy a standardně by se tak transakce chovat neměla ale za určitých okolností to možné je, opravdu záleží na situaci.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by jakovec** [comment]
Rozumim, slo mi spise o pripominku, jestli to do budoucna nezapracovat...

Diky.

**Comment by janbrasna** [comment]
@jakovec Bohuzel platba momentem uzavreni (tj. prikazem k zauctovani) az do fyzickeho zauctovani na konci ucetniho dne je ve stavu jakehosi "zamceni/zmrazeni" a nelze na ni, ani interne, sahat.

Ten use-case je jasny a pochopitelny, ale aktualne zmena onech dotcenych procesu neni realizovatelna, ma to dobeh az do zahranici… mozna pri nejake pristi generacni obmene core systemu, ale je to monstrozni task tak ob dekadu:(

Ano, slo by to "svindlovat", a vratku prijmout v jakemkoliv momentu — a pokud nelze provest tak ji pozdrzet a provest az v nejakem pozdejsim bode, jenze soucasna tendence je opacna: autorizovat vratky online a v pripade nemoznosti okamziteho provedeni je rovnou zamitat (aby obchodnik mel realne aktualni informace, a mohl s tim v dany moment nalozit). Cil je tak eliminovat slozitost rucniho zpracovani pripadnych offline vratek pokud na nich nastane nejaky problem — takze ta idea na system opozdeneho "slibu" a pokusu s pripadnym vyporadanim asynchronne spis nebude aktualne realna, vsichni v tom systemu (asociace, vydavatelske banky) se snazi delat presny opak (napr. aktualne se prechazi na autorizace i vratek, tj. negativni amount se dava k autorizaci u vydavatele jako jakakoliv jina transakce), uvidime jak se tento system v case osvedci, a zda treba na tomto zaklade nejaky async princip nevznikne — pak by se z nej refund behem cekani na zuctovani asi dal odvodit, ale v tuto chvili to bohuzel neni realnejsi nez tato teorie:/ Uvidime do budoucna.
