### ISSUE TITLE
Návrat do e-shopu po metodě payment/process v IE 11 nerespektuje zvolenou returnMethod

### ISSUE THREAD

**Issue by Dwdization** [csob/paymentgateway#525]
**Postup:**

1. V eshopu dokončím objednávku, proběhne payment/init s returnMethod=POST, pak payment/process, jsem přesměrován na ČSOB bránu (https://iplatebnibrana.csob.cz/pay/...).
2. Na bráně zvolím **Zrušit platbu a vrátit se do obchodu**.
3. Brána chybně provede HTTP GET místo POST, URL je správné, ale požadavek neobsahuje žádný z povinných parametrů (např. payId).

**Specifika:**

- k tomuto chování dochází pouze na testovacím prostředí, které používá API URL https://iapi.iplatebnibrana.csob.cz/api/v1.8, na produkčním prostředí s API URL  https://api.platebnibrana.csob.cz/api/v1.8 problém (zatím) nevzniká
- zároveň k tomuto chování dochází pouze při použití Internet Exploreru, v ostatních prohlížečích je korektně použito HTTP POST nesoucí povinné parametry

**Domněnky:**
- problém může být způsoben na straně e-shopu nesprávnou konfigurací certifikátů na testovacím serveru, s tímto si pak IE nedokáže správně poradit; tuto domněnku nejsem momentálně schopen ověřit
- problém může být způsoben na straně ČSOB, pokud se k Internet Exploreru chová jinak, než k ostatním prohlížečům

Prosím proto o kontrolu správné funkce návratu do eshopu po zrušení platby v Internet Exploreru.

Detaily (merchantId, konkrétní dotčená payId atd.) bych radši poskytnul v osobní komunikaci.

**Comment by janbrasna** [comment]
@Dwdization Neni mozne ze vam to prepisuje nejaky SSO, proxy ci podobna sluzba po ceste, ala jako uz se zkoumalo v podobne issue #501…?

**Comment by Dwdization** [comment]
@janbrasna díky za tip. Dnes ráno došlo k nasazení té verze, ve které se chyba projevovala na testovacím prostředí, na produkční prostředí. Tam se chyba neprojevuje ani v IE, což mi přijde jako rozhodující. Tím pádem chyba nejspíš nebude u ČSOB, ale v konfiguraci našeho testovacího prostředí.

Taky to znamená, že tento problém nemusíme řešit tak urgentně.

Počkám na názor DevOps, výsledek vám dám vědět.

Díky.
