### ISSUE TITLE
Nefungují testovací karty

### ISSUE THREAD

**Issue by mobilttl** [csob/paymentgateway#526]
Dobrý den,

v testovacím prostředí se po zadání testovací karty (jakékoliv) vrací brána na tuto chybu:

<img width="897" alt="Snímek obrazovky 2020-09-11 v 14 59 07" src="https://user-images.githubusercontent.com/16777818/92929113-5509a080-f440-11ea-8d99-51b40a6ed97b.png">

děkuji,

**Comment by dkomarek2** [comment]
Dobrý den,

omlouváme se za vzniklé potíže, problém je již v tuto chvíli odstraněn.

S pozdravem,

Daniel Komárek
IT application specialist
