### ISSUE TITLE
WordPress plugin

### ISSUE THREAD

**Issue by riya0408** [csob/paymentgateway#527]
I have download the zip code for ČSOB Platební brána – For VISA and MasterCard. During the installation of this plugin in my WordPress it is showing 
Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin installation failed.

**Comment by Mspisar** [comment]
Hello,

your request was forwarded to responsible service technician. You will be contacted as soon as possible.

best regards

Milan Spisar

**Comment by riya0408** [comment]
thank you so much. I have a website http://knshops.com. I want ČSOB Platební brána – For VISA and MasterCard option in my WordPress site please help me with this

**Comment by dkomarek2** [comment]
Hello,

if you mean the "WooCommerce" plugin, so this is not officially supported by ČSOB.

Best regards

Daniel Komárek
IT application specialist

**Comment by riya0408** [comment]
It’s not about Woo-commerce plugin it’s about  ČSOB Platební brána – For VISA and MasterCard plugin
I downloaded this plugin from github and tried to install in my wordpress site but got this result Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin installation failed.
My site name is knshops.com

**Comment by dkomarek2** [comment]
Hello,

unfortunately ČSOB does not support third-party plugins. 
Contact the author of this plugin for help.

Best regards

Daniel Komárek
IT application specialist
