### ISSUE TITLE
Řešení pro WooCommerce

### ISSUE THREAD

**Issue by MichaelKazda** [csob/paymentgateway#528]
Dobrý den, 
mohl bych požádat o nějakou radu nebo postup, jak se řeší implementace Vaší platební brány do **WP WooCommerce**?
Rozumím, že žádný oficiální plugin nepodporujete, ale potřeboval bych vědět kde alespoň začít a jak implementovat PHP řešení, které máte zde na repozitáři.
Děkuji

**Comment by Mspisar** [comment]
Dobrý den,
požadavek byl zaevidován a předán odpovědnému kolegovi. O dalším postupu budete informován.
s pozdravem
Spisar

**Comment by mklusak** [comment]
Dobrý den, s dovolením jsem v této otázce také velmi zainteresován ... klient používá jakýsi obskurní zastaralý plugin WooCommerceMonetGateWay, který by si rozhodně zasloužil nahradit moderním řešením.

**Comment by dkomarek2** [comment]
Dobrý den,

bohužel vám nemohu nijak pomoci, protože jak jste již zmínil, tak tento plugin není oficiálně podporovaný.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by mklusak** [comment]
Dobrý den,

pokud to byla odpověď pro mě, pak jsem spíše chtěl vědět, jestli není nějaký nový WP / WooCommerce plugin ve vývoji z vaší strany, resp. ze strany ČSOB. Což tedy předpokládám asi není.

S pozdravem
 Marek Klusák

**Comment by dkomarek2** [comment]
Dobrý den,

aktuálně není podporovaný ani vyvíjený žádný plugin pro tuto funkcionalitu.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by MichaelKazda** [comment]
Dobrý den, 

mohl bych tedy poprosit o nějakou radu jak posupovat při implementaci brány do Wordpressu a Woocommerce?

Předem děkuji

S pozdravem,
Michael Kazda

**Comment by dkomarek2** [comment]
Dobrý den,

opakuji, že tento plugin již nadále nepodporujeme a proto vám bohužel nemůžeme nijak pomoci s jeho implementací.
Tzn. jde o aplikaci 3. strany (nejsme jejími autory) kdy neručíme za její funkčnost a ani ji neservisujeme.
Mohu vám poradit jen aby jste se obrátil na autora tohoto pluginu.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by MichaelKazda** [comment]
Otázka nebyla nijak myšlená na existující plugin, ale spíše jak bych měl postupovat bez něj.
