### ISSUE TITLE
Testovací brána - 502 Bad Gateway

### ISSUE THREAD

**Issue by kjanek73** [csob/paymentgateway#53]
Dobrý den, 

při testování se dnes potýkáme s probléme, kdy po zadání platební karty a přechodu do scény "spojujeme se s vydavatelem Vaší karty" (nebo tak nějak) končí požadavek vždy chybou 502 Bad Gateway (url v adresním řádku je https://ivisa.iplatebnibrana.csob.cz/PIT/ACS). Dost nám to komplikuje implementaci. Prosím o informaci kdy bude brána funkční. Naše merchant ID je M1E3CB0094.

Děkuji

Karel Janěk

**Comment by Miculka** [comment]
Dobrý den. 

URL, které máte zadáno je špatně. 

Správné URL jsou : 

"https://iapi.iplatebnibrana.csob.cz" 

nebo starsi verzi 

""https://iplatebnibrana.csob.cz" 

A to pouze a jenom pro testovací prostředí. !!!

Odkazy pro nastavení test brány : https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

Zkuste tedy provést následující. 

Čekám na další instrukce. 

S pozdravem Mičulka

**Comment by ratajskym** [comment]
@kjanek73 Zkuste ještě jednou, už je to v pořádku

**Comment by kjanek73** [comment]
OK ... už funguje. Díky
