### ISSUE TITLE
Nedokončené objednávky

### ISSUE THREAD

**Issue by daliborhonza** [csob/paymentgateway#531]
Dobrý den, 

Rádi bychom prosím získali informaci, případně detaily, proč nám nedopadly níže uvedené objednávky. Máme pouze informaci od zákazníků, že korektně zaplatili, ale následně, nebyl dokončen proces objednávky na našem eshopu. Je možné zjistit, zda skutečně proběhlo přesměrování zpět na eshop? Případně, mohli byste nám poskytnout k těmto objednávkám, nějaké rozšířené informace o průběhu platby? 

ID Platební brány:  M1MIPS3662

id objednávek: 
683d14fbaa317FI
53f8d47299807FI
c12b135e2e492FI
4a4fcad4cd57cFI
dafa7a22abb00FH
d3f1ee5d9a1c6FH

Děkuji za informace  D.Honza

**Comment by daliborhonza** [comment]
Již jsme zjistili, v čem je problém. V důsledku změny politiky pro práci s cookies, při návratu z platební stránky, prohlížeč ztrácel kontext. Více informací je popsáno zde:
https://web.dev/samesite-cookies-explained/
Zdánlivě náhodné chování souviselo s 2 min limitem platnosti viz https://support.google.com/chrome/thread/62111771?hl=en&msgid=65735644

**Comment by janbrasna** [comment]
Parada, zase neco co zanechava okno zpetne nekompatibility 😭 viz:
* https://www.chromium.org/updates/same-site/incompatible-clients

Pravdepodobne do stejneho problemu narazi vicero obchodniku…

TL;DR: Pri POST navratu na svuj web z ciziho kontextu se neposilaji (nejen session) cookies, pokud nebyla v poslednich letech aktualizovana jejich IETF pravidla podle novych specifikaci.

Vice info:
* https://blog.heroku.com/chrome-changes-samesite-cookie
* https://www.coderfrontline.com/chromes-samesite-cookie-changes-are-breaking-apps/
* https://catchjs.com/Blog/SameSiteCookies
* timeline: https://sites.google.com/a/chromium.org/dev/updates/same-site

Default policy "Lax + POST" omezeni na 2min bylo zavedeno hlavne kvuli SSO a jinym auth kanalum, na platebni flow nikdo uplne nemyslel: https://groups.google.com/a/chromium.org/g/blink-dev/c/AknSSyQTGYs/m/YKBxPCScCwAJ — takze na vyse zminenem support vlakne je od postu https://support.google.com/chrome/thread/62111771?msgid=65735644 nize videt pomerne velke problemy hlavne u ecomm/platebnich usecasu, jako jsou 3D Secure overeni a podobne.

Kazdopadne i tak:
1. potreba zmenit session cookie na "nezabezpecenou", jakoby thirdparty policy, aby se po navratu odjinud probudila zase shopping session je dost nestastne :(
2. lepsi by asi bylo aby pro jen opravdu "prijem" OK/nOK postu s odpovedi z brany byl na zpracovani pozadavku, overeni payloadu atp. separe handler, a pak na stranku s trychtyrem/kosikem/sezenim si to teprve presmeroval uz ze sveho kontextu…
3. prip. nespolehat na session cookie a umet kosik rekonstruovat z jineho hashe, ktery je mozne si na branu posilat v `merchantData` — vrati se zpatky s odpovedi.
