### ISSUE TITLE
Chyba volani 400 Bad Request na vsech metodach

### ISSUE THREAD

**Issue by rovis-eu** [csob/paymentgateway#533]
Dobry den,

prosim o radu, prechazim z API 1.7  na 1.8 a pridavam nove metody, vsechny mi ale konci stejnou chybou,
data k zaslani: A4888fNFOD|202010-004|20201004204338|1.1.1.4|104|CZK|https://www.rovis.eu|POST|era|test|CZ
nasledne probehne podepsani a aktivace (init) pres button/init, pri volani cilove URL koncim touto chybou, nevidim pricinu, jak lze prosim zjistit v cem je presne chyba?

calling targetUrl=https://iapi.iplatebnibrana.csob.cz/api/v1.8/button/init, sendData={"merchantId":"A4888fNFOD","orderNo":"202010-004","clientIp":"1.1.1.4","totalAmount":104,"currency":"CZK","returnUrl":"https://www.rovis.eu","returnMethod":"POST","brandButton":"era","merchantData":"test","language":"CZ","dttm":"20201004211153","signature":"c3/ugKtwJtME1HGIYnTE2wARL+Mt2pkULOHGKTzZi1IrSAJNJ104C92G7Z9pUsHZY5rR+7bsIQDhb3UYhUtINWFeFWEgL7hf8eDSTiPnhU61WK+dBvnxhubKQ8GXgvkcsFCcWwPR0LzOWLaAIkKHQK3UoDZhp6sPA0gyllSNKPLJjDQ1CfVfpC+iSolu4udlsjjZjll0xAlrMbb3GRNP1bCriB0ZkOVGfIgDJvj55+SxsaiAKkovcqjiCvUZnqsnZEbGgoMwGkcTc7KiZutZF8EJpkZKLnMxBzWiD9eBYEe9WjOPiJM7NrBznxDvrMaxAPCNuIrQWWZZ+X3fKa4gbw\u003d\u003d"}

dekuji

R.Visek

**Comment by dkomarek2** [comment]
Dobrý den,

na náš server váš poslední request přišel v tomto tvaru (text jsem jen pro přehlednost odřádkoval + zkrátil podpis):
{"returnUrl": "https://www.rovis.eu",
    "returnMethod": "POST",
    "language": "CZ",
    "orderNo": "202010-004",
    "clientIp": "1.1.1.4",
    "totalAmount": 104,
    "currency": "CZK",
    "merchantData": "test",
    "merchantId": "A4888fNFOD",
    "dttm": "20201004211153",
    "signature": "c3/ugKtwJtME1HGIYnTE2wARL+M........"}

Když jsem jej porovnal s definicí [ZDE](https://github.com/csob/paymentgateway/wiki/Metody-pro-platebn%C3%AD-tla%C4%8D%C3%ADtko#metoda-buttoninit-) tak výsledek:
- chybí vám definice parametru "brand"
- u parametru "merchantData" uvádíte hodnotu "test" což není kódováno v BASE64. Tento parametr není povinný, takže pokud jej nechcete plnit relevantními daty ve správném tvaru, pak jej v definicu vůbec neuvádějte.

Pozn.: U parametru "totalAmount" se uvádí hodnota v setinách měny, tzn. váš příklad "104" znamená "1,04 CZK".

Data se samozřejmě musí shodovat s těmi ve stringu (vámi uváděný příklad asi patří k jinému pokusu ale obsahově vypadá v pořádku).
Dále nezapomeňte, že pro eAPI 1.8 je potřeba použít algoritmus založený na SHA-256.

Prosím opravte si implementaci a pokus vyzkoušejte znovu.
Pokud by byl stále problém, tak mi prosím opět zanechejte odeslaná data i se stringem.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by rovis-eu** [comment]
Zdravim Danieli, dekuji za napovedu, uz mi to proslo (mel jsem misto brand nastaveno brandButton), jen jeste dotaz: chyba 160 je zde na testu asi OK?

R.

**Comment by dkomarek2** [comment]
Dobrý den,

Chyba 160 znamená "Payment method disabled (operace není povolena, obchodník si o nastavení musí smluvně zažádat)" takže se pokoušíte volat metodu, kterou nemáte povolenou od banky. Je potřeba ji kontaktovat a domluvit si aktivaci této platební metody.

Vaše pokusy o request typu oneclick jsou zamítány, protože používáte neznámou hodnotu parametru "merchantId":"A2232sZDuQ". Při vašich předchozích pokusech button/init jste používal "merchantId": "A4888fNFOD" takže předpokládám, že to je to správné.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by rovis-eu** [comment]
Zdravim Danieli, dekuji, to me nenapadlo, ze puvodni test ucty maji nejakou zivotnost a ze po nejake dobe zmizi ;-)

Po vymene u vsech plateb za nove test ID mi klasicka platba (payment/init) jiz prosla, OneClick take (jen hlasi, ze nemam puvodni payId platne, to je OK), ted uz je OK i applepay/init

Rozumim tedy tomu spravne, ze na test prostredi bez povoleni button a applepay "bankou" nelze provest spravne dotestovani, protoze se mi bude vracet result 160 a MarekD by mi to mohl na dane merchantId povolit?

dekuji moc za trpelivost

R.

**Comment by dkomarek2** [comment]
Dobrý den,

předpokládám, že používáte ID vygenerované na webu "https://iplatebnibrana.csob.cz/keygen/" ovšem dle tvaru ID "A*" usuzuji, že se jedná o tzv. Anonymní ID pro prvotní testy. Ty mají ovšem platnost pouze 1 měsíc a navíc jsou omezeny funkčně. Info: https://github.com/csob/paymentgateway/wiki/Postup-integrace,-zabezpe%C4%8Den%C3%AD-pomoc%C3%AD-kl%C3%AD%C4%8D%C5%AF.
Proto vám navrhuji kontaktovat banku a domluvit si s ní přidělení fixního ID, které vám již zůstane. Při té příležitosti si s nimi domluvte funkce, které chcete využívat aby vám je aktivovali.
Poté si vygenerujete nové klíče pro toto ID a doděláte integraci funkcionalit, které potřebujete.
Podrobný postup je uveden na odkaze výše.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by rovis-eu** [comment]
super, dekuji za support!
R
