### ISSUE TITLE
detailní kód zamítnutí 702

### ISSUE THREAD

**Issue by jakub-isols** [csob/paymentgateway#534]
Dobrý den,

mohl bych Vás poprosit o informace proč došlo k zamítnutí transakcí níže? Zákaznice je velmi neoblomná v tom že chyba je na naší straně, že s ověřovala s bankou a ta jí řekla že je to chyba u nás, a že potom naštvaně šla ke konkurenci kde zaplatila bez problémů. 

Některé transakce končí ve stavu "zrušeno uživatelem", ostatní ve stavu "zamítnuto" - ty přikládám. Zároveň bych Vás chtěl poprosit o informaci, co znamená detailní kód zamítnutí 702 a co znamená, když je transakce zamítnuta bez detailního kódu.

Předem moc děkuji,
Hrdlička

MerchantID: M1MIPS7062

objednávky
2f6116785419dFJ zamítnuto (702)
7e291340d89acFJ zamítnuto (702)
096bc00cb9effFJ zamítnuto (702)
002b39bf06292FJ zamítnuto (bez kódu)
604fba487e42eFJ zamítnuto (bez kódu)
4ed1b9ee2c6feFJ zamítnuto (702)
1e346bc9f6a9bFJ zamítnuto (702)
c6dbe88e29cf5FJ zamítnuto (702)

**Comment by Mspisar** [comment]
Dobrý den,

platby byly zamítnuty ze strany 3DS autorizace. Tedy na straně vydavatelské banky v tomto případě České spořitelny.

z logu:

mdesc |   | FROM_3DS_DECLINED_STATUS_N

s pozdravem

Spisar
