### ISSUE TITLE
Testovací rozhraní a ukázky implementace

### ISSUE THREAD

**Issue by Miroslav-Stopka** [csob/paymentgateway#535]
Dobrý den,

mám dotaz ohledem testovacího rozhraní. Snažíme se otestovat ukázkové implementace z [https://github.com/csob/paymentgateway/tree/master/Integration%20Examples/eAPI%20v1.8/php](https://github.com/csob/paymentgateway/tree/master/Integration%20Examples/eAPI%20v1.8/php)

Máme vygenerované testovací klíče - private i public. Public klíč byl nahrán na CSOB, ID requestu je 8734. Nevíme ale jakou url máme při testování volat. Url "[https://iapi.iplatebnibrana.csob.cz/](https://iapi.iplatebnibrana.csob.cz/)"je nefunkční. Taktéž URL https://iapi.iplatebnibrana.csob.cz/api/v1.8 vrací při testovací platbě asi nevalidní výsledek - zobrazí se nám payment/init failed, unable to verify signature. Vrácený result array, který se pak ukázková implementace snaží verifikovat je ```
{
  ["dttm"]=>
  string(14) "20201013172814"
  ["signature"]=>
  string(344) "aJ2WVHDW03eaaQkQJTOdG8scxZmVS1hakWCenJNo1/qgkSJe3pclliavq5GOVre+VUkTRoayRIYlV9H+Alb4NtrhoZawf3upQbwquiYj3AzlYzHxEzbXXTPReONJhEImgopTR8uqYst4CW2IpvHjNp6L9M4Agurv0czTTHapcjAJgbuWyzJPgrg9rBpjW1yRCf43RrjftpWTxs+FsnqJWpxvdAt1LCqHXQDpqZlXXr5wk0VremO4hXJ1GXFGQmaMhG0xmIM8F3KqGLffg/DJU7cnXCDzA0DFlOfPxujzHhr6gOHW9T9nC5r/14Vn6sNz/bEGe42EZZedFdtCo3fq+A=="
  ["payId"]=>
  string(15) "e77450a3027f2FJ"
  ["resultCode"]=>
  int(0)
  ["resultMessage"]=>
  string(2) "OK"
  ["paymentStatus"]=>
  int(1)
}
```

Poprosím tedy o informaci, jak máme testovací implementaci úspěšně otestovat. Děkuji

**Comment by mjanek** [comment]
Dobrý den, 
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
Miroslav Janek

**Comment by dkomarek2** [comment]
Dobrý den,

dohledal jsem si váš pokus a předpokládám, že používáte pro testy tzv. Anonymní ID "A4904sL2OF".
Jen vás chci upozornit, že je určené jen pro prvotní testy a má životnost jen 1 měsíc. Pokud chcete opravdu implementovat platební bránu do nějakého eshopu, pak doporučuji kontaktovat banku a domluvit si vytvoření permanentního ID.

Nicméně zkontroloval jsem váš poslední pokus, který jsme obdrželi "2020-10-13 17:35:11,500" a je tam obsahově jeden problém. V parametru "merchantData" uvádíte hodnotu null což není povolené (v žádném parametru). Pokud jej nechcete plnit, pak jej vůbec v requestu nedefinujte (platí pro všechny nepovinné parametry - ty jsou označeny netučným fontem).
Předpokládám, že si chcete vyzkoušet celý proces platby + další operace, takže až vyladíte payment/init, pak pokračujte dalšími. Ty jsou definované zde https://github.com/csob/paymentgateway/wiki/P%C5%99ehled-eAPI-metod.

Obecně doporučuji aby jste si prostudoval informace na naší Wiki, zejména:
https://github.com/csob/paymentgateway/wiki/Pr%C5%AFb%C4%9Bh-platby
https://github.com/csob/paymentgateway/wiki/Postup-integrace,-zabezpe%C4%8Den%C3%AD-pomoc%C3%AD-kl%C3%AD%C4%8D%C5%AF
https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody
https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD

Pokud budete mít další dotazy, pak nám opět napište.

S pozdravem,

Daniel Komárek
IT application specialist
