### ISSUE TITLE
Mall Pay paymentStatus:6 resultCode:190

### ISSUE THREAD

**Issue by radovanx** [csob/paymentgateway#536]
U obchodníka M1MIPS0864 platební brána ČSOB platba kartou v pořádku funguje.
U platby Mall Pay se při volání payment/init vrací paymentStatus:6 resultCode:190.
Payment method error (chyba ve zpracování u poskytovatele metody)

Prosím o prověření na bráně.
Děkuji

*** Fri, 16 Oct 2020 10:41:32 +0200 Csob gatewayOrderRedirectAction submethod: MallPay
----- Fri, 16 Oct 2020 10:41:32 +0200 ----- payment/init data to sign:: 'M1MIPS0864|20100512|Platiti|Tester|x@x.cz|777666888|62550|CZK|8159|CZK|15|CZ|Atlantida|Uzka 321|12000|BILLING|20100512-1|Bio rajsky protlak s|57132|CZK|0|CZK|15|20100512-2|Bio rajcatova omacka|5418|CZK|0|CZK|15|false|20201016104132|78.156.32.250|https://bionebio.cz/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&lang=cs&unimodul=Csob|POST'
*** Fri, 16 Oct 2020 10:41:32 +0200 Csob API call: https://api.platebnibrana.csob.cz/api/v1.8/payment/init/ POST: {"merchantId":"M1MIPS0864","orderNo":"20100512","customer":{"firstName":"Platiti","lastName":"Tester","email":"x@x.cz","phone":"777666888"},"order":{"totalPrice":{"amount":62550,"currency":"CZK"},"totalVat":[{"amount":8159,"currency":"CZK","vatRate":15}],"addresses":[{"country":"CZ","city":"Atlantida","streetAddress":"Uzka 321","zip":"12000","addressType":"BILLING"}],"items":[{"code":"20100512-1","name":"Bio rajsky protlak s","totalPrice":{"amount":57132,"currency":"CZK"},"totalVat":{"amount":0,"currency":"CZK","vatRate":15}},{"code":"20100512-2","name":"Bio rajcatova omacka","totalPrice":{"amount":5418,"currency":"CZK"},"totalVat":{"amount":0,"currency":"CZK","vatRate":15}}]},"agreeTC":false,"dttm":"20201016104132","clientIp":"78.156.32.250","returnUrl":"https:\/\/bionebio.cz\/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&lang=cs&unimodul=Csob","returnMethod":"POST","signature":"Jl4OUZfxbw7eY2q4AdUN0XWsJnjlLKAnBWxLsGllegGE1Xl9K8vkhNLaLlIKqzWHnuraW3mgyaPb3rGjTLAZlPKw+ev1IN1WlnjfZXDYdWw5e9DklmJxr2ugNj9X33Jrn8A4czW5hVSc88Sj9qjGFZWAqd\/GvkigM7hlbwENoLw8UdXdK9MV9\/W3VG\/6v66j08Yd6U\/1hkGQ0weDwHbOPK9NCynD+c3GaBa3lLRv1uL2e+Ua4OZynH7iRdkFvmMKqsU2n4zgJouSYm12tapa82HMYU7cmsXcMW3IJKEDfdjy38NjlRi\/qZwzKryuaBkez3U5P4RwT4E4k9RrpewcXw=="}
*** Fri, 16 Oct 2020 10:41:32 +0200 payment/init result:
{"dttm":"20201016104132","signature":"h9SRcItVHwyNeij0kZy2Il7TwoSavUWvEu6q7qLdSryWbZQsO9EhG8wBl8tFBsaUKjtboPfdr21mF95J6PxEdrvU+trRyFtbzT5XSbtrnjHbFfRjtUymtNlfL+/XpMg7F2w9Htj7GcUM397Tr4vD0T36a+T2IkYjpQz0H/3s+nI6nK5sNjwpgaC/THdivhHiW8Fd8tmdboOLHjouoxSUHj2Mp7wY3Z8I2Y2pAve4a5jKtL3C7Ey5ImZjWyILmVaIAaA9vSoEgXUBgn+nYOQWSfeZoeGSCKmuowmS/CbRlCA1Hw6o8N627cdZYnB1xuDwEadtIPacAraRYgcNcJpOVg==","payId":"f8345191274b4FJ","resultCode":190,"resultMessage":"unable to initialize mallpay trx","paymentStatus":6}

**Comment by radovanx** [comment]
Prosím o odpověď. Děkuji

**Comment by dkomarek2** [comment]
Dobrý den,

Zkontroloval jsem zmíněnou transakci a ta byla zamítnuta na straně MallPay z důvodů nevalidního ověření údajů, které jste tam posílali.

Podle obsahu dat z vašeho requestu (např. "email": "x@x.cz") usuzuji, že se nejednalo o ostrá data regulérní transakce z ostrého provozu reálného zákazníka ale o váš pokus o otestování této funkcionality. Mám v tomto pravdu?
Na vašem produkčním prostředí nevidím v průběhu tohoto roku ani jednu úspěšnou transakci tohoto typu a na vašem integračním prostředí je situace stejná, tam není ani pokus.
Pokud tedy mám pravdu a funkcionalitu teprve testujete, tak ji prosím testujte oproti testovací bráně "https://iapi.iplatebnibrana.csob.cz/" a nikoli na produkčním prostředí. Na integračním prostředí to můžete odladit a teprve pak přejít na ostrý provoz. Nemůžete na produkčním prostředí posílat testovací data, ta budou vždy zamítnuta jako nevalidní.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by radovanx** [comment]
Brána je v produkci již delší dobu a funkční pro platby kartou.
Potřebujeme pouze přidat MallPay platbu. Jak tedy postupovat ? Při použití reálných údajů dostáváme stejnou odpověď.
paymentStatus:6 resultCode:190.

**Comment by dkomarek2** [comment]
Dobrý den,

ano brána vám sice funguje delší dobu ale je pravidlem novou funkcionalitu i tak odlaďovat na integračním prostředí a nikoli na produkčním.
Proto vám opět navrhuji přesměrovat vaše testy na integrační prostředí kam patří.
Tam odladíme obsah, který odesíláte a další případné problémy.
Abych mohl zkontrolovat na naší straně výsledek vašeho pokusu, zašlete mi vždy datum a čas pokusu a odesílaná data.

Můžeme také přejít na čistě emailovou komunikaci kvůli případnému zasílání citlivějších informací.

Děkuji.

S pozdravem,

Daniel Komárek
IT application specialist
E: dkomarek@monetplus.cz

**Comment by radovanx** [comment]
Dobrý den,
Důvodem odmítnutí platby byl  neexistující e-shop s daným merchantID v MallPay.
Tiket můžeme uzavřít.
