### ISSUE TITLE
Operace close na nižší částku se zaúčtuje v plné výši

### ISSUE THREAD

**Issue by varecham** [csob/paymentgateway#538]
Zdravím, pokouším se uzavřít transakci na nižší částku, ale nedaří se mi to při volání přes API, funguje mi to pouze při manuálním zadání v POS Merchant.

_paymentStatus: 4_, následně volám close:
```
{
  merchantId: 'M1MIPS8795',
  payId: '86e37fd0bc669FK',
  totalAmount: 2000,
  dttm: '20201103001626',
  signature: '...'
}
```
vrátí se:
```
{
  dttm: '20201103001627',
  signature: '...',
  payId: '86e37fd0bc669FK',
  resultCode: 0,
  resultMessage: 'OK',
  paymentStatus: 7,
  authCode: '...'
}
```

Avšak když se podívám na detail transakce v POS Merchant, vidím zaúčtování na plnou částku.

Napadá vás, proč by mohl být parametr totalAmount ignorován?
Díky moc.

**Comment by varecham** [comment]
Chyba je v POS Merchant, kdy je správná částka zobrazena až po najetí v tooltipu, kromě toho je vše v pořádku.

Děkuji.

**Comment by dkomarek2** [comment]
Dobrý den,

z informací, které zde popisujete + mé kontroly této transakce v POS Merchant + logu aplikace usuzuji, že proběhlo vše v pořádku.
Transakce se založila s hodnotou 300 CZK a v requestu Close jste poslal hodnotu 20 CZK a s touto poníženou hodnotou se transakce úspěšně dokončila.
V aplikaci POS Merchant se vždy zobrazuje ve výpisu transakcí hodnota s níž byla transakce založena a nikoli uzavřena. Pokud ji uzavíráte na nižší částku, pak je původní hodnota ponížena. Po najetí myši na původní hodnotu uvidíte v našeptávači o kolik byla reverzována aby byl výsledek správný. Toto není chyba aplikace POS Merchant ale její vlastnost.

Pokud by jste měl nějaké další dotazy, pak nás klidně opět kontaktujte.

Děkuji.

S pozdravem,

Daniel Komárek
IT application specialist
