### ISSUE TITLE
Provozní prostředí payment/init občasná 400

### ISSUE THREAD

**Issue by MichalOtt** [csob/paymentgateway#539]
Dobrý den.
Platební brána v ostrém provozu začala občas vracet 400 bez zjevného důvodu.
Přitom většina plateb projde v pořádku.

Api:
/api/v1.5

Ukázka dat které vrátily 400 (nahrazeny hodnoty returnUrl a description)
`----- Wed, 18 Nov 2020 15:29:12 +0100 ----- payment/init data to sign:: 'M1MIPS0107|0001029218|20201118152912|payment|card|153835|CZK|false|returnUrl|POST|Produkty|1|153822|Zakoupené produkty v e-shopu|Poštovné|1|0|GLS - kurýrní služba (dodání 1-2 dny)|description| Platba kartou online|MDAwMDAxMTQxNw==|28493|CZ'`

**Comment by dkomarek2** [comment]
Dobrý den,

zkontroloval jsem vámi uvedenou transakci a porovnal hodnoty, které jste uvedl s tím které přišly na bránu:

- v parametru "totalAmount" uvádíte hodnotu "153835" což znamená "1538,35 CZK" (uvádím pro kontrolu, jestli je to ta hodnota, kterou jste zamýšlel uvést, pokud ano pak je to OK)
- v sekci "cart" v parametru "amount" uvádíte u první položky hodnotu "153821.99999999997" což není dovolený tvar hodnoty pro tento parametr a navíc se tato hodnota neshoduje s tím co uvádíte ve stringu pro podpis, kde máte "153822". 
Z tohoto důvodu neprošla kontrola shody hodnot mezi JSONem a stringem.

Ohledně tvaru hodnoty parametru "amount" definice říká: "Celková cena za uvedené množství položek v setinách měny."
Tzn. například to má vypadat takto: **153822** pro hodnotu 1538,22 CZK neboli 1538 korun a 22 haléřů.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by MichalOtt** [comment]
Dobrý den.

Děkuji, vyřešilo se to opravou problému s počtem desetinných míst.
(nesedící hodnoty jsem způsobil ručním nastavením při testu)

S pozdravem,
Michal Ott
