### ISSUE TITLE
Integrace v Go

### ISSUE THREAD

**Issue by hypertornado** [csob/paymentgateway#54]
Potrebuji integrovat vasi platebni branu v jazyce Go, proto si vytvarim takovou malou knihovnu. Bohuzel request `/api/v1/payment/init` vraci `HTTP/1.1 400 Bad Request`. Netusim kde by mohla byt chyba, jestli je to spatny podpis, nebo nejaka jina chyba? Prikladam vypis na konzoli i zdrojove kody. Vygenerovane MerchantID je `A1224Avw3Z`. Dekuji za pomoc.

**Výstup na konzoli**
```
REQUEST:
POST /api/v1/payment/init HTTP/1.1
Host: api.platebnibrana.csob.cz
Content-Type: application/json

{
  "cart": [
   {
    "amount": 100,
    "description": "d1",
    "name": "item1",
    "quantity": 1
   }
  ],
  "closePayment": true,
  "currency": "CZK",
  "description": "d2",
  "dttm": "20150929181010",
  "language": "CZ",
  "merchantData": "md",
  "merchantId": "A1224Avw3Z",
  "orderNo": "20",
  "payMethod": "card",
  "payOperation": "payment",
  "returnMethod": "POST",
  "returnUrl": "http://www.example.com",
  "signature": "137Oi9/mw7r04aclB4yD+6ALi6yvPP88rXncMrXJ/l36Xkm6YtqAujFlKAxm61E9DEMPaWu1mBwrpAeg6bcWCrj2I+a0UZ6fcHW+jGdkrYx1GyvtlZdDUkRZ7QkewFRTTMPM2C8bqmTM3xEAIcU5PuxAgTPGj9sboeA7aRrX0YMFoqWSqU8qUbzoRjhie7rpuyWNgYKdIJXlxdvPQnb38vniGyF6N25GhHD0o7nkIa07ljd/kkAkMnaZFXBjdKjLYgnSJRgy0+pE1ffEWzlnWgyR1vrv0zstylIQ9BbA0i50cTKglS6UoX2hPXhc1B23YrYTN9+zeXW1CKTL/Fc64g==",
  "totalAmount": 100
 }

RESPONSE:
HTTP/1.1 400 Bad Request
Content-Length: 0
Cache-Control: no-cache, no-store, must-revalidate
Connection: keep-alive
Date: Fri, 02 Oct 2015 11:26:52 GMT
Expires: 0
Pragma: no-cache
Server: nginx
Set-Cookie: BIGipServerasors_platebnibrana.csob.cz_6443_pool=VzxTJtrjOhkpaZRYY6PqN4EWSl/lMu7m2X7YwQLY8o+9zE3RuvSxDknLIINbrKDRr/+zTcFbnfBxyYwAAAAB;secure; path=/


```

**csob.go**
```go
package csob

import (
	"bytes"
	"crypto"
	"crypto/md5"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/http/httputil"
)

type CSOB struct {
	merchantId string
	key        *rsa.PrivateKey
}

func NewCSOB(merchantId, privateKeyPath string) *CSOB {
	key := loadKey(privateKeyPath)
	return &CSOB{
		merchantId,
		key,
	}
}

func (c *CSOB) Init(price uint, title, desc string) {
	params := map[string]interface{}{
		"merchantId":   c.merchantId,
		"orderNo":      "20",
		"dttm":         "20150929181010",
		"payOperation": "payment",
		"payMethod":    "card",
		"totalAmount":  100,
		"currency":     "CZK",
		"closePayment": true,
		"returnUrl":    "http://www.example.com",
		"returnMethod": "POST",
		"cart": []interface{}{
			map[string]interface{}{
				"name":        "item1",
				"quantity":    1,
				"amount":      100,
				"description": "d1",
			},
		},
		"description":  "d2",
		"merchantData": "md",
		"language":     "CZ",
		"signature":    "",
	}

	signString := c.merchantId + "|20|20150929161010|payment|card|100|CZK|true|http://www.example.com|POST|item1|1|100|d1|md|CZ"

	signed, err := signData(c.key, signString)
	if err != nil {
		panic(err)
	}

	params["signature"] = signed

	marshaled, err := json.MarshalIndent(params, " ", " ")
	if err != nil {
		panic(err)
	}

	client := &http.Client{}

	req, err := http.NewRequest("POST", "https://api.platebnibrana.csob.cz/api/v1/payment/init", ioutil.NopCloser(bytes.NewReader(marshaled)))
	if err != nil {
		panic(err)
	}

	req.Header.Add("Content-Type", "application/json")

	fmt.Println("REQUEST:")
	oo, err := httputil.DumpRequest(req, true)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(oo))

	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}

	fmt.Println("\nRESPONSE:")
	out, err := httputil.DumpResponse(resp, true)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(out))

}

func loadKey(path string) *rsa.PrivateKey {
	bytes, err := ioutil.ReadFile(path)
	if err != nil {
		panic(err)
	}

	block, _ := pem.Decode(bytes)

	key, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		panic(err)
	}

	err = key.Validate()
	if err != nil {
		panic(err)
	}

	return key

}

func signData(key *rsa.PrivateKey, data string) ([]byte, error) {
	hash := md5.New()
	io.WriteString(hash, data)
	sum := hash.Sum(nil)

	signed, err := key.Sign(rand.Reader, sum, crypto.MD5)
	if err != nil {
		return []byte{}, err
	}
	return signed, nil
}
```

**csob_test.go**
```go
package csob

import (
	"github.com/hypertornado/prago"
	"io/ioutil"
	"testing"
)

func TestServer(t *testing.T) {
	test := prago.NewTest(t)
	test.EqualInt(21, 21)

	data, err := ioutil.ReadFile("test_keys/merchantId.txt")
	test.EqualNil(err)

	csob := NewCSOB(string(data), "test_keys/rsa.key")
	csob.Init(100, "title", "desc")

}

```

**Comment by Miculka** [comment]
Dobrý den. V logu jsem vás nenašel. V POS Merchant vaše ID vidím a když se dostanete na klíče a dáte "provést validaci" vypíše Vám to seznam věcí, které ještě zbývá provést. 

![image](https://cloud.githubusercontent.com/assets/14308839/10245932/c722a122-690c-11e5-95ee-2cf4062bc795.png)

**Comment by dmarek** [comment]
Dobrý den,

používáte merchant ID vygenerované na integračním prostředí, které nelze použít na produkci. Změňte proto prosím url z api.platebnibrana.csob.cz (produkce) na iapi.iplatebnibrana.csob.cz (ibrana)

-dm

**Comment by hypertornado** [comment]
Dekuji za rychlou odpoved, zmenil jsem. Pri posilani na `https://iapi.iplatebnibrana.csob.cz/api/v1/payment/init` ted ale dostavam chybu 500 Server Error s prazdnym body.

**Comment by Miculka** [comment]
Máte špatně nastavené klíče - certifikáty

![image](https://cloud.githubusercontent.com/assets/14308839/10246155/f52fb008-690e-11e5-8b47-26cf898ed47d.png)

**Comment by Miculka** [comment]
Dobrý den,. Rád bych vyzjistil jak se vám daří v nastavení?

**Comment by hypertornado** [comment]
Dobry den, vygeneroval jsem nove klice s merchantID A1230UgNQK, poslal je do banky, bohuzel znovu dostavam odpoved 400 Bad Request.

**Comment by Miculka** [comment]
Dobrý den. 

Já tam vidím stále špatný podpis. 

![image](https://cloud.githubusercontent.com/assets/14308839/10307145/8ecce256-6c2c-11e5-945d-f65dca5ba4f8.png)

Takže testovací prostředí - testovací klíče - ve scriptu změnit ID !!!! máte jiné - a nastavit správně URL. 

Dějte vědět.

**Comment by hypertornado** [comment]
A znamena to tedy, ze URL je spravna a verejny klic k danemu merchantID je odeslan? Takze je tedy spatne pouze parametr "signature"? To by znamenalo, ze bud spatne sestavuju ten retezec na podpis, nebo ten retezec spatne podepisuji. Prikladam vystup z testovaciho skriptu, kde je prvni uveden retezec ktery podepisuji a pod nim je JSON request:

```
STRING TO SIGN:
A1230UgNQK|20|20150929181010|payment|card|100|CZK|true|http://www.example.com|POST|item1|1|100|d1|md|CZ

REQUEST:
POST /api/v1/payment/init HTTP/1.1
Host: iapi.iplatebnibrana.csob.cz
Content-Type: application/json

{
  "cart": [
   {
    "amount": 100,
    "description": "d1",
    "name": "item1",
    "quantity": 1
   }
  ],
  "closePayment": true,
  "currency": "CZK",
  "description": "d2",
  "dttm": "20150929181010",
  "language": "CZ",
  "merchantData": "md",
  "merchantId": "A1230UgNQK",
  "orderNo": "20",
  "payMethod": "card",
  "payOperation": "payment",
  "returnMethod": "POST",
  "returnUrl": "http://www.example.com",
  "signature": "gqeY72TtVqwBgL3ofvS4GLjCvQ+0kBs5me1R65Us0PHBaqdkKgehNQrU1HJzjef1yDB6KXOi4xwxoUyIVab2yWSS5wfTNXkp+tZTo0ngDoX+SS2PedOUa6fEnH/U1H52EF8oOY8coz0bbQXazW5S1jc4sMOmQKVw08NXGO8eH5zw7CyGfv/3dDehVgX+w8Gf1APxUsI08hC12o/Qkks93asKyhz2YdEE7Mn87BrbtEZzsJBttjYQpWQ8VOQeTXKJjhyjROI8E5UM1wBQVmn2cAAK2OuxVaaDqtWCSuc9baYWeg4twylk5RcIQOxeS1kg/qXZLALaTruOk2BnPRjWqA==",
  "totalAmount": 100
 }

RESPONSE:
HTTP/1.1 400 Bad Request
Content-Length: 0
Cache-Control: no-cache, no-store, must-revalidate
Connection: keep-alive
Date: Tue, 06 Oct 2015 13:18:12 GMT
Expires: 0
Pragma: no-cache
Server: nginx
Set-Cookie: BIGipServerasors_iplatebnibrana.csob.cz_6443_pool=Y55vrQSarxmfq1lYY6PqN4EWSl/lMu/30A+y5jLQt8q74xFR5MLoYvRtu9IsrYQ5JRso639icIj0VGMAAAAB;secure; path=/

```

Dalsi moznosti je, ze spatne podepisuji ten retezec. Puvodne jsem pouzival MD5 hash, ale v implementaci pro JAVU jsem si vsiml, ze se k podepisovani pouziva SHA1.

**Comment by dmarek** [comment]
retezec pro podpis vypada na prvni pohled OK, pisete spravne, ze se podepisuje pomoci SHA1. Zkuste tedy jeste jednou s timto nastavenim.

**Comment by Miculka** [comment]
zrejme tam nebude sedet certifikat - casto se to muze splest, kdyz to zkousi clovek vicekrat. Vidim v logu, ze transakce nema platny podpis.

**Comment by hypertornado** [comment]
Zkusil jsem vygenerovat dalsi certifikat (A1233aBcVn), ale stale stejny problem. Nebylo by mozne poslat nejaky klic a k nemu nejaky retezec a jeho podpis? Mohl bych si tak alespon overit, ze moje podepisovani funguje dobre. Pripadne, pokud sidlite nekde v Praze, mohl bych se stavit a dohodnout se osobne. Implementaci v jazyce Go jsem pak ochoten nabidnout jako open source. Diky.

**Comment by Miculka** [comment]
Dobrý den.  

Dívám se a dnes 14:35 opět neplatný podpis. 

Asi půjdeme po jednotlivých krocích. 

Zkontrolovat - 

1) vygeneroval jste certifikáty pro dané ID A1233aBcVn dal jste na konci procesu "Odeslat do BANKY? "

2) Máte opravdu správný "soukromý klíč ",  který jste vygeneroval k ID A1233aBcVn ?

Odkaz na branu mate spravne jinak bych vas nevidel - ID tam mate tez spravne. 

Problem je zajiste s certifikaty - nekde musi byt prohozene nebo tam nejsou ty spravne - to uz nam bohuzel technika nepovi.

**Comment by hypertornado** [comment]
Problem byl ve spatne slozenem retezci v podpisu. Nyni funguje.
