### ISSUE TITLE
Životní cyklus transakce - stav 8

### ISSUE THREAD

**Issue by yacobcz** [csob/paymentgateway#540]
Dobrý den,

u stavu 8 je uvedeno, že se lze do něj v případě autorizované transakce dostat přímo ze stavu 2.

[Průběh platby - Životní cyklus transakce](https://github.com/csob/paymentgateway/wiki/Pr%C5%AFb%C4%9Bh-platby#%C5%BDivotn%C3%AD-cyklus-transakce-)

> 8) Platba zúčtována je pro obchodníka ten správný koncový stav. Vše proběhlo, transakce byla zařazena do zúčtování, zúčtování bylo provedeno a peníze jsou na cestě. Tento stav je sice koncový, nicméně pokud se obchodník rozhodne transakci zrušit (např. pokud zákazník objednávku zruší nebo zboží vrátí v zákonné lhůtě), může prostředky vrátit zákazníkovi pomocí operace vrácení prostředků. **POZOR! Při platbě platebním tlačítkem ČSOB / Poštovní spořitelna se autorizovaná transakce dostane ze stavu 2 přímo do stavu 8. Je proto nutné, aby e-shop vyhodnocoval i stav 8 jako zaplaceno.**

Je toto pravdivá informace? 

Pokud je nastaveno `closePayment` na `true`, tak se platba ze stavu 2 dostane do stavu 7, nikoliv do stavu 8, jak naznačuje i přerušovaná čára na obrázku diagramu stavů:
![Diagram stavů](https://raw.githubusercontent.com/wiki/csob/paymentgateway/img/cz/state-transitions-cz.png)

**Comment by mbazant** [comment]
Dobrý den,

stav 7 je u transakce mezistavem, kdy transakce v pořádku projde, avšak ještě nebyla zaúčtovaná. To se děje zpravidla po půlnoci téhož dne a tím přejde transakce ze stavu 7 dostavu 8.
Je tedy potřeba, aby eshop bral jako autorizovanou platbu jak stav 7, tak stav 8.

**Comment by yacobcz** [comment]
Dobrý den,

děkuji za odpověď. Výše popsanému rozumím, nicméně:

> Při platbě platebním tlačítkem ČSOB / Poštovní spořitelna se autorizovaná transakce **dostane ze stavu 2 přímo do stavu 8.** 

Nerozumím, kdy se platba dostane ze stavu 2 přímo do stavu 8 a "přeskočí" tak zmíněný mezistav 7?

**Běžná platba:**
_(pozitivní scénář)_
Stav 1 -> Stav 2 -> Stav 4 -> Stav 7 -> Stav 8

**Autorizovaná platba:**
_(pozitivní scénář)_
`closePayment` nastaveno na `true` - _přerušovaná čára vlevo na stavovém diagramu_
Stav 1 -> Stav 2 -> Stav 7 -> Stav 8

Chápu-li správně, tím, že je platba nastavena jako autorizovaná, přeskočí stav 4, nikoliv stav 7. 
Nikdy se však platba nedostane ze stavu 2 přímo do stavu 8 (jak je uvedeno v citaci).

> Je proto nutné, aby e-shop vyhodnocoval i stav 8 jako zaplaceno.

Tuto část nezpochybňuji. Nicméně platí podle mě z jiného důvodu (např. pokud zákazník platí chvíli před půlnoci a následné ověření stavu úhrady proběhne až po půlnoci, kdy se platba stihla postupně dostat ze Stavu 2, přes Stav 7 až do Stavu 8).

**Comment by janbrasna** [comment]
> "Nikdy se však platba nedostane ze stavu 2 přímo do stavu 8 (jak je uvedeno v citaci)."

Dostane, viz zbyek té věty:

> "Při platbě platebním tlačítkem ČSOB / Poštovní spořitelna se autorizovaná transakce dostane ze stavu 2 přímo do stavu 8. Je proto nutné, aby e-shop vyhodnocoval i stav 8 jako zaplaceno."

Jsou to tyto metody: [wiki/Platební-tlačítko-ČSOB-a-Poštovní-spořitelny](https://github.com/csob/paymentgateway/wiki/Platebn%C3%AD-tlač%C3%ADtko-ČSOB-a-Poštovn%C3%AD-spořitelny) — tj. nejspíš nejen pro `/button/*` metody, ale i pro situaci kdy přímo na bráně místo karty zákazník zvolí okamžitou úhradu stržením z účtu.
