### ISSUE TITLE
Chyba transakce - testovaci platebni brana

### ISSUE THREAD

**Issue by mfeuermann** [csob/paymentgateway#542]
Dobry den

dlouhodobe pouzivame platebni branu CSOB.
Na nasi testovaci instanci nicmene prestala z nejakeho duvodu fungovat. 
Nefunguje nam ani na jednom testovacim prostredi bez zmeny naseho kodu.

Jedna se o M1E3CB3838
Produkcni instance nam bezi bez zmeny, prestal nam fungovat sandbox.

Muzete nam prosim rici proc tomu tak je ?

Dekuji 
S pozdravem
Marek Feuermann

**Comment by Mspisar** [comment]
Dobrý den,
poslední požadavek paymentInit na implementační platební bránu vidím dnes v 6:43 souhlasí s Vašim časem nefunkčnosti?  Aktuálně zasíláte pouze požadavky paymentStatus, které končí na nenalezené platbě. Komunikace na bránu je tedy v pořádku.
s pozdravem
Spisar

**Comment by mfeuermann** [comment]
Dobry den, pozadavky na stav platby jsou v poradku, nelze nam ale vytvorit nova platba. Posledni pokusy byly vcera...

**Comment by Mspisar** [comment]
Dobrý den, 
jak jsem psal poslední požadavek jsem viděl ze dneška 6:43. Problém bude zřejmě na Vaší straně.
zde záznam z posmerchantu:
![image](https://user-images.githubusercontent.com/14308940/102602369-bae18480-4121-11eb-8c43-aa542b669238.png)
s pozdravem
Spisar
