### ISSUE TITLE
Řetězec payId - povolené znaky?

### ISSUE THREAD

**Issue by rad3kM** [csob/paymentgateway#545]
Dobrý den,
od 12.1. vrácená **payId** obsahují znak "**@**" například **fac53d950d5f@GA**, je pravda že nikde nespecifikujete znaky, které řetězec může obsahovat, mám tedy počítat s čímkoliv?

Díky

**Comment by Mspisar** [comment]
Dobrý den,

velice se omlouváme za opožděnou odpověď. 

K Vašemu dotazu:

tento formát má payID vždy.

s pozdravem

Milan Spisar
IT support specialist

**Comment by janbrasna** [comment]
@rad3kM Format, delka aj. jsou zmineny v:
- #640
