### ISSUE TITLE
Platebni tlacitka HTTP 404

### ISSUE THREAD

**Issue by janbrasna** [csob/paymentgateway#546]
Polamaly se vsechny hostovane obrazky (loga a tlacitka) prime platby: [wiki/Loga-a-prezentace-platebních-metod#logo](https://github.com/csob/paymentgateway/wiki/Loga-a-prezentace-platebn%C3%ADch-metod#logo)

Kazdy konci serverovou chybou, tzn. misto obrazku se klientum zobrazuji krizky.

**Comment by Mspisar** [comment]
Dobrý den,

velice se omlouvám za opožděnou odpověď. Je prosím tento dotaz stále relevantní?

děkuji

S pozdravem
Milan Spisar
IT support specialist

**Comment by janbrasna** [comment]
Hezky den, tak to snad vite vy, zda to jiz funguje, ci nikoliv;)

Staci kliknout ^ na odkaz, pak na libovolny dalsi odkaz… a voila:

![Screenshot 2021-04-03 at 00 17 21](https://user-images.githubusercontent.com/1784648/113458246-063e4b00-9412-11eb-890f-5fd429fb73bb.png)

**Comment by dkomarek2** [comment]
Dobrý den,

URL pro hostovaná loga se změnila. V tuto chvíli byly upraveny URL na zmiňované stránce na githubu tak aby byly funkční.

Omlouváme se za vzniklé potíže.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@dkomarek2 Jasne, nicmene nikde to neni v changelogu nebo u novinek ve wiki, tj. obchodnik nema jak zjistit ze se neco zmenilo. Myslel jsem jestli stare URL nebudete treba na nove presmerovavat, ale to se taky nedeje, tak nevim jak se pripadne o takove zmene dozvedet (mimo tento tiket).

**Comment by dkomarek2** [comment]
@janbrasna dle mích informaci to byl důsledek migrace na mips2.
Kolega opravil URL operativně.
Více k tomu nevím.

**Comment by janbrasna** [comment]
No, nastesti jsou ty metody asi tak popularni, ze to vubec nikomu nezpusobilo vypadek;) Takze zaviram jako vyresene, i kdyz jsem cekal nejaky 3xx redirect nebo zminku v changelogu.
