### ISSUE TITLE
Znovu provedení zrušené platby

### ISSUE THREAD

**Issue by Pitrsn** [csob/paymentgateway#547]
Dobrý den,

Napojuji plat. branu na eshop (PHP) a sekl jsem se na jedné veci. 

Pokud uzivatel zrusi platbu primo v platebni brane, vratí se zpet na eshop s paymentStatus = 3 (6 kdyz vyprsi casovy limit), coz je v poradku. 

V momente, kdyz si to uzivatel rozmyslel a chce zaplatit, tak automaticky klikne na stejny link co mu prisel do mailu. Dostane hlasku, ze Platba byla zrusena. 
Chtel bych mu dat moznost znovu zaplatit kartou. tzn bude mit tlacitko, zaplatit online a klikne na nej. A tady se dostavam do problemu. 

1. Zkousim inicializovat stejnou platbu znova, ale skoncim s chybou, ze uz tam takova platba je. -> To chápu
2. . Pokud zkusim vytvorit uzivateli link pres toto **https://api.platebnibrana.csob.cz/api/v1.8/payment/process/{merchantId}/{payId}/{dttm}/{signature}**
Dostane se na plat. bránu s touto chybou: **We can't process your payment**

Jaký je prosimvas spravny postup, aby mohl uzivatel znovu zaplatit stejnou objednavku. Díky za odpoved a vas cas.

`$bankMerchantId = "A507099yFT"`

**Comment by Mspisar** [comment]
Dobrý den,

velice se omlouvám za opožděnou odpověď. Je prosím tento dotaz stále relevantní?

děkuji

S pozdravem
Milan Spisar
IT support specialist

**Comment by Pitrsn** [comment]
Dobrý den,
Taky se zpozdenim... 

Ano stale plati. Dokazali byste me pomoct? Chcete nejake dalsi informace?

**Comment by dkomarek2** [comment]
Dobrý den,

pokud již byla transakce (pro vás platba s vygenerovaným "payid") již zrušena (paymentStatus 6 nebo 3) tak ji již nelze znovu inicializovat. Transakce je trvale zrušena.
Pokud chcete zákazníkovi znovu umožnit platbu, pak musíte vygenerovat novou transakci pomocí requestu "payment/init" a následně "payment/process". A tuto si spárovat s vaší objednávkou na vaší straně implementace.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by Pitrsn** [comment]
Muzete zavrit, díky poimohlo.
