### ISSUE TITLE
Problém s rozparsováním "API extension detail karty pro platbu na klik"

### ISSUE THREAD

**Issue by jahr** [csob/paymentgateway#548]
Dobrý den,

chtěl bych se zeptat, jestli se něco nezměnilo v "API extension detail karty pro platbu na klik". Do 25.1.2021 všechno fungovalo jak má, od tohoto data některá z hodnot "longMaskedCln", "maskedCln" nebo "expiration" buď není přítomna nebo je v jiném formátu. Samotné rozšíření ve zprávě je, jen se nedaří načíst některou z položek.
Problém se projevuje na produkční bráně, na testovací vše funguje.

Děkuji

**Comment by Mspisar** [comment]
Dobrý den,

velice se omlouvám za opožděnou odpověď. Je prosím tento dotaz stále relevantní?

děkuji

S pozdravem
Milan Spisar
IT support specialist

**Comment by jahr** [comment]
Dobrý den,

situace se srovala, nyní vše funguje.

Děkuji a přeji příjemný den
