### ISSUE TITLE
Nepotvrzení proběhlé platby

### ISSUE THREAD

**Issue by sch3399** [csob/paymentgateway#549]
Mám docela často problém cca. 2x týdně s návratem stavu proběhlé platby z platební brány. Platba je ovšem správně zúčtovaná. Jedná se konkrétně o obj. 4e7655894b68@GA (28.1. 808,-). Prozkoumával jsem access log na našem serveru okolo času 28.01.2021 18:42:19 a brána náš systém vůbec neprovolala. 

Dokážete mi prověřit a vysvětlit k čemu zde dochází? 

Může se stát, že zákazník zavře okno platební brány a tím zblokuje potvrzení platby? Existuje v takovém případě z Vaší strany nějaký webhook pro dodatečné potvrzení?

Předem děkuji za objasnění.

**Comment by kkolarikova** [comment]
Dobrý den,
předáno na odpovědného kolegu.
S pozdravem Kolaříková Kateřina

**Comment by dkomarek2** [comment]
Dobrý den,

omlouvám se za pozdní odpověď.
Zkontroloval jsem průběh uvedené transakce a vše proběhlo z našeho pohledu v pořádku.

Ze situace, kterou popisujete je opravdu možná nějaká nestandartní akce ze strany uživatele, kterou nedokážeme ovlivnit.
Ale v tomto případě bych vám navrhnul implementování odesílání requestu typu "payment/status" v nějakém opakovaném intervalu do doby než vám vrátí úspěšný výsledek. Tento request vám vždy vrátí katuální stav transakce, takže i když by selhala standartní cesta response na vaší stranu, tak tento request vám jej vrátí taky. Na tomto základě můžete považovat poté transakci za úspěšnou či cokoliv jiného, co vám vrátí.

Definice requestu: https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody#payment-status-operation

S pozdravem,

Daniel Komárek
IT application specialist
