### ISSUE TITLE
queryOrderState

### ISSUE THREAD

**Issue by Danny177** [csob/paymentgateway#55]
Dobry den,
zvazujeme prechod z GP WebPay, brani nam v tom vsak chybejici operace: queryOrderState,
jakym zpusobem tuto operaci lze nahradit? Popr. jak zjistit stav objednavky?
Dekuji,
D.

**Comment by ratajskym** [comment]
Dobrý den, 

pro zjištění stavu objednávky musíte naimplementovat eAPI rozhraní viz [dokumentace](https://github.com/csob/paymentgateway/wiki/eApi-1.5#get-httpsapiplatebnibranacsobczapiv15paymentstatus-)
