### ISSUE TITLE
resultCode 900 Internal error

### ISSUE THREAD

**Issue by ocajda** [csob/paymentgateway#550]
Zdravím, 
snažím se implementovat platební bránu do pythonu a při volání https://iapi.iplatebnibrana.csob.cz/api/v1.7/payment/init/ dostávám odpověď  {"resultCode":900,"resultMessage":"Internal error"}

Příklad volání:
 {
   "merchantId": "M1MIPS2410",
   "orderNo": "138",
   "dttm": "20210202131044",
   "payOperation": "payment",
   "payMethod": "card",
   "totalAmount": 1789600,
   "currency": "CZK",
   "closePayment": true,
   "returnUrl": "https://...../payment_callback",
   "returnMethod": "POST",
   "cart": [
       {
           "name": "vasobchod.cz",
            "quantity": 1,
            "amount": 1789600
        }
   ],
   "description": "description",
   "language": "CZ",
   "signature": "w33x....A=="
}

Můžete prosím poradit, kde by mohl být problém? 
Děkuji.

S pozdravem,
Ondřej Cajthaml

**Comment by Mspisar** [comment]
Dobrý den,
požadavek byl zaevidován a předán k řešení. V nejbližší možné době budete kontaktován odpovědným kolegou.
s pozdravem
Spisar

**Comment by ocajda** [comment]
Dobrý den,

Můžete zavřít. Volání jsem opravil.
