### ISSUE TITLE
Napojení ČSOB brány přes GPWebPay

### ISSUE THREAD

**Issue by strita87** [csob/paymentgateway#551]
Dobrý den, 

řeším propojení ČSOB platební brány s eshopem gronych.cz. Klient má u vás smlouvu (09713409_2020) pod IČ 09713409. Nyní se snažíme napojit testovací platební bránu s číslem M1MIPS9071. U našeho eshopu nemáme propojení přímo do vaší platební brány, ale využíváme napojení pro GP WebPay a tento postup https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay.

Platební bránu jsme měli na eshopu již napojenou přes fyzickou osobu a propojení fungovalo. Nyní klient změnil své podnikání na právnickou osobu, a proto u vás podepsal novou smlouvu a je potřeba napojit novou platební bránu.

Postupoval jsem tímto způsobem:
1.	Vygeneroval jsem testovací klíče https://iplatebnibrana.csob.cz/keygen/ a nechal potvrdit veřejný klíč.
2.	Mám stažen soukromý klíč a chtěl bych pokračovat dle návodu (Privátní klíč zaveďte do svého systému, nový veřejný klíč potvrďte v systému ČSOB POS Merchant pomocí jednorázového kódu, který vám přijde na kontaktní e-mail), ale e-mail s jednorázovým kódem do e-mailu info@gronych.cz nedorazil.

Prosím o radu, jak dále postupovat a zdali napojení přes GPWebPay je stále možné a může fungovat.

Děkuji za pomoc.

**Comment by strita87** [comment]
Případně prosím o zprávu, zdali by šlo obejít testování, přepnout rovnou do ostrého režimu a tam nastavit dle vašeho návodu propojení s GPWebpay.

Děkuji za zprávu.

**Comment by dkomarek2** [comment]
Dobrý den,

tato legacy metoda je určena pro stávající provozovatele původní ČSOB GP Webpay tak aby jejich přesun na novou bránu byl co nejjednodušší. Jestli to dobře chápu, tak měníte implementaci jen kvůli změně merchantID atd. Takže by se na vás asi vztahoval tento případ a mohli by jste dále používat (pokud již používáte) tuto verzi.
Takže pokud máte již funkční implementaci, tak by měla stačit změna klíčů a vše by mělo fungovat jako dříve. Tedy bych navrhoval vyzkoušet pár základních operací aby jste si byli jisti funkcionalitou a pokud bude vše v pořádku, požádejte banku o schválení přechodu na produkční prostředí.

Nicméně vás upozorním na funkční omezení vycházející z legacy systému. Podrobnosti viz odkaz, který jste zmiňoval v dotaze.
Takže by možná stálo za úvahu zda pokud již musíte určité změny provádět tak by nestálo za to rovnou přejít na aktuální verzi eAPI v1.8, která má značné výhody ve funkcionalitě atd. To zvažte vy co by vám to přineslo či naopak.

S pozdravem,

Daniel Komárek
IT application specialist
