### ISSUE TITLE
HTML odpověď na payment/refund

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#552]
Dobrý den,

občas na API při volání payment/refund dostaneme odpověď s HTTP 200 ale s HTML obsahujícím zprávu `Request Rejected`

Co je prosím důvodem a je to správné chování? 

```
PUT /api/v1.8/payment/refund HTTP/1.1
Content-Length: 456
Accept-Encoding: gzip, deflate
User-Agent: Slevomat.cz Guzzle HTTP client
Host: api.platebnibrana.csob.cz
Content-Type: application/json

{"merchantId":"M1E3CB0860","payId":"2194e821f080cFA","amount":479000,"dttm":"20210211161304","signature":"..."}
```

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: close
Content-Type: text/html; charset=utf-8
Pragma: no-cache
Content-Length: 245
P3P: CP="{}"
Set-Cookie: TS7f993d38029=089ed84951ab2800e86a905740a1dbfa7e92db8b9612ef8600609773ad4f6983b9384edb8596e4aa48a93fd184668a6a; Max-Age=30;Path=/

<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 346652806526191545<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
```

**Comment by dkomarek2** [comment]
Odpověď emailem:


Dobrý den,

Omlouváme se za neaktivitu na portálu Github.

Váš pokus o refund jsem prověřil a bohužel během zpracování se stala chyba v našem systému a proto operace nebyla úspěšně dokončena.
Bohužel nyní je již transakce více než 13 měsíců stará a nelze tak již refundovat z našeho systému.


@Akceptacekaret - Pokud se tak již nestalo tak bych Vás moc poprosil o provedení refundu transakce „2194e821f080cFA - 7068793690“ obchodníka s ID „M1E3CB0860“ ve vašem systému.


Děkuji


S pozdravem,

Daniel Komárek
IT application specialist
