### ISSUE TITLE
Code 140 na payment/status

### ISSUE THREAD

**Issue by Sarkoncz** [csob/paymentgateway#554]
Dobrý den,

na testovací bráně https://iapi.iplatebnibrana.csob.cz/api/v1.8 jsem vytvořil platbu s ID 7dd632f722c9@GB pro merchant ID A5123UVJLh. 

Po provedení úspěšné platby chci zavolat payment/status, bohužel mi volání vrací [resultCode] => 140, [resultMessage] => Payment not found.

Mohu Vás požádat o radu, co je špatně? 
Děkuji.

**Comment by Mspisar** [comment]
Dobrý den,
Předáno na odpovědného kolegu.
S pozdravem
Milan Spisar
IT support specialist

**Comment by dkomarek2** [comment]
Dobrý den,
v logu jsem dohledal, že se vám podařilo 24.2. založit a autorizovat transakci s payID "7331b72dc772cGB". Jinou úspěšnou transakci pod merchantID "A5123UVJLh" nevidím.

Proto když voláte request payment/status na transakci "7dd632f722c9@GB" tak vám systém vrátí:
paymentStatus: payment A5123UVJLh/7dd632f722c9@GB not found

Tato transakce totiž v systému neexistuje.

S pozdravem,

Daniel Komárek
IT application specialist
