### ISSUE TITLE
Automatické rozesílání plateb 

### ISSUE THREAD

**Issue by ocajda** [csob/paymentgateway#556]
Dobrý den,

Chtěl bych se zeptat na možnost pravidelného rozesílání plateb na různé bankovní účty.
Platební brána na našem webu by měla sloužit jako prostředník. To znamená, že přes platební bránu uživatel zaplatí, my si ponecháme určitou marži a zbytek přepošleme na jiný účet. Vyváříme aplikaci pro nakupování vstupenek a peníze by měli jít různým promotérům.
Je možné nějakým způsobem implementovat, aby například každý den nebo každý druhý den se zaúčtované platby zaslaly na konkrétní účty?

Děkuji předem za odpověď.

Ondřej Cajthaml

**Comment by dkomarek2** [comment]
Dobrý den,

váš dotaz jsem přeposlal na kolegy z oddělení Akceptace karet.

Mohl by jste mi prosím poslat svůj kontakt (alespoň kontaktní email pokud bude jiný) + ID brány nebo název obchodníka abychom mohli dotaz spárovat se smlouvou u ČSOB?

Prosím na můj email: dkomarek@monetplus.cz

Děkuji

S pozdravem,

Daniel Komárek
IT application specialist
