### ISSUE TITLE
Chybějící detail provedených refundů k jedné platbě (payId)

### ISSUE THREAD

**Issue by emandevelopment** [csob/paymentgateway#557]
V poslední verzi API `PUT https://api.platebnibrana.csob.cz/api/v1.8/payment/refund`, které používáme, je `paymentStatus` po zavolání `payment/refund` vztažen k celé platbě. Chybí informace o tom, jaký je stav jednotlivých _refundů_, pokud jich k jedné platbě (`payId`) proběhlo více, což je celkem obvyklé, je-li na původní objednávce více položek.

![image](https://user-images.githubusercontent.com/3009963/111427619-ab5ce200-86f6-11eb-8eee-2caa20f2f7f8.png)

Bylo by možné doplnit do API rozpad na jednotlivé _refundy_?

## Navrhovaná řešení

1. Ideálně doplnit akceptaci `externího ID` (de facto identifikátoru refundované položky), se kterým by se endpoint `payment/refund` volitelně volal. Toto `externí ID` by pak bylo v rozpadu vidět u jednotlivých _refundů_, aby si klient mohl jednotlivé _refundy_ párovat, resp. by se použilo při volání samostatného endpointu (viz dále).
2. Alternativně by stačilo očíslovat jednotlivé _refundy_ na straně API a vracet jejich jejich identifikátory přímo při volání `payment/refund`, což už ale naráží na to, že klient nemusí zprávu dostat atd. – konsekvencí je obecně více.
3. Případně, **v první fázi by stačilo ve stavu platby alespoň vidět celkovou _refundovanou_ částku**.

Skvělé by bylo, kdyby po očíslování, resp. externím označení (body 1 a 2), se dal zavolat nový endpoint vracející stav konkrétního _refundu_.

**Comment by Mspisar** [comment]
Dobrý den,
Předáno na odpovědného kolegu.
S pozdravem
Milan Spisar
IT support specialist

**Comment by dkomarek2** [comment]
Dobrý den,

v tuto chvíli takto popisovanou operaci nemáme implementovanou v této podobě a není mi známo, že by jsme v dohledné době měli takto měnit.

Nicméně předám váš dotaz na kolegu zda není plánováno dlouhodobě.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by dkomarek2** [comment]
Dobrý den,

bylo mi potvrzeno že navrhované změny nemáme aktuálně v plánu.

S pozdravem,

Daniel Komárek
IT application specialist
