### ISSUE TITLE
Implementace platební brány

### ISSUE THREAD

**Issue by Ross-cz** [csob/paymentgateway#558]
Dobrý den,

máme provést implementaci platební brány ČSOB. Můžete potvrdit, že ČSOB používá tenhle repositář nebo máme čekat na nějaký oficiální vyjádření, na který čekáme už měsíc? Dotaz na akceptacekaret@csob.cz taky bez odpovědi...

Děkuji,
RH

**Comment by Mspisar** [comment]
Dobrý den,
Předáno na odpovědného kolegu.
S pozdravem
Milan Spisar
IT support specialist

**Comment by dkomarek2** [comment]
Dobrý den,

potvrzuji, že tento repozitář patří platební bráně ČSOB. Zdejší informace jsou platné.

S pozdravem,

Daniel Komárek
IT application specialist
