### ISSUE TITLE
Informace o proběhlé platbě

### ISSUE THREAD

**Issue by mklusak** [csob/paymentgateway#559]
Dobrý den,

mohu se zeptat na platbu payId d77c29063b25@GC, kdy v logu komunikace s platební bránou vidím zahájení transakce, zákazník odešel na platební bránu, ale už z ní nikdy nepřišla odpověď ohledně výsledku platby (byla zaplacena, ale eshop se to nedozvěděl).

Děkuji!

**Comment by Mspisar** [comment]
Dobrý den, pane Klusáku,

transakce proběhla korektně. Pro zjištění stavu objednávky slouží příkaz payment status

S pozdravem

Milan Spisar
IT support specialist

**Comment by mklusak** [comment]
Rozumím správně, že platební brána neposílá notifikaci "bokem"? Spolehá se na přesměrování zákazníka do eshopu po provedení platby s transakčními parametry v URL?

**Comment by mjanek** [comment]
Dobrý den,
transakční parametry si platební brána bere z databáze. Více informací ohledně metody payment/status najdete [ZDE](https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody#metoda-paymentstatus-). 

S pozdravem
Miroslav Janek

**Comment by martykan** [comment]
Dobrý den, zaznamenali jseme v podobnou dobu (dne 23.3.) stejný problém jako popisuje pan Klusák. 
Nebylo zavoláno returnUrl i když transakce proběhla úspěšně. 
Kód je 7cd9146733b6@GC

**Comment by dkomarek2** [comment]
Dobrý den,

zkontroloval jsem průběh transakce 7cd9146733b6@GC a zpracování proběhlo v pořádku, transakce byla úspěšně zúčtovaná.
Dle našich záznamů proběhl u této transakce i redirect na returnURL.

Opět doporučuji implementaci requestu "paymentStatus" a jeho použití v nějakém opakovaném intervalu dokud nedostanete relevantní odpověď (autorizováno, zamítnuto atp.)
Definice requestu: https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody#payment-status-operation

S pozdravem,

Daniel Komárek
IT application specialist
