### ISSUE TITLE
Vraceni penez pres eApi

### ISSUE THREAD

**Issue by Danny177** [csob/paymentgateway#56]
Zdravim,
v dokumentaci je uvedeno:
Nepodporuje částečné kredity, které se musí provádět ručně z administrace v systému POS Merchant.

Kreditovani se tak musi provadet rucne v POS Merchant, coz je casove narocne,
bude kreditovani mozne delat take pres eApi?

**Comment by ratajskym** [comment]
Dobrý den, 

pokud máte na mysli částečné návraty z provedených transakcí, tak ano. Tuto funkcionalitu připravujeme a v nejbližší době bude oficiálně k dispozici.

**Comment by Danny177** [comment]
Dobry den, 
v nejblizsi dobe znamena do kdy asi?

**Comment by ratajskym** [comment]
Dobrý den, částečné návraty jsou již k dispozici viz. dokumentace

[částečné zaúčtování] (https://github.com/csob/paymentgateway/wiki/eAPI-1.5#payment-close-desc)

[částečný návrat](https://github.com/csob/paymentgateway/wiki/eAPI-1.5#puthttpsapiplatebnibranacsobczapiv15paymentrefund-)
