### ISSUE TITLE
Neprovedená úspěšná autorizace platby v testovacím prostředí

### ISSUE THREAD

**Issue by zooroom** [csob/paymentgateway#560]
Dobrý den,

nedaří se mně provést poslední validaci v testovacím prostředí POS MERCHANT přes úspěšnou autorizaci platby.

Kartu č.: 4154610001000209 s expiraci 11/20 a CVC 100 nemohu kvůli expiraci 11/20 použít a když změním expiraci na 11/21 tak mě brána přesměruje zpět na eshop s informací k platbě: Nesprávné ověření podpisu s návratovým údaji.

Děkuji za pomoc

**Comment by Mspisar** [comment]
Dobrý den,
zkuste použít kartu 4125010001000208 - **Simulace úspěšné autentizace s CVC různým od ( 200 300 400 500 ).** 
Karta 4140920001000209 slouží jako simulace neúspěšné autentizace
s pozdravem
Milan Spisar

**Comment by zooroom** [comment]
Všechny podmínky úspěšně splněny, děkuji. Jen se mně nedaří přihlásit do produkčního prostředí POS. Do produkčního prostředí jsou jiné přihlašovací údaje než do testovacího?

**Comment by Mspisar** [comment]
Dobrý den,
v tomto případě prosím kontaktujte banku na email: akceptacekaret@csob.cz 
s pozdravem
Milan Spisar
