### ISSUE TITLE
Nesprávné ověření podpisu s návratovým údaji.

### ISSUE THREAD

**Issue by zooroom** [csob/paymentgateway#561]
Dobrý den, v produkčním prostředí POS MERCHANT potvrzena aktivace produkčních klíčů, certifikáty nahrány i na eshop ale při kažé platbě po zadání na platební bráně, dojde k přesměrování na eshop s informací k platbě: 

****Platba byla neúspěšná nebo jste ji zrušili, akci je nutné opakovat. Zpráva o chybě:
Nesprávné ověření podpisu s návratovým údaji.****

Platbu zkouším svojí vlastní kartou, nevíte kde může být prosím chyba?

Děkuji
Berka

**Comment by Mspisar** [comment]
Dobrý den,

doplňte prosím Vaše merchantID pro podrobnější analýzu.

děkuji

s pozdravem

**Milan Spisar**
1st level support - Team Leader

**Comment by zooroom** [comment]
merchantID: M1MIPS9198

Děkuji

**Comment by dkomarek2** [comment]
Dobrý den,

Vidím u vaší brány dnes 1 úspěšnou transakci "3af8cbcb2039@GD - 1210001185". 
Dále 1 zrušenou uživatelem "04add99354c6@GD - 1210001118". U této jste pozoroval popisovanou situaci?

Problém s klíči vidím v logu naposledy: Mar 31, 2021 @ 13:33:52.642.
Nemáte již tedy vyřešeno?

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by zooroom** [comment]
Dobrý den,

problém pořád bohužel přetrvává, právě jsem udělal další zkouškový nákup na mojí osobní kartu v hodnotě 5Kč a platba opět přesměrována na eshop se stejnou informací k platbě.

Na bankovním účtu, z kterého jsem prováděl zkouškové nákupy je pořád uvedeno ,,nezaúčtováno,,

Děkuji
Berka

**Comment by zooroom** [comment]
Podle POS-MERCHANT jsou platby přijaté k zaúčtování, některé jsou už zaúčtované ale po každé platbě, dojde k přesměrování na eshop s informací k platbě: 
**Platba byla neúspěšná nebo jste ji zrušili, akci je nutné opakovat. Zpráva o chybě:
Nesprávné ověření podpisu s návratovým údaji.**

Podle informací od IT může být problém ve veřejném certifikátu/klíči ale s jiným klíčem co mám k dispozici(např. z integrace) nelze platbu inicializovat. Mohu někde ještě stáhnout soukromý a veřejný klíč pro případnou zkoušku, nebo kde může být prosím problém?

Děkuji
Berka

**Comment by dkomarek2** [comment]
Dobrý den,

z toho co popisujete to opravdu vypadá na problém s ověřením odpovědi z platební brány.
Tyto odpovědi musíte ověřovat pomocí veřejného klíče banky: https://github.com/csob/paymentgateway/blob/master/keys/mips_platebnibrana.csob.cz.pub

Zkontrolujte si prosím, že používáte správný klíč a algoritmus SHA-256 (pro eAPI v1.8 a vyšší).

S pozdravem,

Daniel Komárek
IT application specialist
