### ISSUE TITLE
Návratové kódy CallOneClickInit (obchodník: M1MIPS7116)

### ISSUE THREAD

**Issue by JaroslavDuska** [csob/paymentgateway#562]
Dobrý den,

v případě volání metody CallOneClickInit dostávám zpět chybové kódy 150 (ResultCode: 150, ResultMessage: orig payment not authorized, oneclick card expired) a 180 (ResultCode: 180, ResultMessage: orig payment not found). 
Podle číselníku návratových kódů na adrese https://github.com/csob/paymentgateway/wiki/Vol%C3%A1n%C3%AD-rozhran%C3%AD-eAPI#operation-return-code bych ale očekával v případě volání inicializace platby na klik chybové kódy 700-740, proč mi tedy brána vrací výše uvedené?

Děkuji, Duška Jaroslav

**Comment by Mspisar** [comment]
Dobrý den,
požadavek předán na odpovědného kolegu. Co nejdříve budete kontaktován.
S pozdravem
Milan Spisar

**Comment by JaroslavDuska** [comment]
Z testování jsem zjistil, že návratové kódy 700-740 vrací volání metody OneClickEcho, metoda OneClickInit vrací nějaké jiné a jejich přehled není na wiki uveden. Dotaz zavírám, problém vyřešen.
