### ISSUE TITLE
mallpay/init status code 500

### ISSUE THREAD

**Issue by lukasjanikcz** [csob/paymentgateway#563]
Dobrý den,
rozšiřujeme napojení o MallPay a když zašlu testovací data na mallpay/init, vrací mi brána status code 500, který není v dokumentaci nikde popsán.

Zasílané data:
```
{
	["merchantId"]=> string(10) "M1E3CB0797"
	["orderNo"]=> int(15604)
	["customer"]=> array(3)
	{
		["fullName"]=> string(8) "John Doe"
		["email"]=> string(12) "john@doe.com"
		["phone"]=> string(9) "123456789"
	}
	["order"]=> array(4)
	{
		["totalPrice"]=> array(2)
		{
			["amount"]=> int(1452000)
			["currency"]=> string(3) "CZK"
		}
		["totalVat"]=> array(3)
		{
			["amount"]=> int(252000)
			["currency"]=> string(3) "CZK"
			["vatRate"]=> int(21)
		}
		["addresses"]=> array(5)
		{
			["addressType"]=> string(7) "BILLING"
			["streetAddress"]=> string(13) "Radlická 333"
			["city"]=> string(7) "Praha 5"
			["zip"]=> string(5) "15000"
			["country"]=> string(2) "CZ"
		}
		["items"]=> array(1)
		{
			[0]=> array(4)
			{
				["code"]=> string(4) "X123"
				["name"]=> string(9) "iPhone XS"
				["totalPrice"]=> array(2)
				{
					["amount"]=> int(1452000)
					["currency"]=> string(3) "CZK"
				}
				["totalVat"]=> array(3)
				{
					["amount"]=> int(252000)
					["currency"]=> string(3) "CZK"
					["vatRate"]=> int(21)
				}
			}
		}
	}
	["agreeTC"]=> bool(false)
	["clientIp"]=> string(11) "192.168.0.3"
	["returnUrl"]=> string(47) "http://www.xmlshop.cz/objednavky/?objlist=15604"
	["returnMethod"]=> string(4) "POST"
}
```

podpisový řetězec
"M1E3CB0797|15604|John Doe|john@doe.com|123456789|1452000|CZK|252000|CZK|21|BILLING|Radlická 333|Praha 5|15000|CZ|X123|iPhone XS|1452000|CZK|252000|CZK|21|false|192.168.0.3|http://www.xmlshop.cz/objednavky/?objlist=15604|POST"

Když zašlu chybná data, vrací brána status code 400.

Prosím o prověření.

**Comment by Mspisar** [comment]
Dobrý den,

požadavek zaevidován a předán odpovědnému kolegovi. O dalším průběhu budete informován.

S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,

na první pohled vidím, že vaše data neobsahují parametr "dttm" který má obsahovat datum.
Z tohoto parametru bych si vyčetl datum a čas pokusu abych jej mohl zkontrolovat v našem logu.
Je to jeden z povinných parametrů, který request musí obsahovat.

Prosím zkontrolujte si, že vámi odesílaný request obsahuje všechny povinná pole.
Definice requestu mallpay/init: https://github.com/csob/paymentgateway/wiki/Metody-pro-Mall-Pay#mallpay-init-operation

Pro kontrolu bych potřeboval datum a přesný čas pokusu abych to dohledal v našem logu.
Dále prosím uvedení na jakou URL posíláte request - uveďte prosím celou URL.

Děkuji.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by lukasjanikcz** [comment]
Dobrý den,
přidán dttm, ale stále API vrací status code 500.
Odesílaná data:
```
{
   "merchantId":"M1E3CB0797",
   "orderNo":"9999",
   "customer":{
      "fullName":"John Doe",
      "email":"john@doe.com",
      "phone":"123456789"
   },
   "order":{
      "totalPrice":{
         "amount":"1452000",
         "currency":"CZK"
      },
      "totalVat":{
         "amount":"252000",
         "currency":"CZK",
         "vatRate":"21"
      },
      "addresses":{
         "addressType":"BILLING",
         "streetAddress":"Radlicka 333",
         "city":"Praha 5",
         "zip":"15000",
         "country":"CZ"
      },
      "items":[
         {
            "code":"X123",
            "name":"iPhone XS",
            "totalPrice":{
               "amount":"1452000",
               "currency":"CZK"
            },
            "totalVat":{
               "amount":"252000",
               "currency":"CZK",
               "vatRate":"21"
            }
         }
      ]
   },
   "agreeTC":false,
   "dttm":"20210426133904",
   "clientIp":"192.168.0.3",
   "returnUrl":"http://www.xmlshop.cz/objednavky/?objlist=15604",
   "returnMethod":"POST"
}
```

**Comment by dkomarek2** [comment]
Dobrý den,

na integračním prostředí (https://iapi.iplatebnibrana.csob.cz) vidím vaše pokusy s requestem "mallpay/init" a poslední tam dorazil 20.4. 09:59:24.685.
Tyto pokusy skončily na chybě: Invalid mallpayInit signature.
Tedy problém s klíči, odesílanými daty nebo algoritmem šifrování.

Na produkčním prostředí () vidím vaše pokusy o request "payment/init" které taky končí na chybě "Invalid signature". Poslední je z 15.4. 15:46:55.839

Tedy prosím o upřesnění na jaké prostředí - na jakou URL requesty zasíláte.

Ověřte si, že používáte správné klíče, určené pro dané prostředí.
Dále že se odesílaná data v JSONu shodují s daty ve stringu pro vytvoření podpisu (signature) - zde je důležité i pořadí dat.
Dále je důležitý algoritmus pro šifrování dat založený na SHA-1 (pro eAPI v1.7 a nižší), nebo SHA-256 (pro eAPI v1.8 a vyšší).

Pro odladění problémů s klíči můžete použít request "echo" který je na to určený. Jeho definice: https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody#echo-operation

Prosím o upřesnění a kontrolu vaší implementace.

Pro lepší komunikaci + možné zasílání citlivějších dat navrhuji přejít na emailovou komunikaci.
Můžete mi napsat na můj email: dkomarek@monetplus.cz

S pozdravem,

Daniel Komárek
IT application specialist
