### ISSUE TITLE
Payment refund (405) Method Not Allowed

### ISSUE THREAD

**Issue by VeselyJanHelpIS** [csob/paymentgateway#569]
Dobrý den,

v testovacím prostředí se snažíme o vrácení platby, ale vrací se nám status (405) Method Not Allowed.
Data níže posíláme jako POST na https://iapi.iplatebnibrana.csob.cz/api/v1.8/payment/refund

V čem je problém?

Jan Veselý
HelpIS, s.r.o.

{
  "merchantId": "M1MIPS5935",
  "payId": "fd29b2b726469GD",
  "dttm": "20210427164546",
  "signature": "NnvTzfijoPRM8BrHVE7J60osOyEMHvfumQXZputHgUr91SUnESCFZb1H/gr0GyO2O4PDe3ZQ9BbOIHQurTRUwvaP1WXBIMyjpYncWGv9qM7/PvcbYwUFAFtMKgtsLWriMh0dMHYS/XIiDjnCq0OWornDkpHS5Wzr/tfYZJud82obvKMNbXYivUJFovvuLsoYy0YWwIrlRrWZI/G3ENDmK0Yy7e6fPb3dVu+uTAGUlwpNTbcWrIOhEa+6sDgA80Nzcq0g4tm8+63BdMCx2l1JufhrepyAveKEAZSs6o+iX7TfC1wYUh5ogOGCLFE7wdXP+J0vKqY+UU8lyxK22yiF8g=="
}

**Comment by dkomarek2** [comment]
Dobrý den,

Odepsal jsem vám dnes na emailovou komunikaci

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by VeselyJanHelpIS** [comment]
No jo přehlédl jsem, že jde o PUT.
Vyzkoušíme.
Děkuji

**Comment by dkomarek2** [comment]
Dobrý den,

děkuji za potvrzení.

S pozdravem,

Daniel Komárek
IT application specialist
