### ISSUE TITLE
endpoint `customer/info` nevrací `customerId`. Dokumentace tvrdí opak

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#57]

**Comment by dmarek** [comment]
díky za upozornění, opravíme dokumentaci (customerId v response být nemá).

**Comment by dmarek** [comment]
nakonec opraveno v aplikaci (dokumentace zustava nezmenena, vcetne ukazkovych prikladu)
zmena je nasazena na integracnim prostredi
