### ISSUE TITLE
Exspirace transakce

### ISSUE THREAD

**Issue by rad3kM** [csob/paymentgateway#570]
U metody **payment/init** je parametr **ttlSec**, který určuje životnost transakce, zaznamenal jsem, že transakce exspirují dříve než je stanoveno parametrem.

Například u testovací platby **29068865300f@GE** s **ttlSec** = 600, zavedena **05.05.2021 15:35:59** a k exspiraci došlo **05.05.2021 15:44:00**, tedy cca po 8 minutách místo očekávaných 10 min.

**Comment by janbrasna** [comment]
@mrazekl Muzu poprosit o kontrolu logu? ^^ Vyprsela trx ve zminenych timestampech, a nebo to jen uspechalo API a zatahlo si za /timeout drive u klienta, nebo opravdu nastal uz v tomto case zevnitr na zivotnim cyklu a vratil ho takto /status?

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,

prověřil jsem transakci a ty čísla sedí v DB i logu s vašimi údaji.
Ještě to probereme kde může být chyba.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@dkomarek2 Je k tomu nejaky update, nalez nebo vysvetleni proc by to mohlo nastat?

@rad3kM Stava se to prosim i nadale?

**Comment by rad3kM** [comment]
Stále trvá, vyzkoušel jsem i změnu na 5min limit a k exspiraci došlo po cca 3, takže vám to někde ukusuje 2 minuty.

> [2021-09-20 07:44:47.730700] - ECHO
[2021-09-20 07:44:47.808942] - INIT
[2021-09-20 07:44:48.009374] - PROCESS 3df98f61b215@GI
[2021-09-20 07:47:50.797263] - EXPIRE 3df98f61b215@GI

**Comment by janbrasna** [comment]
@rad3kM Hezky den, diky za potvzeni. Nejaky TTL fix probehl pres leto, ale vas problem evidentne nevyresil :/ (Vim o known issue s kracenim TTL na trx v radu desitek dnu, ale u beznych v radu minut-hodin, bez externi platebni metody, to je divne. Uvidime s cim prijde support.)

**Comment by rad3kM** [comment]
Možná je to úplně mimo, ale web platební brány obsahuje mimo jiné i `<body data-init="{"mipsTimeout":179787}">` což přibližně odpovídá těm třem minutám při zadaném **ttlSec = 300**. 

U **ttlSec = 600** je tam pak hodnota 479577 (cca 8min).

**Comment by dkomarek2** [comment]
Dobrý den,

objevili jsme chybu v našem systému, která mohla ovlivňovat čas expirace transakce.
Chybu v nejbližší době opravíme.

Omlouváme se za vzniklé potíže.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@rad3kM Vubec to neni mimo, uvazujete spravnym smerem — tam se presne predava tolerance mezi API lifecyclem a UI lifecyclem, a vypada to ze se od nejakeho bodu pro nejake trx neposila spravne (nejvic to je videt na extremne kratkych, a extremne dlouhych TTLs), uz se resi proc. Diky za potvrzeni!

**Comment by janbrasna** [comment]
Uz by melo byt TTL honorovano spravne i pro ruzne kratke ci dlouhe custom hodnoty.

@rad3kM Zkuste prosim zda se to i pro vase transakce vyresilo a nepozorujete odchylky, je pak mozno zavrit.

**Comment by rad3kM** [comment]
Už se to zdá v pořádku, děkuji.
