### ISSUE TITLE
MallPay - expirace transakce

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#571]
Dobrý den,

zdá se že platební brána a MallPay nijak nereflektují parametr ttlSec volání mallpay/init. Máme ze včerejška platbu `8b05aafa0904@GE` na bráně `M1E3CB0860`. Byla založena s ttl 1 hodiny a přesto je pořád aktivní. V rozhraní Mall Pay je platba již expirovaná, k tomu ale došlo až po několika hodinách od založení, ne po hodině (nebím přesně, byla noc...)

Platební brána ale v payment/status stále říká že platba je ve stavu 2 - probíhá. I teď, po 22 hodinách od založení.

**Comment by janbrasna** [comment]
@mrazekl Muzu poprosit o kontrolu logu? ^^ Kdy se zmenil stav z [2] na nejaky terminalni? (a zda bylo info od MP ze trx vyprsela, a kdyztak zkusit dat proverit proc nevyprsela ze strany merchantskeho ttl drive, nebo nejhure po 12h zivotnosti MP trx, prosim?)

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaevidován  a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,
prověřil jsem tuto transakci a vše sedí jak je napsáno, což je zvláštní.
Proberu ještě s kolegou jaké jsou možnosti.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@janlanger Tusite kdy (a zda vubec) se ta trx nakonec realne zamitla? Nebo tam sviti jako (2) az dodnes?

@dkomarek2 Je k tomu prosim nejaky update, nalez nebo vysvetleni jak to muze nastat? Diky.

**Comment by janlanger** [comment]
@janbrasna v posmerchantu se pořád ukazuje ve stavu 2 - zpracování objednávky

**Comment by dkomarek2** [comment]
Dobrý den,

zjistili jsme, že vlivem konfigurace systému neprobíhalo nastavování správného stavu transakce po vypršení expirace MallPay transakcí.
Konfiguraci jsme opravili a nyní má již transakce správný stav.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@dkomarek2 Kazdopadne i kdyby nemel dorazit nejaky notice ze strany MP, tak by asi vzdy transakce mela defaultne vytimeoutovat a) po svem nastavenem TTL, b) po maximalnim moznem TTL pro MP lifecycle obecne.
