### ISSUE TITLE
MALL Pay - neplatný podpis odpovědi z mallpay/init 

### ISSUE THREAD

**Issue by lubomirpokorny** [csob/paymentgateway#573]
Dobrý den,

po založení platby na **mallpay/init** a zamítnutí platby v prechecku (návratovém kódu **600**) se nám nedaří ověřit podpis. 

Odpověd:
```
{
  "dttm": "20210530035152",
  "signature": "bMfEQ3trxiNZcNxz/YK+i9zHNojVSOAMKB4ZDD7inSNlNxHOGLkH6vMMuzn7B0am+0w4eehs2VmkJxOBb3DAMJ+NCSQsPTTtRYv7svkSkno071+tt0aGZGZMPv8IDxO/gEFNsda8iTMvNLVARnHFnsplLChNmcmIXg9ySMPzEFpA2+ouFvyIHzYXtqg0c0MNp7WsnYWgZGIlMgLRpiyQvhd/CbJbpTQS5nT9iv2HC0Y0c4tOHBZm+VA87e9y3Zq0hdW6fBWiZyusEYG2n4SthiqOkxbJFgKssBRW/MGRX30rspRXpvUbzAkhv5BHeG6xfbTHq7bN42PNJLXHciJYSA==",
  "payId": "6d6fa3bd5d6c@GE",
  "resultCode": 600,
  "resultMessage": "MALL Pay payment declined in precheck",
  "paymentStatus": 6
}
```

Pořadí použití hodnot při sestavování řetězce pro ověření: 
1. payId
2. dttm
3. resultCode
4. resultMessage
5. paymentStatus

Podpisy všech ostatních odpovědí bez problému ověříme (včetně ne-MALL Pay).

Děkuji za prověření,
Pokorný

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,

pořadí jak ho uvádíte je podle mě správné.
Takže může být problém v použitém klíči - ověřte si prosím, že používáte pro odpovědi z banky veřejný klíč banky (nikoli váš veřejný klíč) - https://github.com/csob/paymentgateway/blob/master/keys/mips_platebnibrana.csob.cz.pub
Dále může být problém s použitým algoritmem - ve vašem případě musí být založen na SHA-256.
Poslední možnost co mě napadá je neshoda dat v tom řetězci vůči datům v té odpovědi.
Samozřejmě je důležité to pořadí.

Prosím překontrolujte parametry.

Děkuji

S pozdravem,


Daniel Komárek
IT application specialist
