### ISSUE TITLE
Z returnUrl mizí předávaný parametr mc

### ISSUE THREAD

**Issue by Ross-cz** [csob/paymentgateway#574]
Dobrý den,

náhodně se nám na produkci stává, že zmizí z returnUrl query parametr, který je uprostřed URL. Tento parametr používáme k vyhodnocení identity obchodníka a nemění se při ostatních platbách. Může mít vliv to, že se jmenuje "mc"?
Url je dlouhá 232 znaků a je složená např. takto: https://.../PaymentGateway/Csob/PaymentResponse.ashx?on=20214542&mc=M.....80&cru=https%3A%2.......
Platební brána přesměruje na neplatnou url - vynechá parametr mc, např. https://.../PaymentGateway/Csob/PaymentResponse.ashx?on=20214542&cru=https%3A.......
User-agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Náš systém platbu odmítne, protože ji tento parametr chybí.
Můžete se prosím podívat na tyto případy?
2021-05-30 14h
4e07d30a63d9@GE
f28a5f708868@GE
cb1189aa8347@GE

Děkujeme.

R

**Comment by Mspisar** [comment]
Dobrý den,

požadavek byl zaevidován a předán k řešení odpovědnému kolegovi. O dalším průběhu budete informován.

S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,

zkontroloval jsem jeden vámi dodaný příklad transakce "4e07d30a63d9@GE".

Request pro založení transakce na platební bránu přišel s touto returnUrl:
` "returnUrl":"https://api.quickmedia.tv:443/PaymentGateway/Csob/PaymentResponse.ashx?on=20214542&mc=M1MIPS9280&cru=https%3A%2F%2Fwww.jedensvetonline.cz%3A443%2Fafterpaymentgateway%3FreturnUrl%3Dmovies%252Fnase-generace-z_78485" `

Po úspěšné autorizaci transakce byl proveden redirect uživatele včetně resultCode atd:
` Payload: {"redirect":{"url":"https://api.quickmedia.tv:443/PaymentGateway/Csob/PaymentResponse.ashx?on=20214542&mc=M1MIPS9280&cru=https%3A%2F%2Fwww.jedensvetonline.cz%3A443%2Fafterpaymentgateway%3FreturnUrl%3Dmovies%252Fnase-generace-z_78485","method":"POST","vars":{"payId":"4e07d30a63d9@GE","dttm":"20210530142747","resultCode":"0","resultMessage":"OK","paymentStatus":"7","authCode":"134599","merchantData":"TTFNSVBTOTI4MHwyMDIxNDU0Mg==","signature":"VTZg5r1ydEfZwDI4PtO3crgBZRpDRWfg2RhueJTLSE88oMhvrtmYsB6F/XxW2viVUFI/Zp81rN0oEGxxJkl6kTeJxQUNslI7S4g877AlQ+vG9hkOuzcmn9Megk0P9wraWE1qiXzindLrHhby4hiUG5t8RHDe8wpUZbfXFNnX1KFYthiEOyhmfqIIJ0L8+00mv4tYCbs28lUOPXo5G76QD7TAE1C/DuUwQmKJp994Hzv1evWMyuJoe0MVevXFdATU854+dpY4QzeFetKYOFwZX8zre15AVzZhcfLlkKtSEHXyUOrn6YppXPgNub7rT6uLJH6eohI/qcAcQohdNCgO0Q=="},"timeout":2500},"poll":false,"html":"<p class=\"main-msg\">Dokončujeme platbu</p><p class=\"msg return-link-text\">Vyčkejte, prosím, na&nbsp;přesměrování k obchodníkovi.</p>","status":"processed"} `

Z našeho pohledu to vypadá v pořádku - url vypadá stejně.
Nejsem si ovšem jist validitou té URL v rámci nějakých pravidel pro http (musel bych nechat ověřit).
Každopádně redirect jsme provedli na vámi dodanou URL.

Pokud si potřebujete předávat informaci která se vám vrátí s transakcí tak vám nestačí si to uložit do parametru "merchantData"? Vidím že to používáte.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@Ross-cz Dokazete poznat, o jaky UA se jedna, kdyz parametr "zmizi"? Stane se to jak pri POST, tak pri GET? (Kdysi tady jiny obchodnik debugoval problemy tusim IE11, nejakych redirectu/SSO/cache po ceste, a prepisovani ("downgrade") POST na GET pozadavku atd. … a cestou se ztracely nejake promenne. Tak jestli v tech chybovych pripadech nevidite nejaky vzorec user agenta, platformy atp.?)
