### ISSUE TITLE
WebView receive error

### ISSUE THREAD

**Issue by voneskuba** [csob/paymentgateway#575]
Zdravím,

v produkci se nám od pátku stává, že webview na androidu nedokáže načíst platební bránu. Důvodem je error u resources, konkrétně `https://platebnibrana.csob.cz/favicon.ico`, můžete asap vyřešit prosím?

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.

S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,

probíhaly nějaké úpravy webu kvůli testům.
V tuto chvíli by mělo být již opraveno, můžete prosím vyzkoušet znovu?

Děkuji

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by voneskuba** [comment]
@dkomarek2 vypadá to, že funguje. Díky.

**Comment by dkomarek2** [comment]
Dobrý den,

děkuji za potvrzení.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@dkomarek2 No nicneme ten .ico asset stale vraci 404 chybovou stranku, nebylo by jednodussi ho tam proste pridat, at je od nej klid?

**Comment by dkomarek2** [comment]
@janbrasna dle mých informaci jde o dočasnou změnu, takže předpokládám, že se vrátí funkcionalita zpět.

**Comment by janbrasna** [comment]
@voneskuba Ukazalo se, ze ten root site obsluhuje marcom/agentura, a mezi updaty neni spoleh na konzistenci podobnych krosreferovanych podkladu v case, takze nektery z pristich releasu v radu tydne ci dvou si to vyresi uvnitr aplikace, a zmizi i ta posledni 404ka. Diky za nahlaseni!
