### ISSUE TITLE
endpoint `payment/init` a pozice `customerId` v podpisu.

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#58]
Z dokumentace není úplně jasné, kam zařadit `customerId` ve zprávě pro podpis (endpoint `payment/init`). Metodou pokus-omyl jsem sice na to přišel, ale mohlo by být v dokumentaci upřesněno.

**Comment by dmarek** [comment]
Parametr `customerId` je umístěn v řetězci pro podepsání mezi parametry `merchantData` a `language`, v dokumentaci je i příklad s [popisem](https://github.com/csob/paymentgateway/wiki/eAPI-1.5#sestaven%C3%AD-podpisu-vol%C3%A1n%C3%AD)
