### ISSUE TITLE
Dokumentace pro init neobsahuje polozku Description. Je pouze v prikladu. 

### ISSUE THREAD

**Issue by kasparkova-arion** [csob/paymentgateway#582]

**Comment by janbrasna** [comment]
@kasparkova-arion Hezky den, muzete prosim poslat odkaz na misto, ktera ma `description` v prikladu volani? Byl pouze ve starsich verzich (pro 3D Secure 1.x svet) a zadny example aktualni v1.8 by ho nemel nikde v dokumentaci obsahovat. Pokud ano, je to bug.

Co me napada je known issue #493 s .NET priklady, ktera opravdu stary description definuje:

https://github.com/csob/paymentgateway/blob/10941461faa3dc654c81df2ab524ec966571e7e9/Integration%20Examples/eAPI%20v1.8/dotNET/CsobGTWDemo/CsobGatewayClientExample/Communication/DataObjects/PayInitReq.cs#L37-L75

ale do requestu uz by se posialt nemel, podle vyse zmineneho ticketu v samotnem jsonu neni.

Pokud je toto na co jste narazila, tak klidne konkretni vyskyty nahlaste do zmineneho ticketu, at je tam maji na jednom miste. Priklad spojeni jinak funguje, nebo se diky tomu ani nepodari sestavit stringbuilderem spravny retezec k podpisu, tj. na aktualni eAPI v1.8 ten C#/.NET example ani nefunguje?

**Comment by kasparkova-arion** [comment]
ano slo mi presne o priklad kodu ktery uvadite. Pridam do #493.
