### ISSUE TITLE
Upravení údajů o platební bráně

### ISSUE THREAD

**Issue by ocajda2** [csob/paymentgateway#584]
Dobrý den,
Potřeboval bych přes https://posman.csob.cz/posmerchant změnit údaje o platební bráně  (Název, doménu, url, emaily a telefony). Nemohu nikde najít možnost editace.

Můžete mi prosím poradit?

Děkuji.

S pozdravem,
Ondřej Cajthaml

**Comment by Mspisar** [comment]
Dobrý den,
požadavek o změnu údajů prosím zašlete na akceptacekaret@csob.cz.
s pozdravem
Spisar
