### ISSUE TITLE
Potvrzení funkčnosti iapi.iplatebnibrana.csob.cz

### ISSUE THREAD

**Issue by stik** [csob/paymentgateway#585]
Zdravím,
můžete mi potvrdit funkčnost testovacího prostředí ( PHP )? Ještě včera běželo vše v pořádku. 
Dneska již hlásí: payment/init failed, unable to verify signature

Klíče používám stejné jako včera / zkusil jsem vygenerovat i nové merchant ID a klíče, ale stále brána hlásí chybu ověření.
* Nefunguje ani implementace této knihovny doplněné pouze o klíče. 

Pokud použiji knihovnu od OndryKoupila, tak knihona hlásí ( ještě opakuji, včera vše naprosto v pořádku ): 
Something went wrong: Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date.

**Comment by Cipery** [comment]
Máme stejný problém, podpisy odpovědí z integračního prostředí platební brány nejsou správně podepsané

**Comment by kasparkova-arion** [comment]
mám stejný problém - v1.8, implementace dotnet. Neprojde verifikace podpisu odpovedi. Vcera vse ok.

**Comment by Cipery** [comment]
Zdá se, že to již funguje

**Comment by kancek** [comment]
Potvrzuji, už to funguje, díky.

**Comment by stik** [comment]
Nevím jak Vám, ale mě po transakci nevrací správný formát dat. 
Takže za mě stále nefunkční. ( ale transakce se už alespoň založí )

**Comment by VachaJiri** [comment]
Příjde mi, že problém je opět aktuální. Nemáte někdo stejný problém ?

**Comment by janlanger** [comment]
@VachaJiri máme taky problém s nefunkčností. Ne teda že by byl špatný podpis, api vůbec nefunguje https://github.com/csob/paymentgateway/issues/588

**Comment by ondrejneufinger** [comment]
Nevím jak moc je to aktální, ale na iplatebnibrana,csob.cz mě nejde ani regulérně zaplatit testovacími kartami

**Comment by janbrasna** [comment]
@ondrejneufinger Mozna stejny problem jako #589?

**Comment by janbrasna** [comment]
Bohuzel si problem nikdo podle vseho nechtel vzit za vlastni :O tak to tady asi nebudeme susit bez odpovedi nadosmrti. Nicmene to vypada ze vsechny bugy okolo migrace sandboxu a prenastaveni firewallu/loadbalanceru se snad postupne vyresily, a nevypadavaji tam na pozadavcich na api ani na web/app/simulatory nejake dalsi incidenty — pokud ano, tak prosim vzdy pro kazdy pripad otevrete separe issue, idealne i s ID ci snimkem toho stavu, aby se dal v networkingu dohledat. Ale snad to nebude potreba. Diky.
