### ISSUE TITLE
Nefungující MallPay SIM z důvodu chybějícího DNS záznamu?

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#587]
Dobrý den,

ještě pár dní zpět mi URL adresy pro MallPay SIM fungovaly, nyní nikoliv. 

Tvar URL: `https://i-sim.asors.csob.cz/mallpay-sim/SIM/mallpay/<uuid>`

```
curl https://i-sim.asors.csob.cz/mallpay-sim/SIM/mallpay/<uuid>
curl: (6) Could not resolve host: i-sim.asors.csob.c
```

Používám tyto DNS servery:

```
> cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 1.1.1.1
```

Browser:

![image](https://user-images.githubusercontent.com/383294/122881987-04fb2b00-d33c-11eb-983d-3df1959e24dd.png)

Je chyba u vás, nebo dělám něco blbě? Děkuji.

**Comment by mrazekl** [comment]
Dobrý den,

adresa simulátoru byla přenesena na jinou doménu, můžete vyzkoušet?:
https://i-sim.monetplus.cz/mallpay-sim/SIM/mallpay/<uuid>

**Comment by pepakriz** [comment]
@mrazekl Jako jo, nová doména se zdá, že je nachystaná na přijímání nových adres, ale API volání `mallpay/init` vrací HTML místo JSON s nějakým ticket id nebo co to je (`Your support ID is: 585713142689587933`). Takže stejně kompletní platební flow nefunguje.

Máte možnost si prosím otestovat na nějakém vašem testovacím accountu happy path, že vám mall pay funguje jak má? Jinak tady docela pálím čas a raději si počkám, až bude vše spravené. Děkuji.

**Comment by mrazekl** [comment]
Dobrý den,
zřejmě sem to uplně nepochopil. Tohle je uri mallpay simulátoru, ale na inicializačním volání mallpay/init se nic nemění.
mallpay/init  volejte beze změny a směřujte standartně na https://iapi.iplatebnibrana.csob.cz/api/v1.8
a platební brána následně zporcesuje přesměrování na adresu simulátoru

**Comment by pepakriz** [comment]
@mrazekl pochopil jsem to správně. Na volání mallpay/init jsem nic neměnil. (`POST https://iapi.iplatebnibrana.csob.cz/api/v1.8/mallpay/init body={"orderNo":"123",…`)
a dostávám HTML odpověď. Včera podobné pokusy (jen jiné orderNo) končily úspěšně.

**Comment by mrazekl** [comment]
můžete to, prosím, zkusit znova? Včera od 20:05 do dnešních 8:30 jsme se na testovacím prostředí potýkali s technickými problémy síťového charakteru. Děkuji.

**Comment by pepakriz** [comment]
@mrazekl Ano, potvrzuji, už to funguje. Děkuji.
