### ISSUE TITLE
Nedostupná iplatebnibrana.csob.cz

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#588]
Dobrý den, 

testovací api https://iapi.iplatebnibrana.csob.cz/api/v1.8/ je již minimálně druhý den nefunkční.

`cURL error 56: TCP connection reset by peer`

Nefungují karty ani třeba simulace Mall Pay

**Comment by mrazekl** [comment]
Dobrý den,

16.6 večer po 22 hodině došlo ke změně DNS záznamů pro https://iapi.iplatebnibrana.csob.cz
Z chyby, kterou popisujete, je možné, že máte pro https://iapi.iplatebnibrana.csob.cz nastavenou napevno IP adresu?
Pokud ano, změntě prosím ideálně na dynamický DNS název, nebo na novou IP adresu.

**Comment by janlanger** [comment]
IP určitě napevno nastavenou nemáme. iapi.iplatebnibrana.csob.cz se mi resolvuje na 193.245.38.104 u mě, na našich serverech i třeba zde https://dns.google.com/query?name=iapi.iplatebnibrana.csob.cz

**Comment by mrazekl** [comment]
Dobrý den,
ano, toto je správná IP adresa po přepnutí. Tento problém není aplikačního rázu, bude spočívat v síťovém spojení, bylo by prosím možné sdělit email na nějakého vašeho kolegu síťaře, se kterým by se následně spojil náš kolega z infrastruktury, aby to mohli společně analyzovat?

**Comment by janlanger** [comment]
Dobrý den, nezdá se mi že by problém byl způsobený konkrétním providerem, zaznamenali jsme ho při testování přes běžné připojení od UPC a Dial Telecomu i z testovacího serveru v datacentru stable.cz/Superhosting. A podle 👍  reakcí tady se nezdá, že bychom byli jediní...

**Comment by l1zard** [comment]
@janlanger @mrazekl 

Ano máme stejný problém.

**Comment by pepakriz** [comment]
U nás potvrzuju funkčnost testovacího prostředí, jak přidání karty, tak i oneclick platby. Mall Pay se řešilo v samostatném issue, ale to se zdá být nyní také OK. IP adresa API se nám resolvuje na `193.245.38.104`.

**Comment by mrazekl** [comment]
@l1zard 
@janlanger
bylo by prosím možné přidat nějaký log, ať můžeme alespoň něco předat naší infrastruktuře?

**Comment by pepakriz** [comment]
@janlanger nemůže být problém se SSL? Dokážeš chybný request zreprodukovat s curl? Bych to zkusil spustit od sebe, kdyby ti nevadilo, že ti založím platbu v test prostředí :)

**Comment by janbrasna** [comment]
Pokud je problem s kompletnim resolvem tak je mozne GET/HEAD na

- https://iplatebnibrana.csob.cz/pay pro payments/web status
- https://iapi.iplatebnibrana.csob.cz/api/v1.7/ a pro api status

a netreba klice a zakladat trx atp., pokud se neprobourate ani tam (na "OK" response stranku)

**Comment by janlanger** [comment]
Mno, je to zajímavé. Vypadá to že blokujete User-Agent který obsahuje "HTTP client"

Toto totiž nefunguje ```curl --location --request GET 'https://iplatebnibrana.csob.cz/pay' 
--header 'User-Agent: Guzzle HTTP client'``` ale bez té hlavičky ano

**Comment by jstorm31** [comment]
Dobrý den, narazil jsem na stejný problém. Status request ☝️ pro mě nefunguje ani bez hlavičky:
```
❯ curl --location --request GET 'https://iplatebnibrana.csob.cz/api/v1.8'
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

Volání ze serveru taky výsledek `Connection reset by peer (errno: 54)`. Je nějaký update z vaší strany @mrazekl?

**Comment by mrazekl** [comment]
Dobrý den,
obecně bych chtěl přidat do diskuze, že mám od kolegů z infrastruktury informaci, že v pátek bylo "whitelistováno" volání obsahující --header parametr

@jstorm31
tenhto endpoint neexistuje, dosupné jsou pouze tyto, jak uvádí @janbrasna 
https://iplatebnibrana.csob.cz/pay 
https://**iapi**.iplatebnibrana.csob.cz/api/v1.7/

**Comment by jstorm31** [comment]
Díky za rychlou reakci. Zkoušel jsem i uváděné endpointy, ale předtím vracely stejnou odpověď. Zajímavé, po vašem příspěvku jsem zkoušel znova a requesty přes curl i ze serveru už fungují. Za mě je tedy aktuálně stav OK.

**Comment by mrazekl** [comment]
ty pokusy ke kterým se vracíte, byly bohužel ovlivněny updaty databáze, které probíhaly mezi 09 - 11 hodinou a v tomto období nebylo možné zaručit stabilní spojení.

**Comment by janlanger** [comment]
Potvrzuji že původní problém s nedostupností je již vyřešen. Díky.
