### ISSUE TITLE
Nefunkční ACS server simulator

### ISSUE THREAD

**Issue by kopecmi8** [csob/paymentgateway#589]
Dobrý den,
minimálně od 22.6.2021 eviduji nefunkční testovací platební bránu při pokusu zaplatit testovací kartou s 3DS ověřením. 

![image](https://user-images.githubusercontent.com/8993750/123235356-13804880-d4dc-11eb-915b-409f078e01d2.png)

K chybě dojde při návratu na platební bránu z ACS server simulatoru.

Testovací brána funguje bez problému při použití testovací karet bez 3DS ověření, kde nedochází k použití ACS simulátoru.

**Comment by Mspisar** [comment]
Dobrý den,

předávám na síťové oddělení k prověření.

s pozdravem

Spisar

**Comment by kopecmi8** [comment]
Dobrý den,
děkuji. Teď už testovací brána nefunguje ani pro karty bez 3DS...

![image](https://user-images.githubusercontent.com/8993750/123257199-26057c80-d4f2-11eb-8525-6edd3d7dee12.png)

**Comment by mrazekl** [comment]
Dobrý den,
v pátek večer byla provedena úprava na straně sítí, která by měla tento nedostatek vyřešit. 
Vyzkoušejte prosím.

**Comment by kopecmi8** [comment]
Dobrý den,
potvrzuji že došlo ke kompletnímu zprovoznění testovací brány.

Děkuji.

**Comment by kopecmi8** [comment]
30.6.2021

![image](https://user-images.githubusercontent.com/8993750/124018681-62e8dc00-d9e8-11eb-9e64-23be6a3e7bd5.png)

**Comment by mrazekl** [comment]
Dobrý den,
předchozí problém spočíval ve vysokém počtu parametru v hlavičce, max. limit byl navýšen.
Nyní sem předal na kolegy pro ověření, že se jedná o stejný důvod zamítnutí nebo nějaký jiný. na základě jejich zjištění podnikneme další kroky.

**Comment by janbrasna** [comment]
@kopecmi8 Hezky den. Vyskytuji se vam i nadale problemy s ACS simulatory ci stavy transakce, nebo po tech spolecne vyladenych pravidlech na firewallu je takto uz vse v poradku? Diky za update.

**Comment by kopecmi8** [comment]
Dobrý den,
od druhé opravy už se zdá být vše v pořádku.

Díky za opravu
