### ISSUE TITLE
Metoda pro založení plateb pro testovací účely

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#59]
Hodilo by se mít nějakou možnost, jak vytvořit platbu v určitém stavu (mluvím teď o testovacím prostředí).

Příklad:
Chci mít automatický integrační test, který testuje endpoint `payment/status`. Bohužel nemám možnost, jak si předem připravit platby a nastavit je do správných stavů, abych mohl komunikaci s endpointem plně otestovat.

1) Možnost předpřipravit si je ručně se mi moc nelíbí. Rozbije se to při první špatné manipulaci, nebo při změně merchantId.
2) Varianta použít selenium testy sice funguje, ale například při testování expirace brány musí test čekat půl hodiny.

**Comment by ondrakoupil** [comment]
+1 To by bylo užitečné.

**Comment by ratajskym** [comment]
Dobrý den, 

děkujeme za smysluplný podnět, nicméně v nejbližší době zásahy tohoto typu neplánujeme.

**Comment by fprochazka** [comment]
:+1:

**Comment by Misneit** [comment]
+1 pro vytváření takových plateb.
