### ISSUE TITLE
Extension pro masku karet nefunguje u palteb provedených 22.6.2021

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#590]
Dobrý den,

22.6.2021 jsme zaznamenali chybějící `maskClnRP` extenzi v odpovědi na `payment/status`. U aktuálních plateb je už vše v pořádku, ale postižené platby z 22.6.2021 stále extenzi neobsahují. Bylo by možné zpětně data doplnit, nebo jsou nenávratně ztracené?

Děkuji za info.

Jeden příklad:
```
"merchantId": "M1MIPS7146"
"payId": "bb06d418915b@GF"
```

**Comment by Mspisar** [comment]
Dobrý den,
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,

Omlouvám se za pozdní reakci ale dříve jsme se k tomu bohužel nedostal.
Pokud je váš požadavek stále aktuální a potřeboval by jste dodat maskovaná čísla karet k některým transakcím, tak vám je můžu dodat ale museli by jsme se domluvit spíše přes email a nějak si ověřit, že máte oprávnění tato data obdržet.

Pokud je tedy ještě potřeba tak prosím napište na email servis@monetplus.cz a odkažte se prosím na toto téma zde na Githubu (stačí odkaz nebo číslo #590) a nějak se domluvíme.

Ještě jednou se omlouvám.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@dkomarek2 On je asi @pepakriz chce dostavat na API, pro ty trx kde chybely. A ze je stale /status nevraci.

**Comment by dkomarek2** [comment]
Dobrý den,
pokud je to tak, tak jsem to špatně pochopil. Prověřím ten uvedený příklad.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by dkomarek2** [comment]
Dobrý den,
u transakce "bb06d418915b@GF" byl request payment/status provolaný naposledy 24.6. a opravdu nevrátil extension maskClnRP.
@pepakriz bylo by prosím možné provolat tento request u této transakce nyní aby jsme si ověřili funkcionalitu nyní? Jestli nebylo již nějak vyřešeno.

Děkuji

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by pepakriz** [comment]
@dkomarek2 provoláno znovu a stále tato extenze u platby `bb06d418915b@GF` není doplněna. Každopádně mám dojem, že před pár dny kolega doplňoval chybějící masku u postižených plateb z nějakého reportu, protože data už máme kompletní. Takže doplnění masky k postiženým platbám už nemusíme dále řešit. Děkuji však za reakci.

**Comment by dkomarek2** [comment]
Dobrý den,

Pokud se již u nových transakcí nevyskytuje a k těm postiženým máte již data doplněna, pak beru jako vyřešené.

Děkuji

S pozdravem,

Daniel Komárek
IT application specialist
