### ISSUE TITLE
3D Secure 2.2 data transakce

### ISSUE THREAD

**Issue by rad3kM** [csob/paymentgateway#592]
Jen dotaz, jsou již dostupné nějaké informace ohledně implementace, kdy se to bude nasazovat, jaká data o zákazníku bude muset obchodník předávat?

**Comment by Mspisar** [comment]
Dobrý den,
Váš požadavek byl zaevidován  a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,

V tuto chvíli je na platební bráně ČSOB implementovaná podpora pro 3DS 2.1.
Nemám žádné informace o tom jestli a kdy se bude implementovat verze 3DS 2.2.

Pokud vás zajímá více tak zkuste prosím kontaktovat přímo zástupce ČSOB s tímto dotazem.

Děkuji.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by rad3kM** [comment]
Část vyjádření z banky:

> Banka v průběhu Q1/2021 zveřejní novou specifikaci pro implementaci 3D Secure 2.2. V rámci implementace vyšší verze je již nutná součinnost obchodníka, kdy e- shop bude nově předávat platební bráně více informací o držiteli karty, například:
• Jméno
• E-mailová adresa
• Domácí telefonní číslo
• Číslo mobilního telefonu
• Fakturační adresa
• Dodací adresa

a

> Kompletní popis dat, která bude nově nutné předávat v rámci 3D Secure 2.2, naleznete v technické specifikaci na Githubu. O zveřejnění nové verze eAPI budete informováni e- mailem v průběhu Q1/2021.
V případě dalších dotazů se prosím obracejte na e-mailovou adresu platebnibrana@csob.cz.

**Comment by janbrasna** [comment]
@rad3kM To jsou prezite informace. Od te doby vysly dodatky 2.1 ktere meni povinnost vstupu (a 2.2 bude uplne transparentni, na pozadi se prepina podle potreby), takze sbirana data jsou pouze pro vyssi sanci autentizace bez nutnosti potvrzeni uzivatelem, ale nejsou povinna.

Nicmene ano, v dalsi verzi tato nepovinna data budou, prave pro moznost zrychlovat pruchody overenim u banky vydavatele, zkusim pohledat o jaky rozsah cca jde, a sepisu.

**Comment by janbrasna** [comment]
- [@csob/platebnibrana/wiki/Dodatečná-data-o-nákupu](https://github.com/csob/platebnibrana/wiki/Dodate%C4%8Dn%C3%A1-data-o-n%C3%A1kupu)
