### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by DIOEMAIL** [csob/paymentgateway#596]
Dobrý den návod pro implementaci do woocommerce na odkazu https://github.com/csob/paymentgateway/tree/master/WooCommerce%20Plugin je nefunkční. Je možné získat pro laika návod jak implementovat bránu do woocommerce?

**Comment by Mspisar** [comment]
Dobrý den, 

plugin jsme přestali oficiálně podporovat - nejsme autoři. Se starší verzí  @API ( do 1.7 ) můžete nastavit dle přiloženého screenu. 
**Funkčnost však již zaručit nemůžeme.**

![MIPS woocommerce](https://user-images.githubusercontent.com/14308940/128298482-fe85d357-bd83-47e2-88f7-c2d16c5f36a0.png)

s pozdravem

Milan Spisar
