### ISSUE TITLE
Platební brána vrací 400

### ISSUE THREAD

**Issue by skalahonza** [csob/paymentgateway#598]
Dobrý den,

Při používání testovací platební brány mi vše fungovalo jak mělo. S přechodem na produkční platební bránu se zaseknu hend na INIT a dostanu 400 BAD REQUEST (víc bohužel nic).

Merchant id: MIPS9346

Request:
```js
{
  "orderNo": "1101090189",
  "payOperation": "payment",
  "payMethod": "card",
  "totalAmount": 191180,
  "currency": "CZK",
  "closePayment": true,
  "returnUrl": "https://payment.services.talxis.com/check",
  "returnMethod": "GET",
  "cart": [
    {
      "name": "1101090189",
      "quantity": 1,
      "amount": 191180,
      "description": "1101090189"
    }
  ],
  "description": null,
  "merchantData": "NWE5OTQxMTItYTk5MC00N2VhLWE2M2MtNDgyMTliM2M1ZTdi",
  "customerId": null,
  "language": "CZ",
  "ttlSec": 300,
  "logoVersion": 0,
  "colorSchemeVersion": 0,
  "merchantId": "MIPS9346",
  "dttm": "20210908152751",
  "signature": "RhdhDyFjbzwdQBaDGKSrVnjahR+YRynKHQwfbHa4Z9XzhgkyQoJDc34yD4CqKy34q11j9RAWcn2j244fYCf4zNUqmiRyZjAV778Zn8tgegsTzRUFwtowK2a3mUXtf3ReAqwD5N9H2QqEqBhrRCaq3ByaLeKL7WdCiD+nE8CemLphd5C1ryaS0ag/k7lG5q/FM2xoP+uxVGQbEGtX5+TGUZCBknBNm1T6GVvdWryOKNkPGiSBHQjGr5oLz8+XXS0OwxFrs78gzk3RYDHV1IamgvSuJK36DS4H+TaJezXexbXbSGlgNlDjNSvwIzQLl8I/sZxObvjTvBqSNjqnKbM/IA=="
}
```

Můžete se prosím podívat do logů na jaké chybě to končí?

**Comment by janbrasna** [comment]
Zkuste 0 a null pole vůbec neposílat, nejspíš na nich selhává podpis. (Pokud jinak /echo funguje, tj. krypto atp. je správně a klíče aktivní.)

**Comment by skalahonza** [comment]
Zkusil jsem ECHO GET
URL:
`https://api.platebnibrana.csob.cz/api/v1.8/echo/MIPS9346/20210909084732/I2vVVIRwdy0QfAOvexQ6V8toPu7PMzuFbOd5yO2M4Dcy21DMDXydOZ5y09SjLjGdgm37Pu6ZYXHbhJdBudhViYa9YuI%2b3GHOLOr%2bvXOuPcTnk4wo3obr1ELloVXwzFDINvMZUs8SZBfJ0Q3NUxXPSoo4E5ckSD719Ve8slmDL%2fapB13V2jhixgcH0%2bmZZCuI7k6wjJ7kUNU4REGAYW6dA6v3AOMwbzrF1tOfMCB7s9hz6waaz6WjSNnX8aAyLPxiyS8EA5o1LvXgTUKY2culS98ttijPEnbj3A6TJdxoOYjPb%2fy5pg8b8fhEwwss4QaQ1edswTv7j4eck1LI3vEj0A%3d%3d`

Opět dostávám BAD REQUEST

Zkoušel jsem i vynechat null a 0
Request:
```js
{
   "orderNo":"1101090189",
   "payOperation":"payment",
   "payMethod":"card",
   "totalAmount":191180,
   "currency":"CZK",
   "closePayment":true,
   "returnUrl":"https://payment.services.talxis.com/check",
   "returnMethod":"GET",
   "cart":[
      {
         "name":"1101090189",
         "quantity":1,
         "amount":191180,
         "description":"1101090189"
      }
   ],
   "merchantData":"YTRjZGYxYmUtZGZkNS00YzRmLTkzNTYtNzA4NGQ3ZDVkMWU2",
   "language":"CZ",
   "ttlSec":300,
   "merchantId":"MIPS9346",
   "dttm":"20210909085408",
   "signature":"CZwk40whk/LHi2rRcxFj1t8QIuCGge5TQ9wc04wWWG0jEzw7O251gnVD0S1EpNKQk9hcOC2Llwr3/HdLzZgiDzrtaCL6luVqLbLnUTrl9kpTlb1zx23TTDHnzYwJcnGA4+7YGxmP7wfdissoUi+RHA3/U6+uwbt7s5R36GBAsTVEN8S8Dmn/EZl9ErQxjEC8vL/xbR/SpKVEDL+gUilZxEfNKfL+jVyKkxVQWx51t52JoAvcw1Yiwlwt2amM/Q8zCE5zwsZlPW4y/QL3Hyqazg9iQXFePh83XbgT4lNSyD23hAudUKA9SxD5SW8O1QgYg3jysbSwe1ygYfJZQOtqVQ=="
}
```

Opět BAD REQUEST

Mám trochu podezření jestli zákazník udělal vše správně co měl. Můžete mi prosím ověřit zda jsou u merchanta MIPS9346 vůebc nějaké platné klíče? Případně pak můžeme ještě porovnat SHA-1 veřejných klíčů.

**Comment by dkomarek2** [comment]
Dobrý den,

odpověděl jsem vám na váš email.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by skalahonza** [comment]
Napíšu ještě rozuzlení. Ukázalo se, že zákazník zapomněl poschvaolvat klíče v POS Merchant aplikaci.
Díky všem za pomoc.
