### ISSUE TITLE
oneclick/echo vrací resultCode 700 pro neautentizované karty

### ISSUE THREAD

**Issue by vojtechMatocha** [csob/paymentgateway#599]
Dobrý den,

narážíme na problém s oneclick/echo. Metoda nám na testovacím prostředí vrací chybu 700, přestože originální platba s uložením karty úspěšně proběhla. MerchantID = 53269606, OrigPayID = cab3dc9f1079@GI

CSOBGateway oneclick/echo -> {"dttm":"20210909111740","signature":"DfUdgRtsYKXiueBztTsnyrff2cVDb0KFfGpmoWOgAf/utq5ZALtDi99KlviQbMJ2X1iv4XMJb62yzO+FQwMLKHIyx5O9O11Kzf4pwPkcPr0InyUZc7AEIB4WHnm+kkOg5d+KkpdiSudRCiD4hZYRbPLsljqlBvx+yFtUbEQr8LD85c0Va1dwjOgtidghJrxeMWzB/f05NZjbHbPpDPrEG2TJOAGNM+2F8jVegKUPjr+qv7XhtjWYE0RAeFiNjG0eB+brRZXtAfwPjs6CKmfnCilNq3dKAEi4TEGcYrf+RxRr8gfW9oEgZj+0a5B8iSUmyWz6KaQkJQKf4EV50HHYLw==","origPayId":"cab3dc9f1079@GI","resultCode":700,"resultMessage":"Oneclick template not found"}

Zdraví

Vojtěch Matocha

**Comment by jstuchlik-mnt** [comment]
Dobrý den, 
váš požadavek byl předán k řešení odpovědnému kolegovi.
S pozdravem

--
Jan Stuchlík

IT Support Specialist

**Comment by dkomarek2** [comment]
Dobrý den,

prověřil jsem logy jak původní transakce ze které jste chtěli vytvořit OneClick template tak i vaše následné volání.

Zjistil jsem, že uložení OneClick template bylo zamítnuté z důvodu použití platební karty, která není zapojena do 3DS autentizace. To je totiž jedna z podmínek této funkcionality. A proto následné provolání oneclick/echo vrátilo odpověď "Oneclick template not found".

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by pepakriz** [comment]
@dkomarek2 Dobrý den, můžete prosím potvrdit, že i na produkci po úspěšně proběhlé platbě (přidání karty) musím zkontolovat pomocí `oneclick/echo`, jestli je daná platba použitelná pro následné oneclick platby? Nebo se to takto chová jen na sandboxu? Doposud jsem žil v domnění, že úspěšný průchod platbou (přidání karty) znamená automaticky možnost platit přes oneclick.

Děkuji

**Comment by dmarek** [comment]
Uvedená trx na ibráně (u které byl `payOperation` nastaven na `oneclickTemplate`) byla provedena kartou ***0209 (která není ani 3DS2 ani 3DS1), provedl se pokus o 3DS1 autentizaci, autentizace neproběhla, daná trx se pouze autorizovala. Vzhledem k tomu, že neproběhla 3DS1 autentizace, nebyla založena oneclick template. Ano, je potřeba provolat `oneclick/echo` pro potvrzení, že byla šablona vytvořena.

V případě, že by se jednalo o 3DS2 kartu a nebyla by úspěšně dokončena požadovaná silná autentizace, nepokračuje se dále, zobrazuje se oranžová chyba (nejde se do autorizace, nevytvoří se žádná oneclick template)

**Comment by pepakriz** [comment]
@dmarek Děkuji za vysvětlení. Doporučuju zaktualizovat/doplnit dokumentaci (https://github.com/csob/paymentgateway/wiki/Platba-na-klik#platba-na-klik-technicky), jelikož z ní jednoznačně vyplývá, že prošlá platba v `oneclickTemplate` je připravena k následnému použití. Mimochodem s neautorizovanou kartou jsem při požadavku na založení oneclick platby dostával pro mě nic neříkající resultCode=180. Zabil jsem pár hodin debugováním, než jsem objevil toto vlákno :)

**Comment by pepakriz** [comment]
@dmarek Ještě jeden problém jsem objevil. Testovací karta pro paltbu na klik (https://github.com/csob/paymentgateway/wiki/Testovac%C3%AD-karty#testovac%C3%AD-karty-pro-platbu-na-klik) vrací na `oneclick/echo` resultCode=700. Tudíž ji po vámi navrhovaných úpravách nejsem schopen "uložit" do eshopu. Nejlepší by bylo, kdyby se karta chovala, jak je uvedeno v dokumentaci - tedy že simuluje chyby typu `nedostatek prostředků`, ale v ostatních situacích se tváří, že šablona funguje.

**Comment by dmarek** [comment]
@pepakriz prověříme, nejspíš bude potřeba tuto kartu nakonfigurovat aby byla brána jako 3DS

**Comment by dmarek** [comment]
@pepakriz testovaci karta 5332290001000202 je nakonfigurovana (jde do 3DS autentizace, oneclick template se vytvori, nasledna oneclick payment se zamitne v simulatoru dle dokumentace), prosim o overeni a nasledny close. Diky.

**Comment by pepakriz** [comment]
@dmarek potvrzuji, funguje to. Zavřít issue nemůžu, protože nejsem autor, ani admin.
