### ISSUE TITLE
getting 404 "Not found" error for payment/process

### ISSUE THREAD

**Issue by krunal131987** [csob/paymentgateway#6]
Here is my url,
https://iapi.iplatebnibrana.csob.cz/api/v1/payment/process/A1050uj4XS/c2ba43215ad84ab/20150604172506/dlD1LNy73VDxI8S19Uz6+j/KZQSrI/3k2690G52rWD+19JUCl+fe5I0U7fLdXoA70pLKzpL04vT8JxDrW/zZdQlGERLPrQFhAg3Zd8yIUl87XnqgLJbEs91CrAv8eUZsf0yML54aAUR2IjVGkwzBRZPwFaKxppO+fh0lxIzRhu1HnWNrQvQfkrGSC1o46XPeILepm8/kMvfzB2fnVuDuausYywy3vLKU0NoxzI9QlW0NWpay5ucQyXpbqgEj/0ssTPBroZpJ8Ts9sFec2dBdhxvEm/zQi9qyJ0T65NP3RMKQ/KDzMSx00tpPtsXxEg0b+/MKFAXMu3UdhBP4JK/lAw==

Is there any mistake to passed data in this payment/process url?

Thank you,
Krunal

**Comment by dmarek** [comment]
signature must be url-encoded (because base64 contains "/"), see https://github.com/csob/paymentgateway/wiki/eAPI-v1-(English-version)#get--httpsapiplatebnibranacsobczapiv1paymentprocess-

**Comment by krunal131987** [comment]
now, my encoded url is
https://iapi.iplatebnibrana.csob.cz/api/v1/payment/process/A1050uj4XS/eb0a7510ef27464/20150604174720/pZ%2FcosxOHETP%2F7RfndmB%2B7xN68Y70WKvILz8aQFUSK7euLiOLc0HftXS6QGFKCXbCeNXxMTCZStDMIaKORmj10kde9Z2mZnld4PnopaeyQFwL9SLT8VktY3z2dXGU%2FZjk%2BuTo%2BuQRW26rXfwdg82gt7QuHZf5MPEN%2B%2F5JHKL4qtG6gQowJyQ3buFY8ZoTFzJVTXBAAKFztmNJ7kJ%2FdxuSr1dPGsTqvfdHkKZzmfNghDCeqKZTwww3XmLBm%2Fc8vfltOOkrl9Yi7BJglVUTMgLT7Hje%2FoZacq9%2Bgm997%2Bz2WhuRKz%2BKb%2FJ3g25NVg33MQ%2B%2FuPOM%2Bg0Gv%2FcpvnZZj0LVg%3D%3D

please, check this link i am getting this error,

We can't process your payment

The payment request contains incorrect data. We are sorry for the trouble, please return to the merchant and select different payment method.
