### ISSUE TITLE
Debugování LegacyAPI

### ISSUE THREAD

**Issue by tomasfejfar** [csob/paymentgateway#60]
Pokusil jsem klientovi zmigrovat bránu. 

* upravil jsem adresy
    * `<form enctype="application/x-www-form-urlencoded" method="post" action="https://iplatebnibrana.csob.cz/pay/entry/merchant/">`
* upravil jsem MID
    * `<input type="hidden" name="MERCHANTNUMBER" value="XXXXXXXX" id="MERCHANTNUMBER">`
* změnil jsem klíče
    * DIGEST se vygeneroval

Bohužel při platbě to nefunguje. Brána (`https://iplatebnibrana.csob.cz/pay/merchant-error.html`) vypíše:
```
Platba nemůže být provedena
Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.
```
Jak to můžu zdebugovat? Jsou někde nějaké logy? Nebo jak zjistím, co mám špatně? Původní brána posílala PRCODE a SRCODE :(

**Comment by ratajskym** [comment]
Dobrý den, 

bohužel jste nenapsal jedinou informaci, které bychom se mohli chytnout. Logy k dispozici jsou, ale samozřejmě nejsou veřejně dostupné. PRCODE a SRCODE se vrací i nadále. Vše si můžete vyzkoušet na vygenerovaném anonymním účtu, nebo můžete svůj dotaz položit na mail platebnibrana@csob.cz, doplňte ho prosím o Vaše merchant id

**Comment by tomasfejfar** [comment]
Nechtěl jsem merchantId posílat veřejně :) Máte mail.

**Comment by Miculka** [comment]
servis@monetplus.cz

**Comment by Miculka** [comment]
ono to tady zase tak veřejné není. Vidí to jen ti co to mají vidět :-)

**Comment by tomasfejfar** [comment]
Mail jsem poslal na platebnibrana@csob.cz :)

**Comment by Miculka** [comment]
třeba nám to z tama někdo pošle

**Comment by tomasfejfar** [comment]
Díky, měli jste pravdu, byl to klíč :)
