### ISSUE TITLE
Po úspěšném ECHO a INIT, vrací na PROCESS Url Rejected

### ISSUE THREAD

**Issue by honzastefan** [csob/paymentgateway#609]
Dobrý den,

můžete prosím poradit.
Po první provedené platbě proběhla s bránou komunikace kdy jsem úspěšně založil platbu příkazem INIT.
Pak jsem Zavolal PROCESS. Naběhla mě stránka, kde jsem podle návodu vyplnil kartu. Zaplatil jsem.
Brána mě přesměrovala zpátky na náš web. Neposlala ale údaje merchantData, takže u mě ve webu to skončilo s chybou.
Mapování merchantDat jsem odstranil a celý proces zopakoval.

Opět se jsem korektně dostal odpověď na ECHO a na INIT viz obrázek.
![initPayment](https://user-images.githubusercontent.com/61694066/142446807-d8600cf0-fbab-4b33-92ac-f9fb81938d90.png)

Následně jsem dal PROCESS, ale brána mi začala hlásit viz obrázek
![processError](https://user-images.githubusercontent.com/61694066/142446872-13f5ec39-350e-458e-822d-fe32bb360485.png)

PayId by mělo sedět s tím co obdržím a u požadavku PROCESS.
Nevíte prosím v čem by mohl být problém?

MerchantId, které používám je A1525CDigx

Díky

Honza Štefan

**Comment by honzastefan** [comment]
Dobrý den,

tak dnes stejný průběh.
První platba se povedla, další vrací to samé.

To vypadá že mám pouze jeden pokus na zaplacení za den.

Včera jsem použil MasterCard, dnes Visa (4125010001000208) 

Můžete na to prosím kouknout?

Díky moc

Štefan

**Comment by honzastefan** [comment]
Dobry den,
v pátek se zdálo, ze to je OK, provedl jsem vícero plateb.
Dnes jsem opět provedl provedl jednu a zdá se, že mě FW opět z nějakého důvodu zařízl.
S pozdravem
Jan Štefan

**Comment by dkomarek2** [comment]
Dobrý den,

můžete prosím poslat úplně celý request pro jeden process, který vám takto neprošel?
Nedohledal jsem je v aplikačním logu, předpokládám, že v něm bude nějaká chyba a proto to k aplikaci vůbec nedojde a zařízne se to dříve.

Děkuji 

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by honzastefan** [comment]
Ok, 

udelam nejake screenshoty. Ale nevim co bych mel mit spatne, kdyz prvni platba probehne OK (echo, init, proces, vrati se na nas web a vse probehne jak ma) a ve druhe uz me ten request kompletne odmitne.

S pozdravem
Stefan

**Comment by dkomarek2** [comment]
Dobrý den,

klidně sem vložte celý request jako text abych s tím mohl pracovat, ze screenu bych to musel ručně opisovat.

Děkuji

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by honzastefan** [comment]
Platba c.1

Echo Request

merchantId=A1525CDigx
dttm=20211130110048
signature=wIIDXc5mRZQBTCLz0B8timz40Buvo1NzHvS5arfKgKQnNVrajNTKzzEOsSNlGzurwgbs+7aYwTI9/305Mxf4ov60LLHeNed9yaL8G/mra/j8jnj+sSdpelbkO7WBBZFXM4m9tWBUd8qsdaziFtoSVtk2AIvIq+uruogKeea8JH9vC0S6bd/N8WsEAHiEQ6iNx5lTmiad68sgaWrfUZgilGtPMxyZw8cYQfBPDpqx92t+KTgwZxydB0aUWhvii4q5WSHvtLZpMU+ZbaFlq1lrifSwCMgFa/tGGRJe/rXZB+uuvZ+p0WGGVdVq0XPNYHP4S5MlHaq950JiinrXFrAkzQ==

Echo response
dttm=20211130110000
resultCode=0
resultMessage=OK
signature=ON9HNbz0TFYUCBhGXrcd8LJ5D1sOIQW7MEf1yaVEjEqUQiCs9in9Xp2m6NVGco2NuGWRGZZ2k1FFIgmR8p5na0xFGBxKo7G6gXY5RCo/IslVe74ZgMKgupVSMZJWmWvyZI9ojgjCxdGOp57MIgfhtxaLrpXbaEN0hd53/82l3W6p5WBLtwCZWYe1mRRU0rayBnarKxwiLHOPibXKLnk17FWKyhNd+TehBxVXKeY1ShQA89vFIupuymFPmaJiMjT9vEp1beD0aGEAaYPB95JZ4dWeAMxD+KUpujhymW3NN08BCG8OZVRl33Fn0QIKehrLo3ggPT6jKunvBT6q/Fb3jQ==

![image](https://user-images.githubusercontent.com/61694066/144026419-7000b1ce-4440-47e8-bd8f-1104a3939bcc.png)

**Comment by honzastefan** [comment]
InitResponse
CsobGwPaymentInitRequest(merchantId=A1525CDigx, orderNumber=69972756111, timestamp=20211130110503, payOperation=payment, payMethod=card, totalAmount=50000, currency=CZK, closePayment=true, returnUrl=http://localhost:8089/payment/csobgw/return, returnMethod=POST, cart=[CsobGwCartObject(name=pokuta, quantity=1, amount=50000, description=popis pokuty)], merchantData=null, customerId=null, language=CZ, ttlSec=null, logoVersion=null, colorSchemeVersion=null, customExpiry=null, signature=SKCcMqVnM4l71dL4ztVg0yCulTKjyyIcZOs0aAyHJWGipQa4+npYLT5tesloN7s0ciU/GgcTbbF5hcQPSZYiOHoqyQBM0p+2dnAK/+XtpJijTb8AWJ5Glkp8aNufDVg+rlmd2b0CsPsQG5SSgi82f1r+mmH8DoYdlMjq+sJWFm6rYLVo6LVYr/fgVOeZM7Ry4WBQLqlbh1+B9/x+zEy78GOM2aqSic3ZsEj+l+EIaikMYOxQrCUA5UeL4xB963bWJsQtrotCQYGUtxfHfpsy+odkfkjFP/MrvvfSlLACuLv0cwVVARjNo5gVd76Pvh1tPupCP9TMlwJTFVuRFkFsgA==)

InitRequest
CsobGwPaymentResponse(payId=5357da5434f5@GK, timestamp=20211130110415, resultCode=0, resultMessage=OK, paymentStatus=1, authCode=null, customerCode=null, statusDetail=null, signature=VlMSnVbqpatOAlM/rVH6m9GFLc+yEUQT+gYwRtz89uFyOlsFTw2Z6107WJw3rFzoC8rUXhsieVG9MSLaJexB/IRpxbg83iMiKlmsdOYad4U0cuKv7YNa50sVtsna5GTcML50yWX/s2Qa35AFywhBf4ymbnjkujPiCtLh56RIUiosfTgwM60rIT6oSDuyMaFHP2ot6EIhYbebo1yshm7dOJ0ViFDShdGI4qY2gA6hAQYKrdLGK9dlLbDkKHkEv4C6cnMlAfYN9Jz/kmcs3tFdKaOKUlH17Z13NKhN3zQGqLvJ/3jOerGb9p3FXQyVpvQRDuPaxfvfWs07RJYBKGyUPQ==)

**Comment by honzastefan** [comment]
Request URL: https://iapi.iplatebnibrana.csob.cz/api/v1.8/payment/process/A1525CDigx/5357da5434f5@GK/20211130110829/ZTj4yV%2BGVQ4EPHXswo3Zse7kzbBBWqnYf0IYL4iyUCfUIoI%2FnJaW71UOXAtFrzslObVM816E7kd%2BEspVwBl9Slpeqf3UR5MOQSrsUtVLpXH%2BPkFvBmeu%2FLEDw0k92pSbrLrFaDYh9%2BNLYJ12DvfWONBa%2BTdwTEBPfmi3NVTiaLpVQizhR%2Fqe0OrpDmoYxT2SDPdE%2BBPUfi%2Bf3f0fkXt%2BSw7hTr05bh6%2BcV19UXHnf%2B%2Bre161E7xBlan76IN6HtYkgMsr8yEHRJvRLdessTyfYD6ehjjb1uy29o%2BRA84jhKOzqiSZ%2FJS%2F7HArNKC6Cu%2Bzki5Q8c7CqC4b11A4Y25dtw%3D%3D
Request Method: GET
Status Code: 303 See Other
Remote Address: 193.245.38.104:443
Referrer Policy: strict-origin-when-cross-origin

Request URL: https://iplatebnibrana.csob.cz/pay/shop.example.com/5d1d1d23-b772-4316-aa58-2895081aafc7/
Request Method: GET
Status Code: 200 OK
Remote Address: 193.245.38.104:443
Referrer Policy: strict-origin-when-cross-origin

**Comment by honzastefan** [comment]
![image](https://user-images.githubusercontent.com/61694066/144028243-d3e82c77-59b2-4892-8885-816bc258d54f.png)

**Comment by honzastefan** [comment]
Pak to presmeruje. A hotovo

Ted jsem udelal druhou platbu, init a echo prosel.
A oproti prvnimu pripadu me neprisel Redirect(303)

Request URL: https://iapi.iplatebnibrana.csob.cz/api/v1.8/payment/process/A1525CDigx/5a8aa609337b@GK/20211130111917/eVk0cnQK%2BX4sN4tlRJJHn7ktGibpcjLCgvDR1nSQ%2BtyBdyqFVvLhCgFM5sHvlJ7xQ2fjEsIq%2FSmGJStsfzKBoWH%2BL2kjzFkLAgSLRgYt70R3YWahryQQDu5m4%2FRfYCsrGmTK9iqPMrWQ4N5WenkFrQ%2BB%2B97T1aXCxuZ7JpEHMOYB9rlFYq42dK0OzJLGlYcyIAM15TYk%2B9Rrv76AYuGdzs2ipuvn6HPAkw%2FE2yj5Uotlxysahamz16H80CPwnUC6T7nmFx%2FGY677gu7OCa8t0R11GHTZ0Dt%2F3JnSvTUs3ywEq%2FxhC3%2BD0E%2BMc6zJZfQg7RtTftECYN7a1g6tuwg9pw%3D%3D
Request Method: GET
Status Code: 200 OK
Remote Address: 193.245.38.104:443
Referrer Policy: strict-origin-when-cross-origin
Cache-Control: no-cache
Connection: close
Content-Length: 246
Content-Type: text/html; charset=utf-8
P3P: CP="{}"
Pragma: no-cache
Set-Cookie: TS72564661027=08fdf8696aab20009f98cc4127fdb845e7dcacfdcc3e0eef6cafa91a7a636806e4a9defb116d769408a924ec4711300071f54590fb30889679849706e74fcca86c3ba8a2385269f1299f3ecf87d50395cf8653a2ee8eda1102a5cb1f317679e4;Path=/

**Comment by dkomarek2** [comment]
Dobrý den,
tato transakce evidentně v pořádku prošla.

Můžete mi prosím poslat request pro payment/process z případu, kdy vám to neprošlo a skončil jste na té chybové obrazovce?
V tom co jste poslal je vše v pořádku, nebo se pletu?

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by honzastefan** [comment]
Potrebujete jeste neco nebo to takto zatim staci?
Ale evidentne je problem v tom ze na process neprijde 303.

**Comment by janbrasna** [comment]
@dkomarek2 Protoze ten response je `200 OK` `text/html` coz bude zase firewall incident F5/bigip viz #605

**Comment by honzastefan** [comment]
Minuly tyden, to celkem fungovalo. Dnes jsem testoval Reverzovani plateb. Skoncilo mi to s chybou a FW me opet asi zarizl a uz zase nevraci (303), ale rovnou (200). Diky

S pozdravem

Stefan

**Comment by honzastefan** [comment]
Mam takove tuseni, ze blokovani FW nastane ve chvili kdyz se neencoduje podpis a v podpisu zustanou lomitka.
Chybu jsem objevil v knihovnach FeignClienta, ten bohuzel vsechna lomitka v url opet dekoduje. 

[(https://github.com/OpenFeign/feign/issues/1190)]

Takze s pokud se pouziva SpringMvcContract tak s tim nejde udelat vubec nic.

**Comment by honzastefan** [comment]
Tak vyreseno.

![image](https://user-images.githubusercontent.com/61694066/145831639-9974106b-75c4-44b1-ab71-e5b934d52e56.png)

Tato stranka nabehne pokud platbu delam s otevrenym DevTools v Chrome.

Pokud jsou DevTools zavrene. Tak vse funguje v poradku.

Muzete toto issue zavrit.

Diky
