### ISSUE TITLE
mastercard karta 5168440001000202

### ISSUE THREAD

**Issue by petrpruner** [csob/paymentgateway#61]
Dobrý den,

zkouším v implementačním stádiu odeslat platbu s těmito údaji:

5168440001000202
12/16
100

**očkávaný výsledek**: Simulace úspěšné autentizace uživatele
**reálný výsledek**: Vaše platba byla zamítnuta z důvodu blokace karty. Použijte prosím jinou kartu, nebo se vraťte na <jmeno obchodu> a vyberte jinou platební metodu.

Můžete toto prosím ověřit na vaší straně?

**Comment by Miculka** [comment]
Dobry den. Poprosim vás o merchant ID  na tom základě muzu vás problém řešit. Dekuji

**Comment by petrpruner** [comment]
M1MIPS0125

**Comment by Miculka** [comment]
v logu vidím, že transakce probíhají, použita karta Visa. Jak jste tedy na tom?

**Comment by petrpruner** [comment]
Myslel jsem tuto konkrétní testovací kartu, je to karta mastercard, ostatní testovací karty fungovaly správně dle očekávání a dle dokumentace, ale tato karta má vrátit úspěšnou transakci a nevrací

**Comment by Miculka** [comment]
Mohl by jste vyzkouset provest transakci kartou Master jeste jednou? 

Kde se nyní nacházíte? Vidím , že jste již požádal o klíče do produkce a čeká se na POSMerchant na schvaleni jednorazovym kodem.

**Comment by petrpruner** [comment]
teď jsem zkoušel, stále nefunguje, dostávám stejnou chybu, viz první post, měl byste mít v logu

**Comment by ratajskym** [comment]
Dobrý den, pro tento test byl špatně nastaven simulátor. Vyzkoušejte

**Comment by petrpruner** [comment]
Funguje, díky za rychlou reakci
