### ISSUE TITLE
Problem s platbou - ID neexistujici na CSOB brane, ID duplicitni na eshop strane

### ISSUE THREAD

**Issue by kvaseczech** [csob/paymentgateway#610]
zacal se nam objevovat problem pri platbe kartou z eshopu kvaseczech.cz na platforme fastcentrik. Dle aktualniho stavu je problem s platbou v tom, ze jiz takovy zaznam na platebni brane existuje.
Zadne zmeny nastaveni jsme nedelali, nedelal jsem ani storno, ani refundaci platby.

Priklady problematickych plateb
VS 842
VS 774
VS 667
VS 699
VS 733

Popis problemu:
- platby bezne funguji spravne
- nektere platby neprobehnou, zacina byt takovych plateb vic.
- zakaznik zada platbu kartou a okamzite dostane chybovou hlasku na eshopu, na platebni branu se ani nedostane
"Během zpracování požadavku pro platební bránu ČSOB došlo k chybě. Kontaktujte nás prosím."
- kdyz hledam platbu na platebni brane, tak tam nenajdu zadny zaznam
- kontantoval jsem fastcentrik a zde je vysledek
There was an error preparing data for payment form of system 'csob'. Errors: Invalid paymentInit request: authorized trx for merchantId M1MIPS7600 and orderNo 842 already exists. Data: Gaia.Frontend.Payments.Components.PaymentSystemFormViewComponent+Model
`[redacted]`

**Comment by dkomarek2** [comment]
Dobrý den,

pro merchantId M1MIPS7600 vidím v systému nastavenou kontrolu na duplicitu VS a proto to nedovolí vytvořit další transakci se stejným VS.
V databázi jsem dohledal, že tyto transakce již historicky existují:
![image](https://user-images.githubusercontent.com/67467762/144383029-49475ac9-d34c-40a3-9a4a-6ce5bbeb7e85.png)
![image](https://user-images.githubusercontent.com/67467762/144383056-421ed444-0c3c-44a1-b9fd-aed7bbeaf6fc.png)

Tedy můžete využít jinou číselnou řadu pro VS tak aby se čísla neopakovala nebo si musíte někde držet informaci o již použitých VS. Nebo pokud nechcete kontrolu duplicity používat, tak kontaktujte banku aby vám tuto funkci deaktivovala.

S pozdravem,


Daniel Komárek
IT application specialist
