### ISSUE TITLE
Error 400 only at development

### ISSUE THREAD

**Issue by 0yik** [csob/paymentgateway#613]
> merchantId = M1MIPS8365'

Try POST https://iapi.iplatebnibrana.csob.cz/api/v1.8/payment/init

{'merchantId': 'M1MIPS8365', 'orderNo': '15584', 'dttm': '20211213113810', 'payOperation': 'payment', 'payMethod': 'card', 'totalAmount': 63400, 'currency': 'CZK', 'closePayment': 'true', 'returnUrl': 'https://eshoptestweb.mattoni1873.cz/payment/csob/response', 'returnMethod': 'GET', 'cart': [{'name': 'eshop.mattoni.1873cz', 'quantity': 1, 'amount': 63400}], 'language': 'CZ', 'customerId': '3', 'merchantData': 'eyIwIjogMTU1ODQsICIxIjogMTU1ODQsICIyIjogMSwgIjMiOiBbMjczNiwgMjczMiwgMjczMywgMjczNF0sICI0IjogMjczNn0=', 'signature': 'GHPAUe+xRfqdCmnv1F4iVFIEQkN+JlEwvQvVE35WFjneAKi9Q4UVPBSQvA0arFe25yeodlSJ4Z1rAD54Ximg1PZ/qnnhoVlPUyT3XjHsgtZu2N3OPZqCT/X5wIp89bApE2jZ+FKtxvmadybWXYXfEq4EVopgX8m50YdfjNxxRhZafP4Yi26nkChaa84u8Ln9OCzLqtSqeNzlQA03yl+xLNMquURh0E8AiuYNGR842zyjDUp1djbaFVMt4XveXshuZLAyVSZxL7TjpR6v+pXnqQ4ZtaCdgSVAZidwTv7FPZcGv/c06jVufa/Anfd9684edjq33wz1vi1jegW2C4w0rA=='}

Then i get error response
400 Client Error: Bad Request for url: https://iapi.iplatebnibrana.csob.cz/api/v1.8/payment/init

But no problem at production (URL https://api.platebnibrana.csob.cz/api/v1.8/payment/init)

**Comment by jstuchlik-mnt** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Jan Stuchlík
IT Support Specialist

**Comment by dkomarek2** [comment]
Hello,

I replied to your colleague Lukas Halda's email.

Best regards,

Daniel Komárek
IT application specialist
