### ISSUE TITLE
Nevyhodnocení testu autorizované platby

### ISSUE THREAD

**Issue by honzastefan** [csob/paymentgateway#614]
Dobry den,

chci se zeptat jestli byste mi nedokazali poradit co delam spatne. Pokousim se zazadat o prechod do ostreho prostredi z testovaciho.
Vas system mi hlasi, ze mi zbyva udelat posledni test. Problem je ze vzdy kdyz ho provedu, tak nasledujici den se opet hlasi jako neprovedeny. Priznam se, ze uplne nevim jestli to má reálne vliv na prechod do ostreho rezimu.

Takto to vypada pred provedenim posledniho testu

![image](https://user-images.githubusercontent.com/61694066/146344489-2aca74a3-3811-45c5-9c0d-37d196fc8dd0.png)

Po zaplaceni kartou stranka vypada takto

![image](https://user-images.githubusercontent.com/61694066/146345210-17445953-c5ce-4934-9ae8-6b21e2a1b262.png)

Muj dotaz tedy zni, jestli kdyz pak kliknu na odeslani pozadavku, jestli se pozadavek skutecne odesle a proc nasledujici den se hlási test jako opet neprovedeny.

Pokud to nema vliv a je to jedno, jen informace co ukazuje POS je pak trochu zavadejici.

Diky za info

S pozdravem

jan Stefan

**Comment by jstuchlik-mnt** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Jan Stuchlík
IT Support Specialist

**Comment by dkomarek2** [comment]
Dobrý den,

transakce ve stavu "Autorizace potvrzena / Posláno k zaúčtování" v tomto stavu zůstane do cca půlnoci a poté se automaticky posílá do zúčtování a poté dostane stav "Zaúčtováno".
To je korektní chování a nemělo by vás to nijak omezovat nebo vám to v něčem bránit.
Vy odešlete požadavek na schválení ve chvíli, kdy je to stále v požadovaném stavu (tedy v den vytvoření a dříve než o půlnoci).

Dále je to na bance zda vám schválí.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by honzastefan** [comment]
OK diky
