### ISSUE TITLE
MallPay - příliš krátké pole pro dič

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#615]
Dobrý den,

cituji z dokumentace https://github.com/csob/paymentgateway/wiki/Metody-pro-Mall-Pay#datov%C3%A1-struktura-customer-%C3%9Adaje-o-z%C3%A1kazn%C3%ADkovi <html>
<body>

vatin | String | DIČ zákazníka, max. délka 10 znaků
-- | -- | --

</body>
</html>

DIČ podnikající fyzické osoby je ve formátu CZ+rodné číslo, které samo o sobě má 10 znaků, tedy dohromady 12. Je možné rozsah opravit?

**Comment by dkomarek2** [comment]
Dobrý den,

zjišťuji možnosti a informace.
Až něco zjistím, tak napíšu.

Děkuji.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@janlanger Diky, to je samozrejme spatne — je to planovane s pristi verzi, jen co se overi ze to projde i upstream api aj.
