### ISSUE TITLE
MallPay na ibráně - nedochází k zaúčtování

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#616]
Dobrý den, potřebovali bychom na **ibráně** otestovat na částečné vratky u MallPay. Bohužel ani po několika dnech nejsou naše testovací platby ve stavu 8 - zaúčtováno a request na refund tak vrací chybu. U platebních karet přechází transakce do stavu 8 druhý den, je možné s tím něco udělat u MP?

Jde o bránu M1E3CB0860

**Comment by horakmichal91** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Bc. Michal Horák
IT Support Specialist

**Comment by dkomarek2** [comment]
Dobrý den,
našel jsem konfigurační problém, který jsem dnes opravil.
Po půlnoci by se měly všechny MallPay transakce ve stavu 7 přesunout do stavu 8.
Zítra zkontroluji výsledek.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by dkomarek2** [comment]
Dobrý den,

bohužel jsme zjistili, že na integračním prostředí není funkční systém zajišťující přesun MallPay transakcí ze State 7 do State 8.
Byl zadán podnět na vyřešení problému na vývojové oddělení.

Pokud potřebujete tedy nějakou transakci dostat do stavu 8 aby jste zkusil refund, tak mi prosím napište o jakou transakci by se jednalo a já vám ji přesunu manuálně.

Omlouváme se za vzniklé potíže.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janlanger** [comment]
@dkomarek2 Dobrý den, prosím `2e6e88e2fa44@GL`, `9970753a9e50@GL`, `44ca97dc4c7f@GL`, `b54603096ca0@GL`, `31b48e972b5e@GL` ať máme víc pokusů

**Comment by dkomarek2** [comment]
Dobrý den,

provedl jsem update stavu transakcí, které jste uvedl.
Zkuste tedy prosím refund nyní.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janlanger** [comment]
@dkomarek2 Prosím ještě `caed2452e358@HA` a `9408c9a67daf@HA`. Museli jsme ještě u nás nějaké věci  upravit...

**Comment by dkomarek2** [comment]
Dobrý den,

hotovo, zkuste nyní.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by janbrasna** [comment]
@dkomarek2 Pls jaky je obecne stav opravy zauctovani mallpay na ibrane? Vime kdy to bude funkcni a nebude potreba testovat integraci rucnimi zasahy?

**Comment by dkomarek2** [comment]
@janbrasna verze s opravou by měla být už nasazena ale chybělo konfigurační nastavení. To jsem nyní nastavil, takže po půlnoci by se měly všechny transakce ve state 7 narovnat do state 8.
Zítra zkontroluju výsledek.

**Comment by janbrasna** [comment]
@dkomarek2 Diky moc.
@janlanger Pak si pls zkuste otestovat integraci a pokud to takto bude dostacujici, tak si prosim zavrete; diky.
