### ISSUE TITLE
Chybějící Extensions v parametrech při návratu z brány

### ISSUE THREAD

**Issue by lubomirpokorny** [csob/paymentgateway#617]
Dobrý den,

lze docílit toho, aby byly hodnoty jednotlivých rozšíření zasílány i v parametru POST požadavku při návratu zákazníka z brány zpět na WEB?

Jde mi konkrétně o [zamaskovaná čísla karet](https://github.com/csob/paymentgateway/wiki/API-extension-detail-karty-pro-platbu-na-klik#funk%C4%8Dnost-extension-v-eapi-16-a-vy%C5%A1%C5%A1%C3%ADm). 

Při volání endpointu `/status` vše funguje dle očekávání.

Děkuji za odpověď.
Pokorný

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším postupu budete informován odpovědným kolegou.

s pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by dkomarek2** [comment]
Dobrý den,

to bohužel nelze, ty hodnoty se můžou vracet jen v tom response na payment/status.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by lubomirpokorny** [comment]
To je velka skoda, pravdepodobne to nepasuje do workflow vetsiny shopu.

Lze se alespon spolehnout na to, ze pri okamzitem provolani status
endpointu po navratu zakaznika dostaneme spravna data o rozsirenich?

Dekuji,
Pokorny

Dne pá 14. 1. 2022 13:21 uživatel dkomarek2 ***@***.***>
napsal:

**Comment by dkomarek2** [comment]
Dobrý den,

obsah extension se v response na payment/status začíná vracet od okamžiku úspěšné autorizace.
Obsah se zjišťuje a plní online, tedy daty, které jsou v danou chvíli v našem systému.
Tedy pokud provoláte payment/status po úspěšné autorizaci, tak se vám vrátí data pro extension, která máte aktivní.

Kdyby jste měl problémy s touto funkcionalitou, tak prosím napište na servis@monetplus.cz a uveďte konkrétní případ s popisem situace.

Děkuji.

S pozdravem,

Daniel Komárek
IT application specialist
