### ISSUE TITLE
Synottip.cz - Nelze přidat kartu České Spořitelny

### ISSUE THREAD

**Issue by hradsky-easit** [csob/paymentgateway#618]
Dobrý den,

zákazník nám reklamoval problém kdy nelze přidat kartu od České Spořitelny. 

![obrazek](https://user-images.githubusercontent.com/99178778/152770628-914b3be2-453d-46b3-a8d3-a9057f8abd7c.png)

Zkoušeli jsme situaci nasimulovat s jinou kartou od ČS a chyba se opakuje - 2022-02-07 10:01
Vypadá to že problém mají nově vydané karty, tj. od začátku roku 2022.
Karty od jiných společnosti jdou přidat bez problému.

Prosím o prověření.

Díky
Ondřej

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším postupu budete informován odpovědným kolegou. 

prosím doplňte prvních 6 čísel z Vámi uvedené karty. 

s pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by hradsky-easit** [comment]
Dobrý den,

např. číslo 451161, ta je vydaná 11/19.

Předem díky
Ondřej

**Comment by hradsky-easit** [comment]
Dobrý den,

máte nějaký update k téhle záležitosti?

Předem díky za Vaši odpověď.
Ondřej

**Comment by dkomarek2** [comment]
Dobrý den,

aktuálně řeším situaci s kolegy z vývojového oddělení.
Tento BIN by se měl dle mích aktuálních informací akceptovat.
Až budu vědět více tak vám napíšu.

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by hradsky-easit** [comment]
Dobrý den,

máte nějaké nové informace?

Předem díky
Ondřej

**Comment by dkomarek2** [comment]
Dobrý den,

bohužel na opravě stále pracujeme.
Až budu mít nějaké nové informace, budeme vás informovat.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by dkomarek2** [comment]
Dobrý den,

dnes ráno byla nasazena oprava, která by měla tento problém vyřešit.

Můžete prosím potvrdit funkčnost?

Děkuji.

S pozdravem,

Daniel Komárek
IT application specialist
