### ISSUE TITLE
Problém platby na integračním prostředí

### ISSUE THREAD

**Issue by kjanek73** [csob/paymentgateway#62]
Dobrý den, 
máme momentálně problém s platbou na testovacím (integračním) prostředí. Po ověření karty v 3D (simulovaném) se vrátí na bránu s chybou "Omlouváme se za nepříjemnosti, platbu se z technických důvodů na naší straně nepodařilo zpracovat. Platbu můžete zkusit znovu." Jsme MerchantID M1E3CB0094.
Možná to souvisí s tím, že nám dnes končí podepisovací certifikát, který jsme si přes Vaše rozhraní generovali před měsícem. Jak se dá tento certifikát prodloužit?

Děkuji

Karel Janěk

**Comment by Miculka** [comment]
Dobrý den přeji.. 

Vidím, že máte všechny podmínky pro test splněny, můžete tedy přistoupit k produkci. 

![image](https://cloud.githubusercontent.com/assets/14308839/10635561/f01d9edc-77f9-11e5-8c7c-4363410100b5.png)

**Comment by ratajskym** [comment]
V tuto chvíli provádíme upgrade simulátoru. Proto jsou všechny transakce zamítnuté. Budu Vás informovat o ukončení

**Comment by kjanek73** [comment]
Děkuji za odpověď, 

nicméně jste mne trochu vystrašili s tím přechodem do produkce. O tom nerozhodujeme my (implementátoři), ale zákazník, pro kterého celé řešení připravujeme. Takže o přechodu do produkce zatím neuvažujeme (předpokládám, že to znamená přejít na ostrou bránu a spuštění ostrého provozu a na to nejsme zatím připraveni). Předpokládám, že i po přechodu do produkce budeme v rámci vývoje a našeho testování stále přistupovat k integračnímu rozhraní a tím pádem expirace certifikátu i nadále zůstává v mých očích problémem. Je možné, že jsem princip testování po přechodu do produkce nepochopil, tak mne případně opravte.

Děkuji

Karel Janěk

**Comment by Miculka** [comment]
Kdy přejdete do produkce je samozřejmě na vás. Jen jsem informoval, že máte proto splněny všechny náležitosti.

Vygenerujte si nové testovací certifikáty pro dané ID https://iplatebnibrana.csob.cz/keygen/ znova a proveďte ty samé kroky jako předtím. Takto můžete vždy testovat.

**Comment by kjanek73** [comment]
Děkuji za info a uzavírám.
