### ISSUE TITLE
Doba uchování platby v systému

### ISSUE THREAD

**Issue by daliborhonza** [csob/paymentgateway#620]
Dobrý den,

prosím jak dlouho systém uchovává informace o platbě a jejím stavu? 
Zdá se, že informace o platbě jsou dostupné cca 1 rok přes volání "payment/status" a následně systém vrací NULL a kód 140.
Je možné, že se tato doba uchování v poslední době změnila?

jaký je maximálně počet dní, po který lze zavolat pro platbu požadavek na "vrácení platby"? (tedy převod ze stavu 8 na 10)

Děkuji

**Comment by horakmichal91** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Bc. Michal Horák
IT Support Specialist

**Comment by dkomarek2** [comment]
Dobrý den,

transakce uchováváme v našem systému 13 měsíců.
Po tuto dobu můžete na transakci posílat request payment/status a dostanete regulérní odpověď.
Po stejnou dobu můžete transakce refundovat (state 10).
Po této době již nikoli.

Pokud máte nějakou transakci, která by měla jít refundovat ale nelze tak prosím o její identifikaci (č. objednávky, mechant_id, VS atp.) a prověříme stav.

Děkuji

S pozdravem,


Daniel Komárek
IT application specialist

**Comment by dkomarek2** [comment]
Dobrý den,

doba 13 měsíců je standardem již delší dobu a nevím o tom, že by se to měnilo.
Leda by měl některý obchodník nějakou speciální domluvu s bankou.
Pokud máte nějaký konkrétní problém tak mě můžete kontaktovat na email dkomarek@monetplus.cz

Děkuji.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by jgrmelova** [comment]
Dobrý den, 

na požadavek neevidujeme žádné doplňující dotazy. Tento požadavek tedy uzavírám. 

V případě potřeby je možné vytvořit požadavek nový nebo tento požadavek znovu otevřít.

--
Jana Grmelová
