### ISSUE TITLE
Invalid signature novo vygenerovaných certifikátov Sandbox 

### ISSUE THREAD

**Issue by Vertisko** [csob/paymentgateway#621]
Dobrý deň,

po vygenerovaní nového páru kľúčov na adrese https://iplatebnibrana.csob.cz/keygen pre Sandbox development a následnom nahratí public kľúča na bránu dostávam z funkcie openssl_verify návratový kód 0. To znamená incorrect signature. Referencia https://www.php.net/manual/en/function.openssl-verify.php 

Fragment používaného kódu:

```
$message = $signatureDataFormatter->formatDataForSignature($data);

$publicKey = (string) file_get_contents($this->bankPublicKeyFile);
$publicKeyId = openssl_pkey_get_public($publicKey);
if ($publicKeyId === false) {
	throw new PublicKeyFileException($this->bankPublicKeyFile);
}

$signature = base64_decode($signature, true);
if ($signature === false) {
	throw new VerificationFailedException($data, 'Unable to decode signature.');
}

$verifyResult = openssl_verify($message, $signature, $publicKeyId, self::HASH_METHOD);
```

Pri použití starších certifikátov iného projektu pre rovnaké prostredie sa s chybou nestýkam a preto by v setupe nemal byť problém. 

Používaná knižnica tretej strany: https://github.com/slevomat/csob-gateway
API URL kam smerujú requesty: https://iapi.iplatebnibrana.csob.cz/api/v1.8
MerchantID: A2120uYdLR

Prosím o preverenie a prípadné nasmerovanie.

**Comment by mjanek** [comment]
Dobrý den,
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
Miroslav Janek

**Comment by dkomarek2** [comment]
Dobrý den,

předpokládám, že jste si vytvořil nové Anonymní merchant_ID "A2120uYdLR" a následně integroval k sobě klíče.
U anonymního ID nemusíte odesílat klíče do banky, to se děje automaticky. 
Mimochodem toto ID má životnost cca 1 měsíc.

Jinak pro toto ID vidím v logu komunikaci, takže váš privátní klíč máte v pořádku.
Pokud máte problém s dešifrováním response z brány, tak jste si možná integroval váš veřejný klíč místo veřejného klíče brány (někdy se stává), tedy správná klíč banky je ze: https://github.com/csob/paymentgateway/blob/master/keys/mips_iplatebnibrana.csob.cz.pub

Případně mi prosím napište jaký přesný request vám neprochází (od vás na bránu a nebo z brány odpověď k vám?) a prosím konkrétní příklad s přesným datem a časem pokusu a zkontroluju to v logu.

Děkuji.


S pozdravem,


Daniel Komárek
IT application specialist

**Comment by Vertisko** [comment]
Dobrý deň,

v prvom rade ďakujem za rýchlu a rozsiahlu reakciu. 

Chyba bola na mojej strane, že som v tomto prípade používal svoj public key, namiesto toho od banky. Prehliadol som to.

Topic teda uzatváram, nakoľko už dokážem správne vystavovať presmerovanie na bránu.
