### ISSUE TITLE
Návod na Přechod do produkčního prostředí obsahuje neplatné karty

### ISSUE THREAD

**Issue by kasparkova-arion** [csob/paymentgateway#624]
Dobrý den, 
v návodu: https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD jsou v krocích Úspěšně autorizovaná platba a Reverzovaná platba karty, které nepustí platební brána viz vaše tabulka karet: https://github.com/csob/paymentgateway/wiki/Testovac%C3%AD-karty

**Comment by horakmichal91** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Bc. Michal Horák
IT Support Specialis

**Comment by dkomarek2** [comment]
Dobrý den,

máte pravdu, nechám to opravit.
Děkujeme za upozornění.

S pozdravem,

Daniel Komárek
IT application specialist

**Comment by dkomarek2** [comment]
Dobrý den,

čísla karet jsme vyměnili za jiné, které již projdou.

S pozdravem,

Daniel Komárek
IT application specialist
