### ISSUE TITLE
Ukončení integrace platební brány v PosMerchantu ČSOB - plugin Toret

### ISSUE THREAD

**Issue by MartyAtlet** [csob/paymentgateway#626]
Dobrý den, potřeboval bych poradit s ukončením procesu integreace a aktivováním platební brány. 
Podařilo se mi nainstalovat Plugin od firmy Toret.cz 
Odkaz na plugin zde: https://toret.cz/produkt/csob/
Plugin nastavit a vložit ID a privátní klíč. 
Potom jsem se pustil do testovaní dle návodu zde: https://github.com/csob/paymentgateway/wiki/P%C5%99echod-do-produk%C4%8Dn%C3%ADho-prost%C5%99ed%C3%AD
Povedla se mi úspěšně provést zrušená i autorizovaná platba pomocí testovací kreditní karty zmíněné v návodu výše. 
V posmerchantu, ale platby nevidím - spíše je nemohu najít. 
Může mi prosím někdo poradit jak bránu od ČSOB v PostMerchantu aktivovat a uvést do běžného provozu. 
Děkuji

**Comment by horakmichal91** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Bc. Michal Horák
IT Support Specialist

**Comment by MartyAtlet** [comment]
Dobrý den, 
děkuji 
Podle vydavatele Pluginu byly potřebné platby potvrzeny v testovacím prostředí PostMerchant. 
V tuto chvíli vyčkávám na rekaci banky, která by měla zaslat email s dalším postupem a aktivovat platební bránu. 
S úctou 
Martin

**Comment by MartyAtlet** [comment]
Dobrý den, již vše funguje. Děkuji 
Jen bych doporučoval přidat do návodu obsluhu aplikace PostMerchant s tím jsem bojoval nejvíce. 
Děkuji 
S úctou Martin

**Comment by jstuchlik-mnt** [comment]
Dobrý den,

návod na obsluhu PosMerchant je přímo ve webové aplikaci v sekci nápověda je k dispozici PDF.

S pozdravem

--
Jan Stuchlík
IT Support Specialist
