### ISSUE TITLE
Nevrácení klienti zpět do eshopu

### ISSUE THREAD

**Issue by zalibaba** [csob/paymentgateway#628]
V poslední době se nám množí případy že platební brána po úspěšné autorizaci nevrátí klienta zpět do eshopu na cílovou adresu, byly v tomto ohledu nějaké změny, dříve se nám to nestávalo v takovéto míře jako nyní (výrazný nárůst), používáme verzi 1.8 k nárůstu začalo docházet cca v posledním týdnu (10.6.2022)

s pozdravem Knieradl

**Comment by pklucka** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Ing. Petr Klučka
IT Support Specialist

**Comment by zalibaba** [comment]
Dobrý den,

posílám požadovaná ID

M1MIPS1320
M1MIPS1321
S pozdravem Knieradl

**Comment by zalibaba** [comment]
Klienti nám začali psát že je to vrací na stránku s informací:
po potvrzení platby byl z platební brány přesměrován na stránku, na které bylo oznámení, že přesměrování do eshopu se nezdařilo.

Knieradl

**Comment by jgrmelova** [comment]
Dobrý den,

děkuji za informaci. U zaslaných platebních bran jsem prověřila transakce od 10.06.2022. Na první pohled však nevidím, že by docházelo k velkému nárustu zamítnutých transakcí. Je tedy možné, že transakce byla úspěšně dokončena i když nedošlo k přesměrování zpět na e-shop. Je tedy pro mne těžké tyto transakce identifikovat. 

Nemáte, prosím, k dispozici, číslo objednávky, u které máte potvrzeno, že k uvedené situaci došlo? Moc by mi to pomohlo při prověření. 

Děkuji

---
Jana Grmelová
IT administrátor

**Comment by zalibaba** [comment]
Dobrý den,

posílám vzorek ze včerejška klient zaplatil platba prošla, ale nebyl přesměrován zpět do eshopu na místo toho se mu zobrazila stránka že se přesměrování nezdařilo, 
tyto informace máme proto že tento klient se nám ozval a popsal co se stalo, platbu jsme mu vrátili a on si objednal znovu, detail transakce viz níže

Objednávka: ***@***.***
VS: 122061614




s pozdravem Knieradl

**Comment by jgrmelova** [comment]
Dobrý den, 

zaslanou transakci jsem prověřila, dle logů vypadá transakce v pořádku (viz níže). Jediné čeho jsem si všimla, tak po zaslání požadavku na přesměrování došlo k znovunačtení prohlížeče, to mohlo možná způsobit, že přesměrování nebylo úspěšné. Je možné, že prohlížeč nebo e-shop následně informuje, že přesměrování do e-shopu se nezdařilo. (Platební brána tuto informaci neobsahuje - nevrací.)

Jedná se však pouze o mou domněnku, kterou se mi, bohužel, nepodařilo potvrdit. Situaci jsem si zkoušela navodit na našem prostředí v prohlížeči Firefox, Chrome, Edge a i v případě, že jsem prohlížeč obnovila, tak se platba dokončila v pořádku a došlo k přesměrování zpět do našeho e-shopu. 

Doporučila bych obrátit se na vývojáře e-shopu se žádostí, aby zkusili tuto situaci navodit, aby při přesměrování na e-shop zkusili prohlížeč obnovit, zda se nezobrazí stránka, že se přesměrování nezdařilo.  V tomto konkrétním případě se jednalo o prohlížeč Edge. 

V případě potřeby jsem Vám k dispozici. 

---  

Logy:

Jun 16, 2022 @ 13:36:34.603    decoded CRes: {"acsTransID":"8c9528d0-ed68-41ec-8c10-c2574ae832bc","transStatus":"Y","threeDSServerTransID":"c409417d-456a-4129-bc35-4f9ac3c2fe8e","messageType":"CRes","messageVersion":"2.1.0"}

Jun 16, 2022 @ 13:36:38.611    completeThreedsChallengeOnBackground for M1MIPS1320 / cdb2e4844d07@HF started

Jun 16, 2022 @ 13:36:38.646    REQ: SmSwFARE {#01(ID)[^0x00078472=492658] ,#02(OPERATION)[EPAY] ,#03(TERM_ID)[M1MIPS1320] ,#05(AMOUNT)[^0x0001F9DC=129500] ,#06(VS)[122061614] ,#09(CURRENCY)[203] ,#10(NETWORK_CODE)[CSOB_CZ] ,#11(TRN_UUID)[061b3a45-85a7-4397-8814-2fbcc9936979] ,#17(BRAND)[VS] ,#18(TRN_DTTM)[2022-06-16T13:34:57.591] ,#30(PAY_ID)[cdb2e4844d07@HF] ,#32(PAN)[****1445] ,#33(EXPIRE)[****] ,#34(CVC)[***] ,#36(CAVV)[AAcBBQMDSAAAAfncIDFndFkWRUk=] ,#37(ECI_CODE)[05] ,#3E(DEPOSIT_FLAG)[^0x01=1] ,#3F(TRN_ATTEMPT)[^0x0001=1] ,#40(IP_ADDRESS)[77.242.90.136] ,#42(PROGRAM_PROTOKOL)[^0x0002=2] ,#43(ECOM_TYPE)[S] ,#47(APPLE_PAY_FLAG)[^0x00=0] ,#4B(DS_TRN_ID)[10fccf66-464e-4477-a4f7-ab4263433f7a] }

Jun 16, 2022 @ 13:36:38.648    completeThreedsChallengeOnBackground for M1MIPS1320 / cdb2e4844d07@HF finished

Jun 16, 2022 @ 13:36:38.994    receiving M1MIPS1320:cdb2e4844d07@HF:1 ProcResult[{*}status=OK,message=success{*},smswResponseCode={*}APPROVED{*},issuerResponseCode=00,processorUuid=6436adf1-c10b-480f-8522-780737e34bcc,processorDateTime=2022-06-16T13:36:38.000,approvalCode=993083,cardAlias=<null>,pan=<null>,token=,rrn=216713810178,traceId=482167417981733,settlementDate=<null>,instRespData=NO_INSTALLMENT_OFFER]
 
Přesměrování - REQ_IN:
2022-06-16 13:36:39,731 INFO [qtp1869197498-821478][REQ_IN] - REQ_IN
    Address: .../pay/erosstar.cz/3092d7a8-6676-4fc8-bbd5-993088717e17/process
    HttpMethod: GET
    ExchangeId: 804832ca-b21c-4dc4-b0a2-40d7e3c10105
    Headers:

{Cookie=OptanonConsent=isGpcEnabled=0&datestamp=Tue+Jun+14+2022+10%3A50%3A53+GMT%2B0200+(St%C5%99edoevropsk%C3%BD+letn%C3%AD+%C4%8Das)&version=6.21.0&isIABGlobal=false&hosts=&consentId=9e87b0db-7a4e-44b1-a88e- ea66bec47ec8&interactionCount=1&landingPath=https%3A%2F%2Fwww.csob.cz%2Fportal%2Flide%2Fpojisteni%2Fzivotni-pojisteni&groups=C0001%3A1%2CC0002%3A0%2CC0003%3A0%2CC0004%3A0; JSESSIONID=node01rtjy847y1a3988mm2pn9ww5q218476.no de0; SECRET=!qZmZoIbNNnN3fAdg1vs6sAcuEcBaygl7X3ZSmRkZtC6kY5RlFrEJWSzc5PnMB43Nbot6HeS9xDDHTjK96BrRrNszTb2ork08O2qy+RKtpQ==, Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,applic ation/signed-exchange;v=b3;q=0.9, Referer=https://platebnibrana.csob.cz/pay/erosstar.cz/3092d7a8-6676-4fc8-bbd5-993088717e17/threeds-return, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, l ike Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.41, Sec-Fetch-Dest=document, Sec-Fetch-Site=same-origin, Host=127.0.0.1:5010, X-Forwarder-Host=platebnibrana.csob.cz, Sec-Fetch-Mode=navigate, sec-ch-ua=" Not A ;Brand";v="99", "Chromium";v="102", "Microsoft Edge";v="102", sec-ch-ua-mobile=?0, Upgrade-Insecure-Requests=1, sec-ch-ua-platform="Windows", X-Customers-Domain=csob.cz, X-Forwarded-For=77.242.90.136, 10.139.194.161, conne ction=close, Accept-Language=cs,en;q=0.9,en-GB;q=0.8,en-US;q=0.7, X-Real-IP=10.139.194.161, accept-encoding=gzip, deflate, br}
 

Načtení stránky:

Jun 16, 2022 @ 13:36:39.741    User agent major version parsed as '0' : mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/102.0.5005.124 safari/537.36 edg/102.0.1245.41

 
Přesměrování - RESP_OUT:
2022-06-16 13:36:39,775 INFO [qtp1869197498-821478][RESP_OUT] - RESP_OUT
    Address: http://127.0.0.1:5010/pay/erosstar.cz/3092d7a8-6676-4fc8-bbd5-993088717e17/process
    Content-Type: text/html
    ResponseCode: 200
    ExchangeId: 804832ca-b21c-4dc4-b0a2-40d7e3c10105
    Headers: {Cache-Control=no-cache, no-store, must-revalidate, Pragma=no-cache, Expires=0, Date=Thu, 16 Jun 2022 11:36:39 GMT, Content-Type=text/html}
    Payload: <!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <title>erosstar.cz: Online platba 1 295,00 CZK</title>
    <link rel="stylesheet" href="/cz/css/style.css">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <style>
    .sidebar

{         color: #363636;         background-color: #f3f3f3;     }
    .mobile-sidebar .purchased-items

{         background-color: #f3f3f3;         color: #363636;     }
    .purchased-item

{         border-top-color: #d0d0d0;     }
    .total-price

{         background-color: #d52b69;     }
    .total-price::after

{         border-left-color: #d52b69;     }
    .down-arrow

{         background: none;     }
    .mobile-sidebar .total-price.show-arrow::after,
    .mobile-sidebar .total-price.hide-arrow::after

{         color: #ffffff;     }
    .button-cancel::before

{         color: #363636;     }
    .button-cancel

{         background-color: #ffffff;         color: #363636;         box-shadow: inset 0 0 3px #363636;     }
    .mobile-sidebar-bottom

{         background-color: #f3f3f3;         background-image: linear-gradient(top, #f3f3f3, #f3f3f3);         color: #4E4024;     }
 </style>
</head>
<body class="js static-page " id="CSOB-CZ"  onLoad="OnLoadEvent();" >

<div class="overlay-space show">
    <div class="overlay-dialog">
        <div class="overlay-element overlay-adv">

        </div>
        <p class="main-msg">
            Dokončujeme platbu
        </p>
        <p id="redirectText" class="msg return-link-text"></p>
            <form name="submitForm" action="https://www.erosstar.cz/csobpay?oid=104033" method="POST" class="text-center">
                <noscript>
                <p class="text-center small-msg">Pro přesměrování zpět na ErosStar.cz klikněte, prosím, na tlačítko "Vrátit se do obchodu"</p>
                <input class="button" type="submit" name="commit" id="eshop-submit" value="Vrátit se do obchodu" />
                </noscript>
                <input type='hidden' name='payId' value='cdb2e4844d07@HF' /><input type='hidden' name='dttm' value='20220616133639' /><input type='hidden' name='resultCode' value='0' /><input type='hidden' name='resultMessage' value='OK' /><input type='hidden' name='paymentStatus' value='7' /><input type='hidden' name='authCode' value='993083' /><input type='hidden' name='merchantData' value='' /><input type='hidden' name='signature' value='sYubvwY8HD8ANQ0UsEbbbBNbYwRiL51uN6tBPyJDLo87hgzDeJMa+FhDLaxarYTr4piN9NVuUqWYvTLU8FffmXVzml6UMh8Z/q6ayiFzIV2uheZGj9JaCuuyLmznjlUoFz2vRcmCwqUvA93+hNmQqCLfbpU8pTnAy0C4kckUJ1uk6hlNCCDjW5tas+9P/ERIL2WvCcXVvuhhrJCtWgAr5f4PrshchFeMjSQp5ykLau90Z9+rSaBlUR4jbpUaZEKhGKPobfRSGONkVeTuzJlxT2Sbv3YP1VP7hF4V6012hN58acSEHv+s0vYwiLQ4vy8A/kvj1El1Ul6CysGefFaE3A==' />
            </form>
            <script language="Javascript" >
            
            </script>
        <div class="overlay-element fail-icon hide"></div>
        <div class="overlay-element loader hide"></div>
        <div class="overlay-element check-icon show"></div>
    </div>
</div>
<div class="wrap">

    <div class="header">
        <div class="center">
            <h1>Bezpečná online platba</h1>

            <div class="logo-brand"></div>
        </div>
    </div>

    <div class="main">
        <div class="information-text" data-page="page2">
            <p>Vaše platební údaje nikdy nesdílíme s obchodníkem. V adresním řádku prohlížeče si prosím ověřte, že se nacházíte na stránce platebnibrana.csob.cz a že zelená ikonka zámečku indikuje bezpečné spojení.</p> ...


--- 
Jana Grmelová
IT administrátor

**Comment by jgrmelova** [comment]
Dobrý den,

u požadavku neevidujeme žádné doplňující dotazy. Tento požadavek v současné chvíli ukončuji. 

V případě potřeby je možné vytvořit požadavek nový nebo tento požadavek znovu otevřít.

Hezký den.

--
Jana Grmelová

**Comment by zalibaba** [comment]
Dobrý den,

posílám požadovaná ID

M1MIPS1320
M1MIPS1321



S pozdravem Knieradl

**Comment by FVarak** [comment]
Dobrý den,

tuto informaci jsme již obdrželi. 

Stále se jedná o stejnou situaci? 

Bylo provedeno: "Doporučila bych obrátit se na vývojáře e-shopu se žádostí, aby zkusili tuto situaci navodit, aby při přesměrování na e-shop zkusili prohlížeč obnovit, zda se nezobrazí stránka, že se přesměrování nezdařilo. V tomto konkrétním případě se jednalo o prohlížeč Edge." ?

**Comment by zalibaba** [comment]
Dobrý den,

uvedený tiket jsem neotevírali, 
již je vyřešeno, 
cca pár dnů po začátku řešení problému se sám vyřešil, 
a již je vše OK, 
vypadá to že byla asi nějaká chyba v prohlížeči, 
kterou opravila následná aktualizace

s pozdravem Knieradl

**Comment by jgrmelova** [comment]
Dobrý den, 

děkujeme za informaci. Požadavek ukončuji. 

Hezký den.
