### ISSUE TITLE
MasterCard Mobile

### ISSUE THREAD

**Issue by petlom** [csob/paymentgateway#63]
Dobrý den, 
Původní API od GPE podporovalo možnost výběru preferované platbení metody. 

PAYMETHOD 
Hodnota určující preferovanou platební metodu.
Podporované hodnoty:
MCM – MasterCard Mobile
MPS – MasterPass

V testovacím prostředí není možné ověřit. Dostávám hlášku

Omlouváme se za nepříjemnosti, ale platbu MasterCard Mobile momentálně nedokážeme zpracovat. Použijte, prosím, platební kartu, nebo se vraťte do obchodu a vyberte jiný způsob platby.

Podporuje nové eAPI možnost MasterCard Mobile? 
Lze nastavit možnost předvýběrui platby typu MasterCard Mobile?

Děkuji

**Comment by petlom** [comment]
Dnes už přepnutí na MasterCard Mobile funguje. 
Bylo by možné rozšířit eAPI o možnost nastavení paymethod na hodnotu "mcm", aby se defaultně zobrazil způsob platby MasterCard Mobile. 
Děkuji za info.

**Comment by radehorak** [comment]
Dobrý den,
platební brána podporuje MC Mobile a danou funkci nastavuje a povoluje v parametrech ČSOB. Jinak rozšíření do eAPI zvážíme.
Radek Horák

**Comment by jenysdavid** [comment]
Dobrý den,
rád bych navázal na kolegu Petra Lomovciva a na jeho dotaz z 22.října 2015, chci se zeptat na aktuální stav eAPI, zda byla rozšířena paymethod o hodnotu "mcm", nebo nikoliv?

Předem děkuji za odpověď.

S pozdravem
David Jenyš

**Comment by dmarek** [comment]
Požadavek je stále v pipeline, prozatím nebylo rozhodnuto.
