### ISSUE TITLE
Integrační prostředí - ověření karty

### ISSUE THREAD

**Issue by janousek** [csob/paymentgateway#633]
Dobrý den,

při pokusu o platbu pomocí testovacích karet v rámci integračního prostředí dostávám neustále tuto chybovou hlášku:
_Bohužel se nepodařilo ověřit Vaši transakci u vydavatele karty. Zkuste, prosím, transakci provést znovu a v případě přetrvávajících problémů kontaktujte banku, která Vaši kartu vydala._

Chyba se zobrazuje na jen na straně platební brány. Platba je neustále ve stavu 1 a nedochází k předání žádné chyby zpět z platební brány.

Hláška se zobrazuje pro všechna čísla karet a to bez ohledu na zadaný CVC/CVV.

**Comment by pklucka** [comment]
Dobrý den,

požadavek byl předán na servis.

S pozdravem

--
Ing. Petr Klučka
IT Support Specialist

**Comment by jgrmelova** [comment]
Dobrý den, 

můžete mi, prosím, upřesnit pod jakým Merchant ID testujete? 

Moc děkuji. 

--
Jana Grmelová
IT administrátor

**Comment by janousek** [comment]
Dobrý den,

Merchant ID je: A2455DlKtz

**Comment by jgrmelova** [comment]
Dobrý den,

aktuálně by již mělo být v pořádku. Prosím Vás o otestování i z Vaší strany.

Děkuji.

--
Jana Grmelová
IT administrátor

**Comment by janousek** [comment]
Dobrý den,

již je vše funkční.
