### ISSUE TITLE
iPOSman dlouhá reakce

### ISSUE THREAD

**Issue by marekkrivan** [csob/paymentgateway#637]
Dobrý den,

pokud v ipostmanu na testu dám seřadit dle datumu a čas vzniku řadí to nahodile viz screen https://ctrlv.link/Felk
Dále pokud odešlu požadavek na API pro platbu, zaplatím mám ID vše se tváří OK tak zde trvá asi tak 2hod než se projeví platba, dříve to bývalo ihned. Jaká je tam přesná prodleva? Potřebuji to sdělit klientovi, aby věděl jak to otestovat.

Děkuji

**Comment by jgrmelova** [comment]
Dobrý den, 

děkujeme za upozornění. Defaultně se objednávky po vyhledání řadí od nejnovější po nejstarší. Předám však požadavek na kolegu k prověření řazení. Doba než se objednávka v systému POS Merchant objeví se liší v závislosti na frontě požadavků, které se zpracovávají. Tím, že se jedná o integrační prostředí není doba zpracování tak rychlá jako je tomu v produkčním prostředí. Rychlost zpracování prověříme. 

V případě doplňujících dotazů jsem Vám k dispozici. 

---
Jana Grmelová

**Comment by sukvojte** [comment]
Dobrý den,
mám podobný problém se prodlevou ve výpisu transakcí v iposman, s tím rozdílem, že nejde o 2 hodiny, ale o více jak den. V přehledu platebních bran vidím poslední transakci 21.09.2022 15:52:02, rovněž suma souhlasí, ale výpis transkakcí je stále prázdný. Používáme API v1.8, všechny transakce skončily úspěšně a v našem systému vidím korektní API odpovědi o brány.
Mohu poprosit o prověření? Rád bych spustil akceptaci, bohužel bez výpisu transakcí mohu jen smutně koukat.
Děkuji

**Comment by jgrmelova** [comment]
Dobrý den, 

synchronizaci transakcí se systémem POS Merchant na integračním prostředí jsme upravili. Zpracování je nyní rychlejší. 

Můžete, prosím, otestovat i z vaší strany, že je již vše v pořádku? 

Děkuji.

**Comment by sukvojte** [comment]
Dobrý den,
odezva je nyní rozhodně rychlejší (v řádu sekund až minut). 

Děkuji za řešení :)

**Comment by jgrmelova** [comment]
Dobrý den, 

děkuji za informaci, požadavek tedy ukončuji. 

Hezký den.
