### ISSUE TITLE
Formát dat v API rozšíření o zpracování a vypořádání transakce

### ISSUE THREAD

**Issue by pvlst** [csob/paymentgateway#639]
Rozšíření „[Detailní datum a čas zpracování a vypořádání transakce](https://github.com/inoxive/API-1.9/wiki/Detailn%C3%AD-datum-a-%C4%8Das-zpracov%C3%A1n%C3%AD-a-vypo%C5%99%C3%A1d%C3%A1n%C3%AD-transakce)“ obsahuje 4 různé formáty data a času. Z jakého důvodu není dodržen jednotně např. [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) formát, tzn. `YYYY-MM-DD` pro datum a `YYYY-MM-DDThh:mm:ss+-hh:mm` pro datum včetně časové složky?

Kvůli tomuto musíme implementovat 3 různé manuální konvertory těchto dat, neboť vyjma položky `createdDate` jsou ostatní formáty nestandardní. Plus to také naráží na problém popsaný [v jiném issue s neuváděním časových zón](https://github.com/inoxive/API-1.9/issues/11).

**Comment by janbrasna** [comment]
@pvlst To samozrejme irituje vsechny, nicmene jednotlive formaty se za posledni dekadu postupne posbiraly "cestou" z jinych systemu, kombinaci z jinych rozsireni atp. ze kterych toto verejne vznikalo, to je ale v realite amalgam lecjakych privatnich potreb obchodniku za ta leta…

Vsechny nove hodnoty se pridavaji jako ISO 8601… nicmene historicke formaty zustavaji pro zpetnou kompatibilitu napric eAPI v1.x; urcite jakmile bude na poradu dne backlog pro breaking change na API v2+ tak podobne roztrousene formaty se budou sjednocovat.
