### ISSUE TITLE
eAPI 1.9 - refunkční refund mallpay

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#647]
Dobrý den,

od přechodu na eAPI 1.9 nám nám api při refundaci mallpay platby vrací chybu Payment not found

Př.
```
PUT /api/v1.9/mallpay/refund HTTP/1.1

{"merchantId":"M1E3CB0860","payId":"4c1bc9e6fb8b@HI","amount":12900,"refundedItems":[{"code":"52532322","name":"www.slevomat.cz\/akce\/1944700","type":"PHYSICAL","quantity":1},{"code":"48000838","name":"Doprava","type":"SHIPPING_FEE","quantity":1},{"code":"credits","name":"Sleva","type":"DISCOUNT","quantity":10}],"dttm":"20221024131142","signature":"..."}

HTTP/1.1 200 OK
Date: Mon, 24 Oct 2022 11:11:42 GMT

{"dttm":"20221024131142","signature":"...","payId":"4c1bc9e6fb8b@HI","resultCode":140,"resultMessage":"Payment not found"}
```

V Posmerchnatu platbu vidím, takže payId existuje. Problém se vyskytuje u všech storen mallpay plateb.

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás bude informovat odpovědný servisní technik.

**Comment by jgrmelova** [comment]
Dobrý den, 

pro metodu mallpay/refund byla zapnuta kontrola verze, tzn. refund musel být zadán ze stejné verze aplikace jako byla transakce vytvořena. V tomto případě se jednalo o transakci, která byla vytvořena pod verzí 1.8 a refund byl volán pod verzí 1.9. Verze nesouhlasila a refund tedy nebyl proveden.

Byla provedena úprava a kontrola verze v tomto případě byla vypnuta. Nyní by již refund měl být v pořádku zpracován i případě rozdílné verze. Můžete, prosím, zkusit i z Vaší strany, zda je již v pořádku? 

Děkuji.

**Comment by janlanger** [comment]
Bohužel to stále nefunguje, stejná chyba. Testovali jsme payId 07589c3a1f6@HJ

**Comment by jgrmelova** [comment]
Dobrý den, 

moc děkuji za informaci. Předala jsem požadavek na kolegy z vývoje k prověření. 

O výsledku Vás budu informovat.

**Comment by jgrmelova** [comment]
Dobrý den, 

včera došlo k nasazení nové verze. Můžete, prosím, znovu zkusit z Vaší strany, a potvrdit zda je již v pořádku?

**Comment by janlanger** [comment]
Dobrý den, potvrzují že refund již funguje.

Děkuji
