### ISSUE TITLE
eAPI 1.9 - clientIP - IPv6

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#649]
Dobrý den,

následující problém jsme už posílali na support servis@monetplus.cz, ale dosud jsme neobdrželi žádnou reakci. Ticket TSGSMIPS-17981

Platební brána v parametru clientIp metod oneclick/googlepay/applepay neakceptuje IP adresu ve formátu IPv6. A to přesto, že dokumentace explicitně IPv6 zmiňuje.

Dříve na takový požadavek přišla HTML odpověď s textem Request refused, dnes přichází odpověď z API s chybou `{"resultCode":110,"resultMessage":"Invalid format of clientIp parameter"}`

```
POST /api/v1.9/oneclick/init HTTP/1.1
Content-Length: 1209
Accept-Encoding: gzip, deflate
User-Agent: Slevomat.cz Guzzle HTTP client
Host: api.platebnibrana.csob.cz
Content-Type: application/json

{"merchantId":"M1E3CB0860","origPayId":"c335ce3a9a58@GK","orderNo":"1234","clientIp":"2a02:8308:9002:5200:50bc:edf8:6b66:2783","totalAmount":52400,"currency":"CZK","returnUrl":"https:\/\/www.slevomat.cz\/csob-gateway\/receive-gateway-response\/1234","returnMethod":"GET","customer":{**removed**}},"order":{**removed**},"clientInitiated":true,"sdkUsed":false,"dttm":"20221110162321","signature":"..."}

HTTP/1.1 400 Bad Request
Date: Thu, 10 Nov 2022 15:23:21 GMT
Content-Type: application/json
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: 31536000
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self';
X-XSS-Protection: 1; mode=block
Transfer-Encoding: chunked

{"resultCode":110,"resultMessage":"Invalid format of clientIp parameter"}
```

**Comment by jgrmelova** [comment]
Dobrý den, 

situaci jsem prověřila a v současné chvíli dochází k validaci parametru clientIp pouze na IPv4. Požadavek jsem předala na vývojáře k hlubšímu prověření a případně k úpravě. 

O výsledku Vás budu informovat. 

Hezký den.

**Comment by rlombart** [comment]
Opraveno a připraveno na release.

**Comment by janlanger** [comment]
Kdy se můžeme těšit na release?

**Comment by jsmerda** [comment]
Dobrý den,
můžete informovat o tom, kdy release vyjde? Máme stejný problém.
Děkuji moc.

**Comment by rlombart** [comment]
Dobrý den,
release je plánovaný na 5.1.2023

**Comment by janlanger** [comment]
Jak to dopadlo?

**Comment by jgrmelova** [comment]
Dobrý den, 

úprava byla nasazena do produkčního prostředí 05.01.23. 

Hezký den.
