### ISSUE TITLE
WooCommerce pluginu se nepodaří ověřit údaje

### ISSUE THREAD

**Issue by Musilda** [csob/paymentgateway#65]
Dobrý den

použil jsem plugin pro WooCommerce, ale nedaří se mi ověřit podpis.
Mám vygenerované testovací klíče, po kliknutí na objednat se přesměruje eshop na chybovou stránku s tím, že se nepodařilo ověřit údaje. V logu ale není žádná chyba, verify zapisuje OK. 

Pokud použiji produkční klíče, samozřejmě, změním i url api, tak se nestane vůbec nic, plugin, jakoby vůbec nereagoval.

Díky za pomoc.
Musílek

**Comment by ratajskym** [comment]
Dobrý den, nemůžu Vám pomoci, když nevím jediný údaj, kterého bych se chytl. Např Merchant id a čas transakce bude stačit

**Comment by Musilda** [comment]
Dobrý den

Merchant id je M1E3CB2218.
Čas transakce s testovacími klíči je Fri, 23 Oct 2015 05:55:33
Čas transakce s provozními klíči je Fri, 23 Oct 2015 06:01:36

Děkuji

**Comment by ratajskym** [comment]
Prosím, neposílejte nic do produkce, když jste nerozchodil ani test.

Vidím, že jste transakci poslal dnes dopoledne, tak to úplně neodpovídá Vašemu příspěvku. 
October 26th 2015, 10:37:21.986 Received paymentInit request M1E3CB2218 / 6288414d2af0455

S přijetím zprávy nebyl žádný problém a brána Vám odpověděla. Co se stane pak? Odpověď brány se Vám nedaří ověřit? Použil jste správné klíče pro testovací [prostředí](https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys)?

**Comment by Musilda** [comment]
Dobrý den

to mohl udělat klient, já jsem dnes platbu kartou netestoval. 
Proces platby se zastaví po verify. V logu je payment/init verify: 967e9ec3c8ec440|20151023075533|0|OK|1 a dále nic.

**Comment by Musilda** [comment]
Dobrý den

máte pro mne nějakou radu?

**Comment by ratajskym** [comment]
Dobrý den, jak jsem se ptal v předchozím příspěvku

Použil jste správné klíče pro testovací prostředí? Jak se jmenuje veřejný klíč banky, který máte zavedený ve skriptu?

**Comment by Musilda** [comment]
Dobrý den

použil jsem klíče, které jsem si stáhnul v generátoru pro testovací prostředí. Jméno klíče je rsa_M1E3CB2218

**Comment by ratajskym** [comment]
Pro ověření odpovědi je potřeba použít veřejný klíč brány, ke stažení [zde](https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys)

**Comment by Musilda** [comment]
Děkuji, tady byl zádrhel, myslel jsem si, že mám použít oba klíče, které jsou si vygeneroval.

Přeji hezký den.

**Comment by ratajskym** [comment]
Jsem rád, že jsme se domluvili.

Pěkný den
