### ISSUE TITLE
Java example pro eApi 1.9 neodpovídá popisu

### ISSUE THREAD

**Issue by janvyb** [csob/paymentgateway#650]
Třída [OneClickInitResponse](https://github.com/csob/paymentgateway/blob/master/examples/eApi%20v1.9/java/eAPI-v19-connector/src/main/java/cz/monetplus/mips/eapi/v19/connector/entity/responses/OneclickInitResponse.java#L23) neodpovídá popisu v dokumentaci, vrácené odpovědi z platební brány ani stejné třídě v examplu pro C# (takže po přijetí odpovědi jí nelze deserializovat):

Typ atributu `actions` v javě je `List<Action`, viz:
```java
public class OneclickInitResponse extends SignBase {
    @NonNull
    private String payId;
    @NonNull
    private Integer resultCode;
    @NonNull
    private String resultMessage;
    private Integer paymentStatus;
    private String statusDetail;
    private List<Action> actions = new LinkedList<>();
```
[V dokumentaci](https://github.com/csob/paymentgateway/wiki/Methods-for-OneClick-payment#return-values--1) je ale atribut actions popsaný jako objekt [actions](https://github.com/csob/paymentgateway/wiki/Methods-for-OneClick-payment#actions).

[V examplu pro C#](https://github.com/csob/paymentgateway/blob/master/examples/eApi%20v1.9/dotNET/CsobGTWDemo/CsobGatewayClientExample/Communication/DataObjects/Response/OneclickInitResponse.cs#L15) je to správně:
```csharp
public class OneclickInitResponse : SignBase
{
    public string? PayId { get; set; }
    public int ResultCode { get; set; }
    public string? ResultMessage { get; set; }

    public int? PaymentStatus { get; set; }
    public string? StatusDetail { get; set; }

    public Action? Actions { get; set; }
```

**Comment by pklucka** [comment]
Dobrý den, 
Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by janbrasna** [comment]
@janvyb Diky moc za nahlaseni! Muzete vyzkouset fix 7a992acd z #651, zda uz se vam actions podepisi spravne?

**Comment by janvyb** [comment]
Problém se bohužel netýká jen téhle konkrétní třídy, v aktuální podobě je Java implementace nepoužitelná, namátkou:

- Stejný problém s List<Actions> je všude, kde se actions atribut vyskytuje, např. `GooglepayInitResponse`, `GooglepayProcessResponse`, `ApplepayInitResponse`, `ApplepayProcessResponse`, `PaymentStatusResponse`...
- Action nemá žádné atributy a `ActionDeserializer` vrací vždy null, takže u response co obsahují `Action `nelze ověřit podpis, ani z nich vyčíst data
- Třída `Auth3dsBrowser` zdá se odpovídá `fingerprint.browser` v popisu API, má ale přeházené atributy pro podpis, takže nejde ověřit
- Třída `Endpoint` má taky zpřeházené atributy pro podpis, navíc `deleteLast(sb);` se volá na špatném místě
- Lombok anotace jsou, zdá se, přidány náhodně, takže polovině tříd chybí konstruktory a gettery/settery

**Comment by rlombart** [comment]
Opraveny actions ve všech třídách. Opraven ActionDeserializer, opraveny toSign u Auth3dsBrowser a Endpoint, doplněny lombok anotace.

**Comment by janvyb** [comment]
Díky, s touhle úpravou to je již funkční. Měl bych k tomu ještě pár otázek:

- Jak mám jako klient pracovat s těmi Action třídami? Když mi přijde např. `OneclickInitResponse`, tak je tam sice Action, ale ta na sobě nemá žádné atributy, takže jediná možnost je to zkoumat přes `instanceof`, což mi přijde trochu nešikovné
- Jak mám vlastně ty examply použít ve vlastní aplikaci? Aktuálně z toho vypadne spring fat jar, takže to nějak jednoduše bez úprav nejde. Navíc je to pod GPLv3 licencí, takže pokud to upravím, nebudu muset zveřejnit i kód aplikace, do které to přidám jako závislost?

**Comment by rlombart** [comment]
- Můžete si dopnit metody do interface Actions. Např pokud to nepoužíváte na mobilním zařízení (tj. může vám přijít pouze browserInit nebo browserChallenge), tak si můžete např. do interface Actions přidat metodu Optional<Endpoint> getEndpoint() a implementovat je v AuthChallenge a AuthInit. Nebo si můžete do Actions  nadefinovat všechny metody Optional<Endpoint> getEndpoint(),  Optional<SdkChallenge> sdkChallenge() a Optional<SdkInit> sdkInit() (a pokud by Vám to zpřehlednilo kód tak třebas boolean isSdk()). 
- Jestli to chápu dobře (s tím že nejsem odborník na licence), tak pokud se jedná o in-house úpravy kódu (tj. nepřeprodáváte/nedistribuujete dalším firmám), tak upravený kód zveřejňovat nemusíte. Pokud chcete z kódu vytvořit samostatnou knihovnu a tu distribuovat/prodávat dalším stranám tak by jste řešení publikovat jako open source měl.
