### ISSUE TITLE
identita.csob/otevrene-bankovnictvi - výpis JS a 404

### ISSUE THREAD

**Issue by janlemon** [csob/paymentgateway#653]
Dobrý den,

připravujeme párování plateb přes providera Nordigen a při testování napojování CSOB na Nordigen jsme narazili tuto chybu, viz screenshot.

Při loginu na Identita.CSOB se vypisuje celý JS. Můžeme poprosit o fix?

Díky

<img width="1438" alt="Screenshot 2022-11-27 at 20 02 43" src="https://user-images.githubusercontent.com/74051941/204155024-f822df04-8ed7-43ab-9c25-b75a5d6eff5f.png">

**Comment by janlemon** [comment]
[identita.csob.cz-1669577002395.log](https://github.com/csob/paymentgateway/files/10099039/identita.csob.cz-1669577002395.log)

**Comment by jgrmelova** [comment]
Dobrý den, 

identita.csob nesouvisí s platební bránou. 

Pokud však zadám pouze URL adresu identita.csob/otevrene-bankovnictvi, je zde vidět tato informace:

_Chyba serveru
Při zpracování vašeho požadavku došlo k chybě.

Zkuste se sem prosím vrátit později. O problému již víme a na nápravě pracujeme.

Děkujeme za pochopení.
Vaše ČSOB_

Případně se můžete zkusit obrátit na telefonní kontakt uvedený vpravo nahoře:  +420 499 900 222. 

Hezký den.

**Comment by janlemon** [comment]
Dobrý den,

Můžete mě spojit s někým, kdo nám pomůže chybu opravit? 

Děkuju

H.

**Comment by matejcekdav** [comment]
Dobrý den, dle informací co jsem obdržel z API Competence Centra, když jsem se pokusil problém adresovat, jste to již vyřešili. Prosím o potvrzení :) Děkuji, David M.

**Comment by janlemon** [comment]
Dobrý den @matejcekdav ,

psal jsem nejdříve k Vám do ČSOB a bylo mi řečeno, že mám oslovit support z Nordigenu, že chyba je na jejich straně. 

Do Nordigenu jsem psal, zatím bez odpovědi - chyba stále přetrvává.

Děkuju

Honza
