### ISSUE TITLE
Podpora pro `ttlSec` u OneClick platby

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#657]
Dobrý den,
existuje důvod, proč oneClick platba nemá podporu pro `ttlSec`? Dalo by se případně doplnit?

Vzhledem k tomu, že místo neexistujících webhooků musíme periodicky checkovat stav platby, snažím se toto časové okénko alespoň zkrátit na nutné minimum. U google a apple pay tato možnost existuje, u zapamatované karty nikoliv.
Děkuji,

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by dmarek** [comment]
Dobrý den, parameter `ttlSec` doplníme do `oneclick/init` (bude jako nepovinný parameter s default hodnotou, stejně jako u `applepay/init` a `googlepay/init` method)

**Comment by dmarek** [comment]
doplneni `ttlSec` pro `oneclick/init` nasazeno na integracnim a produkcnim prostredi, doplnena dokumentace
