### ISSUE TITLE
v1.9: Jak otestovat platbu bez `actions.fingerprint`

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#658]
Dobrý den,
v testovacím prostředí se po každém volání `<oneclick/googlePay/applePay>/init` vrací `actions.fingerprint`, což se ale v produkci nemusí dít pro každou platbu. Šlo by prosím umožnit otestování všech scénářů i v testovacím prostředí? Například pro cenu `100` je zdokumentováno přeskočení authorizace. Něco podobného by mohlo existovat i pro přeskočení fingerprintu. A ideálně, kdyby se dalo obojí kombinovat.

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by dmarek** [comment]
Dobrý den,

aby bylo možné otestovat scénář bez fingerprintu doplníme do dokumentace novou testovací kartu. Pokud bude zadána, v response `init` metody nebude vyplněna struktura `actions.fingerprint`.

**Comment by pepakriz** [comment]
@dmarek děkuji. Jen se ještě připomínám s tou možností kombinace fingerprint=vyp/zap a auth=vyp/zap. Tzn 4 spec. hodnoty.

**Comment by dmarek** [comment]
@pepakriz ano, nove bude mozne otestovat overeni/platbu i bez moznosti fingerprintu

**Comment by dmarek** [comment]
na integracni prostredi byla nasazena zmena umoznujici otestovani overeni pro @shop metody s/bez fingerprintu, je aktualizovana [dokumentace](https://github.com/csob/platebnibrana/wiki/Testovac%C3%AD-karty)

**Comment by pepakriz** [comment]
@dmarek díky, dobrá práce!
