### ISSUE TITLE
Zadaný ale nezpracovaný refund

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#659]
Dobrý den,

od přechodu na api 1.9 se občas setkáváme se situaci že refundace platby, která je úspěšně odeslána na platební bránu se nezpracuje, není vidět v POS a zákazník peníze neobdrží.

Poslední takový případ máme objednávku `f20899557a69@HL` kdy byly zadány dvě refundace, ale zpracovala se jen první:

```
Jan 09 17:49:11 csobGateway PUT payment/refund | 200 | 114.6 ms | {"merchantId":"M1E3CB0860","payId":"f20899557a69@HL","amount":7700} | {"payId":"f20899557a69@HL","resultCode":0,"resultMessage":"OK","paymentStatus":8}
Jan 09 17:49:11 csobGateway PUT payment/refund | 200 | 99.3 ms | {"merchantId":"M1E3CB0860","payId":"f20899557a69@HL","amount":16600} | {"payId":"f20899557a69@HL","resultCode":0,"resultMessage":"OK","paymentStatus":10}
```

Stejnou situaci jsme zaznamenali i u objednávky `7ff1cfcfab9d@HL`
```
2022-12-12 10:12:49 PUT payment/refund | 200 | 136.9 ms | {"merchantId":"M1E3CB0860","payId":"7ff1cfcfab9d@HL","amount":519600} | {"merchantId":null,"payId":"7ff1cfcfab9d@HL","resultCode":0,"resultMessage":"OK","paymentStatus":8,"authCode":null,"statusDetail":null,"actions":null}
2022-12-12 12:12:59 PUT payment/refund | 200 | 87.7 ms | {"merchantId":"M1E3CB0860","payId":"7ff1cfcfab9d@HL","amount":129900} | {"merchantId":null,"payId":"7ff1cfcfab9d@HL","resultCode":0,"resultMessage":"OK","paymentStatus":8,"authCode":null,"statusDetail":null,"actions":null}
```
Zde byl proveden pouze druhý refund.

Vše M1E3CB0860

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by jgrmelova** [comment]
Dobrý den, 

refundy obou transakcí jsem prověřila. Pokud jsou dva refundy zaslány krátce po sobě, může v ojedinělých situacích nastat chvíle, kdy se jeden refund nezpracuje, a to z důvodu, že právě probíhá zpracování prvního refundu. Tato situace nastala u transakce f20899557a69@HL. 

Refund transakce 7ff1cfcfab9d@HL nebyl korektně zpracován z důvodu omezení na platební bráně. Za způsobené komplikace se Vám omlouvám. 

---
S pozdravem 
Jana Grmelová

**Comment by janbrasna** [comment]
@jgrmelova A nemel by se takovy "neprijaty" refund (protoze probiha zpracovavani predchoziho) zamitnout, aby obchodnik hned vedel ze tu castku efektivne platci nevratil? Aby to bud mohl provest pozdeji, nebo nejak informovat zakaznika. (Tady to ale vypada ze se v poradku refund na api prijima… ale pak se nekde ztrati?!?)

Related:
* #645 
* #557
