### ISSUE TITLE
Apple Pay - test zamítnuté transakce

### ISSUE THREAD

**Issue by vaclavprokopius** [csob/paymentgateway#661]
Dobrý den,
zamítnutí transakce testujeme v testovacím prostředí pomocí částky totalAmount = 200, dle [https://github.com/csob/paymentgateway/wiki/Test-cards-and-credentials#testing-apple-pay-and-google-pay-payments-in-an-integration-environment]
Platba s totalAmount = 200 nám ale při platbě metodou Apple Pay prochází.

**Comment by pklucka** [comment]
Dobrý den,
Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by dkomarek2** [comment]
Dobrý den,

jedná se o nedorozumění, v definici je v tabulce uvedeno, že se jedná o hodnotu "totalAmount", což je formát obsahující i desetinná místa.

Tzn. zápis "200" = "2,00", tedy pro zamítnutí se musí zadat hodnota 2 CZK.

S pozdravem,

Daniel Komárek
QA engineer
MONET+,a.s.
