### ISSUE TITLE
Chybějící podpora pro `language` u oneclick, google a apple pay plateb

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#663]
Dobrý den,

jelikož s verzí 1.9 přibyla u těchto platebních metod závěřečná stránka informující o stavu transakce, bylo by dobré mít možnost změnit její jazyk. Jako je tomu u `payment/init`. Existuje případně jiná cesta, jak jazyk ovlivnit? Například pomocí http hlaviček?

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by dmarek** [comment]
Dobrý den, použijeme parameter `language` ze struktury fingerprint.browser z příslušného volání `oneclick/process`, `googlepay/process` nebo `applepay/process`. Danou úpravu máme zaevidovanou (EPAPG-1074), dáme vědět, až bude nasazeno na ibráně/produkci.

**Comment by pepakriz** [comment]
@dmarek zvláštní řešení. `navigator.language`, které se posílá do `fingerprint.browser` se nemusí shodovat s jazykem, do kterého má uživatel web aktuálně přepnutý. Pro mé potřeby (jelikož se jedná o mobilní appku+webview) to půjde ohnout (ohackovat hodnotu `navigator.language` ve webview), ale kdyby byla naše integrace čistě webová, pak vaše navrhované řešení není stoprocentní. Proto bych se raději přikláněl k zavedení fieldu `language`, jako máte u `payment/init`.

**Comment by dmarek** [comment]
@pepakriz máte pravdu, vhodnější řešení bude přidání nepovinného parametru `language` i do `applepay/init`, `googlepay/init` a `oneclick/init`.

**Comment by janbrasna** [comment]
FYI jazyk transakci "bez nastaveneho jazyka" se bere z Accept* hlavicek, tj. vytahovat to z fingerprintu by stejne nemelo ve vetsine pripadu efekt (pokud se v tom presne takto pri transportu nekdo nevrta, tak vycteny fingerprint mel nejspis stejne preference jazyku jako samotny http request pri otvirani hostovanych kroku dokonceni overeni… a takovy jazyk by se stejne automaticky pouzil tak jako tak.)

@pepakriz Pokud tedy dokazete nastavit tomu WebView "vhodnou" Accept-Language hlavicku dle aktualne zvoleneho uzivatelskeho jazyka, melo by se to vyresit "samo".

@dmarek Je samozrejme otazka, zda to parsovani jazyka funguje spolehlive, a i z bordelu jako `Accept-Language: uk, cs-cz;q=0.9, en-gb;q=0.8, en;q=0` spravne vybere "viteze" jako cestinu 🤷‍♂️

**Comment by dmarek** [comment]
nepovinný parametr `language` přidán i do `applepay/init`, `googlepay/init` a `oneclick/init`, nasazeno na ibránu i na produkci.

**Comment by pepakriz** [comment]
@dmarek super, díky
