### ISSUE TITLE
Request Rejected při oneClick/process

### ISSUE THREAD

**Issue by vojtechMatocha** [csob/paymentgateway#664]
Dobrý den,

na integračním prostředí se snažíme o implementaci platby OneClick přes API 1.9 s využitím 3DS SDK od Netcetera.

2023-02-09 13:58:58,357 [116] INFO  - CSOBGateway oneclick/process(75832d832be0@IB)
2023-02-09 13:58:58,513 [116] INFO  - CSOBGateway oneclick/process -> 200 - OK
2023-02-09 13:58:58,513 [116] INFO  - CSOBGateway oneclick/process -> <html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 2732842130323188173<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>

Jak je vidno z logů výše, dostáváme stav 200 - OK, ale k tomu chybové HTML.

Můžete nám prosím poradit?

**Comment by pklucka** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by vojtechMatocha** [comment]
Doplňuji ještě více informací z našeho volání:

2023-02-13 11:24:06,284 [15]
oneclick/init

OrigPayId = 3ff33fa1933d@IB
OrderNo = 230444104597256
TotalAmount = 1800
Currency = CZK
ClientIp = 46.33.96.97
ClosePayment = True
ReturnUrl = cz.odp.vpk://paymentDone/bcbb07bc-b7f0-4e27-9583-a52e4a19bb5d
ReturnMethod = GET
Customer = NULL
Order = NULL
ClientInitiated = True
SdkUsed = True
MerchantData = NULL
MerchantId = M1MIPS0190

oneclick/init -> {"payId":"7cbc9588300a@IB","resultCode":0,"resultMessage":"OK","paymentStatus":1,"dttm":"20230213112406","signature":"dRItE5edc6f/aON4k0aHGNa7BDG7RXFQWkRfvzDRVHVbe2J8bm/iuMAht2ZxO/7foB6ZvLENi+pk2LNPDl3hiOknW3fqd3C7FAikQ+7X5IGRXuVinj/buja0wOGKXCC1O1gyTRULv5audwJToLo912i8xI2f1gtV7urgdCHfNQfCBtUH/XUuG+gibxEUdJZtvqUqj+n3NcDFRkPn+R5psa8w4UGf/h1EXn5NX7zJCmwy+y6jmF87Q54CKBECZpWq2cF29LncSyXmZbh50lZlDxDj3dH9JN3JpF3Emv8UZ3zmLRDahAttpIW1sldvfdkpYkTdS40WykAWQo6r42kBGA==","actions": {"fingerprint": {"sdkInit":{"directoryServerID":"A000000003","schemeId":"Visa","messageVersion":"2.2.0"}}}}

2023-02-13 11:24:07,018 [81] INFO
oneclick/process
PayID = 7cbc9588300a@IB
AuthData
 Sdk: AppID = b9088efd-777d-4053-ae4d-1d5c4cca5525
 EncData = eyJhbGciOiJSU...p7fvNcqVxlanA
 EphemPubKey = {"y":"8RymFMvJfdc0ePWX_dvqSjB687nzi7j0Q0kUbj50Hbk","x":"bB6dx77PAZxUS7tA9uA5P4XtMcL1i9Z-StmK7hCZXIo","kty":"EC","crv":"P-256"}
 MaxTimeout = 5
 ReferenceNumber = 3DS_LOA_SDK_NEAG_020200_00529
 TransID = 91276290-1afe-44f8-8d70-824da42d2000

oneclick/process ->
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 2732842130327752581<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>

Nemůže být třeba problém ve struktuře EphemPubKey? Nemá se taky kódovat ještě base64?

**Comment by jgrmelova** [comment]
Dobrý den, 

děkujeme za upřesnění. Kolegové z vývojového týmu již situaci prověřují. 

Jakmile budu mít bližší informace, budu Vás informovat. 

---
S pozdravem 
Jan Grmelová

**Comment by mime-digital** [comment]
Dobrý den, připojuji se při pokusu o init platby dostávám zpět totožnou chybu viz níže.
Používám PK vygenerovaný pro sandbox konkrétně A2813jH8hM. 

<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 2732842130335223605<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>

Děkuji.

**Comment by jgrmelova** [comment]
Dobrý den, 

kolegové provedli úpravu, která je již nasazena. 

Hezký den. 

---
S pozdravem
Jan Grmelová
