### ISSUE TITLE
Brána občas nedovolí `payment/close`, pokud je provoláno příliž brzy po stavu 4

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#667]
Dobrý den,

můžete mi prosím potvrdit moji domněnku, že zavolání `payment/close` může způsobit chybový response:
```
{"dttm":"...","signature":"...","payId":"...","resultCode":150,"resultMessage":"Payment not in valid state","paymentStatus":2}
```
přestože jsme těsně před tím získali status, kde paymentStatus=4?

Soudím tak na základě našich logů. Stane se to jednou za čas a osobně bych tipoval, že se to děje z důvodu moc krátkého časového rozestupu mezi překlopením do stavu 4 a následném zavolání `close`. O vteřinu později už platba zavřít lze.

Tato situace nastala například u platby `75d32e4a8d9d@IB`, merchant `M1MIPS7146`
Děkuji za prověření.

**Comment by FVarak** [comment]
Dobrý den, Váš požadavek byl předán k řešení.
O dalším průběhu Vás budeme informovat.

**Comment by jgrmelova** [comment]
Dobrý den, 

situaci jsme se opakovaně snažili navodit. Avšak ani po několika pokusech se nám nepodařilo u nás na vývojovém prostředí situaci navodit. 

Můžete nás, prosím, informovat, zda se s uvedenou situací stále setkáváte? 

Děkuji.
