### ISSUE TITLE
Přechod z API v1 na eAPI1.9

### ISSUE THREAD

**Issue by masak2009** [csob/paymentgateway#670]
Zdravím. Snažím se rozhýbat klienta pro ČSOB platební bránu původně napsaného pro v1. Z dokumentace chápu, že rozdíl je v šifrování: místo SHA1 se má použít SHA256. Tuto změnu jsem udělal nicméně dostávám odpověď (testovací prostředí):
`{"resultCode":110,"resultMessage":"Wrong signature"})`

Client je napsán v Ruby a zde příkládám klíčový moment podepisování:
```
private_key = OpenSSL::PKey::RSA.new(File.read(key))
signature = private_key.sign(OpenSSL::Digest::SHA256.new, text)
Base64.strict_encode64(signature)
```
Testovací URL brány:
[https://iapi.iplatebnibrana.csob.cz/api/v1.9](https://iapi.iplatebnibrana.csob.cz/api/v1.9)

Jestli koukám dobře, není tu po ruce původní dokumentace k v1. V tuto chvíli netuším, co je vlastně špatně. Pokud to změním na SHA1 a URL dám na API v1, platby v testovacím prostředí fungují.

Můžete mi prosím poskytnout integrační rozdíly mezi v1 a v1.9 ?

**Comment by mjanek** [comment]
Dobrý den,
Váš požadavek byl zaevidován a předán k řešení. O dalším průběhu Vás bude informovat odpovědný servisní technik.
S pozdravem
Miroslav Janek

**Comment by mjanek** [comment]
Dobrý den, 
kromě algoritmu se měnili i parametry a jejich pořadí. 
Dokumentace naleznete kompletně na https://github.com/csob/platebnibrana/wiki, v pravé liště dole je i pro verzi 1.0
![obrazek](https://user-images.githubusercontent.com/22815840/224396262-7fdae3c0-334c-453e-ba04-fb507b3da781.png)
Doporučujeme abyste upravili rovnou podle verze 1.9, změn tam bude více.
