### ISSUE TITLE
Apple Pay/OneClick u nativní aplikace - platba 100CZK vyžaduje potvrzení platby zákazníkem

### ISSUE THREAD

**Issue by zbynda** [csob/paymentgateway#673]
Implementujeme eAPI 1.9 do nativní iOS aplikace. Používáme Netcetera 3DS SDK a celý proces platby se nám podaří projít. Pokud ale zadáme částku pro platbu 100 Kč, dle popisu zde https://github.com/csob/platebnibrana/wiki/Testovac%C3%AD-karty by pak nemělo být potřeba potvrzení platby. Nicméně i u těchto částek třeba z funkce POST https://api.platebnibrana.csob.cz/api/v1.9/applepay/process dorazí položka "actions" s vyplněným "sdkChallenge" a stav platby není CONFIRMED. Podobně se eAPI 1.9 chová i u OneClick. Prosím o prověření třeba pro payId "d4c5cf2e2173@IC".
Díky

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek byl zaevidován a předán k řešení. O dalším postupu budete informován odpovědným kolegou.

s pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by pepakriz** [comment]
100 znamená 100 haléřů.

**Comment by zbynda** [comment]
> 100 znamená 100 haléřů.
> 
> edit: Teď koukám, že v dokumentaci se nedávno objevilo dovysvětlení a přidala se podpora i pro kč :)

Ano, původně byla v dokumentaci částka pouze 1Kč / 100, ale aktuálně tam je i 100Kč / 10000, tak počítám, že by to mělo také fungovat.

**Comment by janbrasna** [comment]
Jen pro jistotu si ověřte že opravdu voláte testovací bránu (kde to simulátory přepínají podle testovacích scénářů). Endpoint který je zmíněný v otázce je produkční a tam si vyžadovanou strategii samozřejmě určuje vydavatelská banka protistrany.

**Comment by zbynda** [comment]
Ano, voláme testovací - oneClick normálně vezme testovací kartu 4000007000030004, platba přes Apple Pay žádné peníze neodečte.

**Comment by zbynda** [comment]
Už je vše v pořádku. Díky
