### ISSUE TITLE
API 1.5 a 1.7. - termín ukončení

### ISSUE THREAD

**Issue by adam-janca** [csob/paymentgateway#674]
Dobrý den,

poprosil bych o info k ukončení fungování API v1.5. 

Nastane ukončení prosím natvrdo 1.4.2023 a starší brány využívající 1.5 již nebudou fungovat? Nebo je možné že bude ještě pár dní pozdrženo? 

Řešíme jeden projekt, kde upgradujeme PHP abychom mohli použít poslední verzi API. Ale řešíme ještě nějaké komplikace a tak do 1.4.2023 nestihneme. Dokončení odhadujeme na 10.4..2023.

Musíme na tu dobu vypnout platební bránu? Nebo je možné že API v1.5 ještě chvíli poběží? 
Preferovali bychom kdyby bylo možné vypnutí ještě chvíli pozdržet, aby mohli zákazníci přes ČSOB platit. 

Díky za info jestli je pozdržení možné, nebo zdali máme platby na ČSOB radeji vypnout.

**Comment by pklucka** [comment]
Dobrý den,
k vypnutí API v1.5 dojde někdy v týdnu od 3.4. - 9.4. 2023, přesné datum bohužel neznáme.
Tuto dobu je možné prodloužit zařazením vaší platební brány na whitelist.
O zařazení na whitelist je nutné požádat Vašeho obchodního zástupce (banku).

**Comment by adam-janca** [comment]
Dobrý den,

řešíme obdobnou situaci s verzi API 1.7.. Dle informací by již od května neměla být podporovaná, ale máme ještě jednoho klienta, kde máme upgrade na 1.9 rozpracovaný. Dokončit bychom měli pravděpodobně první týden v květnu. 

Kdy by prosím mělo dojít k finálnímu vypnutí 1.7? Je možné také zařadit projekt na whitelist aby fungoval i nějaký čas v květnu?

Díky za info.

**Comment by matejcekdav** [comment]
Dobrý den, vypnutí eAPI 1.7 proběhne koncem příštího týdne. V případě, že přechod na novou verzi eAPI 1.9 nestíháte do daného termínu, prosím obraťte se s žádostí o výjimku u svého obchodního zástupce. David M.
