### ISSUE TITLE
OneClick platba - expirace šablony po 12 měsících

### ISSUE THREAD

**Issue by Du57iN** [csob/paymentgateway#676]
Dobrý den,
jak se přesně určuje expirace šablony pro OneClick platbu? 
V dokumentaci je : Od poslední OneClick platby uplynulo více než 12 měsíců.
je to přesně 365 dní nebo je možné provést opakovanou roční platbu i po uplynutí 365 dnů aspoň v rámci stejného měsíce kdy došlo k předchozí platbě?
Děkuji

**Comment by FVarak** [comment]
Dobrý den,
Váš požadavek byl předán k řešení. O dalším průběhu Vás budeme informovat.

**Comment by jgrmelova** [comment]
Dobrý den, 

jedná se o počet dní 365. Není tedy možné provést opakovanou roční platbu po uplynutí této doby.  

Hezký den.
