### ISSUE TITLE
Problém se sandbox prostředím

### ISSUE THREAD

**Issue by wodCZ** [csob/paymentgateway#683]
Dobrý den.

Dnes po několika měsících přestal oproti sandbox prostředí fungovat Merchant ID, resp. komunikace začala vracet chybu
```
Invalid parameter merchantId A4018YOoh5
```

Nejspíše jsem při integraci použil Sandbox ID u kterého varujete, že není trvalé. Nevadí, vygeneruji na https://iplatebnibrana.csob.cz/keygen/ nové, protože teď zase nejspíš neseženu údaje pro "plnotučné" testovací merchant ID.

S novým mi ale brána začala vracet chyby s http kódem 403.
```html
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 1643502886961282613<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
```

Zkusil jsem založit další merchant id, stále stejná chyba.

Celý požadavek vypadá následovně:
```http
POST /api/v1.9/payment/init HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json
User-Agent: axios/1.6.2
Content-Length: 682
Accept-Encoding: gzip, compress, deflate, br
Host: iapi.iplatebnibrana.csob.cz
Connection: keep-alive

{"merchantId":"A4487mKFAn","orderNo":"1","dttm":"20231219150810","payOperation":"payment","payMethod":"card","totalAmount":123400,"currency":"CZK","closePayment":true,"returnUrl":"https://wod.fromargo.com/payments/return","returnMethod":"GET","cart":[{"name":"Nákup na webu","quantity":1,"amount":123400}],"language":"cs","signature":"tbYiMCp8VEvm+4OZy0OP+Tp8O87btHdpCiOhYYSqJ502Cf3kKkKX8Ha2I4lZkrpQ6NxsforPUUJb9SabKWumdYBJti9ttnzhEhRQez55jmKOGpYvBl8BtOiU4YAMwSBZbYc3bB2Gy/ceBH80oua0xH3eIwCfDRSsuJpOtMQIcZBu6JG0nESX75A5eS37bTT8C2WywPikMTmOb/wN4tdZAe/GMOreSaqeTWLohMQVSU7wUSPUn4BiKjdSAd2QwXZfrEp0uJi0tL2Kh7aV22HNtkqYQzLdrzRJkM5fLEWwNoY0mGUb519JAJSJHgMvTpbEc3s57vkzZS4KWgYje+R8pg=="}
```

Jde o nějakou dočasnou chybu na vaší straně, nebo je s požadavkem opravdu něco v nepořádku?

Děkuji.

**Comment by jgrmelova** [comment]
Dobrý den, 

ano, platnost anonymního Merchant ID A4018YOoh5 vypršela. 

Pro Merchant ID A4487mKFAn vidím, že chybí veřejný klíč na straně banky:  Payload: {"resultCode":110,"resultMessage":"Merchant key not found for merchantId A4487mKFAn"}. Po vygenerování klíče na https://iplatebnibrana.csob.cz/keygen/ je nutné ještě kliknout na tlačítko "Odeslat veřejný klíč do banky". 

V případě doplňujících dotazů, jsme Vám k dispozici. 

Hezký den. 

Jana Grmelová
IT administrátor

**Comment by wodCZ** [comment]
Dobrý den,

na odeslání jsem zapomněl, po odeslání už se chyba nevrací.

Děkuji.
