### ISSUE TITLE
Špatný překlad platnosti karty do PL

### ISSUE THREAD

**Issue by pvlst** [csob/paymentgateway#688]
Ozval se nám zákazník z Polska, že je na platební bráně špatný překlad platnosti platební karty. Kvůli tomu zadal špatné údaje.

Místo **Płatność**, což znamená platba, by mělo být uvedeno **Ważność**, což je platnost (validita).

![image](https://github.com/csob/paymentgateway/assets/39799837/07a53cc1-011a-4a76-b728-37b92c3ad0a5)

Prosím o opravu, polských nákupů s platbou skrze platební bránu máme vyšší desítky tisíc měsíčně.

**Comment by dmarek** [comment]
Díky za podnět, opravu zařadíme do příštího bugfix release.

**Comment by jgrmelova** [comment]
Úprava přenesena na produkci. Požadavek ukončuji.
