### ISSUE TITLE
payment/init response code 400

### ISSUE THREAD

**Issue by vasek-gmx** [csob/paymentgateway#689]
Platební bránu používáme několik let bez problémů. Teď jsem do requestu **payment/init** přidal objekt customer a upravil podpisový řetězec a začal se nám vracet HTTP response code **400**.

Je to v testovacím prostředí, verze 1.9. Requesty se posílají na  https://iapi.iplatebnibrana.csob.cz/api/v1.9/payment/init

Echo GET a POST funguje.

```javascript
RETEZEC_ZPRAVY = M1MIPS8969|1251|20240729125844|payment|card|90000|CZK|false|http://localhost:8084/order?necy-order=4082&c=EAVNVRUKSR42HSE678MV3TDBP595FM6Y|POST|Produkty|1|90000|Jan Novák|jan.novak@example.com|+420.800300300|cs

json = {
    "merchantId": "M1MIPS8969",
    "orderNo": "1251",
    "dttm": "20240729125844",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 90000,
    "currency": "CZK",
    "closePayment": false,
    "returnUrl": "http://localhost:8084/order?necy-order=4082&c=EAVNVRUKSR42HSE678MV3TDBP595FM6Y",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "Produkty",
            "quantity": 1,
            "amount": 90000
        }
    ],
    "customer": {
        "name": "Jan Novák",
        "email": "jan.novak@example.com",
        "mobilePhone": "+420.800300300"
    },
    "language": "cs",
    "signature": "fPxPff5HArunumyoxrM7UoTJlH/+xZQ/IyTC1zxWiyqnvJ4fr/C73sPV5dinFVYlIWltgGqO+h1BaijkHLezne19yFDo2F9ZESHbuP97mZZjqDHga0yl3619m/M1dfjTU/smn3Cm5FkZeXhG0HV+6wSnQBtfweBr2SGxClKO7OcxpTTuUAT09tcNAXsSRZ7mZRKRuSzkhal3mj13LFfM3jPL6k1Cg4nGQbM3dqitINJIE1BLgMTaTi3gakvakkKjXYqK6mf5mUFk/PbZV3yleUkKkASe6pk2SfVl7hZPPdbYXLUnrKv71X79ln/v/JRQxw+uk/hIxdYrbtSAVa3Cwg=="
}
```

Dokážete mi prosím poradit, co dělám špatně?

**Comment by Mspisar** [comment]
Dobrý den,

Váš požadavek jsme zaevidovali a předali k řešení. O dalším postupu budete informován odpovědným kolegou.

s pozdravem

Milan Spisar
1st level support - Team Leader 

MONET+,a.s., Za Dvorem 505, 763 14  Zlín-Štípa

**Comment by jgrmelova** [comment]
Dobrý den, 

doporučuji zkontrolovat, že JSON texty jsou kódované v UTF-8. 

Viz https://github.com/csob/platebnibrana/wiki/%C4%8Cast%C3%A9-technick%C3%A9-dotazy

V případě dalších dotazů, jsme Vám k dispozici. 

---
Jana Grmelová
IT administrátor

**Comment by vasek-gmx** [comment]
Opravil jsem a funguje. Děkuji.
