### ISSUE TITLE
Nový klient pro PHP

### ISSUE THREAD

**Issue by fprochazka** [csob/paymentgateway#69]
Dobrý den,
rozepsal jsem si vlastního klienta a mimo jiné jsem u něj přepsal Vaše examples.
Do složky, kde jsou umístěny, jsem nakopíroval Vaši licenci a do readme napsal, že je ten kód založen na kódu této knihovny.

https://github.com/Kdyby/CsobPaymentGateway/tree/master/examples

Je to takto licenčně v pořádku, nebo mám něco změnit? 

Díky

**Comment by ratajskym** [comment]
Nevidím důvod, proč by to takhle nemělo zůstat. 

Děkuji
