### ISSUE TITLE
Příklad URL adresy platební brány při migraci z GP Webpay

### ISSUE THREAD

**Issue by webczech** [csob/paymentgateway#7]
Řešíme s klientem převod platební brány GP Webpay na novou platební bránu ČSOB - tento postup je z Vaší strany popsán na url adrese:

https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

Chtěl bych poprosit, zda by v tomto postupu mohla být doplněna ukázková URL adresa pro volání platby vč. parametrů. Není jasné, zda se parametry mají připojit do adresy:

https://platebnibrana.csob.cz/pay/entry/merchant/AMOUNT=123...

nebo volat stejný skript jako doposud:

https://platebnibrana.csob.cz/pay/entry/merchant/order.do?AMOUNT=123...

Obě tyto adresy mi každopádně hlásí chybu "Platba nenalezena", takže bych před dalším řešením problému rád eliminoval možný problém způsobený voláním špatné URL adresy.

Děkuji.

**Comment by dmarek** [comment]
Pokud používáte metodu GET, musí výsledná URL vypadat ...

https://platebnibrana.csob.cz/pay/entry/merchant?AMOUNT=12300&MERCHANTNUMBER=...
(misto / je tam ?)

pokud používáte metodu POST, posílají se jednotlivé parametry v těle požadavku jako "form-url-encoded".

Záleži na použitém pluginu nebo řešení, základ url zadávaný v nastavení pluginu by měl být https://platebnibrana.csob.cz/pay/entry/merchant (pro produkční prostředí)

**Comment by webczech** [comment]
Děkuji. Nyní jsem narazil na nový problém, založím samostatné vlákno.
