### ISSUE TITLE
platba v prostředí e-shopu

### ISSUE THREAD

**Issue by itstudiocz** [csob/paymentgateway#74]
Dobrý den,

od jednoho z našich klientů máme informaci, že je již možné platit přímo v prostředí e-shopu bez přesměrování na platební bránu (prý Vámi byl kontaktovaný pomocí newsletteru). Předpokládám, že by se jednalo o něco ve stylu inline brány GoPay.

Nikde jsem o tom ale nenašel žádné informace, takže nevím, co na tom je pravdy.

Prosím o bližší detaily, pokud něco takového plánujete.

**Comment by ratajskym** [comment]
Dobrý den, myslíte [platbu na klik](https://github.com/csob/paymentgateway/wiki/Platba-Na-klik) ?
