### ISSUE TITLE
Postup při ukládání klíčů

### ISSUE THREAD

**Issue by andreamoravkova** [csob/paymentgateway#75]
Dobrý den,

náš technik po zadání Mechant ID a emailu uložil public a private key a odeslal klíč ve formě žádosti bance.

Jaký je další postup? Máme čekat od banky další instrukce?

Moc děkuji za odpověď!

Morávková (NORTER s.r.o.)

**Comment by Miculka** [comment]
Dobrý den. Patrně jste vygenerovali kliče pro testovací prostředí? Merchant ID by jste mohla sdělit? 

Pak tedy se můžete pustit do integračního prostředí, po úspěšném testu se provede žádost o produkční klíče. 

Postupujte dle návodů - https://github.com/csob/paymentgateway/wiki

**Comment by andreamoravkova** [comment]
Dobrý den, jak mi již bylo sděleno.

Zatím jsme pouze v testu.

*Merchant ID:  M1MIPS0278*

Po uložení klíčů a odeslání žádosti bance, technik říká, že od Vás musí
něco obdržet než bude moci pokračovat.

Je to tak?

Omlouvám se za laické vyjadřování.

Děkuji za odpověď


Dne 12. listopadu 2015 13:20 Michal Mičulka <notifications@github.com>
napsal(a):

> Dobrý den. Patrně jste vygenerovali kliče pro testovací prostředí?
> Merchant ID by jste mohla sdělit?
>
> Pak tedy se můžete pustit do integračního prostředí, po úspěšném testu se
> provede žádost o produkční klíče.
>
> Postupujte dle návodů - https://github.com/csob/paymentgateway/wiki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csob/paymentgateway/issues/75#issuecomment-156089636>.
>



-- 
*S pozdravem*

*Mgr. Andrea Morávková*
*Project Manager*
*722649257*
*flymeango.com <http://flymeango.com>*

**Comment by Miculka** [comment]
Ne, nyní se pustťe do testů. Výsledky testů jsou na https://iposman.iplatebnibrana.csob.cz/posmerchant/ po zadání platební brány - vašeho ID - vyhledat  -  a poslední ikonka s klíčemi - provést validaci a zjistíte jak jste daleko.

Na projití testem máte návody zde a na přechod do produkce též. 

Jakmile projdete integračním (testovácím) prostředím, poté zažádáte o klíče do produkce u banky. Úspěšné testy zjistít na strance POSm ve validaci bude vše označeno zelenou fajfkou. 

V případě problémů Vám budeme k dispozici.

**Comment by andreamoravkova** [comment]
Dobrý den pane Mičulka,

abych mohla vyhledat naší validaci, tak je potřeba uživatelské jméno a
heslo.

Tyto údaje mají být ve smlouvě?

Děkuji.


Dne 12. listopadu 2015 13:34 Michal Mičulka <notifications@github.com>
napsal(a):

> Ne, nyní se pustťe do testů. Výsledky testů jsou na
> https://iposman.iplatebnibrana.csob.cz/posmerchant/ po zadání platební
> brány - vašeho ID - vyhledat - a poslední ikonka s klíčemi - provést
> validaci a zjistíte jak jste daleko.
>
> Na projití testem máte návody zde a na přechod do produkce též.
>
> Jakmile projdete integračním (testovácím) prostředím, poté zažádáte o
> klíče do produkce u banky. Úspěšné testy zjistít na strance POSm ve
> validaci bude vše označeno zelenou fajfkou.
>
> V případě problémů Vám budeme k dispozici.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csob/paymentgateway/issues/75#issuecomment-156092664>.
>



-- 
*S pozdravem*

*Mgr. Andrea Morávková*
*Project Manager*
*722649257*
*flymeango.com <http://flymeango.com>*

**Comment by Miculka** [comment]
Přijde vám emailem zadaným při generování klíčů.

**Comment by andreamoravkova** [comment]
Dobrý den ještě jednou pane Mičulka,


již je to dva dny a na můj email (andrea.moravkova@norter.cz) žádné údaje
nepřišly!

Jak dlouho to standartně trvá?

Děkuji za odpověď!







Dne 12. listopadu 2015 14:09 Michal Mičulka <notifications@github.com>
napsal(a):

> Přijde vám emailem zadaným při generování klíčů.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csob/paymentgateway/issues/75#issuecomment-156098827>.
>



-- 
*S pozdravem*

*Mgr. Andrea Morávková*
*Project Manager*
*722649257*
*flymeango.com <http://flymeango.com>*

**Comment by Miculka** [comment]
No max den, ale spíše obratem. 

Zkontrolujte adresy osokin@norter.cz

**Comment by Miculka** [comment]
Omlouvám se, mrkněte do smlouvy. Tam tyto údaje naleznete. 

Heslo pro přístup vám přijde až pro produkční prostředí.

**Comment by Cleme987** [comment]
> Dobrý den ještě jednou pane .com_
