### ISSUE TITLE
Legacy API

### ISSUE THREAD

**Issue by MartaniCZ** [csob/paymentgateway#76]
Dobrý den,

zkoušíme převést branu klienta na Legacy API. Požadavky tedy místo na gpwebpay.com smeřujeme na url https://iplatebnibrana.csob.cz/pay/entry/merchant/csob/order.do. Nicméně stále dostáváme chybovou hlášku 

Platba nenalezena
Požadovaná platba bohužel neexistuje, nebo vypršela platnost požadavku. Pokoušíte-li se zaplatit objednávku, vraťte se prosím na stránky obchodníka a zaplaťte prosím znovu.

Prosím o radu.

Děkuji.

**Comment by ratajskym** [comment]
Dobrý den, zkuste následující url https://iplatebnibrana.csob.cz/pay/entry/merchant

https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

**Comment by MartaniCZ** [comment]
Odstranili jsme chybný konec url. Nyní dostáváme hlášku:
Platba nemůže být provedena
Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem.

**Comment by ratajskym** [comment]
Tak mi prosím sdělte merchant id, podívám se do logu

**Comment by MartaniCZ** [comment]
Je to testovací A13285GASy. Děkuji.

**Comment by ratajskym** [comment]
Nemáte vygenerované klíče. Věnujte prosím pozornost [dokumentaci](https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay)

**Comment by MartaniCZ** [comment]
Vygenerovali jsme nové testovací ID A1346bcHrK a tentokrát správně použili i poslední tlačítko na stránce https://iplatebnibrana.csob.cz/keygen/. Nyní jsme se již na testovací bránu dostali. Děkuji za spolupráci a trpělivost.

**Comment by ratajskym** [comment]
Dobře. Issue uzavírám.
