### ISSUE TITLE
Nezdokumentovaný resultCode

### ISSUE THREAD

**Issue by jiripudil** [csob/paymentgateway#78]
Pokud pošlu požadavek na opakovanou platbu, ale jako origPayId předám id platby, která nebyla označena jako šablona pro opakovanou platbu, eAPI mi vrátí resultCode 180 a resultMessage `orig payment not recurrent payment template`. Tento stav zdá se není zdokumentovaný.

**Comment by jiripudil** [comment]
A když už jsme u toho, v dokumentaci je nejvyšší návratový kód relevantní pro platby 150. Teď jsem narazil na 180. Není možné, že jsou nezdokumentované i kódy 160 a 170, případně i vyšší?

**Comment by ratajskym** [comment]
Dobrý den, 

chybějící response kódy prověříme a doplníme do dokumentace. Děkujeme za upozornění

**Comment by dmarek** [comment]
do dokumentace [eAPI 1.5](https://github.com/csob/paymentgateway/wiki/eAPI-1.5) doplněn chybějící response kód "Operation not allowed" (180). 

Výše uvedená chyba "orig payment not recurrent payment template" s kódem 180 se vrací v případě, že se pokoušíte provést opakovanou platbu na základě autorizované transakce, která není označena jako šablona pro opakované platby (aby byla transakce označena jako šablona pro opakované platby a bylo ji možné použít, je nutné v parametru `payOperation` při založení transakce  nastavit hodnotu `recurrentPayment`).

ještě jednou díky za upozornění, chybějící část dokumentace byla sice připravena a zrevidována ale už se nedostala do public verze.

**Comment by dmarek** [comment]
uzaviram, pokud se jeste neco vyskytne, dejte vedet.
