### ISSUE TITLE
Nelze opakovat platbu s větší částkou

### ISSUE THREAD

**Issue by jiripudil** [csob/paymentgateway#79]
Při pokusu o opakovanou platbu s částkou převyšující částku původní platby mi eAPI vrátí kód 110, `payment/recurrent amount exceeds origin payment amount`. Kolega mi ovšem říkal, že mu to nedávno fungovalo korektně, tzn. že platba s vyšší částkou prošla. Nezměnilo se něco?

**Comment by ratajskym** [comment]
Dobrý den,

každý obchodník může mít své specifické nastavení. Konkrétně v tomto případě máte nastaveno:
- opakovaná platba je povolena
- částka musí být stejná nebo nižší jako původní platba
- částka musí být ve stejné měně jako původní platba

Pokud to kolegovi fungovalo, pravděpodobně pracoval s jiným merchant id než Vy. Je to možné?

**Comment by jiripudil** [comment]
Dobrý den, je to nejen možné, ale dokonce pravděpodobné. Díky za nasměrování a toto issue zavírám.

**Comment by KEYELEMENTS** [comment]
Dobrý den, můžete mi poradit, kde takové nastavení najdu?  
Ve webové aplikaci "Posmerchant - Testovací (implementační) prostředí pro platební bránu" jsem to nenašel.
Děkuji
