### ISSUE TITLE
Výpis chybových hlášení při neúspěšném volání platby (migrace ze systému GP Webpay)

### ISSUE THREAD

**Issue by webczech** [csob/paymentgateway#8]
Při neúspěšném požadavku na provedení platby dojde k přesměrování na obecnou url adresu:

https://platebnibrana.csob.cz/pay/merchant-error.html

Na této adrese je zobrazena velmi obecná informace "Platba nemůže být provedena
Omlouváme se za nepříjemnosti, ale v platebním požadavku obchodníka se objevila technická chyba. Vraťte se, prosím, na stránky obchodníka a zaplaťte jiným způsobem."

Je možné nějakým způsobem zjistit v čem konkrétně je problém? Původní brána GP WebPay vracela kombinace chybových stavů, pomocí kterých byl problém jednoduše dohledatelný.

**Comment by dmarek** [comment]
Doporučuji test na integračním prostředí (ověření, že podpis požadavku pomocí nově generovaných klíčů je v pořádku). 

Chyba, kterou zmiňujete výše je zobrazena v případě, že nejsou validní základní parametry (identifikace obchodníka, nesedí podpis). Takto obecná je z důvodu nastaveného zabezpečení platební brány. 

Poté, co je příchozí požadavek zvalidován na základní parametry, jsou další případné chyby reportovány pomocí `resultCode` a `resultMessage` v zasílané odpovědi (viz také https://github.com/csob/paymentgateway/wiki/eAPI-v1-CZ#%C4%8C%C3%ADseln%C3%ADk-n%C3%A1vratov%C3%BDch-k%C3%B3d%C5%AF-), a to u non-browser operací `payment/init`, `payment/status` apod anebo zobrazením podrobnější chybové zprávy přímo v prohlížeči v případě přesměrování na platební bránu pomocí `payment/process`.

**Comment by webczech** [comment]
Bohužel přestože jsou použity nově vygenerované klíče (pro produkční prostředí, veřejný byl zaslán do banky), je použita nová URL adresa platební brány (produkční prostředí) a nová hodnota merchant_id, se stále zobrazuje toto chybové hlášení. Nemůže problém nastat i v případě, kdy klient nemá produkční prostředí povoleno? Je možné se s konkrétním problémem obrátit na někoho mimo github, kdo by zjistil, kde je problém?

**Comment by ratajskym** [comment]
Dobrý den, jak to vypadá s Vaším problémem? Podařilo se jej vyřešit ?

**Comment by webczech** [comment]
Dobrý den,

ano, problém jsme dořešili po emailu již dávno. Problém byl způsoben 
nepotvzrením klíčů pro produkční prostředí ze strany zákazníka.

S pozdravem

Petr Konečný

GlobeWeb Czech s.r.o.
www.webczech.cz
email: petr.konecny@webczech.cz

Dne 4. 8. 2015 v 9:12 Martin Ratajský napsal(a):

**Comment by ratajskym** [comment]
Děkuji za informaci. Uzavírám.
