### ISSUE TITLE
Inicializace platby - malformed

### ISSUE THREAD

**Issue by Madla** [csob/paymentgateway#80]
Dobrý den,

snažím se inicializovat platbu a bohužel se mi vrácí "reason: malformed" ... bohužel, z toho nejsem schopen poznat, kde přesně chyba je. Mohli by jste mi prosím pomoc?

payment/init data to sign:: 'M1MIPS0059|11300074|20151101111111|payment|card|50800|CZK|false|http://www.vasepoteseni.cz/rezervace-objednavky/|POST|Vasepoteseni.cz...|1|49800|Platba za zbozi...|DPD - doprava prepravni spolec...|1|1000|Doprava|Platba za zbozi|CZ'

Dále bych se Vás chtěl zeptat, zda existuje někdě nějaká stránka či tool, kde bych se dozvěl více informací o dané chybě.

Děkuji

**Comment by ratajskym** [comment]
Dobrý den, 

vidím Vaše transakce v produkčním prostředí a tam není Váš merchant povolen. Zkuste to prosím napřed proti testovacímu prostředí.

**Comment by Madla** [comment]
Dobrý den,

problém byl někde jinde. Měl jsem špatnou URL na platební bránu.

Děkuji za pomoc
