### ISSUE TITLE
Návrat z plaby

### ISSUE THREAD

**Issue by snrcze** [csob/paymentgateway#81]
Dobrý den, programuji platební bránu poprvé a chci se zeptat, jakým způsobem se řeší návrat z platby. Vrací to stav platby, jestli byla úspěšná atd., ale podle které hodnoty mám danému zákazníkovi přiřadit, že ji zaplatil právě on? Například, aby mi to vrátilo i hodnotu order_no. Děkuji za odpověď.

**Comment by ratajskym** [comment]
Dobrý den, 

v inicializaci transakce máte parametr customerId. Podívejte se prosím do dokumentace

https://github.com/csob/paymentgateway/wiki/eAPI-1.5#-post-httpsapiplatebnibranacsobczapiv15paymentinit-

**Comment by snrcze** [comment]
A je možné, abych například v returnURL pomocí metody GET získal mujobchod.cz/navrat?order_no=123456 ? Případně jak to udělat? Děkuji za odpověděď.

**Comment by ratajskym** [comment]
Návratové hodnoty jednotlivých funkcí jsou přesně definovány v dokumentaci.

**Comment by snrcze** [comment]
Stále nevím, kde mám zadat, jaké hodnoty chci vrátit. Není mi to z dokumentace jasné.. Pro jistotu opakuji, že jsem začátečník. Všechno mi už funguje, jen se mi nedaří získat zpět v odkaze order_no. Mohl byste sem, prosím, vložit příklad kódu, kde a co změnit?

**Comment by ratajskym** [comment]
Vy přece nevybíráte co Vám má brána vrátit. Brána vrací hodnoty podle toho, jak je popsáno v dokumentaci. Takže pro Vás by to bylo asi následovně:
Provádíte paymentInit (posíláte své číslo objednávky) -> brána Vám vrací unikátní payId
V další komunikaci už pracujete s payId, které máte u Vás svázané s číslem objednávky. 

Případně se můžete inspirovat [zde](https://github.com/csob/paymentgateway/tree/master/eshop-integration/eAPI/v1.5/php/example). Skript ovšem není určen pro produkční prostředí.

**Comment by snrcze** [comment]
Jo takhle, já že můžu pořád pracovat s naším číslováním objednávek. Už tomu rozumím. Děkuji moc za Vaši pomoc. Přeji pěkný den. :)
