### ISSUE TITLE
Automatické platby

### ISSUE THREAD

**Issue by simPod** [csob/paymentgateway#82]
Je nutné strhávání plateb od zákazníka nejak potvrzovat, pokud mi už jednou povolil uložení karty?

Potrebuji vedet, zda-li je s vasim API mozny tento use case:

Zakaznik si objedna opakovanou sluzbu, pri prvni platbe zada svou kartu, ta se ulozi k vam do systemu, probehne platba. Nastane opakovani sluzby a platba se vykona automaticky na zaklade nejakeho ulozeneho tokenu, ktery identifikuje zakaznikovu kartu u vas a provede transakci bez nutnosti obtezovani zakaznika s platbou

**Comment by dmarek** [comment]
Ano, je to možné pomocí [opakovaných plateb](https://github.com/csob/paymentgateway/wiki/eAPI-1.5#opakovan%C3%A1-platba-). Po provedení prvotní platby za účasti zákazníka už jen voláte operaci `payment/recurrent`. Obchodník musí mít na platební bráně opakované platby povolené.

**Comment by simPod** [comment]
supr dekuji
