### ISSUE TITLE
Kontrola postupu

### ISSUE THREAD

**Issue by michalfreiberg** [csob/paymentgateway#84]
Dobrý den,

chtěl bych se zeptat jestli postupuji správně. Od klienta jsem obdržel přístupy do https://iposman.iplatebnibrana.csob.cz/posmerchant, merchantID "gf36NW17" a email, který uvedl při registraci u vás. Bohužel se mi ale nedaří vygenerovat testovací klíče na https://iplatebnibrana.csob.cz/keygen/. Zkoušel jsem místo merchantID zadávat i ID platební brány, ale také bez úspěchu. Klient tvrdí, že žádné další údaje z banky nemá. 

Je to merchantID správné? Přijde mi divné, že testovací anonymní mělo 10 znaků a toto má jen 8.

Díky za odpověď

Michal

**Comment by Miculka** [comment]
Dobrý den. Dejte prosím před ID ještě M1- tj. M1gf36NW17

**Comment by michalfreiberg** [comment]
Dobrý den,

díky za odpověď. Pořád se mi ale nedaří klíče vygenerovat. Mohl byste
prosím zkontrolovat jestli uvedený email (krepela@worldcz.cz) je zadaný i u
vás? Nebo je tam jiný? Informace od klienta jsou bohužel trochu zmatené.

Díky za odpověď,

Michal Freiberg

Dne 20. listopadu 2015 12:31 Michal Mičulka <notifications@github.com>
napsal(a):

**Comment by Miculka** [comment]
V naší aplikaci jsem tohle ID nenašel. Je tedy možné, že je v něm chyba. Zkusme dohledat obchodníka podle IČO. Znáte?

**Comment by michalfreiberg** [comment]
IČ je 26731851. Díky

Dne 20. listopadu 2015 16:06 Michal Mičulka <notifications@github.com>
napsal(a):

**Comment by Miculka** [comment]
IDcka brany dle ICO obchodnika jsem vyhledal 

M1MIPS0203
M1MIPS0204

Obe maji emaily mlejnek, krepela od worldcz
a info od erex24

**Comment by michalfreiberg** [comment]
Dobrý den,

děkuji. U ID M1MIPS0203 se mi podařilo kódy vygenerovat, ale nedaří se mi z
nich sestavit podpis. V příloze posílám data, která odesíláme na bránu.
Vrací se kód 400.

Mohl byste se na to prosím podívat, kde by mohl být problém?

Děkuji,

Michal Freiberg


Dne 20. listopadu 2015 17:42 Michal Mičulka <notifications@github.com>
napsal(a):

> IDcka brany dle ICO obchodnika jsem vyhledal
>
> M1MIPS0203
> M1MIPS0204
>
> Obe maji emaily mlejnek, krepela od worldcz
> a info od erex24
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csob/paymentgateway/issues/84#issuecomment-158454429>.
>

{
    "merchantId": "M1MIPS0203",
    "orderNo": "611525111001",
    "dttm": "20151125185330",
    "payOperation": "payment",
    "payMethod": "card",
    "totalAmount": 9698,
    "currency": "EUR",
    "closePayment": "false",
    "returnUrl": "http://www.medichea.eu/erex_eu/platba_csob.php",
    "returnMethod": "POST",
    "cart": [
        {
            "name": "E-REX 24 Forte (60 tabliet)",
            "quantity": 1,
            "amount": 4798,
            "description": "test"
        },
        {
            "name": "Pošta",
            "quantity": 1,
            "amount": "49",
            "description": "test"
        },
        {
            "name": "ČSOB",
            "quantity": 1,
            "amount": "0",
            "description": "test"
        }
    ],
    "description": "Nákup na Erex24.eu: E-REX 24 Forte (60 tabliet)",
    "merchantData": null,
    "language": "EN",
    "signature": "HbnSWXzUqS7rWIoIybHaCJJZGpOzhCOtdhzD8/YSWXR+BgizeUGSyKLJBYUuhWar5SGujL3n9VrqliEEBEOsV3eeap1SJ5KB6h8sPU0PyZQQM/63d+7l2b+9XA4X3Q7ovCTnFc0oj0Pa24iwXXv5mBXerryrFRRdrvqKkYSlt8pRi+7awHvKDBjwDksb+YAagFKyqQxpcY1OpC4Jt/zuf4yjP/ZoOpakm/xVR3ltQjjx5tO7nCAequHQBzsCJkctob8D0/Yp9L0Q3SjT1Hk36HPBhygGNySOCwmoKsuCpGe2+Xu5/r7kCgHlQW43TkhaOJFCHBshxTuaKSfajyKyYQ=="
}

**Comment by ratajskym** [comment]
Dobrý den, 

v našem aplikačním logu vidím "špatný podpis". Při letmém pohledu na Vám uvedený signature vidím obsažené lomítka. Ty by v podpise neměli být, podpis by měl být url encoded.

**Comment by michalfreiberg** [comment]
Dobrý den,

díky za informaci. Pro vytvoření podpisu používám třídu crypto.php z Vašeho
příkladu. Podpis je tam zakódován pomocí base64_encode, který lomítka
prostě někdy vrací... Můžu lomítka samozřejmě nahradit jiným znakem, ale
nedokážu si pak představit, jak by došlo k dekódování na Vaší straně.

Když jsem vyzkoušel pustit Váš ukázkový příklad pomocí mých na bráně
vygenerovaných klíčů (nic jiného jsem ve Vašem kódu nezměnil), tak byla
odpověď také 400 a v podpisu byly lomítka. S kódy z příkladu vše proběhlo v
pořádku. Není potřeba ty klíče ještě nějak aktivovat (já jsem pouze po
vygenerování klíčů klikl na "odeslat veřejný klíč do banky")?

Testoval jsem to pro ID: M1MIPS0203

Díky za pomoc,

zdraví Michal Freiberg


Dne 26. listopadu 2015 9:13 Martin Ratajský <notifications@github.com>
napsal(a):

**Comment by ratajskym** [comment]
Jak jsem psal v předchozím postu, při odeslání na bránu je potřeba na podpis použít fci [urlencode](http://php.net/manual/en/function.urlencode.php)

**Comment by michalfreiberg** [comment]
To jsem zkoušel a výsledek byl stejný.

2015-11-27 11:50 GMT+01:00 Martin Ratajský <notifications@github.com>:

**Comment by ratajskym** [comment]
Echo Vám funguje? viz [dokumentace](https://github.com/csob/paymentgateway/wiki/eApi-1.5#getpost-httpsapiplatebnibranacsobczapiv15echo-)

**Comment by michalfreiberg** [comment]
Nefunguje, ale posílám tam stejný podpis jako do "init", takže problém bude
při vytváření toho podpisu. Bohužel ho nemůžu objevit stále. Vzhledem k
tomu, že stejně dopadne i Vaše ukázková aplikace s mými klíči, tak si
myslím, že bude problém v nich.

Jinak jsem zkusil pustit tu ukázkovou aplikaci s přidaným urlencode a vrátí
se mi pak také kód 400. I s Vašimi původními klíči. Urlencode jsem použil
na $data["signature"] ve funkci crypto->createPaymentInitData(). Je to
špatně?

Díky

2015-11-27 12:07 GMT+01:00 Martin Ratajský <notifications@github.com>:

**Comment by ratajskym** [comment]
Pokud Vám nefunguje ani naše ukázková aplikace, tak může být opravdu problém s klíči. V tom případě nezbývá, než vygenerovat nové a zkusit to ještě jednou.

**Comment by ratajskym** [comment]
Dobrý den,

vidím, že Váš problém je již vyřešen, task tedy uzavírám.
