### ISSUE TITLE
`payment/recurrent ` vrací #500

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#85]
Dobrý den,

asi blbě používám `payment/recurrent`. Brána neřekne, co dělám špatně. Místo toho dostávám pětikilo.
testovací metchantId `A1376F8OiD`

Díky za info

**Comment by ratajskym** [comment]
Dobrý den, 

zkuste to, prosím, ještě jednou.

**Comment by pepakriz** [comment]
Dobrý den,

chybu způsobuje nevalidní request (místo `orderNo` jsem posílal `orderId` s UUID), v případně validních dat vše funguje. Očekával bych kód `100` (viz https://github.com/csob/paymentgateway/wiki/eAPI-1.5#%C4%8C%C3%ADseln%C3%ADk-n%C3%A1vratov%C3%BDch-k%C3%B3d%C5%AF-)

**Comment by dmarek** [comment]
dikza za upozorneni, opravime.

**Comment by ratajskym** [comment]
Nasazeno na testovací prostředí, nyní se bude vracet smysluplnější hláška

"resultCode": 100,
"resultMessage": "Missing parameter orderNo",
"paymentStatus": 6

**Comment by pepakriz** [comment]
:+1:
