### ISSUE TITLE
Při odstávce API dostávám #200 dokumentace tvrdí něco jiného

### ISSUE THREAD

**Issue by pepakriz** [csob/paymentgateway#86]
V dokumentaci je psáno, že při odstávce vrací server #503, nyní probíhá odstávka (30.11.2015 10:00) a server vrací HTML s kódem 200

**Comment by ratajskym** [comment]
Dobrý den, 

v tomto případě se nejednalo o standardní odstávku, ale jen o restart aplikace, který trval několik málo minut.

**Comment by pepakriz** [comment]
Dobrý den,

restart nebo odstávka je pro mě totožná situace. V dokumentaci píšete pro kód `503` popis `Služba je dočasně mimo provoz.`, což podle mě přesně vystihuje mimo jiné i situaci, kdy provádíte restart.
Jaký je tedy podle Vás doporučený postup, jak na stejnou situaci reagovat? Mám detekovat kód `200` a matchovat text v html? To snad ne

Děkuji za reakci

**Comment by kukulich** [comment]
Dobrý den,

prosím @ratajskym o reakci k tomu, co psal výše @pepakriz.

**Comment by janbrasna** [comment]
To vypadá podobně jako #135 — tzn. by i HTML odpovědi měly mít správné HTTP signálování.

@pepakriz BTW to HTML vracel API request, nebo nějaký wget na frontendovou URL?

**Comment by kukulich** [comment]
@janbrasna Vracel to API request, viz název tohoto issue.

**Comment by janbrasna** [comment]
@kukulich Wow. OK. To zni docela divoce;) Proto jsem se pro jistotu jen znovu ptal… Dobre vedet, budu sledovat.

**Comment by ratajskym** [comment]
@janbrasna @pepakriz je to dáno architekturou systému, o které bych se tady nerad více rozepisoval. Testovací a produkční prostředí při nedostupnosti aplikace vrací html stránku "Omlouvame se, pozadovana sluzba je momentalne nedostupna." tedy status 200. 

Na vývojovém prostředí tato html stránka není a vrací se Status 502 Bad Gateway.

Proberu interně co s tím

**Comment by janlanger** [comment]
@ratajskym Stačilo by vracet stejnou HTML stránku ale s HTTP 503. Problém není ani tak v tom že posíláte HTML ale právě v tom že ho posíláte s HTTP 200, což nám neumožňuje detekovat problém.

**Comment by ratajskym** [comment]
Dobrý den, tohle už je u nás v procesu. Budu Vás informovat o nasazení

**Comment by ratajskym** [comment]
Informuji Vás o nasazení úpravy. V případě nedostupnosti aplikace bude zasílán http kód 503
