### ISSUE TITLE
Produkční brána vrací 500

### ISSUE THREAD

**Issue by adman01** [csob/paymentgateway#87]
Dobrý den,

při přepnutí na produkční platební bránu mi brána vrátí http code 500.

Merchant ID: M1E3CB3618
URL: https://api.platebnibrana.csob.cz/api/v1/payment/init/

Nevíte, kde dělám chybu?

**Comment by ratajskym** [comment]
Dobrý den,

na produkčním prostředí musíte rovněž vygenerovat klíče. Tyto klíče je nutné aktivovat v aplikaci Posmerchant pomocí jenorázového hesla, které Vám bylo zasláno emailem

**Comment by adman01** [comment]
To jsem samozřejmě udělal. Tuto informaci máte napsanou v logu?
Mohu to zkusit ještě jednou, ale bojím se, že výsledek bude stejný.

**Comment by ratajskym** [comment]
Ne, tohle jste neudělal. 

Klíče jste generoval dne 30.09.15 13:51:02 a následně Vám byl zaslán OTP. Tímto kódem musíte musíte v aplikaci Posmerchant vygenerované klíče potvrdit. Toto potvrzení jste neprovedl

**Comment by adman01** [comment]
Dobrý den,

měl jste pravdu, klíč opravdu nebyl potvrzený. Nově jsem ho potvrdil, ale opět se mi nedaří ověřit platbu. Můžete se ještě jednou podívat do logu, kde je chyba?

**Comment by ratajskym** [comment]
Předpokládám, že se nedaří ověřit platba u Vás v eshopu a to v našem logu těžko uvidím. Používáte správný veřejný klíč platební brány?

**Comment by adman01** [comment]
Máte pravdu, že je chyba v ověření veřejného klíče, ale jak postupovat, pokud mám klíč nově vygenerovaný a stále se chyba opakuje? Kód jsem ověřoval a mám za to, že načítám správný klíč.

**Comment by ratajskym** [comment]
Dobrý den,

správný postup by byl, přečíst si dokumentaci. Veřejný klíč platební brány není ten Vámi vygenerovaný , ale musíte použít [tento](https://github.com/csob/paymentgateway/tree/master/eshop-integration/keys). Pozor, pro testovací a produkční prostředí je jiný.

**Comment by adman01** [comment]
Aha, už to funguje. Pravda, měl jsem se prvně podívat do dokumentace, ale po zcela groteskním php příkladu z minulého tisíciletí a zkušenostmi s vaší konkurencí jsem ztratil chuť a postupoval pouze podle nápovědy v emailech a telefonické podpory, která mě odkázala na vás.
Ovšem používat technickou podporu přes github s přístupem „Raiffeisenbank“ je smutné i na ČSOB. 
Pro příště bych se doporučoval rozhlédnout po konkurenci (třeba FIO) anebo alespoň zvážit nákup telefonu.

**Comment by ratajskym** [comment]
Děkuji za Vaše připomínky, nicméně podotýkám, že technická podpora funguje nejen přes github, ale i přes emaily a v určitých případech po telefonu.
