### ISSUE TITLE
Přechod do ostrého prostředí

### ISSUE THREAD

**Issue by Madla** [csob/paymentgateway#88]
Dobrý den,

možná blbá otázka, ale mohli by jste mi prosím vysvětlit první dva úkolu pro přechod do ostré verze platební brány?
Test komunikace - echo (GET)
Test komunikace - echo (POST)

Zaráží mně tu, že zákazník chce používat pouze metodu POST a nevidím, proč mám testovat i GET. Mohli by jste mi prosím k tomu dát další informace? 

Děkuji

PS: Ostatní úkolu jsem úspěšně splnil

**Comment by ratajskym** [comment]
Dobrý den, vyberte si metodu, kterou budete používat.
