### ISSUE TITLE
x-frame-options: deny  proč?

### ISSUE THREAD

**Issue by VitMichalek** [csob/paymentgateway#89]
Dobrý den, <b>10 let</b> máme platební bránu z povahy celého systému vloženou do iframe. Od včerejška zobrazujete v odpovědi voláni x-frame-options deny, což způsobuje nemožnost platit kartou v našem systému. Kvůli této neohlášené změně, jsme včera přišli o několik tisíc korun. Můžete to vrátit do původního stavu?

**Comment by Tomas-M** [comment]
Kde je dokumentace k iframe řešení? Ve wiki jsem to nenašel.

**Comment by VitMichalek** [comment]
iframe řešení není podporováno. Je nutné systém napojit na API

**Comment by Tomas-M** [comment]
alza.cz používá bránu ČSOB v iframu... tudíž to podporováno je.

**Comment by VitMichalek** [comment]
Tak to netuším. U nás se přešlo na nové API. Pracovníci banky se vyjádřili že v iframe to možné není a vyjímky dělat nebudou. Při našem volání do iframe byla odpověd z csob serveru s hlavickou x-frame-options deny což tuto možnost vylučuje.

**Comment by hanuss** [comment]
V novém release platebnní brány je již iframe podporován. Pilotně je nasazen právě ve spolupráci s alza.cz, nicméně dokumentace není veřejně dostupná. Uvolnění dokumentace pro konkrétní implementace bude v nejbližší době možné po dohodě s ČSOB (akceptace karet) - předpokladem bude smluvní / obchodní dohoda.
