### ISSUE TITLE
Migrace z GP Webpay a testovací platební brána

### ISSUE THREAD

**Issue by webczech** [csob/paymentgateway#9]
Na adrese níže uvádíte adresu platební brány. Předpokládám, že se jedná o produkční platební bránu. Chtěl bych se dotázat zda existuje nějaká testovací platební brána?

https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay

S klientem byla podepsána nová smlouva a byl mu poskytnut obecný postup pro implementaci, který mmj. obsahuje kroky "Generování testovacích klíčů pro integrační prostředí; Provedení testovacích transakcí; ...", takže předpokládám, že takto vygenerované klíče pro testovací prostředí nebudou v "produkčním prostřed" funkční.

**Comment by dmarek** [comment]
Kompletní dokumentace včetně popisu vlastního API, dostupných prostředí, generování klíčů apod je dostupná na https://github.com/csob/paymentgateway/wiki

**Comment by webczech** [comment]
Testovací platební brána má tedy stejnou adresu v legacy prostředí jako v řešení skrze nového API, nebo jsem něco přehlédl? Domnívám se, že veškeré informace, které jsou platné pro migraci z GP Webpay by měly být k dispozici v sekci "Přechod z brány GP Webpay".

**Comment by dmarek** [comment]
Máte pravdu, adresa na integrační prostředí pro legacy API v dokumentu uvedená není.

https://iplatebnibrana.csob.cz/pay/entry/merchant

Doplníme.

**Comment by webczech** [comment]
Děkuji.

**Comment by ratajskym** [comment]
Doplněno [zde](https://github.com/csob/paymentgateway/wiki/P%C5%99echod-z-ji%C5%BE-pou%C5%BE%C3%ADvan%C3%A9-platebn%C3%AD-br%C3%A1ny-GP-Webpay#4-testovac%C3%AD-prost%C5%99ed%C3%AD---vyzkou%C5%A1ejte-si-v%C5%A1e-nane%C4%8Disto)
