### ISSUE TITLE
Implementácia platobnej brány pre java web aplikáciu (JSF) bežiacej na serveri JBoss

### ISSUE THREAD

**Issue by z10032** [csob/paymentgateway#91]
Dobrý deň,
rád by som sa informoval ohľadom možností implementácie vašej platobnej brány ČSOB vo webovej aplikácii napísanej v programovacom jazyku JAVA (JDK 1.6) s použitím xhtml stránok založených na technológii JSF (JavaServerFaces). Táto aplikácia beží na aplikačnom serveri JBoss 6.
Jedná sa o aplikáciu v rámci nami vytvoreného stravovacieho portálu, ktorý obsahuje webový klient pre objednávanie zamestnaneckej stravy, pričom máme záujem o doplnenie platobnej brány z dôvodu možnosti dobíjania kreditu na stravu samotnými používateľmi.

Z adresy https://github.com/csob/paymentgateway/tree/master/eshop-integration (po novom https://github.com/csob/paymentgateway/tree/master/Integration%20Examples) som si stiahol zdrojové kódy pre integráciu platobného systému, samotná implementácia je však naprogramovaná v jazyku PHP, pričom v jazyku JAVA sú vytvorené generátory pre verejný a privátny kľúč a eAPI-v15-connector pre webovú službu (vyžaduje min. verziu JDK1.8), ktorý by sa zrejme dal použiť pri implementácii.

**Comment by dmarek** [comment]
eAPI-v15-connector je ukazkovy priklad, jak volat eAPI operace z Javy. Je tam zejmena ukazka toho, jak se podepisuji pozadavky a kontroluji podpisy odpovedi a komunikuje se serverem platebni brány (JSON formát v request/response apod). Pro provadeni crypto operaci je vyzadovana tato zavislost

```
<dependency>
	<groupId>org.bouncycastle</groupId>
	<artifactId>bcprov-jdk16</artifactId>
	<version>1.46</version>
</dependency>
```

ktera je pro kompatibilni s JDK 1.6

Pokud si zmenite v maven.xml nastaveni javy z 1.8 na 1.6, projekt jde zkompilovat.

```
<java.version>1.6</java.version>
```

Zkuste prosím se inspirovat tímto příkladem a provést integraci...

**Comment by dmarek** [comment]
dobry den, pokrocil jste? muzu tot issue/dotaz zavrit?

**Comment by z10032** [comment]
Dobrý deň. Túto otázku môžte uzavrieť. Po firemnej dohode zrejme pristúpime k PHP implementácii alebo budeme hľadať ešte iné riešenie.
