### ISSUE TITLE
Dlouhotrvající recurring platba

### ISSUE THREAD

**Issue by janlanger** [csob/paymentgateway#92]
Dokumentace:
> Volání operace payment/recurrent je synchronní, pokud je výsledek autorizace znám do 15 vteřin, vrací se v odpovědi jak stav platby, tak pokud je platba autorizována i autorizační kód. V případě, že autorizace trvá déle a nen íznám výsledek do 15 vteřin, vrátí se v odpovědi na payment/recurrent stav Platba probíhá (2) a obchodník má možnost následně zjišťovat výsledek autorizace pomocí volání payment/status.

Je nějaký způsob jak tento scénář otestovat proti integračnímu rozhraní? Případně neplánujete ho přidat?

**Comment by dmarek** [comment]
diky za namet, pro integracni prostredi doplnime tak, aby se toto chovani dalo nasimulovat (nejspis specialnim cislem karty)

**Comment by pepakriz** [comment]
:+1:

**Comment by pepakriz** [comment]
@dmarek Dobrý den. Nějaký progress ohledně možnosti testování tohoto usecase? Zajímalo by mě také, jestli je nutné čekat celých 15s, nebo si můžu dovolit nastavit nižší timeout a poté ověřovat status přes `payment/status`. Bohužel jakékoliv experimentování je třílení naslepo.

**Comment by dmarek** [comment]
diky za pripomenuti, pozadavek mame v pipeline ...

**Comment by dmarek** [comment]
od eAPI 1.6 vyřešeno rozdělením původní operace na dvě volání, a to `payment/oneclick/init` a `payment/oneclick/start`, druhá operace pouze nastartuje autorizaci, výsledek je nutné zjistit pomocí volání `payment/status`

**Comment by janlanger** [comment]
@dmarek eAPI 1.6 sice řeší některé problémy původní operace recurrent, ale teto podle mého názoru zrovna ne. Dokumentace uvádí že zpracování může trvat až 60 sec, ale v testovacím prostředí dostanu na první volání payment/status už výsledek platby.

Mohli byste to ještě zvážit, testování flow placení když proces trvá déle se nyní testuje dost komplikovaně.
