### ISSUE TITLE
Chybička ve WooCommerce pluginu

### ISSUE THREAD

**Issue by SumLord** [csob/paymentgateway#95]
Dobrý den,
v souboru start.php pluginu WooCommmerce chybí středník na konci řádky 50. Wordpress nemůže aktivovat plugin.
Díky za opravu, ale hlavně za plugin :-)

https://github.com/csob/paymentgateway/blob/master/WooCommerce%20Plugin/www/wp-content/plugins/WooCommerceMonetGateWay/start.php

**Comment by dmarek** [comment]
diky, opraveno
