### ISSUE TITLE
Chyba v řádku 51

### ISSUE THREAD

**Issue by fiorita** [csob/paymentgateway#96]
Dobrý den, Při pokusu o aktivaci Vašeho pluginu dostávám zprávu Plugin nemůže být aktivován, protože způsobil závažnou chybu. Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /www/doc/www.fiorita.cz/www/wp-content/plugins/WooCommerceMonetGateWay/start.php on line 51

**Comment by dmarek** [comment]
diky, chybicka se vloudila, opravili jsme chybejici strednik

**Comment by fiorita** [comment]
no a?

Mám stáhnout obnovenou verzi? Za jak dlouho se asi objeví na GitHubu?

2015-12-12 23:53 GMT+04:00 Daniel Marek <notifications@github.com>:

**Comment by dmarek** [comment]
ano, stahnete si novou verzi, opraveno v https://github.com/csob/paymentgateway/commit/6f955e6a326d977e53ddc91e663d88e78ec25a90
