### ISSUE TITLE
Inicilizace platby na platební bráně se nezdařila, nepodařilo se ověřit podpis odpovědi

### ISSUE THREAD

**Issue by fiorita** [csob/paymentgateway#97]
DObrý den

Při zkoušení platební brány došlo k chybě: Inicilizace platby na platební bráně se nezdařila, nepodařilo se ověřit podpis odpovědi

To sdělení se objevilo po tom co jsem tiskl tlačítko Objednat na stránce Pokladna (woocommerce e-shop) Nastavení pokladny jsou číslo obchodníka jak to mám od banky, jména souboů klíčů ve formátu rsa_(č.obchodníka).key nebo .pub respektive

Díky

**Comment by ratajskym** [comment]
Dobrý den, pro ověření odpovědi z platební brány je nutné použít veřejný klíč brány, nikoliv ten který jste si vygeneroval. Ke stažení [zde] (https://github.com/csob/paymentgateway/tree/master/keys)

**Comment by fiorita** [comment]
DObrý den, teď to funguje, díky moc!!!
Teď musím vyzkoušet testovací karty...
