### ISSUE TITLE
WooCommerce - podněty

### ISSUE THREAD

**Issue by SumLord** [csob/paymentgateway#98]
Dobrý den,
v pluginu pro WooCommerce lze do pole "Název první položky košíku" zadat velmi dlouhý text, ale brána vezme maximálně 20 znaků, jinak se ani nenačte a vrátí chybovou hlášku "Invalid length of cart/name parameter". Zabralo mi dost času zjistit, co daná hláška znamená (není ani uvedena na wiki) a kde jsem vlastně udělal chybu. Pokud chcete ušetřit čas dalším zájemcům o plugin, doporučil bych omezit vstup zmíněného pole.
A druhá věc, v souboru start.php na řádku 50 by bylo lepší použít 'wpurl' místo 'url' (https://codex.wordpress.org/Function_Reference/get_bloginfo) kvůli přemístěným instalacím (https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory), i když je to jen kvůli jedné ikonce.
Snad to pomůže někomu dalšímu a nebudete to brát jako hnidopišství, za plugin jsem opravdu rád.
Ať se daří

**Comment by ozaoral** [comment]
Dobré ráno, díky za oba podněty, to není hnidopišství, ale vylepšení. Název košíku jde hned do dokumentace, omezení jeho délky a wpurl vylepšíme v dohledné době. 
Ještě jednou díky!

**Comment by Musilda** [comment]
Pokud mohu mít také podnět, tak global $woocommerce; je zavržený způsob, zůstává to tam pouze kvůli zpětné kompatibilitě. 
K datům by se mělo přistupovat:
$customer = WC()->customer;
místo
$customer = $woocommerce->customer;
