### ISSUE TITLE
Nerozhodnutelnost recurrent transakce 

### ISSUE THREAD

**Issue by KEYELEMENTS** [csob/paymentgateway#99]
Zdravím, 
mám dotaz k metodě pro opakované platby
payment/recurrent  
volani je synchronní a je pouze 1 krokové. Co když se nedozvíme odpověď? Jak zjistíme v jakém stavu je transakce vzniklá na základě tohoto volání, když neznáme payId? 

Modelový případ:
1. zavoláme recurrent, 
2a - server transakci provedl a vrací výsledek...
2b - spojení spadne (např. network chyba) ještě před příchodem odpovědi. Neznáme tedy payId.

Tedy volat status nemůžeme neb nemáme payId.  Nemůžeme rozhodnout na úrovni aplikace, ani že platba proběhla, ani že neproběhla... něco mi uniklo nebo jak to řešit?

Děkuji

**Comment by dmarek** [comment]
Máte pravdu, že díky synchronímu přistupu není případ 2b rozumně řešitelný. Zvažujeme do budoucna rozdělení buď na dvě operace (init a pak vlastní provedení recurrent operace) anebo přidání nové operace "získání stavu posledních recurrent trx v daném časovém období pro konkrétního obchodníka".

**Comment by dmarek** [comment]
v aktualne zverejnene verzi eAPI 1.6 je puvodni `payment/recurrent` prepracovana na dvoukrokovou `payment/oneclick/init` a `payment/oneclick/start`, viz take https://github.com/csob/paymentgateway/wiki/eAPI-1.6
